### ISSUE TITLE
no online docs for libmdaxdr

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/mdanalysis#1003]
The sphinx docs do not contain any docs for `libmdaxdr` (the interface to the Gromacs XDR routines to read TRR and XTC files). We used to have docs for libxdr2 and that was useful for development work and pointing people to some of the nitty-gritty. It would be good to have docs for the underlying xdr reader/writer code. 

The docs also don't mention anywhere the frame index files. It should be documented somewhere when a reader writes to the directory and under which circumstances the frame indices are rebuilt.

MDAnalysis 0.16.0-dev0

**Comment by kain88-de** [comment]
@orbeckst did you fix this as well in your recent docs fixes?

**Comment by orbeckst** [comment]
No (as far as I remember), sorry, wasn't on my radar.

**Comment by kain88-de** [comment]
No Problem. This would need it's own rst file to show up right?

**Comment by orbeckst** [comment]
Yes, that's typically how we do it: just a stub file with
```rest
.. automodule: MDAnalysis.lib.formats.libmdaxdr
   :members:
```
(or leave out `:members:` if you write the docs explicitly. You need to make sure that your module has a proper heading for a table of contents.) I am not 100% sure how it works with cython. With SWIG there were some tricks required to get docs in, hopefully it is easier with cython.
