### ISSUE TITLE
increase code coverage in PSA

### ISSUE THREAD

**Issue by jdetle** [MDAnalysis/mdanalysis#1006]
Hi all,
One issue with code coverage in PSA is the amount of code dedicated to plotting the results of the path similarity analysis. I'd like to get people's opinions on whether this code should exist to as is, or if we should consider moving it to an example notebook outside of the class. In my limited experience with the analysis modules, it seems like the place for demonstrating how to aggregate and plot the data should be documentation, and not the actual code. There are around 300/1925 lines dedicated to plotting in the PSA module.

**Comment by tylerjereddy** [comment]
I've been working on increasing coverage of this module. I think there are algorithm issues with some of the path code (see https://github.com/MDAnalysis/mdanalysis/pull/1005), but I've generally been able to deal with plotting-related coverage by writing unit tests that check for return of a `matplotlib` object type in i.e., @richardjgowers analysis module. The latter tests don't really check for the correctness of the plot, but if all the number crunching code is also unit tested, that may be ok.

And the streamline visualization code I contributed does nothing but plot from an enduser standpoint, so I think it can be ok.

**Comment by orbeckst** [comment]
Just adding context: The issued in PR #1005 is a documentation issue, not a bug as far as I can tell, but @sseyler should be able to clear any remaining doubts.

The plotting in PSA is pretty complicated and it is a good thing to give users some working examples. Just test for returning a matplotlib object as @tylerjereddy said.

**Comment by kain88-de** [comment]
we can also test the actual image. When we save a reference image it should be possible to get the matplotlib image as a bitmap that we can compare to a stored reference image.

**Comment by jdetle** [comment]
^ Heh. Thats kind of one of those _letter of the law_ vs _spirit of the law_ sort of things.

**Comment by orbeckst** [comment]
@sseyler can you please have a look and comment? Then we can decide what to do – possibly add more tests so that the code is covered. Our [guidelines](https://github.com/MDAnalysis/mdanalysis/wiki/Style-Guide#tests-for-mdanalysisanalysis) say that analysis code must have **at least 70% coverage** or code is moved to `MDAnalysis.analysis.legacy`.

**Comment by orbeckst** [comment]
Ping @sseyler

**Comment by sseyler** [comment]
I'll get on that starting tomorrow! (I actually talked to Taylor Colburn today about helping to update the PSA code and contributing on GitHub, as he's also found some issues and points of improvement.)

**Comment by orbeckst** [comment]
Once 1.0 comes around, coverage of PSA needs to be [up to our standards](https://github.com/MDAnalysis/mdanalysis/wiki/Style-Guide#tests-for-mdanalysisanalysis) and have ≥ 70% code coverage (more is obviously better).

**Comment by orbeckst** [comment]
@sseyler if you can convince @tcolburn to write some tests then that would be awesome.

**Comment by sseyler** [comment]
@orbeckst 

Update: I gave Taylor the full overview today so he has most of what's needed to start writing tests for PSA (git, github + PRs, virtualenvs + editable installs, unit testing + pytest, etc.). Hopefully he (and I) will get some more tests done this week.

**Comment by orbeckst** [comment]
Ping @sseyler and @tcolburn ...
