### ISSUE TITLE
Order of fragments and their atoms

### ISSUE THREAD

**Issue by mnmelo** [MDAnalysis/mdanalysis#1007]
`u.fragments` does not currently maintain fragment ordering between invocations: if I reload `u` there is no guarantee I'll get the same fragment order.

Furthermore in each fragment the atom order, while consistent between invocations, is not always monotonic.

I propose to make this intuitive and return fragments ordered by the index of their first atoms, and also make fragment atoms properly ordered by index.

The tone of this bug report does not reflect the amount of grief I got over the last couple of days because I made wrong assumptions on fragment/atom order (_\*punches screen at 5:30AM\*_).

**Comment by richardjgowers** [comment]
This sounds like an issue with using sets to make the fragments.  The fix should just be calling `sorted` when turning the sets into lists, and again sorting the AtomGroups based on the 0th atom. 

https://github.com/MDAnalysis/mdanalysis/blob/develop/package/MDAnalysis/core/AtomGroup.py#L4568

**Comment by jbarnoud** [comment]
I'm on it.
