### ISSUE TITLE
 problems for geometric selection command 'prop'

### ISSUE THREAD

**Issue by tpan1039** [MDAnalysis/mdanalysis#1009]
I used the keyword 'prop' to select atoms within a range of absolute coordinate.
But it showed me error. I have no idea about this error, I just typed the command as the online documentation says. Could someone help me ?
### Code to I used:

import MDAnalysis as md
u=md.Universe('OW_2us.pdb')
sel=u.select_atoms("prop 1<=x")
### Error message:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/MDAnalysis/core/AtomGroup.py", line 4922, in select_atoms
    return self.atoms.select_atoms(sel, *othersel, **selgroups)
  File "/usr/local/lib/python2.7/dist-packages/MDAnalysis/core/AtomGroup.py", line 3310, in select_atoms
    atomgrp = Selection.Parser.parse(selstr, selgroups).apply(self)
  File "/usr/local/lib/python2.7/dist-packages/MDAnalysis/core/Selection.py", line 1000, in parse
    parsetree = self.parse_expression(0)
  File "/usr/local/lib/python2.7/dist-packages/MDAnalysis/core/Selection.py", line 1008, in parse_expression
    exp1 = self._parse_subexp()
  File "/usr/local/lib/python2.7/dist-packages/MDAnalysis/core/Selection.py", line 1026, in _parse_subexp
    return _SELECTIONDICT[op](self, self.tokens)
  File "/usr/local/lib/python2.7/dist-packages/MDAnalysis/core/Selection.py", line 839, in __init__
    self.value = float(tokens.popleft())
IndexError: pop from an empty deque
```
### currently version of mdanalysis:

0.15.0

....

```


```

**Comment by jbarnoud** [comment]
I could reproduce the error. The parser does not like the property to be on the right on the operator. It should work if you inverse your test:

```python
import MDAnalysis as md
u=md.Universe('OW_2us.pdb')
sel=u.select_atoms("prop x>=1")
```

On our side, we could have a friendlier error message.

**Comment by tpan1039** [comment]
OK, I have tried different situations. In some case, like "prop x>=1", it complains "could not convert string to float". In other case, like "prop 1<=x<2", it shows "pop from an empty deque". The only case that works well is "prop x >= 1", or "prop x >= 1 and prop x < 2". There must be a space between  the 'x' and the comparing operator. And we can not use two operators together, must use 'and' to connect them.
I think this grammar standard is too serious, and little people know it. Can it be a bug ?

**Comment by richardjgowers** [comment]
Ok I think part of this might be that the parser splits around whitespace, so `prop x <= 5` works, but `prop x<=5` doesn't. (notice the spaces)

For now, makes sure there's **always** spaces around the `<=` characters.  This should be fixed by making the splitting around these tokens smarter...

**Comment by richardjgowers** [comment]
And as for `prop 1 <= x < 2`, this won't work currently, the value after `prop` must be the property that will be compared against (eg `x` or `mass` etc), so you can't chain the comparisons.  Might be a nice feature, but not sure how difficult it will be to implement.
