### ISSUE TITLE
363 - atoms coming unsorted when accessed via residue or segment group

### ISSUE THREAD

**Issue by khuston** [MDAnalysis/mdanalysis#1014]
### Expected behaviour

`u.residues.atoms` and `u.segments.atoms` have same order as `u.atoms`.
### Actual behaviour

`u.residues.atoms` and `u.segments.atoms` don't have same order as `u.atoms`. Residue/segment order is correct, but atom order within each residue is not.
### Code to reproduce the behaviour

``` python
import MDAnalysis as mda
import numpy as np
u = mda.Universe('/Users/khuston/mdanalysis/testsuite/MDAnalysisTests/data/adk_open.pdb')
print('Matching indices: {}'.format(np.sum(u.atoms.indices == u.residues.atoms.indices)))
print('Total indices: {}'.format(len(u.atoms.indices)))

```

Output:

```
Matching indices: 14
Total indices: 3341
```
### Currently version of MDAnalysis:

0.15.1-dev0 -- I just pulled from mdanalysis/issue-363

The atoms can be easily `sorted()`, but I'm not sure the best place for that.

**Comment by richardjgowers** [comment]
Thanks @khuston .  Can you add a version of your code snippet to the [parser base tests](https://github.com/MDAnalysis/mdanalysis/blob/issue-363/testsuite/MDAnalysisTests/topology/base.py#L23) as a start?  Also FYI it's [Hacktoberfest](https://hacktoberfest.digitalocean.com/)!

**Comment by richardjgowers** [comment]
fixed now!

```python
In [2]: u = mda.Universe('adk_open.pdb')

In [3]: all(u.atoms.indices == u.residues.atoms.indices)
Out[3]: True
```
