### ISSUE TITLE
ag.rotate should rotate around selection center of mass/geometry

### ISSUE THREAD

**Issue by kain88-de** [MDAnalysis/mdanalysis#1022]
### Expected behaviour

If I do `ag.rotate(R)` I would expect that I can rotate the protein I selected around it's center of mass/geometry.  I would propose we add a kwarg `origin` for this. This point determines the origin or the rotation and we default to the center of geometry (or lab for backwards compatibility)

``` python
def rotate(self, R, origin='cog'):
    if origin=='cog':
        point = self.center_of_geometry()
    elif origin=='com':
        point = self.center_of_mass()
    elif origin=='lab':
        point = np.zeros(3)

    self.translate(-point)
    # do rotation
    self.translate(point)
```
### Actual behaviour

The center of the rotation is the center of the coordinate system. This means instead of just an internal rotation I can rotate protein in my lab system to another place.
### Currently version of MDAnalysis:

(run `python -c "import MDAnalysis as mda; print(mda.__version__)"`)
0.16.0dev

**Comment by kain88-de** [comment]
We could also allow to give an arbitrary origin to this name selection

**Comment by richardjgowers** [comment]
@kain88-de there is also currently `rotateby` which looks like it does something like what you want?

**Comment by kain88-de** [comment]
But it doesn't accept a rotation/transformation matrix. Besides I spend today hours until I remembered this fact about rotate.  Then that `rotate` and `rotateby` behave differently isn't good since one accepts a matrix and the other an axis and angle, plus origin of rotation, even though the docs say they do exactly the same thing.

**Comment by kain88-de** [comment]
I noticed today (after around one hour of debugging) that this change broke `alignto` and `AlignTraj` when we align an a selection instead of the whole protein. The problem is that `align.rotation_matrix` returns a matrix that assume the rotation is done around a point centered at `(0,0,0)` in the lab-system. Which was the old behavior when `rotate` is used. Since this is a very subtle change which can break existing user code in non obvious ways, I would revert this change and have `rotate` use `(0,0,0)` as a center for the rotation again. This means that rotate and rotateby have slightly different default behavior but I rather live with that for historical reasons then break lots of code that is used.

I will also include a new alignment test that shows the failure this change introduced.
