### ISSUE TITLE
transfer_to_memory should accept start,stop,step parameters

### ISSUE THREAD

**Issue by kain88-de** [MDAnalysis/mdanalysis#1030]
### Expected behaviour

I should be able to do `u.transfer_to_memory(start=10, stop=100, step=2)`. That would be nice because the iteration kwargs then are consistent with the kwargs in python and our analysis classes.

E.g. `u.transfer_to_memory(start=4, step=4, stop=40)` would only load 9 frames from the original trajectory.

### Actual behaviour

This results in a Argument Error since the only accepted kwarg is `frame_interval`.

**Comment by pratyushprakash** [comment]
Hi, can I take this up?

**Comment by kain88-de** [comment]
Yes you can submit a PR for this.

**Comment by utkbansal** [comment]
I'd like to work on this. Just to be clear, in `u.transfer_to_memory(start=4, step=4, stop=40)` I just have to add support for `start` and `stop` parameters. Right?

**Comment by richardjgowers** [comment]
@utkbansal rename `frame_interval` to `step` (it's not been released yet, so we don't have to deprecate etc) and add `start` and `stop`.  Make sure that the defaults are all `None` (including `frame_interval`) else backwards iteration etc won't work.  Then do a `git grep 'frame_interval'` and change references to step

**Comment by utkbansal** [comment]
@richardjgowers Thanks! I'm working on it. 😄
