### ISSUE TITLE
Helper class `PDBToBinaryTraj` in psa module uses deprecated syntax

### ISSUE THREAD

**Issue by sseyler** [MDAnalysis/mdanalysis#1035]
### Current behaviour

The helper class  `PDBToBinaryTraj` uses a deprecated "num atoms" attribute to get the number of atoms from a trajectory/timestep (e.g. `MDAnalysis.Universe.trajectory.numatoms`). It also uses `MDAnalysis.Writer.close_trajectory()` instead of the updated syntax (i.e. `close()`).

### Corrected behaviour

`PDBToBinaryTraj` should use the updated syntax to get the number of atoms from a trajectory/timestep (e.g. `MDAnalysis.Universe.trajectory.n_atoms`). It should also use `MDAnalysis.Writer.close()` (instead of `close_trajectory()`).

### Impact of the problem

This issue isn't crippling single `PDBToBinaryTraj` is a non-essential convenience class for converting PDB-based (multiframe) trajectories to DCD format (by default). This is for the purpose of being able to read trajectories faster, preferably in a binary format; as many path-generating servers produce output as many separate PDB files or a single multiframe PDB, it becomes costly to re-read these non-binary trajectories when doing exploratory analysis.

### Other changes that should be made to the code

The `PDBToBinaryTraj` class currently writes a PDB topology file using the first frame it reads from the (multiframe) PDB from the universe it's fed. Instead, it should write both the new topology and the corresponding binary trajectory _only after_ `PDBToBinaryTraj.convert()` is called to make its behavior more predictable.

**Comment by kain88-de** [comment]
Wouldn't it make more sense now to switch to the memory reader for faster 'reading'?

**Comment by sseyler** [comment]
I'm completely open to better ideas... the only real purpose of the class was to make exploratory analysis faster—just hand it a multiframe PDB file and boom, you have a DCD and a matching PDB topology file. But the class itself is, of course, rather out of place in the module as it is.

**Comment by kain88-de** [comment]
Well a more common `trajectory.write` could be added similar to the `atomgroup.write` method.

```python
u.trajectory.write('foo.dcd')
```

That would fit in more with the general approach and be quick code to convert trajectory formats.

**Comment by sseyler** [comment]
I like that approach. It would also reduce bloat in the PSA module.

**Comment by orbeckst** [comment]
As a quick band-aid solution you could just replace the deprecated code.

You could then raise an issue for something like `u.trajectory.write('foo.dcd')` (which looks neat) or look into `MemoryReader` and refactor without having to worry that the existing code breaks under 0.16.0.

**Comment by kain88-de** [comment]
@sseyler check if the MemoryReader works for you examples. If it does just change the docs and remove PDBtoBinrary class. We can then raise a new issue to add a write method to the trajectory reader.

**Comment by sseyler** [comment]
@kain88-de Okay. I already wrote code yesterday that _should_ fix the reader and then also coded some unit tests, but I'll check the MemoryReader before I do anything.

**Comment by sseyler** [comment]
Looks like `MemoryReader` does most of everything that'd be needed for PSA examples. I removed `PDBToBinaryTraj` + docs and I'll set up a PR. I'm still onboard with adding a write method to the trajectory reader too and I'll raise an issue if I have time tomorrow.
