### ISSUE TITLE
transfer_to_memory doesn't copy dynamics dimension information

### ISSUE THREAD

**Issue by kain88-de** [MDAnalysis/mdanalysis#1041]
### Expected behaviour

If I load a trajectory from an NPT simulation into memory I would expect that the memory reader also copies the dimension information for every frame
### Actual behaviour

Only the information from the first frame is used.

**Comment by orbeckst** [comment]
I consider this a bug and because `ts.dimensions` is a top level attribute of `Timestep` it should also be copied.

However, it raises the question if the MemoryReader should also be aware of other per-timestep information – aren't we storing these data nowadays in a `ts.data` dict?

**Comment by kain88-de** [comment]
The data dict is reader specific. I'm OK if that isn't copied. But other available top level attributes should be copied if available.

**Comment by jbarnoud** [comment]
Do we have an equivalent of `Reader.timeseries` for the box shape? Fixing this is not difficult, but I have to iterate through the trajectory even when the faster `timeseries` is available.

**Comment by kain88-de** [comment]
We don't have an equivalent. But libdcd reader does return it as well. I wouldn't mind adding a method that can also read the box information for all frames and returns them as an array. We should think if we want to add this to `timeseries` though to avoid iterating several times over a possibly large trajectory.

**Comment by orbeckst** [comment]
I don't think we have but we should. Ideally you'd also get the additional time step information such as lambda or the more complicated stuff in some other formats such as trz (or tng?). Basically, it would be good to start with a data structure that allows some flexibility depending on available per frame data. E.g. a dataframe like array with named fields. We could start with a slow Python implementation in the base class and upgrade readers as we go along. 

Ideally you'd want to do coordinates and other timestep data together, of course. 

--
Oliver Beckstein
email: orbeckst@gmail.com

**Comment by jbarnoud** [comment]
If libdcd has it, then it would make sense to expose it. Not much of a priority, but convenient at least in that context.

**Comment by kain88-de** [comment]
Btw xarray sounds like the right package for a data format that such a universal time series should return.

**Comment by orbeckst** [comment]
@jbarnoud if you fix this issue then we have dealt with all [defect for 0.17](https://github.com/MDAnalysis/mdanalysis/issues?utf8=%E2%9C%93&q=is%3Aopen%20is%3Aissue%20label%3Adefect%20milestone%3A0.17.0%20) issues.

**Comment by orbeckst** [comment]
I'd really like this one to work... but it looks as if the chances for this getting fixed in 0.17.0 are slim. It is a bug fix so this can always go into a 0.17.x.

Feeback from anyone working on this issue would be welcome.
