### ISSUE TITLE
Use pylint during the CI

### ISSUE THREAD

**Issue by kain88-de** [MDAnalysis/mdanalysis#1044]
I found this [blog post](https://codewithoutrules.com/2016/10/19/pylint/) talking about the value of [pylint](https://pylint.readthedocs.io/en/latest/index.html) as a static analyzer to find bugs for us. For MDAnalysis it throws a tone of warnings but I think using only a handful of warnings/errors will help us to improve the code. For example i will mention all the cases where we should do `from __future__ import division` in files to ensure that division behaves the same in python 2 and 3. 

I think once we really go for python 3 compatibility this might be a good tool to help.

**Comment by richardjgowers** [comment]
Yeah I'm in favour of this.  I do think we'd need to do a gradual switch on to avoid lots of annoying errors that aren't errors (we had this a lot with QC).

**Comment by kain88-de** [comment]
I'll upload something today.
