### ISSUE TITLE
encore docs are not included in online docs

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/mdanalysis#1047]
### Expected behaviour

I should be able to find documentation for `MDAnalysis.analysis.encore` somewhere at http://devdocs.mdanalysis.org/
### Actual behaviour

No encore-related docs are visible.
### Currently version of MDAnalysis:
- Release:  0.16.0-dev0
- Date: October 19, 2016

**Comment by richardjgowers** [comment]
The RST stubs aren't in `package/doc/sphinx/source/documentation_pages`
