### ISSUE TITLE
mda.Universe(topology, array_like) should load into a MemoryReader

### ISSUE THREAD

**Issue by kain88-de** [MDAnalysis/mdanalysis#1049]
### Expected behaviour

Using a `u = mda.Universe(PSF, np.random.uniform(size=(...)))` should just work like with any other reader.
### Actual behaviour

I get a error that the fileformat can't be determined

**Comment by richardjgowers** [comment]
If you do `format='memory'` this will work.  This needs a hack into `get_reader_for` which makes it return the MemoryReader if the "filename" is actually a np array

**Comment by orbeckst** [comment]
@richardjgowers : Using `format="memory"` does not work (on develop pre-363) because we haven't special-cased it in `util.guess_format(filename)` – it is assumed to be an array for the CHAIN reader:
```python
u0 = mda.Universe(PSF, np.random.uniform(size=(u0.atoms.n_atoms, 100, 3)), format="memory")
```
fails with
```
...

/Volumes/Data/oliver/Biop/Library/python/mdanalysis/package/MDAnalysis/lib/util.pyc in guess_format(filename)
    855         # and list of filenames is handled by ChainReader
    856         format = (format_from_filename_extension(filename)
--> 857                   if not iterable(filename) else 'CHAIN')
    858
    859     return format.upper()

...

TypeError: Cannot determine file format for file '0.749369681291'.
           You can set the format explicitly with 'Universe(..., format=FORMAT)'.
```

Explicit `MemoryReader` works:
```python
>>> import MDAnalysis as mda; from MDAnalysisTests.datafiles import PSF
>>> from MDAnalysis.coordinates.memory import MemoryReader

>>> u0 = mda.Universe(PSF, np.random.uniform(size=(u0.atoms.n_atoms, 100, 3)), format=MemoryReader)
>>> print(u0.trajectory)
<MemoryReader with 100 frames of 3341 atoms>
```

**Comment by orbeckst** [comment]
@richardjgowers – does `format = "memory"` works in #363 because you do the fancy autoregistering of readers?

**Comment by richardjgowers** [comment]
Nah this won't be any different in 363 afaik.  I thought `format=` would override everything, but it seems that CHAIN has higher precedence.

**Comment by orbeckst** [comment]
Ok, then we should fix this to be consistent. 

--
Oliver Beckstein
email: orbeckst@gmail.com
