### ISSUE TITLE
AlignTraj should have in_memory option

### ISSUE THREAD

**Issue by wouterboomsma** [MDAnalysis/mdanalysis#1059]
### Expected behaviour
With the introduction of MemoryReader in 0.16, `rms_fit_trj` gained an in_memory option, which makes it possible to do in-place (in-memory) alignment. `AlignTraj` should have the same option.

### Currently version of MDAnalysis:
0.16.0-dev0

**Comment by orbeckst** [comment]
This option should be added for 0.16.0 because `rms_fit_trj()` is being deprecated.
