### ISSUE TITLE
Python 3.5 through Miniconda in Windows10 visual studio 2015

### ISSUE THREAD

**Issue by JimSEOW** [MDAnalysis/mdanalysis#1071]
### Actual behaviour
![image](https://cloud.githubusercontent.com/assets/8244633/20238625/fc35c96a-a8ef-11e6-8c9e-5727686a5017.png)

![image](https://cloud.githubusercontent.com/assets/8244633/20238638/54150218-a8f0-11e6-8ec9-1d789175c6b0.png)

[PyCObject_AsVoidPtr removed from python 3.2?](https://mail.python.org/pipermail/python-dev/2011-March/108882.html)

However
https://github.com/MDAnalysis/mdanalysis/issues/808

**Comment by richardjgowers** [comment]
Hey, thanks for the report. 

What version of mdanalysis is this from?

**Comment by JimSEOW** [comment]
git clone it.

Here is more information to replace 
![image](https://cloud.githubusercontent.com/assets/8244633/20239054/4849171e-a8f8-11e6-9d65-30d2e945c88d.png)

http://omz-software.com/pythonista/docs/howto/cporting.html

**Comment by orbeckst** [comment]
Related in a broader sense to making it work under Windows #450.

**Comment by kain88-de** [comment]
This exact error won't exist anymore after #929 with the cython port. But the cython port won't run out of box on windows. To have the cython port also run on windows you will need to add a conditional compiled definition for the `fio_fd` type. 

The cython port will earliest be included in 0.17 though.
