### ISSUE TITLE
Add option to keep original Atom IDs when writing PDB

### ISSUE THREAD

**Issue by kain88-de** [MDAnalysis/mdanalysis#1072]
### Expected behaviour

When I use `ag.write('foo.pdb')` I expect the atom ids to be the same as in the AtomGroup

### Actual behaviour

The atom ids's always start from 0.

### Code to reproduce the behaviour

``` python
import MDAnalysis as mda
from MDAnalysisTests.datafiles import PDB

u = mda.Universe(PDB)
bb = u.select_atoms('backbone')
bb.write('foo.pdb')
u2 = mda.Universe('foo.pdb')
assert np.all(bb.ids == u2.atoms.ids)
```

### Currently version of MDAnalysis:
(run `python -c "import MDAnalysis as mda; print(mda.__version__)"`)
develop branch

**Comment by orbeckst** [comment]
One can make a case that the AtomIDs are just sequential numbers in the PDB format and a new PDB file is correctly written as long as the IDs start at 1 and are consecutively numbered (AtomIDs should also start with 1 in PDB files, not with 0). In fact, in many cases that might actually be desired behavior, e.g., if one wants to take only, say chain B of a PDB file as input for further simulations.

On the other hand, I also see use cases for wanting to remember the atomids for selections.

Perhaps the PDBWriter should get a flag, like "keep_atomids", "keep_resids", etc? Or how would you be able to get continuous numbering in a PDB if you implemented the "keep old atomids"?

**Comment by tylerjereddy** [comment]
+1 for eventually having the increased flexibility, as a heavy user of MDAnalysis for system building / topology manipulation purposes.

**Comment by kain88-de** [comment]
I can't find anything in the PDB standard that the atom numbers have to be continuous.

**Comment by orbeckst** [comment]
The [PDB FAQ](http://deposit.rcsb.org/format-faq-v1.html) (from 2001) implies that *serial* records start at 1; it sounds to me that they should be continuous ("consecutive" as written below) but admittedly this not said anywhere.

* Q. How are models in NMR ensembles organized in PDB entries?
*  A.	In older NMR files the atom serial numbers were consecutive across all models in the entry. Owing to limitations in the field width for the atom serial number, this practice resulted in some ensembles being divided among multiple PDB entries. With entries processed since February 1999, the atom serial number is reset to 1 at the beginning of each model thereby allowing the full ensemble to be included within a single PDB entry.

-----

You could try to run a PDB file with discontinuous serials through the PDB deposit validation server and see it if complains (although you probably also need structure factors and what not...).

Or ask an expert such as @arose .... (I asked on twitter https://twitter.com/orbeckst/status/801234933356195841 in case anyone else is interested).

**Comment by kain88-de** [comment]
Sounds like they should be numbered in serial starting from 1 if I want to create a PDB to be added to the official PDB. But for normal system building both should be fine.

**Comment by arose** [comment]
So, it is a convention: files from the archive go from 1 to the number of coordinates for mmCIF files and for PDB files to restart from 1 for each model.

**Comment by orbeckst** [comment]
Thank you, much appreciated.

**Comment by kain88-de** [comment]
OK then we keep the current default of consecutive atom numbers starting at 1 but also add a new kwarg to keep the atomid if people like to do that.

**Comment by orbeckst** [comment]
Sounds Good!

--
Oliver Beckstein
email: orbeckst@gmail.com

**Comment by dotsdl** [comment]
Yeah I think I agree with the philosophy that for writers we do whatever needs to be done with topology attributes to match the standards/customs/idiosyncracies of the format we're serializing to. This is analogous to the philosophy we use for parsing topologies, but in the reverse direction: we take what's present and try to make reasonable choices for each parser for what the contents of the file mean in terms of the MDAnalysis topology system.

If someone wants to hold on to all of the contents of their Topology as it is, they'll need to use something like JSON serialization (#643).

**Comment by richardjgowers** [comment]
As a note for whenever this gets picked up next.  The atom ids need to get remapped in both the ATOM list, as well as the CONECT list.

**Comment by mdpoleto** [comment]
Hi,

I stumbled upon this exactly because I need a subset of atoms for a PLUMED script. The flag is working fine, but I believe `reindex=False` is yielding a 0-based list of atom IDs (I'm using v2.4.3) 

```
u = mda.Universe(psf,crd)
u.add_TopologyAttr("tempfactors")
u.add_TopologyAttr("occupancies")

center = u.select_atoms("resid 1")
center.write('reference.pdb',` reindex=False)
```

gives me this:

```
TITLE     MDANALYSIS FRAME 0: Created by PDBWriter
CRYST1    1.000    1.000    1.000  90.00  90.00  90.00 P 1           1
REMARK     285 UNITARY VALUES FOR THE UNIT CELL AUTOMATICALLY SET
REMARK     285 BY MDANALYSIS PDBWRITER BECAUSE UNIT CELL INFORMATION
REMARK     285 WAS MISSING.
REMARK     285 PROTEIN DATA BANK CONVENTIONS REQUIRE THAT
REMARK     285 CRYST1 RECORD IS INCLUDED, BUT THE VALUES ON
REMARK     285 THIS RECORD ARE MEANINGLESS.
ATOM      0  O1  LIG X   1     -45.259  24.026 -17.998  0.00  0.00      H001
ATOM      1  CA  LIG X   1     -45.283  23.944 -19.445  0.00  0.00      H001
ATOM      2  HA1 LIG X   1     -44.881  24.872 -19.907  0.00  0.00      H001
ATOM      3  HA2 LIG X   1     -46.340  23.835 -19.776  0.00  0.00      H001
```
