### ISSUE TITLE
uninitialized variables

### ISSUE THREAD

**Issue by alinelena** [MDAnalysis/mdanalysis#1075]
Hi,

i try to package mdanalysis here... 
https://build.opensuse.org/package/live_build_log/home:ealin:physics/python3-MDAnalysis/openSUSE_Tumbleweed/x86_64
rpmlint complains about few things related to some c code.
[   42s] I: Program is using uninitialized variables.
[   42s]    Note the difference between "is used" and "may be used"
[   42s] W: python3-MDAnalysis uninitialized-variable MDAnalysis/lib/formats/src/xdrfile_trr.c:414
[   42s] E: python3-MDAnalysis 64bit-portability-issue MDAnalysis/coordinates/dcdtimeseries.c:1570
[   42s] E: python3-MDAnalysis 64bit-portability-issue MDAnalysis/coordinates/src/dcd.c:96, 117, 127, 282, 388, 409
[   42s] 
[   42s] I: Program returns random data in a function
[   42s] E: python3-MDAnalysis no-return-in-nonvoid-function MDAnalysis/coordinates/src/dcd.c:945
[   42s] 
[   42s] I: Program returns random data in a function
[   42s] E: python3-MDAnalysis no-return-in-nonvoid-function MDAnalysis/coordinates/src/dcd.c:945
[   42s] 

would be nice if can be fixed.

Alin

### Code to reproduce the behaviour

``` python
import MDAnalysis as mda

u = mda.Universe(top, trj)

....

```

### Currently version of MDAnalysis:
(run `python -c "import MDAnalysis as mda; print(mda.__version__)"`)

**Comment by orbeckst** [comment]
I see "python3" in the log – are you trying to build a Python 3 package? Release 0.15.0 is not supported under python 3, only python 2.7. Py3 support is in the works #260 and the code that you flagged is one of the center pieces that need to be upgraded.

**Comment by kain88-de** [comment]
Yeah but that doesn't fix the uninitialized variables. The errors in the xtc library are not from us and all the DCD errors will be fixed in the future due to the cython port.

**Comment by alinelena** [comment]
On Thursday, 17 November 2016 00:25:17 GMT Max Linke wrote:
> Yeah but that doesn't fix the uninitialized variables. The errors in the xtc
> library are not from us and all the DCD errors will be fixed in the future
> due to the cython port.
I build both the python2 worked without issues. 

Alin

-- 
______________________________________________________________________
Dr. Alin Marin ELENA
http://alin.elena.space
______________________________________________________________________

**Comment by kain88-de** [comment]
Ah ok the build doesn't stop for uninitialized warnings. Then the other issues will go away after we fully support python3, that will likely hit around 0.17.
