### ISSUE TITLE
new topology docs

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/mdanalysis#1078]
### Expected behaviour
The philosophy behind the new topology system #363 should be outlined. 
- [ ] docs
- [ ] CHANGELOG

### Actual behaviour
At the moment, PR #1077 only removed obviously outdated comments in the docs in `topology/__init__.py`. 

See also TODO in `core/topology.py` and the structure `doc/sphinx/documentation_pages/core_module.rst`.

~~Perhaps it would be worthwhile making this a proper rst file under `doc/sphinx` instead of cramming all the docs into a `__init__.py` etc (?).~~

**Comment by orbeckst** [comment]
`git grep TODO` shows a few more
* package/MDAnalysis/core/topologyattrs.py:# TODO: update docs to property doc
* package/MDAnalysis/core/topology.py:# TODO Notes:
* package/doc/sphinx/source/documentation_pages/overview.rst:.. TODO: more about philosophy etc... copy and paste from paper (more than just topology)

**Comment by richardjgowers** [comment]
So this definitely needs doing.  I wouldn't want to put it in a `rst` directly as many people might not even know they exist when they start hacking MDA, I'd rather have all the docs in the `.py` source (which gets slurped into the `rst` automatically.

**Comment by orbeckst** [comment]
If you prefer in the py then that's totally fine with me – as long as it is *somewhere* ;-).

**Comment by orbeckst** [comment]
Note: #363 is not even mentioned in CHANGELOG!! Please add as part of fixing this issue (and don't forget to add @dotsdl to the 0.16.0 changes).

**Comment by kain88-de** [comment]
Related #1108 to explain what we mean with a unique segment/residue

**Comment by dotsdl** [comment]
Working on this this week. PR incoming soon.

**Comment by richardjgowers** [comment]
@dotsdl if you want to put up a skeleton of topics it'll make it easier for me to chip in.  Or use a project board or something?

**Comment by dotsdl** [comment]
@richardjgowers I can do that. I'll make a project board.
