### ISSUE TITLE
Can't write PDB with 0 atoms

### ISSUE THREAD

**Issue by kain88-de** [MDAnalysis/mdanalysis#1083]
### Expected behaviour

When I have an atomgroup with 0 atoms I should get an error that this PDB can't be written due to that there are no atoms in the atomgroup

### Actual behaviour

I get an internal error that I'm calling `_write_pdb_title` gets an unexpected number of arguments

### Code to reproduce the behaviour

``` python
import MDAnalysis as mda

u = mda.Universe(top, trj)
ag = u.select_atoms('resid 100000')

with mda.Writer('test.pdb', ag.n_atoms) as w:
    w.write(ag)

```

### Currently version of MDAnalysis:
(run `python -c "import MDAnalysis as mda; print(mda.__version__)"`)
Develop version

**Comment by richardjgowers** [comment]
Slightly related to #434 but a different route to the same bug
