### ISSUE TITLE
rmsd uses relative weights

### ISSUE THREAD

**Issue by kain88-de** [MDAnalysis/mdanalysis#1089]
Does anyone know why we use relative weights for the rmsd calculations with QCP? See [rms.py](https://github.com/MDAnalysis/mdanalysis/blob/37d107ef260b82ad17a75cf89f528900bf3223ae/package/MDAnalysis/analysis/rms.py#L196) and [align.py](https://github.com/MDAnalysis/mdanalysis/blob/37d107ef260b82ad17a75cf89f528900bf3223ae/package/MDAnalysis/analysis/align.py#L255). I didn't see any reason for doing that in the original QCP papers.

**Comment by orbeckst** [comment]
IIRC that was how @synapticarbors implemented it originally. I don't recall any extended discussion about it.

**Comment by kain88-de** [comment]
I was asking because I don't see anyone else doing that. So we could remove the relative weights?

**Comment by synapticarbors** [comment]
The relative weights is what was used by convention in Douglas Theobald's reference C implementation, which I originally adapted to Cython:

http://theobald.brandeis.edu/qcp/

It looks like maybe newer versions of the code/subsequent updates automatically normalize within the routines instead of relying on the user to follow the convention.

**Comment by kain88-de** [comment]
Yeah I actually didn't see anything about the weights in the original papers or in the implementations. So we can remove the relative weights then. In my own testing it also didn't make a lot of difference.

**Comment by kain88-de** [comment]
@synapticarbors You wrote the pyx implementation yourself completely? If so then Pu Liu and Douglas L. Theobald don't hold any copyright to that code since you did a re-implementation in a new language.

**Comment by orbeckst** [comment]
@synapticarbors , are you referring to the fact that the original [qcprot.c](http://theobald.brandeis.edu/qcp/qcprot.c) code was recently updated to automatically normalize by the sum of weights? From the Change History in the file:
 *    2016/07/13      Fixed normalization of RMSD in FastCalcRMSDAndRotation(), should divide by
                     sum of weights (thanks to Geoff Skillman)

Looking at the `CenterCoords()` function
```C
static void
CenterCoords(double **coords, const int len, const double *weight)
{
    int             i;
    double          xsum, ysum, zsum, wsum;
    double         *x = coords[0], *y = coords[1], *z = coords[2];

    xsum = ysum = zsum = 0.0;

    if (weight != NULL)
    {
        wsum = 0.0;
        for (i = 0; i < len; ++i)
        {
            xsum += weight[i] * x[i];
            ysum += weight[i] * y[i];
            zsum += weight[i] * z[i];

            wsum += weight[i];
        }

        xsum /= wsum;
        ysum /= wsum;
        zsum /= wsum;
    }
    else
    {
        for (i = 0; i < len; ++i)
        {
            xsum += x[i];
            ysum += y[i];
            zsum += z[i];
        }

        xsum /= len;
        ysum /= len;
        zsum /= len;
    }

    for (i = 0; i < len; ++i)
    {
        x[i] -= xsum;
        y[i] -= ysum;
        z[i] -= zsum;
    }
}
```

it looks to me that for the old code (where the lines `xsum /= wsum;` ... were apparently missing) one *had* to use relative weights exactly in the way that @synapticarbors implemented.

When I then look at `InnerProduct()` it seems to me that there is still a normalization missing although apparently that this is corrected in `FastCalcRMSDAndRotation()` (by eventually dividing by `len`) — I think if one wants to use `E0 = InnerProduct(..., weight)` with raw weights then the true weighted inner product is `E0/wsum`.

**Comment by orbeckst** [comment]
No new conclusions over the last 1.5 years – closing.
