### ISSUE TITLE
Can't Install MDAnalysis 0.15.0 on Windows 10 64 Bit Through Pip or Easy_install

### ISSUE THREAD

**Issue by Jdogzz** [MDAnalysis/mdanalysis#1095]
### Expected behaviour
I should be able to install MDAnalysis through pip or easy_install on Windows 10 64 Bit.

### Actual behaviour
It fails to install through both methods. I have attached the error logs for both.
[mdanalysis_pip_log.txt](https://github.com/MDAnalysis/mdanalysis/files/619220/mdanalysis_pip_log.txt)
[mdanalysis_easyinstall_log.txt](https://github.com/MDAnalysis/mdanalysis/files/619221/mdanalysis_easyinstall_log.txt)

### Code to reproduce the behaviour
`pip install --upgrade mdanalysis`
`easy_install -U mdanalysis`

### Currently version of MDAnalysis:
The version I am attempting to install is 0.15.0

**Comment by kain88-de** [comment]
@Jdogzz  We don't support windows. We can't debug this either since none of the core developers uses windows. You might be able to run MDAnalysis under the ubuntu shell on windows though (I don't own window 10 so I never used the ubuntu shell it has since this year)

**Comment by orbeckst** [comment]
@Jdogzz , we have an open issue for windows support #450 but not enough developers to take on the work. Anyone who is willing and interested to make it work under Windows is very welcome!

**Comment by mimischi** [comment]
Just an FYI: MDAnalysis works on Windows 10 (anniversary build #14393.447) inside Bash on Windows (Ubuntu 14.04 currently).

**Comment by orbeckst** [comment]
@mimischi thanks for the feedback – that's very valuable. 

Could I entice you to add a small HOWTO on how you managed to get it to work on our wiki under [MDAnalysis on Windows](https://github.com/MDAnalysis/mdanalysis/wiki/MDAnalysis-on-Windows)? (I think you can edit the wiki, if not let me know.)

It would help us a lot and can then be used to redirect other people.

**Comment by mimischi** [comment]
@orbeckst Sorry for getting back that late.

I'm using [Bash on Windows](https://msdn.microsoft.com/de-de/commandline/wsl/about) and therefore I've got a (more or less) full Ubuntu setup besides my Windows runtime. Therefore I was able to just install Anaconda and then install the package via ``conda``. Should I just put that note in? I don't think writing the same as in the [quick start guide](http://www.mdanalysis.org/pages/installation_quick_start/) is that valuable.

Anyway, if you think that info would be of any value, I'd be happy to help out.

**Comment by mimischi** [comment]
[Done](https://github.com/MDAnalysis/mdanalysis/wiki/MDAnalysis-on-Windows)!

**Comment by richardjgowers** [comment]
Awesome, thanks @mimischi !

**Comment by orbeckst** [comment]
Many thanks!!

--
Oliver Beckstein
email: orbeckst@gmail.com

**Comment by Gojja** [comment]
Thanks, Conda installation worked out well for me!
https://www.mdanalysis.org/pages/installation_quick_start/
