### ISSUE TITLE
ENCORE code and docs still use deprecated align.rms_fit_trj()

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/mdanalysis#1098]
The examples for [Functions for ensemble comparisons](http://www.mdanalysis.org/mdanalysis/documentation_pages/analysis/encore/similarity.html#functions-for-ensemble-comparisons)
 still use the deprecated `align.rms_fit_trj()` function.  The code itself (`MDAnalysis/analysis/encore/similarity.py`) and the tests (`testsuite/MDAnalysisTests/analysis/test_encore.py`) also use it.

Instead, use `align.AlignTraj(...).run()` (see #1059).

- [ ] ENCORE code updated
- [ ] ENCORE docs updated

**Comment by orbeckst** [comment]
See also discussion following https://github.com/MDAnalysis/mdanalysis/pull/1076#issuecomment-261724674

**Comment by mtiberti** [comment]
Thanks! I'll be able to get on this before the weekend
