### ISSUE TITLE
Missing SelectionWriter docs

### ISSUE THREAD

**Issue by kain88-de** [MDAnalysis/mdanalysis#1104]
I looked into the online selection writer docs. There are some example missing how to use the selection writer on https://pythonhosted.org/MDAnalysis/documentation_pages/selections_modules.html. It's actually not possible for me to find out how to write a selection for an atomgroup. There isn't any argument name for the AtomGroup documented. I'm not sure how used the feature itself is though.

**Comment by orbeckst** [comment]
In short:
```python
g = u.select_atoms('protein")
g.write("selections.vmd", name="mda_protein")
```
In vmd
```tcl
source selection.vmd
set sel [atomselect top mda_mdanalysis]          #  use     macro mda_protein
```

Basically write a file identified by the file extension and then load it in whichever way standard for the program.

**Comment by orbeckst** [comment]
We can add a few more examples.

**Comment by kain88-de** [comment]
We should add some in the Selections module. But honestly I'm also not very happy to hijack the `atomgroup.write` method like that. I only used that function so far to write the AtomGroup to a topology file like PDB it didn't even occur to me in the slightest that we could also use it to write selection files for different programs. 

I would prefer something like this myself and only write topology files from the AtomGroups.

```python
mda.selection.vmd.write(ag, "mda_protein")
```

**Comment by jbarnoud** [comment]
>  But honestly I'm also not very happy to hijack the atomgroup.write method like that.

I o not see the problem here. `ag.write` writes the AtomGroup in a file in a given format; if the format stores coordinates we write the coordinates, if the format stores selection we write the selection. Would the format store the atom colors, the write method would write the color. What makes you feel it is a "hijack"?

**Comment by orbeckst** [comment]
As a followup to PR #1245 : also show how to use the more pythonic `SelectionWriter`, e.g. (from #1244 ):
```python
with mda.selections.gromacs.SelectionWriter('leaflets.ndx', mode='w') as ndx:
    ndx.write(upper_saturated, name='upper_sat')
    ndx.write(upper_saturated, name='lower_sat')
    ndx.write(upper_saturated, name='upper_unsat')
    ndx.write(upper_saturated, name='lower_unsat')
```

**Comment by orbeckst** [comment]
Alternatively, use the AtomGroup's `write()` method with the proper file extension (".ndx") for a Gromacs index file:
```python
ndx = "leaflets.ndx"
upper_saturated.write(ndx, name="upper_sat", mode="w")
lower_saturated.write(ndx, name='lower_sat', mode="a")
upper_unsaturated.write(ndx, name='upper_unsat', mode="a")
lower_unsaturated.write(ndx, name='lower_unsat', mode="a")
```

Perhaps not as pretty because one needs to take care of choosing the proper mode arguments.

**Comment by orbeckst** [comment]
Supporting https://github.com/MDAnalysis/mdanalysis/issues/1104#issuecomment-264794420 wouldn't be hard by just adding a generic `write()` function to each selection writer module:
```python
def write(ag, stream, **kwargs):
   name = kwargs.pop("name", "MD_001")
   with SelectionWriter(stream, **kwargs) as w:
        w.write(ag, name=name)
```

Question is if we want to advertise **three* different ways to do essentially the same thing.

**Comment by jbarnoud** [comment]
@orbeckst I do not mind having the `write` function you propose, Yet, I fail to see more than a very marginal  gain compared to the two other methods we have. Maybe I am not using the feature often enough, or maybe I am too use to the current way.

Would there be a way to have the function in every module without copy pasting it everywhere?

**Comment by orbeckst** [comment]
I'm not super keen on this function but @kain88-de suggested it in the comment that I linked. I don't know if he changed his view after seeing the more pythonic use if the context manager. 

--
Oliver Beckstein
email: orbeckst@gmail.com


> Am Mar 18, 2017 um 2:17 schrieb Jonathan Barnoud <notifications@github.com>:
> 
> @orbeckst I do not mind having the write function you propose

**Comment by kain88-de** [comment]
I'm ok with the new method. It fits the trajectory writer pattern.
