### ISSUE TITLE
MMTF parser doesn't work well.

### ISSUE THREAD

**Issue by leonqli** [MDAnalysis/mdanalysis#1107]
### Expected behaviour
show all residues in A chain:

### Actual behaviour
['HOH', 'HOH', 'HOH']

### Code to reproduce the behaviour

``` python
from MDAnalysis.coordinates.MMTF import fetch_mmtf
s=fetch_mmtf("1kq2")
s.A.residues
list(r.resname for r in s.A.residues)

```

### Currently version of MDAnalysis:
0.16.0-dev0

**Comment by kain88-de** [comment]
There are two problems here. Once is that `s.A` doesn't return chain A. I'm not sure right now what it returns. The other that the PDB entry does contain 3 HEATM entries that belong to chain A with the residue identifier 'HOH'. To select only chain A of the protein use `s.select_atoms('protein and segid A')` then you get the correct residues.

**Comment by richardjgowers** [comment]
The Universe quick access to chains works by iterating over all segments, so if you have two segments with an identical segid (here we have 2 segid A segments) you'll only get the last one.

```python
# Current code
for seg in self.segments:
    setattr(self, seg.segid, seg)

# Possible fix?
# Loop over all unique chain identifiers (segids?) and group these together
for segid in unique(self.segments.segids):
    seg = self.select_atoms('segid {}'.format(segid))
    setattr(self, segid, seg)
```

**Comment by kain88-de** [comment]
I like the work around. It will likely also fix the current problem I'm seeing with mmtf and the correponding pdb

```python
In [1]: m = mda.fetch_mmtf('1kq2')

In [2]: p = mda.Universe('1kq2.pdb')

In [3]: m.A
Out[3]: <Segment 7>

In [4]: p.A
Out[4]: <Segment 8>
```

I'm not sure why the same operation returns different results on theoretical the same topology.

**Comment by kain88-de** [comment]
Ah ok. The order of the segments is just different between the mmtf and the pdb. Otherwise they seem to be the same. I just just confused that `universe.A` print the number of the segment ( I thought it shows that it contains as number of residues or something similar)
