### ISSUE TITLE
MMTF and PDB of the same protein return different topologies

### ISSUE THREAD

**Issue by kain88-de** [MDAnalysis/mdanalysis#1110]
### Expected behaviour

Loading a PDB or a MMTF yields the same topology

### Actual behaviour

They differ. See [1nmu](http://www.rcsb.org/pdb/explore/explore.do?structureId=1NMU).
The current stable release returns the same result as the mmtf

### Code to reproduce the behaviour

``` python
import MDAnalysis as mda

u = mda.Universe('1nmu.pdb')
u.atoms.segments.unique.segids # contains 8 entries
m = mda.fetch_mmtf('1nmu')
m.atoms.segments.unique.segids # contains 10 entries
....

```

### Currently version of MDAnalysis:
(run `python -c "import MDAnalysis as mda; print(mda.__version__)"`)
0.16.0dev

**Comment by richardjgowers** [comment]
Not sure this is an MDA issue.  The files have different topologies too, the pdb file has 4 different chain IDs (out of order, see #1108), the mmtf file has 10 chains

**Comment by kain88-de** [comment]
I get 10 chains using MDA version 0.15.0

**Comment by kain88-de** [comment]
I would also be 90% sure that different files of the same PDB entry have identical content.
