### ISSUE TITLE
Encore uses different progressbar

### ISSUE THREAD

**Issue by kain88-de** [MDAnalysis/mdanalysis#1114]
[See](http://www.mdanalysis.org/mdanalysis/documentation_pages/analysis/encore/utils.html#MDAnalysis.analysis.encore.utils.ProgressBar). It should also switch to our common progressbar in `mda.lib.log`.

**Comment by mtiberti** [comment]
I just had a quick look at ProgressMeter - It looks like we could make the switch, but I'll have a better look in the next few days. The main difference I see is that our current progress bar also tracks progress from parallel runs.

**Comment by jdetle** [comment]
Hi @kain88-de, @mtiberti, I've been thinking of updating the mda.lib.log progress meter to make use of new functionality in ipython, (if users have installed 5.1), https://github.com/jupyter/jupyter_client/issues/209 the cool thing about this is that it allows for the progress bar to exist separate from the cell that is running the calculation. Let me know if you think this would be desirable to have.

**Comment by kain88-de** [comment]
We shouldn't have jupyter as a default dependency.

**Comment by jdetle** [comment]
Okay! Thanks for the quick response.
