### ISSUE TITLE
Improving Efficiency on making AroundSelection many many times.

### ISSUE THREAD

**Issue by yliu120** [MDAnalysis/mdanalysis#1118]
Use cases:

User want to check all potential neighbors of a specific atom/AtomGroup throughout a trajectory. This kind of analysis is often desirable when people want to check potential interactions with some fixed group throughout the simulation.

Since all DistanceSelections would alter the indices of the AtomGroup, so the selection should be updated for every frame. (Other selections don't have such an issue) A straightforward implementation of such analysis is the following:

``` python
univ = Universe("traj.gro", "traj.xtc")
for ts in univ.trajectory:
    group = univ.select_atoms("around 8 (resid 1 and name CA)")
    # do something with group
....
```

The above implementation has a severe performance problem, especially when the n_frames is very large for that trajectory. The performance costs are majorly from the following:

1. Parsing performance. The selection string should be parsed for n_frames times.
2. Selection Evaluation problems. The selection string will be parsed into a AST and the apply() method will be called for each operator in the AST. However, in the above code, some portion of selections are fixed throughout the trajectory ("resid 1 and name CA"). We do not have to re-evaluate "ResidSelection" "AndOperator" "NameSelection" for many times.
3. KDTree cost. The major performance loss are caused by KDTree construction and search() method.

To improve performance, a smarter implementation would
1. Cache the AST parsed from the selection string to avoid n_frames time of parsing.
2. To fix 2, a smart programmer can do this.

```python
univ = Universe("traj.gro", "traj.xtc")
ref_group = univ.select_atoms("resid 1 and name CA")
for ts in univ.trajectory:
    group = univ.select_atoms("around 8 group ref", ref=ref_group)
    # do something with group
```

Refer to the [pull request](https://github.com/MDAnalysis/mdanalysis/pull/1117) simply implements the 1., the above code could be optimized to

```python
univ = Universe("traj.gro", "traj.xtc")
ref_group = univ.select_atoms("resid 1 and name CA")
for ts in univ.trajectory:
    group = univ.select_atoms("around 8 group ref", cached=True, ref=ref_group)
    # do something with group
```

3. To fix the KDTree performance cost, as my knowledge there is no good way to be accurate. An approximate algorithm would be: 
1) we assume that the conformation of the molecule won't change too much.
2) By 1) assumption, we can enlarge the scope of KDTree search to 2 times. So instead of searching from all atoms, we only search from a possible portion of the molecule.

The code for 3 would be,

```python
univ = Universe("traj.gro", "traj.xtc")
ref_group = univ.select_atoms("resid 1 and name CA")
scope = univ.select_atoms("around 20 group ref", ref=ref_group)
for ts in univ.trajectory:
    group = scope.select_atoms("around 8 group ref", cached=True, ref=ref_group)
    # do something with group
```
The code will not give us an accurate answer but for approximation purposes, it is good enough sometimes. 

However the code snippet looks cumbersome. I don't know whether there is any existing way to make it better. What I propose is to make a new selection called scope, then we can do

```python
group = univ.select_atoms("around 8 scope 20 group ref", cached=True, ref=ref_group)
```

### Currently version of MDAnalysis:
(run `python -c "import MDAnalysis as mda; print(mda.__version__)"`)

**Comment by kain88-de** [comment]
The issue about updating the AtomGroup  is taken care of in #1080.  We are aware that the KDTree could be speed up with a different algorithm. There has already been some work on investigating other algorithms, see [cellgrid](https://github.com/richardjgowers/cellgrid).

**Comment by tylerjereddy** [comment]
Do we know how the KDTree algorithm we use compares with the one in scipy?

**Comment by kain88-de** [comment]
https://gist.github.com/kain88-de/3617d6ec20aaf3cb1ef4

I have an old gist for this. It doesn't render nicely anymore on github though. The scipy implementation is faster. But @orbeckst didn't like to add scipy as a default dependency. But right now I would rather have scipy as a dependency then biopython.

**Comment by richardjgowers** [comment]
@yliu120 Welome to MDA!  With selections like this, if you benchmark it 90%+ of your time will be doing the distance selection, any other optimisation wouldn't really be worth the added complexity of managing caches etc.

It would be interesting to see if we could cache KDTrees/CellGrids, maybe even have a trajectory of KDTrees/CellGrids as an Auxiliary to the trajectory...

**Comment by orbeckst** [comment]
The gist renders nicely through nbviewer http://nbviewer.jupyter.org/gist/kain88-de/3617d6ec20aaf3cb1ef4

**Comment by jdetle** [comment]
@kain88-de, I think the file extension has to be `.ipynb` to render nicely in github.

**Comment by orbeckst** [comment]
The other issue with KDTree is that we don't have a good way to use it for periodic selections. There's an issue for KDTree with PBC #137 but that hasn't been explored in a while.

**Comment by yliu120** [comment]
@orbeckst, I briefly read #137. As I know, the correctness of making selections under PBC is hard to guarantee, especially for gromacs. I use the dodecahedron box for my protein. For those random pbc boxes, dodecahedron and triclinic, special cares should be taken and they might make things inefficient.

**Comment by mnmelo** [comment]
Closing because #1080 addresses the main topic of this issue.
A new issue can be opened to discuss cache managing, if deemed worthy.
