### ISSUE TITLE
PCA module error

### ISSUE THREAD

**Issue by MamtaMohan** [MDAnalysis/mdanalysis#1122]
Hi,

I tried to use new link and PCA does not load.

In [1]: import MDA
MDAnalysis       MDAnalysisTests  

In [1]: import MDAnalysis as mda

In [2]: import MDA
MDAnalysis       MDAnalysisTests  

In [2]: import MDAnalysis.analysis.pca as pca
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-fa3964fefd9b> in <module>()
----> 1 import MDAnalysis.analysis.pca as pca

ImportError: No module named pca

**Comment by orbeckst** [comment]
You mean you tried using @kain88-de 's conda beta of 0.16.0-dev0 (see #1116 ) and it does not work?

What does
```python
import MDAnalysis as mda
print mda.__version__
print mda.__file__
```
show? Are you picking up the right version?

Can you run the tests?
```python
import MDAnalysisTests
MDAnalysisTests.run(argv=["-v", "--exe", "--processes=4", "--process-timeout=120"])
```

(I use multiple cores to speed up the tests but you can removed the `"--processes=4", "--process-timeout=120"` arguments). Tests can take a while... in serial about 10 minutes for almost 4000 tests.

**Comment by MamtaMohan** [comment]
Please find results of commands you asked to execute.

Mamta

In [1]: import MDAnalysis as mda

In [2]: print mda.__version__
0.15.0

In [3]: print mda.__file__
/home/mamta/anaconda2/lib/python2.7/site-packages/MDAnalysis/__init__.pyc

In [4]:



Ran 3368 tests in 88.301s

OK (SKIP=5)
An exception has occurred, use %tb to see the full traceback.

SystemExit: False

To exit: use 'exit', 'quit', or Ctrl-D.
In [6]: %tb
---------------------------------------------------------------------------
SystemExit                                Traceback (most recent call last)
<ipython-input-5-904fba575ac8> in <module>()
----> 1 MDAnalysisTests.run(argv=["-v", "--exe", "--processes=8", "--process-timeout=120"])

/home/mamta/anaconda2/lib/python2.7/site-packages/MDAnalysisTests/__init__.pyc in run(*args, **kwargs)
    155     # By default, test our testsuite
    156     kwargs['defaultTest'] = dirname(__file__)
--> 157     return nose.run_exit(*args, **kwargs)
    158
    159

/home/mamta/anaconda2/lib/python2.7/site-packages/nose/core.pyc in __init__(self, module, defaultTest, argv, testRunner, testLoader, env, config, suite, exit, plugins, addplugins)
    119             self, module=module, defaultTest=defaultTest,
    120             argv=argv, testRunner=testRunner, testLoader=testLoader,
--> 121             **extra_args)
    122
    123     def getAllConfigFiles(self, env=None):

/home/mamta/anaconda2/lib/python2.7/unittest/main.pyc in __init__(self, module, defaultTest, argv, testRunner, testLoader, exit, verbosity, failfast, catchbreak, buffer)
     93         self.progName = os.path.basename(argv[0])
     94         self.parseArgs(argv)
---> 95         self.runTests()
     96
     97     def usageExit(self, msg=None):

/home/mamta/anaconda2/lib/python2.7/site-packages/nose/core.pyc in runTests(self)
    208         self.success = result.wasSuccessful()
    209         if self.exit:
--> 210             sys.exit(not self.success)
    211         return self.success
    212

SystemExit: False



________________________________

**Comment by orbeckst** [comment]
The `__version__` information that you show indicates that you are *not* running the 0.16.0dev0. Therefore, `pca` is not available.

I don't know why you do not get 0.16.0dev0 if you followed @kain88-de 's installation instructions. Things to check
* uninstall any previous versions of MDAnalysis
* start in a fresh conda environment

**Comment by kain88-de** [comment]
closing because this is an installation error
