### ISSUE TITLE
minimal install uses scipy

### ISSUE THREAD

**Issue by kain88-de** [MDAnalysis/mdanalysis#1147]
Our minimal install now pulls scipy as a dependency.  This comes from the griddataformats conda package (which depends on scipy for remapping). To solve this griddataformats would have to be installed from pip for the minimal build.

Or we just allow scipy as a dependency.

**Comment by richardjgowers** [comment]
It's not the minimal install it's the minimal travis build that pulls scipy right?  So I could still install MDA without scipy, just griddataformats wouldn't have remapping.

**Comment by kain88-de** [comment]
Yes that is correct.

**Comment by orbeckst** [comment]
In principle that's not a problem **if** we can still test minimal environments (i.e., everything is working without scipy).

Could we disable the conda scipy in the minimal build?

**Comment by richardjgowers** [comment]
@orbeckst yeah @kain88-de is doing that in #1148
