### ISSUE TITLE
MDAnalysis Universe with error "invalid mode ('rtb')"

### ISSUE THREAD

**Issue by YISION** [MDAnalysis/mdanalysis#1149]
### Actual behaviour

D:\ProgramFiles\Anaconda\lib\site-packages\MDAnalysis\core\AtomGroup.pyc in __init__(self, *args, **kwargs)
   4345             raise ValueError("Failed to construct topology from file {0}"
   4346                              " with parser {1} \n"
-> 4347                              "Error: {2}".format(self.filename, parser, err))
   4348
   4349         # Generate atoms, residues and segments

ValueError: Failed to construct topology from file D:\ProgramFiles\Anaconda\lib\site-packages\MDAnalysisTests\data\adk.psf with parser <class 'MDAnalysis.topology.PSFParser.PSFParser'>

Error: Invalid mode ('rtb')

### Code to reproduce the behaviour

``` python

from MDAnalysis import Universe

from MDAnalysis.tests.datafiles import PSF, DCD

u = Universe(PSF,DCD)

....

```

### Currently version of MDAnalysis:
(run `python -c "import MDAnalysis as mda; print(mda.__version__)"`)
version:
0.15.0

**Comment by YISION** [comment]
I failed this test in windows platform, but the same code could work in linux. Both used anaconda.

**Comment by kain88-de** [comment]
MDAnalysis isn't officially supported under windows. We have reports though that it works with the ubuntu emulation under windows 10 [wiki](https://github.com/MDAnalysis/mdanalysis/wiki/MDAnalysis-on-Windows). You also shouldn't have been able to install MDAnalysis with the conda package under windows, we only release a linux version.

**Comment by orbeckst** [comment]
@YISION , how did you install MDAnalysis under Windows? 
Did you try it according to [MDAnalysis on Windows with Bash-on-Windows](https://github.com/MDAnalysis/mdanalysis/wiki/MDAnalysis-on-Windows) ?

I am closing this issue until we have more information because at the moment it looks as if you are using MDA in an unsupported configuration – we don't have native Windows support yet – see Issue #450 .

**Comment by YISION** [comment]
very thanks for reply



shendeyidishui@gmail.com
 
From: Max Linke
Date: 2017-01-09 16:46
To: MDAnalysis/mdanalysis
CC: YISION; Author
Subject: Re: [MDAnalysis/mdanalysis] MDAnalysis Universe with error "invalid mode ('rtb')" (#1149)
MDAnalysis isn't officially supported under windows. We have reports though that it works with the ubuntu emulation under windows 10 wiki. You also shouldn't have been able to install MDAnalysis with the conda package under windows, we only release a linux version.
