### ISSUE TITLE
principal_axes sorts lowest to highest instead highest to lowest (as documented)

### ISSUE THREAD

**Issue by jonekoo** [MDAnalysis/mdanalysis#1162]
### Expected behaviour
The documentation says:
> The eigenvectors are sorted by eigenvalue, i.e. the first one
> corresponds to the highest eigenvalue and is thus the first principal axes.

### Actual behaviour
The eigenvector corresponding to the **smallest** eigenvalue is the first. 

This is easily verified and also seen by looking at the code of principal_axes. (numpy.argsort sorts in ascending order).

**Comment by jdetle** [comment]
Hi, I'd like to tackle this. Would we rather just properly reflect the ordering in the documentation, or switch the order and change/add some tests?

**Comment by kain88-de** [comment]
We have to switch the order. The documentation is correct
