### ISSUE TITLE
Random access in GMS shifted in python 3

### ISSUE THREAD

**Issue by jbarnoud** [MDAnalysis/mdanalysis#1174]
Tests for the GMS reader are failing on python 3. On python 3, trying to access frame N  with `u.trajectory[N]` actually gives frame N + 1. Iterating through the trajectory works fine, though.

The following gist demonstrate the issue by running the name notebook with both python 3 and python 2: https://gist.github.com/jbarnoud/37696da9be941f7df2277f33e8635fc8

In both cases, the notebook iterate through the trajectory to store the coordinates for each frame in a list.

Then it compares the coordinates obtained by randomly accessing frames to the coordinates stored in the list for that frame. This test works on python 2, but it fails on python 3. Also, on python 3, MDAnalysis does not manage to access the last frame (IOError).

When trying to compare the coordinates obtained by random access of frame N with the coordinates stored for N+1, python 3 finds that they match, while python 2. Of course, the behaviour of python 2 is the correct one.

The problem does not appear to be due to subsequent access to the trajectory as iterating twice over the trajectory yields the same coordinates.

**Comment by richardjgowers** [comment]
So looking into this...

In Python 2:
```python
In [1]: import MDAnalysis as mda

In [2]: u = mda.Universe('symopt.gms')

In [3]: u.trajectory._offsets
Out[3]: [12187, 29564, 36358, 43152, 49946, 56740, 63534, 70256]

```

In Python 3:
```python
In [1]: import MDAnalysis as mda
/home/richard/miniconda2/envs/py3/lib/python3.6/site-packages/MDAnalysis/__init__.py:210: UserWarning: #####
MDAnalysis on python 3 is highly experimental!
It is mostly non functional and dramatically untested.
Use at your own risks!!!

In [2]: u = mda.Universe('symopt.gms')

In [3]: u.trajectory._offsets
Out[3]: [12188, 29565, 36359, 18446744073709594770, 49947, 56741, 63535, 70257]

```

So something screwy is happening with one of the `tell` calls.  Also weird is that they're all different by 1 byte?  The PDB and XYZ random access works similarly, so I wouldn't be surprised if they have (or could have) similar issues.

The code that calculates this is below, it basically just goes line by line looking for a regex match and stores a `File.tell()` if it sees this.

https://github.com/MDAnalysis/mdanalysis/blob/develop/package/MDAnalysis/coordinates/GMS.py#L153

**Comment by jbarnoud** [comment]
It seems that the problem does not come from the `tell` but from the `len(line)`:

```python
u = mda.Universe(GMS_ASYMOPT)

if u.trajectory.runtyp == 'optimize':
    trigger = re.compile(r'^.NSERCH=.*')
elif u.trajectory.runtyp == 'surface':
    trigger = re.compile(r'^.COORD 1=.*')

offsets = []
tells = []
len_lines = []
with mda.lib.util.openany(u.trajectory.filename, 'rt') as out:
    line = True
    while not line == '':  # while not EOF
        line = out.readline()
        if re.match(trigger, line):
            offsets.append(out.tell() - len(line))
            tells.append(out.tell())
            len_lines.append(len(line))
            print((line, len(line)))
```

Output on python 2:

```
('1NSERCH=   0\r\n', 14)
('1NSERCH=   1\r\n', 14)
('1NSERCH=   2\r\n', 14)
('1NSERCH=   3\r\n', 14)
('1NSERCH=   4\r\n', 14)
('1NSERCH=   5\r\n', 14)
('1NSERCH=   6\r\n', 14)
('1NSERCH=   7\r\n', 14)
('1NSERCH=   8\r\n', 14)
('1NSERCH=   9\r\n', 14)
('1NSERCH=  10\r\n', 14)
('1NSERCH=  11\r\n', 14)
('1NSERCH=  12\r\n', 14)
('1NSERCH=  13\r\n', 14)
('1NSERCH=  14\r\n', 14)
('1NSERCH=  15\r\n', 14)
('1NSERCH=  16\r\n', 14)
('1NSERCH=  17\r\n', 14)
('1NSERCH=  18\r\n', 14)
('1NSERCH=  19\r\n', 14)
('1NSERCH=  20\r\n', 14)
```

Output on python 3:

```
('1NSERCH=   0\n', 13)
('1NSERCH=   1\n', 13)
('1NSERCH=   2\n', 13)
('1NSERCH=   3\n', 13)
('1NSERCH=   4\n', 13)
('1NSERCH=   5\n', 13)
('1NSERCH=   6\n', 13)
('1NSERCH=   7\n', 13)
('1NSERCH=   8\n', 13)
('1NSERCH=   9\n', 13)
('1NSERCH=  10\n', 13)
('1NSERCH=  11\n', 13)
('1NSERCH=  12\n', 13)
('1NSERCH=  13\n', 13)
('1NSERCH=  14\n', 13)
('1NSERCH=  15\n', 13)
('1NSERCH=  16\n', 13)
('1NSERCH=  17\n', 13)
('1NSERCH=  18\n', 13)
('1NSERCH=  19\n', 13)
('1NSERCH=  20\n', 13)
```

It appears that python 3 converts `\r\n` to `\n` in files by default. 

One solution is to open the file in bytes mode rather than as text. It works on the short example:

```
u = mda.Universe(GMS_ASYMOPT)

if u.trajectory.runtyp == 'optimize':
    trigger = re.compile(b'^.NSERCH=.*')
elif u.trajectory.runtyp == 'surface':
    trigger = re.compile(b'^.COORD 1=.*')

offsets = []
tells = []
len_lines = []
with mda.lib.util.openany(u.trajectory.filename) as out:
    line = True
    while not line == b'':  # while not EOF
        line = out.readline()
        if re.match(trigger, line):
            offsets.append(out.tell() - len(line))
            tells.append(out.tell())
            len_lines.append(len(line))
            print((line, len(line)))
```

gives on bitn python 2 and 3:

(b'1NSERCH=   0\r\n', 14)
(b'1NSERCH=   1\r\n', 14)
(b'1NSERCH=   2\r\n', 14)
(b'1NSERCH=   3\r\n', 14)
(b'1NSERCH=   4\r\n', 14)
(b'1NSERCH=   5\r\n', 14)
(b'1NSERCH=   6\r\n', 14)
(b'1NSERCH=   7\r\n', 14)
(b'1NSERCH=   8\r\n', 14)
(b'1NSERCH=   9\r\n', 14)
(b'1NSERCH=  10\r\n', 14)
(b'1NSERCH=  11\r\n', 14)
(b'1NSERCH=  12\r\n', 14)
(b'1NSERCH=  13\r\n', 14)
(b'1NSERCH=  14\r\n', 14)
(b'1NSERCH=  15\r\n', 14)
(b'1NSERCH=  16\r\n', 14)
(b'1NSERCH=  17\r\n', 14)
(b'1NSERCH=  18\r\n', 14)
(b'1NSERCH=  19\r\n', 14)
(b'1NSERCH=  20\r\n', 14)
```

**Comment by jbarnoud** [comment]
Reading the file as bytes works. I'll include the fix in my nest batch of python 3 fixes.
