### ISSUE TITLE
Doc does not say that RMSD does not make molecule whole when centering

### ISSUE THREAD

**Issue by jbarnoud** [MDAnalysis/mdanalysis#1182]
It is not clear from the documentation that `analysis.rms.rmsd` and `analysis.rms.RMSD` do not make the molecule whole before calculating the center of mass for centering. This can cause surprising results such as those described in the original issue.

Original issue:
-----------

`analysis.rms.rmsd` and `analysis.rms.RMSD` do not make the molecule whole before calculating the center of mass for centering. This can lead to wrong centering, hence wrong superimposition, and therefore abnormally high RMSD values.

[This notebook shows the problem on a toy example](https://gist.github.com/jbarnoud/4982c7c65c32f33036da84d7348a2bb5). In a nutshell, I get some abnormally high RMSD values when I try to calculate the RMSD of a protein throughout a trajectory. I can get the result outputed by gromacs by making my protein whole before hand. I can get with gromacs the same bogus results as I get with MDAnalysis if I prevent gromacs to make the molecules whole.

Alternatively, since RMSD can be calculated on structures that are not covalently bonded, atoms from the selections could be pack together in a way similar to what I describe here: <http://stackoverflow.com/a/41704546/2799884>.

**Comment by kain88-de** [comment]
I'm sorry the docs don't specify that but yes you need to make molecules complete again yourself before you calculate the rmsd. I don't think we can generally add this though. My own simulations don't work with standard PBC repairing algorithms and I know from others in my group that they often need different algorithms to repair the pbc artifacts, mostly using g_trjconv with different options several times.

**Comment by jbarnoud** [comment]
Maybe it should be clearer in the doc, then. I rename and retag the issue.
