### ISSUE TITLE
Single frame PDB writer

### ISSUE THREAD

**Issue by xiki-tempula** [MDAnalysis/mdanalysis#1199]
I'm using on a software (coot) which only works on a single frame PDB file. This software doesn't like the line "MODEL         1" in PDB file so I want to write PDB files which don't contain this line. 

I noticed that if I use PDBWriter to write PDB file directly and specifying the multiframe flag to be False, I can get the "right" file, which don't contain "MODEL         1". However, if I write from the atom group, I will get a pdb file with the line "MODEL         1" even though I specify the multiframe to be False.

Having taking some look into the source code, I found that in the file 'core.py', in the' get_writer_for' function, when the multiframe == False, the function returns the corresponding writer from the '_SINGLEFRAME_WRITERS' dictionary. The writer which corresponding to the pdb file in  '_SINGLEFRAME_WRITERS' is MultiPDBWriter class. This class set the multiframe to True and result in the writing of "MODEL         1". I wonder if it is possible to put 'PDBWriter' class in the '_SINGLEFRAME_WRITERS' dictionary and I guess that might be more appropriate. Thank you.

### Expected behaviour (content in the pdb file)

HEADER    
TITLE     MDANALYSIS FRAMES FROM 0, SKIP 1: Created by PDBWriter
CRYST1    0.000    0.000    0.000   0.00   0.00   0.00 P 1           1
ATOM      1  C   MDA     1       0.000   0.000   0.000  1.00  0.00           C
ENDMDL
END

### Actual behaviour (content in the pdb file)

HEADER    
TITLE     MDANALYSIS FRAMES FROM 0, SKIP 1: Created by PDBWriter
CRYST1    0.000    0.000    0.000   0.00   0.00   0.00 P 1           1
MODEL         1
ATOM      1  C   MDA     1       0.000   0.000   0.000  1.00  0.00           C
ENDMDL
END

### Code to reproduce the behaviour

``` python
import MDAnalysis as mda
with open('foo.pdb', 'w') as f:
    f.write('ATOM      1  C   MDA     1       0.00    0.00    0.00   1.00  0.00           C\nEND\n')
u = mda.Universe('foo.pdb')  
u.atoms.write('bar.pdb', multiframe = False)

```

### Currently version of MDAnalysis:
py35 and mdanalysis: 0.15.0

**Comment by xiki-tempula** [comment]
When loading PDB.py in the coordinate module, the classes are added to _SINGLEFRAME_WRITERS and  _MULTIFRAME_WRITERS by the _Writermeta meta class. However, since there are two classes in the PDB.py which has the format attribute, _Writermeta will be called twice. Since _Writermeta will attempt to add every thing into _SINGLEFRAME_WRITERS regardless of whether multiframe is true or not. The MultiPDBWriter will be added to _SINGLEFRAME_WRITERS and overwrite the original PDBWriter.

**Comment by richardjgowers** [comment]
@xiki-tempula I've put up a fix at #1201 which should fix this for you.  You should be able to do `git checkout issue-1199-writerregistration` to try this branch.

The other issue here is that `AtomGroup.write` returns multiframe writers, when really it should preferentially choose a single frame writer surely?

**Comment by xiki-tempula** [comment]
@richardjgowers Thank you for your attention. I have made a quick and dirty fix to this problem without introducing other modifications. When MultiPDBWriter is created it overwrites the PDBWriter in the _SINGLEFRAME_WRITERS['PDB']. So I create a new class SinglePDBWriter which is identical to PDBWriter and is created after MultiPDBWriter. So SinglePDBWriter can overwrite the MultiPDBWriter for _SINGLEFRAME_WRITERS['PDB'].

**Comment by richardjgowers** [comment]
@xiki-tempula yeah that's a nice quick and dirty fix :)

Writer registration doesn't **have** to happen inside the package even, so inside your scripts etc you could put 

```python
# at the top of your script somewhere
# redefine PDBWriter to make it overwrite existing
from MDAnalysis.coordinates.PDB import PDBWriter

class PDBWriter(PDBWriter):
    format = 'PDB'
```
at the top and you'll do the overwrite.

**Comment by xiki-tempula** [comment]
@richardjgowers Thank you. I guess you are right.
