### ISSUE TITLE
conflicting variable types in encore analysis

### ISSUE THREAD

**Issue by ghoti687** [MDAnalysis/mdanalysis#1200]
I tried to perform encore analysis and encountered a bug. I loaded two GROMACS XTC trajectories and tried: `sim, details = encore.hes([u1,u2])`.

The bug occurs in line 872 in encore/similarity.py on: `ensemble.transfer_to_memory()`.
The function is defined in core/universe.py and the problem is the 'step' argument, which defaults to `None`. In line 468, this gets passed as `interval = step` to the ProgressMeter class.

In lib/log.py on line 369, the line `self.interval = int(interval)` fails, because interval now is None, which cannot be coerced into an integer. In the __init__ method of the class ProgressMeter, you defined the default to be interval=10, an integer.

The bug can be resolved by changing either default of the 'step' argument of the `transfer_to_memory()` function to an integer, or by checking the 'interval' argument in `ProgressMeter.__init__` for being NoneType

**Comment by jbarnoud** [comment]
The way the code is written now, the `ProgressMeter` would work as expected if it were instanciated with `interval=1`.

**Comment by jbarnoud** [comment]
@ghoti687 Thank you for the very precise bug report. I wrote a very quick fix in the pull request #1204, it still needs to go through review (even though it may be the shorter fix in the project history) but you can already try it by using the branch "issue-1200-progress-transfer".

**Comment by jbarnoud** [comment]
@ghoti687 The fix got merged. Hopefully your problem is solved in the current state of the code.
