### ISSUE TITLE
density_from_Universe with soluteselection and cutoff fails

### ISSUE THREAD

**Issue by macraild** [MDAnalysis/mdanalysis#1211]
### Expected behaviour
```python
D=density.density_from_Universe(u, atomselection, soluteselection, cutoff, update_selection=True)
```

should return a density map of the atoms in atomselection that are within cutoff of soluteselection

### Actual behaviour
Traceback (most recent call last):
```
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python2.7/site-packages/MDAnalysis-0.16.0_dev0-py2.7-linux-x86_64.egg/MDAnalysis/analysis/density.py", line 475, in density_from_Universe
    coord = current_coordinates()
  File "/usr/lib64/python2.7/site-packages/MDAnalysis-0.16.0_dev0-py2.7-linux-x86_64.egg/MDAnalysis/analysis/density.py", line 468, in current_coordinates
    return notwithin_coordinates()
  File "/usr/lib64/python2.7/site-packages/MDAnalysis-0.16.0_dev0-py2.7-linux-x86_64.egg/MDAnalysis/analysis/density.py", line 601, in notwithin_coordinates
    solvation_shell = ns_w.search_list(protein, cutoff)  # solvent within CUTOFF of protein
AttributeError: 'AtomNeighborSearch' object has no attribute 'search_list'
```

### Code to reproduce the behaviour

``` python
import MDAnalysis as mda
from MDAnalysis.tests.datafiles import PSF,DCD 
from MDAnalysis.analysis import density

u = mda.Universe(PSF,DCD)

D=density.density_from_Universe(u, atomselection='resid 1-10', soluteselection='resid 10-20', cutoff=3.5, update_selection=True)
....

```

### Currently version of MDAnalysis:
0.16.0-dev0

From a quick look at the code, I guessed that `ns_w.search_list()` should be `ns_w.search()`

Making that change fixes the AttributeError, but the resulting density maps are insensitive to the value of cutoff. So clearly there is a deeper problem here that I don't understand.

**Comment by lohani2280** [comment]
I am a newcomer here and i would like to get assigned to work on this issue. Any suggestions are welcome!!

**Comment by orbeckst** [comment]
You can submit a PR, just mention #1211 in the PR. 

I can't formally assign you to the issue because you were not the one who opened it and you're not a contributor yet (you will become one with the first merged PR). However, that's not an issue – if we you want to contribute, submit a PR, and people will start communicating with you through the review process of the PR.

**Comment by richardjgowers** [comment]
Hey @macraild thanks for the detailed report, - it really helps,  I've fixed a few things you've found.  With the cutoff problem, were you seeing that the value of cutoff didn't seem to make any difference?

**Comment by macraild** [comment]
Hi @richardjgowers , 
That is certainly what I reported. But looking again at the code and docs now, I realise I had completely misunderstood the expected behaviour. From my initial report: 
"should return a density map of the atoms in atomselection that are within cutoff of soluteselection"
but in fact the documented behaviour is atoms in atomselection that are **not within** cutoff of soluteselection

Based on my misunderstanding, I was testing very small cutoffs and seeing no effect, but I now realise that is the expected behaviour (though I must admit it remains counterintuitive to me that this would be the desired behaviour).

I'll try and find time in the next day or so to test your fixes for my somewhat unusual use-case.

**Comment by orbeckst** [comment]
The use case is generating a "bulk" density. It was special cased because of performance reasons. 

> atoms in atomselection that are not within cutoff of soluteselection

**Comment by orbeckst** [comment]
How should we phrase the docs to make this clearer? 

> (though I must admit it remains counterintuitive to me that this would be the desired behaviour).

**Comment by macraild** [comment]
I'm not sure I can help there, @orbeckst - the docs look abundantly clear to me now. This was just a case of confirmation bias - I was looking for a specific functionality, and it was all to easy to find a set of kwargs that looked to do what I want and to miss the critical 'not' in a quick read of the docs. Because I'm interested in something other than solvent density in this case, bulk density has little meaning for me and hadn't really entered my thinking.

**Comment by macraild** [comment]
For me, after #1232 the code to reproduce above gives:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/vcp1/people/macraild/progs/MDAanalysis_devel/mdanalysis/package/MDAnalysis/analysis/density.py", line 472, in density_from_Universe
    u, groupselection, soluteselection, cutoff,
NameError: global name 'groupselection' is not defined


Looks like 'groupselection' should be 'atomselection' here?

**Comment by orbeckst** [comment]
... hm, looking into it.

**Comment by orbeckst** [comment]
Yes, ... will fix and add proper test case.

**Comment by orbeckst** [comment]
@macraild I updated the docs a bit with some examples that hopefully make `soluteselection` and `cutoff` a bit clearer: see [MDAnalysis.analysis.density.density_from_Universe](http://www.mdanalysis.org/mdanalysis/documentation_pages/analysis/density.html#MDAnalysis.analysis.density.density_from_Universe), in particular the *Examples* section.

There's also an example for how you can get the solvent atoms *within* a cutoff (just might be a bit slower).

**Comment by macraild** [comment]
Thanks @orbeckst. I've had the 'around' selections working. Though as noted [here](https://groups.google.com/forum/#!topic/mdnalysis-discussion/8Gl_HwM2Hy8) this doesn't handle the edge case of updating selections that are empty for some frames.
