### ISSUE TITLE
Small typo error in wiki-page: https://github.com/MDAnalysis/mdanalysis/wiki/Setup-Development-Environment

### ISSUE THREAD

**Issue by lohani2280** [MDAnalysis/mdanalysis#1212]
### Expected behaviour
```
cd testsuite/MDAnalysisTests
./mda_nosetests
```
### Actual behaviour
```
cd testsuite/MDAnalsysisTests
./mda_nosetests
```

### Code to reproduce the behaviour

``` python
import MDAnalysis as mda

u = mda.Universe(top, trj)

....

```

### Currently version of MDAnalysis:
(run `python -c "import MDAnalysis as mda; print(mda.__version__)"`)

**Comment by lohani2280** [comment]
I am a newcomer here and while i was going through the wiki-page to setup my development environment for MDAnalysis i found this small typo error.

**Comment by kain88-de** [comment]
@lohani2280 should be able to edit the wiki yourself. It would be nice if you can do that thanks.

**Comment by lohani2280** [comment]
@kain88-de I made the correction. Thanku.
