### ISSUE TITLE
Reactivate OSX tests in travis

### ISSUE THREAD

**Issue by jbarnoud** [MDAnalysis/mdanalysis#1217]
With #1216, we deactivated the Travis tests for OSX. The tests were erroring already for a long time so that they were "allowed to fail".

Ultimately, the travis tests on OSX should be fixed and reestablished.

**Comment by kain88-de** [comment]
The error was simple. We set the language to python which starts a apt-install script that will fail for OSX. Setting the language to generic should fix the build 

But like I mentioned in the PR the OSX resources on travis are limited to 128 runners with a regular backlog of 1000 builds for the OSX queue.  The questions is what tests to we really need on OSX that aren't equally done by the linux build. As I remember we only run OSX builds for installation tests.

**Comment by richardjgowers** [comment]
I'd like at least the full build. The chances of the build failing are low, but it has happened on this project before.

**Comment by richardjgowers** [comment]
I did try and get OSX working in #1148 by setting the build language to default/ruby but it didn't immediately work, I can't remember the error it gave though.

https://github.com/conda/conda/blob/master/utils/travis-bootstrap-conda.sh#L18

This looks like a way to generically install conda on either mac or linux on Travis which might work.

**Comment by kain88-de** [comment]
We don't have problems installing conda on osx. Setting the language to generic should be enough. But  I'm saying again that OSX resources are limited. Once the OSX builds take 40 min we might also be getting less priority in the queue resulting in CI taking 12h and more since we need to wait that long for travis to give us a osx worker.

**Comment by hainm** [comment]
I normally obly setup nightly build with osx.

**Comment by hainm** [comment]
Pretty fast to have the job running (new york time)

**Comment by richardjgowers** [comment]
Fixed in #1282
