### ISSUE TITLE
Can't get the position of atoms when loading a simple PDB file with kwarg "format"

### ISSUE THREAD

**Issue by jp43** [MDAnalysis/mdanalysis#1219]
### Expected behaviour

import MDAnalysis
u = MDAnalysis.Universe('start.pdb', format='pdb')

ligand = u.select_atoms('resname LIG')
print ligand.positions

[[  0.52499998 -14.05200005   6.47700024]
 [ -0.42699999 -13.18900013   7.6500001 ]
 [ -0.33000001 -14.24300003   5.49399996]
 [  1.85300004 -14.43700027   6.54300022]
 [ -1.92999995 -13.13799953   6.70800018]
 [ -1.55900002 -13.79899979   5.58099985]
 [  2.67700005 -14.07800007   7.56099987]
 [ -3.21499991 -12.53199959   7.07399988]
 [  3.9690001  -14.5          7.50400019]
 [  2.27200007 -13.39000034   8.5010004 ]
 [ -4.00199986 -12.18799973   6.20200014]
 [ -3.48300004 -12.3579998    8.24800014]
 [  4.954      -14.17000008   8.54800034]
 [  4.97200012 -15.26200008   9.58600044]
 [  4.85900021 -16.62100029   9.1960001 ]
 [  5.09800005 -14.92199993  10.94799995]
 [  4.87200022 -17.63800049  10.17099953]
 [  5.11199999 -15.93200016  11.92800045]
 [  5.         -17.29899979  11.54599953]
 [  5.00699997 -18.28499985  12.5       ]
 [  6.36999989 -18.68000031  12.74300003]
 [  6.79500008 -19.05500031  11.83500004]
 [ -2.23000002 -13.94799995   4.81099987]
 [  4.25600004 -15.04599953   6.73699999]
 [  4.71299982 -13.23200035   9.00199986]
 [  5.92399979 -14.0909996    8.10400009]
 [  4.7670002  -16.86499977   8.19699955]
 [  5.17999983 -13.93200016  11.22700024]
 [  4.78900003 -18.62700081   9.88799953]
 [  5.204      -15.68099976  12.92500019]
 [  6.3920002  -19.45000076  13.48600006]
 [  6.94799995 -17.8390007   13.06400013]
 [  6.79500008 -19.05500031  11.83500004]]

### Actual behaviour

import MDAnalysis
u = MDAnalysis.Universe('start.pdb', format='pdb')

ligand = u.select_atoms('resname LIG')
print ligand.positions

Traceback (most recent call last):
  File "find_exit_path.py", line 8, in <module>
    print ligand.positions
  File "/nfs/r720-1/preto/.local/lib/python2.7/site-packages/MDAnalysis/core/AtomGroup.py", line 1044, in __getattr__
    self.__class__.__name__, name))
AttributeError: 'AtomGroup' object has no attribute 'positions'

### Code to reproduce the behaviour
See above (I guess it should fail with any .pdb file)

### Currently version of MDAnalysis:
(run `python -c "import MDAnalysis as mda; print(mda.__version__)"`)
0.13.0 and later

**Comment by richardjgowers** [comment]
Thanks for the report, this is a strange one, it ended up being because lower case characters were used in the format= string. If you do `format='PDB'` it should work again. 

@jp43 can you confirm that using upper case fixes this for you? 

I've checked the current development branch and we've accidentally fixed this bug, so it's already fixed. I'll push some tests that we should have had before.
