### ISSUE TITLE
bring back expressive repr for Atom, Residue, Segment

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/mdanalysis#1221]
Pre-new topology I could easily see what atoms and residues I selected by just looking at the `repr` of a `Atom` or `Residue`. That was very useful to me when doing interactive work. With the new topology system, only index numbers are shown. This is not very helpful. 

We might have had a discussion about this (can't find it, though) but I now realize that the explicit representation was a rather good and user-friendly feature. Can we bring it back?

### Expected behaviour

```python
In [3]: import MDAnalysis as mda; from MDAnalysis.tests.datafiles import PSF, DCD

In [4]: u = mda.Universe(PSF, DCD)

In [5]: list(u.atoms[:3])
Out[5]:
[<Atom 1: N of type 56 of resname MET, resid 1 and segid 4AKE>,
 <Atom 2: HT1 of type 2 of resname MET, resid 1 and segid 4AKE>,
 <Atom 3: HT2 of type 2 of resname MET, resid 1 and segid 4AKE>]

In [6]: list(u.atoms.residues[:3])
Out[6]: [<Residue MET, 1>, <Residue ARG, 2>, <Residue ILE, 3>]

In [7]: list(u.atoms.segments)
Out[7]: [<Segment 4AKE>]
```

### Actual behaviour
```python
In [36]: u = mda.Universe(PSF, DCD)

In [37]: list(u.atoms[:3])
Out[37]: [<Atom 0>, <Atom 1>, <Atom 2>]

In [38]: list(u.atoms.residues[:3])
Out[38]: [<Residue 0>, <Residue 1>, <Residue 2>]

In [39]: list(u.atoms.segments)
Out[39]: [<Segment 0>]
```

### Currently version of MDAnalysis:
(run `python -c "import MDAnalysis as mda; print(mda.__version__)"`)

'0.16.0-dev0' vs '0.15.0'

**Comment by richardjgowers** [comment]
I think it's just we haven't reimplemented it yet rather than it was
ditched.

With the Group reprs, I think we wanted ndarray style truncation for large
groups

**Comment by orbeckst** [comment]
That would be nice!
