### ISSUE TITLE
Smart Reprs for Groups

### ISSUE THREAD

**Issue by richardjgowers** [MDAnalysis/mdanalysis#1223]
In PR #1222 we fix the `repr`to match old behaviour, but this  makes `Residue/SegmentGroup` representation a little long as it will *always* print the repr of each member:

```python
u = mda.Universe(PSF, DCD)

rg = u.residues[:10]

<ResidueGroup [<Residue MET, 1>, <Residue ARG, 2>, <Residue ILE, 3>, <Residue ILE, 4>, <Residue LEU, 5>, <Residue LEU, 6>, <Residue GLY, 7>, <Residue ALA, 8>, <Residue PRO, 9>, <Residue GLY, 10>]>
```

TODO: 
 - Implement both `__str__` and `__repr__` for `AtomGroup`, `ResidueGroup`, and `SegmentGroup`.  Ideally this is done in a generic way in `GroupBase`
 - `__repr__` is to be short and terse (similar to how AtomGroup is now) ie `'<ResidueGroup with 5 Residues>'`
 - `__str__` is to be long, pretty and informational, similar to how `ResidueGroup` is currently, so `AtomGroup` needs a similar treatment.
 - the `str` representation needs to truncate itself if the Group is over 10 members, and instead only show the first and last three members in a verbose way.  This is similar to how long numpy arrays truncate the repr of themselves:

```python
np.arange(10000)
array([   0,    1,    2, ..., 9997, 9998, 9999])

```

**Comment by orbeckst** [comment]
I like your proposal
- `≤ 10` items: show full
- `> 10` items: show first three and last three

For `AtomGroup`: for consistency showing `Atom` reprs in the same way would be good although I also like the quick overview over how many items there are. 

In fact I would also be fine with the following:
- For all `Group` instances, just show a summary repr such as `<AtomGroup with N atoms>` or `<ResidueGroup with N residues>`.
- `list(group)` gives a full list of representations, `np.array(group)` gives an object array that is then formatted according to the numpy pretty printing style.

This would keep things compact (Dr @dotsdl would probably be happier) but still allow sufficient detail for anyone who wants to look (like myself).

**Comment by dotsdl** [comment]
@orbeckst can we do ``__repr__`` giving the summary like ``<AtomGroup with N atoms>`` and ``__str__`` giving the list of representations with compacting? This way one can always do ``print(ag)`` to get a more detailed picture.

``list(atomgroup)`` should do what ``list(<iterable>)`` would be expected to do: give a list of individual ``Atom`` objects in order represented in the ``AtomGroup``. Not sure what we should expect ``np.array(atomgroup)`` to do, but I guess it would do something similar but give a numpy array instead.

**Comment by orbeckst** [comment]
Compact `repr` and smart extended `str` sounds good to me. If `list()` always work (i.e., the items have good `repr`) then I am happy. `array` was an afterthought (mainly so that we don't have to think about smart representations...).

**Comment by richardjgowers** [comment]
Yeah I like the use of `repr` being terse and like current AG, and `str` being longwinded like the current RG.  Single item `repr` can be long too
