### ISSUE TITLE
tests for indexError exception in hbond_analysis.py file #597 (https://github.com/MDAnalysis/mdanalysis/issues/597)

### ISSUE THREAD

**Issue by kash1102** [MDAnalysis/mdanalysis#1229]
https://coveralls.io/builds/10401476/source?filename=miniconda%2Fenvs%2Fpyenv%2Flib%2Fpython2.7%2Fsite-packages%2FMDAnalysis%2Fanalysis%2Fhbonds%2Fhbond_analysis.py#L775

approach is to make the index out of range

    def test_get_bonded_hydrogen_list(self, **kwargs):
    	kw = self.kwargs.copy()
        kw.update(kwargs)
        h = MDAnalysis.analysis.hbonds.HydrogenBondAnalysis(self.universe, **kw)
        self.universe.atoms[0].index = -2
        array = h._get_bonded_hydrogens_list(self.universe.atoms[0],**kw)
        assert_equal(len(array),0)

**Comment by jbarnoud** [comment]
It seems you tried to write the body of your issue in the title. Could you please reformat the issue so we can get the content?

**Comment by kash1102** [comment]
@jbarnoud  basically testing for exception IndexError in hbond_analysis.py

**Comment by kash1102** [comment]
@jbarnoud @richardjgowers  could you please look into my code and give me some inputs whether it is fine or do i need to change it, I have made 2 test functions for exception raised (referring to issue #597), also did a pull request.Any inputs on this would  be appreciated.
Thanks :)

**Comment by orbeckst** [comment]
The corresponding PR has been closed so I am closing this issue.
