### ISSUE TITLE
Make setup script able to install optional dependencies

### ISSUE THREAD

**Issue by GoogleCodeExporter** [MDAnalysis/mdanalysis#123]
Add some option to setup.py script so one can install dependencies that are not vital for MDAnalysis but may be useful for some users (e.g. netCDF4 for AMBER users).

Quote from issue #122 topic:

" specifying `--install-dependencies=AMBER` or `--install-dependencies=analysis` or `--install-dependencies=all` you would have `setup.py` also try to install the *extras_require* dependencies of the given tag."

Original issue reported on code.google.com by `sebastie...@gmail.com` on 20 Dec 2012 at 8:32
* Blocked on: #125

**Comment by jbarnoud** [comment]
Isn't that fixed? The shortcut to install all the dependencies is not implemented, but do we need it? If we do need it I can add it.

**Comment by kain88-de** [comment]
how is this possible right now?

**Comment by jbarnoud** [comment]
I read the issue to fast. I thought it was with pip, not directly from the setup.py. My bad.

**Comment by orbeckst** [comment]
Is this something we need? We can also tag it with *wont fix* and close it --- should the necessity ever arise again, we can reopen.
