### ISSUE TITLE
Tag unit testing failures for optional dependencies as known failures

### ISSUE THREAD

**Issue by GoogleCodeExporter** [MDAnalysis/mdanalysis#124]
When running a test that concerns an optional dependency which is not installed on the testing machine, it is assumed that the test will fail due to the dependency not being installed (and not due to a possible bug). The idea is to tag this kind of failure as "known" failure while allowing the test to "properly" fail when the failure is not related to the lack of dependency.

By doing so, an user that is not using the optional dependency will be able to run tests without the output being "polluted" by false positives.

Yet, a warning should be raised in the case a known failure to remind  developers that they should take care of it.

Original issue reported on code.google.com by `sebastie...@gmail.com` on 20 Dec 2012 at 8:46

**Comment by richardjgowers** [comment]
So now we've got travis we should be able to include this as part of the build matrix, so we build with
 - everything (current build, mda with all the optional stuff)
 - only MDA + required deps (and have all optional stuff known fail)

I think our only optional dependencies are NCDF and matplotlib.  I thought scipy was too, but it's in the required in `setup.py`.. so maybe that's a mistake.

**Comment by orbeckst** [comment]
The full functional core (i.e. not analysis or visualization) needs

* numpy
* biopython
* netCDF4

Analysis wants for full functionality

* networkx
* GridDataFormats
* matplotlib
* scipy

Not all of these are easy to install with `pip` so we went with a compromise to make the most functionality immediately available while also reducing entry hurdles and installation pain:
We are currently requiring all the packages that install easily with `pip`:

* numpy
* biopython
* networkx
* GridDataFormats

and make others like `netCDF4` optional (which is only used for the binary AMBER reader and if it is not available, the user gets a detailed error message pointing to [ncdf installation information](https://github.com/MDAnalysis/mdanalysis/wiki/netcdf)). `matplotlib` used to be a pain to install with pip so we leave that to the user and their package manager.

**Comment by richardjgowers** [comment]
https://github.com/MDAnalysis/mdanalysis/blob/develop/package/setup.py#L267

Does this mean scipy is required?  I think you're right in that it's not used anywhere but analysis... if memory serves.

**Comment by orbeckst** [comment]
Hm, I am confused (read: to lazy to look up at the moment) what `requires` does compared to `install_requires` in `setup.py`. If `requires` just advertises all the packages that you *might* want then `scipy`, `matplotlib`, `mayavi` should all be in there. If `pip` tries to pull those in, then `scipy` should not be in there.

**Comment by richardjgowers** [comment]
I'm going to bump this because installing netcdf isn't trivial and running all the tests without it gives a lot of Error results

**Comment by orbeckst** [comment]
So you want a decorator that decides that if netcdf is not installed then it should be a knownfailure? I think `@knownfailure_if` (or similar) already exists; it is used for the HOLE and CLUSTALW tests.

**Comment by richardjgowers** [comment]
Yeah I was thinking along those lines, I didn't know it already existed.  I'll look into those

**Comment by orbeckst** [comment]
Btw, the conda install magically installs netcdf (it seems), at least that was my experience when I tested [conda-based installation](http://becksteinlab.github.io/MDAnalysis-workshop/install_conda.html) on a pristine VM.

**Comment by hainm** [comment]
> I'm going to bump this because installing netcdf isn't trivial and running all the tests without it gives a lot of Error results

with conda, it's trivial. :D

**Comment by orbeckst** [comment]
Something along [executable_not_found_runtime()](https://github.com/MDAnalysis/mdanalysis/blob/develop/testsuite/MDAnalysisTests/__init__.py#L152); in fact it should be used with `@dec.skipif`.

**Comment by richardjgowers** [comment]
It was possible with our existing `knownfailure` decorator, if you specify that ImportError is the expected failure.  I think I'll put a layer around `knownfailure` which specifies `knownfailure_if(test)`.  So if test returns True, it's expected to fail.  Then test can be something simple like

``` python
import MDAnalysis as mda

def check_ncdf():
    try:
        import netCDF
    except ImportError:
       return True
    else
       return False

@knownfailure_if(check_ncdf)
def test _ncdfthing
```

I think I can get that bundled with 0.12.1.

Then going forward we want our travis build to have another dimension, which is testing both minimal and full installations.

**Comment by mnmelo** [comment]
That's a cool idea @richardjgowers. We can even overload the already existing knownfailure to take an argument `only_if`, that defaults to `True`.

What do you think? I'll be glad to make a PR for it.

**Comment by richardjgowers** [comment]
Yeah a kwarg for knownfailure might be smarter actually.  If you want to take this that would be great.

**Comment by mnmelo** [comment]
In the end I think @orbeckst's skipif way is cleaner. Had to decorate each and every test under the netCDF test classes. These numpy decorators can't be applied to classes.

**Comment by richardjgowers** [comment]
I had luck just decorating the setUp method?

**Comment by mnmelo** [comment]
Ah, should have tried that! ;)
