### ISSUE TITLE
enable "auto cancel pushes" on Travis

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/mdanalysis#1243]
Travis announced **Auto Cancellation : Get faster results by only testing your most recent build**  travis-ci/beta-features#8 as beta feature.

[Discussion on the dev list](https://groups.google.com/d/msg/mdnalysis-devel/eUe4N_RKrX4/mxZTjKLXBQAJ) says that we want to enable this feature as soon as possible to reduce queue time in frequent builds/pushes.

Some repos are already using the feature (eg see https://github.com/obspy/obspy/pull/1713#issuecomment-286562994 ) but I don't yet see an option to enable this feature. In some cases, new beta features can be enabled on https://travis-ci.org/features but I don't yet see a switch for *Auto cancel pushes*.

(PS: While exploring the beta features page I also found the setting for [beta dashboards](https://blog.travis-ci.com/2017-02-28-introducing-dashboard) on Travis.org: I like it quite a bit!)

**Comment by kain88-de** [comment]
I'll send them a message to the support email.

**Comment by kain88-de** [comment]
I've just enabled the feature on travis for pull requests and pushes to local branches. They've asked for feedback about the feature on the issue @orbeckst linked above.

**Comment by orbeckst** [comment]
Awesome – the settings are now on our settings page and enabled.
