### ISSUE TITLE
Doc for keyword *bonds* of PDBWriter is wrong

### ISSUE THREAD

**Issue by jbarnoud** [MDAnalysis/mdanalysis#1246]
The documentation of `PDBWriter.__init__` tells:

```
*bonds*
           write bonds to the PDB file as CONECT_ records [``False``]
```

This is in contradiction with the signature of the signature that tells that the default value for the argument is `"conect"`. It is also in contradiction with the code of `PDBWriter._write_pdb_bonds`:

```python
        # Write out only the bonds that were defined in CONECT records
        if self.bonds == "conect":
            bonds = ((bond[0].index, bond[1].index) for bond in bondset if not bond.is_guessed)
        elif self.bonds == "all":
            bonds = ((bond[0].index, bond[1].index) for bond in bondset)
        else:
            raise ValueError("bonds has to be either None, 'conect' or 'all'")
```

**Comment by orbeckst** [comment]
So basically just change the docs (while changing to numpy style):
```rest
bonds : {"conect", "all", None} (optional)
     If set to "conect", then write those bonds to the output file that were already defined in an input PDB file as PDB CONECT_ records. If set to "all", write all bonds (including guessed ones) to the file. ``None`` does not write any bonds. The default is "conect". 
```

Have we got a test case?

**Comment by Shtkddud123** [comment]
Dear all, 

Hopefully I've done things as requested, and I apologise again for my rookie-ness. I've updated the doc in a numpy style, and written it here: 

https://github.com/Shtkddud123/mdanalysis/blob/develop/package/MDAnalysis/coordinates/PDB.py]

Please let me know if this is satisfactory. I'm still committed to the curvature studies, whether part of GSOC or not;  I'll try to get a preliminary code on it working out a simple x-y plane meshgrid style hopefully sometime next week. 

Thanks

Yours Sincerely

Sang

**Comment by jbarnoud** [comment]
Rookie-ness is normal when you begin. Don't worry about that, you will learn.

I've seen that you updated the documentation for the PDB writer in the pull request about the distance calculation. Since these are two unrelated issues, they should be tackled in two different pull request. Could you [create a new branch](https://git-scm.com/book/en/v2/Git-Branching-Basic-Branching-and-Merging) for your change in the PDB documentation, and submit a new pull request on that issue?
