### ISSUE TITLE
universe( "xxx.pdb", format="pdb") gives wrong dimension

### ISSUE THREAD

**Issue by yanmingwang88** [MDAnalysis/mdanalysis#1253]
### Expected behaviour
u=mda.Universe("xxx.pdb",format="pdb")
u.select_atoms("around 3.0 protein")
should have the same result as:
u=mda.Universe("xxx.pdb",format="PDB")
u.select_atoms("around 3.0 protein")

### Actual behaviour
will prompt error:
AttributeError: 'AtomGroup' object has no attribute 'dimensions'

### Code to reproduce the behaviour

``` python
import MDAnalysis as mda
from MDAnalysisTests.datafiles import PDB
u=mda.Universe(PDB,format="pdb")
u.select_atoms("around 3.0 protein")

....

```

### Currently version of MDAnalysis:
0.15.0

**Comment by jbarnoud** [comment]
Thanks for reporting the issue. It appears that it is fixed in the development version.

@yanmingwang88 You can find the instructions on how to install the development version [on our wiki](https://github.com/MDAnalysis/mdanalysis/wiki/Setup-Development-Environment).
