### ISSUE TITLE
remove deprecated code in analysis.contacts

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/mdanalysis#1276]
`analysis.contacts` contains lots of old code that is scheduled for removal.

- [ ] remove deprecated functions in package/MDAnalysis/analysis/contacts.py 
- [x] check that all references to the remove functions are removed from the docs
- [ ] add CHANGELOG entry

**Comment by orbeckst** [comment]
P.S.: This is one of the easiest coverage boosts that I can think off...

**Comment by orbeckst** [comment]
Oops... scheduled for 0.17 can't score this one for 0.16.

**Comment by kain88-de** [comment]
Yeah I was wondering.  I recently removed all left over deprecations for this release.

**Comment by orbeckst** [comment]
@kain88-de , when did you add the new `Contacts` class (the docs don't have a `.. versionadded` tag), namely had we had those already in 0.15.0 ?

If yes, I'd be willing to just schedule them for early removal ahead of schedule... there are so many changes in 0.16.0 that we might as well throw it in there.

**Comment by kain88-de** [comment]
I'm  sure that class is new. Even if not. I don't like to remove it before the advertised schedule.

**Comment by orbeckst** [comment]
ok

> On 1 Apr, 2017, at 10:39, Max Linke <notifications@github.com> wrote:
> 
> I'm sure that class is new. Even if not. I don't like to remove it before the advertised schedule.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

--
Oliver Beckstein * orbeckst@gmx.net
skype: orbeckst  * orbeckst@gmail.com
