### ISSUE TITLE
convert all docs to numpy style

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/mdanalysis#1277]
According to our [Style Guide](https://github.com/MDAnalysis/mdanalysis/wiki/Style-Guide#writing-docstrings), all doc strings should be in written with the [numpy doc formatting](https://github.com/numpy/numpy/blob/master/doc/HOWTO_DOCUMENT.rst.txt). All new docs are being written according to this style (and for an example see the numpy [doc/example.py](https://github.com/numpy/numpy/blob/master/doc/example.py)). 

Old docs need to be manually converted:

- [x] core library: see PR #1247 (@jbarnoud)
- [x] analysis module: see PR #1240 (@orbeckst)
- [ ] visualization module: TODO

**Comment by orbeckst** [comment]
@tylerjereddy could you have a look at your code in visualization to update the docs to numpy style when you have a moment? Thanks.

**Comment by orbeckst** [comment]
@tylerjereddy ... or if you can find someone willing to do it (new contributors, anyone?) feel free to delegate. But all in visualization is your code so I think you should at least review any changes there.

**Comment by kain88-de** [comment]
Are all docs now really numpy style?

**Comment by orbeckst** [comment]
I think so... always possible that we missed something, of course.

Just did a 
```
git grep :Keywords:
```
and got
```
MDAnalysis/analysis/contacts.py:        :Keywords:
MDAnalysis/coordinates/PDB.py:        :Keywords:
MDAnalysis/core/topologyobjects.py:        :Keywords:
MDAnalysis/core/topologyobjects.py:        :Keywords:
```
so probably a few stragglers that need to be mopped up.

**Comment by kain88-de** [comment]
Contacts is deprecated classes that will be removed soon.
