### ISSUE TITLE
Windows 10 WSL work -- getting MDA running on Windows 10 (rough steps)

### ISSUE THREAD

**Issue by tylerjereddy** [MDAnalysis/mdanalysis#1285]
The Windows 10 - Windows subsystem for linux (WSL) is officially supported by Microsoft and is currently in beta. This allows for effectively native use of bash on Windows, with various caveats, but far lighter weight than i.e., a virtualization or even containerization approach.

I have access to a Windows 10 machine now and naturally the first thing I tried to do was install MDA in the WSL. Here are my results (mostly positive; perhaps one or two mysteries to solve, but looks very promising I think):

 - follow the [WSL install guide](https://msdn.microsoft.com/en-us/commandline/wsl/install_guide)
 - after installing, [consult the docs as needed](https://msdn.microsoft.com/commandline/wsl/about)
 - to start ubuntu, open cmd prompt and type `bash`
 - current version of ubuntu used by default is: Ubuntu 14.04.5 LTS; this default will change to 16.04 with the next major patch (Creators Update) ~April  11/ 2017
 - working in bash inside cmd prompt:
```
sudo apt-get install git
mkdir github_projects
```
 - created a new path at: `/mnt/c/Users/treddy/github_projects`
 - confirmed that this is also clearly visible via Windows File Explorer
 - clone the latest development branch of MDAnalysis at the above path: `git clone https://github.com/MDAnalysis/mdanalysis.git`
 - install conda / python dependencies; use apt to install: gcc; 
 - build MDA: `python setup.py install --user`
   - note: a bit buggy with no output displayed on first attempt (similar issue with conda install commands; sometimes there's success with less output than normal); reopened cmd prompt / bash shell to try again and normal MDA compilation output is displayed; 
   - no errors and: "Finished processing dependencies for MDAnalysis==0.16.0.dev0" (!!!!!)
 - build the test suite with same setup command as above; installed normally with no errors
 - run the recommended test suite command: `./mda_nosetests --exe -v --processes=4 --process-timeout=120`
   - I see some tests passing and some strange errors mixed in, many look like the following:     
      - "OMP: Error #100: Fatal system error detected."
 - try a different approach from `IPython`
```python
from MDAnalysis.tests import test
test(argv=["--exe", "-v"])
```
`"test_AlignTraj (MDAnalysisTests.analysis.test_align.TestAlign) ... OMP: Error #100: Fatal system error detected.
OMP: System error #22: Invalid argument
Aborted (core dumped)"`

 - ok, so unit test aren't working yet, what about a simple universe load:
```python
In [1]: import MDAnalysis
In [2]: from MDAnalysisTests.datafiles import PSF, DCD
In [4]: u = MDAnalysis.Universe(PSF, DCD)
In [5]: u
Out[5]: <Universe with 3341 atoms>
```
  - looks ok
 - what about accessing a coordinate file saved separately to the windows file system from within Windows Subsystem for Linux:
   - Downloaded `5JFB.pdb` to Windows 10 Desktop
```python
u = MDAnalysis.Universe('/mnt/c/Users/treddy/Desktop/5jfb.pdb')
In [7]: u
Out[7]: <Universe with 802 atoms>
In [9]: u.atoms.positions
Out[9]:
array([[ -8.06299973,   9.11900043, -16.37599945],
[ -7.41599989,   9.1789999 , -15.03199959],
[ -5.88500023,   9.10000038, -15.13199997],
...,
[-10.19200039,  12.7489996 ,   0.161     ],
[  3.62199998,  -5.67799997,  -6.42000008],
[ -0.64399999,  22.27099991,   3.34299994]], dtype=float32)
```

**Comment by orbeckst** [comment]
See also #450 and Wiki:[MDAnalysis on Windows](https://github.com/MDAnalysis/mdanalysis/wiki/MDAnalysis-on-Windows)

**Comment by kain88-de** [comment]
Hm strange. I know from a colleague that MDAnalysis works for him on windows 10 without problems using their linux kernel interface.

**Comment by tylerjereddy** [comment]
@kain88-de It works pretty well I think apart from the unit testing issue. The platform itself is still in beta so naturally I do see some things on the command line that are slightly suspicious, but somehow pretty much everything works quite well.

I'll experiment with it a bit more as time permits and see if the approach from @richardjgowers alleviates the unit testing issue. I should also check if OMP has known issues on the platform / fixes planned, etc., or if it is just something on my machine.

**Comment by tylerjereddy** [comment]
Ok, I've fixed up the formatting mess in my original post.

Also, I see the wiki link from @orbeckst beat me to it, but as this is more recent & I'm likely to experiment with developing on the platform as well (if the full test suite starts working), I'll keep the issue open in case I need to ask questions/ make useful notes.

**Comment by tylerjereddy** [comment]
I tried setting the environment variable `export KMP_AFFINITY="disabled"` in my `~/.bashrc`, which seemed to alleviate the issues described above with OMP--as described for another python package here--https://github.com/Microsoft/BashOnWindows/issues/785

However, now when running the unit tests output eventually gets suppressed / muted in either `IPython` or the conventional `Python` prompt. Consider the following input / output:

```python
>>> from MDAnalysis.tests import test
>>> test(argv=["--exe"])
```
output (notice muting after generation of new / spurious prompt line):
```
...............S.......................................................................S...................SSSS..S..SS.S.S...S................................................................SSSSSSSS..............................................................................................................................................................................................................................................>>>
```
Since the above referenced Microsoft issue was closed largely in reference to fixes made in the newer 16.04 / patch build, it may be that this issue will not exist after the patch.

**Comment by tylerjereddy** [comment]
Running `nosetests (module name)` generally works fine on a smaller scale though, so I think the problem is pretty superficial, and doesn't really interfere with development substantially given the reliance on Travis anyway.

**Comment by tylerjereddy** [comment]
MDAnalysis can be developed / used just fine on WSL now so closing this.

Apparently there's now support for more than just Ubuntu in the subsystem as well.
