### ISSUE TITLE
Oldest compatible numpy version is 1.9.3

### ISSUE THREAD

**Issue by kain88-de** [MDAnalysis/mdanalysis#1286]
### Expected behaviour

We claim to support numpy 1.5 and upwards.

### Actual behaviour

Everything below 1.9.3 has a lot of errors in the testsuite or just crashes. For 1.9.3 we just seems to have some accuracy errors for regression tests. 

Here are links to travis runs

[Numpy 1.10.4](https://travis-ci.org/MDAnalysis/mdanalysis/builds/219240316)
[Numpy 1.9.3](https://travis-ci.org/MDAnalysis/mdanalysis/builds/219234044)
[Numpy 1.8.3](https://travis-ci.org/MDAnalysis/mdanalysis/builds/219230330)
[Numpy 1.7.1](https://travis-ci.org/MDAnalysis/mdanalysis/builds/219227618)
[Numpy 1.6.2](https://travis-ci.org/MDAnalysis/mdanalysis/builds/219223754)
[Numpy 1.5.1](https://travis-ci.org/MDAnalysis/mdanalysis/builds/219212223)

I suggest we fix the tests and bump the minimum version to 1.9.3

**Comment by richardjgowers** [comment]
Is this just as simple as updating the requirements in setup.py?

**Comment by kain88-de** [comment]
I don't know where else we specify the numpy requirements

**Comment by orbeckst** [comment]
Thanks for checking! 

IIRC `setup.py` is the one that matters; possibly some requirements files (?), possibly docs, possibly [PyPi page](https://pypi.python.org/pypi/MDAnalysis) (not sure if the *Requires* is generated from `setup.py`).

Perhaps we should have a Travis Cron job that periodically tests the claimed minimal compatible versions? We certainly don't have to do this on each PR.
