### ISSUE TITLE
update copyright year

### ISSUE THREAD

**Issue by kain88-de** [MDAnalysis/mdanalysis#1298]
I noticed our copyright headers all say 2016. Do we have a script that did the update last year?

**Comment by orbeckst** [comment]
I *thinkk* @tylerjereddy did it the last time... wasn't there a script attached to an older issue?

**Comment by tylerjereddy** [comment]
Yeah, it is associated with https://github.com/MDAnalysis/mdanalysis/pull/1001, which was superseded by efforts from @kain88-de using my script available in a github repo here: https://github.com/tylerjereddy/headerfix

I'm guessing @kain88-de might have had to make one or two changes before using it.
