### ISSUE TITLE
build binary .whl packages ?

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/mdanalysis#1300]
Is there a simple way or a build service that we could use to also build binary wheel (`.whl`) packages (for Linux and OSX), in addition to the conda packages?

- There are Linux build system docker images available at https://github.com/pypa/manylinux
- For OSX we could probably use travis.

**Comment by hainm** [comment]
just FYI: Since I only release `pytraj` one or two times a year, I build everything on my Mac (for OSX) with docker (for Linux) with a single script. Setting up things on different services is much time consuming. :D 

To speeding things up, you can build wheel first and then use that file to build conda.

**Comment by hainm** [comment]
Oh conda build has option to build wheel too.

**Comment by orbeckst** [comment]
As @Luthaf in https://github.com/MDAnalysis/mdanalysis/issues/1194#issuecomment-345390925 said, he wrote a script to build wheels from conda packages https://github.com/chemfiles/conda-to-wheels – we could adapt it for MDAnalysis, too.

**Comment by orbeckst** [comment]
> Oh conda build has option to build wheel too.
Does it? That would be even easier...

Do you mean https://github.com/JanSchulz/conda-build-wheel ?

**Comment by kain88-de** [comment]
Building a wheel isn’t hard. The problem is to get it running on a lot of hardware. The manylinux docket image will help. We have to think about the numpy  version we build against though.

**Comment by Seanny123** [comment]
Is this relevant again now that the build system is being updated in https://github.com/MDAnalysis/mdanalysis/pull/3398?

**Comment by tylerjereddy** [comment]
Maybe, but have to be cautious of the maintenance burden/increasing complexity of the release process. A lot of upstream packages spend a considerable amount of bandwidth on this stuff. At least we don't have Fortran code, last time I checked.

**Comment by Seanny123** [comment]
I've built MDAnalysis wheels for Linux using `manylinux` for internal use at ProteinQure and it worked pretty well. I'll watch that PR and make a PR afterwards adding a script for creating releases.

**Comment by Seanny123** [comment]
Actually, looking at the CI, what's the process for uploading a release? Is this process written down anywhere?

**Comment by richardjgowers** [comment]
https://github.com/MDAnalysis/mdanalysis/wiki/PreparingReleases

Docs above, We upload to pypi then that triggers the conda forge builds.

**Comment by IAlibay** [comment]
:P Richard beat me to the response - releases are currently done out of CI for now. We're planning to move part of that infrastructure to a github action in the (hopefully near) future [probably coupled with a move towards fortnightly dev builds].

Any suggestions / ideas / etc... here are very much appreciated.

**Comment by Seanny123** [comment]
As documented in the [`manylinux` repository](https://github.com/pypa/manylinux) the best way to build wheels is using the provided Docker image:
```
git clone git@github.com:MDAnalysis/mdanalysis.git
docker run --rm -it -v (pwd)/mdanalysis:/io/mdanalysis quay.io/pypa/manylinux_2_24_x86_64 /bin/bash
```

Once inside the image, wheels for all supported Python versions can be built:
```
cd mdanalysis/package
/opt/python/cp37-cp37m/bin/python setup.py bdist_wheel
/opt/python/cp38-cp38/bin/python setup.py bdist_wheel
/opt/python/cp39-cp39/bin/python setup.py bdist_wheel
/opt/python/cp310-cp310/bin/python setup.py bdist_wheel
```

Then, after exiting the docker image, the wheels can be uploaded using `twine`:
```
twine upload dist/*
```

These wheels would be uploaded in addition to the source code tar ball.

If you give me edit access to your wiki, I can add these instructions. I could also add these wheels to PyPi if you'd like.

I do not yet know how to build a wheel for OS X or Windows.

This could also be integrated into a GitHub Action, but that can be discussed on another issue.

**Comment by IAlibay** [comment]
Thanks for the details @Seanny123 - I'm currently looking at implementing wheel deployment via cibuildwheel but there's a few things about our install & release process I want to clean up before I get to it. I'll ping back something here in a week or two hopefully.

**Comment by Seanny123** [comment]
Yes, please use `cibuildwheel`. I'm not discovering the process I described creates an invalid distribution which causes the error:
```
MDAnalysis/lib/_cutil.pyx:1: in init MDAnalysis.lib._cutil
    ???
E   ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 80 from PyObject
```

:man_facepalming:

**Comment by IAlibay** [comment]
Re wiki - I think we had to limit it to folks that have at least one contribution because we had some issues with bots inserting malicious looking links, not sure if there's a way to waive that requirement for a given user

**Comment by Seanny123** [comment]
FYI, further efforts to resolve this incompatibility have only baffled me further.

I tried installing requirements first
```
# also tried numpy==1.18.5
/opt/python/cp39-cp39/bin/python -m pip install numpy==1.19.5 cython
/opt/python/cp39-cp39/bin/python setup.py bdist_wheel
```

This allowed the package to work with `numpy=1.22.3`. However, when I used this wheel with `numpy==1.19.5`, I got the error:

```
RuntimeError: module compiled against API version 0xf but this version of numpy is 0xd
```

Hopefully `cibuildwheel` resolves this, because I'm baffled as to what is happening.

**Comment by Seanny123** [comment]
FYI, I realized this morning I wasn't using the new PEP517 build system. So instead of `setup.py` I should be using:

```
/opt/python/cp39-cp39/bin/python -m pip wheel numpy==1.19.3 --no-deps --wheel-dir=wheelhouse .
```

However, despite specifying to build with numpy==1.19.3, I still get the same error if I use `numpy==1.19.3` instead of `numpy==1.22.3`:
```
RuntimeError: module compiled against API version 0xf but this version of numpy is 0xd
```

**Comment by IAlibay** [comment]
So an update here, using `cibuildwheel` locally works perfectly fine, so it seems like it'll be the way forward. The next step is really to map out how we'll be doing deployment from now on (mostly modifying our current release process with the way `cibuildwheel` likes to do things).
