### ISSUE TITLE
Resides with the same residue id are merged into a single residue

### ISSUE THREAD

**Issue by xiki-tempula** [MDAnalysis/mdanalysis#1306]
### Expected behaviour
When reading a gro file with two residues which have the same residue id (residue GLN/ resid 9;residue POPC/ resid 9), the two residues are treated as two residues. 

### Actual behaviour
The two residues are merged into one residue.

### Code to reproduce the behaviour
``` python
import MDAnalysis as mda
grotest = '''test
2
    9GLN      N  115  12.094  14.850   8.129
    9POPC     N 9039  15.355  18.311   6.914
  25.48044  26.74952  10.00000'''
with open('test.gro', 'w') as f:
    f.write(grotest)
u = mda.Universe('test.gro')
print(u.atoms)
```
Got
```
<AtomGroup [
<Atom 1: N of type N of resname GLN, resid 9 and segid SYSTEM>, 
<Atom 2: N of type N of resname GLN, resid 9 and segid SYSTEM>]>

```
I know that somewhere in the documentation, it is said that atoms with the same residue ids are merged into one residue. 

https://pythonhosted.org/MDAnalysis/documentation_pages/core/AtomGroup.html?highlight=set_resid#MDAnalysis.core.AtomGroup.AtomGroup.set_resid

> Changing resids can change the topology.
> Assigning the same resid to multiple residues will merge these residues. Assigning different resid to atoms in the same residue will split a residue (and potentially merge with another one).

But I guess merging two residues with the same id together and forcefully changing the residue name of the second residue into the first residue name is not the best thing to do if your gro file is read from an existing source. I wonder if it is possible to adopt the logical with atoms in that there is an internal ordering of the residue which serves as an unique identifier and an external ordering which preserves the user content.
### Currently version of MDAnalysis:
py35, mda:0.16.1-dev0

**Comment by richardjgowers** [comment]
Yeah I think we just need to use [`change_squash`](https://github.com/MDAnalysis/mdanalysis/blob/develop/package/MDAnalysis/topology/base.py#L121) in GROParser and pass it both resids **and** resnames so a change in either will trigger a new residue (and avoid squashing it into one residue).  

For example in the PDBParser, we [detect residues based on resids, icodes and segids](https://github.com/MDAnalysis/mdanalysis/blob/develop/package/MDAnalysis/topology/PDBParser.py#L246) though not resnames actually, which means this bug is technically in the PDBParser too.

**Comment by xiki-tempula** [comment]
@richardjgowers  Thank you. I have solved my problem.

**Comment by richardjgowers** [comment]
I think this is still a bug with the GROParser, but I'm not 100% on gromacs.. @jbarnoud does this seem like a valid bug?

**Comment by jbarnoud** [comment]
It is still a valid bug.
It seems that we indeed need to be more careful with how we split residues.

Also:

```
4
    9GLN      N  115  12.094  14.850   8.129
    9POPC     N 9039  15.355  18.311   6.914
   10POPC     N 9039  15.355  18.311   6.914
    9POPC     N 9039  15.355  18.311   6.914
  25.48044  26.74952  10.00000
```

This should be 4 residues. Now it is 2 with all the resid == 9 on the first residue and the resid == 10 in the other.

**Comment by xiki-tempula** [comment]
@richardjgowers @jbarnoud 
I saw in the documentation (https://pythonhosted.org/MDAnalysis/documentation_pages/core/AtomGroup.html?highlight=set_resid#MDAnalysis.core.AtomGroup.AtomGroup.set_resid). It seems that it describes that setting two residues with the same residue id will merge these two residues is an expected behaviour. 

> Changing resids can change the topology.
> Assigning the same resid to multiple residues will merge these residues. Assigning different resid to atoms in the same residue will split a residue (and potentially merge with another one).

**Comment by jbarnoud** [comment]
This was a known behavior of 0.15.0, but not the expected one. It was more of a known bug.
