### ISSUE TITLE
Improving text parsing speeds

### ISSUE THREAD

**Issue by richardjgowers** [MDAnalysis/mdanalysis#1308]
Originally started in #1302 , [in particular this comment](https://github.com/MDAnalysis/mdanalysis/pull/1302#issuecomment-293830546) there's some performance to be found in how we convert ascii to numpy arrays.

## Apply to the following Readers

- [x] XYZ
- [x] PQR
- [x] PDB
- [ ] GRO

**Comment by kain88-de** [comment]
@utkbansal Do you want to help with this? It's mostly smaller changes in the parsing logic of the trajectory readers. In the PR @richardjgowers links to he already lists some readers that definitely have to be changed to use a new string -> float conversion algorithm. But I'm sure other readers will profit from it to. We need to find out which ones that are though.

Here is [gist](https://gist.github.com/anonymous/85e1fb9d329eb42cd82b093c7d85934b) of some benchmarks I did today.

**Comment by utkbansal** [comment]
@kain88-de Sure, I'll start with the GRO format.

**Comment by mnmelo** [comment]
For reference, I was curious as to whether `np.loadtxt` would be faster, if fed the string data via a `StringIO` object. It is not. By a large margin. (turns out the internals of `np.loadtxt` essentially do the line by line splitting anyway at the python level, plus a number of extra checks that we don't need here).

**Comment by kain88-de** [comment]
@utkbansal I recommend to start with xyz or PQR. It isn't that important for GRO where we read only a single frame anyway.

**Comment by orbeckst** [comment]
I am re-targeting this to 0.17.0, at least not 0.16.1 – let's focus on fixing bugs.

**Comment by orbeckst** [comment]
Should we move this to 0.16.1 – the PR #1357 is basically done and I recall @richardjgowers considering this to *fix a performance regression* https://github.com/MDAnalysis/mdanalysis/pull/1302#issuecomment-293849231 so it would be perfectly suitable for a patch release.

**Comment by richardjgowers** [comment]
Yes please

**Comment by orbeckst** [comment]
#1367 does not speed-up GRO – can we do this just so that it is _done_?

**Comment by richardjgowers** [comment]
I can't really see anything wrong with GRO (esp. that got regressed).
