### ISSUE TITLE
no online docs for 0.16.0 release

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/mdanalysis#1315]
The online docs for the stable release at http://pythonhosted.org/MDAnalysis/ have traditionally been hosted on pythonhosted.org. However, this service is now in read-only mode. 

@jbarnoud https://github.com/MDAnalysis/mdanalysis/issues/664#issuecomment-293033814 said:
> It seeams that pythonhosted is deprecated and in read-only mode: https://mail.python.org/pipermail/distutils-sig/2015-May/026381.html

We have been discussing the following options (starting at https://github.com/MDAnalysis/mdanalysis/issues/664#issuecomment-293033814)
* move to Readthedocs (see @dotsdl 's https://github.com/MDAnalysis/mdanalysis/issues/664#issuecomment-293048200)
* create a separate repository for the docs and host as gh-pages (https://github.com/MDAnalysis/mdanalysis/issues/664#issuecomment-293044038)
* interim fix: just change the DNS redirect of http://docs.mdanalysis.org to point to the devdocs (like http://devdocs.mdanalysis.org)

Having online docs available will be the last thing to be done for completing the 0.16.0 release #664

**Comment by orbeckst** [comment]
@dotsdl I have tentatively assigned this issue to you because you have been looking into making the docs work on RTD. Feel free to un-assign yourself but let us know of any progress or barriers.

**Comment by orbeckst** [comment]
I changed the DNS forwarding so that http://docs.mdanalysis.org now does temp redirect (302) to the devdocs http://www.mdanalysis.org/mdanalysis/

**Comment by orbeckst** [comment]
Btw, the devdocs are still at 0.16.0-dev from April 4 – it seems that Travis is not building/pushing devdocs anymore. Has this anything got to do with @kain88-de 's recent changes to the doc building process?

**Comment by orbeckst** [comment]
@dotsdl do you think it is feasible to get our docs to build on RTD?

I'd like to have some closure on 0.16.0...

**Comment by kain88-de** [comment]
@orbeckst how hard would it be to have the docs on our github pages repository? By now we got used to publishing a new blog post anyway so the docs could be part of the same PR in the future. 

I would also like this since it's easier to me. One less service I have to know and it should be possible to add an update of the docs to the release script we currently have.

**Comment by kain88-de** [comment]
Actually having a repository that only contains the docs in a gh_pages branch is very easy to do and creating a  script to automatically create a PR for it when the release-script is run shouldn't be to hard either.

**Comment by orbeckst** [comment]
We could add something to the travis job that pushes a doc update to a pure doc repo whenever something is merged or updated on *master*. Basically, take the current [deploy_docs.sh](https://github.com/MDAnalysis/mdanalysis/blob/develop/maintainer/deploy_docs.sh) script and modify slightly.

One advantage of RTD is (when it works) that you can easily switch between different versions of the docs and that people (and search engines) are really used to it.

**Comment by orbeckst** [comment]
I created https://github.com/MDAnalysis/docs and will play around with pushing into it; I'll first use it as a test bed for PR #1126

**Comment by orbeckst** [comment]
PR #1126 contains [maintainer/deploy_master_docs.sh](https://github.com/MDAnalysis/mdanalysis/blob/new-sphinx-style/maintainer/deploy_master_docs.sh) which can push the docs to [MDAnalysis/docs](https://github.com/MDAnalysis/docs) ; at the moment, they show up as http://www.mdanalysis.org/docs/

The script needs to be adapted when used through travis but manually it works just fine:
```
export GH_TOKEN=secret
cd package && python setup.py build_sphinx
cd .. && ./maintainer/deploy_master_docs.sh
```
(If you want to try it, remove the GH_TOKEN from the script and manually enter username/password.)

**Comment by orbeckst** [comment]
I am going to manually put the docs for master (0.16.0) into the `mdanalysis/doc` repo and then redirect http://docs.mdanalysis.org to http://mdanalysis.org/docs . 

Once this is done, we can integrate the `maintainer/deploy_master_docs.sh` into the Travis matrix.

**Comment by orbeckst** [comment]
We have docs at http://docs.mdanalysis.org so I am closing this issue.

The PR #1365 is needed for 0.16.1.
