### ISSUE TITLE
devdocs deployment broken

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/mdanalysis#1316]
Deploying devdocs appears to have been broken around April 4, 2017. 

Looking at the docs travis task eg in https://travis-ci.org/MDAnalysis/mdanalysis/jobs/222937777 it seems that the deploy script is never being called:

```
if test ${TRAVIS_PULL_REQUEST} == "false" && \ test ${TRAVIS_BRANCH} == ${GH_DOC_BRANCH} && \ test "${BUILD_DOCS}" == "true"; then bash ${TRAVIS_BUILD_DIR}/maintainer/deploy_docs.sh; fi

/home/travis/.travis/job_stages: line 53:  test: command not found
```

See also #1315

**Comment by kain88-de** [comment]
@orbeckst ues this likely broke with the addition of the test command. But I'm surprised that it doesn't work here. Because the ci-helper scripts we are using can use the test command.
