### ISSUE TITLE
feasibility of porting to Python 3k

### ISSUE THREAD

**Issue by GoogleCodeExporter** [MDAnalysis/mdanalysis#132]
At the moment, MDAnalysis will not run in Python 3.x. 

With the move to only support Python 2.6+ (see Issue #130) it should become doable to find out how difficult it will be to make the library also run under Python 3.x.

For the foreseeable future, we will have to maintain a working library under 2.6+ but it would be useful to find out if any of the [porting methods](http://wiki.python.org/moin/PortingPythonToPy3k)  would work for us, e.g. maintaining a "conversion-ready" 2.x code base and then use the [2to3](http://docs.python.org/2/library/2to3.html) tool to generate the 3.x code when needed.

If anyone wants to try this then let me know and I'll make you owner of this issue. We can maintain an experimental py3k branch in the repository.

-- Oliver

Original issue reported on code.google.com by `orbeckst` on 17 Apr 2013 at 5:35
* Blocked on: #130, #211

**Comment by orbeckst** [comment]
See also #260.

**Comment by orbeckst** [comment]
The discussion around #260 (and in particular @kain88-de 's recent work) has established what needs to be done so I am closing this issue.
