### ISSUE TITLE
get_distance_matrix() in encore/confdistmatrix.py crashes on xdr trajectory

### ISSUE THREAD

**Issue by kaplajon** [MDAnalysis/mdanalysis#1324]
Hi,

Doing some clustering on rather long trajectories, I thought it would be neat to save the distance matrix to file, since it is a rather extensive calculation. I realised quite fast that the [get_distance_matrix function()](https://github.com/MDAnalysis/mdanalysis/blob/2c479783cf1d8ec828326f8992a2f1a85ad16d7c/package/MDAnalysis/analysis/encore/confdistmatrix.py#L250) did not like my tpr/xtc Universe very much, since it crashed due to the lack of timeseries support. As I quickly skimmed through the cluster.py I realised [it always uses the merge_universes() function](https://github.com/MDAnalysis/mdanalysis/blob/2c479783cf1d8ec828326f8992a2f1a85ad16d7c/package/MDAnalysis/analysis/encore/clustering/cluster.py#L169), and I worked around the issue by applying that to my trajectory before distance matrix calculation (even though I now see that it had been enough to transfer the trajectory to memory).

Is the use of timeseries necessary for the functionality of get_distance_matrix()? Could it be done in another way? If not, I suggest that the behaviour is documented, so that it is clear for the user that the function needs input with timeseries support (e.g. a transfer_to_memory()).  

### Expected behaviour
get_distance_matrix() should work on any Universe.

### Actual behaviour
get_distance_matrix() does not support Universes without timeseries (tpr/xtc in my case).

### Code to reproduce the behaviour

``` python
import MDAnalysis.analysis.encore.confdistmatrix as cdm
import MDAnalysis as mda
from MDAnalysisTests.datafiles import TPR,XTC
```
Not working:
```python
u = mda.Universe(TPR,XTC)
dm = cdm.get_distance_matrix(u)
```
Working:
```python
u = mda.Universe(TPR,XTC)
u.transfer_to_memory()
dm = cdm.get_distance_matrix(u)
```
Also working:
```python
from MDAnalysisTests.datafiles import PDB_small,DCD
u = mda.Universe(PDB_small,DCD)
dm = cdm.get_distance_matrix(u)
```
### Currently version of MDAnalysis:
0.16.1-dev0

**Comment by kain88-de** [comment]
It would be nice if this works for all trajectory formats. @mtiberti & @wouterboomsma could you have a look.

**Comment by wouterboomsma** [comment]
Since the calculation of a distance matrix will have O(n^2) memory consumption anyway (limiting the functionality to things that fit in memory), I guess we could reasonably just call `transfer_to_memory` as part of `get_distance_matrix`. Any objections to this?

**Comment by orbeckst** [comment]
I think that's ok, assuming that when you do a timeseries from an in-memory trajectory you're just getting a view on the array. Otherwise you'd double memory consumption, wouldn't you?

**Comment by wouterboomsma** [comment]
Right. When you call `MemoryReader.timeseries()` you indeed just get a view of the numpy array.

**Comment by wouterboomsma** [comment]
Something like this should fix it (confdistmatrix.py, line 337):
```
     # Calculate the matrix
     else:
+
+        # Transfer universe to memory to ensure timeseries() support
+        ensemble.transfer_to_memory()
+
         if not isinstance(weights, (list, tuple, np.ndarray)) and weights == 'mass':
             weight_type = 'Mass'
         elif weights is None:
```
Could anyone with direct access to the repo be persuaded to put this in - just to avoid the hassle of a PR for this fairly minor change?

**Comment by kaplajon** [comment]
Is the array view still true if you run `transfer_to_memory` on a trajectory already in memory? Or send slices of an in memory trajectory to `get_distance_matrix`? I don't want to find myself swapping because I didn't ask. :)

**Comment by wouterboomsma** [comment]
`transfer_to_memory` is a noop if it is already in memory - so your first question is definitely not a problem. Not sure what you mean by the second. What type of slicing are you thinking of? Do you have a concrete example?

**Comment by kaplajon** [comment]
I guess I wanted to know if there are cases when you end up with a copy instead of a reference. If you e.g. use the step option to `transfer_to_memory()` in `get_distance_matrix()`, and the Universe you input has a full trajectory loaded.

**Comment by orbeckst** [comment]
It's always a PR. No-one can push directly to develop. 

In any case, we also want a mini test to go with it. 

--
Oliver Beckstein
email: orbeckst@gmail.com

**Comment by wouterboomsma** [comment]
@kaplajon Slicing in a MemoryReader is translated into equivalent slicing in the underlying numpy array. The things that are supported through the MemoryReader API should all be _basic slice_ operations (as described here: https://docs.scipy.org/doc/numpy/reference/arrays.indexing.html), and should thus return a _view_. In contrast, an atom selection is implemented as indexing with an integer array, and will result in a _copy_ (this is referred to as _advanced indexing_, in the numpy docs).

**Comment by kaplajon** [comment]
@wouterboomsma Thanks! :)

**Comment by orbeckst** [comment]
@wouterboomsma thanks for quick fix and thanks to @kaplajon for reporting. 1 day turnaround on an issue is pretty good!!
