### ISSUE TITLE
MDA Exception after LAMMPS atom's index shift 

### ISSUE THREAD

**Issue by zimka** [MDAnalysis/mdanalysis#1330]
### Expected behaviour
Opening LAMMPS dump files after **delete_atoms**  in MDA without problems.

**Comment**:
LAMMPS has **delete_atoms** command, which deletes some atoms, but doesn't change index of the rest.  Therefore after this command there are atoms in system with index higher than the number of atoms.
This inconsistency leads to crash in MDA.

### Actual behaviour
Exception while trying to call universe.atoms properties (positions, bonds etc) 

Traceback:
in MDAnalysis/core/AtomGroup.pyc in positions(self)
_IndexError: index 123083 is out of bounds for axis 0 with size 117432
  2645         .. versionadded:: 0.7.6
   2646         """
-> 2647         return self.universe.trajectory.ts.positions[self.indices, :]
   2648 
   2649     @positions.setter_

### Code to reproduce the behaviour

``` python
import MDAnalysis as mda
u = mda.Universe(top, trj)
pos = u.atoms.positions #Exception!

```
My files that cause crash: [topology](https://yadi.sk/d/lkS8Df1w3HcVKW), [trajectory](https://yadi.sk/d/mpsyuFVe3HcVLj). I have earlier faced same problem with other systems. 

### Currently version of MDAnalysis:
(run `python -c "import MDAnalysis as mda; print(mda.__version__)"`)
0.15.0

Thank you for your useful project and your hard work!

**Comment by richardjgowers** [comment]
@zimka thanks for reporting this and including files, I'll have a look into this.  To clarify, you've deleted some atoms, but the topology and the trajectory both contain the same number of atoms, and this remains constant for each frame?

**Comment by zimka** [comment]
@richardjgowers Yes, exactly. I think both of them are correct, at least from LAMMPS point of view and VMD respectively, and there is no exception during universe init, which occurs when number of atoms is different in topology in trajectory.
