### ISSUE TITLE
Issue with reading amber prmtop if num items is divisible with items per line

### ISSUE THREAD

**Issue by QuantumEntangledAndy** [MDAnalysis/mdanalysis#1331]
### Expected behaviour
Was expecting the prmtop to load without issue.

### Actual behaviour
Failed to load with the error:
Error: could not convert string to float: %FLAG ATOMIC_NUM

### Code to reproduce the behaviour

``` python
import MDAnalysis as mda

u = mda.Universe("HPC.prmtop", "03_heat.nc")

```

### Currently version of MDAnalysis:
(0.16.0)

### Further analysis
My code worked with some of my prmtops but not others
I examined the differences between the files and noticed this:

Files that didn't work looked like this:
```
  0.00000000E+00  5.15691090E+00  0.00000000E+00  5.02935480E+00  0.00000000E+00
  0.00000000E+00 -1.24276086E+01  7.61692140E+00 -1.04596002E+01 -8.52803640E+00
%FLAG ATOMIC_NUMBER
%FORMAT(10I8)
       1       8       6       1       8       6       1       6       1       1
       8       6       1       7       1       6       1       8       1       6
```

Files that did work looked like this:
```
  7.59869910E+00 -1.51973982E+01  7.59869910E+00  7.59869910E+00 -1.51973982E+01
  7.59869910E+00  7.59869910E+00
%FLAG ATOMIC_NUMBER
%FORMAT(10I8)
       1       8       6       1       8       6       1       6       1       1
       8       6       1       7       1       6       1       8       1       6
```

It seems that files where the number of items was exactly divisible by number of items per lines then it fails to load the prmtop.

Looking at the relevant code in the source, I noticed this on line 185 of `topology/TOPParser.py`
```python
              except KeyError:
                    next_getter = self.skipper
                else:
                    num = sys_info[sect_num]
                    numlines = (num // per_line) + 1 #<----HERE

                    attrs[name] = func(atoms_per, numlines)
```
Where I have marked HERE you seem to always be rounding up. You should not round up when the remainder of the division is zero.

I amended the code to read:
```python
              except KeyError:
                    next_getter = self.skipper
                else:
                    num = sys_info[sect_num]
                    numlines = (num // per_line)
                    if num % per_line != 0:
                        numlines += 1

                    attrs[name] = func(atoms_per, numlines)
```

It now works as expected regardless of input.

I hope that this makes sense. Please let me know if there is anything else you would like me to clarify.

**Comment by orbeckst** [comment]
@QuantumEntangledAndy thank you for the report and the patch.

Do you happen to have a small PRMTOP file that failed and which you would be willing to include in the testsuite as a [new data file](https://github.com/MDAnalysis/mdanalysis/wiki/ContributingCode#new-data-files)? 

Files can be attached to an issue if you zip them: Drag and drop on the comment field.

If you would like to [contribute your code](https://github.com/MDAnalysis/mdanalysis/wiki/ContributingCode#contributing-code) and submit a pull request with your fix then we would be happy to include it after review and also include you as an [AUTHOR](https://github.com/MDAnalysis/mdanalysis/blob/develop/package/AUTHORS).

**Comment by QuantumEntangledAndy** [comment]
Sure I can do that. Here is a very small test prmtop that fails to load without the changes mentioned above but succeeds with the changes.
[testCaseNilRemaider.prmtop.zip](https://github.com/MDAnalysis/mdanalysis/files/978032/testCaseNilRemaider.prmtop.zip)

I will also work up that pull request. It just seems a little small. Anything I should be aware of? Reading your contributing guide, would this be classified as fix and thus I should request a pull to both master and develop? Or will you guys handle that if I just put up the request?

**Comment by orbeckst** [comment]
Just make a PR against develop. 

Some of the core devs will then review your code. We'll make suggestions as to what needs to be changed or fixed and when everyone is happy (and all tests pass, which are automatically run on each PR) then someone will merge it into develop. 

Our policy is that any original contribution to the code makes you an author. If it makes MDAnalysis better then you are an author. 

--
Oliver Beckstein
email: orbeckst@gmail.com
