### ISSUE TITLE
continuous integration

### ISSUE THREAD

**Issue by GoogleCodeExporter** [MDAnalysis/mdanalysis#134]
It would be rather nice to use a continuous integration server such as https://travis-ci.org/ to automatically build the library and run the unit tests.

Similarly, using a service such as https://readthedocs.org/ the docs would automatically be rebuilt whenever we get a new commit.

* travis-cl.org only seems to work with github at moment; maybe someone knows if it can be used with Google Code (please comment on this Issue!) or if we just want to periodically clone to github
* readthedocs should be [ridiculously straightforward](https://read-the-docs.readthedocs.org/en/latest/getting_started.html#import-your-docs) 

Original issue reported on code.google.com by `orbeckst` on 24 Apr 2013 at 3:55
* Blocked on: #223

**Comment by hainm** [comment]
is there any progress on building `mdanalysis` by conda yet? If not, I highly recommend to use it. I can just install `pytraj` from binstar within 30 seconds.

Hai

**Comment by tylerjereddy** [comment]
I recently made conda builds on mac and linux and it seemed to work well from binstar. I've mentioned this on the mailing list before, but we still don't have a way to easily make a windows conda build. If there's enough interest we could probably make the mac / linux conda builds more official, but my impression was that we wanted to refine other aspects of the development process first.

**Comment by orbeckst** [comment]
@richardjgowers : This is looking really good. I was surprised that Travis-CL lets you run tests for more than 1h (if I read the "run time" correctly). 

Please merge #278 whenever you think it is ready. Big step forward!

**Comment by richardjgowers** [comment]
The limit is 50 mins... and I'm hitting 45 with the python 2.6 tests :D  I think (luckily) 2.6 and 2.7 are run in parallel, so 1h+ is the cumulative time.

I think going forward we'll have to look at shrinking some of the tests, (iirc some of the PDB file tests take a minute?).  Once we're tracking coverage then we can safely redo the tests and know we're not losing coverage.

**Comment by orbeckst** [comment]
On 19 May, 2015, at 11:57, Richard Gowers wrote:

> The limit is 50 mins... and I'm hitting 45 with the python 2.6 tests :D I think (luckily) 2.6 and 2.7 are run in parallel, so 1h+ is the cumulative time.

I see.

> I think going forward we'll have to look at shrinking some of the tests, (iirc some of the PDB file tests take a minute?). Once we're tracking coverage then we can safely redo the tests and know we're not losing coverage.

... or/and get faster PDB and GRO readers. #212 is already high priority

> 

--
Oliver Beckstein * orbeckst@gmx.net
skype: orbeckst  * orbeckst@gmail.com

**Comment by richardjgowers** [comment]
I still think we don't really need to load 47,000 atom systems*, so if we could create a fake pdb which has 1 of every "feature" we want to read, we could then test this a lot and not worry about the time cost.

* The edge case being checking for stuff like wrapping of numbers in fixed width formats.

**Comment by orbeckst** [comment]
On 19 May, 2015, at 12:06, Richard Gowers wrote:

> I still think we don't really need to load 47,000 atom systems*, so if we could create a fake pdb which has 1 of every "feature" we want to read, we could then test this a lot and not worry about the time cost.

Fair enough. 

(I still like the idea of using real simulation data and perhaps a Trp cage or similar could be used � but even the small cobrotoxin (TPR_xvf, TRR_xvf, PDB_xvf) is still 19385 atoms and is still kind of slow:

```
%timeit u = MDAnalysis.Universe(PDB_xvf)
1 loops, best of 3: 1.73 s per loop

 %timeit u = MDAnalysis.Universe(TPR_xvf, TRR_xvf)
1 loops, best of 3: 560 ms per loop
```

> 	� The edge case being checking for stuff like wrapping of numbers in fixed width formats.

That could be faked with simply using large numbers, I suppose.

I wanted to check if reading from disk is slowing us down so I tried using cStringIO (see below) but it didn't make a difference: same as above, which confirms what we know anyway: the PDB reader is s-l-o-w.

```python
import MDAnalysis
from MDAnalysis.tests.datafiles import PDB_xvf, TPR_xvf, TRR_xvf
import cStringIO
import os.path

stream = cStringIO.StringIO()
stream.writelines(open(PDB_xvf).readlines())
# stream.reset()  # not needed
sPDB = MDAnalysis.core.util.NamedStream(stream, PDB_xvf)

 %timeit u = MDAnalysis.Universe(sPDB)
# 1 loops, best of 3: 1.71 s per loop
```

--
Oliver Beckstein * orbeckst@gmx.net
skype: orbeckst  * orbeckst@gmail.com
