### ISSUE TITLE
Inconsistent subset selection between .select_atoms and .residues[] selection methods

### ISSUE THREAD

**Issue by bieniekmateusz** [MDAnalysis/mdanalysis#1341]
### Expected behaviour
Using noh_set.residues[:n] should select the residues without hydrogens because they are not present in 'noh_set'.

### Actual behaviour
noh_set.residues[:n] selects the residues together with hydrogens as if the selection was used on the universe. Ie works similarly to the use of the word global. 

### Additional comment
In the case of preexisting selection followed by further use of .select_atoms leads to subsetting as described here (https://pythonhosted.org/MDAnalysis/documentation_pages/selections.html#preexisting-selections-and-modifiers). It is only via the use of the keyword global that the selection can escape the the selected subset. The other selection methods (in this case residues[:n]) should behave consistently.

**Comment by orbeckst** [comment]
We had decided that the `.residues` attribute would give *all* atoms connected to the atom group. This is the desired behavior, even though I understand why you might find it counter intuitive. The idea is that you get "all the residues that have at least one atom in the selection". It is a powerful way to walk up and down the group hierarchy.

There is no such thing as a `ResidueGroup` whose `.atoms` only gives you a subset of atoms. `ResidueGroup.atoms` *always* contains *all atoms in the residues*.

I am not 100% sure what exactly you want to achieiev, i.e., so I am giving you two possible solutions:

1. Just get an `AtomGroup` of the atoms in the first `n` residues:

   ```python
    ag = noh_set.residues[:n].select_atoms("not name H*")
    ```
   This will give you an `AtomGroup`.
2. If you want atoms grouped by residue, use [`.groupby`](http://www.mdanalysis.org/mdanalysis/documentation_pages/core/groups.html?highlight=groupby#MDAnalysis.core.groups.ResidueGroup.groupby) (needs 0.16.0):
   
   ```python
     g = noh_set.groupby("resids")
      for resid, ag in g.items():
          print("number of atoms {0} for resid {1}".format(len(ag), resid))
   ```

   Here `g` is a dict, indexed by `resid`.

Does this help?

**Comment by orbeckst** [comment]
@bieniekmateusz did this answer help you?

If there is more we can re-open the issue but I am going to close it for now.
