### ISSUE TITLE
Memory leak plugin with pytest

### ISSUE THREAD

**Issue by utkbansal** [MDAnalysis/mdanalysis#1343]
We have three alternatives for the memory plugin

- [ ] The existing plugin(used with nose)
- [ ] An implementation available [here](https://nvbn.github.io/2017/02/02/pytest-leaking/)
- [ ] ~~pytest-leaks available [here](https://github.com/abalkin/pytest-leaks)~~

* The current plugin calls `gc.collect()` for every test that is executed. This _might_ be the reason
for the slowdown currently faced by the memory plugin as mentioned by @kain88-de [here](https://github.com/MDAnalysis/mdanalysis/issues/1191#issuecomment-290357817) as garbage collection is an intensive operation and calling it manually every time might not be a great idea. Maybe @mnmelo can shed some light on this?
Moreover the custom plugins don't have tests for them, why?

* I have gone through the implementation available on the blog and the code can be summarized as follows -

```
import os
from psutil import Process

_proc = Process(os.getpid())

def get_consumed_ram():
    # Memory in Bytes
    x = _proc.memory_info().rss
    return x

leaks = []

def leak_mem():
    leaks.append({'a': {}})

if __name__ == '__main__':
    get_consumed_ram()
    for i in range(1000):
        leak_mem()
    get_consumed_ram()

```

This IMHO makes more sense than calling `gc.collect()` for each test, but the issue is that our code may not currently guarantee to have no side-effects(which would be the ideal case). We could have a threshold for leaks (eg. 1KB) above which we fail the test case. I'm particularly interested to look into how fixtures work with this - we should be good to go if they rigidly follow functional programming.

* `pytest-leaks` is out of the discussion as it python3 only.

**Comment by mnmelo** [comment]
So, the plugin I wrote catches test-level leaks. It does require calls to `gc.collect` so that we can be sure whatever is in `gc.garbage` really is uncollectable. The current plugin can therefore pinpoint the origin of a leak.

The alternative solution, looking at the aggregate memory usage will be much less precise (tells you there is a leak, but not where). Still, this probably suffices, although we could probably miss small leaks.

To compound (or simplify) this matter, garbage-collection since, i think, python 3.4 can now deal with all kinds of uncollectables, so memleaks should only come up from c extensions.

As for error-plugin tests, it's a bit of a meta-issue: I wrote a test to see if the memleak plugin works (see the end of `test_meta.py`), but if I enable it then, naturally, the testsuite fails because of that error. Note that at this level, at least with nose, we were past the point where we could use `assert_raises`. There is a `MemleakError` raised, but internally and already out of the test's control.

**Comment by utkbansal** [comment]
@mnmelo @jbarnoud  Would you by chance have code to leak memory? I tried a couple of things, but they didn't work. Does the code I've shown above actually leak memory as expected?

**Comment by richardjgowers** [comment]
@utkbansal [there's an example here](https://github.com/MDAnalysis/mdanalysis/issues/297#issuecomment-112370347) which should still work. IIRC it was defining `__del__` twice in objects which reference each other which created some sort of loop.  That made the garbage collector stop working.  It's a fairly common gotcha with python gc and del.

You should be able to make trivial subclasses of Universe and AtomGroup and recreate that as a designed failure (hopefully!).

**Comment by richardjgowers** [comment]
As another thought, if we're using fixtures which are **designed** to persist between tests (ie one Universe for many tests) then we shouldn't be applying a memleak test to everything anyway.  Maybe we just need a special test file which runs through our common operations (load a Uni, create AG off it, delete uni, etc) and makes sure that a leak doesn't happen.

**Comment by mnmelo** [comment]
Good point @richardjgowers. Then we could still do a test-by-test memleak analysis, but only of a selected few operations (although the tricky part here will be to decide which selected ones...)

@utkbansal, in test_meta.py, at the very end, there's commented code that should create a leak.

Note that python>=3.4 is no longer vulnerable to such leaks.

**Comment by utkbansal** [comment]
@mnmelo @richardjgowers If there are only a few tests on which the memory leak will be checked, then I guess the existing plugin is good. We shouldn't trade precision (of @mnmelo's pugin) if its performance doesn't hurt - because the number of test cases it runs is small.

**Comment by jbarnoud** [comment]
@utkbansal Did you manage to reproduce a memory leak? Could you post some timing on how long it takes to run a test that causes a memory leak without plugin, and with our current plugin? Ideally, would you be able to provide some timing using pytest?

**Comment by utkbansal** [comment]
@jbarnoud I was busy last week with my exams. I'm working on this tonight. 
I have timings without plugin and with the nose plugin. I'm going through the documentation to port this to pytest.

**Comment by orbeckst** [comment]
Is this issue still relevant or can we close it?

**Comment by orbeckst** [comment]
There does not seem to be a lot of pressure on to test fro memleaks and because there hasn't been anything happening here for a year I am closing the issue.
