### ISSUE TITLE
import error on parallel computing environment: undefined symbol: __svml_round2

### ISSUE THREAD

**Issue by neonfuzz** [MDAnalysis/mdanalysis#1350]
### Expected behaviour
MDAnalysis will import

### Actual behaviour
```
/usr/lusers/adelak/.local/lib/python2.7/site-packages/MDAnalysis/lib/transformations.py:1813: UserWarning: failed to import module _transformations
  warnings.warn("failed to import module " + module_name)
Traceback (most recent call last):
  File "test.py", line 3, in <module>
    import MDAnalysis as mda
  File "/usr/lusers/adelak/.local/lib/python2.7/site-packages/MDAnalysis/__init__.py", line 178, in <module>
    from .lib import log
  File "/usr/lusers/adelak/.local/lib/python2.7/site-packages/MDAnalysis/lib/__init__.py", line 36, in <module>
    from . import distances  # distances relies on mdamath
  File "/usr/lusers/adelak/.local/lib/python2.7/site-packages/MDAnalysis/lib/distances.py", line 80, in <module>
    package="MDAnalysis.lib")
  File "/sw/anaconda2-4.2.0/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: /usr/lusers/adelak/.local/lib/python2.7/site-packages/MDAnalysis/lib/c_distances.so: undefined symbol: __svml_round2
```
This is occurring on a parallel computing environment, as far as I can tell "__svml_round2" has something to do with parallelization, but I can't find much upon Googling.

### Code to reproduce the behaviour
```python
import MDAnalysis as mda
```

### Currently version of MDAnalysis:
MDAnalysis-0.16.0 (installed with pip)

**Comment by orbeckst** [comment]
In which directory are you running your `test.py`?

Can you also try [running our tests](https://github.com/MDAnalysis/mdanalysis/wiki/UnitTests#users)?
```
cd $HOME
pip install MDAnalysisTests
python -c 'from MDAnalysis.tests import test; test(argv=["--exe", "--processes=4", "--process-timeout=120"])'
```
(you can change the number of processes from 4 to whatever works for you). Do the tests pass (at the end there should be no failed or errored tests).

**Comment by neonfuzz** [comment]
I'm running `test.py` in `/gscratch/stf/adelak`, but the error seems to be location-agnostic. (I've tried in my home directory as well as in `$HOME/.local/lib/python2.7/site-packages`)

I've tried running the tests, but they all fail because I can't even import MDAnalysis. (same error as above)
(`test.py` is literally just one line that says `import MDAnalysis as mda`)

**Comment by orbeckst** [comment]
If this is an HPC environment, do you need to `module load` compiler modules? This could be due to a intel library not being found or something similar. 

Can you import MDAnalysis on the login node?

**Comment by orbeckst** [comment]
Can you
```python
import numpy
```
?

**Comment by richardjgowers** [comment]
It looks like it's importing from a `.local` directory.. Sometimes with this it's a conflict between the versions of numpy used to install MDAnalysis and the locally installed version

**Comment by orbeckst** [comment]
I found that using `conda` is a pretty sane way to work with Python packages in a HPC environment. See, for example, instructions at http://www.mdanalysis.org/SPIDAL-MDAnalysis-Midas-tutorial/installation.html#installing-mdanalysis (which are a bit more extensive than our [Installation Quickstart](http://www.mdanalysis.org/pages/installation_quick_start/)).

We also had recent blog post on [managing different environments with conda](http://www.mdanalysis.org/2017/04/07/environments/).

I tend to work with virtual environments a lot and consider my .local directory as rather temporary and `rm -rf ~/.local` whenever my Python installation shows any signs of weirdness. I try not to use `.local` anymore.

**Comment by neonfuzz** [comment]
I switched all of the dependencies (inc. numpy) to be locally installed, still receiving the `undefined symbol: __svml_round2` error.

**Comment by neonfuzz** [comment]
I'll look into `conda` and see if I can get it to work. Unfortunately I'm stuck using `.local` because I don't have root access on this particular system.

**Comment by orbeckst** [comment]
`conda` (and `virtualenv`) do not require root.

Can you answer the questions from above?
- Does `import numpy` work (and where is the numpy installed, e.g., look at `help(numpy)`)?
- What is the output of `module list`? (I assume you need to load modules.)
- Does the `import MDAnalysis` fail on a head node or a compute node or both?

**Comment by neonfuzz** [comment]
Whoops! Totally missed your comments from above; mb.
`import numpy` works, and is installed at `/usr/lusers/adelak/.local/lib/python2.7/site-packages/numpy/`

Yes, this is an HPC environment, and yes, I do need to load modules; `module list` `gives:
```
Currently Loaded Modulefiles:
  1) modules                      4) contrib/gromacs_5.1.2-head
  2) icc_15.0.3                   5) anaconda2_4.2
  3) icc_15.0.3-impi_5.0.3
```
I'm getting my `python` from `anaconda2_4.2`

`import MDAnalysis` fails on both the head node and on computer nodes.

**Comment by neonfuzz** [comment]
I was able to install the `mdaenv` / `MDAnalysis` with `conda`, but still encounter the same error upon trying to import.

**Comment by richardjgowers** [comment]
@neonfuzz inside your conda environment, which version of numpy get imported?  Iirc, it will still import from `.local` and ignore the version inside your conda environment, which might be causing this error.

**Comment by orbeckst** [comment]
@neonfuzz I would recommend to remove your `~/.local` or at least deactivate it for testing:
```
mv ~/.local ~/.local_DO_NOT_USE_ANYMORE
```

You can install everything that you need in the `conda`-managed environment.

**Comment by orbeckst** [comment]
@neonfuzz have you had any success with any of the suggestions? Is there additional help that you need?

Without further feedback from you we can't really help more and will eventually close the issue.

**Comment by orbeckst** [comment]
We don't have enough data to help with this issue, so I am closing it.

We can re-open if we get more feedback.

**Comment by orbeckst** [comment]
Also see this thread [mdnalysis-users: Installation on hpc:](https://groups.google.com/d/msg/mdnalysis-discussion/D_tovaRrCKI/lMonF2eHCAAJ)
