### ISSUE TITLE
Chain-ID of PDB not always parsed correctly

### ISSUE THREAD

**Issue by kain88-de** [MDAnalysis/mdanalysis#1352]
### Expected behaviour

PDB chain identifiers are parsed as segments

### Actual behaviour

Segments are all called SYSTEM

### Code to reproduce the behaviour

``` python
import MDAnalysis as mda
from MDAnalysis.datafiles import PDB, XTC

u = mda.Universe(PDB, XTC)

u.atoms.segids

```

### Currently version of MDAnalysis:
(run `python -c "import MDAnalysis as mda; print(mda.__version__)"`)
0.16.0 & 0.16.1dev

**Comment by orbeckst** [comment]
I am pretty sure that this used to work...

**Comment by kain88-de** [comment]
It still works. That PDB doesn't have chain ids. My sleep deprived brain yesterday thought it had.
