### ISSUE TITLE
docs tarball missing from 0.16.0 release

### ISSUE THREAD

**Issue by rathann** [MDAnalysis/mdanalysis#1353]
### Expected behaviour

There should be a link to documentation tarball or zip along with 0.16.0 source code, like it was provided with 0.14.0 and 0.15.0.

### Actual behaviour

No documentation tarball is provided.

### Current version of MDAnalysis:
0.16.0

**Comment by orbeckst** [comment]
@rathann Would you prefer a specific name for the zip file? 

In the future we might not create the zip file in under the release tag but instead have it automatically created from a tag in the [MDAnalysis/docs](https://github.com/MDAnalysis/docs) repository where we plan to host docs in the future #1315 ; the docs would then be available from https://github.com/MDAnalysis/docs/releases

**Comment by orbeckst** [comment]
For 0.16.0 I manually generated a `Documentation.zip` file under https://github.com/MDAnalysis/mdanalysis/releases/tag/release-0.16.0 ; as before, it contains `index.html` at the top level so unpack in a directory.

**Comment by rathann** [comment]
@orbeckst Thank you for the quick response. Please choose whatever name you like, as long as it's consistent between releases, for example `MDAnalysisDocs-0.16.0.zip`.

**Comment by orbeckst** [comment]
Ok, will try to remember :-).

> On 19 May, 2017, at 05:12, rathann <notifications@github.com> wrote:
> 
> @orbeckst Thank you for the quick response. Please choose whatever name you like, as long as it's consistent between releases, for example MDAnalysisDocs-0.16.0.zip.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

--
Oliver Beckstein * orbeckst@gmx.net
skype: orbeckst  * orbeckst@gmail.com
