### ISSUE TITLE
treatment of PBC in general triclinic boxes: general minimum image convention

### ISSUE THREAD

**Issue by GoogleCodeExporter** [MDAnalysis/mdanalysis#136]
```
At the moment, MDAnalysis will only deal with orthorhombic simulation boxes. 
For instance, distance_array() can calculate distances taking PBC into account 
(using the minimum image convention).

However, there is no code to calculate minimum image distances for general 
triclinic boxes. Below are two resources for how one could implement such a 
function in MDAnalysis. This would be useful in order to fully support 
distance_array() with PBC but also for remapping trajectories into primary 
unitcells.


Allen & Tildesley [1] provide minimum image routines in their FORTRAN code 
FICHE F.1. PERIODIC BOUNDARY CONDITIONS IN VARIOUS GEOMETRIES (freely 
available) [2] for the truncated octahedron and the rhombic dodecahedron.

Tuckerman [3] in Appendix B, Eq B.9 provides the general algorithm for the 
minimum image convention:

  h := [a, b, c], a=(a1,a2,a3), ... (the matrix of box vectors)
  r_ij := r_i - r_j                 (difference vector)

  s_i = h^{-1} r_i  
  s_ij = s_i - s_j
  s_ij <-- s_ij - NINT(s_ij)        (general minimum image convention)
  r_ij = h s_ij

NINT(x) is the nearest integer function (e.g. numpy.rint()), h^{-1} is the 
matrix-inverse of h.

If anyone would like to do solve this issue please let me know – it would be 
a neat contribution!


REFERENCES

[1] M. P. Allen and D. J. Tildesley. Computer Simulations of Liquids. Oxford 
University Press, Oxford, 1987.
[2] 
http://www.ccl.net/cca/software/SOURCES/FORTRAN/allen-tildesley-book/f.01.shtml
[3] M. E. Tuckerman. Statistical Mechanics: Theory and Molecular Simulation. 
Oxford University Press, Oxford, UK, 2010.

```

Original issue reported on code.google.com by `orbeckst` on 1 May 2013 at 12:30
- Blocking: #156

**Comment by magdalene1233** [comment]
I was diagnosed as primary biliary cirrhosis(PBC) carrier after tests were done to investigate my immune system. I had primary biliary cirrhosis (PBC) of the liver already present. I started treatment with Ursodeoxycholic acid (UDCA), ursodiol (Actigall, Urso),Obeticholic acid (Ocaliva), Fibrates (Tricor) which reduced the viral load initially. After a couple of years the virus became resistant and i decided to try a more natural approach to treat the virus, so i started on primary biliary cirrhosis(PBC)Herbal formula treatment from HEALTH MED LAB CLINIC, this natural (PBC) treatment totally reversed my condition. I did another blood test after the 2 months treatment and tested negative to the virus. Go to health med lab clinic official email healthmedlab@gmail.com This treatment is a breakthrough for all (PBC) carriers.Their natural herbs are very effective and cure your (PBC) permanently.
