### ISSUE TITLE
Installation of MDAnalysis on 32 bit systems

### ISSUE THREAD

**Issue by ashkurti** [MDAnalysis/mdanalysis#1364]
I tried and get the following error:
```
conda install mdanalysis
Fetching package metadata ...............


PackageNotFoundError: Package not found: Conda could not find '
```

I have installed conda by doing the following:
```
wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86.sh
bash Miniconda2-latest-Linux-x86.sh -b -p $HOME/miniconda2
export PATH=$HOME/miniconda2/bin:$PATH
echo "export PATH=$HOME/miniconda2/bin:$PATH" >> ~/.bashrc
```

and my linux operating system is:
```
Linux ubuntu-VirtualBox 3.8.0-35-generic #50-Ubuntu SMP Tue Dec 3 01:25:33 UTC 2013 i686 i686 i686 GNU/Linux
```

**Comment by kain88-de** [comment]
http://www.mdanalysis.org/pages/installation_quick_start/

```
conda config --add channels conda-forge
conda install mdanalysis
```

or short 

```
conda  install -c conda-forge mdanalysis
```

**Comment by orbeckst** [comment]
The important thing is to add the **conda-forge** channel because the MDAnalysis conda packages reside there, together with _all dependencies_ – @kain88-de worked hard to make sure that everything that MDAnalysis needs is available as a conda package.

You only have to do the `--add channels` once for your conda installation.

Please let us know if this works or if there are any other issues.

**Comment by ashkurti** [comment]
Thanks @orbeckst and @kain88-de for your suggestions.

I have tried what you suggest, as I also had run into the links indicated by @kain88-de without success. I also have retried it and this is what I get:
```
ubuntu@ubuntu-VirtualBox:~/test_slabit/slabit$ source activate venv_slabit
(venv_slabit) ubuntu@ubuntu-VirtualBox:~/test_slabit/slabit$ conda config --add channels conda-forge
Warning: 'conda-forge' already in 'channels' list, moving to the top
(venv_slabit) ubuntu@ubuntu-VirtualBox:~/test_slabit/slabit$ conda install mdanalysis
Fetching package metadata ...............


PackageNotFoundError: Package not found: Conda could not find '


(venv_slabit) ubuntu@ubuntu-VirtualBox:~/test_slabit/slabit$ conda  install -c conda-forge mdanalysis
Fetching package metadata ...............


PackageNotFoundError: Package not found: Conda could not find '


(venv_slabit) ubuntu@ubuntu-VirtualBox:~/test_slabit/slabit$ 
```
Any suggestions on what might be going wrong here. Thanks :)

**Comment by richardjgowers** [comment]
@ashkurti what platform is this running on?  What does `conda search mdanalysis` return?

**Comment by kain88-de** [comment]
@ashkurti can you run `conda config --show` and paste the output.

**Comment by ashkurti** [comment]
@richardjgowers 
```
(venv_slabit) ubuntu@ubuntu-VirtualBox:~/test_slabit/slabit$ conda search mdanalysis
Fetching package metadata ...............
(venv_slabit) ubuntu@ubuntu-VirtualBox:~/test_slabit/slabit$
```
@kain88-de :
```
(venv_slabit) ubuntu@ubuntu-VirtualBox:~/test_slabit/slabit$ conda config --show
add_anaconda_token: True
add_pip_as_python_dependency: True
allow_softlinks: True
always_copy: False
always_softlink: False
always_yes: False
auto_update_conda: True
binstar_upload: None
changeps1: True
channel_alias: https://conda.anaconda.org
channel_priority: True
channels:
  - conda-forge
  - MDAnalysis
  - mdanalysis
  - defaults
client_ssl_cert: 
client_ssl_cert_key: 
create_default_packages: []
debug: False
default_channels:
  - https://repo.continuum.io/pkgs/free
  - https://repo.continuum.io/pkgs/r
  - https://repo.continuum.io/pkgs/pro
disallow: []
envs_dirs:
  - /home/ubuntu/miniconda2/envs
  - /home/ubuntu/.conda/envs
json: False
offline: False
proxy_servers: {}
quiet: False
shortcuts: True
show_channel_urls: None
ssl_verify: True
track_features: []
update_dependencies: True
use_pip: True
verbosity: 0
(venv_slabit) ubuntu@ubuntu-VirtualBox:~/test_slabit/slabit$ 

```

**Comment by ashkurti** [comment]
@richardjgowers as to the platform:
```
(venv_slabit) ubuntu@ubuntu-VirtualBox:~/test_slabit/slabit$ uname -a
Linux ubuntu-VirtualBox 3.8.0-35-generic MDAnalysis/mdanalysis#50-Ubuntu SMP Tue Dec 3 01:25:33 UTC 2013 i686 i686 i686 GNU/Linux
(venv_slabit) ubuntu@ubuntu-VirtualBox:~/test_slabit/slabit$ 
```

**Comment by kain88-de** [comment]
@ashkurti this is weird. Can you please remove the MDAnalysis channels from your config file in `~/.condarc`

**Comment by ashkurti** [comment]
@kain88-de I removed MDAnalysis channels and then followed again the previous steps (and nothing changed :( :
```
(venv_slabit) ubuntu@ubuntu-VirtualBox:~/test_slabit/slabit$ conda  install -c conda-forge mdanalysis
Fetching package metadata ...........


PackageNotFoundError: Package not found: Conda could not find '


(venv_slabit) ubuntu@ubuntu-VirtualBox:~/test_slabit/slabit$ cat ~/.condarc
channels:
  - defaults
(venv_slabit) ubuntu@ubuntu-VirtualBox:~/test_slabit/slabit$ conda config --add channels conda-forge
(venv_slabit) ubuntu@ubuntu-VirtualBox:~/test_slabit/slabit$ cat ~/.condarc
channels:
  - conda-forge
  - defaults
(venv_slabit) ubuntu@ubuntu-VirtualBox:~/test_slabit/slabit$ conda install mdanalysis
Fetching package metadata ...........


PackageNotFoundError: Package not found: Conda could not find '


(venv_slabit) ubuntu@ubuntu-VirtualBox:~/test_slabit/slabit$ 
```

**Comment by kain88-de** [comment]
OK this is weird. I'm not sure what is going on there. I sometimes had luck with such weird errors in conda by reinstalling it.  My guess is here also conda because your error message looks cut off.

For example when I try to install a non existing package I get the following error.

```
thinki ~ » conda install mdanalysisssss
Fetching package metadata .................


PackageNotFoundError: Package missing in current linux-64 channels: 
  - mdanalysisssss

Close matches found; did you mean one of these?

    mdanalysisssss: mdanalysis, mdanalysistests
```

**Comment by kain88-de** [comment]
what version of conda your you running?

**Comment by kain88-de** [comment]
run `conda -V`

**Comment by ashkurti** [comment]
```
(venv_slabit) ubuntu@ubuntu-VirtualBox:~/test_slabit/slabit$ conda -V
conda 4.3.14
(venv_slabit) ubuntu@ubuntu-VirtualBox:~/test_slabit/slabit$ 
```

**Comment by kain88-de** [comment]
I'm running 4.3.17. The point release shouldn't change anything but maybe it does.

**Comment by ashkurti** [comment]
what platform are you running on?

**Comment by ashkurti** [comment]
`uname -a`

**Comment by kain88-de** [comment]
I'm running on Fedora. But that shouldn't make any difference. @richardjgowers runs ubuntu and it works for him as well. I've asked the conda-forge people for help.

**Comment by isuruf** [comment]
You need 4.3.16 or above. See https://github.com/conda/conda/issues/4860#issuecomment-292728977

**Comment by ashkurti** [comment]
@isuruf As I want to automatically install conda (as part of a package I am working on) I am getting the conda installation script from `https://repo.continuum.io/miniconda/` 
The latest conda version from those scripts dated less than two weeks ago is 4.3.14. 

Any suggestions? Maybe I can install this version then, include a command for update? Anywhere I can find the script to install a 4.3.16 or above version of conda. Thanks :)

**Comment by isuruf** [comment]
Here's a script from ContinuumIO, https://conda.io/docs/travis.html. Note that they recommend conda even when downloading a fresh version of miniconda.

**Comment by kain88-de** [comment]
@isuruf thanks

@ashkurti running `conda update --all` after installing it might help.

I'll close this since it's not related to MDAnalysis

**Comment by ashkurti** [comment]
I am still not managing to find out mdanalysis within conda. 

So even after updating conda to 4.3.18 it is not managing to find mdanalysis, and specifically the following happens:
```
ubuntu@ubuntu-VirtualBox:~/test_slabit/slabit$ conda config --add channels conda-forge
Warning: 'conda-forge' already in 'channels' list, moving to the top
ubuntu@ubuntu-VirtualBox:~/test_slabit/slabit$ conda install mdanalysis=0.15.0
Fetching package metadata ...........

PackageNotFoundError: Package missing in current linux-32 channels: 
  - mdanalysis 0.15.0*

ubuntu@ubuntu-VirtualBox:~/test_slabit/slabit$ conda install mdanalysis
Fetching package metadata ...........

PackageNotFoundError: Package missing in current linux-32 channels: 
  - mdanalysis

ubuntu@ubuntu-VirtualBox:~/test_slabit/slabit$ conda -V
conda 4.3.18
ubuntu@ubuntu-VirtualBox:~/test_slabit/slabit$ 
```

**Comment by ashkurti** [comment]
The thing is that apparently the Ubuntu image I am using for testing in my virtual machine is a 32 bit one apparently and therefore it cannot find mdanalysis within the linux-32 channel. At this point, is there a specific reason for MDAnalysis to be only supported for 64 bit linux platforms.

**Comment by kain88-de** [comment]
Yeah we don't ship 32bit prebuild binaries. There is also a recent bug report that the library doesn't work on 32bit in some parts.

**Comment by richardjgowers** [comment]
@ashkurti we don't really support 32 bit systems, mostly because none of the developers have access/need a 32 bit system.  If it's something you specifically need, we can guide you through how to make a conda package for this, but there might be some bugs you have to fix too (eg MDAnalysis/mdanalysis#1362).

[Related discussion on dev board](https://groups.google.com/forum/#!topic/mdnalysis-devel/i53j-6QFP7k)

**Comment by orbeckst** [comment]
Just as an update: despite  https://github.com/MDAnalysis/mdanalysis/issues/1364#issuecomment-304212235 there are nevertheless some efforts going on to make it work on 32-bit, see issue MDAnalysis/mdanalysis#1362 (and related MDAnalysis/mdaencore#38) and PR MDAnalysis/mdanalysis#1393 as well as PR MDAnalysis/mdanalysis#1392 for setting up the testing.

**Comment by tylerjereddy** [comment]
I haven't gone through this whole discussion, but perhaps worth revisiting if there are still (32-bit) issues here after MDAnalysis/mdanalysis#2696.

**Comment by IAlibay** [comment]
Is this still an active issue? As far as I understand @tylerjereddy has 32bit Windows support enabled as part of our CI suite.

**Comment by IAlibay** [comment]
Closing as MDAnalysis is no longer planning to keep official support for 32 bit installs (see PR MDAnalysis/mdanalysis#4176 )
