### ISSUE TITLE
KDTree.NeighborSearch.list_search with periodic boundary conditions

### ISSUE THREAD

**Issue by GoogleCodeExporter** [MDAnalysis/mdanalysis#137]
The KDTree-based distance search does not take periodic boundary conditions  into account. [Christopher Ing suggested](https://groups.google.com/d/msg/mdnalysis-discussion/XHG8qf1FMz8/XxzDQ5zwmVgJ) to use Patrick Varilly's "periodic KD-tree" code" available at [patvarilly/periodic_kdtree](https://github.com/patvarilly/periodic_kdtree).

I am filing this report so that his good idea is not forgotten. If anyone wants to try it I will make them owner of this issue report. Questions to be answered:
- Can the `PeriodicCKDTree` code be used as a drop-in replacement for `KDTRee._CKDTree`?
- What is the difference in performance? Should we keep two separate code paths, one with, the other without PBC?
- Does it work with arbitrary (triclinic) boxes? (See also Issue #136).

Original issue reported on code.google.com by `orbeckst` on 1 May 2013 at 12:31

**Comment by richardjgowers** [comment]
[Aboria](https://martinjrobins.github.io/Aboria/index.html) looks like it implements a periodic coordinate search which we could use in place of a KDTree

**Comment by mnmelo** [comment]
Cool! And it also looks like it'll implement it's own (periodic?) KDTree in the near future (see their notes on [Neighbor Searching](https://martinjrobins.github.io/Aboria/aboria/neighbourhood_searching.html)).
