### ISSUE TITLE
Make it easier to create a Universe from scratch

### ISSUE THREAD

**Issue by mnmelo** [MDAnalysis/mdanalysis#1371]
During our dev hangout the idea was surfaced to have a simple way to build a Universe with default values. This would leverage MDAnalysis' role also as a structure builder (and would be another neat thing to mention in an upcoming paper).

We pretty much have the machinery in place in the `make_Universe` function of `MDAnalysisTests.core.util`. We could add some extras, such as the ability to define number of residues/segments. After a Universe is built, the user could assign meaningful values to whichever topology components they want (though this may need to wait for #1186 and #1092).

Another neat side use of this could be the topology-less reading of trajectory files: .xtc, .trr and, AFAIK, .dcd all store the number of atoms, which is enough to create a Universe of default names/masses/charges on which said trajectory data can be loaded. This could help garnering more users that are just looking for a quick way to access trajectory data (though this is also one of the goals of #1194).

Opinions?

**Comment by richardjgowers** [comment]
Technically, it should be very simple to be able to make a Universe structure from a tuple of shape `(natoms, nres, nseg)`, and I can see it being very useful too.

**Comment by orbeckst** [comment]
What is the simplest way to create a fresh universe with a handful (~7) of atoms?

**Comment by richardjgowers** [comment]
@orbeckst if the atoms already exist from another Universe, probably `Merge` with only one `AtomGroup` as an argument.  If the atoms don't exist, `make_Universe` which only exists in the testsuite currently, but see PR #1533
