### ISSUE TITLE
Remove TimeSeries

### ISSUE THREAD

**Issue by kain88-de** [MDAnalysis/mdanalysis#1373]
We discussed recently to remove the TimeSeries objects from MDAnalysis. As far as I know none of the core devs is using it.  We also note that it is unlikely we will ever implement TimeSeries for any other readers besides dcd and memory and most of it's function can be replaced by the Analysis Framework.

The only part in the library that uses TimeSeries is encore. So it would be useful get some input from @wouterboomsma and @mtiberti before we go ahead with this.

As a first step I would remove timeseries from DCD during the cython transition. 
In a later step we would remove timeseries from memory reader and remove  the core TimeSeries class.

**Comment by kain88-de** [comment]
I should be more  specific.  This won't remove the timeseries call from MemoryReader. As this is only a view of the underlying array (useful to have).  Only the fancy correl functions will be removed.

**Comment by wouterboomsma** [comment]
As far as I remember, the only reason Encore uses `timeseries()` was to maximize it's similarity to other Readers. So I don't think there should be any problems removing it. However, I think it would make sense to keep the functionality (perhaps with a different name) within `MemoryReader`, because it is an intuitive interface to extract a numpy array in a specified format.

**Comment by wouterboomsma** [comment]
Ups... Posted before seeing your follow-up message. It seems we agree.

**Comment by wouterboomsma** [comment]
If we keep the `timeseries()` method in MemoryReader, your suggested change would probably not require any modifications in Encore at all - because encore typically works on MemoryReader readers anyway (calling transfer_to_memory if necessary).

**Comment by orbeckst** [comment]
This would also close #186.

**Comment by kain88-de** [comment]
So there is a general agreement to remove the correl like features?

**Comment by orbeckst** [comment]
Yes, I think everyone would like to move forward with removing it. I removed the proposal tag.

**Comment by richardjgowers** [comment]
Ok, once API breaks are decided, we should really put the deprecation notices in asap.  It can even go in a "bugfix" release right?  0.17 will be soonish (tm), so maybe target this (and similar API changes) for 0.18?  And hopefully 0.18 == 1.0?

**Comment by orbeckst** [comment]
We can make 0.16.2 just for deprecation notices if we want to. 

O.18.0 == 1.0.0 would be great.

**Comment by kain88-de** [comment]
This change **has** to come with the DCD update. I could try to make it work but I rather not. It's a hard cut admittedly but there is nothing else using the TimeSeries stuff.

**Comment by richardjgowers** [comment]
Ok, so for 0.17 == py3, we need also for this issue to be 0.17?  I don't think anyone is using this, so maybe we can do that

**Comment by orbeckst** [comment]
I added a longer comment to #1383 basically arguing that we should deprecate Timeseries/correl in 0.16.2 and remove in 0.17.0.
