### ISSUE TITLE
No minimal travis test anymore

### ISSUE THREAD

**Issue by kain88-de** [MDAnalysis/mdanalysis#1376]
I noticed that we currently don't run our minimal travis tests more as specified in our test matrix. Anyone a idea why?

**Comment by kain88-de** [comment]
For example see https://travis-ci.org/MDAnalysis/mdanalysis/builds/238679739

**Comment by orbeckst** [comment]
Is this fixed? For instance _minimal_ is in https://travis-ci.org/MDAnalysis/mdanalysis/builds/239888688
