### ISSUE TITLE
add deprecation warnings for API changes

### ISSUE THREAD

**Issue by richardjgowers** [MDAnalysis/mdanalysis#1383]
Ideally we should push out deprecation warnings as soon as we know it's happening.  Related issues:

- [x] #1373 Timeseries (targeted for 0.17)
- [x] #1377 Quick selectors (target 1.0)
- [x] #782 flags (target 1.0)

**Comment by orbeckst** [comment]
@kain88-de I would do the deprecation warnings in 0.16.2; yes, not much time to adapt but fully consistent with semantic versioning. It's pretty clear to say "if you still want timeseries then get the last release in the 0.16 cycle". And we're still in 0.x so we are allowed to move a bit faster. 

The alternative would be to make 0.17 for the deprecation warning and 0.18 to remove Timeseries. But these would be two "big" releases in quick succession with 0.17 really not having very much content, especially when comparing to 0.16 and 0.15. This seems more confusing than using a light-weight patch level release like 0.16.2 for the purpose. We might even do a 0.16.3 if necessary, e.g. for restructuring testing.
