### ISSUE TITLE
Suggestions for conda install of 0.16.0

### ISSUE THREAD

**Issue by ldomic** [MDAnalysis/mdanalysis#1384]
I tried to install MDAnalysis 0.16.0 with conda on Linux64 docker container and it asked me for a dependency not found in the current Linux64 channels - mmtf-python.  

I did solve that by installing mmtf-python from conda-forge, however, I thought it could be nice to  have a note in the description about where to find this dependency or how to install MDAnalysis in a single line e.g.:

`conda install -c mdanalysis mdanalysis=0.16.0 -c conda-forge` 

Are there plans to move to conda-forge as that would solve this issue? It is always so much nicer to have only a single line to install a program and would make MDAnalysis easier to use as a dependency for other programs.

**Comment by richardjgowers** [comment]
Hi Laura.

We are on conda forge, hopefully all our docs are just using that channel
in how to install. Did you see us using our channel still?

**Comment by ldomic** [comment]
Hi @richardjgowers,

Yes, I clicked on the badge on your README which took me to your channel. The docs are correct though.

**Comment by richardjgowers** [comment]
Aha, thanks!
