### ISSUE TITLE
Writing to .gro breaks the format with if > 99999 molecules

### ISSUE THREAD

**Issue by bieniekmateusz** [MDAnalysis/mdanalysis#1388]
### Expected behaviour
Format .gro starts counting the molecules from the beginning right after 99,999. 

### Actual behaviour
When I saved a file with more molecules, the first column became longer by one character, which consequently shifted all other columns and stopped gromacs and vmd from reading the file. I presume that having over 1 million of molecules would add further columns. 

### Additional condition: molecule IDs must be larger than 99,999
The original input file must use the molecule IDs that are larger than the limit. This is always the case with charmm .crd file format which is recommended for that reason. 

### Code to reproduce the behaviour
``` python
import MDAnalysis as mda
u = mda.Universe('lotsmols.crd')
u.atoms.write('brokencols.gro')
```
### Currently version of MDAnalysis:
0.16.0

**Comment by orbeckst** [comment]
This sounds like #886 – I think @tylerjereddy considered it fixed, though. Maybe it requires a second look?

**Comment by tylerjereddy** [comment]
What I don't understand is the "additional condition." If  I artificially inflate the resid there doesn't seem to be an issue:

input:
```python
  1 import MDAnalysis
  2 from MDAnalysisTests.datafiles import PSF, DCD
  3 print 'MDAnalysis.__version__:', MDAnalysis.__version__
  4
  5 u = MDAnalysis.Universe(PSF, DCD)
  6 residues = u.atoms.residues
  7 residues[-1].resid = 9e9
  8 u.atoms.write('test_large_resid.gro')
```

where the tail of the new `.gro` looks properly truncated (I never worried about getting the counting from zero over again right as long as we didn't violate the column formats):
```
  213LEU      O 3333   0.989   1.658  -0.521
41006GLY      N 3334   0.767   1.735  -0.525
41006GLY     HN 3335   0.680   1.735  -0.477
41006GLY     CA 3336   0.779   1.829  -0.639
41006GLY    HA1 3337   0.849   1.776  -0.706
41006GLY    HA2 3338   0.803   1.924  -0.590
41006GLY      C 3339   0.651   1.845  -0.713
41006GLY    OT1 3340   0.630   1.936  -0.794
41006GLY    OT2 3341   0.559   1.759  -0.697
   0.00000   0.00000   0.00000
```

There's a new topology system under the hood now and I never use that input format, so I'll need more information or (even better) an appropriate reproducible minimum working example of the failure to write a unit test and patch. Probably better if you can figure out how to induce this problem artificially [by manipulating some property of the topology] rather than requiring a large input test file, so we don't have to inflate the size of the test suite.

**Comment by tylerjereddy** [comment]
At the very least, some kind of non-confidential / shareable file that reproduces the problem would be helpful if you don't have time to look at the topology properties under the hood that may be causing this problem.

**Comment by richardjgowers** [comment]
I had a look into this and couldn't reproduce it (but found something else).  We don't actually use the `Atom.id` attribute when writing the gro file, instead we use a `range` call to generate atom ids, so I'm not sure the source of the data should matter.

@bieniekmateusz can you copy + paste a couple of the wrongly formatted lines so I can see where the alignment goes out of place?

**Comment by bieniekmateusz** [comment]
Turns out it is my mistake. I've checked the version of the package with Python3, but for my scripts I am using python2 which had the MDAnalysis version 0.15.0. After the update it is working fine now. 

Donated to Free Software Foundation as an indirect way to say thanks.

**Comment by orbeckst** [comment]
> Donated to Free Software Foundation as an indirect way to say thanks.

That is very kind of you, thank you.

In the future you could also consider https://www.numfocus.org/ for donations; we're affiliated with them and they pass money on to very specific projects.

However, the most valuable contribution that you can make to the project is to report problems and communicate with us (as you do!), possibly introduce other people to MDAnalysis, and [cite our papers](http://www.mdanalysis.org/docs/documentation_pages/references.html#citations-for-the-whole-mdanalysis-library).

**Comment by orbeckst** [comment]
@richardjgowers 
> (but found something else). We don't actually use the Atom.id attribute when writing the gro file, instead we use a range call to generate atom ids, so I'm not sure the source of the data should matter.

Should this be a separate issue?

**Comment by richardjgowers** [comment]
@orbeckst what I found was #1395
