### ISSUE TITLE
Pytest doesn't discover staticmethods within Test Class

### ISSUE THREAD

**Issue by richardjgowers** [MDAnalysis/mdanalysis#1422]
I was poking around `utils/test_units`.  If we run `pytest --collect-only test_units.py`, we get:
```
collected 17 items 
<Module 'MDAnalysisTests/utils/test_units.py'>
  <UnitTestCase 'TestDefaultUnits'>
    <TestCaseFunction 'test_convert_gromacs_trajectories'>
    <TestCaseFunction 'test_length'>
    <TestCaseFunction 'test_time'>
  <UnitTestCase 'TestUnitEncoding'>
    <TestCaseFunction 'test_unicode'>
    <TestCaseFunction 'test_unicode_encoding_with_symbol'>
  <Class 'TestConstants'>
    <Instance '()'>
      <Generator 'test_constant'>
        <Function '[0]'>
        <Function '[1]'>
        <Function '[2]'>
  <Class 'TestConversion'>
    <Instance '()'>
      <Generator 'test_length'>
        <Function '[0]'>
        <Function '[1]'>
      <Generator 'test_time'>
        <Function '[0]'>
        <Function '[1]'>
      <Generator 'test_energy'>
        <Function '[0]'>
        <Function '[1]'>
      <Generator 'test_force'>
        <Function '[0]'>
        <Function '[1]'>
        <Function '[2]'>
```

But [inspecting the test file](https://github.com/MDAnalysis/mdanalysis/blob/develop/testsuite/MDAnalysisTests/utils/test_units.py#L109) shows that some tests aren't getting collected.  It seems to be the tests that are `staticmethod` within an object?

**Comment by utkbansal** [comment]
This is interesting. I can't see anything in the pytest documentation about this. I did a search on the complete pdf doc - no reference to the word `staticmethod` and only one reference to the word `static`. Have asked on StackOverflow, let's see.

**Comment by richardjgowers** [comment]
All I managed to find online was this comment: https://stackoverflow.com/questions/20277058/py-test-does-not-find-tests-under-a-class#comment71144142_20277099

**Comment by mnmelo** [comment]
@utkbansal already managed to get meaningful feedback on [SO](https://stackoverflow.com/questions/44700471/pytest-not-collecting-staticmethod). Quite an unexpected side-effect of `@staticmethod`, that returns non-callable wrapping objects.

**Comment by utkbansal** [comment]
Yeah, we'll just have to stop using `staticmethods` in our tests.

**Comment by mnmelo** [comment]
Linters may camplain, but I'm ok with that.
The alternative, rolling out our own `@staticmethod` descriptor with a `__call__` method seems unnecessary.

**Comment by richardjgowers** [comment]
Ok this is 'fixed' in that we know to keep an eye out for it
