### ISSUE TITLE
Make HOLE conda package for better testing

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/mdanalysis#1429]
HOLE is now open source: https://github.com/osmart/hole2 under *Apache License 2.0*.

We should make a conda package to improve testing and to get kudos from the community. 

We could even make a library out of it for MUCH better integration (assuming Apache License is compatible with GPL... need to check).

**Comment by orbeckst** [comment]
I forked hole2 to https://github.com/MDAnalysis/hole2 and made some installation improvements. I don't really know how to make it a conda package. To build one needs a fortran compiler (gfortran works by default, see my [INSTALL.md](https://github.com/MDAnalysis/hole2/blob/develop/INSTALL.md) for details)
```
cd src
make
make PREFIX="$HOME/hole2" install install-opt install-2dmap
```
(installs everything, most people only need `install`).

**Comment by lilyminium** [comment]
Closed: https://anaconda.org/conda-forge/hole2
