### ISSUE TITLE
Coveralls always errors "Source not available"

### ISSUE THREAD

**Issue by utkbansal** [MDAnalysis/mdanalysis#1445]
### Expected behaviour

On clicking a file in the Coveralls' report, I should be able to see the lines which are no longer covered due to changes made in the PR. 

### Actual behaviour
Source not available
`The file "/home/travis/miniconda/envs/test/lib/python2.7/site-packages/MDAnalysis/core/selection.py" isn't available on github. Either it's been removed, or the repo root directory needs to be updated.`

### Potential fix
The error says that coveralls tried to look for the source code files at `/home/travis/miniconda/envs/test/lib/python2.7/site-packages/MDAnalysis/`. I think it should look in the cloned folder instead. We need to change the repo root to make this work.

It would be huge help for me if we could fix this. Comparing multiple coverage reports manually is a pain.

#### EDIT

Related issue on coveralls github at https://github.com/lemurheavy/coveralls-public/issues/263

**Comment by richardjgowers** [comment]
@utkbansal I think I've fixed this, can you confirm?

**Comment by utkbansal** [comment]
Yes, I can now see the files with the coverage data. Thanks!

**Comment by orbeckst** [comment]
Coveralls does not show line-by-line coverage anymore, even though coveralls is back (#1918)

For example, going into the *Source Files on develop* section, clicking *LIST*, and selecting *...kages/MDAnalysis/analysis/encore/confdistmatrix.py* gives


 Source Not Available
 
 The file "/home/travis/miniconda/envs/test/lib/python3.5/site-packages/MDAnalysis/analysis/encore/confdistmatrix.py" isn't available on github. Either it's been removed, or the repo root directory needs to be updated.

**Comment by richardjgowers** [comment]
Yeah so it's not correctly detecting where in the repo corresponds to the files it's being told about.  I think maybe doing a developer installation on travis might fix this, so then the source files aren't put into a conda env

**Comment by jbarnoud** [comment]
This would be dangerous, though. Indeed, the tests would not fail if a new file is not added correctly to `setup.py`.

**Comment by orbeckst** [comment]
Should we switch from coveralls to coverage? We already use coverage for other projects and we managed to get it to work for those (e.g. pmda).
