### ISSUE TITLE
change timeseries "format" kw to "order"

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/mdanalysis#1453]
In various issues and discussions we sort-of decided that the `Reader.timeseries()` method should not use `format="afc"` as a kwarg but `order="afc"` (which make it consistent with the `MemoryReader`, avoids clashes with the builtin `format`, ... and avoids clashes with the `format` kwarg of `Universe` (yes, that one clashes with the builtin, too)).

**Comment by orbeckst** [comment]
I think we should consider adding this to 0.17 so that we have some deprecation time.

**Comment by orbeckst** [comment]
Note to myself: While playing around with the memory reader for the _Examples_ for [RMSF}(http://www.mdanalysis.org/mdanalysis/documentation_pages/analysis/rms.html#MDAnalysis.analysis.rms.RMSF) I found that not all orderings (keyword `order=...`) work for `Universe.load_new(array_like, order="...")` work. At least I got a cryptic error with `fac` (which is supposedly the default) while it worked with `fac`. Need to investigate more and possibly add tests for *all permutations*.

**Comment by orbeckst** [comment]
Also note that the docs for the [MemoryReader](http://www.mdanalysis.org/mdanalysis/documentation_pages/coordinates/memory.html) need to be update:
- When a array_like is provided then it is automatically passed to the MemoryReader and the `format="MEMORY"` or `format=MemoryReader` is not needed anymore.
- Same for `Universe.load_new()`

In general we need to clarify how file types are recognized.

**Comment by orbeckst** [comment]
I'll try to do this in my ample spare time ;-) – unless anyone else wants to: feel free to snatch this issue from me.

**Comment by kain88-de** [comment]
@orbeckst do you have any code for your experiments of `order` that you did in august.

**Comment by orbeckst** [comment]
No, sorry. But you can take the Example at https://www.mdanalysis.org/mdanalysis/documentation_pages/analysis/rms.html#MDAnalysis.analysis.rms.RMSF and just change `order` in the line
```python
# make a reference structure (need to reshape into a 1-frame "trajectory")
reference = mda.Merge(protein).load_new(
            reference_coordinates[:, None, :], order="afc")
```
and it should fail. 

(I am travelling and if you want to work on this please by all means do so and also assign yourself/un-assign me. Thanks!)

**Comment by kain88-de** [comment]
Your example case works now with my changes.

**Comment by orbeckst** [comment]
@kain88-de many thanks for finishing the PR, I very much appreciate you jumping in. Sorry I wasn't able to be more helpful.

**Comment by kain88-de** [comment]
It’s ok. There is a tone of stuff I’m not getting done on MDAnalysis myself right now.
