### ISSUE TITLE
Auxillary reader step initializing with  -1

### ISSUE THREAD

**Issue by kain88-de** [MDAnalysis/mdanalysis#1457]
### Expected behaviour

auxillary readers work on python 3

### Actual behaviour

The `aux.base.step` is set to -1 [initially](https://github.com/MDAnalysis/mdanalysis/blob/develop/package/MDAnalysis/auxiliary/base.py#L111). Later in [`step_to_frame`](https://github.com/MDAnalysis/mdanalysis/blob/develop/package/MDAnalysis/auxiliary/base.py#L467) this value is used to check if the step is valid when called in [`read_ts`](https://github.com/MDAnalysis/mdanalysis/blob/develop/package/MDAnalysis/auxiliary/base.py#L416). Now `step_to_frame` is allowed to return `None` which under python 2 is comparable to an `int` under python 3 it raises a type error.

I don't see an easy fix here. I'm also unaware when `self.step` in the auxillary reader is ever changed. Grepping didn't yield a code line with `self.step = `.

### Code to reproduce the behaviour

python 2 fine
``` python
None < 2
```

python 3 type error
```python
In [1]: None < 4
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-1-28bfca7a69ed> in <module>()
----> 1 None < 4

TypeError: unorderable types: NoneType() < int()
```

### Currently version of MDAnalysis:
(run `python -c "import MDAnalysis as mda; print(mda.__version__)"`)

**Comment by jbarnoud** [comment]
I encountered the issue some time ago as I was investigating some python 3 issue with the aux reader. I'll see what I can do.

@fiona-naughton could you have a look as well?

**Comment by kain88-de** [comment]
Also the comparison with None produces a True. So this might also be a general bug in the code.

**Comment by kain88-de** [comment]
https://travis-ci.org/MDAnalysis/mdanalysis/jobs/253315764#L2636

there is still an error for this according to travis
