### ISSUE TITLE
update analysis.base.AnalysisBase to conform to API

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/mdanalysis#1463]
In #719 we decided on the details of the analysis interface ("Bauhaus" style). The description for implementation is on the wiki [MDAnalysis.analysis user interface](https://github.com/MDAnalysis/mdanalysis/wiki/MDAnalysis.analysis-user-interface) but we also decided to change a few additional things that are directly defined in the base class and automatically apply to all analysis code: The following needs to be changed in [AnalysisBase](http://www.mdanalysis.org/mdanalysis/documentation_pages/analysis/base.html#MDAnalysis.analysis.base.AnalysisBase):

1. `start`, `stop`, `step` are kwargs of `AnalysisBase.run()` but _not_ of `__init__()`.
2. `verbose` is a kwarg of `__init__` where it sets the default; `verbose` is *also a kwarg of `run()`* where it overrides the default value for the duration of `run` (this allows the user to mute the frame-by-frame calculation but still have verbose output during pre- and post-processing).

Because **1** changes the API, we need to deprecate `start`, `stop`, `step` in `__init__` and **remove them in 1.0.0**. Until then it needs to be possible to set the iteration range in `__init__` and kwargs in `run()` will override the `__init__` values.

**Comment by orbeckst** [comment]
@kain88-de can you have a look and see how much work it is to get this done for 0.17.0?

**Comment by kain88-de** [comment]
From my memory. 

A problem is that we often use information from the start stop step arguments in the init function. This means all sub classes have to be checked after we add a deprecation to the base class. 

Verbosity is likely easier. There might be a corner case in the PCA analysis. 

I’m not sure if there are some surprises in the decorators like base_analysis. 

With writing tests that’s at least a couple of hours of work.

**Comment by orbeckst** [comment]
@richardjgowers can we get deprecations into 0.19.0 #1971 ?

In particular, the `start`/`stop`/`step` in `run()` is reversing a decision that we made much earlier when we tried to move them from `run` to `__init__`. We have depreciation code that says "start/stop/step will be removed from run() in 0.17.0" :-p.

**Comment by richardjgowers** [comment]
@orbeckst I don't understand what needs doing for this, do some classes have start/stop/step in run?

**Comment by orbeckst** [comment]
Classes *should* have start/stop/step in `run()` but not in `__init__`.

At least one (rms.RMSD.run()) has it already in `run()` but it is deprecated. It should be un-deprecated because it will become the norm.

**Comment by jbarnoud** [comment]
Here are the things we need to do for this to come true:

* [ ] Add `start`, `stop`, `step`, and `verbose` arguments to `AnalysisBase.run`.
* [ ] Remove deprecated `quiet` from `AnalysisBase.__init__`.
* [ ] Add deprecation warnings to `AnalysisBase.__init__`.
* [ ] In analysis classes, move some logic from `__init__` to `_prepare`.

**Comment by orbeckst** [comment]
@nawtrey added a parallel  DensityAnalysis in https://github.com/MDAnalysis/pmda/pull/93 which can be back-ported.

**Comment by IAlibay** [comment]
@orbeckst the removal of `start`, `stop`, and `step` from `AnalysisBase.__init__()` are next up on my list of things to do for #2443 

As it is a bit unclear from the thread, I thought it might be worth asking if there is still work to be done here, or is it ready for removal?

**Comment by orbeckst** [comment]
- I assume for anything using AnalysisBase, just removing will be fine. Just check the actual code of the analysis classes for any workarounds, deprecation messages, etc. 
- Any of the analysis classes that do _not_ use AnalysisBase: keep them as they are as they do not fall under this issue. (If we can get any other classes more in line with the AnalysisBase API for 1.0 then that would be great — but raise separate issues and reference this issue.)

**Comment by IAlibay** [comment]
@orbeckst I _think_ this was completed with #2505, is this good to close?

**Comment by orbeckst** [comment]
Yes, thanks for the reminder. This was done with #2505 and the changes to verbose (as part of one of the bigger gsoc PRs).
