### ISSUE TITLE
apt sources to not work for debian

### ISSUE THREAD

**Issue by GoogleCodeExporter** [MDAnalysis/mdanalysis#149]
The method you provide for installing apt sources does not actually work on a debian system + you do not seem to provide a `sources.list` line for debian systems.

Please just remove the line on your downloads page that says this is for "Ubuntu/Debian" --> in fact, the instructions you give only work on Ubuntu systems.

Original issue reported on code.google.com by `johnfra...@gmail.com` on 12 Jul 2013 at 11:22

**Comment by orbeckst** [comment]
We haven't been building binary distributions since 0.10.0 (too many things to keep track of, too little time) so I am closing this issue. It is not resolved but it does not really matter at the moment.
