### ISSUE TITLE
String data types in numpy

### ISSUE THREAD

**Issue by kain88-de** [MDAnalysis/mdanalysis#1497]
https://docs.scipy.org/doc/numpy/reference/arrays.dtypes.html

I came across this today when I noticed problems with `dtype='S8'` in my own scripts. Using the recommended unicode dtype *U* (`dtype='U'`) fixed any string handling problems I had. The problem is that *S* interprets the strings as the bytes type in python 3.

I think we do sometimes use the old string dtype in our library. For python3 compatibility we should likely change all of them to *U*.

**Comment by richardjgowers** [comment]
I thought we currently use `dtype=object` everywhere for strings?  I'll check to see if this will affect us

**Comment by kain88-de** [comment]
Does object handle the encoding issues of unicode vs ascii?

**Comment by tylerjereddy** [comment]
Please provide an example unit test demonstrating the failure if you think this is still a concern.

**Comment by kain88-de** [comment]
If we have no trouble right now I will close it.
