### ISSUE TITLE
StringIO Python 3 Failure

### ISSUE THREAD

**Issue by tylerjereddy** [MDAnalysis/mdanalysis#1513]
There's a test failure as reported below:

```
_______________________ TestIsstream.test_StringIO_read ________________________
[gw0] linux -- Python 3.6.1 /home/travis/miniconda/envs/test/bin/python
self = <testsuite.MDAnalysisTests.utils.test_streamio.TestIsstream testMethod=test_StringIO_read>
    def test_StringIO_read(self):
        with open(datafiles.PSF, "r") as f:
>           obj = StringIO(f)
E           TypeError: initial_value must be str or None, not _io.TextIOWrapper
testsuite/MDAnalysisTests/utils/test_streamio.py:77: TypeError
```

A similar `TyperError` has been [reported and discussed elsewhere](https://stackoverflow.com/questions/31064981/python3-error-initial-value-must-be-str-or-none) for Python 2 to 3 ports, so that should get us started.

**Comment by kain88-de** [comment]
We already use the suggested solution of `f.read()` with *cStringIO* in another [streamio-test](https://github.com/MDAnalysis/mdanalysis/blob/192e75b57d4f249a203e5a9d3aa97d0951419f32/testsuite/MDAnalysisTests/utils/test_streamio.py#L67)
