### ISSUE TITLE
Pytest xdist causes failures

### ISSUE THREAD

**Issue by richardjgowers** [MDAnalysis/mdanalysis#1529]
Originally [brought up here](https://github.com/MDAnalysis/mdanalysis/pull/1524#issuecomment-316265602)

Using parallel execution of tests on travis seems to sometimes cause failures with the error message:
```
==================================== ERRORS ====================================
_____________________________ ERROR collecting gw1 _____________________________
Different tests were collected between gw0 and gw1. The difference is:
```

**Comment by kain88-de** [comment]
I get the same error on my desktop

**Comment by richardjgowers** [comment]
From what I can see, this can be caused by calling something in a parametrize which has a random return order, such as `dict.items`, as when individual processes call this they (might) get a different ordering of items.
