### ISSUE TITLE
Segfaults in utils/test_streamio.py

### ISSUE THREAD

**Issue by utkbansal** [MDAnalysis/mdanalysis#1534]
As seen in #1472 there are segfaults if we try to run some tests in `test_streamio.py`. The current fix is to just mark those tests for skipping.

The travis log for the [old numpy build](https://travis-ci.org/MDAnalysis/mdanalysis/jobs/252952480)

```
____________________ MDAnalysisTests/utils/test_streamio.py ____________________
[gw0] linux2 -- Python 2.7.13 /home/travis/miniconda/envs/test/bin/python
Slave 'gw0' crashed while running 'MDAnalysisTests/utils/test_streamio.py::TestNamedStream_filename_behavior::()::test_expanduser_noexpansion_returns_NamedStream'
____________________ MDAnalysisTests/utils/test_streamio.py ____________________
[gw2] linux2 -- Python 2.7.13 /home/travis/miniconda/envs/test/bin/python
Slave 'gw2' crashed while running 'MDAnalysisTests/utils/test_streamio.py::TestNamedStream_filename_behavior::()::test_expandvars'
____________________ MDAnalysisTests/utils/test_streamio.py ____________________
[gw3] linux2 -- Python 2.7.13 /home/travis/miniconda/envs/test/bin/python
Slave 'gw3' crashed while running 'MDAnalysisTests/utils/test_streamio.py::TestNamedStream_filename_behavior::()::test_expandvars_noexpansion_returns_NamedStream'
============== 3 failed, 5123 passed, 1 skipped in 560.61 seconds ==============
```

There is also a comment in the tests by @orbeckst `Segmentation fault when run as a test on Mac OS X 10.6, Py 2.7.11 [orbeckst]`

**Comment by kain88-de** [comment]
i'd be interested to see if these segfaults still occur with python 3.6

**Comment by richardjgowers** [comment]
I don't think they do, which I suspect is something to do with how namedstream uses os.PathLike, or whatever the changes in 3.6 were related to strings/streams/paths.

**Comment by orbeckst** [comment]
Is this still a problem?

**Comment by orbeckst** [comment]
@richardjgowers @kain88-de should we close this?

**Comment by orbeckst** [comment]
Just to answer my question: the tests are currently skipped. It needs to be evaluated if they still produce segfaults and if so, what the deeper reason is.
