### ISSUE TITLE
release 0.17.0

### ISSUE THREAD

**Issue by richardjgowers** [MDAnalysis/mdanalysis#1536]
TODO for 0.17:
- [x] fix tutorial
- [x] remove yield based tests
- [x] py3
- [x] attribute setting
- [x] things with deprecations: #1453
- [ ] anything [labelled *defect*](https://github.com/MDAnalysis/mdanalysis/issues?utf8=%E2%9C%93&q=is%3Aopen%20is%3Aissue%20label%3Adefect%20milestone%3A0.17.0%20) for 0.17.0

EDIT:
- deprecation stuff and defects – @orbeckst

**Comment by richardjgowers** [comment]
So I've been pretty snowed under because of my real job, but we *should* really do the release asap.  The only thing missing is the attribute setting that I've made an attempt at but haven't finished.  I'm going to try and finish that this week (or realise it's too tricky for me to do quickly so push it further down the line), so hopefully we can release 0.17 this week.

**Comment by kain88-de** [comment]
how does it look @richardjgowers any free time soon?

**Comment by kain88-de** [comment]
can we help with something?

**Comment by richardjgowers** [comment]
#1186 still needs a review.  It doesn't do the "nice" things we want, but it at least stops the gotchas that are currently possible

**Comment by kain88-de** [comment]
gotchas like #1683

**Comment by orbeckst** [comment]
@richardjgowers do we have some time frame for getting 0.17.0 out? Discussion on develop on https://github.com/MDAnalysis/mdanalysis/milestone/10 and perhaps soliciting some commitments to fix issues on the list?

**Comment by kain88-de** [comment]
@richardjgowers how does a release look like?

**Comment by richardjgowers** [comment]
Yeah we really really should, I'm going to prune the 17.0 milestone to things we need to include (eg GSD, molecules from TPR) and once it's burnt through I'll do the release

**Comment by kain88-de** [comment]
Should we concentrate on bug fix PRs and merge the features after a release?  That leaves some time for testing with the nightly builds.

**Comment by richardjgowers** [comment]
I'd like to include GSD, PSA tests and JB's molnum PRs. TNG and Reader.timeseries can be kicked into 0.18/the future. I'll update the milestone and try and track using that

**Comment by orbeckst** [comment]
I set a due date of Dec 31 – we really should make an effort to get this out with a 2017 time stamp... If it becomes a nice Christmas present even better :-).

**Comment by kain88-de** [comment]
So #1578 is the only thing that is left now?

**Comment by kain88-de** [comment]
are there any bugs still keeping us from a release. New features can always go into another release. Our last release is already half a year ago.

**Comment by richardjgowers** [comment]
I just wanna get the Universe PR that Manel started in and I'll do this release

**Comment by richardjgowers** [comment]
Ok I started this today.. so I've merged develop into master and pushed that version of master to this repo, but I'm having some trouble building the new .c files, but it's been a long day and I've probably missed something...

There's a PR up which starts 0.17.1 at least.

**Comment by richardjgowers** [comment]
Ok we're live on pypi, still to do docs & conda release

**Comment by kain88-de** [comment]
I can have a look at conda on Sunday. The recipe needs more work to update and reflect the python 3 support.

**Comment by richardjgowers** [comment]
Ok cool.  I tested and pip & python 3 on a fresh environment works fine.  If you need to update the recipe on master you can just push straight to the branch without any trouble.

**Comment by orbeckst** [comment]
I updated the master docs https://www.mdanalysis.org/docs/ by doing in a mda3 0.17.0 environment
```
(cd package && python setup.py build_sphinx)
GH_TOKEN=<secret> ./maintainer/deploy_master_docs.sh
```

(If you don't want to use a token, edit the script and remove the token and just use your normal way of authenticating.)

**Comment by jbarnoud** [comment]
0.17 became available on pypi just as I was telling to somebody we would have to install the dev version for python 3 support. Perfect timing :stuck_out_tongue:

**Comment by kain88-de** [comment]
conda builds are done. the package is public on conda-forge

**Comment by kain88-de** [comment]
Only the blog post is missing then.

**Comment by jbarnoud** [comment]
@kain88-de merged the blog post and I just twitted it. One more release shipped. Congrats you all!
