### ISSUE TITLE
u.dihedrals.dihedrals() returns negative angles as positive

### ISSUE THREAD

**Issue by nestorwendt** [MDAnalysis/mdanalysis#1554]
### Expected behaviour
u.dihedrals.dihedrals() to return the angles in radians.

### Actual behaviour
u.dihedrals.dihedrals() returns the angles in radians, but all the negative angles are positive.

### Note
u.dihedrals._dihedralsSlow() works, so the problem should be in the Cython implementation.

### Code to reproduce the behaviour

``` python
In [1]: import MDAnalysis as mda
        from MDAnalysis.core.topologyattrs import Angles, Dihedrals
        from MDAnalysis.topology.guessers import guess_angles, guess_dihedrals

In [2]: u = mda.Universe('example.pdb', 'example.trr')

In [3]: angles_list = Angles(guess_angles(u.bonds), guessed=True)
        u.add_TopologyAttr(angles_list)
        dihedrals_list = Dihedrals(guess_dihedrals(u.angles), guessed=True)
        u.add_TopologyAttr(dihedrals_list)

In [4]: u.dihedrals.dihedrals()[:10], u.dihedrals._dihedralsSlow()[:10]
Out[4]: (array([ 3.02015785,  0.0497024 ,  1.87342152,  1.09379527,  1.59478878,
                 2.97920885,  1.02250218,  2.65210548,  0.44485898,  1.89326366]),
         array([ 3.02015829, -0.04970198,  1.87342155, -1.09379518,  1.59478879,
                 2.97920895, -1.02250218,  2.65210557, -0.44485903,  1.89326358], dtype=float32))

```

### Currently version of MDAnalysis:
0.16.2

**Comment by orbeckst** [comment]
@richardjgowers I am throwing this at you for a start because I think you wrote that part of the code. Feel free to re-assign but at least a comment/review of the problem from you would be very helpful. This looks like a serious bug that needs to be fixed asap.

**Comment by nestorwendt** [comment]
I was looking at this yesterday and the error is in the *y* calculation. From wikipedia:

![Dihedral angle formula](https://wikimedia.org/api/rest_v1/media/math/render/svg/a561bd1500d44bf102e7426692bd572cd40b531e)

Now, the *y* is calculated like that: `y = sqrt(xp[0]*xp[0] + xp[1]*xp[1] + xp[2]*xp[2]);`
It should be `y = (xp[0]*vb[0] + xp[1]*vb[1] + xp[2]*vb[2]) / sqrt(vb[0]*vb[0] + vb[1]*vb[1] + vb[2]*vb[2]);`

If there's no problem I can make the PR.

**Comment by jbarnoud** [comment]
@nestorwendt Pull requests are always welcome :smiley:

**Comment by richardjgowers** [comment]
@nestorwendt yeah go for it.  It looks like the trouble is in `lib.distances.calc_dihedrals`.  You can use the below example as a test in [test_distances](https://github.com/MDAnalysis/mdanalysis/blob/develop/testsuite/MDAnalysisTests/utils/test_distances.py)

```python
In [1]: import numpy as np

In [7]: from MDAnalysis.lib.distances import calc_dihedrals

In [2]: a = np.array([[-1, 0, 0]], dtype=np.float32)

In [3]: b = np.array([[0, 0, 0]], dtype=np.float32)

In [4]: c = np.array([[0, 1, 0]], dtype=np.float32)

In [5]: d1 = np.array([[1, 1, 0]], dtype=np.float32)

In [9]: d2 = np.array([[0, 1, 1]], dtype=np.float32)

In [10]: d3 = np.array([[0, 1, -1]], dtype=np.float32)

In [11]: calc_dihedrals(a, b, c, d2)
Out[11]: array([ 1.57079633])

In [12]: calc_dihedrals(a, b, c, d3)
Out[12]: array([ 1.57079633])
