### ISSUE TITLE
Setting positions should require exact shape match

### ISSUE THREAD

**Issue by kain88-de** [MDAnalysis/mdanalysis#1560]
### Expected behaviour

setting atom positions only works if arrays match in shape

### Actual behaviour

If the array has a shape of `(3)` and dimension one it also works. Setting all atoms to that one array.

### Code to reproduce the behaviour

``` python
import MDAnalysis as mda

u = mda.Universe(top, trj)
u.atoms.positions = np.ones(3)
....

```

### Currently version of MDAnalysis:
(run `python -c "import MDAnalysis as mda; print(mda.__version__)"`)
0.17.0dev

**Comment by jbarnoud** [comment]
Shouldn't we allow broadcasting?

**Comment by kain88-de** [comment]
A student of mine used the above code to translate a protein. He is a beginner programmer and didn't see the mistake with that. There wasn't even a warning or anything else that he just placed *all* atoms on the same position.

**Comment by jbarnoud** [comment]
I see your point, but isn't this a "learning numpy" issue rather than an MDAnalysis one?

Note that I would not mind the check; I am just discussing.

**Comment by kain88-de** [comment]
It is not transparent to the user that he is now using numpy. This is also a possible place to introduce subtle bugs in our own code when a numpy cast returns only a position, or we change an algorithm from using a single atom. It is also a question if we normally want to allow setting all atoms to the same position.  I'm not set on introducing such a check but I do see benefits of doing it.

**Comment by mnmelo** [comment]
I think that since it's already called position**s** (plural) it's reasonable to expect that a single value sets all (even if the user isn't numpy-aware); as in: "set positions to [x,y,z]".

Of course, we could just set some warnings. Aesthetics aside (I hate their intrusiveness), I think it'd make it feel very training-wheels-like for more seasoned MDAnalysis/numpy users.

**Comment by richardjgowers** [comment]
Yeah so under the hood what is happening is we're allowing numpy broadcasting.  I don't really want to mess with that as it will annoy more proficient users.

**Comment by kain88-de** [comment]
Ok the majority is for keeping the current behavior.
