### ISSUE TITLE
The minimal build on TravisCI should be the first build in the build matrix

### ISSUE THREAD

**Issue by utkbansal** [MDAnalysis/mdanalysis#1561]
Currently, the minimal build in TravisCI is the last build. It should either be the first build so that the developer gets the errors sooner or if that isn't the purpose of the minimal build, we should completely scrap it - it is redundant.

**Comment by kain88-de** [comment]
The minimal build exists to check that the core library works with a minimal set of dependencies. We want to ensure that the extra required dependencies only affect the analysis modules
