### ISSUE TITLE
Dihedrals.dihedrals() and _calc_dihedral* returning inverse angles

### ISSUE THREAD

**Issue by nestorwendt** [MDAnalysis/mdanalysis#1565]
### Expected behaviour
Dihedrals.dihedrals() and _calc_dihedral* to return the dihedral angle in radians.

### Actual behaviour
Dihedrals.dihedrals() and _calc_dihedral* return the inverse of the correct angle.

### Note
This happens because of how the vectors are calculated. Dihedral.value() works fine, following the IUPAC convention. I will soon make a PR to fix this issue.

### Code to reproduce the behaviour

``` python
import MDAnalysis as mda
from MDAnalysisTests.datafiles import PSF, DCD
import numpy as np
u = mda.Universe(PSF, DCD)

dihedral = [dihedral.value() for dihedral in u.dihedrals]
cython = np.rad2deg(u.dihedrals.dihedrals())
numpy = np.rad2deg(u.dihedrals._dihedralsSlow())

np.testing.assert_almost_equal(dihedral, cython, decimal=1)
np.testing.assert_almost_equal(dihedral, numpy, decimal=1)
np.testing.assert_almost_equal(cython, numpy, decimal=1)
```

### Currently version of MDAnalysis:
0.16.2

**Comment by mnmelo** [comment]
Closed by 0f9ef86
