### ISSUE TITLE
AtomGroup.dimensions returns view sometimes

### ISSUE THREAD

**Issue by richardjgowers** [MDAnalysis/mdanalysis#1582]
`AtomGroup.dimensions` should **always** return a copy of the dimensions information for a given timestep

For this issue:
 - create tests which loop over all `Timestep` object formats and check that a copy is returned

related #1575

**Comment by orbeckst** [comment]
See https://github.com/MDAnalysis/mdanalysis/issues/1575#issuecomment-320104322 in particular.

**Comment by orbeckst** [comment]
@richardjgowers is this issue for creating tests and then #1575 is for fixing the issue?

**Comment by richardjgowers** [comment]
@orbeckst I think #1575 is more about `Timestep`, so I made this to deal with the `AtomGroup.dimensions` issue.  Fixing #1575 *might* fix this too, but they're independent in terms of (esp. black box) tests

**Comment by orbeckst** [comment]
Good point, `Timestep.dimensions` vs `AtomGroup.dimensions`... if we implement https://github.com/MDAnalysis/mdanalysis/issues/1575#issuecomment-320104322 then `Timestep.dimensions` would always be a view and `AtomGroup.dimensions` should just point to it. Then we would be done.
