### ISSUE TITLE
MDAnalysisTest and mock

### ISSUE THREAD

**Issue by tclick** [MDAnalysis/mdanalysis#1584]
Because MDAnalysis is shifting towards Python 3, the MDAnalsysisTest does not necessarily require the mock package because it is already available in unittest. To avoid the following error, I suggest that a try/except block be implemented.

```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-2-52912a4f0416> in <module>()
----> 1 import MDAnalysisTests

/opt/homebrew/anaconda3/envs/mda-py3/lib/python3.6/site-packages/MDAnalysisTests/__init__.py in <module>()
    142     pass
    143
--> 144 from MDAnalysisTests.util import (
    145     block_import,
    146     executable_not_found,

/opt/homebrew/anaconda3/envs/mda-py3/lib/python3.6/site-packages/MDAnalysisTests/util.py in <module>()
     38 from functools import wraps
     39 import importlib
---> 40 import mock
     41 import os
     42

ModuleNotFoundError: No module named 'mock'
```

Simply replace the ```import mock``` with
```
try:
    import mock
except ImportError:
    from unittest import mock
```
I realize that MDAnalysis requires the mock package, and it is understandable for Python 2, but because this package is already implemented in 3, should it be removed, or do you want to keep this dependency?

I loaded this into Python 3.6.2 under Anaconda.
```
>>> sys.version
3.6.2 |Continuum Analytics, Inc.| (default, Jul 20 2017, 13:14:59) \n[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)]
```

**Comment by kain88-de** [comment]
We have a dependency on mock in our setup.py. The package should be installed when you install the testsuite. Honestly I'm surprised how you hit that error.

For the time being I would also leave it like that. There isn't a good way to specify python2 only dependencies in the setup.py currently.

**Comment by tclick** [comment]
I hit that error because I had uninstalled mock while working with some of my own work, but that's okay. I understand that this can be a problem. I'll reinstall it, but it is good to note for future reference, especially if you eventually move away from Python 2.
