### ISSUE TITLE
Regarding creating AtomGroups for hydrogens, donors, and acceptors by doing selections. 

### ISSUE THREAD

**Issue by cy16f01** [MDAnalysis/mdanalysis#1591]
@richardjgowers, @dotsdl, @arose, @orbeckst .....
I have done md simulation in gromacs. This is my .gro (final .gro file after the md run) file which contains glycine and water molecules...
Glycine-Water
XXX
1GLYN N 1 1.554 0.192 1.237 0.2337 0.7678 -0.4403
1GLYN HT1 2 1.595 0.113 1.190 1.2957 1.3150 -0.4663
1GLYN HT2 3 1.567 0.275 1.179 0.2555 1.4287 0.4977
1GLYN CA 4 1.596 0.220 1.375 -0.1659 0.2593 -0.2142
1GLYN HA1 5 1.690 0.279 1.386 0.3912 -0.2223 -2.2182
1GLYN HA2 6 1.527 0.296 1.419 -0.2036 -0.1122 0.3771
1GLYN C 7 1.590 0.109 1.479 -0.4882 0.5503 0.0814
1GLYN OT1 8 1.489 0.061 1.528 -0.1025 -0.2671 0.0940
1GLYN OT2 9 1.711 0.048 1.513 -0.4918 0.6753 0.3137
1GLYN HO2 10 1.698 -0.035 1.560 -0.8295 -0.2734 -1.4207
2SOL OW 11 1.974 1.991 1.614 0.2492 -0.3487 0.3687
2SOL HW1 12 2.040 1.918 1.594 -0.6780 -1.3661 0.9449
2SOL HW2 13 1.884 1.951 1.630 -0.5310 1.0328 -0.4632
3SOL OW 14 0.331 0.052 1.858 -0.2124 0.4141 -0.8687
3SOL HW1 15 0.310 -0.007 1.936 0.1912 -0.3242 -1.3072
3SOL HW2 16 0.293 0.011 1.775 0.6684 0.4113 -1.2785
4SOL OW 17 0.482 1.719 1.590 -0.5622 -0.3605 0.2368
4SOL HW1 18 0.478 1.632 1.541 0.8012 -1.4225 1.9691
4SOL HW2 19 0.444 1.707 1.682 0.8493 0.5546 0.9465
5SOL OW 20 0.168 1.334 1.467 0.1289 -0.3488 0.2064
5SOL HW1 21 0.149 1.375 1.556 3.3113 1.1012 0.2810
5SOL HW2 22 0.167 1.234 1.475 1.0811 -0.2295 2.0747
.
.
.
how do i create atom groups, donors and acceptors by doing selections here..??
I tried as following...
1] import MDAnalysis as mda
from MDAnalysis.tests.datafiles import ('md.gro', 'md.trr')
it is giving the error as:-
from MDAnalysis.tests.datafiles import ('md.gro', 'md.trr')
 SyntaxError: invalid syntax
2] import MDAnalysis as mda
from MDAnalysis.tests.datafiles import GRO, TRR
it is giving the error as:-
ImportError: Traceback (most recent call last)
<ipython-input-29-ef27eb16969c> in <module>()
ImportError: cannot import name TOP

Than how do i import .gro/pdb/xtc/trr/top/tpr files thn....and further create AtomGroups for hydrogens, donors, and acceptors by doing selections, (and further in order to calculate HBond autocorrelation functions).

Thank you...

**Comment by richardjgowers** [comment]
@cy16f01  you should be able to create a `Universe` from the files like this:
```python
import MDAnalysis as mda

u = mda.Universe('md.gro', 'md.trr')
```

Then selecting donors/acceptors depends on what bonds you're interested in.  If you're interested in water bonded to the nitrogen

```python
# first you want to create an array of the hydrogens
hydrogens = u.atoms.select_atoms('name HW*')

# then you want to create an array of the donors for each hydrogens
# we want an array which repeats each oxygen twice, as each is bonded to two hydrogens
# this is one way to do that
OW = u.atoms.select_atoms('name OW')
donors = sum(sum([x, y]) for x, y in zip(OW, OW))


acceptors = u.atoms.select_atoms('name N')
```

I'm going to close this because it's better suited to the [help mailing list](http://help.mdanalysis.org)
