### ISSUE TITLE
Support for secondary structure identification

### ISSUE THREAD

**Issue by richardjgowers** [MDAnalysis/mdanalysis#1612]
## Is your feature request related to a problem? ##
`gmx do_dssp` isn't making nice with DSSP version 3.1.4, and I would like to quantify the secondary structure of my protein.

## Describe the solution you'd like ##
An MDAnalysis version where I don't need to load my entire trajectory into memory.

## Describe alternatives you've considered ##
MDTraj has `compute_dssp` but it loads the trajectory into memory.

## Additional context ##

The issue text was copied from #2608 (duplicate), now that this issue is about dssp and not stride.

**Comment by jbarnoud** [comment]
Do you want to read a STRIDE (or DSSP) output or do you want to implement the method in MDAnalysis?

In anyway we'll need a secondary structure topology attribute. What should be its value for the atoms that are not part of a protein? `numpy.nan`?

**Comment by orbeckst** [comment]
DSSP (new) is open source http://swift.cmbi.ru.nl/gv/dssp/ ; a while back I looked into wrapping that was too complicated. A cython reimplementation  that uses a Universe would be useful.

**Comment by richardjgowers** [comment]
Ok I've started this.  I've got a conda build recipe for STRIDE [here](https://github.com/MDAnalysis/stride) which should allow `conda install stride` to get the binary in place.  I've then got a `pystride` python package, which runs the binary and returns the output.  Then within MDA we can have a layer (probably `MDAnalysis.analysis.stride`) which takes mda objects (`AtomGroup` and `Universe`) and goes to and from the pystride package.

**Comment by richardjgowers** [comment]
I'm a little hesitant to put the stride stuff into `core/` because it relies on an external binary, which can be a little flaky.

**Comment by jbarnoud** [comment]
It for sure should not go in core as it calls an external program. Also, now that I think about it, we do not have support for time dependent topologies, so we cannot store the secondary structure in a topology attribute. I uses Martini too much, I forgot secondary structures could change over time...

**Comment by richardjgowers** [comment]
@jbarnoud I was actually thinking today we could do time dependent `TopologyAttr`s by having a mechanism similar to what @mnmelo used for `UpdatingAtomGroup` which lazily refreshes contents if the current `ts.frame` is different.

**Comment by orbeckst** [comment]
You could consider the secondary structure an auxiliary that is indexed with residue index.

**Comment by orbeckst** [comment]
I removed "STRIDE" from the issue title because of licensing concerns MDAnalysis/stride#2

**Comment by orbeckst** [comment]
It would be great if we had "pydssp" ... see https://github.com/MDAnalysis/dssp/issues/1
