### ISSUE TITLE
Universe.load_new() should return universe

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/mdanalysis#1613]
### Expected behaviour

I would like the example in http://www.mdanalysis.org/docs/documentation_pages/coordinates/memory.html#creating-an-in-memory-trajectory-of-a-sub-system to actually work:
```python
u2 = mda.Merge(protein).load_new(
         AnalysisFromFunction(lambda ag: ag.positions.copy(),
                              protein).run().results,
         format=MemoryReader)
```

### Actual behaviour
`Universe.load_new()` returns a tuple `(array, "MEMORY")`. 

I honestly don't remember the rationale for `load_new` to return the filename and detected file format. The latter might be marginally useful to ascertain what the file format detection algorithm came up with. 

However, I think making it return the `Universe` itself might create a better user experience in the long run.

### Code to reproduce the behaviour
See above.

### Currently version of MDAnalysis:
(run `python -c "import MDAnalysis as mda; print(mda.__version__)"`)

0.16.2

**Comment by richardjgowers** [comment]
Yep, sounds saner to me

**Comment by orbeckst** [comment]
Please see PR #1616. Given that this is a (mild) API break I'd like to get this into 0.17.0.
