### ISSUE TITLE
Docs for analysis modules should explain `verbose`

### ISSUE THREAD

**Issue by kaceyreidy** [MDAnalysis/mdanalysis#1630]
Modules in MDAnalysis.analysis should use the MDAnalysis progress bar.

EDIT (following the discussion below) — @orbeckst
* analysis classes based on AnalysisBase should document that `verbose` enables the progress bar (and also explain what else is shown)
* the default should possibly be `verbose=True`
* changed issue title

**Comment by orbeckst** [comment]
Which analysis classes in particular are missing the progress meter?

I am asking because anything that is already derived from [AnalysisBase](http://www.mdanalysis.org/docs/documentation_pages/analysis/base.html#MDAnalysis.analysis.base.AnalysisBase) should have the progressmetere (when you use `verbose=True`).

**Comment by kaceyreidy** [comment]
PCA doesn't have a progress bar.

**Comment by orbeckst** [comment]
Did you try with `verbose=True`?

**Comment by kaceyreidy** [comment]
Now I did.

**Comment by orbeckst** [comment]
Should `verbose=True` be the default?

**Comment by kaceyreidy** [comment]
I would say yes.

**Comment by kain88-de** [comment]
Verbose is a common keyword used to enable additional reporting for a lot of scientific and other programs. We like to stick to common idoms like that. 

But the docs are not generated correctly on this class to show that the verbose keyword exists and what it means.

**Comment by orbeckst** [comment]
I edited the issue and re-open.

**Comment by orbeckst** [comment]
@kaceyreidy do you want to make a PR for this issue?
