### ISSUE TITLE
Generators cannot call StopIteration from python 3.6 and newer

### ISSUE THREAD

**Issue by kain88-de** [MDAnalysis/mdanalysis#1662]
We currently rely on StopIteration in our single frame reader [code](https://github.com/MDAnalysis/mdanalysis/blob/bc36840e81ea48ec182f0e57fe11d48572ab2996/package/MDAnalysis/coordinates/base.py#L1943). This usage has been deprecated since py 3.5 [PEP 479](https://www.python.org/dev/peps/pep-0479/). This means in python 3.7 our single frame class will stop working.

I'm currently not sure what the best solution is based on the examples in the PEP

**Comment by tylerjereddy** [comment]
I suppose if we're really keen we could start a WIP PR where travis builds & tests with Python 3.7 alpha releases in the next few weeks / months.

**Comment by jbarnoud** [comment]
If I well remember, the recommended usage is to use an empty  `return` instead of raising `StopIteration`. This should work on earlier versions of python as well.
