### ISSUE TITLE
How useful is the distances OpenMP backend?

### ISSUE THREAD

**Issue by kain88-de** [MDAnalysis/mdanalysis#1670]
[benchmark gist](https://gist.github.com/kain88-de/944da763c85cc4d932a515e260bc4b6a)

I've done a check. For triclinic distance calculations the serial and OpenMP enabled code run at the same speed. I tried to give OpenMP a good chance by setting the number of particles to 15000 which is already a large number. The final run times are about the same for each backend. When I check the CPU cores that are used during the calculation with `htop` it also looks like our OpenMP backend is running on a single thread.

Is the OpenMP backend really worth the extra cost in maintenance?  I'm not even sure what the gains of OpenMP could be when even large inputs complete in a second.

**Comment by richardjgowers** [comment]
@kain88-de it sounds like your installation didn't compile with openmp, I get *some* gains.  What does `distances.USED_OPENMP` say? (Should be True/False)

```
In [5]: %timeit distances.distance_array(pos, pos, box=box)
   ...: 
1 loop, best of 3: 2.71 s per loop

In [6]: %timeit distances.distance_array(pos, pos, box=box, backend='openmp')
   ...: 
1 loop, best of 3: 1.42 s per loop

```

That said, I'm not a huge fan of the extra backends (and I wrote them : /).  I think the way forward for performance is through splitting Universes and dask, so multicore backends are probably just confusing the picture.  I'd happily remove them.

**Comment by kain88-de** [comment]
Oh right I didn't build with openMP. This should raise a warning though when using the openMP backend.

I'll make a new test with the openMP backend enabled.

**Comment by kain88-de** [comment]
Yeah when I compile with OpenMP I see a speed up of factor 2 on my dualcore + HT laptop.



> That said, I'm not a huge fan of the extra backends (and I wrote them : /). I think the way forward for performance is through splitting Universes and dask, so multicore backends are probably just confusing the picture. I'd happily remove them.

I agree. But don't worry about removing them for now.

**Comment by orbeckst** [comment]
>  I think the way forward for performance is through splitting Universes and dask, so multicore backends are probably just confusing the picture. I'd happily remove them.

I am obviously a big fan of using dask but there's something to be said for having accelerated calculations readily available, especially for interactive or simple analysis. A factor of 2-4 for distance calculations "for free" that might also be used in selections is good for users. (I just find it annoying that OpenMP on macOS does not work out of the box...) 

Have you ever tried VMD's g(r) on GPUs? Totally blows you away when compared to the multi-threaded implementation – their "GPU backend for g(r)" is pretty awe-inspiring. 

Admittedly, we don't have to over-engineer MDAnalysis in anticipation of developments that *might* come in the future, especially we don't currently have anyone working in earnest on multi-threading or GPU accelerations and perhaps once we have we can think about a better way to organize things.

**Comment by kain88-de** [comment]
If you want a fast distance histogram try [cadishi](http://cadishi.readthedocs.io/en/latest/). With the openmp Backend we have to check more though. I do not know how well it scales for smaller number of particles and I would say everything that runs in under half a second a fast enough for selections.
