### ISSUE TITLE
NetworkX compatibility 

### ISSUE THREAD

**Issue by richardjgowers** [MDAnalysis/mdanalysis#1673]
One of our requirements networkx has released v2.0, which is an API break from 1.0.  We should check instances where we use networkx (only `analysis.leaflet`) and check that our usage is future proof (or pin to version 1.x only)

I think @orbeckst wrote leaflet? But it's probably easy for anyone to do

Migration guide:
https://networkx.github.io/documentation/stable/release/migration_guide_from_1.x_to_2.0.html

**Comment by tylerjereddy** [comment]
Note that Aric Hagberg (one of the original authors) works here if you need me to ask him anything.

**Comment by kain88-de** [comment]
a short search reveals that we only use it in the leaflet code and all tests pass. Locally and  I think on our CI as well. Conda-forge already has networkx v2.0

**Comment by orbeckst** [comment]
Good that 2.0 passes. We could also replace networkx find connected components with the equivalent scipy function, which I saw in a recent version. 

--
Oliver Beckstein
email: orbeckst@gmail.com

**Comment by orbeckst** [comment]
Is this still an issue or can we close it? test_leaflet seems to be passing so I would *think* that this is still ok.

**Comment by richardjgowers** [comment]
my concern was leaflet coverage is 73%, so there's a fair chunk of space where an outdated networkx call could live

**Comment by kain88-de** [comment]
Did you ever check it the networkx calls are covered?

**Comment by orbeckst** [comment]
According to https://coveralls.io/builds/14437937/source?filename=%2Fhome%2Ftravis%2Fminiconda%2Fenvs%2Ftest%2Flib%2Fpython3.6%2Fsite-packages%2FMDAnalysis%2Fanalysis%2Fleaflet.py all the lines with networkX functionality are tested and the tests pass so I assume that we are using the latest networkx correctly.

I'll close this issue with no further actions. (Feel free to reopen if necessary.)
