### ISSUE TITLE
lib.distances.transform_StoR doesn't check input type

### ISSUE THREAD

**Issue by richardjgowers** [MDAnalysis/mdanalysis#1699]
The dtype of the box seems to get checked, but not for the S array input, so you get a nonsense answer

### Code to reproduce the behaviour

``` python
import MDAnalysis as mda

box = np.array([10, 7, 3, 45, 60, 90])
s = np.array([[0.5, -0.1, 0.5]])

box = box.astype(np.float32)

In [9]: mda.lib.distances.transform_StoR(s, box)
Out[9]: array([[  2.62144141e+06,  -1.00000000e-01,   5.00000000e-01]])

In [10]: s.dtype
Out[10]: dtype('float64')

In [15]: s = s.astype(np.float32)

In [16]: s
Out[16]: array([[ 0.5, -0.1,  0.5]], dtype=float32)

In [17]: mda.lib.distances.transform_StoR(s, box)
Out[17]: array([[ 5.75      ,  0.36066014,  0.75000012]], dtype=float32)


```

### Currently version of MDAnalysis:
(run `python -c "import MDAnalysis as mda; print(mda.__version__)"`)

0.17-dev

**Comment by palnabarun** [comment]
I looked into the code and found that the box is validated by `_box_check` function. We can have a function which validates the S array too by checking whether the dtype is float32 or not.

**Comment by richardjgowers** [comment]
@palnabarun Hello! Yeah we've also got [a similar function for arrays](https://github.com/MDAnalysis/mdanalysis/blob/develop/package/MDAnalysis/lib/distances.py#L175), it just needs all connecting up and some tests adding to make sure that "bad" arrays are properly rejected

**Comment by palnabarun** [comment]
Oh. That's great. I somehow missed reading the function just after `_box_check`.

I am on it.
