### ISSUE TITLE
DCD Headers

### ISSUE THREAD

**Issue by tclick** [MDAnalysis/mdanalysis#1701]
### Expected behaviour
A CHARMM trajectory should be readable by CHARMM after writing with MDAnalysis.

### Actual behaviour
CHARMM fails to read the trajectory with the following error:

> At line 83 of file /home/tclick/backup/c41b1/build/gnu/title.F90 (unit = 10, file = '/home/tclick/research/pdz3/fluct/calpha/apo/data/150/cg.dcd')
> Fortran runtime error: I/O past end of record on unformatted file
> 

Previous versions of MDAnalysis correctly wrote the header, but as MDAnalysis transitions to Python 3, all strings are unicode including the remark keyword, which can be larger than ASCII. Therefore, the header is actually larger than CHARMM expects. This seems to occur also in Python 2 when using importing unicode_literals.

### Code to reproduce the behavior
``` python
import MDAnalysis as mda

u = mda.Universe(top, trj)
with mda.Writer('test.dcd') as w:
    for _ in u.trajectory:
        w.write(_)
....
```
Using a CHARMM input file that reads the trajectory:

charmm -i test.inp

### Currently version of MDAnalysis:
0.17.0-dev

#

**Comment by tylerjereddy** [comment]
I think the header is actually constrained to ASCII format (pretty sure @kain88-de & I agreed on this), but I do indeed remember having to make some tricky changes to the size of the remarks / comments section during the Python 3 migration.

Is this actually enough information for someone who doesn't use CHARMM to reproduce the issue? I think if I'm going to patch this I probably need to know exactly what is wrong and to have a unit test in MDAnalysis that currently fails for the expected behavior. Can you use the built in MDAnalysis DCD test file(s) to show that something has changed from what it should be when writing (i.e., REMARKS section is too large by X characters & needs to be constrained)?

**Comment by kain88-de** [comment]
So CHARMM could read DCD files written with MDAnalysis? I'm surprised since we write the DCD files formatted for NAMD. 

But for our test files the comments do match up again in the end. 



> This seems to occur also in Python 2 when using importing unicode_literals.

I do not understand this comment. Does this mean without the import everything works as expected in python 2?

**Comment by tclick** [comment]
@kain88-de , yes, that's what it means. In a previous version of some code that I had, I did not include the unicode_literals, and it worked fine. The DCD files may have been written for NAMD but they may not have been fully written in the way that limited them to NAMD. In a previous version of my own project, I was using MDAnalysis 0.10.0, and whenever I output the DCD trajectory, I would then read it using CHARMM c35 without any problems. 

I'll look at the test files and see what I can find.

**Comment by kain88-de** [comment]
Can you give us the remark string you are trying to write?

**Comment by tclick** [comment]
"Written by fluctmatch.", but I even tried this with the default (an empty string).

**Comment by orbeckst** [comment]
(FYI: There's a freely available version of CHARMM – it is easy to compile.)

**Comment by kain88-de** [comment]
@tylerjereddy might this be correlated with https://github.com/MDAnalysis/mdanalysis/pull/1155/files#r105538588 ? You increased the length of the allowed comment in our code here.

**Comment by tylerjereddy** [comment]
@kain88-de Yeah, that's what I was alluding to above. Since it didn't break a unit test I went with it. So, a unit test (or several) that enforces the required CHARMM behavior is needed. Probably a few examples of input / output strings that work for CHARMM, etc. We should also check (have tests) that the REMARKS section constraints for other DCD-reading software are supported / still supported after addressing this.

The need for someone to extensively & exhaustively look at the various DCD I/O issues across the heterogenous / poorly-defined format landscape was fairly clear during the migration, so this isn't really surprising.

**Comment by kain88-de** [comment]
@tclick would you be able to change the line in the dcd source I remarked above and check if that fixes your problem?

**Comment by tclick** [comment]
Okay. I'll get on that. Thanks.

**Comment by tclick** [comment]
I changed line 472 of readdcd.h from 240 to 80 and then did a 'pip install -U -e'. Unless I'm still overlooking something, it still fails with the same error:

> At line 83 of file /opt/local/charmm/c41b1/build/osx.cmake/title.F90 (unit = 10, file = '/users/tclick/multiphysics/research/pdz3/fluct/calpha/apo/data/1/test/cg.dcd')
> Fortran runtime error: I/O past end of record on unformatted file

I even tried adding a line from a previous version where you null-terminated the title but with no success. Looking into the CHARMM code, the maximum length for a title is 80. So, I could be incorrectly recompiling the code, or it is still possibly a unicode problem.

**Comment by kain88-de** [comment]
I usually don't use pip to recompile. I run `python setup.py build_ext --inplace`.  This will only rebuild the extensions. But I don't see why pip shouldn't work. 

Do you use a publicly available version of charm where we can look into the source code? It would be nice to see if this really happens when charm reads the remarks section or if we screw up somewhere else. I'm not sure how this should be a Unicode problem since we only write bytes, the remarks might be read as garbage should be the worst that happens. A missing null termination could really be a problem though.

**Comment by tclick** [comment]
We have the purchased copy of CHARMM, and so, I'm not sure that I can post the code here.

**Comment by kain88-de** [comment]
@tclick to clarify your original statement. When you run the current version of the development branch on python 2.7 and without including `unicode_literals` then any DCD written with MDAnalysis can be read by CHARMM?

@tylerjereddy Do you think we could write a test that checks if libdcd can write byte-perfect copies of a DCD file? This, of course, would only fix this issue under the assumption that CHARMM can read our DCD test file.

**Comment by tclick** [comment]
@kain88-de, my apologies for the delayed response. When I used MDAnalysis 0.10.0, it worked fine. However, I just tried using a DCD file (written from an XTC file) using Python 2.7 and MDAnalysis 0.17.0-dev. When I try using CHARMM c41b1, I still receive the same error; this is without importing the unicode_literals.

[md.zip](https://github.com/MDAnalysis/mdanalysis/files/1505721/md.zip)

**Comment by kain88-de** [comment]
The zip that you provided does it contain a dcd that works with CHARMM? My idea is that if I have a DCD that is known to work with CHARMM I can test if we can use `libdcd` (the new low level dcd library python wrapper we use) to write a bit by bit identical copy.

**Comment by tclick** [comment]
I have attached a copy of a working trajectory with the necessary input files to work. I have tested it with CHARMM c41b1, and it works as expected. The trajectory was created using MDAnalysis 0.10.0, and the other files were created with the latest version of my software. The files will work with >= c39 because of the change in how CHARMM works with RTF/PRM files. The coordinate file (.cor) can be renamed to .crd, but was labeled .cor for viewing with VMD (crd expects an AMBER coordinate file).

[working-dcd.zip](https://github.com/MDAnalysis/mdanalysis/files/1529388/working-dcd.zip)

**Comment by tclick** [comment]
I just tried MDAnalysis 0.17.0, and it seems that the comments section still goes over the CHARMM expected size. I was using the previously uploaded zip file, and received the following error from CHARMM after converting the DCD to XTC to DCD.

> At line 83 of file /opt/local/charmm/c41b1/build/osx.cmake/title.F90 (unit = 10, file = 'test.dcd')
> Fortran runtime error: I/O past end of record on unformatted file

I take it that this issue has not been solved yet?

**Comment by kain88-de** [comment]
I did some checks on my train ride in the morning. I might have a possible fix. Can you try out 

https://github.com/MDAnalysis/mdanalysis/pull/1767

I wrote myself a small tool to inspect the header of the dcd file. I noticed that the number of bytes we declare the header contains was inconsistent. The PR should hopefully fix that.  You can use the tool yourself. I assume that the claimed remarks size should follow this formula.

`size_remarks = nblocks * 80 + 4`

```python
import sys
import struct

def toint(b, order='little'):
    return int.from_bytes(b, byteorder=order)

def tofloat(b, order='little'):
    return struct.unpack('f', b)[0]
    #return float.from_bytes(b, byteorder=order)

print("usage: python dcdsniffer.py filename")

filename = sys.argv[1]
with open(filename, 'br') as fh:
    raw = fh.read()

print("Magic Number 84 = ", toint(raw[:4]))
print("CORD name = ", raw[4:8])
print("Nframes = ", toint(raw[8:12]))
print("istart = ", toint(raw[12:16]))
print("nsavc = ", toint(raw[16:20]))
print("? = ", toint(raw[20:24]))
print("? = ", toint(raw[24:28]))
print("? = ", toint(raw[28:32]))
print("? = ", toint(raw[32:36]))
print("? = ", toint(raw[36:40]))
print("? = ", toint(raw[40:44]))
print("? = ", tofloat(raw[44:48]))
print("with unitcell = ", toint(raw[48:52]))
for i in range(8):
    print("? = ", toint(raw[52+i*4: 52+(i+1)*4]))
print("charm version = ", toint(raw[84:88]))
print("need 84 here = ", toint(raw[88:92]))

# now we reached the remark section
remark_length = toint(raw[92:96])
print("remark length  = ", remark_length)
nblocks = toint(raw[96:100])
print("number of 80 char blocks = ", nblocks)
print("remark blocks")
for i in range(nblocks):
    print("  raw: ", raw[100 + 80*i:100 + 80*(i+1)])
    print("  decoded: ", str(raw[100 + 80*i:100 + 80*(i+1)], 'ascii', 'ignore'))
    print()
print("end remark blocks")
#print("remarks = ", raw[100:100+80*nblocks])

offset = nblocks*80 + 100
print("remark length again = ", toint(raw[offset: offset + 4]))
print("need a 4 = ", toint(raw[offset+4: offset+8]))
print("natoms = ", toint(raw[offset+8:offset+12]))
print("need a 4 =", toint(raw[offset+12:offset+16]))
```
