### ISSUE TITLE
AtomGroup.rotate is slow

### ISSUE THREAD

**Issue by mimischi** [MDAnalysis/mdanalysis#1707]
### Expected behaviour

Using `universe.atoms.rotate(rotation_matrix)` should be as fast as `np.dot(universe.atoms.postions, rotation_matrix)`.

### Actual behaviour

The `rotate` method is almost 7x slower than `np.dot`. In the test system it's almost unnoticeable (`70μs` vs `490μs`), but in my production system it's a difference of ~30 seconds (with `numpy`) and ~2m30s (with `MDAnalysis`).

### Code to reproduce the behaviour

See [this notebook](https://gist.github.com/mimischi/999cec383d821c3f9730b6e7b57ac9ce).

In my production system I first translate and then rotate my system. To isolate the exact problem, I've used all variations: rotate only, translate only and rotate+translate. Also I've done the tests on both single frames and while iterating over all frames.

### Currently version of MDAnalysis:
0.16.2

**Comment by richardjgowers** [comment]
One difference between the numpy and mda versions of things is MDA ensures that the positions it works on are all unique.  It would be interesting to see if commenting out the uniqueness check in MDA improves performance a lot for your large system

**Comment by kain88-de** [comment]
what position uniqueness check?

**Comment by richardjgowers** [comment]
@kain88-de unique atoms more than positions I guess https://github.com/MDAnalysis/mdanalysis/blob/develop/package/MDAnalysis/core/groups.py#L827

[this line](https://github.com/MDAnalysis/mdanalysis/blob/develop/package/MDAnalysis/core/groups.py#L826) looks needlessly slow too, no reason to go via `atoms.unique`, could just be `x = self.universe....`

**Comment by kain88-de** [comment]
I was wondering about the use of unique here anyway.
