### ISSUE TITLE
Regarding the orientation profile relation with spatial distribution 

### ISSUE THREAD

**Issue by cy16f01** [MDAnalysis/mdanalysis#1711]
Hello,
I am having a confusion between orientation and spatial distribution of water molecules.
Since the orientation profile gives that are the water molecules are oriented more towards N-terminal or towards the C-terminal of the amino acid glycine. And spatial distribution function (SDF) to gives the same idea hope so...
If so, can i calculate the SDF of water molecules around the N-terminal or towards the C-terminal of glycine in MDAnalysis.? and How to calculate the orientation of water molecules around the N-terminal or towards the C-terminal of glycine...??

Thank you

**Comment by orbeckst** [comment]
I pretty much agree with what the Gromacs folks asking you:
https://mailman-1.sys.kth.se/pipermail/gromacs.org_gmx-users/2017-November/117046.html

Clearly define what you want to calculate (i.e., the exact equations).

**Comment by orbeckst** [comment]
Without further input I don't know how to help.
