### ISSUE TITLE
MacOS builds failing

### ISSUE THREAD

**Issue by richardjgowers** [MDAnalysis/mdanalysis#1712]
Starting in #1704 some MacOS builds have started to fail.

Reducing the quantity of tests seems to "fix" the problem, so it might be related to some sort of limit.

Eg:
https://travis-ci.org/MDAnalysis/mdanalysis/jobs/303918794

**Comment by orbeckst** [comment]
Both MacOS builds are now failing during the normal system installation phase

      /Users/travis/.rvm/scripts/functions/support: line 57: shell_session_update: command not found

See, for instance, https://travis-ci.org/MDAnalysis/mdanalysis/jobs/312100713#L1947

**Comment by orbeckst** [comment]
Can we disable Mac OSX builds for the time being? Otherwise PR reviewing gets awkward when we have to ignore failing builds constantly.

**Comment by richardjgowers** [comment]
Yeah disabling is probably best for now.  I think the original error for
this issue isn't the error you've copied, so this issue is now 2 levels
deep of MacOS fixing :)

**Comment by kain88-de** [comment]
Travis recently updated their Xcode package. Maybe that is related because the error looks like it’s from ruby.

**Comment by orbeckst** [comment]
Quick googling: possibly related to travis-ci/travis-ci#6307

**Comment by orbeckst** [comment]
Perhaps a band-aid as in PR searchivarius/nmslib#259 would work for us, too?

**Comment by orbeckst** [comment]
PR #1730 fixes the build failure but two error remain.
