### ISSUE TITLE
Regarding Angular distribution Function analysis

### ISSUE THREAD

**Issue by cy16f01** [MDAnalysis/mdanalysis#1719]
Hello,
I have a .gro file containing glycine+water (1 glycine,100 water molecules)mixture. Now i need to calculate the Angular distribution function of the water around the first hydration shell of N-terminal (NH3+) and the distance which is 0.35 nm (the value is taken from the RDF 1st minima). 
The .gro file is:-
```
    1GLY      N    1   1.273   1.239   1.343
    1GLY     H1    2   1.239   1.214   1.436
    1GLY     H2    3   1.373   1.205   1.339
    1GLY     H3    4   1.223   1.196   1.266
    1GLY     CA    5   1.296   1.388   1.327
    1GLY    HA1    6   1.243   1.437   1.409
    1GLY    HA2    7   1.255   1.416   1.230
    1GLY      C    8   1.448   1.416   1.332
    1GLY    OT1    9   1.485   1.536   1.329
    1GLY    OT2   10   1.512   1.306   1.340
    2SOL     OW 1035   0.225   0.275   0.996
   2SOL    HW1 1036   0.260   0.258   1.088
   2SOL    HW2 1037   0.137   0.230   0.984
   3SOL     OW 1038   1.755   0.607   0.231
   3SOL    HW1 1039   1.743   0.594   0.132
   3SOL    HW2 1040   1.725   0.526   0.280
   4SOL     OW 1041   0.850   0.798   1.823
   4SOL    HW1 1042   0.846   0.874   1.888
   4SOL    HW2 1043   0.872   0.834   1.732
   5SOL     OW 1044   0.685   1.012   0.665
   5SOL    HW1 1045   0.754   0.996   0.735
   5SOL    HW2 1046   0.612   1.069   0.703
   6SOL     OW 1047   1.603   0.447   0.737
   6SOL    HW1 1048   1.529   0.493   0.687
   6SOL    HW2 1049   1.654   0.515   0.790
   7SOL     OW 1050   0.231   1.713   0.483
   7SOL    HW1 1051   0.265   1.790   0.537
   7SOL    HW2 1052   0.275   1.713   0.393
   8SOL     OW 1053   1.127   1.341   1.690
   8SOL    HW1 1054   1.174   1.341   1.778
   8SOL    HW2 1055   1.079   1.254   1.679
.
.
.
```
And the code that i have tried is -
```python
import MDAnalysis
from MDAnalysis.analysis.waterdynamics import AngularDistribution as AD
from matplotlib import pyplot as plt

u = MDAnalysis.Universe('glywat.gro', 'nptmd.trr')
selection = "byres name OW and sphzone 3.5 (protein and (resid 42 or resid 26) )"
bins = 30
AD_analysis = AD(u,selection,bins)
AD_analysis.run()
#now we print data ready to graph. The first two columns are P(cos(theta)) vs cos(theta) for OH vector ,
#the seconds two columns are P(cos(theta)) vs cos(theta) for HH vector and thirds two columns
#are P(cos(theta)) vs cos(theta) for dipole vector
#for bin in range(bins):
      #print("{AD_analysisOH} {AD_analysisHH} 
  #{AD_analysisDip}".format(AD_analysis.graph0=AD_analysis.graph[0][bin], #AD_analysis.graph1=AD_analysis.graph[1][bin],AD_analysis.graph2=AD_analysis.graph[2][bin]))

#and if we want to graph our results
plt.figure(1,figsize=(18, 6))

#AD OH
plt.subplot(131)
plt.xlabel('cos theta')
plt.ylabel('P(cos theta)')
plt.title('PDF cos theta for OH')
plt.plot([float(column.split()[0]) for column in AD_analysis.graph[0][:-1]],[float(column.split()[1]) for column in AD_analysis.graph[0][:-1]])

#AD HH
plt.subplot(132)
plt.xlabel('cos theta')
plt.ylabel('P(cos theta)')
plt.title('PDF cos theta for HH')
plt.plot([float(column.split()[0]) for column in AD_analysis.graph[1][:-1]],[float(column.split()[1]) for column in AD_analysis.graph[1][:-1]])

#AD dip
plt.subplot(133)
plt.xlabel('cos theta')
plt.ylabel('P(cos theta)')
plt.title('PDF cos theta for dipole')
plt.plot([float(column.split()[0]) for column in AD_analysis.graph[2][:-1]],[float(column.split()[1]) for column in AD_analysis.graph[2][:-1]])

plt.show()
```

But i am not getting any output...

Any suggestions are highly appreciated

**Comment by orbeckst** [comment]
Do you mean by
> But i am not getting any output...

that you don't see a graph?

Are you able to just see a simple matplotlib plot? Or at least write it to file:

```python
import numpy as np
from matplotlib import pyplot as plt

X = np.linspace(-5, 5, 100)
plt.plot(X, np.sin(X)) 
plt.savefig("sin.png")
```
![sin](https://user-images.githubusercontent.com/237980/33519949-73783690-d76e-11e7-9310-470e1f5b9dfd.png)

If you cannot see the graphics window then you probably need to [set your matplotlib backend](http://matplotlib.org/faq/usage_faq.html#what-is-a-backend). You can also use a jupyter notebook and use the `%matplotlib inline` command to show figures inside the notebook or start  `ipython -pylab=<BACKEND>` (see `ipython -h` for options).

**Comment by cy16f01** [comment]
Hello,
Suppose i want to calculate all the water molecules-OW (say around 200 water molecules i have my .gro file.) around atom N from glycine, then what are the changes that i need to do..?? with reference of the above .gro file mentioned...
I tried to change the following line:-
selection = "byres name N and sphzone 0.35 (resid 11 to resid 200)" 
but i got errors as:-
SelectionError: Selection failed: 'Failed to parse value: to'

So how do i overcome this error...??

**Comment by orbeckst** [comment]
resid 11-200

**Comment by cy16f01** [comment]
Suppose i want to calculate the orientation profile ie., cos theta v/s Pcos theta of NH3+ of glycine around 1st solvation shell (taken from rdf and it is 0.35 nm) w.r.t water (ie., water molecules surrounded around NH3+ of glycine throughout the simulation).
Here is the code:-
import MDAnalysis
from MDAnalysis.analysis.waterdynamics import AngularDistribution as AD
from matplotlib import pyplot as plt

u = MDAnalysis.Universe('nptmd.tpr', 'nptmd.trr')
selection = "byres name OW and sphzone 0.35 (resid 42 or resid 26)"
bins = 100
AD_analysis = AD(u,selection,bins)
AD_analysis.run()
#now we print data ready to graph. The first two columns are P(cos(theta)) vs cos(theta) for OH vector ,
#the seconds two columns are P(cos(theta)) vs cos(theta) for HH vector and thirds two columns
#are P(cos(theta)) vs cos(theta) for dipole vector
for bin in range(bins):
      
    print("{AD_analysisOH} {AD_analysisHH} {AD_analysisDip}".format(AD_analysisOH=AD_analysis.graph[0][bin],AD_analysisHH=AD_analysis.graph[1][bin], AD_analysisDip=AD_analysis.graph[2][bin]))

#and if we want to graph our results
plt.figure(1,figsize=(18, 6))

#AD OH
plt.subplot(131)
plt.xlabel('cos theta')
plt.ylabel('P(cos theta)')
plt.title('PDF cos theta for OH')
plt.plot([float(column.split()[0]) for column in AD_analysis.graph[0][:-1]],[float(column.split()[1]) for column in AD_analysis.graph[0][:-1]])

#AD HH
plt.subplot(132)
plt.xlabel('cos theta')
plt.ylabel('P(cos theta)')
plt.title('PDF cos theta for HH')
plt.plot([float(column.split()[0]) for column in AD_analysis.graph[1][:-1]],[float(column.split()[1]) for column in AD_analysis.graph[1][:-1]])

#AD dip
plt.subplot(133)
plt.xlabel('cos theta')
plt.ylabel('P(cos theta)')
plt.title('PDF cos theta for dipole')
plt.plot([float(column.split()[0]) for column in AD_analysis.graph[2][:-1]],[float(column.split()[1]) for column in AD_analysis.graph[2][:-1]])

plt.show()

and the plots are as follows,
![download](https://user-images.githubusercontent.com/30516979/33802625-02b917ec-dda1-11e7-81bf-5e3bcf91225a.png)
Any suggestions on these are highly appreciated...

**Comment by orbeckst** [comment]
I see that you followed the [AngularDistribution example](https://www.mdanalysis.org/docs/documentation_pages/analysis/waterdynamics.html#angulardistribution). It looks to me that you have to few frames in your trajectory for your bin size because your histograms/PDFs are very jagged. I'd reduce `bins` or sample more. 

If these are the data that you need to answer your scientific questions is for you to decide.

**Comment by cy16f01** [comment]
Yes, I am following ADF's example.
If i say want to calculate now between C-terminal(or any atoms) and water, and the code is 
selection = ('byres (name HW* and sphzone 2.4 name OT*)') 
Here i am calculating for Oxygen of carbonyl group w.r.t hydrogen of water, or any other case as such... then i am getting a graph (download1.png) like the below attached, which in all case has a peak around 90 degrees, irrespective of the atoms in considerations...
So, what could be the error..??
and the graphs should be like the images shown below (screenshots) from the following literature, but my graphs are entirely not matching at all...
![screenshot from 2017-12-11 00 59 45](https://user-images.githubusercontent.com/30516979/33808560-d5a9e8c6-de0e-11e7-84fc-cffc7e6be3fe.png)
![screenshot from 2017-12-10 12 12 06](https://user-images.githubusercontent.com/30516979/33808561-d5e9b910-de0e-11e7-86d3-5ff5163dc4ad.png)


 
![download1](https://user-images.githubusercontent.com/30516979/33808536-466ddf14-de0e-11e7-84f1-3bda9de6e43d.png)

**Comment by orbeckst** [comment]
> I have ran the simulation for 10ns in GROMACS, and have 20001 frames, hope this is decent time period.

You'll have to demonstrate that your results are converged. "Hope" is not enough. You'll have to demonstrate it by showing appropriate analysis.

Regarding the shape of your graphs: I have no idea, I would calculate these distributions for a case where I know the answer. That's my standard approach to any code we use in my lab. 

You have to understand that we're happy to help but that we all do this here in our free time (nobody gets paid to answer questions or fix bugs!) – and we all have many more important things to do. We make the code and everything else available in the hope that it will be useful. We think it is useful because the authors have been using MDAnalysis in their own work (see citations for WaterAnalysis!) and they have been making efforts to make it accessible to other people like you. But please understand that there's only a very finite amount of time available to discuss user problems in depth. The questions that you're asking are too broad. We can act on focused questions, for instance "there's a bug in MDAnalysis because ...". However, we mostly ignore questions that sound like "mentor me in analyzing these data". I am sorry, we cannot do this, this is the job of your academic advisor (or yourself, if you're an independent academic).

In the future, please ask focused questions such as "why does the output from AngularDistribution for the PDF of the OH of SPC bulk water differ from the published PDF in (citation)?" Please show that you made an effort (such as using the example code!)

----
@alejob @cyanezstange from looking at the output, do you think that there's a bug in your code or that @cy16f01 has made an obvious mistake? A short answer is sufficient, and if the answer is "no" please close the issue. Thanks!

**Comment by cy16f01** [comment]
Thank you for your suggestions...
A few doubts...
What does it mean "results are converged". I have no idea regarding this...
How do i know that the results are converged..??
I have plotted the RDF's and these are matching well with the previous literature. So any insights upon this are appreciated.

Thank you.

**Comment by kain88-de** [comment]
> What does it mean "results are converged". I have no idea regarding this...
> How do i know that the results are converged..??

Determining what converged means for your simulations is your job as a researcher to find out.  There is a lot of literature available online that talks about convergence in simulations. I suggest you talk to your supervisor about this. We cannot help in this regard.

> I have plotted the RDF's and these are matching well with the previous literature. So any insights upon this are appreciated.

Again this should be discussed with your supervisor. We can only help you with using MDAnalysis not interpreting the results. 

I'm closing this as there doesn't seem to be a problem with MDAnalysis but only questions about the scientific interpretation of results, which we cannot answer here.

**Comment by cy16f01** [comment]
i have questions regarding the MDAnalysis code too...
As i have posted the output of my graph and the what previous literature says...
The output from AngularDistribution for the PDF of the OH of SPC bulk water differ from the published PDF in (citation).
1] How to know the orientation w.r.t the 1st hydration shell as @orbeckst  said, "output from AngularDistribution for the PDF of the OH of SPC bulk water differ......" then if the code is giving the output for the bulk, 
2] I think it should be calculating the orientation within the 3.5 angstrom (which corresponds to the 1st minima from RDF.)
3] Is it calculating the angle between dipole of water and nitrogen of glycine within the distance of 3.5 angstroms.  
the code that i have run is as follows:-
import MDAnalysis
from MDAnalysis.analysis.waterdynamics import AngularDistribution as AD
from matplotlib import pyplot as plt

u = MDAnalysis.Universe('nptmd.tpr', 'nptmd.trr')
selection = ('byres (name OW and sphzone 3.5 name N)')
bins = 100
AD_analysis = AD(u,selection,bins)
AD_analysis.run()
#now we print data ready to graph. The first two columns are P(cos(theta)) vs cos(theta) for OH vector ,
#the seconds two columns are P(cos(theta)) vs cos(theta) for HH vector and thirds two columns
#are P(cos(theta)) vs cos(theta) for dipole vector
for bin in range(bins):
      
    print("{AD_analysisOH} {AD_analysisHH}{AD_analysisDip}".format(AD_analysisOH=AD_analysis.graph[0][bin],AD_analysisHH=AD_analysis.graph[1][bin], AD_analysisDip=AD_analysis.graph[2][bin]))

#and if we want to graph our results
plt.figure(1,figsize=(18, 6))

#AD OH
plt.subplot(131)
plt.xlabel('cos theta')
plt.ylabel('P(cos theta)')
plt.title('PDF cos theta for OH')
plt.plot([float(column.split()[0]) for column in AD_analysis.graph[0][:-1]],[float(column.split()[1]) for column in AD_analysis.graph[0][:-1]])

#AD HH
plt.subplot(132)
plt.xlabel('cos theta')
plt.ylabel('P(cos theta)')
plt.title('PDF cos theta for HH')
plt.plot([float(column.split()[0]) for column in AD_analysis.graph[1][:-1]],[float(column.split()[1]) for column in AD_analysis.graph[1][:-1]])

#AD dip
plt.subplot(133)
plt.xlabel('cos theta')
plt.ylabel('P(cos theta)')
plt.title('PDF cos theta for dipole')
plt.plot([float(column.split()[0]) for column in AD_analysis.graph[2][:-1]],[float(column.split()[1]) for column in AD_analysis.graph[2][:-1]])

plt.show()

**Comment by alejob** [comment]
There is not bug, you should change, as @orbeckst the width of your bin, or sample more. Remember that the PDF is an histogram, so, too few data will result in a very jagged plot.
