### ISSUE TITLE
problem with u.transfer_to_memory

### ISSUE THREAD

**Issue by mkhoshle** [MDAnalysis/mdanalysis#1723]
Hi, I am working on the following example:
```python
import numpy as np
import MDAnalysis as mda
import os

DCD1 = os.path.abspath(os.path.normpath(os.path.join(os.getcwd(),'files/1ake_007-nowater-core-dt240ps.dcd')))
PSF = os.path.abspath(os.path.normpath(os.path.join(os.getcwd(),'files/adk4AKE.psf')))
longXTC = os.path.abspath(os.path.normpath(os.path.join(os.getcwd(),'files/newtraj.xtc')))
# LongXTC is created from dcd file and is 600X the trajectory lenghth in dcd file

u = mda.Universe(PSF, longXTC)
print(len(u.trajectory)) # 2512200 frames

mobile = u.select_atoms("(resid 1:29 or resid 60:121 or resid 160:214) and name CA")

# Assuming I have 8 processes and one process will access 2512200/8 ~ 314025 frames
start = 0
step = 1
stop = 314025

# 1st approach
u.transfer_to_memory(start=start,stop=stop,step=step)  #fails due to memory error

# 2nd approach
pos = []
for iframe, ts in enumerate(u.trajectory[start:stop:step]):
      pos.append(mobile.positions) #this method works
```
### Expected behaviour
If there is memory limit issue, I expect that both approaches fail.  

### Actual behaviour
However, the 2nd approach works but the first one using transfer_to_memory fails.

### Code to reproduce the behaviour
Refer to above code

### Currently version of MDAnalysis:
`0.16.2`

**Comment by orbeckst** [comment]
1. What's the memory of the machine?
2. What is the expected size of the array (shape and memory)?
3. What does `np.array(pos).shape` show? 

By the way, to make it a fair comparison, you shouldn't be using `mobile` as a subselection but instead use all `u.atoms`. `len(mobile) < len(u.atoms)` and `transfer_to_universe()` transfers all atoms, not just a subselection. (The latter is possible, though, see [Creating an in-memory trajectory of a sub-system](https://www.mdanalysis.org/docs/documentation_pages/coordinates/memory.html?highlight=memoryreader#creating-an-in-memory-trajectory-of-a-sub-system).)

**Comment by richardjgowers** [comment]
So the code for `transfer_to_memory` is here (afaik only DCD and MemoryReader have implemented `.timeseries`): https://github.com/MDAnalysis/mdanalysis/blob/develop/package/MDAnalysis/core/universe.py#L510

Which is nearly identical to your "2nd approach"

I suspect it might be what @orbeckst has mentioned.  What size is `mobile` relative to `u.atoms`?

**Comment by mkhoshle** [comment]
@orbeckst @richardjgowers  Thanks.
1. It is 62 GB. However in the loging the free memory is only about 2 GB (Based on what I get using free -g).
2. Size of array will be 314025*3*3341 which will be 314025*3*3341*8~23 GB.
3. it is (314025, 146, 3) and is about 314025*3*146*8~1 GB.

Yes, that makes sense to me. `len(mobile) < len(u.atoms)` and I need to an in-memory trajectory of a sub-system!

**Comment by mkhoshle** [comment]
I was able to get my code to work by creating an in-memory trajectory of a sub-system. So I close this issue!
