### ISSUE TITLE
problem loading OpenDx files generated from density_from_Universe() in pymol

### ISSUE THREAD

**Issue by KyleStiers** [MDAnalysis/mdanalysis#1725]
### Expected behaviour
``` python
D = density_from_Universe(u, delta=1.0, atomselection="name OW")
D.convert_density('TIP3P')
D.export("density.dx")
```
'open density.dx in pymol'

``` python
isomesh test, density, 2.0, carve=1.5
```

### Actual behaviour
No errors thrown when density.dx loaded in pymol, but no isomesh is produced from the above command.

If you edit line 23 of the density.dx from 
``` python
object 3 class array type float rank 0 items 9472320 data follows
```
to
``` python
object 3 class array type double rank 0 items 9472320 data follows
```
and then run the command
``` python
isomesh test, density, 2.0, carve=1.5
```
the isomesh map shows up and everything is fine.

**Comment by orbeckst** [comment]
Can you try out if the DX file with `double` is still readable in VMD and Chimera?

The [DX file I/O](http://griddataformats.readthedocs.io/en/latest/gridData/formats/OpenDX.html) is fairly rudimentary and when I wrote it, I only checked that it worked for my immediate purposes; I thought it had worked for pymol, too, but I don't remember. The `float` type is the [default type for the DX array object](https://web.archive.org/web/20080808140524/http://opendx.sdsc.edu/docs/html/pages/usrgu068.htm#Header_440) so I chose it for the output type.

Is it possible that this is a bug in pymol?

**Comment by KyleStiers** [comment]
It works in VMD still, but I can't tell in Chimera. I only see DX loading in Chimera for APBS maps and it seems like it only colors surface. It definitely loaded the file, but unclear whether it actually works as expected.

It's equally likely this is a pymol bug. May be best just to put a note in the documentation so that people know.

**Comment by orbeckst** [comment]
We could add an option to the writer to set the output number format. We could set it to `double` if this increases interoperability; purists could then set it back to `float`. 

If I find time I try in Chimera.

**Comment by orbeckst** [comment]
Ok, that is embarassing: This was a known issue already MDAnalysis/GridDataFormats#35 and I completely dropped the ball on it.

**Comment by KyleStiers** [comment]
Ah, sorry I should've found this as well. I tried to look through all the references to the DX file creation and problems in PyMOL but clearly missed this one.
