### ISSUE TITLE
improve documentation of density_from_Universe() 

### ISSUE THREAD

**Issue by KyleStiers** [MDAnalysis/mdanalysis#1726]
In the documentation for density_from_Universe() it states: 

An input trajectory must

1. have been centered on the protein of interest;
2. have all molecules made whole that have been broken across periodic boundaries;
3. have the solvent molecules remapped so that they are closest to the solute (this is important when using funky unit cells such as a dodecahedron or a truncated octahedron).

In gromacs I've used trjconv to correct my dodecahedron cell for PBC,rotation, and translation, is this what is described as 'remapping'? If not could someone elaborate and update the documentation to reflect a bit more clearly on what is entailed in the remapping?

Thanks!

**Comment by orbeckst** [comment]
Yes, `gmx trjconv -pbc mol -center -ur` and then `gmx trjconv -fit` is exactly what is meant by this statement.

**Comment by KyleStiers** [comment]
Great! Thanks. I'd recommend a quick mention of that in the documentation just for to clarify for people.

**Comment by orbeckst** [comment]
Update docs

**Comment by orbeckst** [comment]
See also #1175
