### ISSUE TITLE
Building docs from the source

### ISSUE THREAD

**Issue by xiki-tempula** [MDAnalysis/mdanalysis#1737]
I'm currently writing the doc for a module and is interested to test if all the formatting are being built correctly.

As advised in the wiki (https://github.com/MDAnalysis/mdanalysis/wiki/WritingDocumentation), I ran `python setup.py build_sphinx -E` to generate the HTML file.

However, I have encountered the following error.
```
...
[9/9] Cythonizing MDAnalysis/lib/qcprot.pyx
/Users/***/anaconda3/envs/mda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/setuptools/dist.py:331: UserWarning: Normalizing '0.17.0-dev' to '0.17.0.dev0'
running build_sphinx
creating /Users/***/GitHub/mdanalysis/package/doc/html
creating /Users/***/GitHub/mdanalysis/package/doc/html/doctrees
creating /Users/***/GitHub/mdanalysis/package/doc/html/html
Running Sphinx v1.6.5

Exception occurred:
  File "/Users/***/GitHub/mdanalysis/package/MDAnalysis/lib/formats/__init__.py", line 24, in <module>
    from . import libdcd
ImportError: cannot import name 'libdcd'
The full traceback has been saved in /var/folders/78/l36vr2_j5l1gg2btxzknnw5h0000gn/T/sphinx-err-ze_rq6jn.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```

I have tried to run `sphinx-build -b html source build` but have encountered the same error. 
Can I have some help regarding how to build the docs, please? Thank you.
Version: py36; OSX10.13.1; mda0.17.0

**Comment by richardjgowers** [comment]
@xiki-tempula how have you installed MDAnalysis?  I think you need to build inplace/developer build so that sphinx sees the extension modules.  Try installing with `pip install -e .` and then building the docs

**Comment by xiki-tempula** [comment]
@richardjgowers Thank you. This has solved my problem. When I opened a new branch to write water bridge analysis, I installed by executing `python setup.py install` as is adviced in (https://github.com/MDAnalysis/mdanalysis/wiki/DevelopmentBranch). 
I was sort of wondering why changing the source code doesn't work as it used to be.

**Comment by kain88-de** [comment]
Well we do write about `python setup.py develop` in a remark on that wiki page (it does the same as the pip command @richardjgowers mentioned). Should be more prominently suggest using a develop installation on the wiki?

**Comment by xiki-tempula** [comment]
@kain88-de I guess `python setup.py develop` install the src to the site-package in the env without touching the src. `pip install -e .` changes the src directly.

**Comment by kain88-de** [comment]
nope develop does touch the source. It will actually only install a package link. I can't imagine that pip does things differently.
