### ISSUE TITLE
consistently indicate absence of box information `Timestep.dimensions`

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/mdanalysis#1738]
### Expected behaviour
When a trajectory does not contain a unit cell, then `u.trajectory.ts.dimensions` should have one value that always indicates the absence of box information, for example `None` or `[0, 0, 0, 0, 0, 0]`

### Actual behaviour
Readers decide for themselves how they handle missing box information. For example:
* XYZReader: `array([ 0., 0., 0., 0., 0., 0.], dtype=float32)`
* DCDReader: `array([  0.,   0.,   0.,  90.,  90.,  90.], dtype=float32)`

See discussion https://github.com/MDAnalysis/mdanalysis/pull/1733#issuecomment-351234725

### Code to reproduce the behaviour

``` python
import MDAnalysis as mda
from MDAnalysis.tests.datafiles import XYZ, PSF, DCD

xyz = mda.Universe(XYZ)
print(xyz.trajectory.ts.dimensions)

dcd = mda.Universe(PSF, DCD)
print(dcd.trajectory.ts.dimensions)
```

### Currently version of MDAnalysis:
(run `python -c "import MDAnalysis as mda; print(mda.__version__)"`)

0.17.0-dev

**Comment by orbeckst** [comment]
Having `dimensions = None` will require quite a bit of extra work in the readers (e.g., when converting units). I'd probably just go with `[0, 0, 0, 0, 0, 0]` because that's already the default coming from `base.Timestep`. Then we only need to look at the readers that rely on specialized code.

**Comment by richardjgowers** [comment]
I'd rather have None. Most (all?) "box=" keywords use None to signify no pbc, so if we used None then we could blindly pass dimensions. 

That said, there's also the issue of dealing with periodicity in only a few dimensions (eg bilayer you don't want pbc normal to lipid plane). If we did allow length=0 to mean no pbc, then semi periodic is a lot easier to deal with. 

So maybe we should allow length=0

**Comment by jmborr** [comment]
@orbeckst Can you also write a utility function that will return `False` if the system is non-periodic in order to hide the particular definition of non-periodic `dimensions` that you will settle for?

**Comment by orbeckst** [comment]
We could add a has_pbc or is_periodic attribute to Timestep. But as @richardjgowers pointed out, what do you do with semi periodic systems? 

Having 0 lengths for non-periodic dimensions seems the cleanest approach to me. 

Maybe a function that returns the dimensions (axes) along a box is periodic, and then you can check for no pbc i.e. [] or 1d e.g. [0], 2D e.g. [1,2], 3D [0,1,2] periodicity by asking how many axes you got back. 

--
Oliver Beckstein
email: orbeckst@gmail.com

**Comment by orbeckst** [comment]
Ok, reading the dumb things that I said 3 years ago and the wise things that @richardjgowers said all along, I am now in favor of `None`.
