### ISSUE TITLE
ImportError: cannot import name _remove_dead_weakref

### ISSUE THREAD

**Issue by lcebaman** [MDAnalysis/mdanalysis#1739]
We get the following error importing mdanalysis. Has anyone seen this before?

### Code to reproduce the behaviour

``` python
~> import MDAnalysis
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/work/z01/z01/user/mdtestwork/lib/python2.7/site-packages/MDAnalysis/__init__.py", line 149, in <module>
    import logging
  File "/work/z01/z01/user/mdtestwork/lib/python2.7/logging/__init__.py", line 26, in <module>
    import sys, os, time, cStringIO, traceback, warnings, weakref, collections
  File "/work/z01/z01/aproeme/mdtestwork/lib/python2.7/weakref.py", line 14, in <module>
    from _weakref import (
ImportError: cannot import name _remove_dead_weakref

....

```
We have the latest version of MDAnalysis installed with Conda.

**Comment by richardjgowers** [comment]
Hi

That looks like it's actually coming from `weakref` not importing correctly which is odd as it's standard library.  Does `import weakref` alone work?

**Comment by lcebaman** [comment]
Yes, that seems to be the case
```
python
lcebaman@mom1:~/work>aprun -n 1 python -c "import weakref"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/work/z01/z01/lcebaman/myenv/lib/python2.7/weakref.py", line 14, in <module>
    from _weakref import (
ImportError: cannot import name _remove_dead_weakref
```

**Comment by kain88-de** [comment]
I don't really have any idea about  that. Seems like something has messed up your python installation. I would check logs for anything that changed the python installation.

**Comment by orbeckst** [comment]
Similar (unsolved) question https://askubuntu.com/questions/981663/python2-7-broken-by-weakref-import-error-please-help implying that an update from Ubuntu 16.04 to 17.10 broke the Python 2.7 installation.

You are saying that you're using conda, though, so this might not be confined to Ubuntu.

Perhaps worthwhile showing all your version information (Python, conda, etc).

**Comment by orbeckst** [comment]
[Debian Bug report logs - #852163: python3.5-minimal wont configure](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=852163) demonstrates that this error (for Python 3.5 and Python 3.6) is due to another incompatible installation of Python in `/usr/local`. 

I suggest you tightly control your Python installations and only have the system python and then a conda or virtual env/pip installation.

**Comment by orbeckst** [comment]
@lcebaman have you made any progress on this issue? We will close it if we don't hear back from you in a day.

**Comment by orbeckst** [comment]
No more comments, closing.

**Comment by Pierre-Sassoulas** [comment]
See https://askubuntu.com/questions/981663/ for solution.

**Comment by orbeckst** [comment]
Thanks for the update, should be helpful for anyone else running into this issue.

**Comment by caot** [comment]
python=2.7.14 fixed the mentioned issue for me. python=2.7.13 or lower version had such an issue.

**Comment by woodenchild** [comment]
@caot @orbeckst  Hi, I can run "import weakref" in python. But when I run in another file it causes a set of error with "ImportError: cannot import name _remove_dead_weakref". How to fix this?

**Comment by orbeckst** [comment]
> But when I run in another file ...

- How do you run the other file? 
- Are you sure that it uses the same Python interpreter? (Add a `import sys; print sys.version` to your file and compare to what you expect.)
- Do you have another python installation (e.g. in `/usr/local` or in your home directory or conda)?
- Do you see this error when using MDAnalysis?

**Comment by caot** [comment]
@woodenchild you should post your trace stack.

**Comment by caot** [comment]
what's the python version?
if it's 2.7, then update it to python=2.7.14

**Comment by NguyenAnhTien** [comment]
please export LD_LIBRARY_PATH to the place the lib directory of your python.
Example: your python is in /data/python-2.7.14
you should export LD_LIBRARY_PATH=/data/python-2.7.14/lib:$LD_LIBRARY_PATH

**Comment by rohit1809996** [comment]
i am also facing the same issue but my problem still not resolved i have tried all the possible solution present on internet, actually i am restoring an website running backup on my local host using plone , and i am stucked at this particular issue ..... please help me out

**Comment by hmacdope** [comment]
Hi @rohit1809996, is your question directly related to MDAnalysis? If so happy to help, but otherwise your question is best directed elsewhere. 👍

**Comment by rohit1809996** [comment]
@hmacdope no actually I was trying to run a plone backup ,and I have solved this issue as I was using different versions of linux not the same as older system where the backup was created..
