### ISSUE TITLE
Possible memory issue regarding hydrogen bond analysis

### ISSUE THREAD

**Issue by xiki-tempula** [MDAnalysis/mdanalysis#1742]
I have a couple of trajectories which I would like to perform hydrogen bond analysis on and save the result to disk.
The code which I used to execute these operations are:

```python
import pickle
import MDAnalysis as mda
from MDAnalysis.analysis.hbonds.hbond_analysis import HydrogenBondAnalysis
for i in range(100):
    u = mda.Universe('topology', 'trajectory')
    h = HydrogenBondAnalysis(u)
    h.run()
    pickle.dump(h._timeseries, open('h_().p'.format(i), 'wb'))
```

### Expected behaviour
I expect the script to go through all the trajectories and spit out the result.
Each trajectory is 340 MB and each _timeseries object is 110MB.

### Actual behaviour
However, I noticed that after 15 trajectories are computed, the python interpreter gives memory error and quit.
I can restart the script starting from the trajectory where memory error occurs and it will run fine for another 14 trajectories before the memory error is issued again.
I would imagine at each iteration, the u tag is taken off from the previous universe and put on the next universe. The previous universe is then cleaned by python GC. However, judging from this behaviour, it seems that all the universe that I have accessed still remain in the memory.

### Currently version of MDAnalysis:
mda17.0, py36

**Comment by orbeckst** [comment]
We have a hack to make AtomGroup pickling work whereby universes keep a [weakref](https://docs.python.org/3.5/library/weakref.html) in `MDAnalysis._ANCHOR_UNIVERSES`. In principle, they should be garbage-collected, though.

Did you try to add 
```python
import gc

...

    pickle.dump(h._timeseries, open('h_().p'.format(i), 'wb'))
    del h
    del u
    gc.collect()
```
inside the loop?

**Comment by xiki-tempula** [comment]
@orbeckst Thank you for the help. It seems that this has solved the problem. However, I'm a bit curious of why this isn't the default behavior.

**Comment by kain88-de** [comment]
we keep the weakref around to enable pickling of atomgroups. This is essential to allow the use multiprocessing with MDAnalysis.

**Comment by orbeckst** [comment]
I don't think that weakref/anchoring has anything to do with your problem---perhaps I should not have mentioned it and just talked about gc. Python's garbage collector can run whenever it wants to (meaning: I don't know the schedule or heuristics that it uses but I know it does not necessarily run during each iteration of your loop so it is entirely normal to not deallocate memory right away and you might have to help Python by running go.collect()).

**Comment by xiki-tempula** [comment]
@orbeckst Sorry for the previous comment. After extensive testing, I noticed that removing the hydrogenbondanalysis and the universe didn't solve the problem.
I'm able to identify the exact location where memory leak happens and can produce a test file which reproduces the problem. Here is the code.
```
import gc
import MDAnalysis as mda
from MDAnalysis.tests.datafiles import PSF, DCD

for i in range(1000):
    print(i)
    u = mda.Universe(PSF, DCD)
    for ts in u.trajectory:
        print('frame')
        for atom in u.atoms:
            selection = atom.residue.atoms.select_atoms(
                "(name H* 1H* 2H* 3H* or type H) and around {0:f} name {1!s}"
                "".format(1.5, atom.name))
            del selection
```
By running this piece of code, the memory usage will continues to increase until python kill itself.
Adding gc.collect() after `del selection` seems to solve the problem but decrease the speed of iteration by at least 10 times.
I have tried
```
for i in range(1000):
    print(i)
    u = mda.Universe(PSF, DCD)
    for ts in u.trajectory:
        print('frame')
        for atom in u.atoms:
            selection = atom.residue.atoms.select_atoms(
                "(name H* 1H* 2H* 3H* or type H) and around {0:f} name {1!s}"
                "".format(1.5, atom.name))
            del selection
        gc.collect()
```
and 
```
for i in range(1000):
    print(i)
    u = mda.Universe(PSF, DCD)
    for ts in u.trajectory:
        print('frame')
        for atom in u.atoms:
            selection = atom.residue.atoms.select_atoms(
                "(name H* 1H* 2H* 3H* or type H) and around {0:f} name {1!s}"
                "".format(1.5, atom.name))
            del selection
    gc.collect()
```
but neither of them seems to be working.
