### ISSUE TITLE
Allow PDBWriter (and similar) to write record_types

### ISSUE THREAD

**Issue by xiki-tempula** [MDAnalysis/mdanalysis#1753]
(@richardjgowers edit:) Following #1762 we now read the record type (ATOM/HETATM)  of each atom.  Now we need to make the PDBWriter (and PQR/PDBQT) write these records when found, otherwise defaulting to a sensible value.

Original Issue:

I have a gro file which contains a ligand and I want to write it out as a pdb file. In the new pdb file can the ligand has a Record type of HETATOM instead of ATOM?

Like
```
import MDAnalysis as mda
u = mda.Universe(grofile)
u.atoms.recordtype = 'HETATOM'
u.atoms.write('ligand.pdb')
```

**Comment by kain88-de** [comment]
Our PDB writer currently doesn't support writing `HETATM` records. I'm not sure we track this information in the topology either.

**Comment by xiki-tempula** [comment]
@kain88-de It seems not.
I have loaded a PDB file where the record type is HETATOM and write it into another pdb. It seems that the HETATOM information is lost.
```
import MDAnalysis as mda
u = mda.Universe('old.pdb')
u.atoms.write('new.pdb')
```
old pdb
HETATM      1  N   LEU     1      32.310  13.778  14.372  1.00  0.00      SYST N 0
new.pdb
ATOM    1  N   LEU     1      32.310  13.778  14.372  1.00  0.00      SYST N 0

**Comment by kain88-de** [comment]
Well yeah for the writing it is lost. Like I said we do not write `HETATM` records at all. This doesn't mean the topology isn't keeping track of this information internally.

**Comment by xiki-tempula** [comment]
@kain88-de Thank you for the help. I guess I will do some string manipulation at the end of my script to solve this problem.

**Comment by richardjgowers** [comment]
So what we could do is add this as a TopologyAttr and read/write it as
you'd expect

**Comment by mieczyslaw** [comment]
I planned to create an issue ticket with the same request so I'm glad that someone else noticed this. I have also noticed that the ticket is already 2 years old. 

I can confirm that HETATM is kept in selection, but I'm not sure what's the problem with writing it out? 

The simple code to reproduce the issue is as follows (the one in the first message with `u.atoms.recordtype = 'HETATOM'` crashes because of `Cannot set arbitrary attributes to a Group`):
```
from MDAnalysis import Universe
reference = Universe("input.pdb", "input.pdb")
hetatms = reference.select_atoms("record_type HETATM")
hetatms.atoms.write("out.pdb")
```

**Comment by IAlibay** [comment]
@mieczyslaw the issue currently is just a case that the PDBWriter as-is doesn't have the correct if/else construct to switch between HETATMs and ATOMs when writing the record lines. It _should_ be relatively simple (from the looks of it maybe ~ 3 lines + tests), unfortunately it's one of those things that get added on top of very long to-do list.

I've added a help wanted  tag if anyone wants to join in and work on this.

**Comment by mieczyslaw** [comment]
@IAlibay I have just improved PDB.py code and will create a PR in a couple of minutes!

**Comment by mieczyslaw** [comment]
@IAlibay my first PR created; are this change desired also for PDBQT?

**Comment by IAlibay** [comment]
@mieczyslaw I think we'll eventually need to fix the PDBQT writer too (although I'm not super clear on where the standard is written out for PDBQT). That being said, the changes here are probably going to be more involved as I'm already seeing a ton of tests that are failing. My suggestion here would be to get #2880 closer to merging before starting on the PDBQT writer (just to avoid code backtracking in case we make decisions that should then be ported from PDB to PDBQT). Either way it's your choice though.

**Comment by mieczyslaw** [comment]
> @mieczyslaw I think we'll eventually need to fix the PDBQT writer too (although I'm not super clear on where the standard is written out for PDBQT). That being said, the changes here are probably going to be more involved as I'm already seeing a ton of tests that are failing. My suggestion here would be to get #2880 closer to merging before starting on the PDBQT writer (just to avoid code backtracking in case we make decisions that should then be ported from PDB to PDBQT). Either way it's your choice though.

Good suggestion, let's focus on #2880.
