### ISSUE TITLE
Separating one segment and assign different segment id to each of them

### ISSUE THREAD

**Issue by xiki-tempula** [MDAnalysis/mdanalysis#1755]
I'm interested in loading a gro file, which doesn't have explicit segment/chain information and write segment id to some atom groups and export them as pdb. 

``` python
import MDAnalysis as mda
u = mda.Universe(grofile)
segid1 = u.select_atoms('resid 1-500')
segid2 = u.select_atoms('resid 501-600')
segid1.segids = 'A'
segid2.segids = 'B'
u.atoms.write('something.pdb')
```
Currently the only way of setting segment id is via `AtomGroup.segments.segids = `, which sets the segids for the whole segment which in the case of gro file, is the whole file.
Thus if I do
```python
segid1.segments.segids = 'A'
print(segid1.segids)
#['A' 'A' 'A' ..., 'A' 'A' 'A']
print(segid2.segids)
#['A' 'A' 'A' ..., 'A' 'A' 'A']
segid2.segments.segids = 'B'
print(segid1.segids)
#['B' 'B' 'B' ..., 'B' 'B' 'B']
print(segid2.segids)
#['B' 'B' 'B' ..., 'B' 'B' 'B']
```

### Currently version of MDAnalysis:
py36; mda 0.17.0

**Comment by richardjgowers** [comment]
The problem is that you've only got one Segment in the Universe, so you're just renaming the same thing twice with your code.  The comment here shows how to add a new Segment to the Universe and assign atoms to it: https://github.com/MDAnalysis/mdanalysis/issues/1268#issuecomment-291436447

**Comment by xiki-tempula** [comment]
@richardjgowers Thank you.
