### ISSUE TITLE
Changing atom id and write out

### ISSUE THREAD

**Issue by xiki-tempula** [MDAnalysis/mdanalysis#1777]
### Expected behaviour
I have a file which I wish to change the atom id according to some rules. I wonder what is the correct way of altering this property? Thanks.

```python
from MDAnalysis import Universe
from six import StringIO
gro = '''test
1
    2CL      CL20850   0.000   0.000   0.000
7.29748 7.66094 9.82962'''
u = Universe(StringIO(gro), format='gro')
u.atoms[0].id = 3
u.atoms.write('temp.gro')
#temp.gro
#test
#1
#    2CL      CL3       0.000   0.000   0.000
#7.29748 7.66094 9.82962
```
### Actual behaviour
The atom id is not changed to 3.
And the output gro file gives
```python
#temp.gro
#test
#1
#    2CL      CL1       0.000   0.000   0.000
#7.29748 7.66094 9.82962
```

### Currently version of MDAnalysis:
py36/mda0.17.0

**Comment by orbeckst** [comment]
I agree that I would have expected your code to produce what is in your comment. Maybe @richardjgowers can tell us if this *should* have worked.

Additionally, I don't think that `Atom.id` is correctly set from GRO: The following
```python
>>> u.atoms[0].id
20850
```
should have produced `2`.

**Comment by richardjgowers** [comment]
This is similar to #1072 .  Currently we just write GRO files with an `enumerate` call providing the index, we could add an option to use the original ids

**Comment by xiki-tempula** [comment]
@richardjgowers Sound like a easy fix. Which flag shall I use? `retain_id =True`?

**Comment by richardjgowers** [comment]
@xiki-tempula not sure, maybe `reindex=True/False` after pandas

I think it's slightly more compicated as either a `Timestep` or `AtomGroup` can be passed to the `write` method, where atom ids aren't available via the Timestep route.

**Comment by richardjgowers** [comment]
@xiki-tempula do you want assigning onto this?

**Comment by xiki-tempula** [comment]
@richardjgowers I have succeeded in Changing the atom id when writing the gro file. However, I'm a bit concerned about the way of passing the reindex argument into the writer. Since the only argument that the write method take is obj `write(self, obj)`, it seems that the only way to do is `atomgroup.reindex=True`.

**Comment by richardjgowers** [comment]
@xiki-tempula you'll need to change the signature of the `write` method to accept the `reindex` keyword argument
