### ISSUE TITLE
Add copy method to ChainReader

### ISSUE THREAD

**Issue by richardjgowers** [MDAnalysis/mdanalysis#1784]
The `coordinates.ChainReader` class needs to implement a copy method.  This should work identically to the base Reader's copy method, but also take into account any peculiarities of the ChainReader

**Comment by navyakhare** [comment]
I understand that `coordinates.ChainReader` concatenates multiple trajectories. Therefore should the copy method create a copy of the the current trajectory something like this-
```python
def copy(self):
       
        new = self.__class__(self.filename,
                             n_atoms=self.n_atoms)
    
       
        new[self._read_frame(self.ts.frame).frame]
        new.ts = self.ts.copy()
        for auxname, auxread in self._auxs.items():
            new.add_auxiliary(auxname, auxread.copy())
        return new

```
or should it iterate over `ChainReader` to give a copy for each trajectory?
Please correct me if there is a conceptual flaw.

**Comment by richardjgowers** [comment]
@navyakhare one of the reasons I opened this is because I've never actually looked inside ChainReader myself :)

So ChainReader accepts a list of filenames and will iterate over each frame in each file, so conceptually:
```python
def iter():
    for filename in self.filenames:
        for frame in load(filename):
            yield frame
```

The copied object should be able to iterate over all these files as if it were the original, without having to refer to the original.

From quickly looking, it might just be possible by copying the `filenames` attribute into a new version of the same class, but it would need testing to check that this iterates in the same way

@kain88-de is there anything obvious I've missed?

**Comment by kain88-de** [comment]
you can copy the filenames and the individual readers. Of course, the current frame has to be stored as well again. Otherwise there isn't anything obvious.

**Comment by navyakhare** [comment]
So for each filename the process of copying, as done in BaseReader, can be followed in ChainReader by keeping in mind the local frame ?

**Comment by kain88-de** [comment]
you can just copy them `[r.copy() for r in reader]`. This has a 90% chance of working right away. Additionally, you need to copy other member variables like files names and the dictionary we use to map from a global index to an index in a specific trajectory.
