### ISSUE TITLE
Add copy method to AuxReader

### ISSUE THREAD

**Issue by richardjgowers** [MDAnalysis/mdanalysis#1785]
A copy method needs to be added to `MDAnalysis.auxiliary.base.AuxReader` which should work similarly to the ReaderBase copy method.  This should then be extended to include the [XVGReader](https://github.com/MDAnalysis/mdanalysis/blob/develop/package/MDAnalysis/auxiliary/XVG.py).

**Comment by navyakhare** [comment]
@richardjgowers once copy method is implemented in Auxreader , it'll be called via ReaderBase copy method :
```
for auxname, auxread in self._auxs.items():
            new.add_auxiliary(auxname, auxread.copy())
        return new
```
so how to add testcases for this method? as u mentioned earlier that base reader has its own set of test cases, so should this be integrated there? or it should be integrated in test_copying.py for which we'll have to define format for AuxReader ? For the copy method itself, auxname and **kwargs (auxdata) should be copied ?

**Comment by IAlibay** [comment]
Is this something worth reviving for @BFedder's GSoC project?

**Comment by richardjgowers** [comment]
Its required to make a Universe with aux Readers copyable, so it’d be great
if they’re getting popularised

**Comment by BFedder** [comment]
I had a quick look, is there any reason why the copy method couldn't just take the output from `mda.auxiliary.base.get_description` to create and return a new instance of the AuxReader? Because if that's okay that would be a reasonably quick fix, but I feel like I'm missing something obvious.

**Comment by orbeckst** [comment]
As discussed on the call today with @BFedder @hmacdope @IAlibay , we need the aux copy(). Starting with your idea, @BFedder , looks like a sensible first step. 

I suggest to then look at Reader.copy() and mirror the behavior for consistency.
