### ISSUE TITLE
lammps topology parser requires resid

### ISSUE THREAD

**Issue by schlaicha** [MDAnalysis/mdanalysis#1791]
When I simulate a simple LJ system, no molecules are usually defined in LAMMPS, thus no molecule tag is assigned (see http://lammps.sandia.gov/doc/2001/data_format.html for the format of LAMMPS topologies).

Now when I read the corresponding file, in the 'Atoms' section the corresponding column does not exist, required by topology/LAMMPSParser.py:384, resids[i] = line[1].

Sample data used see [test.data.gz](https://github.com/MDAnalysis/mdanalysis/files/1768063/test.data.gz).

I can workaround by not setting resids here and reading in the types from line[1] in topology/LAMMPSParser.py, but the generic solution would be more involved...

### Expected behaviour

Create Universe

### Actual behaviour

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
~/.local/lib/python3.5/site-packages/MDAnalysis/topology/LAMMPSParser.py in parse(self)
    210         try:
--> 211             top = self._parse_atoms(sects['Atoms'], masses)
    212         except KeyError:

~/.local/lib/python3.5/site-packages/MDAnalysis/topology/LAMMPSParser.py in _parse_atoms(self, datalines, massdict)
    407             for i, at in enumerate(types):
--> 408                 masses[i] = massdict[at]
    409             attrs.append(Masses(masses))

KeyError: '3.7151744275286681e+01'

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
~/.local/lib/python3.5/site-packages/MDAnalysis/core/universe.py in __init__(self, *args, **kwargs)
    244                     with parser(self.filename) as p:
--> 245                         self._topology = p.parse()
    246                 except (IOError, OSError) as err:

~/.local/lib/python3.5/site-packages/MDAnalysis/topology/LAMMPSParser.py in parse(self)
    212         except KeyError:
--> 213             raise ValueError("Data file was missing Atoms section")
    214 

ValueError: Data file was missing Atoms section

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-1-04255416e702> in <module>()
      1 import MDAnalysis as mda
----> 2 u = mda.Universe('test.data')

~/.local/lib/python3.5/site-packages/MDAnalysis/core/universe.py in __init__(self, *args, **kwargs)
    259                     raise ValueError("Failed to construct topology from file {0}"
    260                                      " with parser {1} \n"
--> 261                                      "Error: {2}".format(self.filename, parser, err))
    262 
    263             # generate and populate Universe version of each class

ValueError: Failed to construct topology from file test.data with parser <class 'MDAnalysis.topology.LAMMPSParser.DATAParser'> 
Error: Data file was missing Atoms section

### Code to reproduce the behaviour

``` python
import MDAnalysis as mda

u = mda.Universe('test.data')

```

### Currently version of MDAnalysis:

0.16.2

**Comment by orbeckst** [comment]
Can you please also try with 0.17.0? (I am pretty sure you'll get the same result but just to be 100% certain – we'd certainly work from the current code base and not 0.16.2)

**Comment by richardjgowers** [comment]
0.17 will be identical, I'm looking into this

**Comment by schlaicha** [comment]
Hi, I just confirmed for 0.17.0. The corresponding lines actually haven't been touched since a while according to git blame.
