### ISSUE TITLE
pqrparser having trouble parsing gromacs generate pqr file

### ISSUE THREAD

**Issue by xiki-tempula** [MDAnalysis/mdanalysis#1804]
### Expected behaviour
I have made some pqr file using gromacs editconf tools
`gmx editconf -f enmin.tpr -mead system.pqr`
I'm interested in using MDAnalysis to analysis it.

### Actual behaviour
``` python
import MDAnalysis as mda
from six import StringIO
pqrfile = '''REMARK    The B-factors in this file hold atomic radii
REMARK    The occupancy in this file hold atomic charges
TITLE     system
REMARK    THIS IS A SIMULATION BOX
CRYST1   35.060   34.040   38.990  90.00  90.00  90.00 P 1           1
MODEL        1
ATOM      1  O    ZR     1      15.710  17.670  23.340 -0.67  1.48           O
TER
ENDMDL'''
u = mda.Universe(StringIO(pqrfile), format='pqr')
```
Gives
Error: invalid literal for int() with base 10: '15.71'

A quick look at the code shows that the pqrparser is not expecting an atom type and that makes the pqrparser think that the segid is included in the pqr file.

### Currently version of MDAnalysis:
mda 0.17.0/py36

**Comment by orbeckst** [comment]
I am pretty sure that the PQR format does not have atom types but did you check the specs for PQR (if you can find any... we might link to APBS and pdb2pqr)?

1. First question: Does our parser not follow the specs? If so, that's a bug.
2. Second question: Does editconf not follow the specs? If so, it's technically their bug.
3. Third question: If it's an "unconventional" PQR format that just enhances the original specs then can we support it so that users can just get their work done?

**Comment by richardjgowers** [comment]
@orbeckst re 2: Even if it's their bug, we still have to read it :)

**Comment by orbeckst** [comment]
@xiki-tempula do you have more input?

Btw, http://www.poissonboltzmann.org/file-formats/biomolecular-structurw/pqr is broken, so our docs https://www.mdanalysis.org/mdanalysis/documentation_pages/coordinates/PQR.html have broken links. The new file formats page is http://apbs-pdb2pqr.readthedocs.io/en/latest/formats/pqr.html ... will raise issue, sigh.

**Comment by orbeckst** [comment]
@xiki-tempula what did you mean with
> A quick look at the code shows that the pqrparser is not expecting an atom type and that makes the pqrparser think that the segid is included in the pqr file.

What is the "atom type" that you are referring to? The *atomName* (see [PQR format](http://apbs-pdb2pqr.readthedocs.io/en/latest/formats/pqr.html)) or the "O" after the *radius*?

According to the spces, *chainID* in
```
Field_name Atom_number Atom_name Residue_name Chain_ID Residue_number X Y Z Charge Radius
```
should be *optional*.

If our PQRReader requires *chainID* then it is a bug.

**Comment by xiki-tempula** [comment]
@orbeckst Thank you for the comment.
This is a gromacs bug where in the standard pqr format, there isn't a column for atom type (in this case O).
The pqrphaser determines whether there is any chain ID by counting the number of columns. So no chainID plus atom type make up the same number of columns as the standard format with chainID.

**Comment by jbarnoud** [comment]
We could probably work around that by checking the type of the fields. If the field 4 is an int, then there is no Chain_ID. If the field -1 is a float, then there is no element. By combining the type of the last field and the number of fields, we should be able to catch the annoying files where the chain id is an int.
