### ISSUE TITLE
AMBER netcdf memory problem in 0.17.0

### ISSUE THREAD

**Issue by tljm** [MDAnalysis/mdanalysis#1807]
MDAnalysis 0.17.0 seems to read AMBER netcdf into memory. Amount of RAM required to open such trajectory == size of trajectory file.

### Expected behaviour

Opening trajectories should have minimal memory footprint.

### Actual behaviour

MDAnalysis 0.17.0 consumes amount of RAM roughly equal to the size of AMBER netcdf file.

### Code to reproduce the behaviour

One can reproduce this with, for example, memory_profiler:

``` python
import MDAnalysis as mda 
print mda.__version__

@profile
def get_universe_nc():
    return mda.Universe('memory_problem.pdb','memory_problem.nc')

@profile
def get_universe_dcd():
    return mda.Universe('memory_problem.pdb','memory_problem.dcd')

U = get_universe_nc()
del U
U = get_universe_dcd()
del U
```

Save the above as `mda_mem_prof.py` and run it with `python -m memory_profiler mda_mem_prof.py`. To do it, appropriate PDB, NC and DCD files are required. I have tested it against 3.5 GB files (10k frames). I can provide these files if necessary.
Any way, in MDAnalysis 0.17.0, on my system, I get something like:

```
0.17.0
Filename: mda_mem_prof.py

Line #    Mem usage    Increment   Line Contents
================================================
     4   53.027 MiB   53.027 MiB   @profile
     5                             def get_universe_nc():
     6 3549.855 MiB 3496.828 MiB       return mda.Universe('memory_problem.pdb','memory_problem.nc')


Filename: mda_mem_prof.py

Line #    Mem usage    Increment   Line Contents
================================================
     8 3549.855 MiB 3549.855 MiB   @profile
     9                             def get_universe_dcd():
    10 3558.715 MiB    8.859 MiB       return mda.Universe('memory_problem.pdb','memory_problem.dcd')
```

It looks like memory leak.

In MDAnalysis 0.16.2 everything seems to be OK:

```
0.16.2
Filename: mda_mem_prof.py

Line #    Mem usage    Increment   Line Contents
================================================
     4   54.812 MiB    0.000 MiB   @profile
     5                             def get_universe_nc():
     6   67.281 MiB   12.469 MiB       return mda.Universe('memory_problem.pdb','memory_problem.nc')


Filename: mda_mem_prof.py

Line #    Mem usage    Increment   Line Contents
================================================
     8   67.281 MiB    0.000 MiB   @profile
     9                             def get_universe_dcd():
    10   75.891 MiB    8.609 MiB       return mda.Universe('memory_problem.pdb','memory_problem.dcd')
```

### Currently version of MDAnalysis:
0.17.0

**Comment by orbeckst** [comment]
The [NetCDF reader](https://www.mdanalysis.org/mdanalysis/documentation_pages/coordinates/TRJ.html#MDAnalysis.coordinates.TRJ.NCDFReader) was changed in 0.17.0. It is supposed to use mmap, though. [By default]((https://www.mdanalysis.org/mdanalysis/documentation_pages/coordinates/TRJ.html#MDAnalysis.coordinates.TRJ.NCDFReader)) we use the behavior of underlying [scipy.io.netcdf](https://docs.scipy.org/doc/scipy/reference/tutorial/io.html#module-scipy.io.netcdf) : 
> The NCDF reader uses [scipy.io.netcdf](https://docs.scipy.org/doc/scipy/reference/tutorial/io.html#module-scipy.io.netcdf) and therefore scipy must be installed. It supports the `mmap` keyword argument (when reading): `mmap=True` is memory efficient and directly maps the trajectory on disk to memory; `mmap=False `may consume large amounts of memory because it loads the whole trajectory into memory but it might be faster. The default is `mmap=None` and then default behavior of scipy.io.netcdf.netcdf_file prevails, i.e. `True` when filename is a file name, `False` when filename is a file-like object.

*However*, when looking at https://github.com/MDAnalysis/mdanalysis/blob/1fa0f8102e2ce1a942f5f70e3e8ebc51a8831c02/package/MDAnalysis/coordinates/TRJ.py#L462 I see that **our docs are wrong** – we are setting `mmap=False` as default, which means reading the whole trajectory into memory. Oops, sorry.

To test that this is the issue, can you please re-run your 0.17.0 example with the `mmap=True` keyword to the `Universe` (which *should* be passed to the reader)?

**Comment by tljm** [comment]
It does work. Thank you!
I guess that in 0.18 it will be set `True` by default?

```
0.17.0
Filename: mda_mem_prof.py

Line #    Mem usage    Increment   Line Contents
================================================
     4   75.559 MiB   75.559 MiB   @profile
     5                             def get_universe_nc():
     6   86.797 MiB   11.238 MiB       return mda.Universe('memory_problem.pdb','memory_problem.nc',mmap=True)


Filename: mda_mem_prof.py

Line #    Mem usage    Increment   Line Contents
================================================
     8   86.797 MiB   86.797 MiB   @profile
     9                             def get_universe_dcd():
    10   93.074 MiB    6.277 MiB       return mda.Universe('memory_problem.pdb','memory_problem.dcd',mmap=True)
```

**Comment by orbeckst** [comment]
Many thanks for the quick feedback. 

We will set it to `None` by default, as said in the docs. This will mean `mmap=True` most of the time.

**Comment by orbeckst** [comment]
@tljm many thanks for the detailed issue report and you being very responsive. This allowed us to fix the issue quickly. 

As you figured out, in the mean time just pass `mmap=True`.

Thanks!
