### ISSUE TITLE
indicate format (reST) for long description in setup.py

### ISSUE THREAD

**Issue by tylerjereddy** [MDAnalysis/mdanalysis#1837]
Perhaps worth bookmarking the fact that [PyPI supports markdown descriptions now](https://dustingram.com/articles/2018/03/16/markdown-descriptions-on-pypi) in case that can be used to enhanced our landing page there at some point. Looks like there was a PEP associated with that too.

**Comment by orbeckst** [comment]
We are writing the README and summary in reST – I don't think there's anything in Markdown that you couldn't do in reST (rather the opposite). Or do you see a specific advantage here?

FYI: the PEP was [PEP 566](https://www.python.org/dev/peps/pep-0566/); it talks about the changes in the metadata formats. Mainly this means for us (I think), that we need to use the lates version of `twine` for publishing to https://pypi.python.org (or soon to https://pypi.org/).

**Comment by tylerjereddy** [comment]
Ok, I can edit the title if the only likely change we'll need is related to `twine`. I didn't really have anything in mind--I just saw the feature release on twitter & wasn't sure if it would be beneficial.

**Comment by orbeckst** [comment]
In setup.py we now need a line to indicate the format of the long description as 
```python
  long_description_content_type='text/x-rst',
```
Otherwise it is shown as raw text on pypi.

I am changing the title so that this becomes an actionable issue.

**Comment by orbeckst** [comment]
While at it, we can also update the [core meta data](https://packaging.python.org/specifications/core-metadata/)
```python

    CLASSIFIERS = ['Development Status :: 4 - Beta',
                 'Environment :: Console',
                 'Intended Audience :: Science/Research',
                 'License :: OSI Approved :: GNU General Public License v2 (GPLv2)',
                 'Operating System :: POSIX',
                 'Operating System :: MacOS :: MacOS X',
                 'Programming Language :: Python',
                 'Programming Language :: C',
                 'Topic :: Scientific/Engineering',
                 'Topic :: Scientific/Engineering :: Bio-Informatics',
                 'Topic :: Scientific/Engineering :: Chemistry',
                 'Topic :: Software Development :: Libraries :: Python Modules',
                 'Programming Language :: Python :: 2',
                 'Programming Language :: Python :: 2.7',
                 'Programming Language :: Python :: 3',
                 'Programming Language :: Python :: 3.4',
                 'Programming Language :: Python :: 3.5',
                 'Programming Language :: Python :: 3.6',
    ],

```

For more see https://packaging.python.org/

**Comment by orbeckst** [comment]
@richardjgowers I assigned this to you tentatively but added the other folks so that it just gets done before the next release.

From the pmda release on the new PyPi I know that at least the `long_description_content_type` *must* be present or it looks crappy on PyPi. (Well, looking at https://pypi.org/project/pmda/ it still looks crappy... :-p ... not sure why.)

**Comment by orbeckst** [comment]
https://packaging.python.org/tutorials/distributing-packages/#setup-args
