### ISSUE TITLE
MDAnalysis devel mailing list deletes the messages.

### ISSUE THREAD

**Issue by ayushsuhane** [MDAnalysis/mdanalysis#1838]
Hi

I am posting messages to MDAnalysis development mailing list, but it is deleting the messages. Can anybody help with the problem.

Thanks.

**Comment by jbarnoud** [comment]
Do you have any error massage or anything that could help us figuring out what is happening? Are you using the correct email address to post on the mailing list? I think there is a filter and only addresses that subscribe to the mailing list can post there; if you have more than one address, it is an easy mistake.

The last message I see from you on the mailing list is from March 14th (Wednesday).

**Comment by orbeckst** [comment]
If you send from an address that has not posted before then the message is held until a moderator allows posting. In this way we keep spam to almost zero. 

However, I haven't seen any of your messages being held (normally, Google emails me when this is the case). 

Did you try posting through the web interface, just to check that at least this is working?

**Comment by orbeckst** [comment]
Sorry, I stand corrected. When I just checked the moderation queue I found 4 messages of yours. I approved them and the email address for posting. 

I'm sorry that I didn't see this earlier. Either the google email was not sent or I overlooked it (I'm traveling st the moment so sometimes things slip through). 

Apologies again.
