### ISSUE TITLE
Regarding the code to calculate hydrogen bond auto-correlation function and related to issue of #1563 

### ISSUE THREAD

**Issue by cy16f01** [MDAnalysis/mdanalysis#1844]
Sir, @orbeckst, @richardjgowers, @dotsdl, @arose 
I ran the code for calculating Hydrogen bond Autocorrelation function for water (my system is Glycine-Water) and the code is:
```python
import MDAnalysis as mda
from MDAnalysis.analysis import hbonds
import matplotlib.pyplot as plt
u = mda.Universe('nptmd.tpr', 'nptmd.xtc')
H = u.select_atoms('name HW1 HW2')
O = u.select_atoms('name OW')
N = u.select_atoms('name HW1 HW2')
hb_ac = hbonds.HydrogenBondAutoCorrel(u, acceptors=O, hydrogens=H, donors=H, bond_type = 'continuous',  sample_time=10)
hb_ac.run()
print(hb_ac.solution['results'])
hb_ac.solve()
```
I am getting the values as:
/home/dilip/anaconda3/lib/python3.6/sitepackages/MDAnalysis/analysis/hbonds/hbond_autocorrel.py:285: RuntimeWarning: Desired number of sample points too high, using 20 .format(req_frames), RuntimeWarning)
Performing run     2/1[200.0%]
[1.   0.40944883 0.22834645 0.15485564 0.11023622 0.0839895 0.0656168  0.03937008 0.02887139 0.02099738 0.01312336 0.01049869  0.00262467 0.00262467 0.00262467 0.00262467 0.00262467 0.   0.    0.  ]

```python
print (tau)
```
0.8040974832090737
```python
print (hb_ac.solution)
```
{'results': array([1.        , 0.40944883, 0.22834645, 0.15485564, 0.11023622,
       0.0839895 , 0.0656168 , 0.03937008, 0.02887139, 0.02099738,
       0.01312336, 0.01049869, 0.00262467, 0.00262467, 0.00262467,
       0.00262467, 0.00262467, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ],
      dtype=float32), 'time': array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5,
       11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5], dtype=float32), 'fit': array([0.60789634, 0.3130644 , 1.56536868]), 'tau': 0.8040974832090737, 'estimate': array([1.0000000e+00, 4.0797937e-01, 2.3191848e-01, 1.5544437e-01,
       1.1029723e-01, 7.9603709e-02, 5.7729632e-02, 4.1922960e-02,.
.
.
.
-4.86388901e-03, -3.68830032e-03, -2.79195132e-03]]), 'ipvt': array([1, 2, 3], dtype=int32), 'qtf': array([-1.51693848e-09, -2.31095157e-07,  9.11203370e-07])}, 'mesg': 'Both actual and predicted relative reductions in the sum of squares\n  are at most 0.000000', 'ier': 1}

So, my questions are
1]  What is the default dt value in MDAnalysis?
I have run a gromacs simulation of a glycine-water system for 10 ns (10000 ps) (dt=0.001 and the trajectories are saved for every 0.5 ps). So, my every frame is 0.5 ps and if the default value of the programme is 1 ps per trajectory, I think it will give a different value of lifetime for my current trajectory. So, do I need to give only trajectories saved after 1 ps?

2] (a) I am getting values for 'time': array ([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,......]).  How can i get intervals for 
         0.1, 0.2, 0.3 etc??
    (b) In the code, if i write "sample_time=10",  it will be writing for every 10 windows... How can i increase 
         the number of bins?

3] Since in water, the oxygen acts as both donor and acceptor, if i give  
H = u.select_atoms('name OW')
O = u.select_atoms('name OW')
N = u.select_atoms('name HW1 HW2')
hb_ac = hbonds.HydrogenBondAutoCorrel(u, acceptors=O, hydrogens=H, donors=H, bond_type = 'continuous',  sample_time=10)
i am getting error as:
ValueError: Donors and Hydrogen groups must be matched.
My question is whether every time do i need to have same numbers of donors and hydrogens? In water case, oxygen can act as a donor, so if I add oxygen list to the donor list, the number of hydrogen and donor list will not be equal.

How to solve this issues..??

Any suggestions are appreciated.

Thank you.

**Comment by orbeckst** [comment]
## dt value
> 1] What is the default dt value in MDAnalysis?

MDAnalysis reads the time and the time step from your trajectory, if the trajectory format supports it. XTC does. Check with
```python
u = mda.Universe('nptmd.tpr', 'nptmd.xtc')
print(u.trajectory.ts.dt)
print(u.trajectory.totaltime)
print(u.trajectory.n_frames)
```
Do you get what you expect?

## times
> 2] (a) I am getting values for 'time': array ([ 0. , 0.5, 1. , 1.5, 2. , 2.5,......]). How can i get intervals for 0.1, 0.2, 0.3 etc??

This is automatically determined in https://github.com/MDAnalysis/mdanalysis/blob/5a232a3168c4aaa1590bc42615ebc07773f14172/package/MDAnalysis/analysis/hbonds/hbond_autocorrel.py#L327 
```python
np.arange(len(master_results), dtype=np.float32) * self.u.trajectory.dt * self._skip
```
from the number of samples and the number of required frames, https://github.com/MDAnalysis/mdanalysis/blob/5a232a3168c4aaa1590bc42615ebc07773f14172/package/MDAnalysis/analysis/hbonds/hbond_autocorrel.py#L282

If you want to affect the time interval, you have change the `nsamples` keyword in [MDAnalysis.analysis.hbonds.hbond_autocorrel.HydrogenBondAutoCorrel](https://www.mdanalysis.org/docs/documentation_pages/analysis/hbond_autocorrel.html) and/or the `sample_time` keyword, because it is used to set `req_frames` https://github.com/MDAnalysis/mdanalysis/blob/5a232a3168c4aaa1590bc42615ebc07773f14172/package/MDAnalysis/analysis/hbonds/hbond_autocorrel.py#L263

## donor and hydrogen selection

> 3] Since in water, the oxygen acts as both donor and acceptor, if i give
> H = u.select_atoms('name OW')
> O = u.select_atoms('name OW')
> N = u.select_atoms('name HW1 HW2')
> hb_ac = hbonds.HydrogenBondAutoCorrel(u, acceptors=O, hydrogens=N, donors=H, bond_type = 'continuous', sample_time=10)
> ...
> My question is whether every time do i need to have same numbers of donors and hydrogens?

(Note: You had `hydrogens=H`, I assume you meant `hydrogens=N`)


Short answer to your question: yes.

`donors` is tricky: from the docs
> *donors (AtomGroup)* – The atoms which are connected to the hydrogens. This group must be identical in length to the hydrogen group and matched, ie `hydrogens[0]` is bonded to `donors[0]`. For many cases, this will mean a donor appears twice in this group.

You must be able to do
```python
for h, d in zip(N, H):
   print(h, d)
```
In particular, this means that each water OW *must occur twice* in the `donor` list so that you get something like
```
HW1 1, OW 1
HW2 1, OW 1
HW1 2, OW 2
HW2 2, OW 2
```
(where I assumed you have two water molecules with resids 1 and 2). You should be able to get the appropriate `donor` and `hydrogen` groups with code similar to the following:
```python
water = u.select_atoms("resname SOL")     # use what you need 
donors, hydrogens = [], []
for w in water.residues:
    ow, hw1, hw2 = w.atoms.select_atoms("name OW", "name HW1", "name HW2")  # use your selections
    donors.extend([ow, ow])              # note: same ow twice
    hydrogens.extend([hw1, hw2])    # once for each of the hw
donors = mda.core.groups.AtomGroup(donors)                 # raises a warning, which you should ignore 
hydrogens = mda.core.groups.AtomGroup(hydrogens)
```

**Comment by cy16f01** [comment]
If i give the full code as:-
```python
import MDAnalysis as mda
from MDAnalysis.tests.datafiles import GRO,XTC
from MDAnalysis.analysis import hbonds
import matplotlib.pyplot as plt
u = mda.Universe('nptmdtrjfullxtc1ps.gro', 'nptmdtrjfull1ps.trr')
water = u.select_atoms("resname SOL")     # use what you need 
donors, hydrogens = [], []
for w in water.residues:
    ow, hw1, hw2 = w.atoms.select_atoms("name OW", "name HW1", "name HW2")  # use your selections
    donors.extend([ow, ow])                           # note: same ow twice
    hydrogens.extend([hw1, hw2])                      # once for each of the hw
donors = mda.core.groups.AtomGroup(donors)            # raises a warning, which you should ignore 
hydrogens = mda.core.groups.AtomGroup(hydrogens)
hb_ac = hbonds.HydrogenBondAutoCorrel(u, acceptors=O, hydrogens=H, donors=N, bond_type='continuous', sample_time=10)
hb_ac.run()
hb_ac.solve()
print(hb_ac.solution['results'])

tau = hb_ac.solution['tau']
time = hb_ac.solution['time']
results = hb_ac.solution['results']
estimate = hb_ac.solution['estimate']
plt.plot(time,results, 'ro')
plt.plot(time,estimate)
plt.show()
```

I am getting the error as:-
NameError                                 Traceback (most recent call last)
<ipython-input-2-c7ae3c20e3a2> in <module>()
     12 donors = mda.core.groups.AtomGroup(donors)                 # raises a warning, which you should ignore
     13 hydrogens = mda.core.groups.AtomGroup(hydrogens)
---> 14 hb_ac = hbonds.HydrogenBondAutoCorrel(u, acceptors=O, hydrogens=H, donors=N, bond_type='continuous', sample_time=10)
     15 hb_ac.run()
     16 hb_ac.solve()
NameError: name 'O' is not defined
How do i solve this issue..??

My basic question is that what is the difference between the two codes..?? ie.,
a) the code for water dynamics (wherein it also has continuous and intermittent) https://www.mdanalysis.org/docs/documentation_pages/analysis/waterdynamics.html
b) the code for autocorrelation function (continuous and intermittent) https://www.mdanalysis.org/mdanalysis/documentation_pages/analysis/hbond_autocorrel.html
I read the literature but it is nowhere clearly mentioned, and couldn't find the difference between the two...
If i run the code for water dynamics, it will take hours for the code to run and give the output, whereas if i run the code with autocorrelation, it will be finished within few seconds. What is the key difference between the two.?

**Comment by orbeckst** [comment]
> NameError: name 'O' is not defined

The error tells you that you used the variable `O` and did not define it. In your original question you had the`O` atomgroup defined.

**Comment by orbeckst** [comment]
> My basic question is that what is the difference between the two codes..?? 
> [...]
> I read the literature but it is nowhere clearly mentioned, and couldn't find the difference between the two...

I don't know the answer. I would read the associated papers, write down the equations that are being solved, and compare them. 

Maybe @alejob and @richardjgowers have time to comment but I wouldn't wait for it. Everyone is busy and they probably consider their papers to be sufficiently succinct.

**Comment by cy16f01** [comment]
Sir,
In water dynamics code https://www.mdanalysis.org/docs/documentation_pages/analysis/waterdynamics.html, there is no any kind of explanation to do the curve fitting for the tau values (fitting to a multiexponential function, using 2 exponents for the continuous lifetime and 3 for the intermittent lifetime). So after i get the values, if i do the curve fitting in xmgrace, i am getting high values. Is this correct..?? or how do i get the tau values from the water dynamics code.?

But in case of autocorrelation function code https://www.mdanalysis.org/mdanalysis/documentation_pages/analysis/hbond_autocorrel.html there is mention of curve fitting. Is this more appropriate.?

Any suggestions @alejob, @richardjgowers, @orbeckst  
Thank you.

**Comment by cy16f01** [comment]
I have few questions regarding the HB autocorrelation function with the code in two links
https://www.mdanalysis.org/docs/documentation_pages/analysis/waterdynamics.html and https://www.mdanalysis.org/mdanalysis/documentation_pages/analysis/hbond_autocorrel.html 

My questions are:-
1] w.r.t water dynamics code if i give the interval ie., t0,tf,dtmax different ie., say (a) 0,20,5 (b) 0,20,10 i get two different graphs and tau values (after the nonlinear curve fitting). How is this considering..??

2] w.r.t HB autocorrelation code, i have got the values but the graphs are different when compared to the graph got from water dynamics code. Why are these two graphs different..?? Are these two codes calculating in a different way for the continuous and intermittent one..??
In both the cases (ie., in water dynamics and autocorrelation codes) after i read the related papers associated with it, the equations in both the cases are similar. But I am unable to find it.

Here is the attached image attached when the graph is plotted together.
![hb-c](https://user-images.githubusercontent.com/30516979/38667756-d953a992-3e5f-11e8-986b-9ae8e5f2c5a0.png)

**Comment by alejob** [comment]
Did you try the HB intermittent? Are both, HB intermittent, plots equals?

**Comment by cy16f01** [comment]
1] Yes, I have tried Intermittent HB autocorrelation functions with water dynamics and autocorrelation function code, again both are different graphs.
2] (a) In water dynamics code https://www.mdanalysis.org/docs/documentation_pages/analysis/waterdynamics.html  there is no any kind of explanation to do the curve fitting for the tau values (fitting to a multiexponential function, using 2 exponents for the continuous lifetime and 3 for the intermittent lifetime). So after i get the values, if i do the curve fitting in xmgrace, i am getting high values. Is this correct..?? or how do i get the tau values from the water dynamics code.?
    (b) But in case of autocorrelation function code https://www.mdanalysis.org/mdanalysis/documentation_pages/analysis/hbond_autocorrel.html  there is mention of curve fitting. Is this more appropriate.?

In both the cases (ie., in water dynamics and autocorrelation codes) after i read the related papers associated with it, the equations in both the cases are similar. But there is no mention of the code there specifically explained, which puts the user in dilemma.

**Comment by cy16f01** [comment]
I the auto-correlation code (This is my full code, and i want to calculate the HB between water molecules which are within 6.8 Angstrom from Carboxyl carbon of amino-acid which is the first minima from RDF):-
```python
import MDAnalysis as mda
from MDAnalysis.analysis import hbonds
import matplotlib.pyplot as plt
%matplotlib inline
u = mda.Universe('nptmd1f.tpr','nptmd1f.xtc')
H = u.select_atoms('byres(name OW HW1 HW2 and around 6.8 name C)')
A = u.select_atoms('byres(name OW HW1 HW2 and around 6.8 name C)')
D = u.select_atoms('byres(name OW HW1 HW2 and around 6.8 name C)')
hb_ac = hbonds.HydrogenBondAutoCorrel(u, acceptors=A, hydrogens=H, donors=D, bond_type='continuous', sample_time=10, nruns=1000001, nsamples=20, pbc=True, angle_crit=130.0, dist_crit=2.45)
hb_ac.run()
hb_ac.solve()
time = hb_ac.solution['time']
results = hb_ac.solution['results']
tau = hb_ac.solution['tau']
fit=hb_ac.solution['fit']
estimate = hb_ac.solution['estimate']
print("{time} {results}".format(time=time,results=results))
print("{time} {estimate}".format(time=time,estimate=estimate))
plt.figure(1,figsize=(15,5))
plt.figure(1,figsize=(15,5))
plt.subplot(122)
plt.xlabel('time')
plt.ylabel('HBLc')
plt.title('HBL Continuos')
plt.plot(time,results, 'ro')
plt.plot(time,estimate)
plt.show()
print (tau)
```

My questions are:-
1] How is the distance criteria taken.? (as in my case i have given dist_crit=2.45, So is the distance between interoxygen distance or hydrogen-oxygen distance..??)
2) From the literature survey, the angle criteria is taken as 30 degrees(O-O-H angle). But in this case, it is 130 degrees. How is this explained..??
3)If i increase the cutoff (say from 6.8 to 7.2), then i am getting different tau values.(How should i fix this..?)
Any suggestions are appreciated.
Thank you.

**Comment by richardjgowers** [comment]
https://www.mdanalysis.org/docs/documentation_pages/analysis/hbond_autocorrel.html#input
1)
the distance is hydrogen-acceptor

2)
there's two ways of defining the angle, autocorrel does the acceptor-hydrogen-donor angle, so it'll be 180 degrees for a perfect linear hydrogen bond.  The other way is (180-angle) so is 0 degrees for a linear hydrogen bond, if you draw it out it'll become clear

3) 
if you change the distance cutoff you should get different tau values, you're calculating a different measurement.  If you draw it out and consider the rates at which bonds can form/break with different geometric definitions you'll see that this should make a big difference

This doesn't seem like a coding issue, so I'm closing this and recommending that you go to to help.mdanalysis.org if you have any more questions

**Comment by cy16f01** [comment]
Sir,
I have been trying to calculate the Hb auto-correlation for about a month as of now, but i am unable to get satisfactory answers.
I have a system which contains 1amino-acid+x co-solvent+ y water. I have one molecule of aminoacid and have varied the co-solvent, water molecules (x,y) to get different concentrations and i have added different co-solvents too. So, in general, i want to study " the effect of hydrogen bond dynamics with different co-solvents and with varying concentrations".

I am now studying the HB auto-correlation between those water molecules which are near C-terminal and from the RDF taking the 1st and 2nd minima values.
Here is the screenshot image of RDF, My code, HB graph attached.

But from the information of the RDF, the magenta colour curve should come the in the bottom in HB correlation functions, but it is not happening.

Any suggestions on this are highly appreciated..??
![4](https://user-images.githubusercontent.com/30516979/39714755-adea40fc-5248-11e8-92db-a26fdda549bf.png)
![3](https://user-images.githubusercontent.com/30516979/39714756-ae17865c-5248-11e8-8388-39770ddc07b4.png)
![1](https://user-images.githubusercontent.com/30516979/39714757-ae441a64-5248-11e8-9223-9a3f9efe1f9c.png)
Any suggestions please....
Thank you.
