### ISSUE TITLE
docs for many AtomGroup methods missing

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/mdanalysis#1845]
### Expected behaviour
radius_of_gyration(), principal_axes() (see #1828 ), center_of_mass() and most other "compute something on an AtomGroup" (that require e.g., mass) should be in the docs for AtomGroup.

### Actual behaviour
They are not in the docs anymore (at least since 0.17.0 but probably since #363 / 0.16.0)

### Code to reproduce the behaviour
Look at https://www.mdanalysis.org/mdanalysis/documentation_pages/core/groups.html#MDAnalysis.core.groups.AtomGroup

I think the problem is that we only attached certain methods to AtomGroup when specific TopologyAttrs are present. The bare AtomGroup does not contain masses so many of the most used methods are invisible to the user (and a lot of our docs is broken, e.g., in the tutorial).

### Currently version of MDAnalysis:
develop, but also published 0.17.0

**Comment by orbeckst** [comment]
I don't know how to fix this unless we explicitly write the docs for AtomGroup. @richardjgowers @kain88-de @dotsdl any ideas (eg from datreant) how to properly document when you're doing this magic patching of groups?

From a user's point of view it is absolutely not comprehensible why certain commonly used methods are not documented at all. And it makes it hard to answer user questions because I cannot just link to the docs but have to say "there's this method that just happens to come into existence when you have masses but it's kind of a secret so you need to know about it...".

**Comment by richardjgowers** [comment]
We might be able to hack it in in the rst docs by manually listing them.

If not I'm happy to move them into the class and have them fail gracefully
without masses

**Comment by orbeckst** [comment]
@richardjgowers What needs to be done to get these docs back? If it's rst hacking then if you show one or two examples then I can do some more. A todo list would also be helpful... or perhaps we can generate the list/rst automatically?

**Comment by richardjgowers** [comment]
@orbeckst I'm not sure the easiest way to solve this one.  The fancy "attaching methods on the fly with attributes" doesn't really lend itself well to how we automatically generate docs.  The best solution would be to write the docs manually, (or at least list the methods in order), this would have the benefit that we could control the order & presentation of them

```rst
## Position related methods

Blah blah blah, these all take common kwargs like `pbc`, this keyword always does xyz

.. automethod:: `MDAnalysis.core.groups.center`
.. automethod:: `MDAnalysis.core.groups.center_of_geometry`
.. automethod:: `MDAnalysis.core.topologyattrs.Masses.center_of_mass`
.. automethod:: `MDAnalysis.core.topologyattrs.Masses.radius_of_gyration`

```

**Comment by orbeckst** [comment]
Ok, then we manually write the docs and add a comment to the code that says that you have to add the appropriate doc entry there and there.

**Comment by orbeckst** [comment]
... or we write a small python script that writes the list for us :-).

**Comment by jbarnoud** [comment]
Mouahahahahaha!

```python
import collections
import MDAnalysis as mda

targets = collections.defaultdict(lambda : collections.defaultdict(list))

for attribute_key, attribute in mda.core.topologyattrs._TOPOLOGY_ATTRS.items():
    for target, methods in attribute.transplants.items():
        for method in methods:
            #print(method)
            function = method[1]
            try:
                # We my be dealing with a property; then we need to get the
                # actual method out of it.
                function = function.fget
            except AttributeError:
                # Well, it was not a property
                pass
            text = '.. automethod:: `{}.{}`'.format(function.__module__, function.__qualname__)
            targets[target][attribute_key].append(text)

for target_key, target_dict in targets.items():
    try:
        target_name = target_key.__name__
    except AttributeError:
        # For some reason, some target are not classes but str
        target_name = target_key
    print()
    print(target_name)
    print('=' * len(target_name))
    
    for attribute_key, method_list in target_dict.items():
        print()
        print('Requires ' + attribute_key)
        print('-' * (len('Requires ') + len(attribute_key)))
        print()
        
        for method_text in method_list:
            print(method_text)
```

Prints:

```
Residue
=======

Requires names
--------------

.. automethod:: `MDAnalysis.core.topologyattrs.Atomnames.getattr__`
.. automethod:: `MDAnalysis.core.topologyattrs.Atomnames.getattr__`
.. automethod:: `MDAnalysis.core.topologyattrs.Atomnames._get_named_atom`
.. automethod:: `MDAnalysis.core.topologyattrs.Atomnames.phi_selection`
.. automethod:: `MDAnalysis.core.topologyattrs.Atomnames.psi_selection`
.. automethod:: `MDAnalysis.core.topologyattrs.Atomnames.omega_selection`
.. automethod:: `MDAnalysis.core.topologyattrs.Atomnames.chi1_selection`

Requires name
-------------

.. automethod:: `MDAnalysis.core.topologyattrs.Atomnames.getattr__`
.. automethod:: `MDAnalysis.core.topologyattrs.Atomnames.getattr__`
.. automethod:: `MDAnalysis.core.topologyattrs.Atomnames._get_named_atom`
.. automethod:: `MDAnalysis.core.topologyattrs.Atomnames.phi_selection`
.. automethod:: `MDAnalysis.core.topologyattrs.Atomnames.psi_selection`
.. automethod:: `MDAnalysis.core.topologyattrs.Atomnames.omega_selection`
.. automethod:: `MDAnalysis.core.topologyattrs.Atomnames.chi1_selection`

AtomGroup
=========

Requires names
--------------

.. automethod:: `MDAnalysis.core.topologyattrs.Atomnames._get_named_atom`

Requires name
-------------

.. automethod:: `MDAnalysis.core.topologyattrs.Atomnames._get_named_atom`

Requires bonds
--------------

.. automethod:: `MDAnalysis.core.topologyattrs.Bonds.fragments`

GroupBase
=========

Requires masses
---------------

.. automethod:: `MDAnalysis.core.topologyattrs.Masses.center_of_mass`
.. automethod:: `MDAnalysis.core.topologyattrs.Masses.total_mass`
.. automethod:: `MDAnalysis.core.topologyattrs.Masses.moment_of_inertia`
.. automethod:: `MDAnalysis.core.topologyattrs.Masses.radius_of_gyration`
.. automethod:: `MDAnalysis.core.topologyattrs.Masses.shape_parameter`
.. automethod:: `MDAnalysis.core.topologyattrs.Masses.asphericity`
.. automethod:: `MDAnalysis.core.topologyattrs.Masses.principal_axes`
.. automethod:: `MDAnalysis.core.topologyattrs.Masses.align_principal_axis`

Requires mass
-------------

.. automethod:: `MDAnalysis.core.topologyattrs.Masses.center_of_mass`
.. automethod:: `MDAnalysis.core.topologyattrs.Masses.total_mass`
.. automethod:: `MDAnalysis.core.topologyattrs.Masses.moment_of_inertia`
.. automethod:: `MDAnalysis.core.topologyattrs.Masses.radius_of_gyration`
.. automethod:: `MDAnalysis.core.topologyattrs.Masses.shape_parameter`
.. automethod:: `MDAnalysis.core.topologyattrs.Masses.asphericity`
.. automethod:: `MDAnalysis.core.topologyattrs.Masses.principal_axes`
.. automethod:: `MDAnalysis.core.topologyattrs.Masses.align_principal_axis`

Requires charges
----------------

.. automethod:: `MDAnalysis.core.topologyattrs.Charges.total_charge`

Requires charge
---------------

.. automethod:: `MDAnalysis.core.topologyattrs.Charges.total_charge`

ResidueGroup
============

Requires resnames
-----------------

.. automethod:: `MDAnalysis.core.topologyattrs.Resnames.getattr__`
.. automethod:: `MDAnalysis.core.topologyattrs.Resnames._get_named_residue`
.. automethod:: `MDAnalysis.core.topologyattrs.Resnames.sequence`

Requires resname
----------------

.. automethod:: `MDAnalysis.core.topologyattrs.Resnames.getattr__`
.. automethod:: `MDAnalysis.core.topologyattrs.Resnames._get_named_residue`
.. automethod:: `MDAnalysis.core.topologyattrs.Resnames.sequence`

SegmentGroup
============

Requires segids
---------------

.. automethod:: `MDAnalysis.core.topologyattrs.Segids.getattr__`
.. automethod:: `MDAnalysis.core.topologyattrs.Segids._get_named_segment`

Requires segid
--------------

.. automethod:: `MDAnalysis.core.topologyattrs.Segids.getattr__`
.. automethod:: `MDAnalysis.core.topologyattrs.Segids._get_named_segment`

Atom
====

Requires bonds
--------------

.. automethod:: `MDAnalysis.core.topologyattrs.Bonds.bonded_atoms`
.. automethod:: `MDAnalysis.core.topologyattrs.Bonds.fragment`

Universe
========

Requires models
---------------

.. automethod:: `MDAnalysis.topology.MMTFParser.Models.models`

Requires model
--------------

.. automethod:: `MDAnalysis.topology.MMTFParser.Models.models`
```

Now, is there a way to have sphinx inject it directly in the right docstrings?

**Comment by richardjgowers** [comment]
@jbarnoud that looks like it'd be good enough as a rst stub, then sphinx will do its magic when we build docs

**Comment by orbeckst** [comment]
Can we re-label these methods so that it looks as if they came from AtomGroup? 
```rest
.. automethod:: `AtomGroup.center_of_mass <MDAnalysis.core.topologyattrs.Masses.center_of_mass>`
```
should work.

We will still have to link to the transplant when referring to the method as in 
```rest
You can compute the center of mass with the :meth:`~MDAnalysis.core.topologyattrs.Masses.center_of_mass` method.
```
but this is already much better than before.

There might be a way to write our own sphinx plugin to somehow change things later but for right now I'd be happy with going with @jbarnoud 's script. Can you add it to `./maintainer` and just write out a file ''doc/sphinx/source/documentation_pages/core/atomgroup_methods.rst''  into the sphinx doc tree, which we can then be included from ``groups.rst``
```rest
.. include::  atomgroup_methods.rst
```
(Search through [http://docutils.sourceforge.net/docs/ref/rst/directives.txt](directives.txt) because the official reST html page on [directives](http://docutils.sourceforge.net/docs/ref/rst/directives.html) is broken.)

**Comment by orbeckst** [comment]
If we want to include the generated file *into* the docs for `AtomGroup` then they may not contain section header markup. Instead, you can use
```reST
.. rubric:: Requires masses
```

and it would also be better to have separate files such as
- `atomgroup_methods.rst`
- `atom_methods.rst`
- `residuegroup_methods.rst`
- ...

You can also add a comment at the top
```reST
.. generated with script maintainer/awesome_method_extractor.py on YYYY-MM-DD
.. commit: deadbeef
```

**Comment by orbeckst** [comment]
We are also missing from the [containers](https://www.mdanalysis.org/docs/documentation_pages/core/groups.html#collections)
- resids
- resnums
- segids (or whatever they are called...)
- and what did we have for atoms? index? Or did this one go – but then what does the "index" selection look for?

**Comment by jbarnoud** [comment]
@orbeckst I'll look at this as soon as I have time. I like the `.. include::` method. I'll see if I can have sphinx run a script or a function to generate the stub when it builds the doc.

@richardjgowers Do you know if it is possible to distinguish singulars and plurals from `mda.core.topologyattrs._TOPOLOGY_ATTRS`? Right now I have everything double.

**Comment by richardjgowers** [comment]
@jbarnoud iterate over a set of the values of `mda._TOPOLOGY_ATTRS` then grab the `attrname` off each TA
```python
# replaces your first loop
for attribute in set(mda._TOPOLOGY_ATTRS.values()):
    attribute_key = attribute.attrname

**Comment by jbarnoud** [comment]
Good idea. Thanks.
