### ISSUE TITLE
weird unrelated failures on Travis CI in TestHydrogenBondAutocorrel.test_solve_intermittent

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/mdanalysis#1848]
### Expected behaviour
Tests that are not affected by code changes (eg PR #1846 ) or doc changes (eg #1843) should not suddenly fail.

### Actual behaviour

**TestHydrogenBondAutocorrel.test_solve_intermittent** fails with  **ValueError: The array returned by a function changed size between calls** (*../../../miniconda/envs/test/lib/python3.5/site-packages/scipy/optimize/minpack.py:387: ValueError*)

### Code to reproduce the behaviour
See e.g., https://travis-ci.org/MDAnalysis/mdanalysis/jobs/357878683#L3652 or https://travis-ci.org/MDAnalysis/mdanalysis/jobs/358708798#L2190  on Travis CI.

### Currently version of MDAnalysis:
develop

**Comment by orbeckst** [comment]
@richardjgowers any idea why the minpack routine in hbond correlation should misbehave in the tests? Maybe a problem with running two processes????

**Comment by kain88-de** [comment]
was there are new scipy release?

**Comment by tylerjereddy** [comment]
> was there a new scipy release?

Yes, there was a maintenance release `1.0.1` about four days ago & I note that the travis log is showing that we search for >=1.0 & eventually do indeed install 1.0.1. Some `scipy.optimize` code was touched in the maintenance release (should be no new features, just bug fixes though).

**Comment by richardjgowers** [comment]
Yeah I'm not doing anything weird and wonderful with scipy, just calling `leastsq` to do a curve_fit with boundary conditions for the parameters

**Comment by kain88-de** [comment]
[CRON job for master a week ago](https://travis-ci.org/MDAnalysis/mdanalysis/jobs/355824201)

[CRON job for master a day ago](https://travis-ci.org/MDAnalysis/mdanalysis/jobs/358859673)

A week ago the master branch still passed. I haven't checked all dependencies but scipy did change in between the builds.

**Comment by richardjgowers** [comment]
@zemanj fixed this in #1853
