### ISSUE TITLE
The dihedral function returns nan value

### ISSUE THREAD

**Issue by jeeberhardt** [MDAnalysis/mdanalysis#1850]
### Expected behaviour
The code is expected to compute the dihedral angle between 4 atom positions using the ```dihedral```function.

### Actual behaviour
But instead, the value returned by the ```dihedral```function returns ```nan```. The solution that I found is to convert the atom positions from ```float32```to ```float64```, which is weird...

### Code to reproduce the behaviour
``` python
import numpy as np
from MDAnalysis import Universe
from MDAnalysis.lib.mdamath import dihedral

u = Universe('1LBD.pdb')
ag = u.select_atoms('(resid 225 or resid 226 or resid 227 or resid 228) and name CA')

# Returns nan
A, B, C, D = ag.atoms.positions 
# Returns the right value (about 85 degrees)
#A, B, C, D = ag.atoms.positions.astype(np.float64)

AB = A - B
BC = B - C
CD = C - D

print np.rad2deg(dihedral(AB, BC, CD))
```

### Currently version of MDAnalysis:
MDAnalysis==0.17.0
numpy==1.14.0

**Comment by jeeberhardt** [comment]
No @richardjgowers, I checked the angle using PyMOL to be sure. 

But apparently the problem is somehow linked to ```Jupyter notebook```. If I am executing the code in a separate file from the terminal, I obtain the right result. However, if you execute the same code in a ```Jupyter notebook``` (version 4.4.0), you end up with a ```nan```as a result. And the only way that I found so far to fix that problem is to add ```astype(np.float64)```. So I clearly don't know what is happening with ```jupyter notebook```...

**Comment by richardjgowers** [comment]
@jeeberhardt huh, weird.  Does `AB.copy()` produce the correct result?  It might be that jupyter isn't managing the memory correctly, so its not so much the different precision as the copying the data that fixes it.

**Comment by kain88-de** [comment]
Jupyter doesn't much else than sending data back and forth to an IPython session.  Therefore the error should also appear in an IPython session.  This design also means Jupyter doesn't do any memory management of the process.  I think the Jupyter devs would also like to know if this is reproducible because it should change how the python session behaves.

**Comment by orbeckst** [comment]
Neither in ipython nor in Jupyter can I reproduce the problem (Python 3, MDA 0.17.1-dev): It always gives the same answer:
```python
>>> import numpy as np
>>> import MDAnalysis as mda
>>> from MDAnalysis.lib.mdamath import dihedral
>>> u = mda.fetch_mmtf("1lbd")
>>> ag = u.select_atoms('(resid 225 or resid 226 or resid 227 or resid 228) and name CA')
>>> A, B, C, D = ag.atoms.positions
>>> AB = A - B
... BC = B - C
... CD = C - D
...
>>> print(np.rad2deg(dihedral(AB, BC, CD)))
85.227394
>>> ag.dihedral.value()
85.227394
```

Are you using virtual environments or conda? I sometimes get weird behavior if I forget to install jupyter and ipython inside the same environment where I have MDAnalysis installed.

**Comment by jeeberhardt** [comment]
Hi,

I did my little investigation and I observe this weird behavior only on mac OS. On my other computer under Ubuntu, I get the right asnwer everytime. But as you said @orbeckst, it could be link to way I setup my Python configuration, even if MDAnalysis and jupyter are installed in the same environement, because I couldn't reproduce this bug creating a clean environnement (```conda create -n pymda python=2.7; pip install MDAnalysis numpy jupyter```). Anyway, I will reinstall the whole conda distribution and it should fix the problem, otherwise I will let you know. 

Thanks!

**Comment by orbeckst** [comment]
@jeeberhardt any updates on this issue? Can it be closed?

**Comment by orbeckst** [comment]
Hi, I haven't heard anything else on this issue so I am closing it. Please feel free to re-open or request it to be re-opened.
