### ISSUE TITLE
Regarding hanging issues of the latest version of MDAnalysis with Anaconda (v-4.4.10), pip (v-9.0.3)

### ISSUE THREAD

**Issue by cy16f01** [MDAnalysis/mdanalysis#1851]
Hello,
I have installed latest version of conda, pip as:-

```
workstation1@Dilip:~$ python --version
Python 3.6.4 :: Anaconda, Inc.
workstation1@Dilip:~$ conda --version
conda 4.4.10
workstation1@Dilip:~$ pip --version
pip 9.0.3 from /home/workstation1/anaconda3/lib/python3.6/site-packages (python 3.6)
```

Now my questions are, 
In older versions
```
workstationx@abc:~$ python --version
Python 3.6.3 :: Anaconda, Inc.
workstationx@abc:~$ conda --version
conda 4.4.34
workstationx@abc:~$ pip --version
pip 9.0.1 from /home/workstation1/anaconda3/lib/python3.6/site-packages (python 3.6)
```

1] The environment is different, and in the older versions if i type in terminal "jupyter notebook", it will open a new kernel. And if there is huge data printed, it forms a background stuff (the whole data will be within a space unlike the new one.) where i can scroll down within a certain space....
2] In the newer version, if i give run the code for water dynamics, i am unable to see the % status which defines how much has the code run as in(" MDAnalysis.analysis.hbonds: INFO     Starting analysis (frame index start=0 stop=10001, step=1)
MDAnalysis.analysis.hbonds: INFO     Starting analysis (frame index start=0 stop=10001, step=1)
HBonds frame 100: 100/10001 [10.0%]" as an example.)

How do i solve this issue..?? Here are the two kernels (old and new).

For eg, in ln 67, in the code:-
```python 
import pandas as pd
df = pd.DataFrame.from_records(h.table)
print (df)
```
The output values are written, but in newer one it fills up the whole page, whereas in old one it goes in background, and i can scroll down without consuming the whole page....

http://localhost:8889/lab  --> corresponds to latest version of pip, conda installed
http://localhost:8888/notebooks/Untitled1.ipynb#  --> corresponds to old version of pip, conda installed

Any suggestions are appreciated.

Thank you.

**Comment by orbeckst** [comment]
1. Which version of MDAnalysis are you using?
2. Are you running the same version of MDAnalysis in the old and new environment?

By the way, we can't see anything that's on your local machine ("localhost"). You have to make a screen shot an attach a PNG image or upload the notebook as a gist https://gist.github.com/.

**Comment by cy16f01** [comment]
I am using MDAnalysis version 0.17.0
Here are the Screenshot images.
![old](https://user-images.githubusercontent.com/30516979/38401909-2a4d943c-3976-11e8-848b-26c91599f551.png)
![new1](https://user-images.githubusercontent.com/30516979/38401910-2a7b3932-3976-11e8-8837-f484c6cf5409.png)
![new](https://user-images.githubusercontent.com/30516979/38401911-2aa8ee90-3976-11e8-854b-38edc8bee25f.png)
I want the old one... and not the new ones...

Thank you.

**Comment by orbeckst** [comment]
What are the versions of jupyter in the two cases?

**Comment by orbeckst** [comment]
Is the difference that with 4.4.0 you get an "overlay" of the Jupyter logo over your notebook while the Python kernel is executing, as in your middle screen shot?

I am not really sure what the problem is. And I am not sure that it has anything to do with MDAnalysis itself because all that changed is the Jupyter version.

Have you searched the internet for similar problems?
