### ISSUE TITLE
Regarding "No module named MDAnalysis"

### ISSUE THREAD

**Issue by cy16f01** [MDAnalysis/mdanalysis#1860]
I had previously installed MDAnalysis (v 0.17.0) in my system, but i don't know what happened (i think MDAnalysis in installed somehow during some python kernel upgrading etc and stuff...)and now in jupyter notebook if i type ```import MDAnalysis```, it gives as error stating "No module named 'MDAnalysis'" ).

I tried to install MDAnalysis again through pip and conda, which gets installed,
```pip install MDAnalysis```
Requirement already satisfied: MDAnalysis in ./anaconda3/lib/python3.6/site-packages
Requirement already satisfied: networkx>=1.0 in ./anaconda3/lib/python3.6/site-packages (from MDAnalysis)
Requirement already satisfied: six>=1.4.0 in ./anaconda3/lib/python3.6/site-packages (from MDAnalysis)
.
.
.
Requirement already satisfied: setuptools in ./anaconda3/lib/python3.6/site-packages (from kiwisolver>=1.0.1->matplotlib>=1.5.1->MDAnalysis).

But in the jupyter notebook if it type ```import MDAnalysis``` again it is showing the same error stating as "No module named 'MDAnalysis'".
I followed all the links given for MDAnalysis installation... but in vain
i followed the following links too...
http://becksteinlab.github.io/MDAnalysis-workshop/installation.html#chapter-installing-mdanalysis
https://www.mdanalysis.org/MDAnalysisTutorial/installation.html
https://www.mdanalysis.org/pages/installation_quick_start/
https://github.com/MDAnalysis/mdanalysis/wiki/Install etc.,

And if i do  ```python -c 'from MDAnalysis.tests import test; test()'``` 
i am getting error as:-

Docs: http://doc.pytest.org/en/latest/warnings.html
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 389 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!                       
================== 54 warnings, 389 error in 19.13 seconds===========================

But the docs says "Ideally, you should only get passing tests (“ok” or just a single dot ”.”) or “KnownFailures”."

Is this making any problems..??

How do i solve this issue.?

Any suggestions are appreciated.

Thank you.

**Comment by mimischi** [comment]
Did you try removing the package via `pip uninstall mdanalysis`? I've had this happen to me a few times, never knowing how I got there. Ultimately wiping my python environment helped all the time.

**Comment by cy16f01** [comment]
yes, i will try ```pip uninstall mdanalysis```. how do i wipe the full python environment.? and then install it...?? what are the commands..??

**Comment by orbeckst** [comment]
You might have to do 
```bash
pip uninstall mdanalysis
```
multiple times. 

*If you are using anaconda* (as you seem to do) we suggest you [install MDAnalysis with conda](https://www.mdanalysis.org/pages/installation_quick_start/#conda) (and not with `pip`).

If you are using [conda environments](https://www.mdanalysis.org/2017/04/07/environments/#conda-environments) you should install MDAnalysis into this environment *and* jupyter (and ipython). For me it typically does not work to use jupyter or ipython that has not been installed into the same environment.

**Comment by jbarnoud** [comment]
Do you use the same python executable when running pip, the python kernel in jupyter, and the tests? Do you get the same result if you execute `python -c 'import sys; print(sys.prefix)'` in the terminal, and if you execute the same python instructions in a notebook? Does it match what `which pip` says?

**Comment by cy16f01** [comment]
I solved this issue.
Actually, there was a problem with the kernel, which was i think was not allowing some modules (including MDAnalysis) to load.
So, i followed the link https://github.com/jupyter/notebook/issues/2898
and deleted```/usr/local/share/jupyter/kernels/python3```,  which makes Jupyter to find a default Python kernel using the same Python running Jupyter itself (i.e. Anaconda).
