### ISSUE TITLE
Streamline function returns zero arrays

### ISSUE THREAD

**Issue by tcolburn** [MDAnalysis/mdanalysis#1870]
### Expected behaviour

The code is expected to take in some number of frames from a trajectory and output velocity arrays and displacement statistics, generally for the purposes of generating streamline plots.

### Actual behaviour

Returns zero arrays for the velocities `u1` and `v1`. 

### Code to reproduce the behaviour

``` python
import numpy as np
import matplotlib, matplotlib.pyplot
import MDAnalysis, MDAnalysis.visualization.streamlines
import MDAnalysis as mda

top = "explicit/step5_assembly.psf"
data_list = ["explicit/" + str(i+1).zfill(3) + "/dims_P1_test_1.dcd" for i in xrange(1)]
data = mda.Universe(top, data_list)
data.trajectory

L = data.select_atoms("name P*").bbox()

start = 1
stop = start + 1
u1, v1, average_displacement, standard_deviation_of_displacement = MDAnalysis.visualization.streamlines.generate_streamlines(data.filename, 
            data.trajectory.filename,
            grid_spacing=1, MDA_selection='name P*', start_frame=start, end_frame=stop,
            xmin=L[0,0]*10, xmax= L[1,0]*10,
            ymin= L[0,1]*10, ymax= L[1,1]*10,
            maximum_delta_magnitude=100.0, num_cores=12)

```
Notice that this is very similar to the example in the docs (https://www.mdanalysis.org/docs/documentation_pages/visualization/streamlines.html), but with a different trajectory/topology fed in. Numerous values for `grid_spacing` and `maximum_delta_magnitude` were tried, with no change in results.

Taking a look at the development branch of the code -- specifically `MDAnalysis/visualization/streamlines.py` -- it looks as though this set of lines may be the culprit for the return of zero arrays:

```python
         #I need to write a velocity of zero if there are any 'empty' squares in either frame:
            xy_deltas_to_write = []
            for square_1_centroid, square_2_centroid in zip(list_centroids_this_frame_using_indices_from_last_frame,
                                                            list_previous_frame_centroids):
                if square_1_centroid == 'empty' or square_2_centroid == 'empty':
                    xy_deltas_to_write.append([0, 0])
                else:
                    xy_deltas_to_write.append(np.subtract(square_1_centroid, square_2_centroid).tolist())

```
https://github.com/MDAnalysis/mdanalysis/blob/8c331d7883ccf4a61dec884f2d95110726ce7573/package/MDAnalysis/visualization/streamlines.py#L200

In a moment, I'll drop a Google Drive link to a zipped directory containing the `.dcd` and associated `.psf` used in the example code.

### Used Versions of MDAnalysis (and other packages):

MDAnalysis == 0.17.0, ~0.18.1-dev~
numpy == 1.14.1, 1.14.2

~Note: the code provided gives the same results in the development branch as in the main branch of MDAnalysis.~ (EDIT)

**Comment by tylerjereddy** [comment]
Ok, probably good to include links to some reasonably-sized input files as you say. Somewhat surprising that this issue pops up after recently merging #1859.

Of course, you're also welcome to try to patch it yourself & the core devs here can review it! It is slightly tricky to pactch / test visualization code here because it is only regression tested (not unit tested) at the moment.

**Comment by tcolburn** [comment]
Let me know if this link doesn't work:
https://drive.google.com/file/d/1iM_4-OHCxFxb2XLv-PhS0rnWS6w1S_eJ/view?usp=sharing

**Comment by orbeckst** [comment]
@tcolburn the following looks suspicious:
```python
start = 1
stop = start + 1
```
Can you try setting it to `None` to look at the whole trajectory? 

I don't know why the example has `start=2` and `stop=3` (maybe @tylerjereddy can give some background) but given that you have a atomistic trajectory and not an enormously big coarse grained one and the analysis does some averaging I'd try to look at a whole trajectory.

**Comment by tcolburn** [comment]
@orbeckst The start-stop lines were added by @sseyler after my round of testing. The results are the same whether you use Sean's start-stop scheme, or manually enter the frame numbers (which is what I did). I've tested a number of frame ranges (2-10 frames, and the entire trajectory), all of which give back zero arrays.

**Comment by tcolburn** [comment]
Hold on: I did not attempt the full trajectory with the development branch. I'm in the process of doing this now with a pared down trajectory (every 10th frame of the full trajectory, giving a total of 1000 frames). I'll update the issue as those results come in.

**Comment by tcolburn** [comment]
@orbeckst I managed to generate `u` and `v` arrays that had small but non-zero velocities by using the development branch. The shape of `Grid(x,y)` is now inconsistent with the mutual shape of `u` and `v`, so I'm stalled at the plotting stage -- but I suspect that this is user error. I will open up a new issue if need be, but I'm happy to close this in the meantime, barring objections from anyone else in the thread.

**Comment by orbeckst** [comment]
I am not sure what `Grid(x,y)` is, I don't see it in your original code. Either ask on the mailing list or open a new issue. It will be helpful if you show how the outputs disagree (e.g., `Grid.shape` etc).
