### ISSUE TITLE
Deploying from Travis

### ISSUE THREAD

**Issue by richardjgowers** [MDAnalysis/mdanalysis#1871]
It looks like we could set it up so that after (successfully) pushing to master branch we could get travis to push to pypi for us.

https://docs.travis-ci.com/user/deployment/pypi/

Does anyone see any problems using this?

**Comment by kain88-de** [comment]
no that would be pretty awesome.

**Comment by orbeckst** [comment]
We could also update the doc deployment.

1. At the moment, devdocs are deployed with the [maintainer/deploy_docs.sh](https://github.com/MDAnalysis/mdanalysis/blob/develop/maintainer/deploy_docs.sh) script from travis https://github.com/MDAnalysis/mdanalysis/blob/8bab35993272ad9f1c8ad4893f85bd29928450a8/.travis.yml#L113

2. And the master docs are *manually deployed* by either @richardjgowers or me with the [maintainer/deploy_master_docs.sh](https://github.com/MDAnalysis/mdanalysis/blob/develop/maintainer/deploy_master_docs.sh) script (see also PR #1890 on that process). 

For pytng  @kain88-de and @richardjgowers have used Travis gh-pages deployment  in the [.travis.yml](https://github.com/MDAnalysis/pytng/blob/8f1ae79431a78e069b2c369861d473c75918c2d9/.travis.yml#L30) file, which is cleaner than [deploy_docs.sh](https://github.com/MDAnalysis/mdanalysis/blob/develop/maintainer/deploy_docs.sh).

**Comment by orbeckst** [comment]
> Does anyone see any problems using this?

One possible issue is that you have one less chance to catch a buggy release before it gets out.

**Comment by richardjgowers** [comment]
So the only extra step I do that travis doesn't for a release is I build the source distribution, upload it to testpypi, then download and test that version of things.  We could probably wrap that whole process into a script and then theoretically travis has replaced me!

**Comment by orbeckst** [comment]
The different automation options on travis are pretty cool... maybe
- [build artifacts](https://docs.travis-ci.com/user/deployment/pypi/#Releasing-build-artifacts): perhaps we can use this to upload a tarball of the docs (#1353 )
- automatically tweet the release ;-) with [Running commands after release](https://docs.travis-ci.com/user/deployment/pypi/#Running-commands-before-and-after-release)

**Comment by IAlibay** [comment]
Deployment via CI is now done via gh actions.
