### ISSUE TITLE
add_TopologyAttr should accept list as values

### ISSUE THREAD

**Issue by kain88-de** [MDAnalysis/mdanalysis#1876]
### Expected behaviour

`u.add_TopologyAttr('names', ['CA', 'CA'])` should work and acces of the attribute afterwards/

### Actual behaviour

Only numpy arrays are accepted. Of I give a list a strange int error is thrown only after I try to access the attribute and not when I add it. I would also be OK if there is a type error when I try to add the attribute.

### Code to reproduce the behavior

``` python
import MDAnalysis as mda


u = mda.Universe.empty(2, n_residues=2, atom_resindex=[1, 2])
u.add_TopologyAttr('names', ['CA', 'CA'])
```

### Currently version of MDAnalysis:
(run `python -c "import MDAnalysis as mda; print(mda.__version__)"`)
0.18.0

**Comment by richardjgowers** [comment]
there's a lot of `np.asarray` and type checking missing from attributes really, this is an example of that.  Usually this is hidden because the Parsers we use to create Attributes are fairly internal
