### ISSUE TITLE
switch integrations from services to GitHub apps or webhooks

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/mdanalysis#1885]
See https://developer.github.com/changes/2018-04-25-github-services-deprecation/ : 
> GitHub plans on shutting down GitHub Services so we can shift focus to other areas of the API, such as strengthening GitHub Apps and GraphQL, and improving webhooks. The intention of GitHub Services was to allow third-party developers to submit code for integrating with their services, but this functionality has been superseded by GitHub Apps and webhooks. GitHub Services has not supported new features since April 25, 2016, and we plan to **officially deprecate it on October 1st, 2018.**

TODO (as far as I can tell)
- [ ] Travis
- [x] ReadTheDocs (not really for MDAnalysis)

**Comment by orbeckst** [comment]
When I looked at our services page then it had Travis CI enabled there. Maybe I misunderstand how integrations work. 

--
Oliver Beckstein
email: orbeckst@gmail.com

**Comment by jbarnoud** [comment]
I had a look at the same page, and travis and read the docs are there indeed. It seems I misunderstood how these services are integrated to github. I searched for instruction on what to do about travis but I did not find anything.

**Comment by richardjgowers** [comment]
I'm on this, I sent off an email about it today.

**Comment by orbeckst** [comment]
Thanks.

(Note that we should disable RTD again – we are not using it.)

**Comment by orbeckst** [comment]
I deleted RTD.

**Comment by richardjgowers** [comment]
Ok we're running on travis-ci.com (not .org) so that's done (thanks @jandom )

Looks like a few things don't work yet though:

https://travis-ci.com/MDAnalysis/mdanalysis/builds/72671173?utm_source=github_status&utm_medium=notification

**Comment by richardjgowers** [comment]
https://blog.travis-ci.com/2018-05-07-announcing-support-for-github-checks-api-on-travis-ci-com?utm_source=Intercom&utm_campaign=checks_release

this is fancy

**Comment by richardjgowers** [comment]
So pushing to coveralls from travis isn't working.  I've turned coveralls off/on to see if it picks up the new settings, otherwise maybe we have to add a token to a `.coveralls.yml` file
