### ISSUE TITLE
No module named duecredit

### ISSUE THREAD

**Issue by Ash1000** [MDAnalysis/mdanalysis#1896]
/usr/local/lib/python2.7/dist-packages/MDAnalysis-0.18.0-py2.7-linux-x86_64.egg/MDAnalysis/due.py:88: UserWarning: No module named duecredit
  warnings.warn(str(err))
Traceback (most recent call last):

**Comment by kain88-de** [comment]
duplicate of #1872 

this will be fixed with the next release.
