### ISSUE TITLE
PDB hybrid36 format (Packmol PDB files with hexadecimal numbers)

### ISSUE THREAD

**Issue by richardjgowers** [MDAnalysis/mdanalysis#1897]
Here's a really funny one packmol [writes PDB indices in hexadecimal](https://github.com/mcubeg/packmol/commit/d39950b39c132d75281c1314d8dcd5e64b9c0fe1) when they get too high.   PDB really is the format that never stops giving

**Comment by kain88-de** [comment]
https://www-s.ks.uiuc.edu/Research/namd/mailing_list/namd-l.2015-2016/0569.html

VMD might do something similar.

**Comment by kain88-de** [comment]
http://thegrantlab.org/bio3d/html/read.pdb.html yup now I'm pretty sure VMD supports hex numbers. VMD will also be an easy way to generate a test file

**Comment by richardjgowers** [comment]
Ok but packmol only numbers hexidecimally *after* 99,999 😂 maybe that’s a
bug to report

**Comment by kain88-de** [comment]
I'm not sure if VMD doesn't do that too.

**Comment by richardjgowers** [comment]
Ah apparently VMD does the same.  Which means we'd have to read more than 16 lines to check this.  I think this will be fairly easy to fix, but harder to fix with no performance loss, which is preferable as huge PDB files are commonly used.

**Comment by orbeckst** [comment]
There's a version of the "PDB format" that uses hexadecimals called [hybrid-36](http://cci.lbl.gov/hybrid_36/). (This was discussed in https://github.com/pandegroup/openmm/issues/659 a while ago.) We can support hybrid-36 either separately with our PDBReader.

(I have to say I don't feel very good about having our reader automatically trying to recognize every custom variation of the PDB format; perhaps we could have a flag like the old "strict=True" that actually fails when the format is not the true PDB one.... or at least a warning.)

**Comment by richardjgowers** [comment]
@orbeckst yeah maybe it would be better if you had to specify that this is required via keyword args.  It might also make the resulting code cleaner/faster

**Comment by orbeckst** [comment]
I saw https://plumed.github.io/doc-v2.4/user-doc/html/pdbreader.html
> Since PLUMED 2.4 we allow [hybrid 36](http://cci.lbl.gov/hybrid_36/) format to be used to specify atom numbers. This format is not particularly widespread, but has the nice feature that it provides a one-to-one mapping between numbers up to approximately 80 millions and strings with 5 characters, plus it is backward compatible for numbers smaller than 100000. This is not true for notations like the hex notation exported by VMD. 

Note the comment on VMD apparently doing its own thing vs following the hybrid-36 standard.

What does packmol really do? VMD-style or hybrid-36?

I am all for supporting hybrid-36.

**Comment by kain88-de** [comment]
Does it make sense to allow this format also for residue ids?
