### ISSUE TITLE
Alias tempfactor & bfactors

### ISSUE THREAD

**Issue by richardjgowers** [MDAnalysis/mdanalysis#1901]
These are currently separate attributes, but are in fact the same thing.  Because both names are widely used maybe it makes more sense to alias them, so a single `TopologyAttr` gives you both access points...

**Comment by orbeckst** [comment]
There's also an issue that MMTFReader used bfactors and PDBReader/Writer uses tempfactors. This leads to the annoying situation that writing a PDB from MMTF looses the tempfactors:
```python
import MDAnalysis as mda
u = mda.fetch_mmtf('1AKE')
u.select_atoms("segid A").write("1AKE_A.pdb")
```
gives
```
~/anaconda3/lib/python3.5/site-packages/MDAnalysis/coordinates/PDB.py:906: UserWarning: Found no information for attr: 'tempfactors' Using default value of '0.0'
  "".format(attrname, default))
```

**Comment by orbeckst** [comment]
Workaround for the MMTF/PDB case:
```python
import MDAnalysis as mda
u = mda.fetch_mmtf('1AKE')
u.add_TopologyAttr('tempfactors', u.atoms.bfactors)
```

**Comment by IAlibay** [comment]
@lilyminium and I are keen to see this get fixed for 2.0, if anything it breaks colour-by-bfactor visualisation in NGLView.

Do we need to warn users in 1.0.2? (I don't think so, but maybe I'm missing something).

**Comment by lilyminium** [comment]
To repeat what I said on Discord, IMO we should in 2.0 but maybe not 1.0.2. My arguments is that users *may* have assigned different information to bfactors and tempfactors in existing code. The most likely scenario to select atoms with custom tags (e.g. "bfactor 2" vs "tempfactor 2")

**Comment by orbeckst** [comment]
Note that 1.1.0 promised 1eede18 :

> In version 2.0, MDAnalysis will stop treatiing  tempfactors and bfactors as separate attributes. Instead, they will be aliases of the same attribute.

If we decide to _not_ honor this promise we would technically have to do 1.2.0 with a deprecation note. (We can decide that we're breaking semver a little bit here — but at least we should be clear about what we're doing.)

**Comment by IAlibay** [comment]
> Note that 1.1.0 promised [1eede18](https://github.com/MDAnalysis/mdanalysis/commit/1eede18101cedf2be9ba686cc41429719d8bb3da) :
> 
> > In version 2.0, MDAnalysis will stop treatiing  tempfactors and bfactors as separate attributes. Instead, they will be aliases of the same attribute.
> 
> If we decide to _not_ honor this promise we would technically have to do 1.2.0 with a deprecation note. (We can decide that we're breaking semver a little bit here — but at least we should be clear about what we're doing.)

🙀 Please no more 1.x branch - @lilyminium you're our only hope.

**Comment by lilyminium** [comment]
To sum up earlier discussion before we all forget it, we have decided to alias bfactor to tempfactor so that tempfactor is the One True TopologyAttr.
