### ISSUE TITLE
Error with running WaterBridgeAnalysis

### ISSUE THREAD

**Issue by farshadsm** [MDAnalysis/mdanalysis#1919]
Hello,

When I run following code, I get an error.

```python
w = mda.analysis.hbonds.WaterBridgeAnalysis(u, selection1='type 7', selection2='type 13',
                                            water_selection='type 1 and type 2', forcefield='other')
```
where "type 7" and "type 13" are nitrogen atoms and "type 1" and "type 2" are H and O in water, respectively. 

error:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
~/anaconda/lib/python3.4/site-packages/MDAnalysis/core/selection.py in _parse_subexp(self)
   1284         try:
-> 1285             return _SELECTIONDICT[op](self, self.tokens)
   1286         except KeyError:

~/anaconda/lib/python3.4/site-packages/MDAnalysis/core/selection.py in __init__(self, parser, tokens)
    637         if not vals:
--> 638             raise ValueError("Unexpected token '{0}'".format(tokens[0]))
    639 

ValueError: Unexpected token 'None'

During handling of the above exception, another exception occurred:

SelectionError                            Traceback (most recent call last)
<ipython-input-18-eddeea593a64> in <module>()
      1 w = mda.analysis.hbonds.WaterBridgeAnalysis(u, selection1='type 7', selection2='type 13',
----> 2                                             forcefield='other')
      3 w.run()

~/anaconda/lib/python3.4/site-packages/MDAnalysis/analysis/hbonds/wbridge_analysis.py in __init__(self, universe, selection1, selection2, water_selection, selection1_type, update_selection1, update_selection2, update_water_selection, filter_first, distance_type, distance, angle, forcefield, donors, acceptors, start, stop, step, debug, verbose)
    449             distance_type=distance_type, distance=distance, angle=angle,
    450             forcefield=forcefield, donors=donors, acceptors=acceptors,
--> 451             start=start, stop=stop, step=step, debug=debug, verbose=verbose)
    452         self._update_water_selection()
    453 

~/anaconda/lib/python3.4/site-packages/MDAnalysis/analysis/hbonds/hbond_analysis.py in __init__(self, universe, selection1, selection2, selection1_type, update_selection1, update_selection2, filter_first, distance_type, distance, angle, forcefield, donors, acceptors, start, stop, step, debug, detect_hydrogens, verbose, pbc)
    608 
    609         self.debug = True  # always enable debug output for initial selection update
--> 610         self._update_selection_1()
    611         self._update_selection_2()
    612         # per-frame debugging output?

~/anaconda/lib/python3.4/site-packages/MDAnalysis/analysis/hbonds/wbridge_analysis.py in _update_selection_1(self)
    484         if self.selection1_type in ('donor', 'both'):
    485             self._s1_donors = self._s1.select_atoms(
--> 486                 'name {0}'.format(' '.join(self.donors)))
    487             self._s1_donors_h = {}
    488             for i, d in enumerate(self._s1_donors):

~/anaconda/lib/python3.4/site-packages/MDAnalysis/core/groups.py in select_atoms(self, sel, *othersel, **selgroups)
   2065         sel_strs = (sel,) + othersel
   2066         selections = tuple((selection.Parser.parse(s, selgroups)
-> 2067                             for s in sel_strs))
   2068         if updating:
   2069             atomgrp = UpdatingAtomGroup(self, selections, sel_strs)

~/anaconda/lib/python3.4/site-packages/MDAnalysis/core/groups.py in <genexpr>(.0)
   2065         sel_strs = (sel,) + othersel
   2066         selections = tuple((selection.Parser.parse(s, selgroups)
-> 2067                             for s in sel_strs))
   2068         if updating:
   2069             atomgrp = UpdatingAtomGroup(self, selections, sel_strs)

~/anaconda/lib/python3.4/site-packages/MDAnalysis/core/selection.py in parse(self, selectstr, selgroups)
   1257         tokens = selectstr.replace('(', ' ( ').replace(')', ' ) ')
   1258         self.tokens = collections.deque(tokens.split() + [None])
-> 1259         parsetree = self.parse_expression(0)
   1260         if self.tokens[0] is not None:
   1261             raise SelectionError(

~/anaconda/lib/python3.4/site-packages/MDAnalysis/core/selection.py in parse_expression(self, p)
   1265 
   1266     def parse_expression(self, p):
-> 1267         exp1 = self._parse_subexp()
   1268         while (self.tokens[0] in _OPERATIONS and
   1269                _OPERATIONS[self.tokens[0]].precedence >= p):

~/anaconda/lib/python3.4/site-packages/MDAnalysis/core/selection.py in _parse_subexp(self)
   1287             raise SelectionError("Unknown selection token: '{0}'".format(op))
   1288         except ValueError as e:
-> 1289             raise SelectionError("Selection failed: '{0}'".format(e))
   1290 
   1291 

SelectionError: Selection failed: 'Unexpected token 'None''
```
### Currently version of MDAnalysis:
0.18.0

**Comment by xiki-tempula** [comment]
Thanks for reporting. From a glance, it seems that there might be some problem with the selection string.
Would you mind try.
```python
u.select_atoms('type 7')
u.select_atoms('type 13')
u.select_atoms('type 1 and type 2')
```
To see if any of them gives some error?

Furthermore, when you are using a non-standard forcefield, you will need to set the hydrogen bond donors and hydrogen bond acceptors explicitly. An example can be seen here.

```python
class WaterBridgeAnalysis_OtherFF(WaterBridgeAnalysis):
      DEFAULT_DONORS = {"OtherFF": tuple(set([...]))}
      DEFAULT_ACCEPTORS = {"OtherFF": tuple(set([...]))}
w = mda.analysis.hbonds.WaterBridgeAnalysis_OtherFF(u, selection1='type 7', selection2='type 13',
water_selection='type 1 and type 2', forcefield='OtherFF')
```

**Comment by farshadsm** [comment]
Hi Xiki,

Thanks for your response. It didn't work out. I got the following error.
The problem is that my data file and trajectory are LAMMPS datafile and DCD
file while both WaterBridgeAnalysis and HydrogenBondAnalysis modules are
developed based on Gromacs file formats. My trajectory file doesn't have
any atom names. So, I can't pass donor atomgroups in the format of
'protein' and 'resname HOH' for selection1 and selection2 arguments. So,
what could be the solution?

Best,

Farshad

---------------------------------------------------------------------------AttributeError
                           Traceback (most recent call
last)<ipython-input-11-c2d186dbcc2b> in <module>()      3
                               u.select_atoms('type 13'),      4
                                      u.select_atoms('type 1 and type
2'),----> 5
forcefield='other')~/anaconda/lib/python3.4/site-packages/MDAnalysis/analysis/hbonds/wbridge_analysis.py
in __init__(self, universe, selection1, selection2, water_selection,
selection1_type, update_selection1, update_selection2,
update_water_selection, filter_first, distance_type, distance, angle,
forcefield, donors, acceptors, start, stop, step, debug, verbose)
449             distance_type=distance_type, distance=distance,
angle=angle,    450             forcefield=forcefield, donors=donors,
acceptors=acceptors,--> 451             start=start, stop=stop,
step=step, debug=debug, verbose=verbose)    452
self._update_water_selection()    453
~/anaconda/lib/python3.4/site-packages/MDAnalysis/analysis/hbonds/hbond_analysis.py
in __init__(self, universe, selection1, selection2, selection1_type,
update_selection1, update_selection2, filter_first, distance_type,
distance, angle, forcefield, donors, acceptors, start, stop, step,
debug, detect_hydrogens, verbose, pbc)    608     609
self.debug = True  # always enable debug output for initial selection
update--> 610         self._update_selection_1()    611
self._update_selection_2()    612         # per-frame debugging
output?
~/anaconda/lib/python3.4/site-packages/MDAnalysis/analysis/hbonds/wbridge_analysis.py
in _update_selection_1(self)    471     472     def
_update_selection_1(self):--> 473         self._s1 =
self.u.select_atoms(self.selection1)    474         self._s2 =
self.u.select_atoms(self.selection2)    475         if
self.filter_first and self._s1:
~/anaconda/lib/python3.4/site-packages/MDAnalysis/core/universe.py in
select_atoms(self, *args, **kwargs)    653
:meth:`MDAnalysis.core.groups.AtomGroup.select_atoms`    654
"""--> 655         return self.atoms.select_atoms(*args, **kwargs)
656     657     @property
~/anaconda/lib/python3.4/site-packages/MDAnalysis/core/groups.py in
select_atoms(self, sel, *othersel, **selgroups)   2065
sel_strs = (sel,) + othersel   2066         selections =
tuple((selection.Parser.parse(s, selgroups)-> 2067
        for s in sel_strs))   2068         if updating:   2069
    atomgrp = UpdatingAtomGroup(self, selections, sel_strs)
~/anaconda/lib/python3.4/site-packages/MDAnalysis/core/groups.py in
<genexpr>(.0)   2065         sel_strs = (sel,) + othersel   2066
  selections = tuple((selection.Parser.parse(s, selgroups)-> 2067
                       for s in sel_strs))   2068         if updating:
  2069             atomgrp = UpdatingAtomGroup(self, selections,
sel_strs)
~/anaconda/lib/python3.4/site-packages/MDAnalysis/core/selection.py in
parse(self, selectstr, selgroups)   1255         self.selectstr =
selectstr   1256         self.selgroups = selgroups-> 1257
tokens = selectstr.replace('(', ' ( ').replace(')', ' ) ')   1258
   self.tokens = collections.deque(tokens.split() + [None])   1259
    parsetree = self.parse_expression(0)
~/anaconda/lib/python3.4/site-packages/MDAnalysis/core/groups.py in
__getattr__(self, attr)   1615                 pass   1616
raise AttributeError("{cls} has no attribute {attr}".format(-> 1617
         cls=self.__class__.__name__, attr=attr))   1618    1619
def __reduce__(self):
AttributeError: AtomGroup has no attribute replace

**Comment by orbeckst** [comment]
> I got the following error.

What is the error?

**Comment by jbarnoud** [comment]
The error message was hidden as quote from the earlier email. I edited @farshadsm message so that the traceback is visible, but I cannot have it nicely formated.

**Comment by richardjgowers** [comment]
the selection `type 1 and type 2` isn't doing what you think it should.  That's asking for atoms that are **both** type 1 and type 2, which is probably impossible.  I think you mean to say `type 1 or type 2` (or `type 1 2` as shorthand)

**Comment by sohagb** [comment]
During Hydrogen bond auto-correlation function calculation of water, how to define O of H2O is double donor ?

**Comment by richardjgowers** [comment]
I think this is the `type 1 and type 2` causing an empty group, which is then causing the selection string building to generate an empty string, see #2112.
