### ISSUE TITLE
Error in hydrogen bond autocorrelation

### ISSUE THREAD

**Issue by farshadsm** [MDAnalysis/mdanalysis#1920]
Hello,

I get following error when I run the code given at the end of my email that I run to get Hydrogen Autocorrelation Function (ACF) for water molecules in their first solvation shell around a solid surface. 

The problem is with the following part of my code that select atoms with "Updating=True" argument. My code runs successfully when I select atoms in static mode. But, calculating Hydrogen ACF with static selection of atoms is not a correct approach as atoms move in and out of solvation shell throughout the trajectory frames. What should I do?

Best,

Farshad 

```
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-14-0031cc4bfa91> in <module>()
      2             hydrogens = h_first_sh, donors = donor_first_sh, bond_type='continuous',
      3             sample_time = 100, nruns = 50, nsamples = 50)
----> 4 hb_ac.run()
      5 hb_ac.solve()

~/anaconda/lib/python3.4/site-packages/MDAnalysis/analysis/hbonds/hbond_autocorrel.py in run(self, force)
    313 
    314             # needed else trj seek thinks a np.int64 isn't an int?
--> 315             results = self._single_run(int(start), int(stop))
    316 
    317             nresults = len(results)

~/anaconda/lib/python3.4/site-packages/MDAnalysis/analysis/hbonds/hbond_autocorrel.py in _single_run(self, start, stop)
    364             box = self.u.dimensions if self.pbc else None
    365 
--> 366             d = calc_bonds(self.h.positions[hidx], self.a.positions[aidx],
    367                            box=box)
    368             a = calc_angles(self.d.positions[hidx], self.h.positions[hidx],

IndexError: index 79 is out of bounds for axis 0 with size 78
```

## My code 

```python
import numpy as np
import MDAnalysis as mda
from MDAnalysis.core.groups import AtomGroup
from MDAnalysis.analysis import hbonds

mda.core.flags['use_periodic_selections'] = True
mda.core.flags['use_KDTree_routines'] = False

u = mda.Universe(coord_file, traj_files, dt=1.0)      
                 
### all hydrogen atoms in water
wh_all = u.select_atoms("type 1")

### all oxygen atoms in water
wo_all = u.select_atoms("type 2")

### first solvation shell
first_solvation = ("prop z < 8.0")  

### selecting hydrogen in first solvation shell
h_first_sh = wh_all.select_atoms(first_solvation)

### selecting donor atoms in first solvation shell
donor_first_sh = h_first_sh.select_atoms('bonded type 1')

### selecting acceptor atoms in first solvation shell
acceptor_first_sh = wo_all.select_atoms(first_solvation)

hb_ac = hbonds.HydrogenBondAutoCorrel(u, acceptors = acceptor_first_sh,
            hydrogens = h_first_sh, donors = donor_first_sh, bond_type='continuous',
            sample_time = 100, nruns = 50, nsamples = 50)
hb_ac.run()
hb_ac.solve()
```

**Comment by richardjgowers** [comment]
I think ACF predates dynamic groups.  Seeing as the correlation is tracked over time, it probably doesn't handle that the groups representing the hydrogen bonds you're watching have changed in size.  This is essentially adding more criteria to the lifetimes you're tracking, and it's not clear what should happen.

What you could do is first screen the atoms for who is inside your shells for all timesteps, then only pass in atoms which remain inside these shells:
```python
# make a dynamic selection
shell1_dynamic = u.select_atoms('prop z < 8.0', updating=True)
# create a static copy of the first frame of this dynamic selection
shell1 = shell1_dynamic.atoms

for ts in u.trajectory:
    # update shell1 to only include atoms in both shell1 and shell1_dynamic
    shell1 &= shell1_dynamic

```

For a longer trajectory where the solvation shells will change often you'd need to be able to tell `HydrogenBondAutocorrel` how to slice the trajectory, and this isn't currently possible.

So I'm not sure this is really possible without hacking the code a lot.

**Comment by richardjgowers** [comment]
I don't this will or should fix, if you want to do something like this, filter the atoms first into a regular AtomGroup then pass this into the analysis tool.

**Comment by omkantnirala** [comment]
Hi, 
Can anyone tell me that what is relation between sample_time and nsamples in MDAnalysis?

Thanks
