### ISSUE TITLE
GSD & Windows

### ISSUE THREAD

**Issue by richardjgowers** [MDAnalysis/mdanalysis#1923]
See #1914 

TODO: Add nice handling of GSD under Windows

**Comment by tylerjereddy** [comment]
The GSD maintainer [responded](https://bitbucket.org/glotzer/gsd/issues/18/windows-compatibility) -- basically, if we want GSD to be compatible with windows, we'll have to add the support ourselves.

**Comment by richardjgowers** [comment]
Cool thanks @bdice !
