### ISSUE TITLE
No module named duecredit

### ISSUE THREAD

**Issue by Ash1000** [MDAnalysis/mdanalysis#1925]
Hi everyone, I am unable to successfully run MDAnalysis. I was informed last time, that the following issue will be fixed in coming release. I apologize for asking here, but would someone like to inform me that when the updated MDAnalaysis version is expected to release?

/home/ash/.local/lib/python2.7/site-packages/MDAnalysis/due.py:88: UserWarning: No module named duecredit
  warnings.warn(str(err))

**Comment by kain88-de** [comment]
This is only a warning and you should still be able to use MDAnalysis. Yes the warning is annoying but again you should still be able to use MDAnalysis normally.

**Comment by orbeckst** [comment]
And if you don't want to see the warning, install duecredit:
```
pip install duecredit
```

Closed as duplicate of #1872

**Comment by orbeckst** [comment]
>  I am unable to successfully run MDAnalysis

Just to double check: What other indications (besides the duecredit warning) do you have that MDAnalysis is not working properly?

Did you [run the tests](https://github.com/MDAnalysis/mdanalysis/wiki/UnitTests#users)?

**Comment by orbeckst** [comment]
No more information, closing.
