### ISSUE TITLE
alignto changes all coordiantes in universe

### ISSUE THREAD

**Issue by kain88-de** [MDAnalysis/mdanalysis#1927]
### Expected behaviour

If I use `alignto(mobile, ref)` and both are atomgroups that do not contain all atoms in the attached universes than the atom positions not in the atomgroup are unchanged. 

### Actual behaviour

all atoms in the attached universes are updated.

### Code to reproduce the behaviour

https://gist.github.com/kain88-de/1a44037f00f1008c2b88cb5ecb30b207

```python
from MDAnalysisTests.datafiles import PDB, XTC
import MDAnalysis as mda
from MDAnalysis.analysis import align, rms

u = mda.Universe(PDB, XTC)
ref = mda.Universe(PDB)

#Make the selections for alignment

ref_res1 = ref.residues[1].atoms
res1 = u.residues[1].atoms

res1 = u.residues[1].atoms
res2 = u.residues[2].atoms

#Now we establish some the coordiantes before the alignment

u.trajectory[8]
print(res1.centroid())
print(res2.centroid())
print(ref_res1.centroid())

align.alignto(res1, ref_res1)

#The  centroid of res2 has changed as well. According to the docs these coordinates shouldn't have been updated.

print(res2.centroid())
```

### Currently version of MDAnalysis:
(run `python -c "import MDAnalysis as mda; print(mda.__version__)"`)
dev

**Comment by orbeckst** [comment]
My expectation of `alignto()` is the one that it exhibits: always rotate the whole system. This is also the [documented behavior](https://www.mdanalysis.org/mdanalysis/documentation_pages/analysis/align.html?highlight=alignto#MDAnalysis.analysis.align.alignto). If you want to just move `mobile`, use `subselection=mobile`.

**Comment by kain88-de** [comment]
yes you are right. I overlooked that part.
