### ISSUE TITLE
Density grid does not span the whole simulation box

### ISSUE THREAD

**Issue by Jezabel-Boni** [MDAnalysis/mdanalysis#1928]
### Expected behaviour
It would be good to implement these things in the density calculation function:
1. Have a way to calculate density that spans whole simulation box.
2. Have a consistent grid to compare densities of different species within a simulation.

### Actual behaviour
The density is calculated only between the min/max coordinates of the current selection, leading to different grids sizes for each selection.

### Code to reproduce the behaviour

``` python
import numpy as np
import MDAnalysis as MDA
import MDAnalysis.analysis.density as MDA_Density

topfile='drop_10ns.gro'
trjfile='drop_10ns_trimmed.xtc'

u = MDA.Universe(topfile, trjfile)

cl_density_object = MDA_Density.density_from_Universe(u, delta=5.0, atomselection="name CL")
na_density_object = MDA_Density.density_from_Universe(u, delta=5.0, atomselection="name NA")
h2o_density_object = MDA_Density.density_from_Universe(u, delta=5.0, atomselection="name OW")

print (cl_density_object) >>  <Density density with (39, 36, 12) bins>
print (na_density_object) >>  <Density density with (39, 37, 11) bins>
print (h2o_density_object) >>  <Density density with (41, 39, 29) bins>

....

```

### Currently version of MDAnalysis:
MDAnalysis 0.18.0 

See also discussion https://groups.google.com/d/msg/mdnalysis-discussion/Ypl-26z-zzk/67e80b2cAQAJ

**Comment by IAlibay** [comment]
So a few months ago I was working on the latter half of this issue as I wanted to generate equivalent grid density sizes for a set simulations of different ligands in a binding site.

My eventual fix for this was just to implement a user defined grid with a set origin + box edges. A copy of the code can be found here:

https://github.com/IAlibay/mdanalysis/blob/FixDensityBox/package/MDAnalysis/analysis/density.py

The changes are minimal, if it is of interest to others I can do a PR for it.

Unfortunately I'm not sure this addresses the first part of this issue, unless one was to define a set grid that is greater than all simulation boxes of interest?

**Comment by orbeckst** [comment]
PR is very welcome, even if it only addresses part of the issue.

> Have a way to calculate density that spans whole simulation box.

You can analyze the box for the whole trajectory first (costly but doable):
```python
largest_box = u.trajectory.dimensions.copy()
for ts in u.trajectory:
   box = ts.dimensions
   largest_box = make_larger_box(box, largest_box)
```

where `make_larger_box(box1, box2)` has to be a function that creates the box that envelopes `box1` and `box2` – trivial for orthorhombic boxes, a bit more tricky for triclinic ones.

However, given that the current density calculation uses an orthorhombic container anyway, `make_larger_box()` might start out pretty simple.

**Comment by orbeckst** [comment]
@Shabi-akireisa have you tried out the user-definable grid that was added with PR #2005 and does it address your problem?

**Comment by Shabi-akireisa** [comment]
I have not had the chance to test the PR #2005, as I have temporarily solved the issue by modifying the density function as suggested in the google groups in this thread, https://groups.google.com/forum/#!searchin/mdnalysis-discussion/density%7Csort:date/mdnalysis-discussion/Ypl-26z-zzk/wVuzpehAAAAJ

Just to clarify, I am the same person who initially asked about this in the Google Groups, and opened this issue here on github as per your suggestion there, to better keep track of the issue. Sorry for the confusion!

**Comment by orbeckst** [comment]
It seems that #2005 mostly addressed the issue here.
