### ISSUE TITLE
SingleFrameReaderBase.rewind is broken

### ISSUE THREAD

**Issue by richardjgowers** [MDAnalysis/mdanalysis#1929]
### Expected behaviour

Should reread positions from file, resetting them

### Actual behaviour

Does nothing (ie if I play with positions, my changes should be erased)

### Currently version of MDAnalysis:
(run `python -c "import MDAnalysis as mda; print(mda.__version__)"`)

**Comment by davidercruz** [comment]
I have pushed a fix to #1902 as it is related to the transformations API. the `rewind` method not only needs to re-read the file, but also update the timestep with the auxiliary data (besides the transformations)

**Comment by davidercruz** [comment]
#1902 has been merged so we can consider this issue closed, right?

**Comment by richardjgowers** [comment]
yep
