### ISSUE TITLE
Overwriting the pqr output format

### ISSUE THREAD

**Issue by xiki-tempula** [MDAnalysis/mdanalysis#1935]
I'm interested in changing the pqr output format. I wonder if there is an easy way of overwriting the existing default output format without editing the source code directly?
A scenario would be that by default the pqr writes 4 digits in the charge field. However, in gromacs, for example, the charge is represented in 5 decimal places. Thus, if I open a gromacs topology file and try to write out as pqr file. The overall charge won't be an integer because the last digit has been truncated. 

I'm interested in an interface like this.
``` python
import MDAnalysis as mda
from MDAnalysis.coordinates.PQR import PQRWriter
class PQRWriter(PQRWriter):
    fmt_ATOM = ("ATOM {serial:6d} {name:<4} {resname:<3} {chainid:1.1}"
                "{resid:4d}    {pos[0]:-8.3f}{pos[1]:-8.3f}"
                "{pos[2]:-8.3f} {charge:-8.5f} {radius:6.4f}\n")

u = mda.Universe(top)
u.atoms.write(pqr)
```

### Currently version of MDAnalysis:
py36/mda0.18.1

**Comment by richardjgowers** [comment]
@xiki-tempula what you're proposing nearly works already, you just need to add in `format='PQR'` again to overwrite the old Writer :)

```python
In [1]: import MDAnalysis as mda
u =
In [2]: u = mda.Universe('protein.pdb')

In [3]: mda.Writer('out.pqr')
Out[3]: < PQRWriter 'out.pqr' >

In [4]: mda.Writer('out.pqr').__class__
Out[4]: MDAnalysis.coordinates.PQR.PQRWriter

In [5]: oldcls = mda.Writer('out.pqr').__class__

In [9]: class NewPQRWriter(oldcls):
   ...:     format='PQR'
   ...:     fmt_ATOM = 'X' + oldcls.fmt_ATOM```

**Comment by xiki-tempula** [comment]
@richardjgowers Thank you for advice. I guess the `format='PQR'` is the key to register a new writer.

**Comment by richardjgowers** [comment]
@xiki-tempula yeah there's a [bunch of weird meta programming](https://github.com/MDAnalysis/mdanalysis/blob/develop/package/MDAnalysis/coordinates/base.py#L1820) which makes Readers/Writers get registered on the creation of the class, but it is designed to allow external code to add new Readers/Writers just like this

**Comment by xiki-tempula** [comment]
@richardjgowers Thank you for the explanation. I saw that 'format' is the trigger of class registration.
