### ISSUE TITLE
topologyobjects.Angle does not know about the periodic boundaries nor is this behaviour documented

### ISSUE THREAD

**Issue by matsikora** [MDAnalysis/mdanalysis#1938]
### Expected behaviour
topologyobjects.Angle.angle (and probably dihedral as well) should have a "box" option to allow for correct calculation of angles when contributing atoms cross periodic boundaries. Analogous to  lib.distances.calc_angles().

### Actual behaviour
angle function is not aware of PBC and this behaviour is not documented.

### Currently version of MDAnalysis:
0.17.0

**Comment by orbeckst** [comment]
@richardjgowers I assigned to you as you're working on PR #1939 already
