### ISSUE TITLE
Wrong format of PDB "MODEL" record

### ISSUE THREAD

**Issue by ymwangg** [MDAnalysis/mdanalysis#1950]
### Expected behaviour
It seems that the 'mda.Writer' writes the pdb model number to a slightly wrong position.
From the pdb website (http://www.wwpdb.org/documentation/file-format-content/format33/sect9.html#MODEL): 

COLUMNS        DATA  TYPE    FIELD          DEFINITION
 1 -  6        Record name   "MODEL "
11 - 14        Integer       serial         Model serial number.
### Actual behaviour
```
HEADER    
TITLE     MDANALYSIS FRAMES FROM 0, SKIP 1: Created by PDBWriter
REMARK     THIS IS A SIMULATION BOX
CRYST1   80.017   80.017   80.017  60.00  60.00  90.00 P 1           1     
123456789012345
MODEL         1     
ATOM      1  N   MET S   1      52.017  43.560  31.555  1.00  0.00      SYST N
```
The mda.Writer writes the model number up to column 15. This could cause Chimera to read the wrong models.

### Code to reproduce the behaviour

``` python
import MDAnalysis as mda
import MDAnalysisTests as test
from MDAnalysisTests.datafiles import PDB
u = mda.Universe(PDB)
fh = mda.Writer("tmp.pdb")
fh.write(u)
fh.write(u)
fh.close()
....

```

### Currently version of MDAnalysis:
0.18.0
(run `python -c "import MDAnalysis as mda; print(mda.__version__)"`)

**Comment by orbeckst** [comment]
@ymwangg many thanks for filing such a detailed and concise issue report! Much appreciated.

This issue should now be fixed in the development branch and in the upcoming 0.19.0 release.
