### ISSUE TITLE
resid selection

### ISSUE THREAD

**Issue by shozebhaider** [MDAnalysis/mdanalysis#1958]
Hi, Can any one tell me the md analysis syntax to pick every third CA atom. For example in VMD this command is (residue % 3 == 1) and (name CA)

### Currently version of MDAnalysis: 0.16
(run `python -c "import MDAnalysis as mda; print(mda.__version__)"`)

**Comment by orbeckst** [comment]
Hi @shozebhaider ,

You can't do it with the selection language itself easily (but see below if you have to) but it is easy to slice an AtomGroup in any imaginable way.

I have two nice solutions for you. 
- VMD-like
- Python/numpy array slicing

For the example code I first execute

```python
>>> import MDAnalysis as mda; from MDAnalysis.tests.datafiles import TPR, XTC
>>> u = mda.Universe(TPR, XTC)

>>> # select all protein CA
>>> CA = u.select_atoms("protein and name CA")

and get a AtomGroup `CA` with _all_ CA atoms.

### VMD-like
If you want to directly replicate the VMD selection, which works with the resids then you can do the following:
```python
CA3 = CA[CA.resids % 3 == 1]

>>> print(repr(CA), repr(CA3))
<AtomGroup with 214 atoms> <AtomGroup with 71 atoms>
```
Here `CA.resids % 3 == 1` generates a boolean array that is `True` when `resid % 3 == 1` and `False` otherwise. Using the boolean array for "fancy indexing" gives you your new AtomGroup.

Just be careful with `resids % 3 == 1`: the resids in MDAnalysis start at 0 so this gives you the second, the fifth, etc CA. If you want the first, the fourth, ... then use `resids % 3 == 0`. 

You can also check if your actual residue numbers are available as `CA.resnums` – MDAnalysis stores residue numbers provided in the topology in resnums, while resids are the MDAnalysis-internal 0-based numbers.


### Python/numpy array slicing
Assuming you want the first, fourth, seventh... :
```python
>>> # make AtomGroup with every 3rd one
>>> CA3 = CA[::3]

>>> print(repr(CA), repr(CA3))
<AtomGroup with 214 atoms> <AtomGroup with 72 atoms>
```

The new AtomGroup `CA3` contains every third CA atom (I am just printing the first few atoms here):
```python
>>> print(CA3[:3])
<AtomGroup [
   <Atom 5: CA of type opls_293B of resname MET, resid 0 and segid seg_0_AKeco>, 
   <Atom 65: CA of type opls_224B of resname ILE, resid 3 and segid seg_0_AKeco>, 
   <Atom 122: CA of type opls_223B of resname GLY, resid 6 and segid seg_0_AKeco>]>

>>> print(CA[:7])
<AtomGroup [
   <Atom 5: CA of type opls_293B of resname MET, resid 0 and segid seg_0_AKeco>, 
   <Atom 22: CA of type opls_224B of resname ARG, resid 1 and segid seg_0_AKeco>, 
   <Atom 46: CA of type opls_224B of resname ILE, resid 2 and segid seg_0_AKeco>, 
   <Atom 65: CA of type opls_224B of resname ILE, resid 3 and segid seg_0_AKeco>, 
   <Atom 84: CA of type opls_224B of resname LEU, resid 4 and segid seg_0_AKeco>, 
   <Atom 103: CA of type opls_224B of resname LEU, resid 5 and segid seg_0_AKeco>, 
   <Atom 122: CA of type opls_223B of resname GLY, resid 6 and segid seg_0_AKeco>]>
```

### Selection string
If you *must* provide a selection (e.g., because the code/function only takes selection strings and not AtomGroups), then you can build a selection string on the fly. It's not pretty but should work.

First get `CA3` by either method above and then use the `bynum` selection:
```python
>>> selection_string = "bynum " + " ".join((CA3.indices + 1).astype(str))

>>> print(selection_string)
bynum 22 84 129 160 199 237 284 335 385 435 479 515 568 616 645 686 735 788 827 875 917 967 1015 1068 1121 1165 1214 1260 1298 1356 1403 1442 1491 1523 1572 1621 1675 1717 1763 1810 1869 1924 1966 1999 2060 2115 2162 2215 2259 2299 2335 2383 2443 2484 2528 2590 2649 2702 2750 2793 2840 2894 2934 2965 3022 3070 3103 3155 3196 3242 3298
```

Test that this works:
```
>>> CA.select_atoms(selection_string) == CA3
True
```

(Note that `bynum` considers indices starting at 1 but internally indices start at 0... that's a bit of a historical issue and we'll probably add another selection keyword such as `index` that selects by index...)

**Comment by shozebhaider** [comment]
Thank you Oli. This helped a lot. 
@orbeckst
