### ISSUE TITLE
add index selection keyword

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/mdanalysis#1959]
### Expected behaviour
The [selection language](https://www.mdanalysis.org/docs/documentation_pages/selections.html) should allow me to use the output from `AtomGroup.indices` for selections, which are the *0-based indices*.

### Actual behaviour
Only [`bynum`](https://www.mdanalysis.org/docs/documentation_pages/selections.html#index) is implemented as a selection keyword for indices. It uses *1-based* indices. 

### Code to reproduce the behaviour
See https://github.com/MDAnalysis/mdanalysis/issues/1958#issuecomment-400804285.

### Proposed solution
Implement a new selection keyword `index` that does the same as `bynum` but for 0-based indices.

### Currently version of MDAnalysis:
(run `python -c "import MDAnalysis as mda; print(mda.__version__)"`)
develop

**Comment by IAlibay** [comment]
Hi,

Apologies for digging up an old issue, but I was wondering if implementing this was still of interest?
I've been running a custom version of MDAnalysis with this implemented (same behaviour as bynum but -1) and have been finding it quite useful.

**Comment by orbeckst** [comment]
Yes, still of interest.

(Most old issues are just old because there's precious little time to work on them.)
