### ISSUE TITLE
BUG (windows): cutil dtype

### ISSUE THREAD

**Issue by tylerjereddy** [MDAnalysis/mdanalysis#1962]
I'm getting a few extra test failures locally for Windows 10 native that seem related to a relatively new-looking module:

```
MDAnalysis\lib\_cutil.pyx:33: ValueError
```

Looks like there's some fragility to the dtype specification for the argument there, and while appveyor seems happy with it I guess, I'm seeing buffer dtype mismatches locally.

I guess this is mostly a bookmark for myself; might be tricky to write tests to prevent "regression" if appveyor is happy as is. May not hurt to switch the syntax used to the newer / preferred typed memoryviews in any case since the older buffer stuff is used in that file at the moment.

**Comment by tylerjereddy** [comment]
This is showing up on recent PRs now too, so 30 failures there and locally on windows.

**Comment by jbarnoud** [comment]
I see two solutions : use some cython merged types in unique_int_1d or make sure we always use int64 for indices. I prefer the later but I may not realize the implications.

**Comment by richardjgowers** [comment]
We should strictly type what our indices are throughout the package, but it also wouldn't hurt to use a fused type for the function too.  So both of @jbarnoud 's suggestions are good
