### ISSUE TITLE
TXYZ Arc file parse fails, doesn't recognize periodic boundary box definition

### ISSUE THREAD

**Issue by Dariusrussellkish** [MDAnalysis/mdanalysis#2001]
### Expected behaviour
Parse Tinker Archive file into a Universe

### Actual behaviour
Error on parsing, fails to parse periodic boundary box produced by Tinker on line 2 of each frame. 

103
    10.000000   10.000000   10.000000   90.000000   90.000000   90.000000
     1  OH    -4.258215   -1.973780    0.949736  1232     2    10
     2  CT    -4.263714   -1.766981    2.353863  1063     1     3    11    12
     3  CT    -2.868573   -1.546285    2.893741  1066     2     4     6    13
     4  OS    -2.130847   -2.679206    2.594471  1068     3     5
     5  CT    -0.793726   -2.351497    2.219711  1069     4     7    14    18

### Code to reproduce the behaviour
[hexanes_arc.zip](https://github.com/MDAnalysis/mdanalysis/files/2215812/hexanes_arc.zip)
``` python
import MDAnalysis as mda

u = mda.Universe(top)

....

```

### Currently version of MDAnalysis:
0.18.0

**Comment by richardjgowers** [comment]
Hi @Dariusrussellkish thanks for reporting this

https://dasher.wustl.edu/tinker/distribution/source/prtxyz.f

It looks like tinker only writes the box in a periodic simulation, so there'll have to be some if statements to see what sort of archive/txyz file this is

**Comment by orbeckst** [comment]
I label this as a bug because not detecting PBC in an MD format is not good.
