### ISSUE TITLE
remove untested lib.mdamath.one_to_many_pointers() function

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/mdanalysis#2010]
**Expected behavior**

Code in `lib/mdamath.py` should be used elsewhere in MDAnalysis or at least be tested if it is considered generally useful.

**Actual behavior**

The `lib.mdamath.one_to_many_pointers` function 
https://github.com/MDAnalysis/mdanalysis/blob/461aadf6733d234e0913bae774a6312a208ede27/package/MDAnalysis/lib/mdamath.py#L253  is not used anywhere (`git grep one_to_many_pointers` shows nothing else) and it is not covered by tests, as shown by https://codecov.io/gh/MDAnalysis/mdanalysis/src/461aadf6733d234e0913bae774a6312a208ede27/package/MDAnalysis/lib/mdamath.py#L253

**Currently version of MDAnalysis**

Latest develop (0.18.1-dev).

**Comment by orbeckst** [comment]
@richardjgowers I think [you added this function](https://github.com/MDAnalysis/mdanalysis/blame/461aadf6733d234e0913bae774a6312a208ede27/package/MDAnalysis/lib/mdamath.py#L253). Is there a good reason for still having it?

**Comment by orbeckst** [comment]
This is a cheap way to increase coverage :-).

**Comment by richardjgowers** [comment]
I think this got replaced by `squash_by` which is a little more powerful, so yeah we can ditch this.
