### ISSUE TITLE
make_whole from MDAnalysis.lib.mdamath fails to make the molecule whole 

### ISSUE THREAD

**Issue by bieniekmateusz** [MDAnalysis/mdanalysis#2026]
**Expected behavior**
The selected protein should not be crossing PBC. 

**Actual behavior**
The protein is broken in pieces after using make_whole. 

``` python
import MDAnalysis as mda
u=mda.Universe('npt2us.tpr', 'test.gro')
from MDAnalysis.lib.mdamath import make_whole
make_whole(u.select_atoms('protein'))
u.atoms.write('whole_prot.gro')
```

- MDAnalysis 0.18.0
- Python 2.7.15
- Arch
[makewhole.zip](https://github.com/MDAnalysis/mdanalysis/files/2260569/makewhole.zip)

**Comment by richardjgowers** [comment]
Hey @bieniekmateusz 

So I tried this on 0.18.0 and I can confirm it doesn't work correctly, but I tried it on the latest develop and it seems to work now  (the function has been rewritten in C++, so it also works faster).  So can you check to see if develop works for you?

**Comment by bieniekmateusz** [comment]
Thanks @richardjgowers, just tested on my simulation and it is working fine in the develop branch. Next time I'll check that before posting. Thanks!
