### ISSUE TITLE
altloc selection is not documented

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/mdanalysis#2030]
**Expected behavior**

The [docs on selections](https://www.mdanalysis.org/mdanalysis/documentation_pages/selections.html) should list all supported selection keywords.

**Actual behavior**

`altloc` is not documented.

**Currently version of MDAnalysis**

current develop, 0.18.1-dev

**Comment by orbeckst** [comment]
@hfmull I raised the issue – feel free to grab it.

**Comment by orbeckst** [comment]
It would be a good idea to check that we are documenting all keywords for which we have Selections https://github.com/MDAnalysis/mdanalysis/blob/e2c2b560fd198558a1be797e2dda06e968b449f4/package/MDAnalysis/core/selection.py#L173

**Comment by richardjgowers** [comment]
we've got documentation for selections in two places:

A docs page

https://github.com/MDAnalysis/mdanalysis/blob/develop/package/doc/sphinx/source/documentation_pages/selections.rst

And the docstring for `select_atoms` (which also gets turned into a docs page too)

https://github.com/MDAnalysis/mdanalysis/blob/develop/package/MDAnalysis/core/groups.py#L2117
