### ISSUE TITLE
test_authors.py requires otherwise useless testsuite/__init__.py

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/mdanalysis#2040]
**Expected behavior**

The top-level `testsuite` directory should not contain a `__init__.py` file that marks it as a module.

**Actual behavior**

Removing the file (in 7361a02  in PR #2036 ) broke Travis CI tests, specifically, `test_authors.py`.

```
____________________________ test_testsuite_authors ____________________________
[gw1] linux -- Python 3.5.5 /home/travis/miniconda/envs/test/bin/python
    def test_testsuite_authors():
        from MDAnalysisTests import __authors__
>       assert len(__authors__) > 0, 'Could not find the list of authors'
E       AssertionError: Could not find the list of authors
E       assert 0 > 0
E        +  where 0 = len([])
testsuite/MDAnalysisTests/utils/test_authors.py:33: AssertionError
```

On Appveyor, the tests pass, possibly because we actually properly install the testsuite, as said by https://github.com/MDAnalysis/mdanalysis/pull/2036#issuecomment-411958359

**Code to reproduce the behavior**

See Travis [job #496.1 failed](https://travis-ci.com/MDAnalysis/mdanalysis/jobs/139235902#L3345)

**Currently version of MDAnalysis**

current develop 0.18.1-dev on Travis CI

**Comment by orbeckst** [comment]
Should we maintain the separate *testsuite/AUTHORS* file? I doubt that it is complete;
```bash
git log --format="%an,%ae,%cd" --date="format:%Y"  testsuite/ | sort -t"," -k 3nr | sort -t "," -k 1,2  | uniq
```
gives names that are not in AUTHORS. Unlike the main *package/AUTHORS*, we have been pretty lax with reminding new authors to add themselves to the file. I also don't see the tests as separate from the library itself.

The main justification for a separate AUTHORS file was that we are distributing the tests as a separate package *MDAnalysisTests* so we want to put proper acknowledgements in there. However, we could easily just use the same list as for the *MDAnalysis* package. Or we could generate it from `git` (possibly using a mailcap file to translate names... but then we have to maintain the mailcap file and who wants to do that??)

**Comment by richardjgowers** [comment]
Yeah I don’t see the point in the separate list, the different packages are just a packaging thing.  I’d also merge the CHANGELOG if I could too...

**Comment by orbeckst** [comment]
Yes, we used to record changes to the test infrastructure in *testsuite/CHANGELOG* and that made some sense. However, it remains a source of confusion for everyone and I admit that there's not good reason not to record these things in the *package/CHANGELOG*.

@richardjgowers do you want to open an issue with a proposed solution? [You have my sword... and my bow... and my axe](https://www.youtube.com/watch?v=hyquiA8RL1Q).

**Comment by orbeckst** [comment]
My current understanding of the weird stuff happening here is the following:
1. When I delete `MDAnalysisTests/authors.py`,  which is generated by `setup.py` and _not version controlled_ then the tests for the test authors fails because it is missing the `authors.py` file. The error message is confusing but it's obvious what happens.
2. When `testsuite/__init__.py` is present, the `pytest` imports `testsuite` as a module, finds `setup.py` and thinks it's a package-level setup fixture thingy, which runs _on import_ the code to generate `authors.py`. Thus, the tests pass.
3. On Travis we only `pip install testsuite/` which does not put the `authors.py` file into the checked out sources. However, we _do not use the installed tests_, only the checked-out sources. Thus, without being able to import `testsuite/setup.py`, we don't generate `authors.py` and Travis fails.

(Note on debugging: I put `assert False` in the `testsuite/__init__.py` to see when it would be called... and it was imported by `pytest`.)

It is wrong to run the package installation `setup.py` for any side-effects related to tests. For this reason alone, `testsuite/__init.py__` must go.

To solve the other issues I can do one of the following
1. run `(cd testsuite && python setup.py build)` instead of the confusing `pip install testsuite/` in Travis CI
2. commit `authors.py` to the repo (but we don't like committing generated files)
3. run the `setup.dynamic_author_list()` code as part of the tests somehow (but this is confusing because the test code should be independent of any package data files) 

I find 1. the least insane so I'll do that. Please comment/review.
