### ISSUE TITLE
AttributeError: 'module' object has no attribute 'WaterBridgeAnalysis'

### ISSUE THREAD

**Issue by xdeupi** [MDAnalysis/mdanalysis#2064]
Hi all,
I cannot use the WaterBridgeAnalysis class in the hydrogen bond analysis module. When I execute the following script

```
import MDAnalysis
import MDAnalysis.analysis.hbonds
u = MDAnalysis.Universe('step5_assembly.xplor_ext_JSR.psf', 'runMD500ns_stride50.dcd')
w = MDAnalysis.analysis.hbonds.WaterBridgeAnalysis(u, 'resname ARG', 'resname ASP')
w.run()

```

I get:
> AttributeError: 'module' object has no attribute 'WaterBridgeAnalysis'

I can use other classes in the module (e.g. HydrogenBondAnalysis), and I do see all the necessary source files in my distribution (I installed MDAnalysis 0.18.0-py2.7 in Mac OS 10.13.6 using Conda).

Any ideas?

Thanks,

Xavier

**Comment by richardjgowers** [comment]
Hey Xavier,

I think you'lll find that at `MDAnalysis.analysis.hbonds.wbridge_analysis.WaterBridgeAnalysis`, does that work for you?

**Comment by orbeckst** [comment]
Is `MDAnalysis.analysis.hbonds.WaterBridgeAnalysis` documented to work? Yes, at https://www.mdanalysis.org/mdanalysis/documentation_pages/analysis/wbridge_analysis.html#how-to-perform-waterbridgeanalysis and given that we also import into the `hbonds` namespace  https://github.com/MDAnalysis/mdanalysis/blob/cd58ce0797b466d3a584beda765b58abce7f9ec2/package/MDAnalysis/analysis/hbonds/__init__.py#L24  we should also import the `wbridge_analysis` ones
