### ISSUE TITLE
Rename capped_distance to capped_distance_array

### ISSUE THREAD

**Issue by richardjgowers** [MDAnalysis/mdanalysis#2065]
This is something that I should have brought up in the initial PR, but I think it'd be clearer if `capped_distance` (@ayushsuhane 's new fast distance function) was called `capped_distance_array` to make its relationship to `distance_array` clearer.  (Also `self_` variations)

If we change it now it's never been released into the wild, so no deps etc...

Thoughts?

**Comment by orbeckst** [comment]
Now or never!

**Comment by jbarnoud** [comment]
If I am not mistaken, `capped_distance` does not return an array of distances that is similar ro `distance_array`. Having too similar names may be confusing when the similarity of the outputs is not there.

**Comment by richardjgowers** [comment]
@jbarnoud correct.  But we could also change the output to a sparse array too (if that would also be a more expected API).  I just remembered we have scipy as a dependency now..

**Comment by jbarnoud** [comment]
I am really not sure about changing the output. In many cases, we mostly 
care about the pairs rather than the actual distances.

**Comment by zemanj** [comment]
@jbarnoud I second that. What about having two functions, one called `find_pairs` and one called `capped_distance_array`... that's what the grid search does after all if I'm not mistaken.

**Comment by ayushsuhane** [comment]
For me, the primary role of capped distance is to find the pairs within the cutoff. The distances are just some extra information about the list of pairs i.e. we cannot access the information about the pairs from the distances alone. As @zemanj  suggested, if we want to go for two different functions, probably sparse matrix could be a way to go. The question though is "Is that necessary?" The argument being,  we have to calculate the pairs anyhow using  ``capped_distance`` (or ``find_pairs``)  even for ``capped_distance_array``. Also if there are two different functions and we donot want to calculate the distances twice (once to find the pairs and another during the function call to second function). 

I would want to structure the ``if...else..`` loop around return_distances argument though. And probably figure out a way to return either pairs, distances, or both depending on the function's requirement.

As far as the name is concerned, I feel if we want to make it similar to distance_array, we should change the return parameter to a  sparse array of distances and leave the pairs out (but again the matrices can go very large in size, I am not sure how scipy handles it)

**Comment by richardjgowers** [comment]
Ok I'm convinced this is not necessary as it doesn't return an array, nor should it because sometimes you only want the pair indices
