### ISSUE TITLE
can not install on Python 3.6.6

### ISSUE THREAD

**Issue by HoxinhLuo** [MDAnalysis/mdanalysis#2075]
There are many errors while installing it on Python 3.6.6.

1.     
    cl: 命令行 warning D9002 :忽略未知选项“-std=c99”
    cl: 命令行 warning D9002 :忽略未知选项“-ffast-math”
    cl: 命令行 warning D9002 :忽略未知选项“-O3”
    cl: 命令行 warning D9002 :忽略未知选项“-funroll-loops”

2. 
    MDAnalysis/lib/c_distances.c(2656): warning C4244: “=”: 从“npy_intp”转换到“int”，可能丢失数据
    MDAnalysis/lib/c_distances.c(2665): warning C4244: “=”: 从“npy_intp”转换到“int”，可能丢失数据
    MDAnalysis/lib/c_distances.c(2805): warning C4244: “=”: 从“npy_intp”转换到“int”，可能丢失数据
    MDAnalysis/lib/c_distances.c(2814): warning C4244: “=”: 从“npy_intp”转换到“int”，可能丢失数据
    MDAnalysis/lib/c_distances.c(2954): warning C4244: “=”: 从“npy_intp”转换到“int”，可能丢失数据
    MDAnalysis/lib/c_distances.c(2963): warning C4244: “=”: 从“npy_intp”转换到“int”，可能丢失数据
    MDAnalysis/lib/c_distances.c(3079): warning C4244: “=”: 从“npy_intp”转换到“int”，可能丢失数据
    MDAnalysis/lib/c_distances.c(3216): warning C4244: “=”: 从“npy_intp”转换到“int”，可能丢失数据
    MDAnalysis/lib/c_distances.c(3353): warning C4244: “=”: 从“npy_intp”转换到“int”，可能丢失数据
    MDAnalysis/lib/c_distances.c(3477): warning C4244: “=”: 从“npy_intp”转换到“int”，可能丢失数据
    MDAnalysis/lib/c_distances.c(3604): warning C4244: “=”: 从“npy_intp”转换到“int”，可能丢失数据
    MDAnalysis/lib/c_distances.c(3743): warning C4244: “=”: 从“npy_intp”转换到“int”，可能丢失数据
    MDAnalysis/lib/c_distances.c(3882): warning C4244: “=”: 从“npy_intp”转换到“int”，可能丢失数据
    MDAnalysis/lib/c_distances.c(4021): warning C4244: “=”: 从“npy_intp”转换到“int”，可能丢失数据
    MDAnalysis/lib/c_distances.c(4172): warning C4244: “=”: 从“npy_intp”转换到“int”，可能丢失数据
    MDAnalysis/lib/c_distances.c(4323): warning C4244: “=”: 从“npy_intp”转换到“int”，可能丢失数据
    MDAnalysis/lib/c_distances.c(4474): warning C4244: “=”: 从“npy_intp”转换到“int”，可能丢失数据
    MDAnalysis/lib/c_distances.c(4637): warning C4244: “=”: 从“npy_intp”转换到“int”，可能丢失数据
    MDAnalysis/lib/c_distances.c(4800): warning C4244: “=”: 从“npy_intp”转换到“int”，可能丢失数据
    MDAnalysis/lib/c_distances.c(4927): warning C4244: “=”: 从“npy_intp”转换到“int”，可能丢失数据
    MDAnalysis/lib/c_distances.c(5054): warning C4244: “=”: 从“npy_intp”转换到“int”，可能丢失数据
    MDAnalysis/lib/c_distances.c(5206): warning C4244: “=”: 从“Py_ssize_t”转换到“int”，可能丢失数据
    MDAnalysis/lib/c_distances.c(5571): warning C4244: “=”: 从“Py_ssize_t”转换到“int”，可能丢失数据
3.  
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.15.26726\bin\HostX86\x64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:d:\installer\anaconda3\libs /LIBPATH:d:\installer\anaconda3\PCbuild\amd64 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.15.26726\ATLMFC\lib\x64" "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.15.26726\lib\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\lib\um\x64" "/LIBPATH:D:\Windows Kits\10\lib\10.0.17134.0\ucrt\x64" "/LIBPATH:D:\Windows Kits\10\lib\10.0.17134.0\um\x64" m.lib /EXPORT:PyInit_c_distances build\temp.win-amd64-3.6\Release\MDAnalysis/lib/c_distances.obj /OUT:build\lib.win-amd64-3.6\MDAnalysis\lib\c_distances.cp36-win_amd64.pyd /IMPLIB:build\temp.win-amd64-3.6\Release\MDAnalysis/lib\c_distances.cp36-win_amd64.lib
    LINK : fatal error LNK1181: 无法打开输入文件“m.lib”
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\VC\\Tools\\MSVC\\14.15.26726\\bin\\HostX86\\x64\\link.exe' failed with exit status 1181
4. 
   Command "d:\installer\anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\25772\\AppData\\Local\\Temp\\pip-install-zdft0lss\\MDAnalysis\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\25772\AppData\Local\Temp\pip-record-f5dy2xmv\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\25772\AppData\Local\Temp\pip-install-zdft0lss\MDAnalysis\

**Comment by kain88-de** [comment]
This looks like you are trying to install MDAnalysis on windows. We currently don't support windows.  There has been some progress made by @tylerjereddy to get functioning windows builds. We appreciate if you can help.

**Comment by orbeckst** [comment]
See also https://github.com/MDAnalysis/mdanalysis/wiki/MDAnalysis-on-Windows – in any case, also show the commands that you use to install. 

I am not sure what goes wrong here
```
LINK : fatal error LNK1181: 无法打开输入文件“m.lib”
```
([translation](https://translate.google.com/#auto/en/LINK%20%3A%20fatal%20error%20LNK1181%3A%20%E6%97%A0%E6%B3%95%E6%89%93%E5%BC%80%E8%BE%93%E5%85%A5%E6%96%87%E4%BB%B6%E2%80%9Cm.lib%E2%80%9D)) It should try to link `libm`, at least that's what happens on Linux/macOS. Perhaps linking works differently on Windows. @tylerjereddy might know more

**Comment by tylerjereddy** [comment]
Windows shouldn't try to link `m.lib`; that's one of the first things I fixed in the effort to support windows, so my initial suspicion is that an older version of MDA is being used here.

It would be helpful to include version of MDA and commands used, as noted above.

You can find the source code that switches off `m.lib` on the windows platform (and an explanatory comment)  here: https://github.com/MDAnalysis/mdanalysis/blob/develop/package/setup.py#L300

**Comment by orbeckst** [comment]
@HoxinhLuo can you provide more feedback? We cannot help without more information. We will close this issue in the next 3 days if there is no more activity.

**Comment by orbeckst** [comment]
We cannot really do more here without more information so I will close. If the problem persists, please comment here and we will re-open. Thanks.
