### ISSUE TITLE
DummyReader should be convertable to a MemoryReader

### ISSUE THREAD

**Issue by kain88-de** [MDAnalysis/mdanalysis#2077]
**Is your feature request related to a problem? Please describe.**

I would like to create a dummy universe with a trajectory attached. I can create the dummy universe. I do not know how I load a numpy array as a trajectory into it.

This would work nicely as a feature with our new trajectory writer shortcut. 

**Describe the solution you'd like**

```python
u = mda.Universe.empty(2, trajectory=True)
# shape is (n_frames, n_atoms, 3)
u.trajectory.add_coordinates(np.ones((100, 2, 3))
```

**Describe alternatives you've considered**
I could load a file from the test trajectories.

**Comment by orbeckst** [comment]
Can you do a `u.transfer_to_memory()`?

**Comment by kain88-de** [comment]
If iteration won't work then `transfer_to_memory` won't work either. It
iterates over  a trajectory.

**Comment by richardjgowers** [comment]
Related to #2076 we should just nuke dummyreader and replace with memory
