### ISSUE TITLE
ProgressMeter doesn't work in jupyter lab

### ISSUE THREAD

**Issue by kain88-de** [MDAnalysis/mdanalysis#2078]
**Expected behavior**

A progress meter works the same in a jupyter lab environment and an ipython terminal.

**Actual behavior**
![screenshot from 2018-09-18 15-16-55](https://user-images.githubusercontent.com/4302678/45690177-075e4400-bb56-11e8-8638-f1e1d4146f9c.png)

**Currently version of MDAnalysis**

- Which version are you using? (run `python -c "import MDAnalysis as mda; print(mda.__version__)"`) 0.18.0
- Which version of Python (`python -V`)? 3.6
- Which operating system? Linux

**Comment by orbeckst** [comment]
Is JupyterLab different from a Jupyter notebook? It used to work in the latter, didn't it?

**Comment by kain88-de** [comment]
Jupyter lab is the *next* interface for notebooks. It's more of an IDE then
the normal notebooks. It is a good bit different on the javascript side
though. So things are not 100% compatible between them. The tqdm package
works as expected though.

**Comment by IAlibay** [comment]
So had a look at this as a nice excuse to wrap my head around the progress meter. It looks like Jupyter Lab doesn't like progress meter formatting assigned by the RMSD class. In particular, it breaks on the use of `\r` in `"{step:5d}/{numsteps}  [{percentage:5.1f}%]\r"` (line 607).

Removing it seems to fix this issue:

![image](https://user-images.githubusercontent.com/12460125/45765384-db61c200-bc2c-11e8-9f59-d00a1c937ab9.png)

This would explain why the progress meter for u.transfer_to_memory() works properly.

Within analysis, it looks this will also affect density_from_Universe (checked), helanal_trajectory, PCA, HydorgenBondAnalysis, HydrogenBondAutoCorrel, and WaterBridgeAnalysis.

I have tested removing the extra carriage return on RMSD and density_from_Universe, and (on python3) it looks like it works fine across jupyterlab, ipython and standard python calls.

**Comment by kain88-de** [comment]
That is great. Can you create a PR with the fix?

**Comment by IAlibay** [comment]
@kain88-de Will do, I'm still trying to work out if anything outside analysis is affected but I'll create the PR once I'm done (and tested on p2.7).

**Comment by orbeckst** [comment]
@jbarnoud 's PR #960 is still hanging somewhere in limbo.

I also only recently discovered [tqdm](https://pypi.org/project/tqdm/) (which probably everyone else already knows...) and we could also think about adapting it instead of our home-grown approach. It works in notebooks and is a light-weight dependency.

**Comment by IAlibay** [comment]
Just as an update on the original fix for this, I did have most of this fixed (I think I'm missing a test for some helanal changes related to #2084), just ended up getting distracted with other work. Sorry about that. I'll try to open the PR for it over the next few days.

**Comment by orbeckst** [comment]
Update: In #928 we decided to transition to **tqdm** as progress meter. This might eventually solve this problem (although see https://github.com/MDAnalysis/mdanalysis/pull/960#issuecomment-484990143 on tqdm in Jupyter Lab).

In the meantime. PR #2310 should at least help.

**Comment by mquevill** [comment]
This issue is fixed with #2617 (after running the extra commands in https://github.com/MDAnalysis/mdanalysis/pull/2617#issuecomment-598263187).

**Comment by IAlibay** [comment]
I've closed the issue here, but I'm going to open a new one in the user guide. We'll probably want to document the extra steps somewhere.
