### ISSUE TITLE
accessing the timestep attributes within the _single_frame function of analysis base class

### ISSUE THREAD

**Issue by xiki-tempula** [MDAnalysis/mdanalysis#2086]
I'm interested in moving the water bridge analysis to the new analysis base class.
However, in the documentation, I cannot find how to access the attributes of the timestep with the _single_frame function. 
```python
for progress, ts in enumerate(self.u.trajectory[self.start:self.stop:self.step]):
    frame = ts.frame
```
Which is the ts.frame in this loop.

**Comment by orbeckst** [comment]
`self._ts` – see the code for https://github.com/MDAnalysis/mdanalysis/blob/edb1643c0a78f7e5447aa3ccc02712e4205ff073/package/MDAnalysis/analysis/base.py#L170
