### ISSUE TITLE
Importing GRO_MEPROT from MDAnalysisTests fails

### ISSUE THREAD

**Issue by iparask** [MDAnalysis/mdanalysis#2088]
**Expected behavior**
I am trying to import `GRO_MEMPROT` and `XTC_MEMPORT` and the expected behavior is that the interpreter loads the actual files.

**Actual behavior**
I failed with a `cannot import` error. The trace is:

```
Python 2.7.15 |Anaconda, Inc.| (default, Sep 27 2018, 20:19:23)
Type "copyright", "credits" or "license" for more information.

IPython 5.8.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: from MDAnalysisTests.datafiles import GRO_MEMPROT, XTC_MEMPROT
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-53788bf097c9> in <module>()
----> 1 from MDAnalysisTests.datafiles import GRO_MEMPROT, XTC_MEMPROT

ImportError: cannot import name GRO_MEMPROT
```
**Code to reproduce the behavior**

```python
from MDAnalysisTests.datafiles import GRO_MEMPROT, XTC_MEMPROT
``````

**Currently version of MDAnalysis**
- Which version are you using? (run `python -c "import MDAnalysis as mda; print(mda.__version__)"`)
0.18.0
- Which version of Python (`python -V`)?\
Python 2.7.15 :: Anaconda, Inc.
- Which operating system?
Ubuntu Xenial kernel over Windows.

**Comment by orbeckst** [comment]
This is in the development version only, will be in release 0.19.0.

**Comment by iparask** [comment]
Thank you! I will install the develop branch locally! I am closing this issue
