### ISSUE TITLE
IO error when loading a pdb string

### ISSUE THREAD

**Issue by xiki-tempula** [MDAnalysis/mdanalysis#2089]
**Expected behavior**
I'm trying to load a pdb string
```python
from six import StringIO
import MDAnalysis as mda
pdb = '''
ATOM      1  N   LEU     1      32.310  13.778  14.372  1.00  0.00      SYST N 0
ATOM      2  OW  SOL     2       3.024   4.456   4.147  1.00  0.00      SYST H 0'''
u = mda.Universe(StringIO(pdb), format="pdb")
```
I would expect this code to not trigger any error/.

**Actual behavior**

```
Exception ignored in: <bound method ReaderBase.__del__ of <PDBReader None with 1 frames of 2 atoms>>
Traceback (most recent call last):
  File "~//Documents/GitHub/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2083, in __del__
  File "~//Documents/GitHub/mdanalysis/package/MDAnalysis/coordinates/PDB.py", line 415, in close
  File "~/Documents/GitHub/mdanalysis/package/MDAnalysis/lib/util.py", line 720, in close
  File "~Documents/GitHub/mdanalysis/package/MDAnalysis/lib/util.py", line 662, in reset
ValueError: I/O operation on closed file
```

**Currently version of MDAnalysis**
The mda version is the one which I pulled from develop this Monday
py version is py36
system is osx

**Comment by richardjgowers** [comment]
@xiki-tempula I ran the above without errors.

It looks like the error occurs in the deletion of the object, which shouldn't be a problem (it happens silently in the background).  How are you getting this error to happen?

**Comment by xiki-tempula** [comment]
@richardjgowers when I'm testing the water bridge analysis against the hydrogen bond analysis unit test, I noticed this problem. The exception is ignored which result in the normal termination of the test.
It seems that on my computer the above six lines are sufficient to reproduce the problem.

**Comment by xiki-tempula** [comment]
@orbeckst Thank you for the testing. It's not currently causing any problem that I'm aware of. Since I haven't seen this problem in the previous versions, I thought it will be nice to have it logged.

**Comment by kaplajon** [comment]
I get similar exceptions when the Universe is created from a NamedStream. Here we have flush instead of a seek though. A little bit annoying, since I loop over many pdb streams, and the error clutters my terminal. 

```
Exception ignored in: <bound method ReaderBase.__del__ of <PDBReader r.pdb with 1 frames of 68737 atoms>>
Traceback (most recent call last):
  File "/Users/jon/Library/Python/3.5/lib/python/site-packages/MDAnalysis/coordinates/base.py", line 2105, in __del__
    self.close()
  File "/Users/jon/Library/Python/3.5/lib/python/site-packages/MDAnalysis/coordinates/PDB.py", line 411, in close
    self._pdbfile.close()
  File "/Users/jon/Library/Python/3.5/lib/python/site-packages/MDAnalysis/lib/util.py", line 734, in close
    self.flush()
  File "/Users/jon/Library/Python/3.5/lib/python/site-packages/MDAnalysis/lib/util.py", line 840, in flush
    return self.stream.flush()
ValueError: I/O operation on closed file.
```
MacOS 10.12.6, Python 3.5.7, MDA 0.19.2 (installed with pip).

**Comment by orbeckst** [comment]
@kaplajon thanks for the feedback.

**Comment by satary** [comment]
@xiki-tempula 
Weirdly if you wrap your stream into named stream there won't be any warnings:
```
from io import StringIO
import MDAnalysis as mda
from MDAnalysis.lib.util import NamedStream
pdb = '''
ATOM      1  N   LEU     1      32.310  13.778  14.372  1.00  0.00      SYST N 0
ATOM      2  OW  SOL     2       3.024   4.456   4.147  1.00  0.00      SYST H 0'''
u = mda.Universe(NamedStream(StringIO(pdb), "temp.pdb")
```
Maybe usefull, otherwise I got thousands if warnings, which kills jupyter notebook frontend =)

**Comment by orbeckst** [comment]
@satary thanks for the workaround. This is actually the recommended use, according to https://www.mdanalysis.org/docs/documentation_pages/lib/util.html#streams . Are you using a more recent version than @kaplajon who said in https://github.com/MDAnalysis/mdanalysis/issues/2089#issuecomment-481578337 that `NamedStream`  leads to (ignored) ValueError?

(I consider the stream functionality somewhat experimental. It's a neat idea and works for many different things but there are some rough edges that spoil the user experience. We'd be very glad if someone would find the time to properly review (and possibly rework) that part of the code.)
