### ISSUE TITLE
Add return_distances kwarg to self_capped_distance

### ISSUE THREAD

**Issue by richardjgowers** [MDAnalysis/mdanalysis#2101]
The function `lib.distances.self_capped_distance` offers a quick way to evaluate pairwise distances within a set of coordinates.  This returns indices and distances of pairs of coordinates which are within a certain threshold.

Its partner function `lib.distances.capped_distance` does similar but between two arrays of coordinates.  This function has an optimisation that allows the distances to not be returned (kwarg `return_distances=False`)

TODO:
 - [ ] write tests
 - [ ] add `return_distances=False` to `self_capped_distance`
 - [ ] verify that this is faster

**Comment by zemanj** [comment]
**Performance report:**

Test code:
```python
from timeit import timeit
import MDAnalysis as mda
from MDAnalysis.lib.distances import self_capped_distance
u = mda.Universe("topol.tpr", "traj_comp.xtc")
ag = u.atoms
pos = ag.positions
r_cut = 10.0
print("atoms:", repr(ag))
print("box:", u.dimensions)
print("r_cut:", r_cut)

runtime = timeit(lambda: self_capped_distance(pos, r_cut), number=20) * 0.05
print("call: self_capped_distance(pos, r_cut)")
print("runtime: {:.3f} s".format(runtime))

try:
    runtime = timeit(lambda: self_capped_distance(pos, r_cut, return_distances=False), number=20) * 0.05
    print("call: self_capped_distance(pos, r_cut, return_distances=False)")
    print("runtime: {:.3f} s".format(runtime))
except:
    pass
```

Output before PR #2202:
```
#atoms: <AtomGroup with 15000 atoms>
#box: [55.5085 55.5085 55.5085 90.     90.     90.    ]
#r_cut: 10.0
#call: self_capped_distance(pos, r_cut)
#runtime: 1.682 s
```

Output after PR #2202:
```
#atoms: <AtomGroup with 15000 atoms>
#box: [55.5085 55.5085 55.5085 90.     90.     90.    ]
#r_cut: 10.0
#call: self_capped_distance(pos, r_cut)
#runtime: 1.663 s
#call: self_capped_distance(pos, r_cut, return_distances=False)
#runtime: 0.860 s
```

So, yes, not returning distances makes things faster (at least if the 'nsgrid' method is used).
