### ISSUE TITLE
Change analysis.distances.contact_matrix to use capped_distance

### ISSUE THREAD

**Issue by richardjgowers** [MDAnalysis/mdanalysis#2102]
So currently we have `contact_matrix`:
https://github.com/MDAnalysis/mdanalysis/blob/develop/package/MDAnalysis/analysis/distances.py#L59

Which finds all contacts within a certain distance and returns a sometimes sparse boolean array

This should use `lib.distances.self_capped_distance` so that it doesn't do the full `0.5 * N * (N-1)` search

Todo:
 - [ ] verify that this is faster
 - [ ] add benchmark to `benchmarks/` (will also be visible in the existing leaflet benchmark)
 - [ ] change `contact_matrix` to use `self_capped_distance`

**Comment by orbeckst** [comment]
our leafletfinder should also use it
