### ISSUE TITLE
Update HydrogenBondAutoCorrel to use capped_distance

### ISSUE THREAD

**Issue by richardjgowers** [MDAnalysis/mdanalysis#2103]
This line in `HydrogenBondAutoCorrel` could be replaced by `lib.distances.capped_distance` to make things faster!

https://github.com/MDAnalysis/mdanalysis/blob/develop/package/MDAnalysis/analysis/hbonds/hbond_autocorrel.py#L347

TODO:
 - [ ] check what tests are in place for this class in `testsuite/`
 - [ ] add a benchmark for the class in `benchmarks/`
 - [ ] make the switch from `distance_array` to `capped_distance_array`
 - [ ] check that exclusions (`exclusion_block`) are properly treated

**Comment by NinadBhat** [comment]
Hi,
I am new to MDAnalysis. Can I work on this bug?

**Comment by richardjgowers** [comment]
@NinadBhat sure
