### ISSUE TITLE
SWIG -> Cython rewrite of the XDRReader interface

### ISSUE THREAD

**Issue by GoogleCodeExporter** [MDAnalysis/mdanalysis#211]
Because Cython code is closer to Python than SWIG interfacing code, it is probably a good idea to port the current libxdr wrapping from SWIG to Cython.

Original issue reported on code.google.com by `sebastie...@gmail.com` on 5 Feb 2015 at 4:19
* Blocking: #132

**Comment by orbeckst** [comment]
#419 duplicated this issue but most of the discussion happened there (under @kain88-de 's leadership) so I am closing this older issue report.
