### ISSUE TITLE
hydrogen bond autocorrelation of water

### ISSUE THREAD

**Issue by sohagb** [MDAnalysis/mdanalysis#2111]
During Hydrogen bond auto-correlation function calculation of water, how to define O of H2O is double donor ?
Thank you!

**Comment by richardjgowers** [comment]
Hi, the issues tracker is for code development, I recommend you ask on the [user discussion group](http://users.mdanalysis.org), in particular I think this is answered here:

https://groups.google.com/d/msg/mdnalysis-discussion/Ju_VqtbOFZ8/kyiuWI9zBAAJ
