### ISSUE TITLE
Empty select_atoms string gives unhelpful error

### ISSUE THREAD

**Issue by richardjgowers** [MDAnalysis/mdanalysis#2112]
Calling `AtomGroup.select_atoms('')` gives: `SelectionError: Unknown selection token: 'None'`. 

Instead, an empty string should get caught and a better error message given (`'SelectionError: Empty string`)

NB: Seems trivial but calling with empty strings can happen when selection strings are generated algorithmically, eg #1919

**Comment by richardjgowers** [comment]
Maybe empty with warning?

**Comment by orbeckst** [comment]
That would be a compromise. One can set warnings to become exceptions for those people who'd like that behavior.
