### ISSUE TITLE
Skipping frames in hydrogen bond analysis does not work

### ISSUE THREAD

**Issue by aakognole** [MDAnalysis/mdanalysis#2119]
I am using `mdanalysis                0.18.0                   py27_0    conda-forge`

[HydrogenBondAnalysis.run()](https://www.mdanalysis.org/docs/documentation_pages/analysis/hbond_analysis.html#MDAnalysis.analysis.hbonds.hbond_analysis.HydrogenBondAnalysis.run)

I was trying to run hydrogen bond analysis over long trajectory and tried to use `h.run(step=10)` to skip frames, but it does not seem work. 
```
...
for resid in rna.residues.resids:
    h = MDAnalysis.analysis.hbonds.HydrogenBondAnalysis(u, 'nucleic and resid %d' % (resid), 'nucleic and not resid %d' % (resid), update_selection1=False, update_selection2=False, distance=2.5, angle=120.0, distance_type="hydrogen", donors=("N6", "N3", "N1", "N2", "N4", "O2'"), acceptors=("N1", "N7", "N3", "O4", "O2", "O6", "O4'"))
    h.run(step=10)
    h.generate_table()
    print h.table
    hblist = np.array(h.count_by_type())
```
I also tried it with your test data files which has 10 frames. I tried step=2 and step=5. I got the table showing the h-bonds in all the frames.

_Originally posted by @aakognole in https://github.com/MDAnalysis/mdanalysis/issues/1687#issuecomment-432309130_

**Comment by orbeckst** [comment]
Could you please
1. post the code that you used (that helps us a lot, then we don't have to guess what you did)
2. list the version of MDAnalysis that you are using? 

Thanks!

**Comment by richardjgowers** [comment]
I couldn't reproduce this locally on the dev branch

**Comment by orbeckst** [comment]
With the current develop (which should be equivalent to 0.19.0 in this respect) I also _cannot_ reproduce the problem:
```python
>>> import numpy as np
>>> import MDAnalysis as mda; from MDAnalysis.tests.datafiles import TPR, XTC
>>> import MDAnalysis.analysis.hbonds
>>> u = mda.Universe(TPR, XTC)
>>> h = MDAnalysis.analysis.hbonds.HydrogenBondAnalysis(u, 'protein', 'resname SOL')
>>> print(u.trajectory.n_frames)
10
>>> h.run(step=2)
>>> h.generate_table()
>>> print(h.timesteps)
[0.0, 200.00001525878906, 400.0000305175781, 600.0, 800.0000610351562]
>>> print(np.unique(h.table.time))
[  0.         200.00001526 400.00003052 600.         800.00006104]
>>> print([ts.time for ts in u.trajectory])
[0.0, 100.00000762939453, 200.00001525878906, 300.0, 400.0000305175781, 500.0000305175781, 600.0, 700.0000610351562, 800.0000610351562, 900.0000610351562]
```

So clearly only hydrogen bonds for every second frame were computed.

@aakognole you are using MDAnalysis 0.18.0. **Please try 0.19.0.** If the problem persists, please ask for this issue to be re-opened.
