### ISSUE TITLE
replace deprecated np.matrix operations with operations on np.arrays

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/mdanalysis#2122]
**Expected behavior**

No warnings regarding numpy use should be issued when using MDAnalysis.

**Actual behavior**

For example:
```
.../mdanalysis/package/MDAnalysis/analysis/align.py:288: PendingDeprecationWarning: the matrix subclass is not the recommended way to represent matrices or deal with linear algebra (see https://docs.scipy.org/doc/numpy/user/numpy-for-matlab-users.html). Please adjust your code to use regular ndarray.
```

**Code to reproduce the behavior**

```
pytest  MDAnalysisTests/analysis/test_align.py
```

**Currently version of MDAnalysis**

- Which version are you using? (run `python -c "import MDAnalysis as mda; print(mda.__version__)"`) 0.19.0-dev
- Which version of Python (`python -V`)? Python 3.6.6
- Which operating system? macOS

**Comment by kain88-de** [comment]
I would love to activate pytest to treat warnings as errors. Unfortunately, this will only work correctly once we remove python2.7 support. The warnings implementation has changed between the 2 and 3. It's much more predictable in python3.
