### ISSUE TITLE
PDBReader fails to read PDB file written from Windows

### ISSUE THREAD

**Issue by richardjgowers** [MDAnalysis/mdanalysis#2128]
Related to #2125 

PDB files written from Windows can't be read again, this gives:

```
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-2-b3a4175a284e> in <module>()
----> 1 u = mda.Universe('new.pdb')

~/code/mdanalysis/package/MDAnalysis/core/universe.py in __init__(self, *args, **kwargs)
    333                 coordinatefile = None
    334 
--> 335             self.load_new(coordinatefile, **kwargs)
    336             # parse transformations
    337             trans_arg = kwargs.pop('transformations', None)

~/code/mdanalysis/package/MDAnalysis/core/universe.py in load_new(self, filename, format, in_memory, **kwargs)
    600         kwargs['n_atoms'] = self.atoms.n_atoms
    601 
--> 602         self.trajectory = reader(filename, **kwargs)
    603         if self.trajectory.n_atoms != len(self.atoms):
    604             raise ValueError("The topology and {form} trajectory files don't"

~/code/mdanalysis/package/MDAnalysis/coordinates/PDB.py in __init__(self, filename, **kwargs)
    314         self.n_frames = len(offsets)
    315 
--> 316         self._read_frame(0)
    317 
    318     @staticmethod

~/code/mdanalysis/package/MDAnalysis/coordinates/PDB.py in _read_frame(self, frame)
    403                 try:
    404                     # does an implicit str -> float conversion
--> 405                     occupancy[pos] = line[54:60]
    406                 except ValueError:
    407                     # Be tolerant for ill-formated or empty occupancies

IndexError: index 10 is out of bounds for axis 0 with size 10
```

Even away from Windows.

**Currently version of MDAnalysis**

- Which version are you using? 0.19.1

**Comment by orbeckst** [comment]
Isn't there universal newline support [PEP 278](https://www.python.org/dev/peps/pep-0278/)?

**Comment by orbeckst** [comment]
Is `anyopen()` the ultimate problem?

**Comment by richardjgowers** [comment]
@orbeckst I uploaded a Windows PDB here: https://github.com/MDAnalysis/mdanalysis/issues/2125#issuecomment-433636475

I don't think it's `anyopen`, if I just use bare Python `open` it still fails.

I had some luck fixing this using `open(...., 'rb')` everywhere (ie treating it as a binary blob, so less assumptions are made about encoding/newline), but then I ran into some complications with stream reading

**Comment by orbeckst** [comment]
This has DOS line endings:
```
hexdump -C new.pdb | head -1
```
gives
```
00000000  48 45 41 44 45 52 20 20  20 20 0d 0a 54 49 54 4c  |HEADER    ..TITL|
```
where [ASCII codes](http://www.asciitable.com/) 0x0d == carriage return `\r` and 0x0a == line feed/newline `\n`.

**Comment by richardjgowers** [comment]
OK our PDBWriter writes with DOS line endings in Windows, so maybe we just have to fix **our** Writer..

Another interesting question is do other packages/sources also follow this rule?  Or will we encounter ascii (not just PDB!) files written from VMD/Avagadro/godknowswhat that our ascii Readers choke on because of this issue?

**Comment by orbeckst** [comment]
I often get PDB files from collaborators with DOS line endings, so it definitely happens in the wild, so I think we have to gracefully deal with it. 

If you were to open a PDB file with Unix line endings in a typical Windows text editor (people do this routinely) then it it would be a mess, I think, unless the editor is smart enough to convert.

Can't we use `open('wind.pdb', 'rU')` as in [PEP 278](https://www.python.org/dev/peps/pep-0278/)?

**Comment by orbeckst** [comment]
> OK our PDBWriter writes with DOS line endings in Windows, so maybe we just have to fix our Writer..

I _think_ it should continue to write DOS line endings. 

Have you tried loading a DOS-line endings PDB in VMD on (1) Windows (2) Unix-like?
