### ISSUE TITLE
Add forces and/or velocities to AtomGroup when TimeStep has no forces/velocities defined

### ISSUE THREAD

**Issue by GoogleCodeExporter** [MDAnalysis/mdanalysis#213]
What steps will reproduce the problem?
Load a CHARMM DCD trajectory
```python
u = MDAnalysis.Universe('a.psf', 'a.dcd')
a = u.selectAtoms('all')
a.set_forces(0.)
```

What is the expected output? What do you see instead?

Ideally, no output, simply that forces/velocities have been set. Instead, I receive the following error:

    NoDataError: Timestep does not contain forces

What version of the product are you using? On what operating system?
MDAnalysis 0.8.2dev

Please provide any additional information below.

Ideally, one could set forces/velocities and create a new trajectory or work with the current system instead of having multiple systems available.

Original issue reported on code.google.com by `tcthepoe...@gmail.com` on 10 Feb 2015 at 5:33
* Blocking: #221

**Comment by orbeckst** [comment]
Close with PR #346
