### ISSUE TITLE
Is it possible to create periodic bonds for a unit cell crystal using any MDAnalysis tool (meaning a set tool)? 

### ISSUE THREAD

**Issue by ananvodo** [MDAnalysis/mdanalysis#2147]
### Code to reproduce the behaviour

``` python
import MDAnalysis as mda

u = mda.Universe(top, trj)

....

```

### Currently version of MDAnalysis:
(run `python -c "import MDAnalysis as mda; print(mda.__version__)"`)

**Comment by orbeckst** [comment]
@ananvodo could you please ask your question on the mailing list https://groups.google.com/forum/#!forum/mdnalysis-discussion – we use the issue tracker for (1) bugs and (2) new features. 

Your question might turn into a new feature when it is clearer what you require.

P.S.: When you post to the mailing list for the first time, there will be a delay until your post appears (this is to prevent spam).
