### ISSUE TITLE
Failing Lint test

### ISSUE THREAD

**Issue by xiki-tempula** [MDAnalysis/mdanalysis#2148]
**Expected behavior**

I'm trying to merge a pull request to the develop branch #2087. However, the lint test is failing.

**Actual behavior**

************* Module MDAnalysis.due
package/MDAnalysis/due.py:37: [W0107(unnecessary-pass), InactiveDueCreditCollector._donothing] Unnecessary pass statement
package/MDAnalysis/due.py:53: [W0107(unnecessary-pass), _donothing_func] Unnecessary pass statement
************* Module MDAnalysis.coordinates.base
package/MDAnalysis/coordinates/base.py:1329: [W0107(unnecessary-pass), IOBase.close] Unnecessary pass statement
package/MDAnalysis/coordinates/base.py:1514: [W0107(unnecessary-pass), ProtoReader._reopen] Unnecessary pass statement
************* Module MDAnalysis.selections.base
package/MDAnalysis/selections/base.py:241: [W0107(unnecessary-pass), SelectionWriterBase._write_head] Unnecessary pass statement
package/MDAnalysis/selections/base.py:245: [W0107(unnecessary-pass), SelectionWriterBase._write_tail] Unnecessary pass statement
************* Module MDAnalysis.analysis.base
package/MDAnalysis/analysis/base.py:162: [W0107(unnecessary-pass), AnalysisBase._prepare] Unnecessary pass statement
package/MDAnalysis/analysis/base.py:169: [W0107(unnecessary-pass), AnalysisBase._conclude] Unnecessary pass statement
************* Module MDAnalysis.lib
package/MDAnalysis/lib/__init__.py:43: [W0406(import-self), ] Module import itself
************* Module MDAnalysis.lib.formats
package/MDAnalysis/lib/formats/__init__.py:24: [W0406(import-self), ] Module import itself
package/MDAnalysis/lib/formats/__init__.py:25: [W0406(import-self), ] Module import itself

**Code to reproduce the behavior**

``` python
cd mdanalysis
export  PYLINTRC="./package/.pylintrc" 
pylint package/MDAnalysis
pylint testsuite/MDAnalysisTests
```

**Currently version of MDAnalysis**

- Which version are you using? 0.19.3
- Which version of Python (`python -V`)? py35
- Which operating system? osx10.13.6

**Comment by kain88-de** [comment]
So I'm unable to understand why those errors appear. This looks like a regression in pylint to me. I would see to lower the pylint version on this.

**Comment by orbeckst** [comment]
You mean instead of whitelisting in PR #2149, just pin pylint? How does one do this again in our travis.yml file – `pylint` is installed via [ci-helpers](https://github.com/astropy/ci-helpers) so probably add
```yaml
PYLINT_VERSION=xxx
```
after https://github.com/MDAnalysis/mdanalysis/blob/aaf2f9a5cd7a21a3f58cb1e7f9f71ffc71281404/.travis.yml#L35 and where `xxx` is the previous version (which one)?

**Comment by zemanj** [comment]
@orbeckst pylint is installed automatically by ci-helpers if `$MAIN_CMD` starts with `pylint` (see [here](https://github.com/astropy/ci-helpers/blob/ebcc73dc4c946c761314b2d87aa4e28d633e21af/travis/setup_dependencies_common.sh#L250)). Currently, there exists no option to pin the pylint version AFAIK.
However, adding this functionality to ci-helpers should be rather trivial I guess.

**Comment by kain88-de** [comment]
The pass statements can be removed according to puking devs. They are a
real positive. Personally I like the having them in the code and disabling
the longer locally.

The self import looks like a real bug. We can deactivate it for the time
being. Should hopefully be fixed I’m a new version.

**Comment by zemanj** [comment]
@kain88-de puking devs ftw :rofl:

**Comment by kain88-de** [comment]
sounds good.
