### ISSUE TITLE
Minimum required information on Atoms

### ISSUE THREAD

**Issue by GoogleCodeExporter** [MDAnalysis/mdanalysis#215]
Going through all the topology readers made me notice that most formats provide  very different data, and MDA expects quite a lot of stuff.

The init for Atom currently looks like:
```python
 def __init__(self, number, name, type, resname, resid, segid, mass, charge, residue=None, segment=None, radius=None, bfactor=None, resnum=None, serial=None, altLoc=None):
```
So required fields are:
 * number
 * name
 * type
 * resname
 * resid
 * segid
 * mass
 * charge

It would be good to reduce the required fields, as far as I can see, the only really really, required field is the number?  If we only populate atoms with what is provided, and make any secondary data structures (fragments, residues, bonds) lazily built, it should make things more lightweight in many cases.

To change this, if we make Atom raise `NoDataErrors` and then anything that wants something (eg a Writer) can anticipate a `NoDataError` and fudge the value if necessary?  Maybe raising good warnings too, eg, "I wrote you a pdb but there were no masses, you can add masses with: atoms.masses =  ".

This is a pretty big change, so will likely get split up into many little issues.

Thoughts?

Original issue reported on code.google.com by `richardjgowers` on 12 Feb 2015 at 9:21
* Blocked on: #202

**Comment by richardjgowers** [comment]
I'm gonna drop this in favour of a more systematic approach to performance.
