### ISSUE TITLE
Unannounced deprecation in PKDTree.set_coords

### ISSUE THREAD

**Issue by kain88-de** [MDAnalysis/mdanalysis#2167]
**Expected behavior**

When no deprecation warning is given or documented an update of MDAnalysis from 0.18 to 0.19 does not break my code.  Especially when a parameter is defined and documented as optional I expect this to be the case.

**Actual behavior**

Default PKDTree behavior has changed. The same code now throws an [error](https://github.com/MDAnalysis/mdanalysis/blob/abcdb1e2423ee4714c5ce7b5ce3364778a5a02f7/package/MDAnalysis/lib/pkdtree.py#L132). It is not clear from the documentation why there is a default value and what it does.

**Code to reproduce the behavior**

Show us how to reproduce the failure. If you can, use trajectory files from the test data.

``` python
import MDAnalysis as mda
from MDAnalysis.tests.datafiles import PSF, DCD,  GRO, PDB, TPR, XTC, TRR,  PRMncdf, NCDF

u = mda.Universe(PSF, DCD)
kdt = PKDTree(u.atoms.dimensions)
kdt.set_coords(u.atoms.positions)
....

```

**Additional Information**

The deprecation was introduced in PR [#1990](https://github.com/MDAnalysis/mdanalysis/pull/1990/files#diff-08b446f64bc4574c8b9b7714e83ecfa1R90-R149). The ideal would be to restore the old behavior and have code guess a cutoff when `None` is given. A default here could be the minimal distance between image centers given the box.

**Currently version of MDAnalysis**

Conda Version: 0.19.2-py27hfc679d8_0

**Comment by kain88-de** [comment]
It used to be OK to give an array of shape (3,) as a box. This will fail with the current version. Unfortunately, the check for the shape of the box happens lower in the call-stack (lib.distances). Did we ever have the assumption for lib.distances that a (3,) box is rectangular shaped (i.e. alpha=0, beta=0, gamma=0)?

**Comment by orbeckst** [comment]
Also, `RuntimeError` for a missing `cutoff` seems to be the wrong kind of error, this should be a `ValueError`. But in any case, optional kwargs need to be optional.

**Comment by zemanj** [comment]
Shouldn't it be possible for `PKDTree` to determine the maximum possible cutoff from the box dimensions and proceed from there?

**Comment by kain88-de** [comment]
yeah the PKDtree should be able to do that.

**Comment by orbeckst** [comment]
Closing as this is sooooo outdated.
