### ISSUE TITLE
Add "same" keyword to selections

### ISSUE THREAD

**Issue by GoogleCodeExporter** [MDAnalysis/mdanalysis#217]
I've split this out from another issue, #190 

  Finally to avoid this `fragment` class being useful only when wrapping systems, I also added the `same` keyword into selections. This way one could, e.g., select whole lipid molecules using something like `segid DMPC and same fragment as around 3.5 protein`, or the complete protein residues that are in contact with water using `protein and same residue as around 3 resname TIP3`.

https://code.google.com/p/mdanalysis-caio/source/detail?r=3f1f6c938186758eb0ece0
734a3e2f8cb8a98b84

The coding for the issue has been done, but it needs checking over and unit 
tests.

Original issue reported on code.google.com by `richardjgowers` on 16 Feb 2015 at 1:28

**Comment by richardjgowers** [comment]
I don't really understand the selection system well enough to do this one.

**Comment by orbeckst** [comment]
@mnmelo can you have a look at this, given that you have recently worked on the selections?

**Comment by mnmelo** [comment]
No problem; assign it to me.

**Comment by mnmelo** [comment]
Guys, I also added caio s. souza as a contributor in the CHANGELOG, since much of the code was his. If you'd rather acknowledge the contribution differently let me know and I'll change it.

**Comment by orbeckst** [comment]
@mnmelo : Adding Caio S Souza to CHANGELOG is good (I couldn't find him on GitHub so I don't know which handle he'd go by). Also add him to AUTHORS and in the docs in the authors list in [sphinx/source/conf.py](https://github.com/MDAnalysis/mdanalysis/blob/develop/package/doc/sphinx/source/conf.py#L88).

When I integrate someone else's code I set them as the author of the commit:

     git commit --author="A. U. Thor <author@example.com>" ....

If you want to do this you can quickly rewrite history with

     git commit --author="A. U. Thor <author@example.com>" --amend -C HEAD
     git push -f origin develop

(Yes, forced pushs are a no-no but we'll probably survibe this one....)

You can decide if you want to do this or not, it really depends on how much you did in the commit. You still show up as the committer.

**Comment by orbeckst** [comment]
@mnmelo can you please add a unit test? This is crucial for any commits to the core.
When done, close the issue.

Thanks!

**Comment by mnmelo** [comment]
I did ;)
They cover some of the possible cases. In particular, the "same fragment as ...".

**Comment by orbeckst** [comment]
@mnmelo did you push the tests? – I don't see a commit including tests – that's why I mentioned it in the first place.

**Comment by mnmelo** [comment]
Now that's puzzling! Maybe I only staged the package subdir. In any case, I was already going to amend that commit ;)

**Comment by mnmelo** [comment]
Yup, that was it. All should be fine now, I hope.
