### ISSUE TITLE
Travis build fails on macos with python 2.7

### ISSUE THREAD

**Issue by jbarnoud** [MDAnalysis/mdanalysis#2180]
**Expected behavior**

TravisCI can build MDAnalysis for all tested OS and python versions.

**Actual behavior**

The MacOS build on python 2.7 fails to compile. After a diff between travis's logs on python 3.6 (which succeeds) and travis's logs on python 2.7 (which fails), therelevant error seems to be:

* On failing python 2.7 (<https://travis-ci.org/MDAnalysis/mdanalysis/jobs/481760970#L2180>)

```
g++ -bundle -undefined dynamic_lookup -L/Users/travis/miniconda/envs/test/lib -arch x86_64 -arch x86_64 build/temp.macosx-10.6-x86_64-2.7/MDAnalysis/lib/_cutil.o -L/Users/travis/miniconda/envs/test/lib -lm -o build/lib.macosx-10.6-x86_64-2.7/MDAnalysis/lib/_cutil.so -stdlib=libc++

clang: error: invalid deployment target for -stdlib=libc++ (requires OS X 10.7 or later)

error: command 'g++' failed with exit status 1
```

* On succeeding python 3.6 (<https://travis-ci.org/MDAnalysis/mdanalysis/jobs/481760969#L2219>)

```
g++ -bundle -undefined dynamic_lookup -L/Users/travis/miniconda/envs/test/lib -arch x86_64 -L/Users/travis/miniconda/envs/test/lib -arch x86_64 -arch x86_64 build/temp.macosx-10.7-x86_64-3.6/MDAnalysis/lib/_cutil.o -lm -o build/lib.macosx-10.7-x86_64-3.6/MDAnalysis/lib/_cutil.cpython-36m-darwin.so -stdlib=libc++

ld: warning: object file (build/temp.macosx-10.7-x86_64-3.6/MDAnalysis/lib/_cutil.o) was built for newer OSX version (10.9) than being linked (10.7)
```

The issue is likely related to #2162 and #2163

**Code to reproduce the behavior**

Problem occurs on travisCI builds, see links above. It would probably occur on non-travis MacOS build but I do not have a system to test it.

**Currently version of MDAnalysis**

0.19.3-dev 2bb0aa72c733793a05084dd45afcde3b8e485c02

**Comment by richardjgowers** [comment]
This looks like it's caused by #2144

**Comment by zemanj** [comment]
Quote from the clang manual pages:

> MACOSX_DEPLOYMENT_TARGET
>
>    If -mmacosx-version-min is unspecified, the default deployment target is read from this environment variable. This option only affects Darwin targets.

So, in principle, setting `MACOSX_DEPLOYMENT_TARGET` or supplying `-mmacosx-version-min` should be equivalent.

We explicitly specify `-mmacosx-version-min=10.9` for compiling, but *not* for linking.
Maybe we could have solved the problem in `setup.py` by specifying
```Python
cpp_extra_link_args.append('-mmacosx-version-min=10.7')
```
