### ISSUE TITLE
MMTF parser expects optional fields

### ISSUE THREAD

**Issue by speleo3** [MDAnalysis/mdanalysis#2193]
**Expected behavior**

When importing MMTF files, MDAnalysis only requires fields which are labeled as "Required" in the [MMTF spec](https://github.com/rcsb/mmtf/blob/v1.0/spec.md#fields).

**Actual behavior**

MDAnalysis fails with omitted optional fields. E.g. a file with missing `altLocList`:

```python
>>> u = MDAnalysis.Universe('no-alt-loc.mmtf')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../MDAnalysis/core/universe.py", line 312, in __init__
    self._generate_from_topology()
  File ".../MDAnalysis/core/universe.py", line 367, in _generate_from_topology
    self._process_attr(attr)
  File ".../MDAnalysis/core/universe.py", line 896, in _process_attr
    m=len(attr)))
ValueError: Length of altLocs does not match number of atoms.
Expect: 660 Have: 0
```

**Code to reproduce the behavior**

``` python
import MDAnalysis
import msgpack

with open('1ubq.mmtf', 'rb') as f:
    d = msgpack.unpack(f, encoding='utf-8')

del d['altLocList']

with open('no-alt-loc.mmtf', 'wb') as f:
    msgpack.pack(d, f, use_bin_type=True)

u = MDAnalysis.Universe('no-alt-loc.mmtf')
```

**Currently version of MDAnalysis**
```bash
# python -c "import MDAnalysis as mda; print(mda.__version__)"
0.19.2
# python -V
Python 3.7.2
# uname -a
Linux 4.20.4-arch1-1-ARCH #1 SMP PREEMPT Wed Jan 23 00:12:22 UTC 2019 x86_64 GNU/Linux
```

**Comment by richardjgowers** [comment]
@speleo3 thanks for the detailed report, it makes fixing it very easy for me!

**Comment by richardjgowers** [comment]
Ok I had a little trouble reproducing this, the pdb doesn't seem to host the mmtf for 1ubq: https://www.rcsb.org/structure/1ubq

`MDAnalysis.fetch_mmtf('1ubq')` seems to work fine, probably because the object returned by `mmtf.fetch('1ubq')` has (null valued) altlocs.  Is there an example of an mmtf file without altlocs we can use to reproduce and test this?

**Comment by speleo3** [comment]
@richardjgowers here is the download link for 1ubq:
https://mmtf.rcsb.org/v1.0/full/1UBQ.mmtf.gz

Here is the same file, but I removed the fields `atomIdList`, `altLocList`, `bFactorList`, `occupancyList`, `secStructList`, `insCodeList` and `chainNameList`:
[1ubq-less-optional.mmtf.gz](https://github.com/MDAnalysis/mdanalysis/files/2822568/1ubq-less-optional.mmtf.gz)
