### ISSUE TITLE
Setting/Getting Velocity/Force from Atom

### ISSUE THREAD

**Issue by GoogleCodeExporter** [MDAnalysis/mdanalysis#221]
Can only retrieve velocity from ```Atom```, can't set.ie 
```python
Atom.velocity = [2.5, 1.2, 1.2]
```
would fail.

Can't get/set force from `Atom` (only `AG.forces`) ie `Atom.force` doesn't exist.

Going to include this as part of Issue #213 (reworking Timestep  positions/forces/velocities)

Original issue reported on code.google.com by `richardjgowers` on 20 Feb 2015 at 11:37
* Blocked on: #213

**Comment by richardjgowers** [comment]
Fixed by commit 8041f6b5012409a12dfb69fcc120ce0762413835
