### ISSUE TITLE
Python 3.5 / Numpy 1.16 Travis builds fail due to conflicting conda package dependencies

### ISSUE THREAD

**Issue by zemanj** [MDAnalysis/mdanalysis#2217]
**Expected behavior**

Python 3.5 builds should not fail due to conda package conflicts.

**Actual behavior**

All Python 3.5 Travis builds fail (see PR #2215 builds) since ci-helpers bumped the `LATEST_NUMPY_STABLE` from 1.15 to 1.16 two days ago (see [ci-helpers PR #382](https://github.com/astropy/ci-helpers/pull/382)).

For some reason this triggers a *a lot* of pip fallbacks in the 3.5 builds. The respective conda package installs fail with (see also [Travis log line 783 ff.](https://travis-ci.com/MDAnalysis/mdanalysis/jobs/182634920#L783))
```
UnsatisfiableError: The following specifications were found to be in conflict:
  - numpy=1.16 -> python[version='>=2.7,<2.8.0a0'] -> *[track_features=debug]
  - python=3.5
```
Obviously, the numpy dependency info `python[version='>=2.7,<2.8.0a0']` causes trouble.

For numpy 1.16.x, **there exists no py35 build on conda-forge**, so conda claims to choose the 1.16.2 py37 build (see also [Travis log line 720](https://travis-ci.com/MDAnalysis/mdanalysis/jobs/182634920#L720))
```
The following packages will be downloaded:
    package                    |            build
    ---------------------------|-----------------
    numpy-1.16.2               |py37_blas_openblash1522bff_0         4.3 MB  conda-forge

    ...

The following NEW packages will be INSTALLED:
    numpy:           1.16.2-py37_blas_openblash1522bff_0 conda-forge [blas_openblas]

    ...

The following packages will be UPDATED:
    python:          3.5.6-hc3d631a_0                                --> 3.7.1-h381d211_1002   conda-forge

    ...
```

The output of `conda info numpy` reports correct dependencies for the `1.16.2 py37_blas_openblash1522bff_0` package:
```
numpy 1.16.2 py37_blas_openblash1522bff_0
-----------------------------------------
...
dependencies:
    blas 1.1 openblas
    libgcc-ng >=7.3.0
    libgfortran-ng >=7,<8.0a0
    libstdcxx-ng >=7.3.0
    openblas >=0.3.3,<0.3.4.0a0
    python >=3.7,<3.8.0a0
```

~~So I don't really understand the meaning of the `python[version='>=2.7,<2.8.0a0']` requirement stated in the conda error messages.~~
The dependency `python[version='>=2.7,<2.8.0a0']` in the error message looks like this because if conda cannot find a suitable build, it displays the dependencies of the first non-matching build it can find. In this particular case, that happens to be the py27 build of numpy 1.16.

~~Any ideas what's going wrong here?~~
The error occurs because there is no numpy 1.16 build for python 3.5 on conda-forge, and ci-helpers doesn't implement pip fallbacks for numpy yet.

**Code to reproduce the behavior**
See [Travis build logs](https://travis-ci.com/MDAnalysis/mdanalysis/builds/103313968) of PR #2215.

**Current version of MDAnalysis**
0.19.3-dev

**Comment by zemanj** [comment]
Since for numpy 1.16 there's no py35 build available an conda-forge, I'd expect the installation of numpy via conda to fail at this point, ideally triggering a `pip install numpy=1.16.*`. However, conda seems to try upgrading python to 3.7 instead. The error message, however, suggests that conda actually installed the py27 build of numpy 1.16.2. So it seems that there are multiple things going wrong here.

**Comment by richardjgowers** [comment]
Might just be the new builds haven’t filtered through yet, so I’d give it a couple days before we put any real effort into this.
  

  
  

  
  
>

**Comment by zemanj** [comment]
@richardjgowers I don't think that waiting will help. The latest py35 numpy build on conda-forge is numpy-1.15.2-py35_blas_openblashd3ea46f_0 from 5 months and 9 days ago. In the meantime, they added numpy 1.15.3/1.15.4/1.16.0/1.16.1/1.16.2 packages, and none of those is a py35 build. Looks like Python 3.5 has been dropped.

**Comment by mattwthompson** [comment]
This is pretty concerning to me, both as a 3.5 user and for some other
packages. It looks like they claim to support Python 3.5-3.7 in this
release, any reason why they wouldn't build all those versions to anaconda?

https://github.com/numpy/numpy/releases/tag/v1.16.2

**Comment by zemanj** [comment]
@mattwthompson Thanks for the link, that's good to know! Python 3.5 support has certainly *not* been dropped by the numpy devs (yet),  it just seems that conda-forge no longer provides a build. But since I have no idea who is in charge of deciding which packages/builds are provided via conda-forge, I can only speculate.

I'd be glad if anyone more knowledgable would explain to me how such decisions are made (and who is in charge).

**Comment by richardjgowers** [comment]
Hm ok, yeah looks like it's conda-forge doing the dropping rather than numpy devs.  Might just be a limited resources issue, they (c-f) do all the builds on CI services.

So one option would be to pin numpy on our Py3.5 to whatever worked before.

**Comment by zemanj** [comment]
@richardjgowers I'm working on a solution in ci-helpers where both python and numpy are pinned and installed together, with a pip fallback for numpy if that fails.

**Comment by mattwthompson** [comment]
I asked on their gitter:

>There are no plans yet. conda-forge sets its own prios and dropping 3.5 there makes sense, but it's unrelated to what NumPy the project decides. 3.5 is almost 4 years old though, so I'd expect us to drop it by sometime in 2020.

**Comment by zemanj** [comment]
Ok should be fixed once [this](https://github.com/astropy/ci-helpers/pull/388) gets merged.

**Comment by zemanj** [comment]
The issue is now [fixed](https://github.com/astropy/ci-helpers/pull/388) and our Python 3.5 builds work again (see, for example, [here](https://travis-ci.com/MDAnalysis/mdanalysis/jobs/181168923#L726) and [here](https://travis-ci.com/MDAnalysis/mdanalysis/jobs/181168923#L957)).
