### ISSUE TITLE
Move MDAnalysis to GitHub due to Google Code closure

### ISSUE THREAD

**Issue by GoogleCodeExporter** [MDAnalysis/mdanalysis#223]
```
Google announced that they will shutdown Googlecode 
http://google-opensource.blogspot.com/2015/03/farewell-to-google-code.html (as 
also reported on Ars Technica [1]). The service including all code will be gone 
by 2016:

* August 24, 2015 - The site goes read-only. You can still checkout/view 
project source, issues, and wikis.

* January 25, 2016 - The project hosting service is closed. You will be able to 
download a tarball of project source, issues, and wikis. These tarballs will be 
available throughout the rest of 2016.

Today, "Export to GitHub" buttons appeared on Google Code. I suggest, we make 
the 0.9.0 release from Google Code and then migrate to GitHub. GitHub is a 
nicer platform for collaborative coding but it's hugely annoying that the Issue 
tracker will be lost and we have to think about what to do about that.

Oliver


[1] 
http://arstechnica.com/information-technology/2015/03/google-to-close-google-cod
e-open-source-project-hosting/


```

Original issue reported on code.google.com by `orbeckst` on 12 Mar 2015 at 5:05
* Blocking: #134, #235, #236
* Blocked on: #231, #232, #233, #234

**Comment by orbeckst** [comment]
In principle the move from Google Code to GitHub is complete. There are lots of things to iron out (such as wiki, docs and homepage and how to do attachments with the issue tracker, uploading old downloads to pypi, splitting of tools ("applications") into own repos, ...) but the code is up and all the infrastructure is in place.

@MDAnalysis/coredevs : please start using https://github.com/MDAnalysis/mdanalysis and provide feedback if anything is not working properly.

New clones:

    git clone git@github.com:MDAnalysis/mdanalysis.git

Changing existing repositories (assuming that the google code repo was named "origin"):

    git remote rename origin googlecode
    git remote add origin git@github.com:MDAnalysis/mdanalysis.git

This should be sufficient to use the new repository, for instance, update your develop branch:

    git pull origin develop

Thanks to everyone for their patience and support!
Oliver
