### ISSUE TITLE
I broke travis

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/mdanalysis#2233]
I think as part of PR #2231 I broke travis... since then I can't run Travis jobs, probably messed up .travis.yml.

Working on it...

**Comment by orbeckst** [comment]
```
$ travis lint ../.travis.yml
Warnings for ../.travis.yml:
[x] syntax error: (<unknown>): found a tab character that violate intendation while scanning a plain scalar at line 50 column 12
```

**Comment by orbeckst** [comment]
The docs build fails on Travis at the moment, as far as I can tell. I thought this had something to do with building in a py 3.5 environment and updated the doc build to 3.7 as part of another PR. I thought I fixed everything because the CI status was green. However, Travis did not even run, but AppVeyor did, and that was enough to green-light. (First lesson: a green check mark is not enough, one actually has to look at what ran!)

I had made a mistake in the travis.yml file by introducing a TAB. D’oh!, see https://github.com/MDAnalysis/mdanalysis/issues/2233 ; the corresponding PR fixes that.

However, docs still don’t build, see e.g. https://travis-ci.com/MDAnalysis/mdanalysis/jobs/189877496 ; the error message is
```
reading sources... [ 49%] documentation_pages/coordinates_modules
reading sources... [ 50%] documentation_pages/core/groups
setup.py:124: DeprecationWarning: The SafeConfigParser class has been renamed to ConfigParser in Python 3.2. This alias will be removed in future versions. Use ConfigParser directly instead.
  self.config = configparser.SafeConfigParser()
/home/travis/miniconda/envs/test/lib/python3.7/site-packages/Cython/Compiler/Main.py:367: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /home/travis/build/MDAnalysis/mdanalysis/package/MDAnalysis/analysis/encore/clustering/affinityprop.pyx
  tree = Parsing.p_module(s, pxd, full_module_name)
…
…
…

Exception occurred:
  File "/home/travis/miniconda/envs/test/lib/python3.7/site-packages/sphinx/ext/napoleon/docstring.py", line 703, in _parse_raises_section
    m = self._name_rgx.match(_type).groupdict()
AttributeError: 'NoneType' object has no attribute 'groupdict'
```

If anyone can help then please do. I’m busy/travelling the rest of the day so ANY help is greatly appreciated. Use https://github.com/MDAnalysis/mdanalysis/issues/2233 and PR https://github.com/MDAnalysis/mdanalysis/pull/2234

**Comment by NinadBhat** [comment]
The problem seems to be with sphinx. [https://github.com/sphinx-doc/sphinx/issues/6225](https://github.com/sphinx-doc/sphinx/issues/6225)
