### ISSUE TITLE
Transformation tests not running due to missing  __init__.py 

### ISSUE THREAD

**Issue by Lp0lp** [MDAnalysis/mdanalysis#2241]
**Expected behavior**

Tests for the transformations should run when calling pytest.

**Actual behavior**

The `__init__.py` file is missing at `/testsuite/MDAnalysisTests/transformations/` and therefore the tests are not run when pytest is called.

**Code to reproduce the behavior**

Error was reproduced whilst testing in PR ##2208

**Currently version of MDAnalysis**

- Which version are you using? (run `python -c "import MDAnalysis as mda; print(mda.__version__)"`) 
 0.19.2
- Which version of Python (`python -V`)? 
3.6.3
- Which operating system? 
Ubuntu 17.10

**Comment by orbeckst** [comment]
Thanks. For future reference
- https://docs.pytest.org/en/latest/goodpractices.html#tests-outside-application-code
- https://stackoverflow.com/questions/50796370/pytest-how-to-work-around-missing-init-py-in-the-tests-folder
