### ISSUE TITLE
project ideas for GSoD

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/mdanalysis#2242]
We want to help numfocus to get accepted in Google Summer of Docs, with the goal to get one techical writer to work with us in the fall. 

I submitted to Numfocus answers to their general questions (which they need for their proposal, see https://github.com/MDAnalysis/mdanalysis/wiki/Google-Season-of-Docs#mdanalysis-contribs-to-numfocus-proposal).

What we now need is a number of well-formulated project ideas. The current draft is at https://github.com/MDAnalysis/mdanalysis/wiki/Google-Season-of-Docs#project-ideas and I created a PR https://github.com/numfocus/gsod/pull/2 so that this list of bullet points is added to [MDAnalysis_ideas_list.md](https://github.com/numfocus/gsod/blob/master/2019/MDAnalysis_ideas_list.md) . Bullet points are better than no content at all but what we really need are some well articulated ideas.

**BY SATURDAY APRIL 13 we need an improved list.** I will then create a final PR for numfocus by their April 14 deadline.

Please work on https://github.com/MDAnalysis/mdanalysis/wiki/Google-Season-of-Docs#project-ideas and improve them. The rules are that you can edit anything. If you want something removed add a comment with your reasons and/or discuss on this issue. If there are unresolved disputes by Saturday I’ll just decide based on the evidence when I make the final PR.

PLEASE try to find a few minutes in your busy schedules to contribute. This is a really good opportunity for us to make progress in a strategically important area where we don’t have the resources to address the problem on our own

## Timeline

- [x] add/reformulate [project ideas](https://github.com/MDAnalysis/mdanalysis/wiki/Google-Season-of-Docs#project-ideas) 
- [x] April 13, 2019 finalize (@orbeckst)
- [x] April 14, 2019 (or earlier) submit PR (@orbeckst )

**Comment by richardjgowers** [comment]
I think I agree with the first three ideas there.  I added a fourth which is more graphical that wordy, maybe a little outside of scope for a 'technical writer'.

**Comment by orbeckst** [comment]
I fleshed out the ideas. Feel free to edit.

**Comment by zemanj** [comment]
LGTM! I fixed some typos and rephrased some sentences slightly (less parentheses, missing noun markers, etc.).
I changed "envisage" to "envision" since that sounded more appropriate to me. Since I'm not a native speaker, maybe someone who is could confirm/revert this...

**Comment by orbeckst** [comment]
I added on-the-fly transformations (see also #2246) to the list of intermediate-level tutorials

**Comment by orbeckst** [comment]
@kain88-de commented on https://github.com/numfocus/gsod/pull/2 – in particular he suggests to focus on the first two for the initial GSoD. Can you have a look and comment? If I don't hear anything else I'll reduce the proposed project and fill in the blanks that were mentioned.

I would mentor for docs. Anyone else?

**Comment by jbarnoud** [comment]
I'll be happy to chip in, but I cannot commit to mentor.

**Comment by orbeckst** [comment]
We need at least two mentors in order to participate. If we don't have two mentors we can't participate. Anyone else? Please let me know asap because April 15 is the deadline for merging the PR.

**Comment by richardjgowers** [comment]
I told Max in the PR I'll mentor

**Comment by orbeckst** [comment]
Great. I'll update the pr and then say that it's ready. 

I'll focus on projects 1 and 2 in the pr. I won't have much time to rewrite a lot so if anyone wants to polish the language then please do so (on the wiki page). 

--
Oliver Beckstein
email: orbeckst@gmail.com

**Comment by orbeckst** [comment]
I told NumFOCUS that PR https://github.com/numfocus/gsod/pull/2 is ready.
