### ISSUE TITLE
HydrogenBondLifetimes (Autocorrelation) has an increasing value

### ISSUE THREAD

**Issue by bieniekmateusz** [MDAnalysis/mdanalysis#2247]
The autocorrelation has to be decreasing. 

Adjusted test case from the test_waterdynamics.py file:
```python
def test_HydrogenBondLifetimes_growing_continuous(universe):
    # The autocorrelation cannot grow
    hbl = waterdynamics.HydrogenBondLifetimes(
        universe, SELECTION1, SELECTION1, t0=0, tf=9, dtmax=5)
    hbl.run()
    print("results", hbl.timeseries)
    # Index 0 in frameX[0] refers to the continuous, 1 to intermittent
    assert all([frameX[0] > frameXplus1[0] for frameX, frameXplus1 in zip(hbl.timeseries, hbl.timeseries[1:])])
```
The current autocorrelation code in HydrogenBondLifetimes returns lifetimes that increase over time. We  are planning to address this in the next Pull Request with @p-j-smith where we add the test case and use our standalone autocorrelation function. 

- Which version are you using? developing branch
- Python 2.7
- Linux Arch

**Comment by orbeckst** [comment]
Are you saying that the calculated ACF must be monotonically decreasing? Not even a little bit of noise allowed?

**Comment by bieniekmateusz** [comment]
In the actual experiments I imagine the noise could create this kind of data. However, in the case of continuous ACF this cannot happen. This is because at each point t0, we take our bonds and check if they survive at every step up until a given tau, say tau=t4. If they leave at t3, we do not allow it to return, and so t4 is thrown away (we say it has left). So, by definition, the continuous ACF will be monotonically decreasing. 

Now, some implementations of the intermittent ACF could lead to the noise you suggest. In our case, it is not possible: we say that if the molecule leaves only at t3 and returns at t4, with the intermittency=1, then we treat this bond as if it was there at every step from t0 to t4, including at t3. So again, it is not possible for the ACF to increase.

Paul & Mat

**Comment by richardjgowers** [comment]
Yeah this is slightly worrying. I’ve not looked in too much detail at this yet, is there anything this class does that the hbond autocorrel doesn’t do? And how hard would it be to merge the two?
  

  
  

  
  
>

**Comment by bieniekmateusz** [comment]
@richardjgowers The HydrogenBondLifetimes does not do anything extra. We're hoping to finish soon submit the next PR. We're going to add a function to the Richard's HydrogenBond finder to get the autocorrelation directly. 

Mat
