### ISSUE TITLE
MDAnalysis unable to read a pdb with mangled CRYST record

### ISSUE THREAD

**Issue by fabiotrovato** [MDAnalysis/mdanalysis#2252]
6edu.pdb cannot be read by MDAnalysis (here mda)

script:
```
u = mda.Universe('6edu.pdb')
```
Error:
```
Traceback (most recent call last):
  File "test_mda.py", line 25, in <module>
    u = mda.Universe('6edu.pdb',format="xpdb")
  File "/Users/trovato/anaconda2/envs/pdb_analysis/lib/python3.6/site-packages/MDAnalysis/core/universe.py", line 335, in __init__
    self.load_new(coordinatefile, **kwargs)
  File "/Users/trovato/anaconda2/envs/pdb_analysis/lib/python3.6/site-packages/MDAnalysis/core/universe.py", line 602, in load_new
    self.trajectory = reader(filename, **kwargs)
  File "/Users/trovato/anaconda2/envs/pdb_analysis/lib/python3.6/site-packages/MDAnalysis/coordinates/PDB.py", line 323, in __init__
    self._read_frame(0)
  File "/Users/trovato/anaconda2/envs/pdb_analysis/lib/python3.6/site-packages/MDAnalysis/coordinates/PDB.py", line 391, in _read_frame
    line[40:47], line[47:54]]
ValueError: could not convert string to float: 
```
Can the coordinates of the order of 100 Ang be a problem? How shall I read in this pdb?

**Comment by ezavod** [comment]
@fabiotrovato If you are using this [6edu.pdb](https://www.rcsb.org/structure/6edu) your `CRYST1` entry misses `a`, `b`, `c` and is therefore not parseable. `REMARK 247` elaborates on this. One could load this file if one removes the `CRYST1` line.

**Comment by fabiotrovato** [comment]
@ezavod thank you for the suggestion.
The error is nonetheless cryptic because it does not hint at the CRYST1 entry, at all. 

Suggestions for improvement and for the sake of usability/debugging:
1) if the pdb is not parseable as you say, shouldn't MDAnalysis simply abort when CRYST1 is not complete rather than complaining later on something unrelated (the coordinates are actually fine)?; OR
2) when CRYST1 is missing or incomplete and an error occurs afterwards (like here in the coord section) shouldn't be there a raise ValueError with message "please check CRYST1 entry" or similar?

Is there a feature or an argument that can be passed to the pdb reader so that everything but the coordinates are skipped? If not, it would be a tremendous improvement as many people use pdbs mostly for their coordinates, rather then all the rest of the information.

Thank you,
Fabio

**Comment by richardjgowers** [comment]
Hey @fabiotrovato thanks for reporting this issue

I've put in a patch which should fix this.  Removing the line from the file will also fix this issue.

**Comment by fabiotrovato** [comment]
Thank you!

Il giorno mer 17 apr 2019, 16:38 Richard Gowers <notifications@github.com>
ha scritto:
