### ISSUE TITLE
Print the values of rdf 

### ISSUE THREAD

**Issue by omkantnirala** [MDAnalysis/mdanalysis#2263]
I have written the code for the calculating the RDF and depicted as:

```python
import MDAnalysis as mda
import numpy as np
from mda.analysis .rdf import InterRDF
import matplotlib.pyplot as plt

mda.core.flags ['use_periodic_selections'] = True

u = mda.Universe ('md10.tpr','md.xtc')

cyts1 = u.select_atoms('resname SOL and sphzone 5.3 resid 4')
cyt_groups1 = list(cyts1.groupby('resids').values())
cyts1 = u.select_atoms('resname SOL and sphzone 5.3 resid 4')
cyt_groups2 = list (cyts1.groupby('resids').values())
rdf = InterRDF (g1 = c1,g2 = c2,exclusion_block = (1,1))
rdf.run ()

print(rdf)
plt.plot(rdf.bins,rdf.rdf,'-',label='Glycine 4')
np.savetxt('abc.dat',(rdf.bins))
plt.show ()
```

I am getting the rdf graph but unable to get the values and print it.

So how can i get the values (ie., x and y values of the rdf) and print it into a file? 
What modifications i need to do in order to get it.

Any suggestions are appreciated.
Thank you.

**Comment by ezavod** [comment]
There are several ways to do this. The way that I find most convenient is to first create a dict:
`rdf_dict = {'bins': rdf_data.bins, 'rdf': rdf_data.rdf}` (I renamed your `rdf` to `rdf_data`).
With this dict one could use the full power of [pandas](https://pandas.pydata.org/pandas-docs/version/0.23.0/index.html) and write e.g. to a CSV file (`print` statements to better understand the shape of your data):
```
print(rdf_data)
df = pd.DataFrame(data=rdf_dict)
print(df)
df.to_csv('rdf_data.csv')
```
There are also a lot of other features that pandas provides.

For the sake of completeness there are [json](https://docs.python.org/3.7/library/json.html), [pickle](https://wiki.python.org/moin/UsingPickle) or [HDF5](http://docs.h5py.org/en/stable/) for more advanced/niche applications.
Note that [pprint](https://docs.python.org/3/library/pprint.html) offers some nicer formatting for displaying data in your console.

**Comment by omkantnirala** [comment]
Thanks Ezavod for helping us. 
From that code i am not getting smooth rdf as we found in xmgrace. How can i get a smooth rdf ?

Any suggestions are appreciated.
Thank you.

**Comment by ezavod** [comment]
@omkantnirala You're welcome. With those information I am unable to fully comprehend your problem, but I assume that your bin count is lower than your reference data.
According to [the docs](https://www.mdanalysis.org/docs/documentation_pages/analysis/rdf.html#MDAnalysis.analysis.rdf.InterRDF) the default range is 15 angstrom with 75 bins. So your bin with would be 0.02 nm. [Other](http://manual.gromacs.org/documentation/2019/onlinehelp/gmx-rdf.html#options) programs use much smaller sizes, e.g. 0.002 nm. Maybe try something like `InterRDF(... , nbins=750)`.
Apart from that one could also use more sophisticated settings for plotting, e.g. apply some smoothing. However this could be dangerous if overdone and depends of your judgement of the problem.

**Comment by omkantnirala** [comment]
I tried to finding the number of hydrogen bond from this code. But it is showing error type 
TypeError                                 Traceback (most recent call last)
<ipython-input-437-4b07438fb5a2> in <module>()
     12 trajectory = traj_split.split('.')[0]
     13 
---> 14 traj     = MDAnalysis('md10.tpr','md.xtc')
     15 lines = traj.readlines()
     16 

TypeError: 'module' object is not callable. 
Can anyone help regarding this issue.
### 
**_

> ''' import MDAnalysis as mda
> import MDAnalysis as hbonds
> from os import path
> 
> print ('H-Bond Distance Cutoff')
> bond_cutoff = float( (3.0))
> 
> print ('H-Bond Angle(HOO) Cutoff')
> angle_cutoff = float((130.0))
> traj_split = path.basename('/home/workstation/Documents/OMKANT_5Z32MD/5CAL_5Z32MD/nh-bond.dat')
> traj_dir   = path.dirname(path.abspath('/home/workstation/Documents/OMKANT_5Z32MD/5CAL_5Z32MD/nh-bond.dat'))
> trajectory = traj_split.split('.')[0]
> 
> traj     = MDAnalysis('md10.tpr','md.xtc')
> lines = traj.readlines()
> 
> steps     = []
> atoms     = []
> x_dir     = []
> x_dir_pbc = []
> y_dir     = []
> y_dir_pbc = []
> z_dir     = []
> z_dir_pbc = []
> atoms_O   = []
> atoms_H   = []
> x_O       = []
> x_O_pbc   = []
> y_O       = []
> y_O_pbc   = []
> z_O       = []
> z_O_pbc   = []
> x_H       = []
> x_H_pbc   = []
> y_H       = []
> y_H_pbc   = []
> z_H       = []
> z_H_pbc   = []
> oxygens   = []
> hydrogens = []
> oxy_angle = []
> box_len   = 46.488
> 
> for i in range(0,len('69756')):
>    line = lines[0]
>    if (line[0] == '0'):
>       traj_pbc.write('69756')
>    if (line[0] == '69756'):
>       steps_1 = line.split()
>       step = steps_1[0]+" "+steps_1[1]+"\t"+steps_1[2]
>       steps.append(step) 
>       traj_pbc.write(line)
>    if (line[0] == 'O'):
>       chunk = line.split()
>       atoms.append(chunk[0])
>       atoms_O.append(chunk[0])
>       
>       x_dir.append(float(chunk[1]))
>       O_pbc_x = float(chunk[1]) - (box_len * numpy.floor(float(chunk[1])/box_len))
>       O_pbc_x_move = O_pbc_x - float(chunk[1])
>       x_dir_pbc.append(O_pbc_x)
>       
>       y_dir.append(float(chunk[2]))
>       O_pbc_y = float(chunk[2]) - (box_len * numpy.floor(float(chunk[2])/box_len))
>       O_pbc_y_move = O_pbc_y - float(chunk[2])
>       y_dir_pbc.append(O_pbc_y)
>       
>       z_dir.append(float(chunk[3]))
>       O_pbc_z = float(chunk[3]) - (box_len * numpy.floor(float(chunk[3])/box_len))
>       O_pbc_z_move = O_pbc_z - float(chunk[3])
>       z_dir_pbc.append(O_pbc_z)
>       
>       #            traj_pbc.write("%s\t%2.9f  %2.9f  %2.9f  %2.9f  %2.9f  %2.9f\n" % (chunk[0], O_pbc_x, O_pbc_y, O_pbc_z, float(chunk[4]), float(chunk[5]), float(chunk[6])))
>       
>       traj_pbc.write("%s\t%f\t%f\t%f\n" % (chunk[0], O_pbc_x, O_pbc_y, O_pbc_z))
>       
>       x_O.append(float(chunk[1]))
>       y_O.append(float(chunk[2]))
>       z_O.append(float(chunk[3]))
>       x_O_pbc.append(O_pbc_x)
>       y_O_pbc.append(O_pbc_y)
>       z_O_pbc.append(O_pbc_z)
>       
>    if (line[0] == 'H'):
>       chunk = line.split()
>       atoms.append(chunk[0])
>       atoms_H.append(chunk[0])
>       
>       x_dir.append(float(chunk[1]))
>       H_pbc_x = float(chunk[1]) + O_pbc_x_move
>       x_dir_pbc.append(H_pbc_x)
>       
>       y_dir.append(float(chunk[2]))
>       H_pbc_y = float(chunk[2]) + O_pbc_y_move
>       y_dir_pbc.append(H_pbc_y)
>       
>       z_dir.append(float(chunk[3]))
>       H_pbc_z = float(chunk[3]) + O_pbc_z_move
>       z_dir_pbc.append(H_pbc_z)
>       
>       #traj_pbc.write("%s\t%2.9f  %2.9f  %2.9f  %2.9f  %2.9f  %2.9f\n" % (chunk[0], H_pbc_x, H_pbc_y, H_pbc_z, float(chunk[4]), float(chunk[5]), float(chunk[6])))
>       
>       traj_pbc.write("%s\t%f\t%f\t%f\n" % (chunk[0], H_pbc_x, H_pbc_y, H_pbc_z))
>       
>       x_H.append(float(chunk[1]))
>       y_H.append(float(chunk[2]))
>       z_H.append(float(chunk[3]))
>       x_H_pbc.append(H_pbc_x)
>       y_H_pbc.append(H_pbc_y)
>       z_H_pbc.append(H_pbc_z)
>       
> traj.close()
> traj_pbc.close()
> 
> 
> for o_stp in range(1, 65):
>    stp = 0
>    oxy = atoms_O[(stp * 64) + o_stp - 1]
>    oxy_x = x_O_pbc[(stp * 64) + o_stp - 1]
>    oxy_y = y_O_pbc[(stp * 64) + o_stp - 1]
>    oxy_z = z_O_pbc[(stp * 64) + o_stp - 1]
>    #      oxygen = [stp, o_stp, oxy, oxy_x, oxy_y, oxy_z]
>    oxygen = [o_stp, oxy, oxy_x, oxy_y, oxy_z]
>    oxygens.append(oxygen)
>    for h_stp in range(1, 3):
>       hyd = atoms_H[(stp * 128) + (2 * o_stp) + h_stp - 3]
>       hyd_x = x_H_pbc[(stp * 128) + (2 * o_stp) + h_stp - 3]
>       hyd_y = y_H_pbc[(stp * 128) + (2 * o_stp) + h_stp - 3]
>       hyd_z = z_H_pbc[(stp * 128) + (2 * o_stp) + h_stp - 3]
>       #         hydrogen = [stp, o_stp, hyd, h_stp, hyd_x, hyd_y, hyd_z]
>       hydrogen = [o_stp, hyd, h_stp, hyd_x, hyd_y, hyd_z]
>       hydrogens.append(hydrogen)
> 
>       
> for x in [0, 1, -1]:
>    for y in [0, 1, -1]:
>       for z in [0, 1, -1]:
>         #for stp in range(0,len(steps)):
>          if (x == 0 and y == 0 and z == 0):
>             sudheer = 1
>          else:
>             for o_stp in range(1, 65):
>                stp = 0
>                oxy = atoms_O[(stp * 64) + o_stp - 1]
>                oxy_x = x_O_pbc[(stp * 64) + o_stp - 1] + (x * 46.488)
>                oxy_y = y_O_pbc[(stp * 64) + o_stp - 1] + (y * 46.488)
>                oxy_z = z_O_pbc[(stp * 64) + o_stp - 1] + (z * 46.488)
>                oxygen = [o_stp, oxy, oxy_x, oxy_y, oxy_z]
>                oxygens.append(oxygen)
>                for h_stp in range(1, 3):
>                   hyd = atoms_H[(stp * 128) + (2 * o_stp) + h_stp - 3]
>                   hyd_x = x_H_pbc[(stp * 128) + (2 * o_stp) + h_stp - 3] + (x * 46.488)
>                   hyd_y = y_H_pbc[(stp * 128) + (2 * o_stp) + h_stp - 3] + (y * 46.488)
>                   hyd_z = z_H_pbc[(stp * 128) + (2 * o_stp) + h_stp - 3] + (z * 46.488)
>                   hydrogen = [o_stp, hyd, h_stp, hyd_x, hyd_y, hyd_z]
>                   hydrogens.append(hydrogen)
> 
> i = 0
> Ohbond_list = []
> for j in range(1, 65):
>     li = [j, 0, 0]
>     Ohbond_list.append(li)
> 
> Ohbond_file = file("HBonds_Number.txt", "w")
> Total_hbond = 0
> for j in range(1, 65):
>    hlist = []
>    Ohbond = 0
>    OXY_A = [oxygens[j - 1][2], oxygens[j - 1][3], oxygens[j - 1][4]]
>    oxy_range = range(1, len(oxygens) + 1)
>    oxy_range.remove(j)
>    for k in range(1, 3):
>        HYD_A = [hydrogens[(2 * j) + k - 3][3], hydrogens[(2 * j) + k - 3][4], hydrogens[(2 * j) + k - 3][5]]
>        for l in oxy_range:
>            OXY_B = [oxygens[l - 1][2], oxygens[l - 1][3], oxygens[l - 1][4]]
>            A = [OXY_A, HYD_A, OXY_B]
>            answer_hbond, hbond_dist, hbond_angle, hbond_cutoff, hangle_cutoff = hbonds.hbond(A, 2, 1, bond_cutoff, angle_cutoff)
>            if (answer_hbond == "True"):
>                Ohbond = Ohbond + 1
>                Ohbond_list[j - 1][1] = Ohbond_list[j - 1][1] + 1
>            if (answer_hbond == "True" and l < 65):
>                Ohbond_list[l - 1][2] = Ohbond_list[l - 1][2] + 1
>    Total_hbond = Total_hbond + Ohbond
> 
> 
> Ohbond_file.write("%i  %f  Bond Cutoff = %2.3f  Angle Cutoff = %3.3f\n\n" % (Total_hbond, Total_hbond/64.0, hbond_cutoff, hangle_cutoff))
> for j in range(1, 65):
>     Ohbond_file.write("%i\t%i\t%i\t%i\n" % (j, Ohbond_list[j - 1][1], Ohbond_list[j - 1][2], Ohbond_list[j - 1][1] + Ohbond_list[j - 1][2]))
> Ohbond_file.close() ### '''

_**
Thanks

**Comment by orbeckst** [comment]
I am closing this issue as it is a question that should be handled on the mailing list. 

We decided to keep the issue tracker for code issues/bugs/feature requests. Thanks.

**Comment by omkantnirala** [comment]
I tried to finding the coordination number from this code. But  i am unable to put limits in that code. Please help me regarding this issue.

    `` `import` os
     import numpy as np
     import matplotlib
     from matplotlib import pyplot as plt
   from scipy.integrate import quad

`A` = np.loadtxt(os.path.join(os.path.expanduser('~'),'/home/workstation/Documents/OMKANT_5Z32MD/5CAL_5Z32MD/rdf.dat/rdf5Ca_ARG3-Ow.dat'))
B = open('rdf10.dat','w')

r = A[:,0]
g = A[:,1]
#c=[0]
#z=len(r)
#ans=(0, 5.0)
result=[]
integrand = 4*np.pi*1*(r**2)*(g)
for i in range(len(r)):
        ans = np.trapz(integrand[0:i],r[0:i])
        result = np.append(result,ans)
        B.write (str(r[i])+'\t'+str(result[i])+'\n')
plt.subplot(212),plt.plot(r[:-1],result[:-1],label='integrand(r)')
`plt.xlabel('r')`
plt.ylabel ('Nab')
plt.legend()
`plt.show()``
Thank you .

**Comment by orbeckst** [comment]
Please ask on the mailing list, the issue tracker is for bugs etc. We generally do not answer questions on the issue tracker. Thanks.
