### ISSUE TITLE
MOL2 writer fails if not loaded from MOL2

### ISSUE THREAD

**Issue by GoogleCodeExporter** [MDAnalysis/mdanalysis#227]
Using MDAnalysis 0.9.0, I cannot write a MOL2 file if I loaded from anything that isn't a MOL2 file.

What steps will reproduce the problem?
```python
 import MDAnalysis; from MDAnalysis.tests.datafiles import merge_ligand as LIGAND_PDB
 u = MDAnalysis.Universe(LIGAND_PDB)
 u.atoms.write("fromPDB.mol2")
```

What is the expected output? What do you see instead?

This should write a mol2 file of the ligand. Instead I get an AttributeError because the mol2 reader is trying to access "substructure", which is not available in all readers (in fact, it is only a part of the mol2 reader):

   AttributeError: 'PrimitivePDBReader' object has no attribute 'substructure'

(see full trace below).

Thus, I consider the MOL2 writer broken because it can only be used in a limited set of circumstances at the moment. 

1. It should be rewritten to cope with ALL input topologies. Given our improved topology analysis capabilities, this should be possible.
2. Appropriate test cases need to be added.

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-13-1a7bca870f90> in <module>()
----> 1 u2.atoms.write("fromPDB.mol2")

/Volumes/Data/oliver/Biop/Library/python/mdanalysis/package/MDAnalysis/core/Atom
Group.py in write(self, filename, format, filenamefmt, **kwargs)
   2329             raise ValueError("No writer found for format: {}".format(filename))
   2330         else:
-> 2331             writer.write(self.atoms)
   2332             if coords:  # only these writers have a close method
   2333                 writer.close()

/Volumes/Data/oliver/Biop/Library/python/mdanalysis/package/MDAnalysis/coordinat
es/MOL2.py in write(self, obj)
    344         for framenumber in xrange(start, len(traj), step):
    345             traj[framenumber]
--> 346             self.write_next_timestep(obj)
    347 
    348         self.close()

/Volumes/Data/oliver/Biop/Library/python/mdanalysis/package/MDAnalysis/coordinat
es/MOL2.py in write_next_timestep(self, obj)
    357         or a :class:`~MDAnalysis.core.AtomGroup.Universe`.
    358         """
--> 359         block = self.encode_block(obj)
    360         self.file.writelines(block)

/Volumes/Data/oliver/Biop/Library/python/mdanalysis/package/MDAnalysis/coordinat
es/MOL2.py in encode_block(self, obj)
    305         bond_lines = "\n".join(bond_lines)
    306 
--> 307         substructure = traj.substructure[traj.frame]
    308         substructure = ["@<TRIPOS>SUBSTRUCTURE\n"] + substructure
    309 

AttributeError: 'PrimitivePDBReader' object has no attribute 'substructure'
```

Original issue reported on code.google.com by `orbeckst` on 19 Mar 2015 at 6:03

**Comment by jandom** [comment]
Hi, yup - and thanks for the reminder ;)
Jan

**Comment by orbeckst** [comment]
https://www.cgl.ucsf.edu/chimera/docs/ProgrammersGuide/Examples/writeMol2.py contains a simple recipe for writing mol2 files. It does contain a dict to create the atom types but it seems that Chimera already has basic atom-typing built in.

**Comment by orbeckst** [comment]
The original description for the mol2 format is not available anymore (see eg http://forums.openbabel.org/broken-link-td4659911.html). 

I downloaded http://chemyang.ccnu.edu.cn/ccb/server/AIMMS/mol2.pdf  (Sybyl 7.1 Mid 2005) and attach it here for safe keeping... 

[mol2.pdf](https://github.com/MDAnalysis/mdanalysis/files/1099077/mol2.pdf)
