### ISSUE TITLE
MDAnalysis reading nc file error

### ISSUE THREAD

**Issue by Alfelipe** [MDAnalysis/mdanalysis#2270]
If you have a **QUESTION** such as 

- how to use MDAnalysis in general
- how to accomplish something specific,
- what output means
- ... or similar questions related to USING MDAnalysis 

then please *ask this question on the user mailing list*

   https://groups.google.com/forum/#!forum/mdnalysis-discussion

The issue tracker is meant for DEFECTS ("BUGS"), new FEATURES, and decisions on the API. In order to keep the volume of work on the issue tracker manageable for our volunteer developers, we will IMMEDIATELY CLOSE ISSUES THAT ARE BETTER ANSWERED ON THE USER MAILINGLIST.

We really appreciate you as a user getting in touch with us --- no matter what you want to discuss. But we need your help keeping the amount of work manageable so please use the mailing list for questions and the issue tracker for code-related issues.

Thank you!

The MDAnalysis Development Team

**Comment by orbeckst** [comment]
@Alfelipe I saw your email on the list – thanks for sending it there, much appreciated! Depending on the discussion on the list we might actually ask you to open an issue if this looks like something that needs to be fixed or documented.
