### ISSUE TITLE
Test failures due to wrong scipy version being installed

### ISSUE THREAD

**Issue by zemanj** [MDAnalysis/mdanalysis#2272]
Currently, all `NUMPY_VERSION=1.10.4` tests fail on Travis.

The problem is that conda installs a too old scipy version:
```
scipy: 0.19.1-py35_blas_openblas_202 conda-forge [blas_openblas]
```
even though we require scipy>=1.0.
Later, when `$BUILD_CMD` is evaluated, the build notices the missing requirement
```
Collecting scipy>=1.0.0 (from MDAnalysis==0.19.3.dev0)
```
And a little further below:
```
ERROR: scipy 1.3.0 has requirement numpy>=1.13.3, but you'll have numpy 1.10.4 which is incompatible.
```
As expected, the tests then fail due to numpy/scipy incompatibilities.

**Comment by zemanj** [comment]
I just found out that conda used to install wrong package versions for quite a while (see [here](https://travis-ci.com/MDAnalysis/mdanalysis/jobs/187886606#L1025) and [here](https://travis-ci.com/MDAnalysis/mdanalysis/jobs/187886606#L1564)), which never caused problems because the pip versions being installed by the MDA build did not have incompatibilities. Now, with scipy 1.3, this no longer seems to work.
The reason seems to be [where version numbers are stripped from CONDA_DEPENDENCIES in ci-helpers](https://github.com/astropy/ci-helpers/blob/b1e4c9bdd57c1aca36ff0c0895ba3f802c540f07/travis/setup_dependencies_common.sh#L304). Looks like the pin file created beforehand is not respected.

**Comment by orbeckst** [comment]
Can we just bump the numpy requirement to be compatible with scipy >= 1.0? 

@tylerjereddy do you have some insights in how necessary it is to maintain numpy 1.10.4 compatibility?

**Comment by orbeckst** [comment]
@zemanj – if we required numpy >= 1.13.3 would everthing be ok?

If this is the case and no-one else is chiming in (@MDAnalysis/coredevs , anyone?) I would say we conserve developer time and just bump the requirement instead of debugging ci-helpers/conda version hell.

**Comment by orbeckst** [comment]
Btw, does this problem originate from our `setup.py` requring scipy >= 1.0 https://github.com/MDAnalysis/mdanalysis/blob/f83498ec6b5cc546a0d75598a4d1d6ede6fe2782/package/setup.py#L592
but on travis we don't specify these dependencies explicitly:
https://github.com/MDAnalysis/mdanalysis/blob/f83498ec6b5cc546a0d75598a4d1d6ede6fe2782/.travis.yml#L30 ?

Should we just be consistent between the two files? Maybe that fixes things or at least fails earlier?

**Comment by zemanj** [comment]
I have asked this question already before in another issue but either nobody knew the answer or didn't bother. I'd really like to know on which basis the minimum numpy/python versions we support are determined.

I personally would love to see the minimum numpy version bumped to 1.13.3.

**Comment by zemanj** [comment]
@orbeckst Yeah we should specify the version numbers explicitly and see if that helps. I'm for bumping rhe minimum numpy version anyway unless somone argues against it.

**Comment by orbeckst** [comment]
Just sent an [email to the dev list](https://groups.google.com/d/msg/mdnalysis-devel/yZW95c5L7Bw/PcNrCeUsBwAJ)... give it a day and if no-one objects, let's go ahead and bump it. We can't have all our PRs stalled because of that.

**Comment by orbeckst** [comment]
No-one is against bumping the numpy minimal required version. @zemanj do you want to do the honors (I mean, a quick PR with the appropriate CHANGELOG entry)?

**Comment by zemanj** [comment]
@orbeckst I'd love to, but I'm on vacation right now and only have my phone with me. I won't be available until Sunday next week. If nobody else has jumped in by then, I'll do it.
