### ISSUE TITLE
Add loading .gro time series trajectory.

### ISSUE THREAD

**Issue by acnash** [MDAnalysis/mdanalysis#2276]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by orbeckst** [comment]
Hi @acnash – I hope you didn't feel intimidated by the issue form. We are trying to give you some guidance on how to formulate a report that is immediately useful to us. You don't _have_ to follow the structure but it helps us if you do. You can certainly leave out sections that you don't have anything for.

**Comment by acnash** [comment]
Good morning, Oliver.


Not at all! I just had a slight internet connection issue (I filled in the form and then my browser timed out) and then I decided to go to bed.


I've got two issues to submit, a new feature (loading .gro trajectory files) and the issue with installing through pip whilst on my version of Mac. I'll file those forms today.


Thanks

Anthony


Kind regards
Dr Anthony Nash PhD MRSC

Senior Research Scientist
Department of Physiology, Anatomy, and Genetics
University of Oxford
https://www.dpag.ox.ac.uk/

RMCR Kellogg College
University of Oxford
http://www.kellogg.ox.ac.uk/

________________________________
