### ISSUE TITLE
Around selection does not work for AtomGroups

### ISSUE THREAD

**Issue by ezavod** [MDAnalysis/mdanalysis#2280]
### Expected behaviour
The Method `select_atoms` of `MDAnalysis.core.groups.AtomGroup` [should return](https://www.mdanalysis.org/docs/documentation_pages/core/groups.html#MDAnalysis.core.groups.AtomGroup.select_atoms) all atoms within given search distance.

### Actual behaviour
No atoms are found.

### Code to reproduce the behaviour

``` python
import MDAnalysis

u = MDAnalysis.Universe("pair.gro")

s1 = u.select_atoms("name A and around 15 name B")
s2 = u.select_atoms("name A").select_atoms("around 15 name B")
s3 = u.select_atoms("name A").select_atoms("resname RA")

print(s1) # <AtomGroup [<Atom 1: A of type A of resname RA, resid 1 and segid SYSTEM>]>
print(s2) # <AtomGroup []>
print(s3) # <AtomGroup [<Atom 1: A of type A of resname RA, resid 1 and segid SYSTEM>]>
```
with `pair.gro`:
```
Written by MDAnalysis
   2
    1RA       A    1   0.000   0.000   0.000
    2RB       B    2   1.000   0.000   0.000
   5.00000  5.00000   5.00000
```

### Currently version of MDAnalysis:
`python3` with MDAnalysis f83498ec6

**Comment by orbeckst** [comment]
`s2` fails because the selection is done _within_ the group that only contains atom A, so "none" other is the correct answer. The docs are not very clear on this but there are two possible solutions:

## global
The  [global](https://www.mdanalysis.org/docs/documentation_pages/selections.html#preexisting-selections-and-modifiers) keyword should help:
```python
>>> s2 = u.select_atoms("name A").select_atoms("around 15 global name B")
```

## group
`group` keyword should also work (as in the docs, _Existing AtomGroup objects can be passed as named arguments, which will then be available to the selection parser_):

```python
>>> gB = u.select_atoms("name B")
>>> s2 = u.select_atoms("name A").select_atoms("around 15 group B", B=gB)
```

**Comment by ezavod** [comment]
Thanks, this makes perfectly sense. The docs regarding global selections is also very clear about that (after looking at them).
However I got the impression that this should work because of the examples [here](https://www.mdanalysis.org/docs/documentation_pages/core/groups.html?highlight=select_atoms#MDAnalysis.core.groups.AtomGroup.intersection) and [here](https://www.mdanalysis.org/docs/documentation_pages/core/groups.html?highlight=select_atoms#MDAnalysis.core.groups.ResidueGroup.intersection). These examples seem to use segments, that I associate with protein, on a water only selection.

The `group` keyword seems to behave different than one might think based on the docs. Your second example only works with an additional `global`.

**Comment by richardjgowers** [comment]
@ezavod yeah I think you're right about that being a bad example, I'll do a quick fix on that
