### ISSUE TITLE
option to turn off the mass match in alignto()

### ISSUE THREAD

**Issue by xiki-tempula** [MDAnalysis/mdanalysis#2285]
**Is your feature request related to a problem? Please describe.**
When one might want to convert the coarse-grain simulation to atomistic simulation, one will usually align the crystallographic protein to the coarse-grain protein. 

**Describe the solution you'd like**
Ideally, this should be done using 

```
from MDAnalysis.analysis.align import alignto
alignto(AT.atoms, CG.atoms, select=('name CA', 'name BB'))
```

However, since the mass of the CG backbone bead has a different mass from the CA atoms, the error `MDAnalysis.exceptions.SelectionError: Inconsistent selections, masses differ by more than 0.1; mis-matching atoms are shown above.`
 is raised and there isn't a way of turning this off.

**Comment by orbeckst** [comment]
A dirty workaround should be to set `tol_mass=1000` in [alignto()](https://www.mdanalysis.org/docs/documentation_pages/analysis/align.html#MDAnalysis.analysis.align.alignto).

**Comment by orbeckst** [comment]
@xiki-tempula did this do anything for you?

**Comment by xiki-tempula** [comment]
@orbeckst Thank you for the information. I kind of just did my own fork and move the raise exception part to the actions under `strict` keyword, so if `strict=False` then the exception won't get raised. However, I do notice that `strict=False` is set to False by Default so my method of disabling the mass checking when `strict=False` might not be good for naive users. Thus, I raise an issue and hope to see what are people's opinion on this.
