### ISSUE TITLE
AMBER topology files with negative ATOMIC_NUMBER fail to be parsed

### ISSUE THREAD

**Issue by pd15ms089** [MDAnalysis/mdanalysis#2306]
I simply want to use the code: u=MDAnalysis.Universe('topology.prmtop','coordinate.nc')

But this shows me a huge error, which is following...

--------------------------------------------------------------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-32-a7eeb5ed6b98> in <module>()
----> 1 u=MDAnalysis.Universe('topo.prmtop','prod01.nc')

/home/tcbg1/anaconda2/lib/python2.7/site-packages/MDAnalysis/core/universe.pyc in __init__(self, *args, **kwargs)
    288                 try:
    289                     with parser(self.filename) as p:
--> 290                         self._topology = p.parse(**kwargs)
    291                 except (IOError, OSError) as err:
    292                     # There are 2 kinds of errors that might be raised here:

/home/tcbg1/anaconda2/lib/python2.7/site-packages/MDAnalysis/topology/TOPParser.pyc in parse(self, **kwargs)
    213                         numlines += 1
    214 
--> 215                     attrs[name] = func(num_per_record, numlines)
    216 
    217                     def next_getter():

/home/tcbg1/anaconda2/lib/python2.7/site-packages/MDAnalysis/topology/TOPParser.pyc in parse_elements(self, num_per_record, numlines)
    386         """
    387         vals = self.parsesection_mapper(
--> 388                 numlines, lambda x: NUMBER_TO_ELEMENT[int(x)])
    389         attr = Elements(np.array(vals, dtype=object))
    390         return attr

/home/tcbg1/anaconda2/lib/python2.7/site-packages/MDAnalysis/topology/TOPParser.pyc in parsesection_mapper(self, numlines, mapper)
    525                 val = l[x.entries[j].start:x.entries[j].stop].strip()
    526                 if val:
--> 527                     section.append(mapper(val))
    528         return section
    529 

/home/tcbg1/anaconda2/lib/python2.7/site-packages/MDAnalysis/topology/TOPParser.pyc in <lambda>(x)
    386         """
    387         vals = self.parsesection_mapper(
--> 388                 numlines, lambda x: NUMBER_TO_ELEMENT[int(x)])
    389         attr = Elements(np.array(vals, dtype=object))
    390         return attr

KeyError: -1
--------------------------------------------------------------------------------------------------------------------------------

Please help me regarding this.

**Comment by orbeckst** [comment]
From the error I can only surmise that the Amber topology reader cannot make sense of your topology file. Can you please attach `topo.prmtop` to this issue report? (Your probably have to zip it and attach `topo.prmtop.zip`).

What version of Amber/AmberTools was used to create the file?

**Comment by orbeckst** [comment]
Note that the issue reporting system presents you with a template to fill out. It does help us if you follow the template.

As additional information we need

**Currently version of MDAnalysis**

- Which version are you using? (run `python -c "import MDAnalysis as mda; print(mda.__version__)"`)
- Which version of Python (`python -V`)?
- Which operating system?

**Comment by pd15ms089** [comment]
This is my topology file...
[topo.prmtop.zip](https://github.com/MDAnalysis/mdanalysis/files/3448528/topo.prmtop.zip)
I have used Amber16 with AmberTools17 to make this.

**version informations**

> 
> MDAnalysis version is: 0.19.2
> python version is: Python 2.7.16 :: Anaconda, Inc.
> OS: linux

-------------------------------------------------------------------------------------------------------------------------------------

**Comment by IAlibay** [comment]
Hi,

Just had a look through that topology file, it's the first time I've seen negative numbers values in the ATOMIC_NUMBER field. Looks like they relate to the C1 atoms of the CL3 residues.

@pd15ms089 would you be willing to share more details about how this was parameterised? (force field type + leaprc arguments if possible)?

**Comment by pd15ms089** [comment]
Yeah,
the force fields and leap file arguments are here

`source leaprc.protein.ff14SB`
`source oldff/leaprc.ff14SB`
`loadamberparams frcmod.chcl3`
`mol=sequence{amino acid sequence}`
`solvatebox mol CHCL3BOX 10.0`
`saveamberparm mol topo.prmtop coor.rst`
`quit`

PS: I don't know whether this information will help you or not, I checked that VMD could successfully load the parameter file.

**Comment by pd15ms089** [comment]
@orbeckst and @IAlibay please update me when you will get any solution to this.

**Comment by IAlibay** [comment]
Ok, so an update on this. I can confirm that the bug is due to the presence of negative values in the ATOMIC_NUMBER section (lines 179 to 240 in the provided topology file). Switching them from -1 to 6 seems to fix the problem (note: I haven't gone beyond just checking that the topology gets loaded properly).

From my understanding of how most of the AMBER code works, the ATOMIC_NUMBER fields aren't really used for much (don't quote me on this). So it is probable that this is a valid topology for use with the AMBER MD engines even though it doesn't adhere fully to the AMBER parm7 convention. Since MDAnalysis relies on the ATOMIC_NUMBER values to get element types for each atom, it ends up failing because no element has an atomic number of -1. 

I'm still trying to find out why this is happening within an AMBER context, and if it's expected behavior. If it's ok with you @pd15ms089 I might query this on the AMBER list?

With regards to code fixes, I'll default to @orbeckst here, as I am not very versed in the different ways elements are guessed in MDAnalysis. Off the top of my head, the best I could think of in the short term is to add an exception in ```NUMBER_TO_ELEMENT``` to catch the error and fail in a more descriptive manner.

**Comment by richardjgowers** [comment]
Yeah as a short term fix catching bad element numbers so this file loads with warnings is a good idea. Then maybe we can get smarter and recognise UA atoms as a later feature addition is good.
  

  
  

  
  
>

**Comment by pd15ms089** [comment]
> Ok, so an update on this. I can confirm that the bug is probably due to the presence of negative values in the ATOMIC_NUMBER section (lines 179 to 240 in the provided topology file). Switching them from -1 to 6 seems to fix the problem (note: I haven't gone beyond just checking that the topology gets loaded properly).
> 
> From my understanding of how most of the AMBER code works, the ATOMIC_NUMBER fields aren't really used for much (don't quote me on this). So it is probable that this is a valid topology for use with the AMBER MD engines even though it doesn't adhere fully to the AMBER parm7 convention. Since MDAnalysis relies on the ATOMIC_NUMBER values to get element types for each atom, it ends up failing because no element has an atomic number of -1.
> 
> I'm still trying to find out why this is happening within an AMBER context, and if it's expected behavior. If it's ok with you @pd15ms089 I might query this on the AMBER list?
> 
> With regards to code fixes, I'll default to @orbeckst here, as I am not very versed in the different ways elements are guessed in MDAnalysis. Off the top of my head, the best I could think of in the short term is to add an exception in `NUMBER_TO_ELEMENT` to catch the error and fail in a more descriptive manner.

It would be really helpful in that way. Can you please raise this issue in amber community. And please keep me in that thread.

**Comment by orbeckst** [comment]
@pd15ms089 
> please update me when you will get any solution to this.

If you haven't done so already I suggest you configure your GitHub settings in such a way that you are notified of any changes/comments to an issue that you authored. We use this issue to discuss the case. If we can think of a solution we will have a PR that is linked to this issue. And when we solve the problem, this issue will be closed.

Any help you can give is appreciated – everybody here is very busy and does work here on the side.

**Comment by pd15ms089** [comment]
Ok. And thank you all for providing such an active community.

**Comment by orbeckst** [comment]
Regarding guessing: if we guess anything here, we should warn the user (issue #2222) as @richardjgowers  said https://github.com/MDAnalysis/mdanalysis/issues/2306#issuecomment-516941545

**Comment by orbeckst** [comment]
@pd15ms089 you can try the development version with the fix for this issue . See https://github.com/MDAnalysis/mdanalysis/wiki/FAQ#how-do-i-use-the-development-version 

Let us know how if it works for you.

Thanks @IAlibay for the quick fix!

**Comment by pd15ms089** [comment]
Thank you for such a quick fix, however I have not tried yet. Let me get
how to try the development version from that link.
Next I will get back to you soon.

**Comment by pd15ms089** [comment]
Thank you very much. The development version worked perfectly. While
loading the parameter file it just showed an warning about the issue with
Atomic_number, but it loaded perfectly and it worked fine with the
trajectory.nc file as well.

Thanks again for your help.
