### ISSUE TITLE
Issue Tracker Move

### ISSUE THREAD

**Issue by GoogleCodeExporter** [MDAnalysis/mdanalysis#231]
```
See MoveToGitHub :

1. check if there are any open issues that have attachments. If yes, then

2. download the attachments from all open issues and store them in individual 
directories named IssueNNN/CommentMM with the original file names (NNN is the 
issue id number, eg 055 for Issue 55 and MM is the comment number, eg 01 for 
comment #1 or 00 for the initial issue report).

3. prepare a zip file (and wait for further instructions until we figure out a 
way to put everything back together) 

This has to be done BEFORE the move starts so that we are sure we have 
everything.
```

Original issue reported on code.google.com by `orbeckst` on 28 Mar 2015 at 1:28
- Blocking: #223, #233

**Comment by orbeckst** [comment]
Apparently, attachments were stored in a special place on google servers and automatically linked. Not sure for how long they will exist there so @richardjgowers keep the zip file ;-) — but I think we don't have to do anymore. In the future we need to find a way to add attachments, maybe through [gists](https://gist.github.com/)?

**Comment by richardjgowers** [comment]
Gists work, but not for binary files, ie trajectory samples, so that's going to be a bit annoying.
