### ISSUE TITLE
Regarding MSD 

### ISSUE THREAD

**Issue by omkantnirala** [MDAnalysis/mdanalysis#2315]
Hello everyone,
i Am trying to calculate MSD value through MDAnalysis  tool. The MSD value is not getting started on y-axis. Can anyone tell me where is the error in code.

`import MDAnalysis
from MDAnalysis.analysis.waterdynamics import MeanSquareDisplacement as MSD

u = MDAnalysis.Universe('nptmd.tpr','nptmd.xtc')
selection = "resname SOL"
MSD_analysis = MSD(u, selection, 0, 1000, 20)
MSD_analysis.run()
#now we print data ready to graph. The graph
#represents MSD vs t
time = 0
for msd in MSD_analysis.timeseries:#assert_almost_equal(msd.timeseries[1], 0.03984,decimal=5)
      print("{time} {msd}".format(time=time, msd=msd))
      time += 1

#Plot
plt.xlabel('time')
plt.ylabel('MSD')
plt.title('MSD')
plt.plot(range(0,time),MSD_analysis.timeseries)
plt.show()`

**Comment by orbeckst** [comment]
See https://groups.google.com/d/msg/mdnalysis-discussion/fjpA1JTYX88/lvSe-2L2EgAJ
