### ISSUE TITLE
GSD tests fail with gsd=1.8.0

### ISSUE THREAD

**Issue by IAlibay** [MDAnalysis/mdanalysis#2317]
**Expected behavior**

Issue for python 2.7:
```pytest test_gsd.py``` (for in both the /coordinates and /topology sections) should not fail.

**Actual behavior**

If using gsd=1.7.0, all tests will run fine, however the recently released version 1.8.0 is causing TypeError failures (unicode expected instead of str in gsd.fl.open).

An example case of this issue can be seen in: https://travis-ci.com/MDAnalysis/mdanalysis/jobs/222694436

**Currently version of MDAnalysis**

- Which version are you using?
0.19.3-dev
- Which version of Python (`python -V`)?
Python 2.7.15 (Tests in 3.6 do not fail)
- Which operating system?
Ubuntu 18.04 LTS

**Comment by richardjgowers** [comment]
Looks like a py2/3 thing upstream in gsd. Iirc they have a bit bucket issue tracker. Can see if there’s an easy fix, if not pin to below a certain version of gas until we drop py2 support

**Comment by IAlibay** [comment]
@richardjgowers Just had a look through their PR history, looks like py2.7 got dropped: https://github.com/glotzerlab/gsd/pull/28

I'm assuming somehow it didn't get reflected in their conda build.

**Comment by IAlibay** [comment]
@richardjgowers Considering the lack of support for py2.7 in GSD 1.8.0, do you mind if I create a PR pinning travis to 1.7.0?

**Comment by orbeckst** [comment]
As a quickfix we  pin our test version (add a comment so that we can revert once upstream conda has been fixed). It's too annoying when our CI fails everywhere (e.g. PR #2297 #2314  )

Who maintains the gsd conda build? File an issue their to make sure it is only build for the supported Python versions, please, because for some reason we try to install
```
gsd-1.8.0                  |   py27hc1659b7_0         100 KB  conda-forge
```

**If gsd 1.8.0 does not support 2.7 then there should not be a 1.8.0 package for py27.**

**Comment by IAlibay** [comment]
@orbeckst It looks like the GSD team maintain their conda-forge bulid (https://github.com/conda-forge/gsd-feedstock). 

I have raised an the issue on their bug tracker.

**Comment by mattwthompson** [comment]
Glotzer's lab (HOOMD-Blue, GSD, and others) migrated from bitbucket to here earlier this year. For mbuild, Josh recommended we pin GSD to 1.7 until we drop Python 2.7. We've been looking for reasons to drop 2.7, so we are going ahead with that. But I know here you have a more thorough plan for that process here, so temporarily pinning to 1.7 seems like the right move.

**Comment by orbeckst** [comment]
Thanks for the information. Hopefully the incorrect conda package gets fixed nevertheless, it's not good if the package system gets polluted.

("Thorough plan" is a very charitable reading of #2303 ... I'd say "planning in process")
