### ISSUE TITLE
Export Google Code repository to GitHub

### ISSUE THREAD

**Issue by GoogleCodeExporter** [MDAnalysis/mdanalysis#233]
```
For details see MoveToGitHub and Issue 223.

1. remove commit access to Google Code from everyone

2. create a final snapshot (via Takeout) of the project and save the admin and 
people data

3. use the Export Wizard to transfer the repository to GitHub (code history, 
issue tracker (without attachments), wiki)

4. split off applications into individual repositories

5. set up new access lists (based on the currently active committors) 
```

Original issue reported on code.google.com by `orbeckst` on 28 Mar 2015 at 1:35
* Blocking: #223, #234
* Blocked on: #231, #232

**Comment by orbeckst** [comment]
Transfer completed. Please update your remote repository designations:

    git remote rename origin googlecode
    git remote add origin git@github.com:MDAnalysis/mdanalysis.git

This should be sufficient to use the new repository, for instance, update your develop branch:

    git pull origin develop
