### ISSUE TITLE
make guessers more consistent and transparent

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/mdanalysis#2348]
**Expected behavior**

- Code should only guess when authorized by the user (see #2222 ).
- If property cannot be guessed (atom types, bonds, masses) then a proper error message or warning should alert the user and suggest how to enable guessing.
- Users should be able to override guesses.
- Guessers should use the best available approach.

**Actual behavior**

- Masses are always guessed, sometimes incorrectly (#2222); users cannot opt-out of guessing
- Masses are *always* guessed from `atom_types`, https://github.com/MDAnalysis/mdanalysis/blob/d1b0e659329b1d98fc2422c88614a196976f3497/package/MDAnalysis/topology/guessers.py#L41 , which are either highly forcefield dependent and cannot be used with our simple guesser (fails https://github.com/MDAnalysis/mdanalysis/blob/d1b0e659329b1d98fc2422c88614a196976f3497/package/MDAnalysis/topology/guessers.py#L58 ) or we guess the atom type anyway from the `atomname` https://github.com/MDAnalysis/mdanalysis/blob/d1b0e659329b1d98fc2422c88614a196976f3497/package/MDAnalysis/topology/guessers.py#L98 Instead it would make more sense for masses of atoms to *first determine the element* because this gives a unique mass. If we have to guess then the following might be better:
   1. guess masses from original  atom_types if they exist
   2. guess any remaining undefined (0) masses from the atom names.
   3. (optional: also guess other masses from atom names and compare with masses guessed from types; warn if there are discrepancies)
- Bond-guessing is fragile: it may not work if atom_types are not defined and throw a `ValueError`, see #2143

**Existing discussions**
- #598 for "fancy guessers" 
- #942 had a long discussion on the different required and optional topology attributes (ordered by categories), summarized in [Wiki: Topology attribute handling](https://github.com/MDAnalysis/mdanalysis/wiki/Topology-attribute-handling)
- print warnings when guessing (#2222) – this is implemented for mass guessers
- bond guessing can fail #2143

**Code to reproduce the behavior**

Example for bad mass guessing from atom_types
``` python
import MDAnalysis as mda
from MDAnalysis.tests import datafiles
import numpy as np

u = mda.Universe(datafiles.PDBQT_input)

not_guessed = u.atoms[u.atoms.masses == 0]
print("Missing masses: {}/{}".format(not_guessed.n_atoms, u.atoms.n_atoms))
print("Types without masses:", set(not_guessed.types))

# guessing by name finds all masses
masses_from_name = np.array([mda.topology.guessers.guess_atom_mass(name) for name in not_guessed.names])
print("Guessed masses from missing with name: {}/{}".format(sum(masses_from_name != 0), not_guessed.n_atoms))

# even guessing again from the types improves
masses_from_types_again = np.array([mda.topology.guessers.guess_atom_mass(atype) for atype in not_guessed.types])
print("Guessed masses (again) from missing with type: {}/{}".format(sum(masses_from_types_again != 0), not_guessed.n_atoms))
print("Types without masses:", set(not_guessed[masses_from_types_again == 0].types))
```
gives
```
~/anaconda3/envs/mda3/lib/python3.6/site-packages/MDAnalysis/topology/guessers.py:80: UserWarning: Failed to guess the mass for the following atom types: A
  warnings.warn("Failed to guess the mass for the following atom types: {}".format(atom_type))
~/anaconda3/envs/mda3/lib/python3.6/site-packages/MDAnalysis/topology/guessers.py:80: UserWarning: Failed to guess the mass for the following atom types: HD
  warnings.warn("Failed to guess the mass for the following atom types: {}".format(atom_type))
~/anaconda3/envs/mda3/lib/python3.6/site-packages/MDAnalysis/topology/guessers.py:80: UserWarning: Failed to guess the mass for the following atom types: OA
  warnings.warn("Failed to guess the mass for the following atom types: {}".format(atom_type))
Missing masses: 726/1805
Types without masses: {'HD', 'OA', 'A'}
Guessed masses from missing with name: 726/726
Guessed masses (again) from missing with type: 580/726
Types without masses: {'A'}
```
I actually don't understand why on parsing the topology, the types HD, OA, and A cannot be used for guessing the mass but later HD and OA work and only A fails:
```
u = mda.Universe(datafiles.PDBQT_input)
ng = np.array([mda.topology.guessers.guess_atom_mass(atype) for atype in u.atoms.types]) == 0
print("No masses for types ", set(u.atoms[ng].types))
```
Again, warnings as above, but then `No masses for types  {'A'}` only.

**Currently version of MDAnalysis**

0.20.1

**Comment by RMeli** [comment]
Related discussions:
* [Issue #2265](https://github.com/MDAnalysis/mdanalysis/issues/2265), [PR #2331 #](https://github.com/MDAnalysis/mdanalysis/pull/2331)
* [PR #1808](https://github.com/MDAnalysis/mdanalysis/pull/1808)

**Comment by orbeckst** [comment]
See also #2349

**Comment by richardjgowers** [comment]
See also:

```
In [70]: mda.topology.guessers.guess_atom_element('Zn')                                                                                     
Out[70]: 'N'
```

-_-

**Comment by richardjgowers** [comment]
Also my solution which maybe could make it into mda

```python                                                                                                 
from periodictable import elements
from fuzzywuzzy import process


_ELEMS = {elem.symbol for elem in elements
          if not elem.symbol == 'n'}
_RESULT_CACHE = {}

def to_element(thing):
    try:
        return _RESULT_CACHE[thing]
    except KeyError:
        stripped_thing = thing.strip('1234567890')
        if stripped_thing in _ELEMS:
            ret = stripped_thing
        else:
            ret, score = process.extractOne(thing, _ELEMS)
            # if score < something: throw a tantrum                                                                                         
        _RESULT_CACHE[thing] = ret
        return ret
```

**Comment by Charly-Empereur-mot** [comment]
I tried this, but it still guesses the atom types and masses:
`universe = mda.Universe(aa_coord, aa_traj, guess_types=False, guess_masses=False, guess_bonds=False, guess_angles=False, guess_dihedrals=False)`
Instead, I would like to fill the atom types and masses manually (no idea how to do this, please suggest!) or better, from an ITP file.

I believe this issue is critical to solve, it has impact on basically everything. Also reading types and masses makes no sense if you work with coarse-grained trajectories.

**Comment by RMeli** [comment]
To add on this issue, I think the name of `guess_masses` is misleading. In fact this function does not call `guess_atom_mass` but `get_atom_mass`. `get_masses` could be a better name?

**Comment by AnshulAngaria** [comment]
@orbeckst , I want to work on this issue. Any guidance?

**Comment by orbeckst** [comment]
This is a complicated issue. Start by reading everything that is linked in this issue and try to get an idea of what the problem is. If you want to work on it, don’t try to solve everything, start with a partial solution.
