### ISSUE TITLE
issues reading a pdbqt file

### ISSUE THREAD

**Issue by metma99** [MDAnalysis/mdanalysis#2349]
Hello:
I am a new user of the mdanalysis tools and sent my issue to the google maoling list. Oliver Beckstein encouraged me to file a bug report. I will include my original email and his answer:

my message:

I just downloaded the tool and would like to run some tests.
One of them is reading a pdbqt file like

from MDAnalysis import Universe
u = Universe('./pdbqt_inputpdbqt.pdbqt')

This throws me a Userwarning:
.../MDAnalysis/topology/guessers.py: 80: UserWarning: Failed to guess the mass for the following atom types: A or HD or OA

Please note the pdbqt file is copied from the accompanying data folder.

Anybody knows what is going on?

Oliver's answer:
PDBQT files do not contain masses so the PDBQT parser tries to make a guess at the masses. Some (many) of these guesses fail (see below). It’s not immediately clear to me how some “obvious” atom names such as “O”  are not guessed correctly. 

If I guess again on these names, I get all masses (see below). 

This looks like a problem with the PDBQT parser to me.

Can you please raise an issue at https://github.com/mdanalysis/mdanalysis/issues with what you found (and you can copy and paste my response, too). I can’t promise that this will get fixed immediately but with the issue at hand we won’t forget.

By the way, if you don’t need masses for your analysis (e,g. you don’t use center_of_mass()) then this should not be a problem.

Thank you all of your time!
Markus

**Comment by orbeckst** [comment]
@metma99 a workaround for the moment, if you need masses: Guess the missing masses and set them manually:
```python
import MDAnalysis as mda
from MDAnalysis.tests import datafiles

# exampl file – use your own
u = mda.Universe(datafiles.PDBQT_input)

# AtomGroup with 0 masses
not_guessed = u.atoms[u.atoms.masses == 0]

# guess from name
masses_from_name = [mda.topology.guessers.guess_atom_mass(name) for name in not_guessed.names]

# change 0 masses to newly guessed masses
u.atoms.masses[not_guessed] = masses_from_name
```

You can also guess all masses if you like, using 
```python
u.atoms.masses = [mda.topology.guessers.guess_atom_mass(name) for name in u.atoms.names]
```

**Comment by metma99** [comment]
Thank you very much
