### ISSUE TITLE
continuous=True doesn't work in Universe.__init__ for PDB files

### ISSUE THREAD

**Issue by lilyminium** [MDAnalysis/mdanalysis#2353]
**Expected behavior**

A clear and concise description of what you want to do and what you think should happen. (Code to reproduce the behavior can be added below).

Calling `Universe.__init__(PDB, XTC, XTC, continuous=True)` should give me a trajectory with continuous time steps, per the documentation. 

> continuous: bool, default ``False``
        The `continuous` option is used by the
        :mod:`ChainReader<MDAnalysis.coordinates.chain>`, which contains the
        functionality to treat independent trajectory files as a single virtual
        trajectory.

**Actual behavior**

It dies at this part of ChainReader:
```python
# calculate new start_frames to have a time continuous trajectory.
        if continuous:
            filetypes = np.unique([r.format for r in self.readers])
            if not len(filetypes) == 1:
                raise ValueError("ChainReader: continuous=true only supported"
                                 " when all files are using the same format. "
                                 "found {}".format(filetypes))
            if np.any(np.array(n_frames) == 1):
                raise RuntimeError("ChainReader: Need at least two frames in "
                                   "every trajectory with continuous=True")
            if filetypes[0] not in ['XTC', 'TRR']:
                raise NotImplementedError("ChainReader: continuous=True only "
                                          "supported for xtc and trr format")
```

For some reason, the PDBReader 'format' is a list: ['PDB', 'ENT'] and the full list of reader formats is therefore [['PDB', 'ENT'], 'XTC',  'XTC']. Calling `np.unique` on a list with lists in it makes it unhappy. 

**Code to reproduce the behavior**

```pycon
Python 3.6.7 | packaged by conda-forge | (default, Jul  2 2019, 02:07:37)
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import MDAnalysis as mda
>>> from MDAnalysis.tests.datafiles import PDB, GRO, XTC
>>> mda.__version__
'0.19.2'
>>> u1 = mda.Universe(PDB, XTC, XTC, all_coordinates=True, continuous=False)
/boring/path/MDAnalysis/coordinates/base.py:836: UserWarning: Reader has no dt information, set to 1.0 ps
  warnings.warn("Reader has no dt information, set to 1.0 ps")
>>> u1 = mda.Universe(PDB, XTC, XTC, all_coordinates=True, continuous=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "boring/path/MDAnalysis/core/universe.py", line 335, in __init__
    self.load_new(coordinatefile, **kwargs)
  File "boring/path/MDAnalysis/core/universe.py", line 602, in load_new
    self.trajectory = reader(filename, **kwargs)
  File "boring/path/MDAnalysis/coordinates/chain.py", line 277, in __init__
    filetypes = np.unique([r.format for r in self.readers])
  File "boring/path/numpy/lib/arraysetops.py", line 264, in unique
    ret = _unique1d(ar, return_index, return_inverse, return_counts)
  File "boring/path/numpy/lib/arraysetops.py", line 312, in _unique1d
    ar.sort()
TypeError: '<' not supported between instances of 'str' and 'list'
```

**Currently version of MDAnalysis**

- Which version are you using? (run `python -c "import MDAnalysis as mda; print(mda.__version__)"`)
0.19.2
- Which version of Python (`python -V`)?
3.6.8
- Which operating system?

**Also**

It should probably be better documented that `continuous=True` only works for trajectories with > 1 frame.

**Comment by orbeckst** [comment]
Does adding a PDB file as a topology actually add one frame to the chained trajectory? That shouldn't happen... in particular, I think we should never use the coordinates from a PDB file that is solely used as a toplogy. (It drives me crazy that VMD does it and I have to delete the first set of coordinates every time...)

**Comment by lilyminium** [comment]
> Does adding a PDB file as a topology actually add one frame to the chained trajectory? That shouldn't happen... in particular, I think we should never use the coordinates from a PDB file that is solely used as a toplogy. (It drives me crazy that VMD does it and I have to delete the first set of coordinates every time...)

It doesn't automatically -- in this case, I specified `all_coordinates=True`. Happy to close the issue if this is an unlikely situation.

**Comment by kain88-de** [comment]
The error message is still wrong. I added a fix for that.
