### ISSUE TITLE
Contact analysis does not respect PBC

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/mdanalysis#2368]
**Expected behavior**

* Contact analysis should be able to calculate distances with PBC taken into account.
* There should be a kwarg that allows me to select if I want to use PBC or not.
* At a *minimum* the behavior should be documented as not PBC save.

**Actual behavior**

Code review of `contacts.Contacts`, specifically https://github.com/MDAnalysis/mdanalysis/blob/9372d093acebb78bc5b1a2b4dba815a4e3281b04/package/MDAnalysis/analysis/contacts.py#L430-L432 (and other parts of the code) shows that [`distance_array()`](https://www.mdanalysis.org/docs/documentation_pages/lib/distances.html?highlight=distance_array#MDAnalysis.lib.distances.distance_array) is never called with the `box=ts.dimensions` argument, therefore will never take PBC into account.

(If the class is used on trajectories where intra-molecule contacts are analyzed for a molecule that is whole then no problems arise. However, for molecules broken across PBC or for inter-molecule contacts such as multiple peptides in solution, some contacts will be missed and the contact count is *too low*.)

**Code to reproduce the behavior**

Based on code review.

**Currently version of MDAnalysis**

current develop (0.21-dev)

**Comment by orbeckst** [comment]
The datafiles.XTC trajectory might be a good test case as it contains the AdK protein, broken across the box.

**Comment by orbeckst** [comment]
Other things to fix
- It is  clunky that I have to provide *selections* instead of AtomGroups for `Contacts(..., selections=...))` to indicate which groups the contacts are formed between. I should be able to use static AtomGroups (cannot be dynamic). See #2369 
- The https://github.com/MDAnalysis/mdanalysis/blob/9372d093acebb78bc5b1a2b4dba815a4e3281b04/package/MDAnalysis/analysis/contacts.py#L464 helper function can just use `Universe.copy()`.

**Comment by lilyminium** [comment]
Would switching:
```diff
--- self.r0.append(distance_array(refA.positions, refB.positions))
+++ self.r0.append(distance_array(refA.positions, refB.positions, 
+++                               refA.universe.dimensions))
```

and 
```diff
--- d = distance_array(self.grA.positions, self.grB.positions)
+++ d = distance_array(self.grA.positions, self.grB.positions, 
+++                    self._ts.dimensions)
```

do it?

As you said, a test case could be a universe `u = mda.Universe(TPR, XTC)` where you check that the distance arrays in `Contacts.r0` match the expected distance array computed using a box. Another could be comparing the results of the contact analysis on the normal, broken trajectory vs. running the analysis on a universe that has been made whole.

**Comment by orbeckst** [comment]
I assume that your change https://github.com/MDAnalysis/mdanalysis/issues/2368#issuecomment-590008443 is the key thing that needs to be changed. Of course, this will need tests and documentation. But that makes it a good starter issue.

**Comment by ss62171** [comment]
@orbeckst I would like to claim this issue.

**Comment by orbeckst** [comment]
We don't do claims. Put up a PR and show that you are actively working on the issue. Make sure that your PR references this issue number so that it gets automatically linked.

**Comment by ss62171** [comment]
@orbeckst I added a test for checking distances taking PBC into account, couldn't figure out why distances calculated are so different. Any suggestion how to do this?

**Comment by ss62171** [comment]
> Other things to fix
> 
>     * It is  clunky that I have to provide _selections_ instead of AtomGroups for `Contacts(..., selections=...))` to indicate which groups the contacts are formed between. I should be able to use static AtomGroups (cannot be dynamic). See #2369
> 
>     * The https://github.com/MDAnalysis/mdanalysis/blob/9372d093acebb78bc5b1a2b4dba815a4e3281b04/package/MDAnalysis/analysis/contacts.py#L464
>        helper function can just use `Universe.copy()`.

Do i need to fix this in different PR?
