### ISSUE TITLE
density profiles from mda.analysis.density.density_from_universe does not conserve number of atoms

### ISSUE THREAD

**Issue by MatKie** [MDAnalysis/mdanalysis#2372]
Hello 

Expected behavior:
I'm currently trying to calculate liquid and vapour densities from liquid slab MD simulations using density profiles. For this purpose I read a trajectory into an universe and add the center_in_box(center="mass", wrap=True) and a subsequent pack_into_box transformation, to get the liquid slab centered in the original box.

After this I call mda.analysis.density.density_from_universe() with a predefined box and center (see Issue #1928). The predefined box has padding in xy direction but not in z direction and the delta is chosen to exactly fit the box in z direction (as this is the elongated axis along which we go from vapour to liquid slab back to vapour). As a check, I calculate the sum over the returned three dimensional array and compare it to number of atoms in the trajectory. 

Actual behavior:
The actual behaviour is that the number of atoms is smaller than the number of atoms in the trajectory. This behaviour is independent of the padding in z direction (I tried to add padding), but i found out that its dependent on the delta keyword. Only for delta = 1 I get the right number of atoms. If I choose delta>1 I get lower number of atoms and for delta<1 I get higher number of atoms. This is consistent over multiple trajectories (simulations at different temperature but same number of atoms). 

**Code to reproduce the behavior**

``` python
    

    import MDAnalysis.analysis.density as DENS
    from MDAnalysis.transformations import center_in_box
    import MDAnalysis as mda
    
    box=None
    def put_in_box(atoms):
        # Put atoms in box during each call of the trajectory
        def wrapped(ts):
            ts.positions = atoms.pack_into_box(box=None, inplace=True)
            return ts
        return wrapped


    sys = mda.Universe(LAMMPS_DATAFILE, 
                       XTC/XYZ_TRAJECTORY,
                       atom_style='id type x y z')
    
    # If trajectory does not hold box infos, define yourself
    # This could usually also be done with the datafile...
    if box is not None:
        sys.universe.dimensions = box

    # PBC
    sys.atoms.pack_into_box(box=None, inplace=True) 

    # Center slap at COM + PBC
    workflow = [center_in_box(sys.atoms, center='mass', wrap=True), 
                put_in_box(sys.atoms)]       
    sys.trajectory.add_transformations(*workflow)

    # Get box dimensions and padding in xy directions. Define delta, so that
    # an integer number of bins fits in z direction
    xydim = sys.dimensions[0]
    zdim  = sys.dimensions[2]
    pad = 0.0
    zpad = 0.0
    #delta = (zdim+zpad)/(int(zdim))
    delta = 1.0 
    # Call Density object, disregard first 300 frames and define box manually.
    Dens = DENS.density_from_Universe(sys, atomselection="all", start=300, 
                                      xdim=xydim+pad, 
                                      ydim=xydim+pad, 
                                      zdim=zdim+zpad, 
                                      gridcenter=[xydim/2,xydim/2,zdim/2],
                                      delta=delta) 
    # Calculate Centers of density profile in z direction and initialise
    # density vector
    _, _, edges_z = Dens.edges
    dim_z = len(edges_z) - 1
    dens_z = np.zeros((dim_z,1))

    # Calculate Density profile and give warning if atoms are less
    # than expected
    for i in range(dim_z):
        dens_z[i] = np.sum(Dens.grid[:, :, i])
    print("Atoms: ", np.sum(dens_z))
    print("Atoms: ", np.sum(Dens.grid[:, :, :]))
....

```

Currently version of MDAnalysis:
- Which version are you using? 0.19.2
- Which version of Python: Python 3.73
- Which operating system: Linux, Ubuntu 18.04.3

**Comment by IAlibay** [comment]
@MatKie When you mention "padding", do you mean you vary the values of `pad` and `zpad` in the above example code, or you use the padding flag?

I am realising that I didn't add sufficient checks / warnings to let users know that the padding flag isn't used in user defined boxes...

I might be wrong, but I believe what's happening is that the density returned by density_from_universe is a `physical density` i.e. counts per A**3, rather than a histogram of the atom counts. At A == 1 A, the values return as counts / 1 (i.e. the underlying atom counts), which explains why this is the only case that yields the expected number of atoms.

**Comment by MatKie** [comment]
Yes, I was changing pad and zpad in the example above, but without influence on the atom count.

I think you are right. When I understand you correctly, each volume element in the returned density holds the density in this volume element rather than the number of atoms in this volume element. If a a different edge length of that volume element is chosen, delta != 1.0, the total number of atoms is wrongly estimated by a factor of 1/delta^3. I ran some different delta values and this seems to be the case. 
I don't think this is a bug, but the implications of choosing a different delta on the returned values weren't obvious to me from the documentation.

Thanks for the help!

**Comment by IAlibay** [comment]
Tagging @lilyminium & @orbeckst regarding possible user guide stuff (apologies if it's already in there).

I'll try to get a PR out in the next few days that adds extra details on the nature of the density grid in the `density_from_universe` docstring (in addition to some extra safety checks related to https://github.com/MDAnalysis/mdanalysis/issues/2372#issuecomment-545864248).

**Comment by orbeckst** [comment]
If you look at https://www.mdanalysis.org/docs/documentation_pages/analysis/density.html 

> The positions of all water oxygens are histogrammed on a grid with spacing delta = 1 Å. Initially the density is measured in Å−3
. With the Density.convert_density() method, the units of measurement are changed. In the example we are now measuring the density relative to the literature value of the TIP4P water model at ambient conditions (see the values in MDAnalysis.units.water for details). 

It says that the grid contains a density. If you want numbers, multiply the grid with the cell volume.
