### ISSUE TITLE
Can we make empty Universes?

### ISSUE THREAD

**Issue by lilyminium** [MDAnalysis/mdanalysis#2383]
**Is your feature request related to a problem? Please describe.**
Creating an empty Universe with 0 atoms raises an error. Sometimes with scripts and libraries that build on top of MDAnalysis it's a useful default before files are loaded.

**Describe the solution you'd like**
A Universe with 0 atoms.

**Describe alternatives you've considered**

**Additional context**
I have a branch that has this.

**Comment by richardjgowers** [comment]
I guess so... make a PR so we can see how ugly the hacks are to allow this?
