### ISSUE TITLE
Unnecessary tests

### ISSUE THREAD

**Issue by lilyminium** [MDAnalysis/mdanalysis#2387]
This test doesn't do anything with `parametrize`.

https://github.com/MDAnalysis/mdanalysis/blob/2501d3e014943286dcb123139e3028988c61718f/testsuite/MDAnalysisTests/topology/test_mmtf.py#L36-L59

**Comment by zemanj** [comment]
Should this read
`vals = getattr(u.atoms, attr)`
instead of
`vals = u.atoms.bfactors`?

**Comment by lilyminium** [comment]
Likely. #2390 adds tests to check for missing attributes to all parsers.
