### ISSUE TITLE
chainID behaviour with PDB files

### ISSUE THREAD

**Issue by lilyminium** [MDAnalysis/mdanalysis#2389]
**Expected behavior**

If my PDB file has a chainID column but not a segID column, my atoms have chainIDs.

**Actual behavior**

In this scenario, PDBParser uses the chainID column as `segids` and does not add ChainID topology attributes.

**Code to reproduce the behavior**

https://github.com/MDAnalysis/mdanalysis/blob/2501d3e014943286dcb123139e3028988c61718f/package/MDAnalysis/topology/PDBParser.py#L276-L294

**Currently version of MDAnalysis**

- Which version are you using? (run `python -c "import MDAnalysis as mda; print(mda.__version__)"`)
- Which version of Python (`python -V`)?
- Which operating system?

**Comment by orbeckst** [comment]
This just seems dumb – why don't we use 
```python
segids, chainids = chainids, chainids
```
instead?
