### ISSUE TITLE
AtomGroup.guess_bonds misleading documentation, could pass in fudge_factor

### ISSUE THREAD

**Issue by lilyminium** [MDAnalysis/mdanalysis#2395]
**Expected behavior**

https://github.com/MDAnalysis/mdanalysis/blob/971248a1cf099f26db899b899a8e10d4e96ac3cd/package/MDAnalysis/core/groups.py#L2918-L2926

AtomGroup.guess_bonds guesses bonds, only.

**Actual behavior**

It guesses bonds, angles, and dihedrals.

If the method is going to guess angles, it could guess improper dihedrals too from the angles.

**Code to reproduce the behavior**

Show us how to reproduce the failiure. If you can, use trajectory files from the test data.

https://github.com/MDAnalysis/mdanalysis/blob/971248a1cf099f26db899b899a8e10d4e96ac3cd/package/MDAnalysis/core/groups.py#L2937-L2961

**Currently version of MDAnalysis**

- Which version are you using? current develop branch

**Also**

It would be useful to be able to pass in `fudge_factor` and `lower_bound` kwargs to this method (to pass onto `guessers.guess_bonds`)

**Comment by richardjgowers** [comment]
So impropers are an odd case in that most impropers aren't used (as in have a potential associated with them) - they're mostly used to keep things planar.  So guessing them all would produce a lot of useless entries.

Passing in the other kwargs to guess_bonds makes sense

**Comment by soma2000-lang** [comment]
@lilyminium  Is this issue still open for working .Then I would like to take up this issue.

**Comment by xhgchen** [comment]
I am interested in looking into this further but unsure what changes need to be made exactly. Would someone be able to explain a little more clearly? I have looked around for the terms and found fudge_factor described in the guessing page (https://userguide.mdanalysis.org/stable/formats/guessing.html) but I am unsure what lower_bound means. Thanks!

**Comment by lilyminium** [comment]
@xhgchen the function ``guess_bonds`` (below) takes in the keyword arguments ``fudge_factor`` and ``lower_bound``. ``AtomGroup.guess_bonds`` calls this function but doesn't have these keyword arguments itself.  A fix to this issue would make those keyword arguments available to ``AtomGroup.guess_bonds``.

https://github.com/MDAnalysis/mdanalysis/blob/971248a1cf099f26db899b899a8e10d4e96ac3cd/package/MDAnalysis/topology/guessers.py#L157-L262

**Comment by xhgchen** [comment]
With all the new contributors coming in, I just want to say that I think this is a great starter issue to work on, especially since Lily has taken the time to explain things so clearly :)
