### ISSUE TITLE
Outdated documentation for AMBER TRJReader

### ISSUE THREAD

**Issue by lilyminium** [MDAnalysis/mdanalysis#2398]
**Expected behavior**

https://github.com/MDAnalysis/mdanalysis/blob/e12958ca0e6c5700563e236e21023c2b696489b7/package/MDAnalysis/coordinates/TRJ.py#L114-L124

https://github.com/MDAnalysis/mdanalysis/blob/e12958ca0e6c5700563e236e21023c2b696489b7/package/MDAnalysis/coordinates/TRJ.py#L208-L209

I cannot directly access frames of the trajectory by indexing. 

**Actual behavior**

I can directly access frames of the trajectory by indexing.

**Code to reproduce the behavior**

Show us how to reproduce the failiure. If you can, use trajectory files from the test data.

``` pycon
In [28]: import MDAnalysis as mda

In [29]: from MDAnalysis.tests.datafiles import PRM, TRJ

In [30]: trj = mda.Universe(PRM, TRJ)
/Users/lily/pydev/mdanalysis/package/MDAnalysis/topology/TOPParser.py:270: UserWarning: ATOMIC_NUMBER record not found, guessing atom elements based on their atom types
  warnings.warn(msg)

In [34]: trj.trajectory[2]
Out[34]: < Timestep 2 with unit cell dimensions [0. 0. 0. 0. 0. 0.] >

In [35]: t2 = trj.atoms.positions

In [36]: trj.trajectory[5]
Out[36]: < Timestep 5 with unit cell dimensions [0. 0. 0. 0. 0. 0.] >

In [37]: t5 = trj.atoms.positions

In [41]: np.array_equal(t2, t5)
Out[41]: False
```

**Currently version of MDAnalysis**

- Which version are you using? (run `python -c "import MDAnalysis as mda; print(mda.__version__)"`) 0.20.1
- Which version of Python (`python -V`)? 3.7.3
- Which operating system? MacOS

Just checking that I'm understanding this limitation correctly and can leave it out of the user guide.

**Comment by orbeckst** [comment]
The limitations are outdated. The reader creates offsets for random access.

(I think nowadays _all_ our readers support some form of random access (since PR #1086, see #314 for discussion).)

**Comment by richardjgowers** [comment]
Yeah this looks like docs I forgot to update in the ascii offset push.

**Comment by IAlibay** [comment]
@lilyminium My understanding from this is that all that's needed here is just to clean up the docstring (and maybe add a test)?

I'm planning to do some work on the AMBER readers. Unless you were planning on picking this one up, I can make the changes whilst I'm dealing with that file.

**Comment by lilyminium** [comment]
@IAlibay Yes, I think it's just the documentation here. Please go ahead!
