### ISSUE TITLE
Option for PQRWriter to mimic PDB2PQR without --whitespace option

### ISSUE THREAD

**Issue by chelsell** [MDAnalysis/mdanalysis#2407]
I'm working with a program that parses a PQR. It only works if the PQR it is importing _does not_ have the extra whitespaces you get from running `pdb2pqr --whitespace`. Since there is no option for MDA's PQRWriter to omit these extra whitespaces, I figured out the necessary alterations to MDAnalysis.coordinates.PQR.PQRWriter.fmt_ATOM:

```
fmt = ("ATOM {serial:6d} {name:<4} {resname:<3} {chainid:1.1}"
                "{resid:4d}     {pos[0]:-8.3f}{pos[1]:-8.3f}"
                "{pos[2]:-8.3f} {charge:-7.4f} {radius:6.4f}\n") # corrected formatting for no extra whitespaces
writer = mda.coordinates.PQR.PQRWriter(outfile)
writer.fmt_ATOM = fmt
writer.write(out)
```

This work around is fine, but since the pdb2pqr webserver writes the files sans extra whitespaces I can't be the only one that wants this format. Maybe consider just adding an extra keyword to mda.coordinates.PQR.PQRWriter like `whitespace: Bool =False` that if `True` uses the alternative formatting I give above? Thanks!

**Comment by orbeckst** [comment]
Hi @chelsell , thanks for raising the issue. 

PQR without white space is incredibly messy and we don't even attempt to parse it. We've mainly been following PDB2PQR and apbs's lead, which state for [PQR](https://apbs-pdb2pqr.readthedocs.io/en/latest/formats/pqr.html)
> APBS reads very loosely-formatted PQR files: all fields are whitespace-delimited rather than the strict column formatting mandated by the PDB format.

At the end says
> However, in order to maintain compatibility with most molecular graphics programs, the PDB2PQR program and the utilities provided with APBS attempt to preserve the PDB format as much as possible.

The phrase "as much as possible" strikes fear into the heart of anyone having to _maintain_ code to read and write files as it is not clear what this phrase means and how other code should deal with such files — we actually need the algorithm to implement such "as much as possible" reading/writing. We have been taking the conservative approach and just read and write white-space formatted files. In particular it's awkward when we write files that we might not be able to read ourselves. For these reasons it is not so simple for us to add such a seemingly innocent feature. I'll leave the issue open to see what  opinion you are anyone else might have.

In the meantime you could do in your own scripts
```python
import MDAnalysis as mda

class FixedPQRWriter(mda.coordinates.PQR.PQRWriter):
    fmt = ("ATOM {serial:6d} {name:<4} {resname:<3} {chainid:1.1}"
                "{resid:4d}     {pos[0]:-8.3f}{pos[1]:-8.3f}"
                "{pos[2]:-8.3f} {charge:-7.4f} {radius:6.4f}\n") # corrected formatting for no extra whitespaces

# example use
from MDAnalysis.tests import datafiles as data

u = mda.Universe(data.PQR)
with FixedPQRWriter("new.pqr") as W:
    W.write(u.atoms)
```

**Comment by chelsell** [comment]
I understand, thanks for the detailed response! I'm happy to close the issue and make the change you recommend locally, but someone might find it helpful one day.
