### ISSUE TITLE
unexpected behavior when iterating over trajectories with negative stride

### ISSUE THREAD

**Issue by hejung** [MDAnalysis/mdanalysis#2413]
Note, that `start < stop` in the following.

**Expected behavior**
When using `for ts in u.trajectory[start:stop:][::-1]` I expect to iterate over every frame from stop-1 to start, including both stop-1 and start.

**Actual behavior**
The iteration is empty. This would be the expected behavior for `for ts in u.trajectory[start:stop:-1]`.

**Code to reproduce the behavior**

``` python
import MDAnalysis as mda
from MDAnalysis.tests.datafiles import PSF, DCD,  GRO, PDB, TPR, XTC, TRR,  PRMncdf, NCDF

u = mda.Universe(PSF, DCD)

start = 0
stop = 5
print('unexpected empty iteration:')
for ts in u.trajectory[start:stop][::-1]:
    print(ts)

print('')
print('another empty iteration, but here it is expected:')
for ts in u.trajectory[start:stop:-1]:
    print(ts)

print('')
print('This is what we would expect to happen in the first case')
# Note that I have to leave out the end value of the iteration (start=0) because using 0 results in a different slice, i.e. without the zeroth frame of the trajectory
for ts in u.trajectory[stop-1::-1]:
    print(ts)

....

```

**Currently version of MDAnalysis**
MDAnalysis v0.20.1 from conda-forge on python v3.7.3
OS: Scientific Linux (kernel: 3.10.0-862.11.6.el7.x86_64)

**Comment by jbarnoud** [comment]
Thank you for reporting the issue. I will have a look.
