### ISSUE TITLE
Remove angle from [ settles ] constraints in ITPParser

### ISSUE THREAD

**Issue by lilyminium** [MDAnalysis/mdanalysis#2417]
**Expected behavior**

~If `[ settles ]` is a triangular constraint, shouldn't it add an angle as well as two bonds?~ **Edit: ITPParser only adds two bonds for SETTLE water, the way AMBER treats them.** 

**Actual behavior**

~TPRParser only adds two bonds.~

ITPParser adds two bonds *and* an angle.

https://github.com/MDAnalysis/mdanalysis/blob/3e8ea8e0744f3163ddbf7b4f5f66874dd26796a7/package/MDAnalysis/topology/ITPParser.py#L349-L365

~One or the other should change for consistent behaviour. Personally I think adding an angle makes sense, even if it is not very useful.~ It shouldn't add an angle.

There are existing tests that read `[ settles ]` directives, so changing the number of angles expected in those would suffice to test any solution to this issue.

**Currently version of MDAnalysis**

- Which version are you using? (run `python -c "import MDAnalysis as mda; print(mda.__version__)"`)
Develop branch
- Which version of Python (`python -V`)?
- Which operating system?

**Comment by jbarnoud** [comment]
The reasoning behind treating SETTLE as bonds is that it allowed to treat the water as fragments. I do not see the benefit of adding an angle as well; though I do not really use the angle topology attribute at all so I may just miss something.

**Comment by siddharthjain1611** [comment]
how many angles should one have?

**Comment by jbarnoud** [comment]
It should be the same as the itp parser. If we add angles here, it is for consistency sake.

**Comment by lilyminium** [comment]
I vote for water having an angle :-) (unless it has significant performance downsides?)

**Comment by IAlibay** [comment]
So to add to the conversation here, (i might be misremembering things here) but at least in view of the MD engine SETTLEd waters don't usually have an angle component.

Personally I'm not against the idea of enforcing that waters have angles, however adding it here for ITP files is likely to cause a discrepancy with say a TIP3P water loaded from an AMBER parm7 file (which by default will not have an angle entry).

**Comment by lilyminium** [comment]
That's a good point @IAlibay -- in that case I take back my earlier enthusiasm and suggest changing ITPParser to *not* add an angle for [ settles ] entries.

**Comment by siddharthjain1611** [comment]
Please allow me to work on this.
