### ISSUE TITLE
XYZ parser guesses the elements

### ISSUE THREAD

**Issue by jbarnoud** [MDAnalysis/mdanalysis#2420]
**Expected behavior**

The first column of a XYZ file is, [by definition](http://openbabel.org/wiki/XYZ_%28format%29), the element symbol (or the element number in the UniChem variant. The element being provided by the file, `AtomGroup.elements` should be filled and that should be used to guess the mass.

**Actual behavior**

The first column is treated as atom type and atom name, but not as element symbol. The elements are guessed in order to latter guess the masses. The `elements` attribute is not filled.

**Code to reproduce the behavior**

``` python
import MDAnalysis as mda
from MDAnalysis.tests.datafiles import XYZ

u = mda.Universe(XYZ)
u.atoms.elements
```

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-22-1d38b5e1bdf4> in <module>
      3 
      4 u = mda.Universe(XYZ)
----> 5 u.atoms.elements

~/dev/mdanalysis/package/MDAnalysis/core/groups.py in __getattr__(self, attr)
   2291             except selection.SelectionError:
   2292                 pass
-> 2293         raise AttributeError("{cls} has no attribute {attr}".format(
   2294             cls=self.__class__.__name__, attr=attr))
   2295 

AttributeError: AtomGroup has no attribute elements
```

**Currently version of MDAnalysis**

- Which version are you using? 0.20.2-dev0 4adbd6c01
- Which version of Python (`python -V`)?  `'3.8.0 | packaged by conda-forge | (default, Nov 22 2019, 19:11:38) \n[GCC 7.3.0]'`
- Which operating system? Ubuntu 18.04

**Comment by RMeli** [comment]
@jbarnoud Are you working on this (as part of #2442)? If not, I could give it a shot.

**Comment by jbarnoud** [comment]
@RMeli You are welcome to give this a shot :)

**Comment by richardjgowers** [comment]
FWIW, I think it's naive to think that this column will **always** be an element, I'd put money on the fact that @jbarnoud has written a martini system to xyz once :)  Adding that an xyz file will *try* and populate element seems like a great addition though.

**Comment by jbarnoud** [comment]
The test files indicate that the first column is occasionally an atom name. Though, I would argue that it is a misuse of the format. The XYZ format is not well suited for large systems with its lack of residues, it seems to be mostly used for small molecules and quantum calculations where the atom symbol makes the most sense. My experience with the format is still fairly limited, though.
