### ISSUE TITLE
Update Links on Wiki to reflect move to github

### ISSUE THREAD

**Issue by tylerjereddy** [MDAnalysis/mdanalysis#243]
We need to update URLs in the wiki to reflect the move from google code to github. See [Issue 240](https://github.com/MDAnalysis/mdanalysis/issues/240) for useful notes.

**Comment by orbeckst** [comment]
By the way, one cannot checkout the wiki as git repo, which should facilitate automated link fixing.

**Comment by tylerjereddy** [comment]
A large number of google code issue tracker links have been transformed to github issues tracker subdomain-based links, in a semi-automated fashion. This was just the low-hanging fruit for the link updating--still plenty left to do.

**Comment by orbeckst** [comment]
Changed priority to medium; we've been cleaning up the wiki as we've been going along. 
@tylerjereddy, have you got a way to flag wiki pages that likely need manual attention? It would be fantastic to have a clickable list of these pages attached here (or even better, a list with checkmarks AND links), e.g.

### Pages that need fixing
(Check pages that you fixed)
- [x] [Applications](/MDAnalysis/mdanalysis/wiki/Applications)
- [x] [Downloads](/MDAnalysis/mdanalysis/wiki/Downloads)
- [ ] [Documentation](/MDAnalysis/mdanalysis/wiki/Documentation)
- [ ] [Installing from source](/MDAnalysis/mdanalysis/wiki/Installing from source)
- [ ] .......

**Comment by orbeckst** [comment]
Did a bunch of search & replace and should be mostly fine. I removed the top level warning that wiki has been migrated. 
There are still instances of old links but they seem to be ok (for historical reasons). 
Everyone: please edit anything that seems useless/out of date.
