### ISSUE TITLE
Generalize the water MSD calculation function to any molecule. 

### ISSUE THREAD

**Issue by sperezconesa** [MDAnalysis/mdanalysis#2438]
**Is your feature request related to a problem? Please describe.**
The module to calculate the MSD of water molecules (from MDAnalysis.analysis.waterdynamics import MeanSquareDisplacement as MSD) is very flexible and good. But it only works for water molecules (or three-atomed molecules).

**Describe the solution you'd like**
I would like to be able to call a function like the one for water molecules but that it calculates the MSD for any type of molecule using the coordinate of one of its atoms or its center of mass.

**Describe alternatives you've considered**
I have programed this on a non-MDAnalysis style and non-object oriented way. I think such a good library as MDAnalysis should have a more general MSD calculation module since it is a very basic property of a system.

**Comment by orbeckst** [comment]
If you have written code already, maybe you can work on it in MDAnalysis?

**Comment by sperezconesa** [comment]
I have written some code, more scripts than anything. Perhaps I could do it based on what is implemented. Right now I have a too much work to do it, but I will keep it in mind for the near future.

**Comment by hmacdope** [comment]
I would love to lend a hand!
