### ISSUE TITLE
hbond problem

### ISSUE THREAD

**Issue by jito-tj** [MDAnalysis/mdanalysis#2445]
Hi, I would like to use MDAnalysis to calculate the hbond number, hbond life for bulk water system. so I try to run a small system include 221 water molecular (I use TIP4P model and produce by Gromacs software). I obtain the .gro, .xtc, .tpr file. and then I try to use this code to analysis the hbond. 
here is my code:

from __future__ import division
import numpy as np
import profile

import MDAnalysis as mda
from MDAnalysis.analysis import hbonds
import matplotlib.pyplot as plt

u = mda.Universe('298-add.gro', '298-add.xtc')
H = u.select_atoms('name H*')
O = u.select_atoms('name OW')
hb_ac = hbonds.HydrogenBondAutoCorrel(u, acceptors = O,hydrogens = H, donors = O, bond_type = 'continuous', sample_time = 0, nruns = 1, nsamples = 2)
hb_ac.run()
print(hb_ac.solution['results'])
hb_ac.solve()
print (hb_ac.solution)

-------------------------------------------------
but, it have error:
Traceback (most recent call last):
  File "t2.py", line 17, in <module>
    hb_ac = hbonds.HydrogenBondAutoCorrel(u, acceptors = O,hydrogens = H, donors = O, bond_type = 'continuous', sample_time = 0, nruns = 1, nsamples = 2)
  File "/home/jhtong/opt/python/lib/python2.7/site-packages/MDAnalysis/analysis/hbonds/hbond_autocorrel.py", line 214, in __init__
    raise ValueError("Donors and Hydrogen groups must be matched")
ValueError: Donors and Hydrogen groups must be matched

What should I could do next to get the number of hbond and hbond life in my bulk water system?
 

Best regards,
Jiahuan

**Comment by orbeckst** [comment]
Hello @jito-tj , as I explained in https://github.com/MDAnalysis/mdanalysis/issues/2446#issuecomment-574450510 , please ask your question on the user mailing list https://groups.google.com/group/mdnalysis-discussion . Thank you!
