### ISSUE TITLE
Bio.Alphabet Deprecation

### ISSUE THREAD

**Issue by RMeli** [MDAnalysis/mdanalysis#2448]
When running some MDAnalysis tests I run into the following `PendingDeprecationWarning`:
```
PendingDeprecationWarning: We intend to remove or replace Bio.Alphabet in 2020, ideally avoid using it explicitly in your code. Please get in touch if you will be adversely affected by this. https://github.com/biopython/biopython/issues/2046
```

**Currently version of MDAnalysis**

- MDA: 0.20.2-dev0
- Python: 3.6.7
- OS: macOS 10.5.2

**Comment by richardjgowers** [comment]
Yeah looks like we've got a couple of usages.  Worst case we lift it out of there and put it straight into MDA

**Comment by RMeli** [comment]
The two usages are in:
* `analysis/align.py`
* `core/topologyattrs.py`

It looks like `Bio.Alphabet` can be removed from `analysis/align.py` by not passing an `alphabet` to `Bio.AlignIO.read` and assuming the standard gap symbol `-`.

If I try to remove it from `core/topologyattrs.py` by using the default alphabet argument in `Bio.Seq.Seq` (which is `Bio.Alphabet.generic_alphabet`) the tests pass so the default argument might be enough assuming standard file formats.
