### ISSUE TITLE
EP handling in parm7 files

### ISSUE THREAD

**Issue by IAlibay** [MDAnalysis/mdanalysis#2449]
**Expected behavior**

When loading a parm7 topology, extra points are not assumed to be elements.

**Actual behavior**

Loading in an ff19SB parm7 topology (or actually anything with the SPC/E water model) will yield a user warning that atoms of types EP have been assigned to P (since mass couldn't be recognised).

**Code to reproduce the behavior**

```
u = mda.Universe(<some parm7 topology>)
```

**Currently version of MDAnalysis**

- Which version are you using? 0.20.1
- Which version of Python (`python -V`)? 3.7.3
- Which operating system? Ubuntu 18.04.3 LTS

**Actual comment**

Sorry not the most descriptive bug report, this is in some ways closer to feature request as I am opening this issue in order to get ideas on how this could be tackled.

So I don't think this is a new issue, but if possible I would like to fix this if possible as getting a bunch of phosphates is making things a tad bit more complicated.

Does anyone know if MDA already has a way to deal with extra points (I unfortunately couldn't find anything after an initial quick look through)?

**Comment by richardjgowers** [comment]
I'm assuming extra points are like virtual sites?

I think the assumption is just that users know that their systems have these fake particles and work around them when they build selections up?

**Comment by IAlibay** [comment]
> I'm assuming extra points are like virtual sites?

Yeah, pretty much.

> I think the assumption is just that users know that their systems have these fake particles and work around them when they build selections up?

That's fair, I don't mind dropping this issue, was just wondering if it would be worth considering a "standard" mass-less particle type we could be assigning instead?

**Comment by richardjgowers** [comment]
Actually now you mention it, I think in general how we deal with (intentionally) massless particles in something like a center_of_mass is worth considering and documenting well.

Could also add some more standard selections like `u.select_atoms('not virtual')` where virtual is a common list of virtual atom names.

**Comment by IAlibay** [comment]
Cool, I'll have a longer think about this and see if I can come up with a proposal for a framework for handling all this, particularly all the cases where we should be careful re: mass and mass-less particles.
