### ISSUE TITLE
update helanal to AnalysisBase

### ISSUE THREAD

**Issue by lilyminium** [MDAnalysis/mdanalysis#2452]
**Expected behavior**

When I run ``helanal.helanal_trajectory``, it produces readable output.

**Actual behavior**

``helanal.helanal_trajectory`` writes 8 files (there is no way to turn this off):

- bending_matrix.dat
- fit_tilt.xvg
- local_bend.xvg
- local_tilt.xvg
- origin.pdb
- screw.xvg
- summary.txt
- unit_twist.xvg

None of the `.xvg` files have delimiters, resulting in something like this (unit_twist.xvg):

>```
>0173.50089152.36047157.11974168.0601134.1332682.78972102.89294480.54708134.09038143.31886166.2364105.43222124.6999295.75029122.1871694.43125101.5204499.2620497.0216893.1698991.6502786.83874136.04012134.16911119.11755132.66452166.35683171.27223122.5070494.534966102.8902595.2906597.6656998.8994297.9797.82383102.0121695.7262297.1709147.01093149.21326110.0322688.56357102.8416599.71714105.5752799.8775199.056145101.6334296.66122494.9870894.4209499.65817135.18112141.92354114.745056120.963615134.35696130.1924107.3315199.60976101.5804996.4396102.3210396.43453102.259056104.7718392.5648796.93780596.2955106.55468119.2636123.093636104.8041102.03329133.9388796.147766111.26341105.42476127.773766158.32767162.8811374.15202146.2733362.067436170.5584664.37851110.36818101.4832895.5074697.5645998.09011101.22569103.59741100.17954100.5833197.70348126.24198155.93248169.31538163.89807153.8199364.76133159.19398172.53307168.54634154.64725157.2409160.78711117.229416130.50992101.69997498.69098102.3421398.5284197.9638897.9031384.2355692.51822101.50628112.175995141.17561179.15326115.91146162.714297.18241148.72191177.6465675.098206162.01685178.84647153.61559143.4729582.728778.1872974.47471169.2817782.82487176.68405159.40784127.06898576.81265108.926895116.31709143.0244387.8953476.859406138.5434143.4651297.01566138.7108172.56514115.02348133.1791475.7148175.10802104.24445131.14348144.5514105.2866192.4977393.9222296.55736101.0048695.58964100.96390594.60849102.6927897.4528593.37078100.4637390.25625692.76536109.01559498.313156104.478905100.8604699.90523101.04384695.73096101.6445100.1566798.6450398.35263101.63966104.76728139.75473134.5733364.02203109.86525159.32852177.16191148.17155163.89886151.0398174.66324114.77936119.296104104.45007126.39088499.2082396.272104.2805799.6220799.19309105.1044101.61230598.236244101.4117290.6837682.89361
>```

These aren't fixed-length either. Throwing in a newline after each value gives values with a mix of 4 or 5 decimal places.

> ```
> 0
> 173.50089
> 152.36047
> 157.11974
> 168.0601
> 134.13326
> 82.78972
> 102.892944
> 80.54708
> 134.09038
> ...
> ```
> 

Am I missing some obvious way to interpret these files? If not, IMO these should either be written in an easy way for `np.loadtxt` to bring them back again, or left as attributes in a class.

The documentation also could use a lot of clarification and updating.

**Code to reproduce the behavior**

Show us how to reproduce the failiure. If you can, use trajectory files from the test data.

``` python
import MDAnalysis as mda
from MDAnalysis.tests.datafiles import PDB
from MDAnalysis.align import helanal
u = mda.Universe(PDB)
helanal.helanal_trajectory(u, 'name CA')

```

**Currently version of MDAnalysis**

- Which version are you using? (run `python -c "import MDAnalysis as mda; print(mda.__version__)"`) '0.20.2-dev0'
- Which version of Python (`python -V`)? 3.7
- Which operating system? MacOS

**Comment by richardjgowers** [comment]
Iirc helanal might even predate numpy.  I think rewriting the functionality into how analysis classes are meant to work (and saving against a class attribute) is probably a very good idea!

**Comment by IAlibay** [comment]
Just copying @WG150, I believe in our chat with @richardjgowers back in November he expressed having either started to work on this or wanting to. He was kinda busy with thesis work though...

**Comment by WG150** [comment]
I'd be happy to take a look at this. I've already worked on changing the functionality and output formats. As @IAlibay has said, I'll most likely be able to work on this properly in the next few months.

**Comment by orbeckst** [comment]
A rewrite with AnalysisBase in mind would be most welcome! 

Having a prototype sooner than later would be good so that we could decide if the new helanal should become the standard for release 1.0.

**Comment by orbeckst** [comment]
Rename this issue to "update helanal to AnalysisBase"?

**Comment by IAlibay** [comment]
Pinging @WG150, checking if you were still interested in picking this one up?

**Comment by lilyminium** [comment]
I would actually like to look at some helices sometime this week, so I’m also happy to poke at this if you’re busy @WG150

**Comment by WG150** [comment]
I'll be able to take a look at this later this month. @lilyminium if you want to take a look / make a start this week that's ok with me!

**Comment by orbeckst** [comment]
@fiona-naughton – does "I have to look at helices and I only want to touch the helanal module with gloved hands" sound familiar? (Ok, I am paraphrasing here, that's not a literal quote ;-) )

**Comment by fiona-naughton** [comment]
That does rather capture the sentiment! I'd also be happy to  have a go at improving it, but looks like we've already got several takers

**Comment by orbeckst** [comment]
@lilyminium , sorry if my comment above https://github.com/MDAnalysis/mdanalysis/issues/2452#issuecomment-596846159 was a bit confusing. What I wanted to say was that the helanal module is useful (an apparently many people come to MDAnalysis because of it) but it's horrible to use, not well documented, and really out of date compared with almost everything else in MDAnalysis. @fiona-naughton in my group used it recently and was thinking out aloud that it needed a serious face lift because using it was no fun at all.

**Comment by lilyminium** [comment]
Sorry @orbeckst, I forgot that face is "confused" (why is it not 🤔?)
> an apparently many people come to MDAnalysis because of it

helanal is actually the first code I ever tried to run in MDAnalysis when I was still v. new to Python and MD, ~3 years ago. (Then I decided I didn't *really* need to look at helices). But GitHub didn't have a "flashbacks to my honours year" emoji available, so... 😕 I'm glad that it is now getting a revamp.
