### ISSUE TITLE
indicate NF sponsorship

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/mdanalysis#2460]
Related to MDAnalysis/MDAnalysis.github.io#115

- [x] update README: “Powered by NumFOCUS” badge for your website and/or GitHub - Markdown for adding NumFOCUS badge to project websites:  [![Powered by NumFOCUS](https://img.shields.io/badge/powered%20by-NumFOCUS-orange.svg?style=flat&colorA=E1523D&colorB=007D8A )](http://numfocus.org)
   ```
   [![Powered by NumFOCUS](https://img.shields.io/badge/powered%20by-NumFOCUS-orange.svg?style=flat&colorA=E1523D&colorB=007D8A )](http://numfocus.org)
   ```
- [x] add a Fiscal Sponsor Readme Attribution to the README, following https://github.com/numfocus/templates/blob/master/fiscal-sponsor-readme-attribution.md
 - [x] add text to the docs' top page

**Comment by richardjgowers** [comment]
Woo! :)

**Comment by orbeckst** [comment]
Shush... ;-)

**Comment by RMeli** [comment]
Is the "Fiscal Sponsor Readme Attribution" relevant for MDAnalysis? From what I could gather from the NumFOCUS website, MDA is  an "affiliated" project and not a "sponsored" project. For example, MDA has no NumFOCUS hosted project sponsorship page.

**Comment by richardjgowers** [comment]
It became relevant a day ago :)

**Comment by orbeckst** [comment]
We don’t have an official news release yet... but soon. Patience. 

> Am 23.01.2020 um 04:17 schrieb Richard Gowers <notifications@github.com>:
> 
> It became relevant a day ago :)

**Comment by orbeckst** [comment]
Link in #2506
