### ISSUE TITLE
“how to get started as a contributor” documentation

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/mdanalysis#2462]
We need a “how to get started as a contributor” documentation (for #2460 and MDAnalysis/MDAnalysis.github.io#115)

- [ ] something like CONTRIBUTING.md in the repo – e.g. using https://github.com/github/opensource.guide/blob/master/CONTRIBUTING.md as a starting template (this is CC-BY 4.0 so need to acknowledge source if we use it!)
- [ ] link on the website to the CONTRIBUTING doc

**Comment by lilyminium** [comment]
Have you had a look at the [Contributing page](https://www.mdanalysis.org/UserGuide/contributing.html) on the user guide? I tried to make it comprehensive.

**Comment by lilyminium** [comment]
And the [related PR](https://github.com/MDAnalysis/UserGuide/pull/35) for where I got the information.

**Comment by orbeckst** [comment]
No, I hadn’t had the UserGuide on my radar for CONTRIBUTING. It is great on the technical side. I am missing the community aspects, though – along the lines of (taken/adapted from https://github.com/github/opensource.guide/blob/master/CONTRIBUTING.md <https://github.com/github/opensource.guide/blob/master/CONTRIBUTING.md>). Some the things are already present (such as Code of Conduct), others, like the types of contributions and how to communicate would be useful to set the tone and the expectations:

Types of contributions we're looking for

- bug reports
- bug fixes
- improvements (speed, clarity, modernized code)
- new features
- improvements and additions to documentation (even typo fixes!)
- improvements to the build system


Ground rules & expectations

Before we get started, here are a few things we expect from you (and that you should expect from others):

Be kind and thoughtful in your conversations around this project. We all come from different backgrounds and projects, which means we likely have different perspectives on "how open source is done." Try to listen to others rather than convince them that your way is correct.
MDAnalysis adheres to a Code of Conduct By participating in this project, you agree to abide by its terms.
If you open a pull request, please ensure that your contribution passes all tests. If there are test failures, you will need to address them before we can review your contribution and eventually merge them. If you have problems with making the tests pass, ask for help!
How to contribute

If you'd like to contribute, start by searching through the issues and pull requests  to see whether someone else has raised a similar idea or question.

If you don't see your idea or problem listed, do one of the following:

If your contribution is minor, such as a typo fix, open a pull request.
If your contribution is major, such as a bug fix or a new feature, start by opening an issue first. That way, other people can weigh in on the discussion before you do any work. If you also create a pull request, you should link it to the issue by including the issue number in the pull request’s description.

Communications

Discussions about MDAnalysis take place on the mailing lists and this repository’s Issue Tracker (issues and pull requests). Anybody is welcome to join these conversations. 

Wherever possible, do not take these conversations to private channels, including contacting the maintainers directly. Keeping communication public means everybody can benefit and learn from the conversation.
