### ISSUE TITLE
encore ClusterCollection.get_ids error and unexpected representations

### ISSUE THREAD

**Issue by lilyminium** [MDAnalysis/mdanalysis#2464]
**Expected behavior**

1. `encore.clustering.ClusterCollection.ClusterCollection.get_ids()` works without an error.

2. `encore.clustering.ClusterCollection.ClusterCollection.__repr__` makes it look indexable, so I expect that I can index it.

3. `encore.clustering.ClusterCollection.Cluster.__repr__` looks like a numpy array, so I expect that I can index it.

**Actual behavior**

1. It raises an AttributeError because Clusters do not have an `idn` attribute. Clusters just call it `id`.

https://github.com/MDAnalysis/mdanalysis/blob/972a8b1893b5e353b9d796b15d6fcdd022a93f00/package/MDAnalysis/analysis/encore/clustering/ClusterCollection.py#L218

2. Not indexable. The clusters are in `encore.clustering.ClusterCollection.ClusterCollection.clusters`. Perhaps a `repr` that looks like `<ClusterCollection with 49 clusters>` would be more informative.

3. Not indexable. `repr` returns the Cluster's `elements`, which are a numpy array. Perhaps a `repr` that gives something like `<Cluster with 5 elements, centroid=1, id=1>` would be more informative.

**Code to reproduce the behavior**

[Notebook](https://lilyminium.github.io/UserGuide/examples/analysis/trajectory_similarity/clustering_ensemble_similarity.html)

**Currently version of MDAnalysis**

- Which version are you using? (run `python -c "import MDAnalysis as mda; print(mda.__version__)"`) 0.20.1
- Which version of Python (`python -V`)? 3.7
- Which operating system? MacOS

**Comment by orbeckst** [comment]
cc @mtiberti @tbengtsen @wouterboomsma – maybe you can add some insights on why the current behavior exists and if one can/should change anything (independent from who would actually do it).

**Comment by mtiberti** [comment]
Thanks - I'll reply point by point 

1. I think it should just return a list of `v.id` as you mention

2. The current representation is there mostly for historical purposes (i.e. it was convenient at the time) but I agree it's a bit verbose and it shouldn't necessarily look indexable. I like your suggestion that is more concise - than a user can manually go dig into the details if they want to 

3. Similarly as point 2 - your suggestion definitely makes sense
