### ISSUE TITLE
encore.hes returns an numpy array of a dict

### ISSUE THREAD

**Issue by lilyminium** [MDAnalysis/mdanalysis#2465]
**Expected behavior**

When I call `hes, details = encore.hes(ensemble, details=True` then `details` is readable.

**Actual behavior**

`details` is a `np.ndarray` of a `dict`. 

https://github.com/MDAnalysis/mdanalysis/blob/972a8b1893b5e353b9d796b15d6fcdd022a93f00/package/MDAnalysis/analysis/encore/similarity.py#L940-L945

This is not indexable either with numbers or keys. I don't know how to get information out from it. It's probably easier to just not convert it to an array.

**Code to reproduce the behavior**

[Notebook showing failure to index `details`](https://lilyminium.github.io/UserGuide/examples/analysis/trajectory_similarity/harmonic_ensemble_similarity.html#Calculating-harmonic-similarity)

**Currently version of MDAnalysis**

- Which version are you using? (run `python -c "import MDAnalysis as mda; print(mda.__version__)"`) 0.20.1
- Which version of Python (`python -V`)? 3.7
- Which operating system? MacOS

**Comment by orbeckst** [comment]
cc @mtiberti @tbengtsen @wouterboomsma – maybe you can add some insights on why the current behavior exists and if one can/should change anything (independent from who would actually do it).

**Comment by mtiberti** [comment]
Thanks! I agree - just returning a dict would also be consistent with details returned by `encore.dres` and `encore.ces`. I think we can just skip the arrayification
