### ISSUE TITLE
Proper error message and suggestion for AlignTraj on trajectory without mass

### ISSUE THREAD

**Issue by xiki-tempula** [MDAnalysis/mdanalysis#2469]
**Is your feature request related to a problem? Please describe.**
Coarse-grain trajectory has no assigned mass but it still makes sense to use the AlignTraj. Thus, if one were to run.

```
u = mda.Universe(gro)
protein = u.select_atoms('bynum 1-518')
traj = mda.Universe(xtc, xtc)
AlignTraj(traj, protein, select='bynum 1-518', in_memory=True)
```

He will get

```
  File "pa.py", line 13, in plot
    AlignTraj(traj, protein, select='bynum 1-518', in_memory=True)
  File "/Users//GitHub/mdanalysis/package/MDAnalysis/analysis/align.py", line 668, in __init__
    strict=strict, match_atoms=match_atoms)
  File "/Users//GitHub/mdanalysis/package/MDAnalysis/analysis/align.py", line 1187, in get_matching_atoms
    mass_mismatches = (np.absolute(ag1.masses - ag2.masses) > tol_mass)
  File "/Users//GitHub/mdanalysis/package/MDAnalysis/core/groups.py", line 2294, in __getattr__
    cls=self.__class__.__name__, attr=attr))
AttributeError: AtomGroup has no attribute masses
```

I felt that there should be certain options to disable the check on mass if the weight is not set to mass.

Say if one run 

`AlignTraj(traj, protein, select='bynum 1-518', in_memory=True, weights=None)`

Then the AlignTraj should work without checking for mass.

**Comment by richardjgowers** [comment]
Can this issue be worked around by setting all masses to 1 (as your beads
happen to have identical masses)?

**Comment by xiki-tempula** [comment]
@richardjgowers Yes, I'm currently solving it by adding the mass. But I felt that since the AlignTraj doesn't require mass information in this case, it doesn't make sense by force the mass attribute to be present,

**Comment by lilyminium** [comment]
Try setting `match_atoms=False`. The only reason it checks masses is to try to enforce that the reference and mobile atoms are in the same order.

**Comment by xiki-tempula** [comment]
@lilyminium Thanks. It seems to be working. It might be a good idea to document it.

**Comment by richardjgowers** [comment]
I think this just needs a doc fix rather than a behaviour change. The case where all atoms are similar mass (so don't required weighting) is very niche, and I can see more people (with dissimilar masses) getting burnt by weighting being ignored when masses aren't available.

**Comment by lilyminium** [comment]
@richardjgowers `weights=None` by default in `AlignTraj`, so it doesn't weight alignment without explicitly turning it on. In this case it's dying because `get_matching_atoms` looks for 'mismatching' atoms by checking if any one pair has a difference higher than `tol_mass`.  If you want to keep `match_atoms=True` by default then you could just change this line 

https://github.com/MDAnalysis/mdanalysis/blob/3be5c98271c67ed05bf7f63cfc0cf7d2adef2495/package/MDAnalysis/analysis/align.py#L1367

to ``if match_atoms and hasattr(ag1, 'masses') and hasattr(ag2, 'masses')``

**Comment by siddharthjain1611** [comment]
@lilyminium I'm making the changes suggested by you hope these try to solve the problem of mismatching.

**Comment by siddharthjain1611** [comment]
@lilyminium If could please spare some time to review my PR and suggest the changes required.

**Comment by lilyminium** [comment]
@xiki-tempula actually I'm surprised your topology didn't have masses, because I thought that was a mandatory attribute that would be guessed if not given.
