### ISSUE TITLE
remove atoms from universe 

### ISSUE THREAD

**Issue by teramind** [MDAnalysis/mdanalysis#247]
Hi,

is it possible to remove atoms e.g. everything than the backbone from a universe?

and is it possible to concatenate two trajectories for two different universes?

regards
Soren

**Comment by dotsdl** [comment]
This question is better suited to the [user discussion group](https://groups.google.com/forum/#!forum/mdnalysis-discussion). The issue tracker is intended for bug reports / specific enhancement requests.
