### ISSUE TITLE
mda.Merge for Universes without coordinates

### ISSUE THREAD

**Issue by lilyminium** [MDAnalysis/mdanalysis#2470]
**Expected behavior**

I can make a new Universe with mda.Merge from my old Universe without positions.

**Actual behavior**

I get an AttributeError because mda.Merge does not wrap the `coords` in a try/except clause. MDAnalysis can make Universes without coordinates, so when the `args` don't have `positions`, the `coords[None, :, :]` argument to `Universe()` can be left out.

https://github.com/MDAnalysis/mdanalysis/blob/b5cb49fc06c05d4038f75ba98c66dc30f856d303/package/MDAnalysis/core/universe.py#L1534-L1537

**Code to reproduce the behavior**

Show us how to reproduce the failiure. If you can, use trajectory files from the test data.

``` python
>>> import MDAnalysis as mda
>>> from MDAnalysis.tests.datafiles import PSF
>>> u = mda.Universe(PSF)
>>> subset = mda.Merge(u.atoms[:10])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/lily/pydev/mdanalysis/package/MDAnalysis/core/universe.py", line 1535, in Merge
    coords = np.vstack([a.positions for a in args])
  File "/Users/lily/pydev/mdanalysis/package/MDAnalysis/core/universe.py", line 1535, in <listcomp>
    coords = np.vstack([a.positions for a in args])
  File "mdanalysis/package/MDAnalysis/core/groups.py", line 2294, in __getattr__
    cls=self.__class__.__name__, attr=attr))
AttributeError: AtomGroup has no attribute positions
```

**Currently version of MDAnalysis**

- Which version are you using? (run `python -c "import MDAnalysis as mda; print(mda.__version__)"`) 0.20.2-dev
- Which version of Python (`python -V`)? 3.6
- Which operating system? MacOS

**Comment by AnshulAngaria** [comment]
Hi! @lilyminium @orbeckst I want to work on this issue

**Comment by orbeckst** [comment]
@AnshulAngaria sure, put up a PR and mention this issue in the "Fixes xx#" line.
