### ISSUE TITLE
encore.dres details output contains reference to itself

### ISSUE THREAD

**Issue by lilyminium** [MDAnalysis/mdanalysis#2471]
**Expected behavior**

`dres, details = encore.dres(ensemble)`

`details` is an output of `encore.dres`. I expect `details["dimensionality_reduction_details"]` to have new information.

**Actual behavior**

`details["dimensionality_reduction_details"] is details` returns True.

**Code to reproduce the behavior**

https://github.com/MDAnalysis/mdanalysis/blob/b5cb49fc06c05d4038f75ba98c66dc30f856d303/package/MDAnalysis/analysis/encore/similarity.py#L1413-L1424

I think maybe that last line is meant to be
``details["dimensionality_reduction_details"] = dim_red_details`` ?

**Currently version of MDAnalysis**

- Which version are you using? (run `python -c "import MDAnalysis as mda; print(mda.__version__)"`) 0.20.2-dev
- Which version of Python (`python -V`)? 3.7
- Which operating system? MacOS

**Comment by orbeckst** [comment]
Ping @mtiberti — any insights why this self reference exists in the output of `encore.dres(ensemble)`? Is this something that can be changed without breaking too many things?

**Comment by mtiberti** [comment]
Yes - sorry - @lilyminium is right, there's a mistake in the assigned variable there. I'm opening a PR.
