### ISSUE TITLE
Have a min_mass for HydrogenBondAnalysis.guess_hydrogens

### ISSUE THREAD

**Issue by lilyminium** [MDAnalysis/mdanalysis#2472]
**Is your feature request related to a problem? Please describe.**

``HydrogenBondAnalysis.guess_hydrogens`` only looks for a maximum mass and minimum charge for hydrogen-like atoms.

https://github.com/MDAnalysis/mdanalysis/blob/b5cb49fc06c05d4038f75ba98c66dc30f856d303/package/MDAnalysis/analysis/hydrogenbonds/hbond_analysis.py#L268-L274

However, we know that sometimes the mass guesser will give masses of 0.0 if it can't figure out what a particle is (#2348). This seems like it would lead to a fair few false positives.

**Describe the solution you'd like**
Have a `min_mass` keyword, or just don't choose atoms with a mass of 0.0

**Describe alternatives you've considered**
Making users validate the output of ``HydrogenBondAnalysis.guess_hydrogens`` themselves.

**Additional context**

**Comment by RMeli** [comment]
This looks dangerous indeed. This should be only a temporary solution and a long-term one would be to improve (fix?) the mass guesser (see Issue #2348).

I can implement this fix if no one else is working on it.
