### ISSUE TITLE
Selection by chain ID?

### ISSUE THREAD

**Issue by teramind** [MDAnalysis/mdanalysis#248]
Hi,

is a selection by chain ID implemented?
Or by molecule?

regards

**Comment by dotsdl** [comment]
This question is better suited to the [user discussion group](https://groups.google.com/forum/#!forum/mdnalysis-discussion). The issue tracker is intended for bug reports / specific enhancement requests.

**Comment by richardjgowers** [comment]
The answer to both your questions is yes, so if you ask on the discussion group you'll find what you need.
