### ISSUE TITLE
MDAnalysis/migration

### ISSUE THREAD

**Issue by RMeli** [MDAnalysis/mdanalysis#2490]
Is the `MDAnalysis/migration` sub-package still useful or should it be removed for release 1.0? 

It contains some (failing) tests and the only occurrence in the code is in the main `__init__.py` where `ten2eleven` is imported (`from .migration.ten2eleven import ten2eleven`). The documentation of `ten2eleven` is the following:

```text
Convert MDAnalysis 0.10.0 scripts to 0.11.0

    Usage:
       ten2eleven('myscript.py')
```

**Comment by orbeckst** [comment]
Unless @tylerjereddy has any objections oi would say that this can be removed. It was very useful in the big API break days of 0.11 but we haven’t really used it since.

**Comment by tylerjereddy** [comment]
Removal sounds good to me. I imagine most people have moved past that now.
