### ISSUE TITLE
Deprecation of _reformat_hb in hbonds/hbond_analysis.py for v1.0

### ISSUE THREAD

**Issue by IAlibay** [MDAnalysis/mdanalysis#2492]
Currently going through and doing the required removals/deprecations for #1745 and I noticed that _reformat_hb was set for deprecation as part of #1339 

```
        .. deprecated:: 1.0
           This is a compatibility layer so that we can provide the same output
           in timeseries as before. However, for 1.0 we should make timeseries
           just return _timeseries, i.e., change the format of timeseries to
           the un-ambiguous representation provided in _timeseries.
```

It seems like some change is required here prior to v1.0.0, but it's unclear to me as to what.

**Comment by IAlibay** [comment]
pinging @orbeckst as the author of #1339

**Comment by orbeckst** [comment]
As this is in the old hbond code, which we will just keep for legacy reasons in 1.0 I would say, just remove the deprecation notice and we freeze it as it is, warts and all.

For 2.0 we should consider removing the whole old hbond thing and just use the new hydrogenbond analysis but I don't know what else would need to be updated for this to work.

**Comment by IAlibay** [comment]
Ok thanks, I'll update #2494 accordingly.

**Comment by orbeckst** [comment]
Closing because nothing needs to be done. (Except removing the note)
