### ISSUE TITLE
[upstream?] seaborn 0.10 test issues

### ISSUE THREAD

**Issue by IAlibay** [MDAnalysis/mdanalysis#2495]
**Expected behavior**

All the tests should pass without issues.

**Actual behavior**

`analysis/test_psa.py` fails due to seaborn import issues. This appears to be directly related to the v0.10 release of seaborn, as v0.9 isn't causing the failures.

This appears to currently be the culprit for the recent Travis CI failures.

Trace:

```
self = <MDAnalysisTests.analysis.test_psa.TestPSAnalysis object at 0x7fe0db56f990>, psa = <MDAnalysis.analysis.psa.PSAnalysis object at 0x7fe0dc8965d0>
tmpdir = local('/tmp/pytest-of-mcria/pytest-7/test_dendrogram_produced_annot0')

    @pytest.fixture()
    def plot_annotated_heatmap(self, psa, tmpdir):
        pytest.importorskip('seaborn')
        psa.run(metric='hausdorff')
        with tmpdir.as_cwd():
>           results = psa.plot_annotated_heatmap(filename="annotated.png")

test_psa.py:89:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
../../../package/MDAnalysis/analysis/psa.py:1839: in plot_annotated_heatmap
    None,
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

value = None, from_value = None

>   ???
E   ImportError: ERROR --- The seaborn package cannot be found!
E
E                   The seaborn API could not be imported. Please install it first.
E                   You can try installing with pip directly from the
E                   internet:
E
E                     pip install seaborn
E
E                   Alternatively, download the package from
E
E                     http://pypi.python.org/pypi/seaborn/
E
E                   and install in the usual manner.

<string>:3: ImportError
```

**Code to reproduce the behavior**

`pytest test_psa.py`

**Currently version of MDAnalysis**

- Which version are you using? (run `python -c "import MDAnalysis as mda; print(mda.__version__)"`) 0.20.2-dev0
- Which version of Python (`python -V`)? 3.7.6
- Which operating system? Ubuntu 18.04.3 LTS

**Comment by IAlibay** [comment]
thanks @RMeli for pointing this out, I meant seaborn 0.10 not 1.0.

**Comment by RMeli** [comment]
I can confirm the same problem on `macOS 10.15.3` but I could not reproduce the problem with a clean `conda` environment (`conda create -n sns-test python=3.7 seaborn -c conda-forge`). However, from `seaborn=0.10`' release notes:

> Most notably, all support for Python 2 has now been dropped. Support for Python 3.5 has also been dropped. Seaborn is now strictly compatible with Python 3.6+.

This means we should pin `seaborn` to 0.9 anyway, until MDAnalysis drops Python 2 support.
