### ISSUE TITLE
analysis.AnalysisFromFunction processes arguments incorrectly

### ISSUE THREAD

**Issue by lilyminium** [MDAnalysis/mdanalysis#2503]
**Expected behavior**

If I don't pass a trajectory to AnalysisFromFunction, it looks for the first trajectory in my AtomGroup/s and then saves my given arguments. 

https://github.com/MDAnalysis/mdanalysis/blob/9d5520c611cb8ccfe7a35b1741b948e92475acb5/package/MDAnalysis/analysis/base.py#L226-L237

**Actual behavior**

When the trajectory is not passed, it moves the first argument to the end of `args` instead of the start. It then looks for the trajectory in the last AtomGroup.

**Code to reproduce the behavior**

Show us how to reproduce the failiure. If you can, use trajectory files from the test data.

``` python
>>> import MDAnalysis as mda
>>> from MDAnalysis.tests.datafiles import PSF, DCD
>>> from MDAnalysis.analysis.base import AnalysisBase, AnalysisFromFunction

>>> u = mda.Universe(PSF, DCD)
>>> protein = u.select_atoms('protein')

>>> def mass_xyz(atomgroup, masses):
...    return atomgroup.positions*masses

>>> xyz = AnalysisFromFunction(mass_xyz, protein, protein.masses)
>>> xyz.args
(array([14.007,  1.008,  1.008, ..., 12.011, 15.999, 15.999]),
 <AtomGroup with 3341 atoms>)
>>> xyz.run()
```

Error from `mass_xyz` receiving `(masses, atomgroup)` as the argument instead of `(atomgroup, masses)`
```
<ipython-input-4-50c897828315> in mass_xyz(atomgroup, masses)
      1 def mass_xyz(atomgroup, masses):
----> 2     return atomgroup.positions*masses
      3 
AttributeError: 'numpy.ndarray' object has no attribute 'positions'
```

**Currently version of MDAnalysis**

- Which version are you using? (run `python -c "import MDAnalysis as mda; print(mda.__version__)"`) 0.20.1
- Which version of Python (`python -V`)? 3.7
- Which operating system? MacOS

**Possible solution**

```diff
        if (trajectory is not None) and (not isinstance(
                trajectory, coordinates.base.ProtoReader)):
---       args = args + (trajectory,)
+++       args = (trajectory,) + args
            trajectory = None

        if trajectory is None:
            for arg in args:
                if isinstance(arg, AtomGroup):
                    trajectory = arg.universe.trajectory
+++                 break
            # when we still didn't find anything
            if trajectory is None:
                for arg in six.itervalues(kwargs):
                    if isinstance(arg, AtomGroup):
                        trajectory = arg.universe.trajectory
```

**Tests**

One way to test a solution would be to verify that the breaking analysis in the example, actually works.

**Comment by orbeckst** [comment]
This looks like a bug. I think your proposed solution should work.

I'll add a help wanted, just in case someone else wants to try a simple fix, given that the code changes are already there and will only need testing.

**Comment by HTian1997** [comment]
Followed the idea and made it more compact #2549 . 
`
xyz = AnalysisFromFunction(mass_xyz, protein, protein.masses.reshape(-1, 1))
`
can pass the test.
