### ISSUE TITLE
verbose not set in analysis.AnalysisBase.run

### ISSUE THREAD

**Issue by lilyminium** [MDAnalysis/mdanalysis#2504]
**Expected behavior**

From #1463, I think that `AnalysisBase.run(verbose=True)` is supposed to override the existing `self._verbose`. ~From #2206, it seems that `verbose` is supposed to be deprecated, but there are no deprecation warnings about it.~ (For what it's worth, I think the progress meter is cute.)

EDIT (@orbeckst): Analysis classes should be able to take the `verbose` kwarg for _both_ the `__init__()` constructor _and_ the `run()` method. The value give for `run()` should override the constructor value _while `run()` is executing_, as described in #1463 .

**Actual behavior**

Nothing happens.

**Code to reproduce the behavior**

https://github.com/MDAnalysis/mdanalysis/blob/9d5520c611cb8ccfe7a35b1741b948e92475acb5/package/MDAnalysis/analysis/base.py#L187

Nothing's done with `verbose`. `_setup_frames` defaults to False.

https://github.com/MDAnalysis/mdanalysis/blob/9d5520c611cb8ccfe7a35b1741b948e92475acb5/package/MDAnalysis/analysis/base.py#L149

**Currently version of MDAnalysis**

- Which version are you using? (run `python -c "import MDAnalysis as mda; print(mda.__version__)"`) 0.20.1
- Which version of Python (`python -V`)? 3.7
- Which operating system? MacOS

**Comment by Purva-Chaudhari** [comment]
@lilyminium I would like to work on the issue

**Comment by lilyminium** [comment]
Please go ahead @Purva-Chaudhari! Put up a pull request and link this issue, and it will get reviewed.

**Comment by kpiyush04** [comment]
Hi! @lilyminium @orbeckst 
I would like to work on this issue

**Comment by Purva-Chaudhari** [comment]
@lilyminium From what I have understood(ran example with run(verbose=True)),in the run method in AnalysisBase() self_verbose  is not getting overridden. Referring to issue #2206 I Raised deprecation warning if step/start/stop is none and made their scope private. Is it now expected that the self_verbose in run to override the default .

**Comment by Purva-Chaudhari** [comment]
If I am mistaken in understanding the objective please do let me know

**Comment by lilyminium** [comment]
@kpiyush04 thanks for looking at this, but as @Purva-Chaudhari has already started working on the issue, their pull request will get prioritised. Perhaps you could work on something else, e.g. #2599 was recently opened.

@Purva-Chaudhari Yep, that sounds about right -- as @orbeckst clarified above, `verbose` is not deprecated. Setting `verbose` in `run()` should override the existing `self._verbose`.

**Comment by orbeckst** [comment]
Just to add: @Purva-Chaudhari please open a PR that references this issue in a timely manner. Just saying "I want to do this" is not enough – we'll give you some leeway but we expect that you follow up within a day or so.

**Comment by Purva-Chaudhari** [comment]
@orbeckst Sure will follow that

**Comment by Purva-Chaudhari** [comment]
@lilyminium could you please review the PR, I am a bit new to open source contribution. Hope i made it in a correct way. If not please do let me know and also regarding the changes I made, are they correct or what should I improve in the code,
Thanking you

**Comment by lilyminium** [comment]
@Purva-Chaudhari Thanks for having a go at this, welcome to open source! I see that you [opened a PR](https://github.com/Purva-Chaudhari/mdanalysis/pull/1) in your own fork of MDAnalysis -- however, to merge code into *this* code-base, you need to open one [here](https://github.com/MDAnalysis/mdanalysis/pulls). The [user guide](https://www.mdanalysis.org/UserGuide/contributing_code.html) lays out the steps of how to contribute to MDAnalysis, including [adding and writing tests](https://www.mdanalysis.org/UserGuide/testing.html).

You have also commented which part of the code you would like to change, but you should actually make changes to the code so that tests can be run on it to see if it works. In terms of your suggested change -- it's not quite what we were looking for. The line ``verbose = getattr(self, '_verbose', False)`` overrides the ``verbose`` argument passed in ``run``, whereas the value I pass into ``run()`` should override the saved ``_verbose``, at least while the class is running.

Please feel free to ping me or another dev for a proper review when you open a PR into this repository :-)
