### ISSUE TITLE
error when compiling with python3.4

### ISSUE THREAD

**Issue by hainm** [MDAnalysis/mdanalysis#251]
Hi guys,

I got this error when installing mdanalysis in master branch. Tested with python2.7 and there is no problem. But I got the error with src/KDTree/KDTree.swig.cpp code for `python3.4`. Something like

    src/KDTree/KDTree.swig.cpp: In function âvoid SWIG_Python_AddErrorMsg(const char*)â:
    src/KDTree/KDTree.swig.cpp:877:58: error: âPyString_AsStringâ was not declared in this scope
         PyErr_Format(type, "%s %s", PyString_AsString(old_str), mesg);
                                                              ^
    src/KDTree/KDTree.swig.cpp: In function âPySwigClientData* PySwigClientData_New(PyObject*)â:
    src/KDTree/KDTree.swig.cpp:1268:26: error: âPyClass_Checkâ was not declared in this scope
         if (PyClass_Check(obj)) {

**Comment by richardjgowers** [comment]
Hi

I don't think Python 3 is supported (yet), for details there's Issue #132

**Comment by hainm** [comment]
thanks for your info.

Hai
