### ISSUE TITLE
general question/suggestion about MDAnalysis interface

### ISSUE THREAD

**Issue by hainm** [MDAnalysis/mdanalysis#254]
hi all,

I am working on [pytraj] (https://github.com/pytraj/pytraj) package, which is similiar to `MDAnalysis` but more focusing on AMBER package. There is also another package [mdtraj] (https://github.com/mdtraj/mdtraj) too.

Since no package is perfect, my idea is to "steal" what's good in others. Like currently 'pytraj' (and cpptraj in AMBER) does not support LAMMPS format, so `pytraj` can load coords from MDAnalysis package. I've been play with this package for hour or so but find very hard time with it. There are few points here

*How can I quickly steal 'xyz' coords (shape=n_frames, n_atoms, 3). I can get `xyz` from `mdtraj` package like

    import mdtraj as md
    traj = md.load(traj_name, parm_name)
    from pytraj import io
    p_traj = FrameArray(traj.xyz, parm_name)

For MDAnalysis,
I did this

    from MDAnalysis.tests.datafiles import LAMMPSdata
    from MDAnalysis import Universe as U

    u = U(LAMMPSdata)
    # I look at `u.coord`, `u.trajectory` but got no idea how to easily extract 
    # 3D coords

Did I miss anything?

*method/attribute's are inconsistent too. `u.s8.bond` is a method,  `u.s8.bonds` is an object. but `u.s8.coordinates` is a method. :( 
*Methods, objects' names... in MDAnalysis are too verbose. It's really hard to type without using ipython.

btw: those are my opinions about your package. Hopefully It will be more useful (and being (as I can tell from citations)) and easier to use.

**Comment by hainm** [comment]
ah,

I see that MDAnalysis have human-readable atom selection (similar to VMD). We (AMBER) is using short (and a bit hard to learn) like ':2@CA'. 

Is there any short way to steal atom indices (numpy/python array) from MDAnalysis selection so I can feed to `pytraj`?

Hai

**Comment by richardjgowers** [comment]
Hi Hai

There's not a function which will dump an entire trajectories' coordinates into a numpy array, u.trajectory is an iterable object which moves the selects the currently loaded frame and u.coord points to the current Timestep (object with positions, velocities etc). You could do:

``` Python
u = mda.Universe(topology, trajectory)

ag = u.atoms  # AtomGroup of all atoms

ag.positions  # gives you (n, 3) array of coordinates

whole_traj = np.array([ag.positions for ts in u.trajectory])  # (nframes, n, 3) coords 
```

The attributes / methods are a little inconsistent, we're still nailing down the API.  Now you mention it, bonds() being a method to calculate bondlengths sometimes, and bonds being an attribute giving a list of bonds is confusing, I blame the dev who wrote it (me) :).

I like the names being verbose, makes it much more readable afterwards, and if you're not using ipython for interactive work then you're doing it all wrong :P 

Stealing indices is just

``` Python
ag = u.selectAtoms('whatever')

ag.indices()  # returns 0 based indices as np array
```

There's also the .write() method for AtomGroups which will write out the selection, 

https://pythonhosted.org/MDAnalysis/documentation_pages/selections_modules.html

``` Python
ag = u.selectAtoms('something')

ag.write('out.ndx')  # different suffix for different format
```

I think we're trying to keep Issues to strictly code based things, so I'll refer you to the user discussion group for more help

https://groups.google.com/forum/#!forum/mdnalysis-discussion

Hope that helps
Richard

**Comment by hainm** [comment]
thank you

**Comment by orbeckst** [comment]
Sorry to add to a closed issue but I wanted to just say to @hainm  that although @richardjgowers is absolutely correct that we prefer to answer "how to" questions on the [discussion mailinglist](http://help.mdanalysis.org), we nevertheless do appreciate your feedback on the user interface. The "verbose" names are going to stay but what is a method and what a managed attribute is an [open discussion](https://groups.google.com/d/msg/mdnalysis-devel/jxEns_KC0xY/kDdlDe0W_R4J) and input is welcome. See also recently #241.

**Comment by hainm** [comment]
hi thanks.

One of the reasons I comment here because I made `suggestion` too, not only `how` question. And it's so easy to use markdown in github, they have very friendly interface to view post, comment ... Sometimes some ideas/questions are just randomly popped up and just use phone to write post when traveling. 

It's great that  you guys move to github. I've known this `MDAnalysis` package a while ago but just starting to give comment/suggestion because everything is convenient now. 

btw, the folder organization of this package seems off from traditional python package 
(example: https://github.com/cython/cython, https://github.com/mdtraj/mdtraj).

Again, I am sorry if my post is not being in right place. (and hopefully no one think I am peaky :D)

cheers
Hai
