### ISSUE TITLE
depend on matplotlib-base instead of matplotlib

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/mdanalysis#2540]
PR https://github.com/conda-forge/mdanalysis-feedstock/pull/22 suggests that we should use matplotlib-base as our matplotlib dependency (instead of matplotlib).

~Is this a good idea?~ yes

- [ ] Test if it works. 
- [ ] Update our CI to use matplotlib-base instead of matplotlib.
- [ ] Update dependencies in `setup.py`.

**Comment by orbeckst** [comment]
The PR https://github.com/conda-forge/mdanalysis-feedstock/pull/22 (by a bot) said:

> I noticed that this recipe depends on matplotlib instead of matplotlib-base. Unless you need pyqt, recipes should depend only on matplotlib-base.

**Comment by IAlibay** [comment]
This discussion might be relevant: https://github.com/conda-forge/conda-forge.github.io/issues/933

**Comment by orbeckst** [comment]
Smaller dependency chains are good, and not needing to pull in qt is good!

**Comment by IAlibay** [comment]
@orbeckst Just started working on this one. Just one thing worth noting early on; matplotlib-base started with 2.1.2, so we'd have to increase our minimum version dependency.

**Comment by IAlibay** [comment]
Ok, so on looking at this further the main issue here is that matplotlib-base doesn't seem to be installable via pip. For some reason, it's exclusive to conda.

**Comment by orbeckst** [comment]
I suppose we can make the conda package dependent on matplotlib-base and the pip on matplotlib. For consistency, we keep the same version.

**Comment by lilyminium** [comment]
Moved this to the 2.0 milestone as [matplotlib-base does not support py35](https://github.com/MDAnalysis/mdanalysis/pull/2563#issuecomment-601758228).

**Comment by lilyminium** [comment]
Yes, let's use matplotlib-base.
