### ISSUE TITLE
remove Python 2 constructs

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/mdanalysis#2541]
Release 2.0 does not support Python 2 anymore (see the [Roadmap](https://www.mdanalysis.org/2019/11/06/roadmap/)) so we should get rid of compatibility code (six and friends).

**Comment by RMeli** [comment]
Which versions of Python 3 will be supported? (Asking mainly for f-strings, PEP 498)

**Comment by orbeckst** [comment]
I don’t think we discussed this in any detail. Start a discussion on the dev list?

**Comment by richardjgowers** [comment]
I think we usually followed whatever numpy was also doing, which I think was what continuous integration and conda-forge supported.  I think we usually have to be quite slow because we need to support that one cluster that still happens to run 2.7 in 2020.

**Comment by IAlibay** [comment]
I don't know when 1.19 comes out, but `numpy` seems to have dropped support for 3.5 on its development branch: https://github.com/numpy/numpy/blob/master/INSTALL.rst.txt#prerequisites

My understanding is that major releases of `numpy` are scheduled ~ 6 months, which means 1.19 should come in late June. So that might align itself quite well with a late Q2 goal for MDA 2.0.

**Comment by tylerjereddy** [comment]
SciPy will also be 3.6+ only for the next release (1.5.x). NumPy & SciPy have started to remove large amounts of Python 2 compatibility constructs in their master branches now that their Python 2.7 LTS branches have had what should be their final upates/need for backports.

**Comment by orbeckst** [comment]
For 2.0 I don't have a problem starting with Python >= 3.6.

**Comment by IAlibay** [comment]
Going to link https://github.com/MDAnalysis/mdanalysis/issues/2739#issuecomment-642362469 back to here.

My current approach has been to remove six / __future__ things every time I deal with a file. We probably want a means of tracking progress though.

**Comment by IAlibay** [comment]
As mentioned in https://github.com/MDAnalysis/mdanalysis/pull/2750#issuecomment-643514970 it might be that we want to chip away at this in stages. Having discussed this with @lilyminium, it might be an idea to break it down per "section" where we cover what is both in package & testsuite:
  - [ ] analysis
  - [ ] auxiliary
  - [ ] core
  - [ ] lib
  - [ ] selections
  - [ ] tests
  - [ ] topology
  - [ ] transformations
  - [ ] visualisation
  - [ ] misc (benchmarks, maintainer, setup scripts, datafiles, etc...)
