### ISSUE TITLE
rewrite AnalysisBase to be compatible with pmda.parallel.AnalysisBase

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/mdanalysis#2542]
**Expected behavior**

MDAnalysis and pmda share code and it is easy to parallelize existing analysis; we don't maintain duplicate code. For instance, I should be able to take a `_single_frame()` method for MDAnalysis directly in pmda.

**Actual behavior**

MDAnalysis.analysis.base.AnalysisBase and pmda.parallel.AnalysisBase are different because the serial version can easily share data via the class while the parallel version must have `_single_frame()` return the results for accumulation. The parallel version has `_reduce` to handle accumulation in a parallelizable fashion.

**Comments**

pmda is only one way to parallelize trajectory analysis. However, my understanding is that as soon as one wants to distribute work over processes that cannot communicate by shared memory one needs to change the way in which AnalysisBase works. Therefore, I think that adapting the pmda model is a step in the right direction.

**Comment by IAlibay** [comment]
Is this still feasible for 2.0?

How is this affected by the proposed changes for mda_cli? Pinging @PicoCentauri here.

**Comment by orbeckst** [comment]
Not feasible for 2.0

**Comment by IAlibay** [comment]
@orbeckst shall we move this to 2.1 or do we think it's now become a 3.0 target?

**Comment by orbeckst** [comment]
Do 3.0 for now and if we can get hands on deck we can move it up.

**Comment by IAlibay** [comment]
Looks to me like we're going a different direction here -- closing.

**Comment by RMeli** [comment]
Linking https://github.com/MDAnalysis/mdanalysis/issues/4158 for record.
