### ISSUE TITLE
Turn waterdynamics.HydrogenBondLifetimes into function of HydrogenBondAnalysis

### ISSUE THREAD

**Issue by lilyminium** [MDAnalysis/mdanalysis#2547]
**Is your feature request related to a problem? Please describe.**
Given that `HydrogenBondLifetimes` just runs (the now deprecated) hbonds.HydrogenBondAnalysis under the hood, it seems it could be easily turned into a post-run() function of HydrogenBondAnalysis.

**Describe the solution you'd like**

Turn it into a function of HydrogenBondAnalysis.

**Describe alternatives you've considered**
At least use the new class instead of the old one.

**Additional context**
This is the `run()` function:

```python
def run(self, **kwargs):
        """Analyze trajectory and produce timeseries"""
        h_list = MDAnalysis.analysis.hbonds.HydrogenBondAnalysis(self.universe,
                                                                 self.selection1,
                                                                 self.selection2,
                                                                 distance=3.5,
                                                                 angle=120.0)
        h_list.run(**kwargs)
        self.timeseries = self._getGraphics(h_list.timeseries, self.t0,
                                            self.tf, self.dtmax)
```

**Comment by bieniekmateusz** [comment]
Hi @lilyminium, we have extracted the standalone Autocorrelation function with @p-j-smith (#2256). Once that's merged, we can proceed with your suggestion and add a hydrogen bond lifetime function to HydrogenBondAnalysis that makes use of this discrete autocorrelation function.

The new functions will be available in MDAnalysis.analysis.utils.
