### ISSUE TITLE
LAMMPSDataConverter deprecated with no target for removal

### ISSUE THREAD

**Issue by IAlibay** [MDAnalysis/mdanalysis#2564]
**Details**

As part of the prep for v1.0, I'm going through and checking everything that's been set for deprecation/removal. The LAMMPSDataConverter has been deprecated since 0.9.0, but no removal dates were set. My suggestion here would be to remove it for 1.0.0.

If there's agreement on the removal, I will go ahead and make the change.

**Comment by orbeckst** [comment]
Yes, remove it!
