### ISSUE TITLE
Amber -> Gromacs trajectories with forces

### ISSUE THREAD

**Issue by solernou** [MDAnalysis/mdanalysis#257]
Hi all,  
I need to convert an NetCDF Amber trajectory into a trr Gromacs trajectory porting both coordinates and forces. 
After a discussion with the developers, they concluded that although the NetCDF reader doesn't read Forces currently, it should be possible to include them, and then the TRR writer would be able to write a full Gromacs trajectory.
I prepared a tar ball with a short NetCDF Amber trajectory (just 1MB) that includes the forces, together with the .pdb, .top, and .crd files as well as the amber input file .in in order to help. That was sent to  mdnalysis-discussion@googlegroups.com. 

Thanks,
Albert

**Comment by orbeckst** [comment]
The attachment is part of the email [Re: [mdnalysis-discussion] Re: Amber -> Gromacs trajectories with forces](https://groups.google.com/d/msg/mdnalysis-discussion/RBiJv-Z41J8/PksbwkPafPUJ) and is a tar archive [amberTraj.tar.bz2](https://groups.google.com/group/mdnalysis-discussion/attach/f57cda43c21b4b3e/amberTraj.tar.bz2?part=0.1&authuser=0)

**Comment by richardjgowers** [comment]
I think I've done this (pending user feedback), the unit tests for the Reader are pending permission to use the trajectories.

**Comment by orbeckst** [comment]
@solernou says that @richardjgowers 's code works and gave his [permission to include his files as test cases](https://groups.google.com/d/msg/mdnalysis-discussion/RBiJv-Z41J8/lxQuCvF0eusJ) so I am closing this issue and have a look at #257.
