### ISSUE TITLE
ClusteringMethods don't need to return details

### ISSUE THREAD

**Issue by lilyminium** [MDAnalysis/mdanalysis#2575]
**Expected behavior**

Everything returned by `ClusteringMethod.__call__` contains information that is used.

**Actual behavior**

`ClusteringMethod.__call__` returns ``clusters, details``. ``details`` is always an empty dictionary. It's not used by ``cluster`` and is not even in the documentation:

https://github.com/MDAnalysis/mdanalysis/blob/9bcf6f4c118e1ea137e8514bd60cbd1cd1972062/package/MDAnalysis/analysis/encore/clustering/ClusteringMethod.py#L77-L91

The documentation is also inaccurate: ``clusters`` is an array of the centroid frame indices of length \#elements, as returned by ``encode_centroid_info``:

https://github.com/MDAnalysis/mdanalysis/blob/9bcf6f4c118e1ea137e8514bd60cbd1cd1972062/package/MDAnalysis/analysis/encore/clustering/ClusteringMethod.py#L57-L66

**Code to reproduce the behavior**

As shown below, ``cluster`` does not use the empty ``details`` dictionary.

https://github.com/MDAnalysis/mdanalysis/blob/9bcf6f4c118e1ea137e8514bd60cbd1cd1972062/package/MDAnalysis/analysis/encore/clustering/cluster.py#L234-L235

**Currently version of MDAnalysis**

- Which version are you using? (run `python -c "import MDAnalysis as mda; print(mda.__version__)"`) 0.20.2-dev
- Which version of Python (`python -V`)?
- Which operating system?

**Suggested fix**
Remove ``details`` from all the ``ClusteringMethod``s and update the documentation. Run the tests to make sure it doesn't affect anything else.

**Comment by shfrz** [comment]
Hi @lilyminium I would want to take this one!

**Comment by lilyminium** [comment]
@mtiberti are you happy with @shfrz fixing this issue?

**Comment by orbeckst** [comment]
@shfrz please feel free to work on this issue. @mtiberti can always review.

**Comment by shfrz** [comment]
@orbeckst sure, thank you!

**Comment by shfrz** [comment]
@MDAnalysis/gsoc-mentors could you please review my PR?

**Comment by shfrz** [comment]
Hi, @lilyminium I implemented the suggested fix but 8 out of 12 tests are failing!

**Comment by kpiyush04** [comment]
Hi! @lilyminium @orbeckst 
I want to work on this issue

**Comment by IAlibay** [comment]
@kpiyush04, there is already a PR by @shfrz aiming to deal with this issue (#2585). I would suggest possibly going for a separate GSOC starter issue as #2585 will be prioritised. If the PR stalls then it will be closed and we will look for alternatives.

**Comment by kpiyush04** [comment]
ok thanks a lot

**Comment by shfrz** [comment]
@lilyminium , removing details is not feasible as it generates errors in CusterCollection.py
After fixing the code in ClusterCollection.__init__, other errors follow. Hence, I think we should only update the documentation!

Thanks!
