### ISSUE TITLE
Parallel Unit Testing with Nose

### ISSUE THREAD

**Issue by tylerjereddy** [MDAnalysis/mdanalysis#258]
Parallel unit testing now works great with nose if you are careful to increase the timeout threshold:

```nosetests --processes=8 --process-timeout=120```

As this saves the developers and end users checking installation integrity a substantial amount of time, I suggest the docs (just the wiki for this one?) are updated to reflect this usage. Omitting the timeout flag causes a bit of a trainwreck.

**Comment by richardjgowers** [comment]
Is the process-timeout the maximum time a test can take?

**Comment by tylerjereddy** [comment]
I'm not sure that it is quite that simple. The official documentation for the timeout flag is here: http://nose.readthedocs.org/en/latest/plugins/multiprocess.html#cmdoption--process-timeout

I suppose if a process gets more than one test in some kind of 'batch--' it would be the time to return the results for the batch? But maybe it really is as simple as the time for a single test on a single process.

**Comment by tylerjereddy** [comment]
I've updated the wiki accordingly.
