### ISSUE TITLE
Python 3.6 build fails due to missing numpy on Travis

### ISSUE THREAD

**Issue by lilyminium** [MDAnalysis/mdanalysis#2583]
**Expected behavior**

MDAnalysis builds in Python 3.6 on Travis.

**Actual behavior**

It's failing across #2561, #2577 and the ``develop`` branch itself. The specific environments are Python 3.6 with Numpy 1.17.3 and 1.18.

**Error**

[The environment can't find Numpy.](https://travis-ci.com/MDAnalysis/mdanalysis/jobs/294185943#L1984)

<img width="829" alt="Screenshot 2020-03-05 at 5 14 20 PM" src="https://user-images.githubusercontent.com/31115101/75953136-ceaa5a00-5f04-11ea-8670-37190a59e191.png">

``numpy`` *is* getting [installed, but from defaults instead of conda-forge](https://travis-ci.com/MDAnalysis/mdanalysis/jobs/294185943#L1781), as ``openblas`` etc. are. I don't think you can mix these. 

<img width="589" alt="Screenshot 2020-03-05 at 5 15 31 PM" src="https://user-images.githubusercontent.com/31115101/75953218-03b6ac80-5f05-11ea-903e-963bbe7b6eec.png">

**Comment by orbeckst** [comment]
Should we get rid of defaults and only use conda-forge? 

I tend to get annoyed when the whole package dependency system fails, isn't this what conda is supposed to prevent?

**Comment by richardjgowers** [comment]
I merged a bunch of PRs this morning and the builds passed, I think it was just a hiccup.  I think this issue has self-resolved.

**Comment by lilyminium** [comment]
Awesome, closed!
