### ISSUE TITLE
PersistenceLength.plot() create new axes instead of grabbing current ones

### ISSUE THREAD

**Issue by lilyminium** [MDAnalysis/mdanalysis#2590]
## Is your feature request related to a problem? ##
Because PersistenceLength.plot() grabs the current axes instead of creating a new figure, you can end up with it plotting over something else unintentionally. [e.g. plotting over and over in this figure](https://github.com/MDAnalysis/mdanalysis/pull/2589#issuecomment-596000408)

https://github.com/MDAnalysis/mdanalysis/blob/1f4e492662955e483fc98982728404149f7a1deb/package/MDAnalysis/analysis/polymer.py#L272-L273

## Describe the solution you'd like ##
Create new axes instead. If users want to plot on already created axes, they can pass those in themselves with the ``ax`` keyword already implemented.

**Comment by ss62171** [comment]
@lilyminium is this fine?
