### ISSUE TITLE
Polymer perform_fit deprecated without removal target

### ISSUE THREAD

**Issue by IAlibay** [MDAnalysis/mdanalysis#2596]
:meth:`PersistenceLength.perform_fit` has been deprecated as of 0.19.2 (#2141) but wasn't given a date for removal.

Considering there will be at least one version release between 0.19.2 and 1.0.0, and the fact that `perform_fit` doesn't really do anything anymore, is it ok if I go ahead and remove it as part of #2443 ?

**Comment by IAlibay** [comment]
Tagging @richardjgowers as the author of #2141 here.

**Comment by orbeckst** [comment]
We'll remove it cold-turkey as is – and there' wont't be anything between 0.19.2 and 1.0.0...
