### ISSUE TITLE
Increasing coverage for align.py

### ISSUE THREAD

**Issue by IAlibay** [MDAnalysis/mdanalysis#2598]
## Is your feature request related to a problem? ##

The coverage for `analysis/align.py` is currently at ~ 87%. There are some easy enough parts of the code that are missing coverage that could be tested. See: https://codecov.io/gh/MDAnalysis/mdanalysis/src/develop/package/MDAnalysis/analysis/align.py

## Describe the solution you'd like ##
More tests, example cases that should be easy to cover:
  - `alignto`'s `subselection` (lines: 507-512)
  - `fasta2select`'s `alnfilename` and `treefilename` == `None` (lines: 1040-1045)
  - `get_matching_atoms`'s `strict` diagnostics (lines: 1296-1320)

## Additional context ##
As discussed with @richardjgowers this is being raised as a feature request to point GSOC candidates towards code areas where increased coverage would be useful.

**Comment by siddharthjain1611** [comment]
@IAlibay  I'll love to work on this if allowed.

**Comment by IAlibay** [comment]
@siddharthjain1611 Just going to link to: https://github.com/MDAnalysis/mdanalysis/issues/2599#issuecomment-596601702

PRs are welcome for this issue, however, I would suggest aiming for fixing one issue at a time.

**Comment by smrpn** [comment]
can i work on this issue?

**Comment by IAlibay** [comment]
@siddharthjain1611 are you still looking to work on this issue?

@smrpn I would probably give @siddharthjain1611 a bit of time to see if they still want to work on it.

**Comment by IAlibay** [comment]
@smrpn you may want to give this a go since @siddharthjain1611 hasn't replied.

**Comment by ss62171** [comment]
If anyone is not looking to work on this, can I work on this?

**Comment by ss62171** [comment]
@IAlibay can I work on this?

**Comment by IAlibay** [comment]
Sorry @ss62171, I hadn't seen your previous message. Since there's been no PR on this by @smrpn in the last 11 or so days, please do open a PR if you would like to.

**Comment by ThanhNguyenVu** [comment]
@IAlibay can I just work on the second one (line 1040-1050) for now? I see @ss62171 has not opened a PR yet and I would like to contribute for GSoC, but I would like to leave something to @ss62171 to that he can contribute too.

**Comment by ss62171** [comment]
@ThanhNguyenVu I was going to open PR for this but since you have to qualify for GSoC I would like you to continue on this as I have already 2 merged PRs. ;)

**Comment by IAlibay** [comment]
Thanks for being so understanding @ss62171. @ThanhNguyenVu please do open a PR as soon as possible, the deadline is rapidly approaching and review can at best take a couple of days.

**Comment by ss62171** [comment]
@ThanhNguyenVu are you willing to work on this?
If yes, can you reply to this.

**Comment by ss62171** [comment]
@IAlibay can you review this PR.

**Comment by tylerjereddy** [comment]
@IAlibay Looks like your third suggested code block can't be reached--dead code. You may want to remove that one and open a separate issue for that matter. See related discussion in cognate PR.

**Comment by IAlibay** [comment]
Thanks for working this out @ss62171 and @tylerjereddy!

re: https://github.com/MDAnalysis/mdanalysis/pull/2652#issuecomment-611250117

>Ok, it seems it is an unreachable code path--so not clear to me why @IAlibay suggested it should be covered. Probably they didn't notice it couldn't be reached.

That's pretty much exactly what happened :) The above mentioned parts of the code were more "examples for things not covered that GSOC students could do" rather than "these definitely need testing". My apologies if this led to some wasted time, that being said, finding out there's some unreachable code might not be a bad side-effect 🙃 

Regarding raising a separate issue, since this is most related to the work done in #2652, and there are some finer details that I've not had a chance to look into, is there any chance I could convince you to open the issue @tylerjereddy ?

**Comment by tylerjereddy** [comment]
> Regarding raising a separate issue, since this is most related to the work done in #2652, and there are some finer details that I've not had a chance to look into, is there any chance I could convince you to open the issue @tylerjereddy ?

Ok, I'll do it, but there's not much extra to understand--there's an unreachable code path in your third case.
