### ISSUE TITLE
Document Contacts attributes and add n_initial_contacts

### ISSUE THREAD

**Issue by lilyminium** [MDAnalysis/mdanalysis#2604]
## Is your feature request related to a problem? ##
``Contacts`` gives the fraction of initial contacts in ``timeseries``, but I think most people would also like to know how many initial contacts there actually are. 
 
## Describe the solution you'd like ##
You can calculate this with ``Contacts.initial_contacts[0].sum()``, but it would be nice to just have it there as an attribute e.g. `n_initial_contacts`. Especially since the documentation doesn't list ``initial_contacts`` or ``r0`` as attributes, so many users will not know it's there. So, desired solution:

1. Have `n_initial_contacts`
2. Document the (important) attributes of the class

## Additional context ##

[Example notebook of using the class, and calculating initial contacts, in this user guide notebook.](https://www.mdanalysis.org/UserGuide/examples/analysis/distances_and_contacts/contacts_native_fraction.html#Calculating-fraction-of-native-contacts,-with-a-distance-lower-than-or-equal-to-the-reference-structure)

**Comment by shfrz** [comment]
Hi @lilyminium, what do you mean by "1. Have `n_initial_contacts`?

**Comment by RMeli** [comment]
> [...] but it would be nice to just have it there as an attribute e.g. `n_initial_contacts`

It means to add (have) `n_initial_contacts` as a (documented) attribute of `Contacts`.

**Comment by shfrz** [comment]
@RMeli  @lilyminium,
Does it require to create `def n_initial_contacts(..)` and proceeding further?

**Comment by lilyminium** [comment]
@shfrz No, as `n_initial_contacts` would be a static attribute. I would focus on fixing #2575 and getting a feel for the workflow before working on other issues.

**Comment by RMeli** [comment]
@shfrz If you are not comfortable with OOP in Python I suggest to have a look at [this short introduction](https://realpython.com/python3-object-oriented-programming) since MDAnalysis relies heavily on such concepts. However, I'd follow @lilyminium advice of focusing on a single issue for now.

**Comment by HeetVekariya** [comment]
- @RMeli @lilyminium I have gone through the issue description, PRs, conversation and i understand this issue as,
   - Add the **```n_initial_contacts```** which is equal to **```Contacts.initial_contacts[0].sum()```**
   - Document attributes such that user can know about it (i.e. r0, n_initial_contacts)
   - Write test for the code written for this issue to check whether it is correctly working or not.
 
- If i understand the issue correctly can i proceed with PR ?
- Do i need to also include other attributes in the Docstring than ```ro```, ```n_initial_contacts``` ? If yes can you please let me know about it.

**Comment by lilyminium** [comment]
Hi @HeetVekariya, yep, that sounds about right! However, I notice that you've been interested in multiple issues, some of which can take a bit of work (e.g. #2764 and #516). I'd encourage you to concentrate on fixing one at a time instead of trying to do too much at once.

**Comment by HeetVekariya** [comment]
- Yes you are absolutely right. 
- Currently i thinking to work on [2604](https://github.com/MDAnalysis/mdanalysis/issues/2604) and [2764](https://github.com/MDAnalysis/mdanalysis/issues/2764), but not [516](https://github.com/MDAnalysis/mdanalysis/issues/516) as i think it is bit difficult for me at this time.
- Because of free time i have explored both above mentioned issues and posted my queries.
