### ISSUE TITLE
Secondary structure determination

### ISSUE THREAD

**Issue by lilyminium** [MDAnalysis/mdanalysis#2608]
## Is your feature request related to a problem? ##
`gmx do_dssp` isn't making nice with DSSP version 3.1.4, and I would like to quantify the secondary structure of my protein.

## Describe the solution you'd like ##
An MDAnalysis version where I don't need to load my entire trajectory into memory.

## Describe alternatives you've considered ##
MDTraj has `compute_dssp` but it loads the trajectory into memory.

**Comment by orbeckst** [comment]
Duplicate of  #1612 (but admittedly, this issue is more concise) so I am copying it to the older one and then close this one.
