### ISSUE TITLE
Missing selection module in leaflet.py

### ISSUE THREAD

**Issue by yuxuanzhuang** [MDAnalysis/mdanalysis#2612]
## Expected behavior ##

write_selection works

## Actual behavior ##

``` python
NameError: name 'selections' is not defined
``` 

## Code to reproduce the behavior ##

``` python
from MDAnalysis.analysis.leaflet import LeafletFinder, optimize_cutoff
from MDAnalysisTests.datafiles import Martini_membrane_gro

LIPID_HEAD_STRING = "name PO4"
universe = MDAnalysis.Universe(Martini_membrane_gro)
lipid_heads = universe.select_atoms(LIPID_HEAD_STRING)
lfls_ag = LeafletFinder(universe, lipid_heads, pbc=False)

lfls_ag.write_selection('test.vmd')
```

## Current version of MDAnalysis ##

- Which version are you using? (run `python -c "import MDAnalysis as mda; print(mda.__version__)"`) '0.20.2-dev0'
- Which version of Python (`python -V`)? 3.7
- Which operating system? Ubuntu 18

**Comment by orbeckst** [comment]
Excellent find!
