### ISSUE TITLE
Pytest 5.4.0 requires parametrize arguments to be explicitly declared

### ISSUE THREAD

**Issue by lilyminium** [MDAnalysis/mdanalysis#2618]
## Expected behavior ##

Tests pass regardless of `pytest` version.

## Actual behavior ##

Tests [do not pass with recently released pytest 5.4.0](https://travis-ci.com/github/MDAnalysis/mdanalysis/jobs/297586269#L1709-L1721).

```
==================================== ERRORS ====================================
______ ERROR collecting MDAnalysisTests/coordinates/test_timestep_api.py _______
In function "test_frame":
Parameter "topology" should be declared explicitly via indirect or in function itself
_______ ERROR collecting MDAnalysisTests/core/test_group_traj_access.py ________
In function "test_atomgroup_positions_access":
Parameter "pos" should be declared explicitly via indirect or in function itself
__________ ERROR collecting MDAnalysisTests/formats/test_libmdaxdr.py __________
In function "test_seek":
Parameter "fname" should be declared explicitly via indirect or in function itself
__________ ERROR collecting MDAnalysisTests/formats/test_libmdaxdr.py __________
In function "test_set_offsets":
Parameter "xdrfile" should be declared explicitly via indirect or in function itself
```

A [new feature](https://docs.pytest.org/en/latest/changelog.html#features) of 5.4.0:

>  Now all arguments to @pytest.mark.parametrize need to be explicitly declared in the function signature or via indirect. Previously it was possible to omit an argument if a fixture with the same name existed, which was just an accident of implementation and was not meant to be a part of the API.

A quick look at ``test_timestep_api.py`` shows that ``TestBaseTimestepInterface`` (which contains ``test_frame``) has parametrized arguments, but does not declare them in `__init__`, and I expect the other errored functions are similar.

## Solution

I think explicitly declaring these arguments is manageable and a more long-term solution than pinning the pytest version.

**Comment by orbeckst** [comment]
Thanks, you beat me to it!

**Comment by orbeckst** [comment]
> I think explicitly declaring these arguments is manageable and a more long-term solution than pinning the pytest version.

Yes!

**Comment by shfrz** [comment]
@lilyminium , I am at it!
Here's what I am thinking a possible solution might be:
1. adding `def __init__()`  in `TestBaseTimestepInterface`
2.  adding arguments in __init__() and writing error functions for them.
3. running tests to check everything else is fine
Did I get it right?

**Comment by IAlibay** [comment]
@lilyminium looks like 5.4.1 got released to revert the change: https://docs.pytest.org/en/latest/changelog.html

The fact that this was an "an unintended/surprising behavior", means it might still warrant the change.
