### ISSUE TITLE
update loading crd file in Amber

### ISSUE THREAD

**Issue by hainm** [MDAnalysis/mdanalysis#262]
Hi, 

I was trying to load prmtop.top and a *.crd file in Amber to Universe but got this error

`FormatError: Found 6132 coordinates in '1vrp.crd' but the header claims that there should be 12264 coordinates`

`12264` number here is the n_atoms.

**Comment by hainm** [comment]
ah, need to update for loading REMD traj (with ext like *.x.000, *.x.001, ...) too

**Comment by hainm** [comment]
1TypeError: Unknown topology format 'PARM7' for './myparm.parm7'; only ['XPDB', 'PRMTOP', 'Permissive_PDB', 'TOP', 'PSF', 'PDBQT', 'MOL2', 'PQR', 'DMS', 'TPR', 'CRD', 'GMS', 'GRO', 'XYZ', 'DATA', 'PDB'] are implemented in MDAnalysis.1

**Comment by richardjgowers** [comment]
Hi

The first one looks strange, is it finding twice as many atoms as it should?

Formats are automatically detected based on file endings, but can be manually set using keyword arguments, so

``` python
u = mda.Universe('something.parm7', trj, topology_format='PRMTOP')
```

Should fix the second issue.

**Comment by hainm** [comment]
No, this is the file header
 ```    
12264
  10.2970000  60.3660000  25.0470000   9.4254116  60.7014490  24.6583024
  10.6961028  61.0627718  25.6623123  10.0857547  59.5597713  25.6262623
  11.2500000  59.9720000  23.9700000  12.1997386  59.6832768  24.4228749
```

`12264` is the total number of atoms. mdanalysis though this is the # of coordinates.

This *.crd file has only 1 frame.

**Comment by richardjgowers** [comment]
So I'm not 100% familiar with .crd format, but I think it's not picking up that you've used 'extended' format (ie stacking 2 coordinates per line)

I think if you change the first line to '12264 EXT' it should work properly.  Does Amber allow you to omit the 'EXT' flag?

**Comment by hainm** [comment]
hi, I've been using Amber for 7 years and not aware of having "EXT" tag in Amber file.
this file was taken from Amber official test suite.
Hai

**Comment by richardjgowers** [comment]
Hmm, ok so apparently CHARMM and Amber both have .crd files that are vastly different in format. 

The Amber website seems to be down so I'll ask you, is the format just
```
natoms
x1 y1 z2 x2 y2 z2
etc etc
```
And are the coordinates always space delimited?

**Comment by hainm** [comment]
hi,

It also have 

```
ACE                                                                             
 2101  0.3000000E+02
   6.6528795   6.6711416  -8.5963255   7.3133773   5.8359736  -8.8294175
   8.3254058   6.2227613  -8.7098593   7.0833200   5.5038197  -9.8417650
   7.1129439   4.6170351  -7.9729560   7.6303627   3.5666399  -8.3311917
```

Our school's internet is on and in recent days so you might want to check Amber website next few days.

For the best, you can look at the `cpptraj` code (main data analysis program for Amber)

https://github.com/mojyt/cpptraj/blob/master/src/Traj_AmberRestart.cpp

those are test case for cpptraj with given files.
https://github.com/mojyt/cpptraj/tree/master/test

**Comment by richardjgowers** [comment]
Hey Hai

When you've got time, I've pushed a branch to read that format.  The file needs the suffix "inpcrd" or "restrt", or the keyword "format="INPCRD"" needs to be passed to Universe.  If you can check this works for your files, I'll then push it onto develop.

Thanks
Richard

**Comment by hainm** [comment]
```
In [1]: from MDAnalysis import Universe

In [2]: u = Universe ("prmtop.top", "1vrp.crd", format="INPCRD")
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-2-793b98d08284> in <module>()
----> 1 u = Universe ("prmtop.top", "1vrp.crd", format="INPCRD")

/home/haichit/anaconda3/envs/python2/lib/python2.7/site-packages/MDAnalysis-0.9.3.dev0-py2.7-linux-x86_64.egg/MDAnalysis/core/AtomGroup.pyc in __init__(self, *args, **kwargs)
   3353 
   3354         # Load coordinates
-> 3355         self.load_new(coordinatefile, **kwargs)
   3356 
   3357         # Deprecated bonds mode handling here, remove eventually.

/home/haichit/anaconda3/envs/python2/lib/python2.7/site-packages/MDAnalysis-0.9.3.dev0-py2.7-linux-x86_64.egg/MDAnalysis/core/AtomGroup.pyc in load_new(self, filename, **kwargs)
   3867         # supply number of atoms for readers that cannot do it for themselves
   3868         kwargs['numatoms'] = self.atoms.numberOfAtoms()
-> 3869         self.trajectory = reader(filename, **kwargs)    # unified trajectory API
   3870         if self.trajectory.numatoms != self.atoms.numberOfAtoms():
   3871             raise ValueError("The topology and {} trajectory files don't"

/home/haichit/anaconda3/envs/python2/lib/python2.7/site-packages/MDAnalysis-0.9.3.dev0-py2.7-linux-x86_64.egg/MDAnalysis/coordinates/INPCRD.pyc in __init__(self, filename, convert_units, **kwargs)
     46             line = inf.readline().split()
     47             self.numatoms = int(line[0])
---> 48             time = float(line[1])
     49 
     50             self.ts = self._Timestep(self.numatoms)

IndexError: list index out of range
```

**Comment by hainm** [comment]
worked fine with `pytraj`

```python 
In [5]: import pytraj.io as io                                                                                                        

In [6]: traj = io.load("1vrp.crd", "prmtop")

In [7]: traj
Out[7]: 
<TrajReadOnly with 1 frames, 12264 atoms/frame>
```

`mdtraj`
```python
In [13]: import mdtraj as md                                                                                            

In [14]: top = md.load_prmtop ("./prmtop.top")                                                                                                 

In [15]: traj = md.load_restrt("1vrp.crd", top=top)                                                                               

In [16]: traj
Out[16]: <mdtraj.Trajectory with 1 frames, 12264 atoms, 901 residues, without unitcells at 0x2aaad18b1790>
```

**Comment by richardjgowers** [comment]
I'm guessing that the thing you tried to load doesn't have a time in the header?  I think I just need to wrap that in a try/except.

**Comment by hainm** [comment]
this is the header I posted before

 ```    
12264
  10.2970000  60.3660000  25.0470000   9.4254116  60.7014490  24.6583024
  10.6961028  61.0627718  25.6623123  10.0857547  59.5597713  25.6262623
  11.2500000  59.9720000  23.9700000  12.1997386  59.6832768  24.4228749
```

**Comment by orbeckst** [comment]
MDAnalysis assumes that *crd* is a CHARMM card coordinate format, not AMBER.

**Comment by orbeckst** [comment]
Just merged @265.
