### ISSUE TITLE
weird behaviors when loading netcdf file

### ISSUE THREAD

**Issue by hainm** [MDAnalysis/mdanalysis#263]
Hi, I got this weird error:
1st time I load the traj: everything is OK (i have been using it for a while with netcdf file)
2nd time: got error

`CRITICAL:MDAnalysis.coordinates.AMBER:netcdf4-python with the netCDF and HDF5 libraries must be installed for the AMBER ncdf Reader.
CRITICAL:MDAnalysis.coordinates.AMBER:See installation instructions at https://github.com/MDAnalysis/mdanalysis/wiki/netcdf`

This is my code
```python
topname = "../tests/data/nogit/remd/myparm.top"
fname = "../tests/data/nogit/remd/remd.000.ncdf"
# load MDAnalysis
u = Universe(topname, fname)
```

Hai

**Comment by hainm** [comment]
AFAIN, this happens only in ipython and ipython-notebook. There is no error if using shell script.

Hai

**Comment by richardjgowers** [comment]
Hey Hai.

Thats caused by an import failing, does this work in your ipython?

    import netCDF4 as netcdf

**Comment by hainm** [comment]
hi

```python
In [23]: %timeit import netCDF4 as netcdf                                                                                                           
The slowest run took 6.54 times longer than the fastest. This could mean that an intermediate result is being cached 
1000000 loops, best of 3: 1.53 Âµs per loop
```

**Comment by richardjgowers** [comment]
Sounds very odd, that error is just caught in a try/except when importing netcdf.

Maybe importing netcdf at the top of the ipython script will make it load properly?

**Comment by hainm** [comment]
What I was doing is to compare memory usage for 3 packages: mdnalysis, mdtraj and pytraj.

things went well in the first time I ran the notebook but I needed to turned off mdanalysis due to the error.

you can check the notebook here (I need to rename one of my netcdf file from `remd.x.000` to
`remd.000.ncdf`

http://nbviewer.ipython.org/github/pytraj/pytraj/blob/master/note-books/memory_comparison.ipynb

**Comment by hainm** [comment]
Yes, making it on top did the trick.

Hai

**Comment by richardjgowers** [comment]
Cool, strange bug and a strange fix :)
