### ISSUE TITLE
Non-continuous angles from mdamath.angle

### ISSUE THREAD

**Issue by lilyminium** [MDAnalysis/mdanalysis#2632]
## Expected behavior ##

`mdamath.angle` calculates angles that are continuous in the domain [-1.0, 1.0].

## Actual behavior ##
```python
def angle(a, b):
    """Returns the angle between two vectors in radians

    .. versionchanged:: 0.11.0
       Moved into lib.mdamath
    """
    x = np.dot(a, b) / (norm(a) * norm(b))
    # catch roundoffs that lead to nan otherwise
    if x > 1.0:
        return 0.0
    elif x < -1.0:
        return -np.pi
    return np.arccos(x)
```

`np.arccos` returns values within [0, pi]. This means that `x==-1.0` returns pi, but `x==-1.00001` due to a rounding off error returns -pi. 

## Code to reproduce the behavior ##

``` python
>>> import numpy as np
>>> from MDAnalysis.lib import mdamath
>>> a = np.array([0.1, 0, 0.2])
>>> mdamath.angle(a, -a)
3.141592653589793
>>> mdamath.angle(a**0.5, -(a**0.5))
-3.141592653589793

```

## Current version of MDAnalysis ##

- Which version are you using? (run `python -c "import MDAnalysis as mda; print(mda.__version__)"`) 0.20.1
- Which version of Python (`python -V`)?
- Which operating system?

## Suggested fix ##

Use `np.clip` instead and leave it to `np.arccos` to return. Probably that code above would suffice as a test.

**Comment by shfrz** [comment]
Hi @lilyminium , I am at it.

**Comment by shfrz** [comment]
> np.arccos returns values within [0, pi]. This means that x==-1.0 returns pi, but x==-1.00001 due to a rounding off error returns -pi.
@lilyminium , If I am not wrong, it returns `nan` rather than -pi

**Comment by lilyminium** [comment]
Yes, `np.arccos(-1.00000001)` will return `nan`, hence the need to 
>``# catch roundoffs that lead to nan otherwise``
