### ISSUE TITLE
Testing for fragment attribute

### ISSUE THREAD

**Issue by PicoCentauri** [MDAnalysis/mdanalysis#2635]
## Expected behavior ##
Checking for the `fragment` attribute 

```python
from MDAnalysisTests.core.util import UnWrapUniverse
u = UnWrapUniverse(have_molnums=False, have_bonds=False)

print(hasattr(u,"fragments"))
print(hasattr(u.atoms, "fragments"))
```

should give the following consistent output

```python
False
False
```

## Actual behavior ##

However, while the first works fine and returns `False` the second raises a `NoDataError`.

```python
/usr/local/lib/python3.7/site-packages/MDAnalysis/core/groups.py in __getattr__(self, attr)
   2222             # raise NDE(_ATTR_ERRORS[attr])
   2223             raise NoDataError("AtomGroup.{} not available; this requires Bonds"
-> 2224                               "".format(attr))
   2225         raise AttributeError("{cls} has no attribute {attr}".format(
   2226             cls=self.__class__.__name__, attr=attr))

NoDataError: AtomGroup.fragments not available; this requires Bonds
```

## Current version of MDAnalysis ##

- Which version are you using? 0.20.2-dev0
- Which version of Python: 3.7
- Which operating system? macOS

**Comment by lilyminium** [comment]
Interesting. I guess you could define `__hasattr__` but... would making `NoDataError` a subclass of `AttributeError` fix this?
