### ISSUE TITLE
Port weave functions to Cython

### ISSUE THREAD

**Issue by richardjgowers** [MDAnalysis/mdanalysis#264]
So scipy.weave doesn't support Python 3, so functions written in weave should be ported to Cython to avoid blocking Python 3 (See #260) 

There's currently 2 functions in analysis.distances which use weave: 
 * contact_matrix_pbc
 * contact_matrix_no_pbc

I think these were originally written by @jandom but looking at them it should be easy to move them into src/numtools/calc_distances.h then write a new .pyx interface.

An option is to move these functions inside the distances.pyx interface, so then they could (eventually) share the parallelism there (assuming #261 goes ahead).

**Comment by orbeckst** [comment]
I'd like to get rid of all *weave* code. It's nice for quick hacks but it does require the user to have a working compiler tool chain, and that's not guaranteed. If we want to be able to distribute binary packages then weave code needs to be replaced by Cython.

**Comment by hainm** [comment]
should switch all weave to Cython. It's portable. You can ship your Cython code (*.pyx) with cythonize code (*.cpp). User only need C++ compiler (don't even need Cython) to get the `.so` extension without bothering install `scipy`, `numpy`, ...

I not sure about the idea 'binary packages'? Is this one similar to uploading to `binstar` and using `conda`? If yes, it's great. I can install `pytraj` within 30 seconds.

Hai
