### ISSUE TITLE
the first character in residue name of rotamer is being truncated

### ISSUE THREAD

**Issue by xiki-tempula** [MDAnalysis/mdanalysis#2649]
## Expected behavior ##
I have a pdb file which has two rotamers of the same residue.
```
ATOM      1  N  ASER A   1     -32.490   8.883  33.887  0.50 26.55      A    N  
ANISOU    1  N  ASER A   1     4213   3656   2218  -1404   -634    501  A    N  
ATOM      2  N  BSER A   1     -32.506   8.969  33.819  0.50 25.36      A    N  
ANISOU    2  N  BSER A   1     4072   3504   2060  -1414   -641    506  A    N  
ATOM      3  CA ASER A   1     -32.132   7.588  34.451  0.50 26.71      A    C  
ANISOU    3  CA ASER A   1     4169   3708   2272  -1355   -533    420  A    C  
ATOM      4  CA BSER A   1     -32.212   7.757  34.566  0.50 25.40      A    C  
ANISOU    4  CA BSER A   1     4001   3535   2116  -1342   -546    431  A    C  
```
However, when loaded with mdanalysis, the residue has the same resume as SER.
```
pdb = '''ATOM      1  N  ASER A   1     -32.490   8.883  33.887  0.50 26.55      A    N  
ANISOU    1  N  ASER A   1     4213   3656   2218  -1404   -634    501  A    N  
ATOM      2  N  BSER A   1     -32.506   8.969  33.819  0.50 25.36      A    N  
ANISOU    2  N  BSER A   1     4072   3504   2060  -1414   -641    506  A    N  
ATOM      3  CA ASER A   1     -32.132   7.588  34.451  0.50 26.71      A    C  
ANISOU    3  CA ASER A   1     4169   3708   2272  -1355   -533    420  A    C  
ATOM      4  CA BSER A   1     -32.212   7.757  34.566  0.50 25.40      A    C  
ANISOU    4  CA BSER A   1     4001   3535   2116  -1342   -546    431  A    C  '''
u = mda.Universe(StringIO(pdb), format="pdb")
u.atoms.resnames
```
Gives `array(['SER', 'SER', 'SER', 'SER'], dtype=object)`
Instead of `array(['ASER', 'ASER', 'BSER', 'BSER'], dtype=object)`

## Current version of MDAnalysis ##

- Which version are you using? (run `python -c "import MDAnalysis as mda; print(mda.__version__)"`) 0.20.2-dev0
- Which version of Python (`python -V`)? 3
- Which operating system? osx

**Comment by IAlibay** [comment]
I'm always a bit fuzzy in my memory of PDBv3 formats but isn't technically SER is the residue in both ASER and BSER? A/B are just altloc tags (i.e. if you called u.residues.altlocs it _should_ return ['A', 'B', 'A', 'B'].

**Comment by lilyminium** [comment]
It's because that column of A's and B's are the `altLoc`s. PDB formats only allow [3-letter residue names](http://www.wwpdb.org/documentation/file-format-content/format33/sect9.html#ATOM). Can you [select your rotamers](https://www.mdanalysis.org/UserGuide/selections.html#simple-selections) with the `altLoc` attribute?

**Comment by xiki-tempula** [comment]
Thank @IAlibay and @lilyminium for the help. 
```
u.select_atoms('altloc A')
<AtomGroup with 2 atoms>
```
works but
```
u.atoms.altLoc
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "~/GitHub/mdanalysis/package/MDAnalysis/core/groups.py", line 2226, in __getattr__
    cls=self.__class__.__name__, attr=attr))
AttributeError: AtomGroup has no attribute altLoc
u.residues.altlocs
Traceback (most recent call last):
  File "<input>", line 1, in <module>
AttributeError: 'ResidueGroup' object has no attribute 'altlocs'
```
don't.

**Comment by lilyminium** [comment]
That's not a very helpful error. Does `u.atoms.altLocs` and `u.residues.altLocs` work respectively?

**Comment by xiki-tempula** [comment]
@lilyminium They do work thanks.
```
u.atoms.altLocs
array(['A', 'B', 'A', 'B'], dtype=object)
u.residues.altLocs
[array(['A', 'B', 'A', 'B'], dtype=object)]
```

**Comment by xiki-tempula** [comment]
Is it justified that we use `altLocs` instead of `altlocs`? considering that all other Attributes are in lower-class.
