### ISSUE TITLE
Roundoff error in MDAnalysis.lib.mdamath._angle?

### ISSUE THREAD

**Issue by IAlibay** [MDAnalysis/mdanalysis#2650]
So as we are tying off #2634 (which fixes #2632), I noticed that MDAnalysis.lib.mdamath._angle isn't accounting for roundoff errors in the same way, and will just return an angle of 0 if there's a float overflow with:

https://github.com/MDAnalysis/mdanalysis/blob/60eb9d8289f79a3e5a38b788c5e25999bbe185e4/package/MDAnalysis/lib/mdamath.py#L157

I am probably mis-understanding what `_angle` is meant to be dealing with, but just thought I'd open this issue to check if this was intended behaviour.

## Code to reproduce the behavior ##

``` python
import numpy as np
from MDAnalysis.lib.mdamath import _angle

a = np.array([0.1, 0, 0.2])

_angle(a, -a) # returns 180
_angle(a**0.5, -a**0.5) # returns 0 with a RuntimeWarning
```

## Current version of MDAnalysis ##

- Which version are you using? (run `python -c "import MDAnalysis as mda; print(mda.__version__)"`) 0.20.2-dev0
- Which version of Python (`python -V`)? 3.7.6
- Which operating system? Ubuntu 18.04.4 LTS

**Comment by Oscuro-Phoenix** [comment]
Are you using the angle function (having np.clip()) with rad2deg in the end?

**Comment by IAlibay** [comment]
> Are you using the _angle function (with np.clip()) &rad2deg ? Or is the old _angle function?

If you are referencing to #2632, this is a separate function from `mdamath.angle` @Oscuro-Phoenix.
Although it is related, the question (probably for @richardjgowers who seemed to have transplanted the function there) is if we do actually need to use `np.clip()` here too, or if the behaviour, as it currently is, is intended.

**Comment by Oscuro-Phoenix** [comment]
I was just pondering the reason for not adding np.clip() straightaway. Now I see, this may be intended.

**Comment by lilyminium** [comment]
Is it used anywhere?

> if we do actually need to use np.clip()

I think one of the scenarios its meant to cover is when `norm(a)` or `norm(b)` are 0. Maybe I'm uncreative but I don't think that can ever happen for a non-zero vector?

**Comment by orbeckst** [comment]
It looks as if we should just check if either of the lengths is 0
```python
eps = 1e-16
ab = norm(a) * norm(b)
if np.abs(ab) < eps:
    return 0.0
return np.rad2deg( np.arccos(np.dot(a, b) / ab) )
```

Maybe worthwhile checking where we're using `_angle()`.

**Comment by lilyminium** [comment]
I don't think `_angle()` is used anywhere? Maybe it's best to just fold this check into `angle()`.

**Comment by orbeckst** [comment]
I don't see it being used `git grep '_angle('` so let's remove it ; it's not part of the public API so we don't have to deprecate it. It should be mentioned as a change in CHANGELOG, though.

**Comment by IAlibay** [comment]
Ok, PR incoming.
