### ISSUE TITLE
Add .frames, .times to AnalysisBase

### ISSUE THREAD

**Issue by lilyminium** [MDAnalysis/mdanalysis#2661]
## Is your feature request related to a problem? ##

I find myself needing to re-generate the frame indices / times of the trajectory slice used in AnalysisBase for almost every analysis to make a meaningful graph. Conversely it's extra work to slice `RMSD.rmsd` and it's the only class that does that to its results (add the frame index and time to the first 2 columns).

## Describe the solution you'd like ##

Add `.frames` and `.times` arrays to AnalysisBase, populated in `._run()`

## Additional context ##

Would allow for:

```python
for line in rmsd.rmsd.T:
	plt.plot(rmsd.times, line)
```

vs

```python
# after I look up again which column is the frame and which is time
# the contents of .rmsd is not in the class docstring but the rms module instead
# frames should be ints but times and rmsds are floats
for line in rmsd.rmsd.T[2:]:
	plt.plot(rmsd.rmsd[:, 1], line)
```

**Comment by orbeckst** [comment]
Sounds like an excellent idea and good use of AnalysisBase. 
- Are there any classes where we don’t need it (e.g. `RMSF`, `DensityAnalysis`) and if so, is there a way to disable it? (Sorry, didn’t review any code)
- Deprecate the additional columns in `RMSD` — this is especially important for 1.0 docs: we would like to have a consistent picture and examples with RMSD are common.

**Comment by orbeckst** [comment]
Regarding the deprecation in `RMSD`: I don’t really know how to do it cleanly except introducing a new attribute (but any name but `.rmsd` sounds worse) or hard-breaking code.
