### ISSUE TITLE
SameSelection should have an option for indices

### ISSUE THREAD

**Issue by lilyminium** [MDAnalysis/mdanalysis#2669]
## Expected behavior ##

`byres` and `same residue as` selects the whole residue for each atom in the subsequent selection, by the canonical and unique resindex. Likewise `same segment as` uses `segindex`. 

## Actual behavior ##

`byres` and `same residue as` use the user-supplied, potentially repeated `resid` values. `same segment as` uses `segid`. This is redundant as you can already use `same resid as` or `same segid as` for the same behaviour. This may result in unexpected behaviour with altLocs also. 

## Code to reproduce the behavior ##

Leads to problems like in this [mailing list issue](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/mdnalysis-discussion/oY7pdg8375Y/4mtLSkJBBAAJ) where selecting "byres resname TIP3" returns various amino acids and ions as well.

```python
>>> import MDAnalysis as mda
>>> u = mda.Universe('a.psf', 'a.dcd')
>>> ag = u.select_atoms('byres resname TIP3')
>>> print(set(ag.resnames))
{'GLN', 'LEU', 'TRP', 'THR', 'LYS', 'GLU', 'POPE', 'ASP', 'TYR', 'VAL', 'ARG', 'PHE', 'MET', 'CYS', 'ILE', 'PRO', 'TIP3', 'ALA', 'SOD', 'CLA', 'SER', 'GLY', 'ASN', 'HSD'}
```

## Current version of MDAnalysis ##

- Which version are you using? (run `python -c "import MDAnalysis as mda; print(mda.__version__)"`) 0.20.1
- Which version of Python (`python -V`)? 3.7.3
- Which operating system? MacOS

**Comment by richardjgowers** [comment]
Oops yeah, that's the whole reason we have `ix` and friends
