### ISSUE TITLE
Aux does not rewind after getting last frame

### ISSUE THREAD

**Issue by andrrizzi** [MDAnalysis/mdanalysis#2674]
## Expected behavior ##

Getting timesteps after retrieving the last frame should give the correct auxiliary information.

## Actual behavior ##

I ran into an issue with a trajectory augumented with an `XVGReader` where after obtaining the last `Timestep` with
```python
trajectory[last_frame_idx]
```
the auxiliary information of all the next timesteps obtained through `__getitem__` would be `nan`. I narrowed down the issue to [these lines](https://github.com/MDAnalysis/mdanalysis/blob/6d6b86202a16bff69fad3d8017aca19eed76578c/package/MDAnalysis/auxiliary/base.py#L421-L425):
```python
frame_for_step = self.step_to_frame(self.step, ts)
frame_for_next_step = self.step_to_frame(self.step+1, ts)
if (frame_for_step is not None and frame_for_next_step is not None
        and not (frame_for_step < ts.frame <= frame_for_next_step)):
    self.move_to_ts(ts)
```
when `self.step` is the last one, `frame_for_next_step` is `None` so that `move_to_ts(ts)` is never called.

Patching my local installation with this
```python
frame_for_step = self.step_to_frame(self.step, ts)
frame_for_next_step = self.step_to_frame(self.step+1, ts)
if frame_for_step is not None:
    if (frame_for_next_step is None) and not (frame_for_step < ts.frame):
        # self.step is the last auxiliary step in memory.
        self.move_to_ts(ts)
    elif ((frame_for_next_step is not None) and
          not (frame_for_step < ts.frame <= frame_for_next_step)):
        self.move_to_ts(ts)
```
solved the problem for me.

## Code to reproduce the behavior ##

My code is quite complicated and I don't have time to create a minimal case right now, but I can work on it or even open a PR with the fix if necessary.

## Current version of MDAnalysis ##

MDAnalysis version 0.19.2 installed from the `conda-forge` channel.
Python 3.6.7.
macOS 10.13.6.

**Comment by lilyminium** [comment]
I noticed this bug as well -- thanks for figuring out why @andrrizzi! This is the code I used, which could work as a minimal case / test:

```python
>>> import MDAnalysis as mda
>>> from MDAnalysis.tests.datafiles import XVG_BZ2, PDB_xvf, TRR_xvf
>>> u = mda.Universe(PDB_xvf, TRR_xvf)
>>> u.trajectory.add_auxiliary('protein_force', XVG_BZ2)
>>> u.trajectory[0]
>>> u.trajectory.ts.aux.protein_force
array([    0.     ,   200.71288, -1552.2849 , ...,   128.4072 ,
        1386.0378 , -2699.3118 ])
>>> u.trajectory[-1]
< Timestep 2 with unit cell dimensions [52.839806 52.839806 52.839806 90.       90.       90.      ] >
>>> u.trajectory.ts.aux.protein_force
array([  100.     ,  -246.27269,   146.52911, ...,   484.32501,
        2332.3767 , -1801.6234 ])
>>> u.trajectory[0]
< Timestep 0 with unit cell dimensions [52.763 52.763 52.763 90.    90.    90.   ] >
>>> u.trajectory.ts.aux.protein_force
array([nan, nan, nan, ..., nan, nan, nan])
```

**Comment by orbeckst** [comment]
@andrrizzi thank you. If you could put up a minimal PR then that could be a starting point for others to jump on.

Normally, when we review these PRs we will invariably ask you to add test cases etc. If you can find the time to do this (maybe using @lilyminium 's example) then that would be awesome. But even if not, you can always state that you just don't have the bandwidth to do it at the moment and that anyone else is welcome to contribute to the PR.

**Comment by andrrizzi** [comment]
> If you could put up a minimal PR then that could be a starting point for others to jump on.

Will do! If @lilyminium has no objections to me stealing their example, I'd be happy to include it in the PR as well as a unit test.

**Comment by andrrizzi** [comment]
Actually, I think I managed to make a similar test case inspired by the existing ones. Opening the PR soon.

**Comment by orbeckst** [comment]
Thanks for submitting the PR!
