### ISSUE TITLE
Add 'global' keyword to selections

### ISSUE THREAD

**Issue by mnmelo** [MDAnalysis/mdanalysis#268]
When performing atom selections from an AtomGroup instance all subexpressions are always evaluated within the set of the atoms of that instance. However, that isn't always intuitive:
```python
complex_preselected_solvent_group.selectAtoms("around 10 protein")
# This returns an empty AtomGroup because there is
# no protein in complex_preselected_solvent_group

# It can always be worked around...
universe.selectAtoms("group solv and around 10 protein", solv=complex_preselected_solvent_group)
```
A `global`keyword could be added to make the subsequent subexpressions be evaluated in the universe context, instead of the calling AtomGroup instance:
```python
complex_preselected_solvent_group.selectAtoms("around 10 global protein")
# This would work as expected
```

This construct would also eliminate the need for the `fullgroup` keyword, as we could now use `global group` instead, with equal legibility.
It also makes more sense now that we have the `same ... as` construct:
```python
# Suppose we have multiple protein copies in our system and want the active-site residues
# of those copies that are close to a POPC membrane
active_site_residues.selectAtoms("same fragment as global (protein and around 10 resname POPC)")
```

This is not a serious problem, since it can always be worked around by issuing the selection from the universe object, and using the `group` keyword to bring in the AtomGroup's atoms. But it makes for more readable code, and easier to write.

Opinions?

**Comment by orbeckst** [comment]
I don't see anything wrong with this suggestions and it certainly makes for more readable selections, so yes, +1 ;-).
