### ISSUE TITLE
python3.9: AttributeError: module 'MDAnalysis.analysis.encore' has no attribute 'KMeans'

### ISSUE THREAD

**Issue by junghans** [MDAnalysis/mdanalysis#2688]
## Expected behavior ##

Test would run.

## Actual behavior ##

Test fails with:
```
AttributeError: module 'MDAnalysis.analysis.encore' has no attribute 'KMeans'AttributeError: module 'MDAnalysis.analysis.encore' has no attribute '<Something>'
```

More details in RedHat issue tracker: https://bugzilla.redhat.com/show_bug.cgi?id=1838445

## Code to reproduce the behavior ##

`rpmbuild -ba  python-mdanalysis.spec` with this [python-mdanalysis.spec](https://src.fedoraproject.org/rpms/python-MDAnalysis/blob/master/f/python-MDAnalysis.spec)`

## Current version of MDAnalysis ##

- Which version are you using? (run `python -c "import MDAnalysis as mda; print(mda.__version__)"`) 0.20.1
- Which version of Python (`python -V`)? 3.9.0b1
- Which operating system? Fedora Rawhide

**Comment by IAlibay** [comment]
Do we know if py3.9 is properly supported by sklearn? (i.e. could this be an upstream issue?)

**Comment by tylerjereddy** [comment]
Not sure, but Python 3.9 stable won't be released until October 2020 I think. Some projects will run it in their CI (SciPy uses the nightly build of 3.9, for example), but I don't think there's any reasonable expectation of official support until the stable release.

**Comment by junghans** [comment]
> Not sure, but Python 3.9 stable won't be released until October 2020 I think. Some projects will run it in their CI (SciPy uses the nightly build of 3.9, for example), but I don't think there's any reasonable expectation of official support until the stable release.

Fedora has the tendency to test all packages before the python release goes live and that is where   the above error showed up.

> Do we know if py3.9 is properly supported by sklearn? (i.e. could this be an upstream issue?)

It seems sklearn is broken: https://bugzilla.redhat.com/show_bug.cgi?id=1838489

**Comment by IAlibay** [comment]
I'm going to close this now, py3.9 has been out for some time and we've not seen any further issues. Please do re-open if needed.
