### ISSUE TITLE
Inconsistent handling of Universe dimensions

### ISSUE THREAD

**Issue by RMeli** [MDAnalysis/mdanalysis#2698]
## Expected behavior ##

I expect an Universe created from a file with meaningless or unspecified cell dimensions to have a consistent null value for the dimensions attribute.

## Actual behavior ##

Loading the same cryo-EM structure (with meaningless cell dimensions) from MMTF and PDB files results in different values of the dimensions attribute.

## Code to reproduce the behavior ##

``` python
In [1]: import MDAnalysis as mda

In [2]: u1 = mda.Universe("2bbm.pdb.gz")
/Users/rmeli/Documents/git/software/mdanalysis/package/MDAnalysis/coordinates/PDB.py:432: UserWarning: 1 A^3 CRYST1 record, this is usually a placeholder. Unit cell dimensions will not be set.
  warnings.warn("1 A^3 CRYST1 record,"

In [3]: u1.dimensions
Out[3]: array([0., 0., 0., 0., 0., 0.], dtype=float32)

In [4]: u2 = mda.Universe("2BBM.mmtf.gz")

In [5]: u2.dimensions

In [6]: u2.dimensions is None
Out[6]: True
```

_Note:_ The test files are added in PR #2685 

## Current version of MDAnalysis ##

- Which version are you using? 0.20.2-dev0'
- Which version of Python (`python -V`)? Python 3.7.6
- Which operating system? macOS

**Comment by RMeli** [comment]
https://github.com/MDAnalysis/mdanalysis/blob/55afb4c36328e79c1390c0f4364b2cf5c1aff481/package/MDAnalysis/coordinates/base.py#L302

https://github.com/MDAnalysis/mdanalysis/blob/55afb4c36328e79c1390c0f4364b2cf5c1aff481/package/MDAnalysis/coordinates/base.py#L388-L391

https://github.com/MDAnalysis/mdanalysis/blob/55afb4c36328e79c1390c0f4364b2cf5c1aff481/package/MDAnalysis/coordinates/MMTF.py#L90-L94

**Comment by orbeckst** [comment]
Have we decided what we want to use for MDAnalysis to indicate that there's no unitcell? We have `[0, 0, 0, 0, 0, 0]` and `None` as options.

Personally, I feel that `None` is the more pythonic one but what are other opinions?

@RMeli maybe start a discussion on the dev list?

**Comment by richardjgowers** [comment]
I think maybe `None` is better

**Comment by richardjgowers** [comment]
see #1738

**Comment by IAlibay** [comment]
I'd also prefer `None` here. 

It could be worth creating a list of all the Readers/Writers that will be affected by such a change.

**Comment by RMeli** [comment]
I don't think we decided, but I agree that `None` is better in this case.

```
if u.dimensions is None:
    pass
```
versus
```
if np.allclose(u.dimensions, np.zeros(6)):
    pass
```

**Comment by IAlibay** [comment]
So this got brought up in the context of v1.0 (#2443). A quick look through seems to indicate (I might be missing something here) that this probably won't be a straightforward fix (if anything we'd have to add in more tests to check that each file type is behaving properly). Considering the need to get v1.0 soon-ish, I would suggest putting this as a goal for v2.0.

**Comment by HanatoK** [comment]
I encountered an error related to this issue. If `self._unitcell` is `None`, then the current setter in `base.py`:
```
@dimensions.setter
def dimensions(self, box):
    self._unitcell[:] = box
```
will run into error (`'NoneType' object does not support item assignment`). However, it is a common case that if the unit cell information is not in a PDB or trajectories, the user will setup the cell manually through
```
u.trajectory[0].triclinic_dimensions = <user_defined_cell_information>
```
and this will trigger the error above. Currently I workaround the error by using `self._unitcell = np.copy(box)`
Is there a solution to solve the problem?
