### ISSUE TITLE
Temporary files created by `TestAlignmentProcessing`

### ISSUE THREAD

**Issue by IAlibay** [MDAnalysis/mdanalysis#2701]
## Expected behavior ##

Running tests should not create any temporary files.

## Actual behavior ##

For some strange reason, running `TestAlignmentProcessing` in analysis.test_align is creating extra "test.aln" and "test.dnd" files (see #2700).

I have no idea what changed about my environment that caused this (this is a fresh dev install). <s>Passing `tmpdir` to the function here seems to fix the issue though.</s> I'm wrong here, it's still happening.

## Code to reproduce the behavior ##

pytest test_align.py

## Current version of MDAnalysis ##

- Which version are you using? (run `python -c "import MDAnalysis as mda; print(mda.__version__)"`) 0.20.2-dev0
- Which version of Python (`python -V`)? 3.7.7
- Which operating system? Ubuntu 20.04 LTS via WSL

**Comment by IAlibay** [comment]
Ok, I've finally properly narrowed it down. The issue is with `test_fasta2select_file`.

What happens here is that in when `alignfilename=None` you get this: https://github.com/MDAnalysis/mdanalysis/blob/55afb4c36328e79c1390c0f4364b2cf5c1aff481/package/MDAnalysis/analysis/align.py#L1043-L1045
Which leads to files being generated outside cwd (hence the generation of persistent temporary files even if you use `tmpdir.as_cwd()`.

My suggestion here would be to add `os.path.basename` to the `alnfilename` construction so that the files are always created in cwd (unless there's a reason for allowing the alnfile and the treefile to the same directory as where the fasta file is)?

**Comment by tylerjereddy** [comment]
Not sure if my fault--I did recently migrate us to the `pytest` `tmpdir` stuff and away from our in-house solution. I thought I checked for artifacts pretty carefully, but some tests maybe didn't run on my machine for whatever reason.

**Comment by IAlibay** [comment]
@tylerjereddy That could explain why the issue is only popping up now (I think the specific test in question is skipped if you don't have clustalw installed). However, looking at the code for the default filenames, to me at least it looks like it _should_ have always tried to write outside of the temporary directory.

In any case, I would like to push for the solution of changing the default filenames behaviour. Mainly because, at least to me, writing files outside of $PWD by default seems rather unintuitive / confusing.

**Comment by orbeckst** [comment]
Change it to use PWD... this looks like something I wrote in the olden days :-p, sorry.
