### ISSUE TITLE
CI: Azure pipelines runs

### ISSUE THREAD

**Issue by tylerjereddy** [MDAnalysis/mdanalysis#2708]
Looking at a few recent PRs, I'm not seeing the Azure pipelines entry in the CI list (for Windows 32-bit testing). Seems to only be running on the merge commits when people open PRs from feature branches on their forks: 

https://dev.azure.com/mdanalysis/mdanalysis/_build?view=runs

This should "just work," and I see  we have the marketplace app installed in our repo settings. I probably just forgot to tweak something silly, either in the `yml` file or for the app itself.

Also, I should add a few core team members to the account there for those that are willing to get logins to alleviate the bus factor, etc.

**Comment by tylerjereddy** [comment]
I found it and turned it on--the setting was off:

![image](https://user-images.githubusercontent.com/7903078/83709037-e7e1a600-a5da-11ea-8c7e-2484e920c8ab.png)

**Comment by tylerjereddy** [comment]
I see Azure showing up in the fork-originated PR #2709. I'm going to close that dummy PR for now, but I will keep this issue open until I've seen a few more PRs to MDAnalysis from developer feature branches on forks that trigger Azure automatically. Then I'll close this.

**Comment by tylerjereddy** [comment]
Looking at recent pushes to PRs that are open from feature branches originating in developer GitHub forks, it is clear that the Azure CI triggers are now working. So, closing this issue.

**Comment by orbeckst** [comment]
Thanks @tylerjereddy !

**Comment by orbeckst** [comment]
Do the Azure runs contribute to coverage reporting?

**Comment by tylerjereddy** [comment]
Not at the moment, but we could add that to fuse the data with the other codecov reports--that's probably what you mean.

Azure also has its own built in test and coverage reporting dashboards/infrastructure, so the initial addition was just a draft.

I imagine I/we still need to install more dependencies there too--perhaps a few tests may still be skipped that could be run. I'll try to chip away at that stuff.

**Comment by orbeckst** [comment]
> On Jun 5, 2020, at 6:19 AM, Tyler Reddy <notifications@github.com> wrote:
> 
> Not at the moment, but we could add that to fuse the data with the other codecov reports--that's probably what you mean.
> 

Yes, exactly. Would be good to see if there are code paths that we haven’t seen before. Maybe running the coverage script at the end is enough?

Thanks for working on it. I was also pleasantly surprised how fast these jobs ran.
