### ISSUE TITLE
lib.test_distances.test_coords_in_central_image_tric fails on some gcc version

### ISSUE THREAD

**Issue by IAlibay** [MDAnalysis/mdanalysis#2722]
## Expected behavior ##

All tests run.

## Actual behavior ##

Both the serial and openmp versions of lib.test_distances.test_coords_in_central_image_tric fail on "assert np.all(res >= 0.0)".

As pointed out by @lilyminium it looks like a precision issue. On generating `res`, res[0,0] and res[2, 0] have negative values of order - 1 e-7. This propagates down when calling `transform_RtoS` and causes the test to fail.

## Code to reproduce the behavior ##

pytest test_distances.py

## Current version of MDAnalysis ##

- Which version are you using? (run `python -c "import MDAnalysis as mda; print(mda.__version__)"`) 0.20.2-dev0
- Which version of Python (`python -V`)? Many (3.6+)
- Failing gcc version: 9.3, 8.4 (tested by @lilyminium)
- Working versions of gcc: 7.4
- Working versions of clang: 11.0 (tested by @RMeli)
- Which operating system? Many

**Comment by IAlibay** [comment]
I _think_ I've narrowed it down to some -ffast-math magic

**Comment by richardjgowers** [comment]
But ffast-math is my ffavourite :(

**Comment by IAlibay** [comment]
So related here, Travis uses gcc 5.4 and clang 7.0 (I'm not sure which one setup.py is defaulting to here). We probably want to add something to the test matrix that uses newer versions of the compilers.
