### ISSUE TITLE
Versioned docs

### ISSUE THREAD

**Issue by lilyminium** [MDAnalysis/mdanalysis#2741]
## Is your feature request related to a problem? ##

With 2.0 coming soon (hopefully) we really need versioned documentation.

## Describe the solution you'd like ##

Based on [related discussion on the user guide](https://github.com/MDAnalysis/UserGuide/issues/67) I'm going to try building this into the Travis pipeline instead of hosting on RTD or similar services.

## Describe alternatives you've considered ##

The alternative is hosting on ReadTheDocs, but as @orbeckst points out that comes with potential added problems if RTD breaks and also a small RTD ad in the sidebar.

## Additional context ##

Currently our docs are at mdanalysis.org/docs. We could:

- keep the status quo and have mdanalysis.org/docs/$version urls, where mdanalysis.org/docs redirects to mdanalysis.org/docs/$latest_release and mdanalysis.org/mdanalysis redirects to mdanalysis.org/docs/$dev_version
- switch it up to docs.mdanalysis.org/$version , where both mdanalysis.org/docs and docs.mdanalysis.org/ redirect to docs.mdanalysis.org/$latest_release

I really like the conceptual separation of the second one. All it requires is changing the URL in settings from mdanalysis.org/mdanalysis to docs.mdanalysis.org/, and adding a CNAME DNS record. Any opinions?

**Comment by orbeckst** [comment]
I am happy with the second solution.

*docs.mdanalysis.org* is a CNAME for *www.mdanalysis.org*. At the moment, there exists a Cloudflare page rule (see [our wiki page on DNS](https://github.com/MDAnalysis/MDAnalysis.github.io/wiki/DNS)) that performs a subdomain-forward to https://www.mdanalysis.org/docs. Presumably, you'll have to delete this rule first (which you should be able to do and which should not break anything major as nobody is aware of https://docs.mdanalysis.org and all our links use the normal path – just update the DNS wiki page).

**Comment by lilyminium** [comment]
Ok, updated it so mdanalysis.org/mdanalysis now goes to docs.mdanalysis.org/. This got rid of one PageRule so there's an extra one now!
