### ISSUE TITLE
Waterdynamics depends on deprecated hbonds module

### ISSUE THREAD

**Issue by RMeli** [MDAnalysis/mdanalysis#2745]
`analysis.waterdynamics` uses `analysis.hbonds` which is deprecated in 1.0 and scheduled for removal in 2.0 (see #2739).

**Comment by RMeli** [comment]
Attribute `timeseries` is missing from the new `HydrogenBondAnalysis` but it is used in `HydrogenBondLifetimes.run()`

**Comment by RMeli** [comment]
@alejob @p-j-smith @MDAnalysis/coredevs I stumbled into this while trying to help @IAlibay with #2739 (see #2746 ) but I'm not very familiar with the `waterdynamics.py` and `hbonds` analysis modules. Do you have any suggestion on how to best fix this problem?

**Comment by alejob** [comment]
Hey there, is any replace for `analysis.hbonds`???

**Comment by orbeckst** [comment]
Yes, `analysis.hydrogenbonds`, see [MDAnalysis.analysis.hydrogenbonds.hbond_analysis](https://www.mdanalysis.org/docs/documentation_pages/analysis/hydrogenbonds.html) – it still has a [HydrogenBondAnalysis](https://www.mdanalysis.org/docs/documentation_pages/analysis/hydrogenbonds.html#MDAnalysis.analysis.hydrogenbonds.hbond_analysis.HydrogenBondAnalysis) class but it's called a little bit differently (and it's faster).

**Comment by xiki-tempula** [comment]
My suggestion would be using the water bridge analysis module.
For `MDAnalysis.analysis.waterdynamics.HydrogenBondLifetimes`
```
    def run(self, **kwargs):
        """Analyze trajectory and produce timeseries"""
        h_list = MDAnalysis.analysis.hbonds.WaterBridgeAnalysis(self.universe,
                                                                 self.selection1,
                                                                 self.selection2,
                                                                 distance=3.5,
                                                                 angle=120.0,
                                                                 order=0,# For hydorgne bond detection
                                                                 update_selection=True, # This is default to false in water bridge analysis
)
        h_list.run(**kwargs)
        self.timeseries = self._getGraphics(h_list.timeseries, self.t0,
                                            self.tf, self.dtmax)
```

**Comment by alejob** [comment]
I understand that `HydrogenBondLifetimes` will be removed from waterdynamics, so this update is not necessary anymore.

**Comment by IAlibay** [comment]
@alejob do we have a path already defined for this? We probably need to consider what the deprecation order is going to be for this. We probably can't do a straight removal for 2.0, maybe we'd have to consider deprecating in 1.x or just a stub to the replacement if it behaves the same way?

**Comment by alejob** [comment]
The class was already removed for v2.0, see https://github.com/MDAnalysis/mdanalysis/pull/2842.

**Comment by IAlibay** [comment]
I see the deprecation warning got added in #2798, that makes sense.

I think the only thing leftover in waterdynamics from the old hbonds is an unused import then?
https://github.com/MDAnalysis/mdanalysis/blob/23074c64f5de2795756c44eb16e488d4f1d253f0/package/MDAnalysis/analysis/waterdynamics.py#L392

That'll get itself taken care of when we remove the old hbonds code, so I'm going to go ahead and close this issue unless there's any objections.
