### ISSUE TITLE
CI - ASV currently runs 2.7

### ISSUE THREAD

**Issue by IAlibay** [MDAnalysis/mdanalysis#2747]
## Expected behavior ##

All CI tests return green.

## Actual behavior ##

As mentioned https://github.com/MDAnalysis/mdanalysis/pull/2729#discussion_r438284051 our CI matrix currently call ASV but with py2.7. So attempts to switch to py3+ constructs lead to CI failures (see: https://travis-ci.com/github/MDAnalysis/mdanalysis/jobs/347441669).

## Context ##

From its docs, ASV can handle up to py3.6, however I assume by https://github.com/MDAnalysis/benchmarks/issues/9#issue-341729013 that for MDAnalysis/benchmarks it's not just as simple as updating the CI matrix?

**Comment by orbeckst** [comment]
The details are in https://github.com/MDAnalysis/benchmarks/wiki/automated-benchmark and the linked pages. Primarily I need to change the cron job to use Python 3.6. I'll also need to figure out from which commit it makes sense to re-run benchmarks in the 3.6 environment.

**Comment by orbeckst** [comment]
Things to do
- [x] make sure that we only run 3.6 benchmarks since 0.17.0: in `benchmarking/benchmarks/scripts/cron.sh`
   ```bash
    timeout 20h asv run -e -j 4 --config ${ASV_CONFIG} "release-0.17.0..HEAD --merges" --skip-existing || true
- [x] change matrix to 3.6 in `ASV_CONFIG="${ASV_RUN_DIR}/asv_c3potato.conf.json"`
   ```json
   "pythons": ["3.6"]
   ```

**Comment by orbeckst** [comment]
The 3.6 history is currently being run – will take about 5 days.

**Comment by orbeckst** [comment]
For progress on the data generation follow https://github.com/MDAnalysis/benchmarks/issues/9

**Comment by orbeckst** [comment]
Python 3.6 benchmarks are now up and running continuously.
