### ISSUE TITLE
bynum selections don't work from AtomGroup instances.

### ISSUE THREAD

**Issue by mnmelo** [MDAnalysis/mdanalysis#275]
Small bug, simple to fix, where `bynum n` returns the n-th atom in the object it was called from, rather than always returning the n-th atom in the `Universe`.
I'm reporting it here for the sake of documentation.

```python
sel = universe.atoms[1000:1004]

sel._atoms
Out: 
[<Atom 1001: CG of type C of resname LEU, resid 67 and segid SYSTEM>,
 <Atom 1002: HG of type H of resname LEU, resid 67 and segid SYSTEM>,
 <Atom 1003: CD1 of type C of resname LEU, resid 67 and segid SYSTEM>,
 <Atom 1004: HD11 of type H of resname LEU, resid 67 and segid SYSTEM>]

sel.selectAtoms("bynum 1001")
Out: <AtomGroup with 0 atoms>

sel.selectAtoms("bynum 1")
Out: <AtomGroup with 1 atoms>

sel.selectAtoms("bynum 1")._atoms
Out: [<Atom 1001: CG of type C of resname LEU, resid 67 and segid SYSTEM>]
```

**Comment by richardjgowers** [comment]
Ha, you're on fire!

It looks like there's not a test for this atm, in fact most the tests are all based on u.atoms.select and never atomgroup.select

**Comment by mnmelo** [comment]
Well... things are piling up one on another.
For now I'm adding test cases for the selections I'm fixing. We might think about generalizing it (like, run every selection test at both `Universe` and `AtomGroup` levels) but I'm not sure how easy that'll be in that most of the code would probably have to be duplicated regarding the comparison targets.

**Comment by richardjgowers** [comment]
Yeah sorry, I didn't mean to make you rewrite the entire selections test harness, I think just covering this Issue would suffice :D

I think you're right though, a cool solution would be a test generator that goes through a standard set of tests on the many different start points we can have (maybe mixin a different start group).
