### ISSUE TITLE
Clean up gh-pages

### ISSUE THREAD

**Issue by lilyminium** [MDAnalysis/mdanalysis#2760]
## Expected behavior ##

`gh-pages` contains only the things we need for the docs to work. 

## Actual behavior ##

The new script in Travis did not remove the old stuff (and this is required to keep doc versions going) but simply added new stuff. The old directories and files are docs that no longer need to be in the root directory:

* _images
* _modules
* _sources
* _static
* documentation_pages
* genindex.html
* objects.inv
* py-modindex.html
* search.html
* searchindex.js
* sitemap.xml

## Code to reproduce the behavior ##

https://github.com/MDAnalysis/mdanalysis/tree/gh-pages

## Current version of MDAnalysis ##

- Which version are you using? (run `python -c "import MDAnalysis as mda; print(mda.__version__)"`) https://github.com/MDAnalysis/mdanalysis/commit/c761ba3538fefe5df96f28f4c0b33990a72196f0
- Which version of Python (`python -V`)?
- Which operating system?

**Comment by orbeckst** [comment]
Fixed with #2761
