### ISSUE TITLE
Links for google group badges broken

### ISSUE THREAD

**Issue by IAlibay** [MDAnalysis/mdanalysis#2766]
## Expected behavior ##

Clicking on the README.md's badges gets me to the right place.

## Actual behavior ##

Credit to @RMeli for pointing this one out, for some reason the links associated for the google group badges (http://users.mdanalysis.org/) and (http://developers.mdanalysis.org/) don't point to anywhere.

Unless these were meant to point somewhere, we could probably just use https://groups.google.com/group/mdnalysis-discussion and https://groups.google.com/group/mdnalysis-devel instead?

**Comment by lilyminium** [comment]
I think these are a couple of those [spotty subdomain redirects](https://github.com/MDAnalysis/UserGuide/issues/67#issuecomment-643423337) that @orbeckst removed a few days ago; redirecting to google groups is probably the best answer here, yeah.

**Comment by orbeckst** [comment]
Yes, sorry – I didn't realize that the redirects were actually used somewhere.
