### ISSUE TITLE
Release 1.0.1

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/mdanalysis#2768]
A few things are accumulating for a patch-level release for 1.0, related to

- installation
- performance regressions

The point is to make 1.0.x a stable platform for anyone who needs legacy MDAnalysis for the foreseeable feature. 1.0.x should not be worse than 0.20.1.

**Comment by orbeckst** [comment]
One potentially controversial statement in _Challenge to scientists: does your ten-year-old code still run?_ Nature 2020 doi:[10.1038/d41586-020-02462-7](https://doi.org/10.1038/d41586-020-02462-7) 
> Newer languages’ rapidly evolving APIs and reliance on third-party libraries make them vulnerable to breaking. In that sense, the sunsetting of Python 2.7 at the start of this year represents an opportunity for scientists, Rougier and Hinsen note. Python 2.7 puts “at our disposal an advanced programming language that is guaranteed not to evolve anymore”, Rougier writes (Rougier, N. P. ReScience C https://doi.org/10.5281/zenodo.3886628).

provides some additional motivation for making sure that we have a stable Python 2.7-capable release.

**Comment by orbeckst** [comment]
The backports from PR #2798 are now included.

The remaining major issues is to either disable capped-distance with nsgrid #2930 or fix it.

**Comment by jbarnoud** [comment]
The fix for #2984 could be backported.

**Comment by IAlibay** [comment]
So after some off-github discussions with @lilyminium and @richardjgowers, we were wondering how everyone would feel about pushing for a rapid 1.0.1 release where we disable nsgrid completely and then have aim for a 1.0.2 release with @richardjgowers' fix?

If the mailing list is any indication, quite a lot of people are facing issues with things that are now fixed in `master`, on top of that we've got this nsgrid bug that users probably aren't aware of. Personally I think it would be better for everyone to have some type of patch fix out there earlier than later?

pinging @MDAnalysis/coredevs here.

**Comment by lilyminium** [comment]
+1 for releasing an interim 1.0.1 as strictly better than keeping 1.0.0 until the fix is in (e.g. all the pytest failures)

**Comment by orbeckst** [comment]
Yes, I agree – disable nsgrid #2930 for 1.0.1.

I'd also include a backport fix for #2984 and then do a 1.0.1. We can really do a patch release in rapid succession. Doubt that anyone minds getting code fixed.

**Comment by lilyminium** [comment]
And #2427!

**Comment by orbeckst** [comment]
I'll backport PR #2427.

**Comment by orbeckst** [comment]
Outstanding backports/fixes
- [ ] #2930
- [ ] backport PR #2427 
- [ ] backport #2984

**Comment by orbeckst** [comment]
The deprecation of hbond.waterbridge analysis in PR #2913 could go in 1.0.1 if it gets turned around quickly. Otherwise we make a 1.0.2 soon-ish.

**Comment by orbeckst** [comment]
Unfortunately, I broke Travis for master (see PR #3011) so that PR also has to go through before we can wrap 1.0.1.

**Comment by IAlibay** [comment]
Just FYI unless there's any objections, I'm going to declare a code freeze on 1.0.1 (excluding release related CI/maintenance stuff).

There's a lot of things that still need deprecating/backporting (e.g. #2913, #2857), and then the nsgrid fix, so we'll need to cut a 1.0.2 release for them.

I still have hopes we can release this week, assuming we don't encounter more upstream issues...

**Comment by IAlibay** [comment]
Release 1.0.1 has been completed -- closing
