### ISSUE TITLE
set status to mature

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/mdanalysis#2773]
Our classifiers should indicate that we're out of beta (after > 12 years?).

https://github.com/MDAnalysis/mdanalysis/blob/788f294e53ca19fdfba8cc7e2f86d0de7be82bbf/package/setup.py#L534

Should be changed for 
- 1.x
- 2.x

**Comment by IAlibay** [comment]
Somehow the autoclose keywords on the two PRs didn't work, closing now.

**Comment by orbeckst** [comment]
Apparently, it only works for merges into develop.
