### ISSUE TITLE
parallel testing crashes (matplotlib?)

### ISSUE THREAD

**Issue by IAlibay** [MDAnalysis/mdanalysis#2780]
## Expected behavior ##

running `pytest -n4 .` in `testsuite/MDAnalysisTests` should complete successfully.

## Actual behavior ##

Several tests (all of which seem to use matplotlib) fail with "node down: Not properly terminated" issues.

test failures:

analysis/test_dihedrals.py::TestJanin:test_plot
anlysis/test_dihedrals.py::TestRamachandran::test_plot
analysis/test_persistencelength.py::TestPersistenceLength::test_current_axes
visualization/test_streamlines.py::test_streamplot_2D
analysis/test_persistencelength.py::TestPersistenceLength::test_plot_with_ax
analysis/test_psa.py::TestPSAnalysis::test_dendrogram_produced
analysis/test_persistencelength.py::TestPersistenceLength::test_plot_ax_return

## Current version of MDAnalysis ##

- Which version are you using? (run `python -c "import MDAnalysis as mda; print(mda.__version__)"`) 2.0.0-dev0
- Which version of Python (`python -V`)? 3.7.7
- Which operating system? Ubuntu 20.04 LTS (WSL2)

**Comment by IAlibay** [comment]
So I can confirm this issue is down to my X-server not being enabled on my WSL2 instance. I'll try it later on a non X-forwarded ssh session and see if it's unique to my setup / WSL2.

**Comment by lilyminium** [comment]
I can't reproduce this with 2.0.0-dev0 on python 3.7.6 and non-WSL 20.04 LTS, if that helps.

**Comment by IAlibay** [comment]
It looks to me like the issue is related to the changes in #2763. I can't replicate it on a remote linux machine without X-forwarding.

It looks like it's a rather unique failure case where $DISPLAY is set to a value but this $DISPLAY location isn't accessible (essentially the X-server is down) by matplotlib to use, so the mpl backend doesn't default to "agg" and fails.

Exporting `MPLBACKEND=agg` (as per what we do with travis/appveyor/azure) does the trick here. Considering how unique to the situation this is (I guess maybe other WSL users might face this), I'm going to say this one is related to user error and close the issue.
