### ISSUE TITLE
Cleaning up analysis.__ini__ and hole2 docs

### ISSUE THREAD

**Issue by IAlibay** [MDAnalysis/mdanalysis#2786]
As discussed in this thread: https://github.com/MDAnalysis/mdanalysis/pull/2778#discussion_r443195698 the `analysis.__init__` docstring doesn't seem to be used anywhere and is somewhat superseded by `analysis_modules.rst`, thoughts on what to do with this text?

Furthermore, linked to that same PR, it seems that there is no page specifically for `analysis.hole2`, with the docstring instead being in `analysis.hole2.hole`. Should we be moving the core of the `hole2.hole` docstring to `hole2.__init__` instead?

**Comment by orbeckst** [comment]
I often use `help(module)` or `module?` and then it's nice if a short, comprehensible doc string appears. If we don't use the doc string in the generated docs then I would suggest to cut down `analysis.__init__` to something  brief (and possibly include a link to the online docs).

All the classes and functions that are important for a user show up under `analysis.hole2` so I'd expect the docs to reflect it broadly. I.e., have the general docs appear for `hole2` there, so I would move the general docs from `hole2.hole` to `hole2.__init__` and have the classes/functions remain in `hole2.hole`. I have lately played around with [sphinx.autosummary](https://www.sphinx-doc.org/en/master/usage/extensions/autosummary.html) and one could put a summary of classes into `hole2`.

**Comment by manishsaini6421** [comment]
@orbeckst Sir , i have fixed this issue. can you review it please.

**Comment by IAlibay** [comment]
@manishsaini6421 both @lilyminium and I have commented on https://github.com/MDAnalysis/mdanalysis/pull/3579, those comments will need to be addressed before we consider reviewing.

**Comment by manishsaini6421** [comment]
@lilyminium what i have to fill in this field during the final application.[https://drive.google.com/file/d/1NA29pjDVaSucBQslmwXphxXrgwvYe7Gu/view?usp=sharing](url)

**Comment by lilyminium** [comment]
Closed by #3579
