### ISSUE TITLE
Python 2.6 Support

### ISSUE THREAD

**Issue by richardjgowers** [MDAnalysis/mdanalysis#279]
Support for Python 2.6 is up for debate

Points for discussion
 - Does anyone actually still use 2.6?
 - Would keeping 2.6 hinder Python 3 port?

Related dev mailing list discussion:

https://groups.google.com/forum/#!topic/mdnalysis-devel/ailYSQSYbL8

**Comment by hainm** [comment]
it is not worth trying 2.6. should focus on 2.7 and make 3 compat.
with conda, it is much easier to get Python.

Hai

**Comment by richardjgowers** [comment]
So 2.6 works for now.
