### ISSUE TITLE
https://docs.mdanalysis.org/ redirects to https://mdauserguide.minium.com.au/1.0.0/

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/mdanalysis#2800]
## Expected behavior ##
docs url leads to the generated MDA docs

## Actual behavior ##

redirects to @lilyminium 's test User Guide https://mdauserguide.minium.com.au/1.0.0/

## Code to reproduce the behavior ##

look at https://docs.mdanalysis.org/

**Comment by orbeckst** [comment]
https://www.mdanalysis.org/docs/ is working

**Comment by lilyminium** [comment]
that's really unexpected

**Comment by orbeckst** [comment]
I'll reopen until we have confirmation that it is fixed.

**Comment by orbeckst** [comment]
Works again
- https://docs.mdanalysis.org leads to https://docs.mdanalysis.org/1.0.0/
- https://docs.mdanalysis.org/2.0.0-dev0/ is also available

**Comment by lilyminium** [comment]
Yay, will try not to do that again. 

I set up the docs to point to the latest release by default but http://docs.mdanalysis.org/dev should point to the dev version. Given the coexistence of mdanalysis.org/docs, should this default be changed to the dev version?

**Comment by orbeckst** [comment]
Are you asking if MDAnalysis.org/docs should point to dev or last release? I think it should remain the last release as there might be links elsewhere using it. 

Btw, we should change the links on our homepage and sidebar. Also, how about changing the sidebar from gray to black to agree with the userguide/docs style?

**Comment by lilyminium** [comment]
Cool, I've raised an issue on the website repo. Reflecting on how this happened a little, I wonder if this means that anyone with sufficient knowledge could open a PR and overwrite our docs, since I accidentally pushed changes to this repo via a PR to master on my own fork. Also, could someone write "echo $GH_TOKEN" and get the decrypted key? That could be a problem.

**Comment by lilyminium** [comment]
#2802 says no, I think. In that case, when I accidentally pushed to here, I must have used my own personal access token and given it too many permissions. That's a relief.

**Comment by orbeckst** [comment]
Thanks for testing… indeed, relief.

> On Jun 27, 2020, at 4:45 AM, Lily Wang <notifications@github.com> wrote:
> 
> #2802 <https://github.com/MDAnalysis/mdanalysis/pull/2802> says no, I think. In that case, when I accidentally pushed to here, I must have used my own personal access token and given it too many permissions. That's a relief.

--
Oliver Beckstein
orbeckst@gmail.com
