### ISSUE TITLE
Insertion code attribute not available for single atom

### ISSUE THREAD

**Issue by cbouy** [MDAnalysis/mdanalysis#2803]
## Expected behavior ##

Accessing `u.atoms[0].icode` should return the icode value if the icodes are present

## Actual behavior ##

Even if the icodes attribute exists, the above will return a NoDataError. `u.atoms.icodes[0]` will work though

## Code to reproduce the behavior ##

``` python
import MDAnalysis as mda
import numpy as np

u = mda.Universe.from_smiles("CCO")
icodes = np.array(["X"], dtype=object)
u.add_TopologyAttr("icodes", icodes)

u.atoms.icodes
# array(['X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X'], dtype=object)

u.atoms[0].icode
# NoDataError: This Universe does not contain icode information
```
Doing the same with the `resnames` attribute will not reproduce this error:

```python

resnames = np.array(["UNK"], dtype=object)
u.add_TopologyAttr("resnames", resnames)

u.atoms.resnames
# array(['UNK', 'UNK', 'UNK', 'UNK', 'UNK', 'UNK', 'UNK', 'UNK', 'UNK'], dtype=object)

u.atoms[0].resname
# 'UNK'

```

## Current version of MDAnalysis ##

- Which version are you using? (run `python -c "import MDAnalysis as mda; print(mda.__version__)"`)
2.0.0-dev0
- Which version of Python (`python -V`)?
Python 3.6.10
- Which operating system?
Ubuntu 18.04.4 LTS through a VM (WSL2)

**Comment by lilyminium** [comment]
I think this is because `Atom` is not a `target_class` of `Icodes`. @richardjgowers given that most residue attributes include it in their target_classes, should Atom be in there by default? Same for SegmentAttrs with Atom and Residue
