### ISSUE TITLE
Typo in RMSF docstring

### ISSUE THREAD

**Issue by IAlibay** [MDAnalysis/mdanalysis#2806]
## Expected behavior ##

Following examples in docstring should work.

## Actual behavior ##

I believe there is a typo in https://github.com/MDAnalysis/mdanalysis/blob/343e10a257690e4312673f2a0fa4703b31b2e223/package/MDAnalysis/analysis/rms.py#L741

The reference is missing, it probably should be `align.AlinTraj(u, u, select...)` (as per the PMDA docstring)?

## Current version of MDAnalysis ##

develop doctstring

**Comment by orbeckst** [comment]
Also worthwhile checking what the User Guide says... and it seems that it doesn't have an entry for RMSF yet, at least in the [1.0.0  / Jun 25, 2020 version](https://userguide.mdanalysis.org/). PR https://github.com/MDAnalysis/UserGuide/pull/38 says that there's an entry  on RMSF but I couldn't find it in the linked [forked ug](https://lilyminium.github.io/UserGuide/examples/analysis/README.html). 

@lilyminium , did you write a RMSF section for the UG and if so, where can it be found?

**Comment by lilyminium** [comment]
I think I overwrote my doc build for the fork when I was doing the Travis script for versioned user guides. I've added the RMSF to https://github.com/MDAnalysis/UserGuide/pull/75 but I expect it won't build until the seg fault is fixed (https://github.com/MDAnalysis/UserGuide/issues/82)
