### ISSUE TITLE
boolean indexing of AtomGroup

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/mdanalysis#282]
AtomGroups implement most of fancy indexing and behave mostly like good numpy arrays. However, boolean indexing does NOT work:
```python
import numpy as np
import MDAnalysis; from MDAnalysis.tests.datafiles import PSF, DCD      
u = MDAnalysis.Universe(PSF, DCD)
wanted_atoms = u.selectAtoms("prop x < 0 and prop y < 0")

# try with boolean indexing
mask = np.logical_and(u.atoms.positions[:,0] < 0, u.atoms.positions[:,1] < 0)
myatoms = u.atoms[mask]

# fails
assert len(wanted_atoms) == len(myatoms)   # 784 != 3341
assert list(wanted_atoms) == list(myatoms)
```
At the moment, this fails because the boolean array is interpreted as ``[0, 0, 1, 1, ...]`` and hence we just get a sequence of the first and second atom, 3341 times.

A possible hack is to do 
```python
ix = np.arange(len(mask))[mask]
myatoms = u.atoms[ix]

assert len(wanted_atoms) == len(myatoms)
assert list(wanted_atoms) == list(myatoms)
```
Note that creating the index by boolean indexing of arange is about 3x faster than using ``np.where``, at least that's what quick benchmarks showed.

I propose to add something along the lines of the hack to `AtomGroup.__getitem__` to round out the API.

Any takers (who'd also implement a unit test)? Glory awaits!!

**Comment by orbeckst** [comment]
Once this implemented, one can use it to clean up some rather ugly code in `analysis.align.get_matching_atoms()`...

**Comment by richardjgowers** [comment]
I think it'd be good if this became some sort of function like `core.util._process_slice`, so that our fancy slicing a) behaves identically across all of MDA b) is tested properly

So objects that we have that could use this function..... AtomGroup, TopologyGroup, Reader?  Not sure on Reader because it's more like a generator
