### ISSUE TITLE
Raise the minimum numpy version

### ISSUE THREAD

**Issue by cbouy** [MDAnalysis/mdanalysis#2827]
## Is your feature request related to a problem? ##

In PR #2775 @IAlibay suggested that it might be a good idea to set the minimum version for RDKit to 2020. 
This version is however not compatible with `numpy==1.13.3`.  
Since python < 3.6 is no longer supported and there's already a discussion to drop 3.6 on the [mailing list](https://groups.google.com/forum/#!topic/mdnalysis-devel/vCDDPH_2iTo), it might be a good time to raise the minimal version of numpy to at least `1.15.0` (compatible with rdkit 2020.03.1).

**Comment by jbarnoud** [comment]
The discussion in the mailing list is about following the support scheme for python and NumPy described in that document: https://numpy.org/neps/nep-0029-deprecation_policy.html

The support table would look like:


Date | Python | NumPy
-- | -- | --
Jan 07, 2020 | 3.6+ | 1.15+
Jun 23, 2020 | 3.7+ | 1.15+
Jul 23, 2020 | 3.7+ | 1.16+
Jan 13, 2021 | 3.7+ | 1.17+
Jul 26, 2021 | 3.7+ | 1.18+
Dec 26, 2021 | 3.8+ | 1.18+
Apr 14, 2023 | 3.9+ | 1.18+

Except if 2.0.0 is released this month, it means our minimal supported versions would be python 3.7 and numpy 1.16. By supporting python 3.6 and numpy 1.15, we are conservative regarding that scheme, which I am happy with.

There has not been so much participation on the mailing list discussion, so it would be good if some more @MDAnalysis/coredevs could chip in.

**Comment by IAlibay** [comment]
Unless anyone has any objections, from that table it make sense to set the minimum version 1.16. Technically 1.16 still supports py3.5-3.7 (https://numpy.org/devdocs/release/1.16.0-notes.html) and I very much doubt that we'd do a 2.x release before the end of this month.

@cbouy would you be ok with creating a PR to raise the minimum numpy version and rdkit to 2020+?
