### ISSUE TITLE
bfactors and tempfactors

### ISSUE THREAD

**Issue by RMeli** [MDAnalysis/mdanalysis#2833]
## Expected behavior ##

I expect attributes representing the same thing to be consistent across file formats.

## Actual behavior ##

For the MMTF format we have the `bfactors` attribute, while for other formats we have `tempfactors` (see [user guide](https://userguide.mdanalysis.org/1.0.0/formats/index.html#topology)).

From a quick search within the code, I think `bfactors` is also used by `TPRParser` and `ParmEdParser`.

In `topologyattrs.py`there are both `class Tempfactors` and `class Bfactors`. Should the two attributes be merged?

**Comment by lilyminium** [comment]
[Yes!](https://github.com/MDAnalysis/mdanalysis/issues/1901)

It's especially annoying that the PDB format only uses `tempfactors` when writing out to PDB, as that's quite a common task to do for [e.g. RMSF visualisation](http://minium.com.au/UserGuide/examples/analysis/alignment_and_rms/rmsf.html#Visualising-RMSF-as-B-factors).

At least in Oct 2019 [TPRParser did not actually have either bfactors or tempfactors](https://github.com/MDAnalysis/mdanalysis/issues/2362). ParmedParser [uses Tempfactors](https://github.com/MDAnalysis/mdanalysis/blob/56cb47c93eda3574c84788ad374e0723068fcbf2/package/MDAnalysis/topology/ParmEdParser.py#L236) despite ParmEd calling them bfactors (as does nglview).

Personally I prefer bfactors > tempfactors, but the latter seems to be the majority attribute.

**Comment by RMeli** [comment]
I must learn to search for open issues before opening new ones...

**Comment by RMeli** [comment]
@lilyminium you are right about the `TRPParser`; it popped up because of a docstring:

https://github.com/MDAnalysis/mdanalysis/blob/3e56b70da3b48a523924308e1149d46fadddbb5d/package/MDAnalysis/topology/TPRParser.py#L114

**Comment by orbeckst** [comment]
duplicates #1901
