### ISSUE TITLE
References are formatted properly

### ISSUE THREAD

**Issue by lilyminium** [MDAnalysis/mdanalysis#2837]
## Expected behavior ##

References are formatted properly

## Actual behavior ##

Mark*down* markup != reStructuredText

<img width="639" alt="Screen Shot 2020-07-11 at 6 41 32 am" src="https://user-images.githubusercontent.com/31115101/87201332-b37fa900-c341-11ea-990c-ffa9036d5b09.png">

## Code to reproduce the behavior ##

https://github.com/MDAnalysis/mdanalysis/blob/3e56b70da3b48a523924308e1149d46fadddbb5d/package/MDAnalysis/analysis/contacts.py#L257

## Current version of MDAnalysis ##

2.0.0-dev0 docs

## More ##

It might be easier to just use bibtex and autoformat the references, as the user guide does. Then we'll  also have a consistent style.

**Comment by jbarnoud** [comment]
+1 for bibtex.

**Comment by orbeckst** [comment]
Is there a way to generate doi links with appropriate bibtex styles?

**Comment by lilyminium** [comment]
https://userguide.mdanalysis.org/1.0.0/references.html#michaud-agrawal-mdanalysis-2011

The default style has linked URLs and DOIs. I haven't figured out how to change the inline citation style though (surname initials + year, that one shows up as MADWB11).
