### ISSUE TITLE
Other ways to find leaflets

### ISSUE THREAD

**Issue by lilyminium** [MDAnalysis/mdanalysis#2843]
## Is your feature request related to a problem? ##

Looking at the current LeafletFinder algorithm, it seems that the cutoff is very important in building the graph, as every node is connected providing its distance is lower than the cutoff. The cutoff must therefore be small enough to not include lipids in the other leaflet, but large enough to account for potentially bulky tail groups and lipids in the middle of flip-flopping. 

> 1. build a graph of all phosphate distances < cutoff
> 2. identify the largest connected subgraphs
> 3. analyse first and second largest graph, which correspond to the leaflets

If you are identifying the leaflets on every frame of a trajectory where the membrane is changing thickness and lipids are flip-flopping, a single cutoff may not cut it. An ``optimize_cutoff`` function is provided to help out, but it is self-admittedly slow.

## Describe the solution you'd like ##

* use whichever method I like
* have more methods pre-defined, e.g. spectral clustering, which removes a need to think much about the cutoff
* but have them flexible and accessible outside LeafletFinder

**Comment by orbeckst** [comment]
Given that this specialized functionality exists in the [MDAKit lipyds](https://mdakits.mdanalysis.org/lipyds.html#lipyds) (see https://github.com/MDAnalysis/mdanalysis/pull/2844#issuecomment-834811704 ) we can work towards deprecating and removing the original leafletfinder.

**Comment by orbeckst** [comment]
I opened #4306 so I will close this one.
