### ISSUE TITLE
Cython directive 'language_level' not set

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/mdanalysis#2853]
## Expected behavior ##

With Python 3 only, our Cython code can also become Python 3 only and does not need Python 2 compatibility anymore.

https://cython.readthedocs.io/en/latest/src/userguide/source_files_and_compilation.html#compiler-directives says 

> **language_level (2/3/3str)**
>  
>  Globally set the Python language level to be used for module compilation. Default is compatibility with Python 2. To enable Python 3 source code semantics, set this to 3 (or 3str) at the start of a module or pass the “-3” or “–3str” command line options to the compiler. The 3str option enables Python 3 semantics but does not change the str type and unprefixed string literals to unicode when the compiled code runs in Python 2.x. Note that cimported files inherit this setting from the module being compiled, unless they explicitly set their own language level. Included source files always inherit this setting.

## Actual behavior ##

We get warnings like the following
```
/home/travis/miniconda/envs/test/lib/python3.7/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /home/travis/build/MDAnalysis/mdanalysis/package/MDAnalysis/analysis/encore/clustering/affinityprop.pyx
```

## Fix?

Might be as simple as
```python
compiler_directives={"language_level": "3"}
```
in setup.py (gleaned from https://github.com/Toblerity/Fiona/pull/677/files )

## Code to reproduce the behavior ##

Build with `python setup.py build`.

Or see https://travis-ci.com/github/MDAnalysis/mdanalysis/jobs/361617958 (random CI log)

## Current version of MDAnalysis ##

develop branch

**Comment by IAlibay** [comment]
Just testing this one out locally, there's a couple of implicit imports that need fixing, but it looks like adding language_level will just work.
