### ISSUE TITLE
Use both available cores on Travis CI

### ISSUE THREAD

**Issue by IAlibay** [MDAnalysis/mdanalysis#2862]
## Is your feature request related to a problem? ##

Currently Travis runs a lot slower than azure pipelines, part of the issue here might be the underlying hardware used, but in part it might be because azure pipelines runs using 2 cores vs 1 core on Travis: https://github.com/MDAnalysis/mdanalysis/blob/2e6b9608bfdbbf02133d5d1f0cd29db0cd43473b/azure-pipelines.yml#L83

## Describe the solution you'd like ##

Use pytest-xdist to bump up core usage.

## Describe alternatives you've considered ##

Carry on as normal.

## Additional context ##

Currently testing this in #2861

**Comment by orbeckst** [comment]
I _think_ we used to do `-n 2` but ran into instability issues and weird failures. Maybe @richardjgowers @kain88-de remember? By all means, see if it works better now.

**Comment by orbeckst** [comment]
And yes, then I don't know why it works just fine on Azure...

**Comment by tylerjereddy** [comment]
May depend to some extent on how many "real cores" you get, etc. Looks like it is 2 now on Travis though. Do have to be cautious with tests that are verifying warnings--I believe warnings capture is not thread-safe by default, though it seems "ok" on Azure.

Avoiding the `conda`/`astropy-helpers` stuff under the hood may also help Azure if you're looking at the overall job time--not sure if you've looked at the breakdown by "stage" on Travis.

**Comment by IAlibay** [comment]
We no longer use Travis so I'm closing. We should eventually review our usage of how thread indepdent our tests are, but that's no longer a priority (the main hinderance to the tests is actually running coverage [I think it does some kind of weird thread interruption stuff]).
