### ISSUE TITLE
Update seaborn.apionly to seaborn

### ISSUE THREAD

**Issue by xy127** [MDAnalysis/mdanalysis#2864]
Hello,
I have the following error message after I run pytest --disable-pytest-warnings --pyargs MDAnalysisTests. I have tried conda install seaborn and pip install seaborn, and it showed that packages already installed or requirements already satisfied. I wonder what should I do. 

___________________________________________________________________ ERROR at setup of TestPSAnalysis.test_dendrogram_produced_annotated ____________________________________________________________________

self = <MDAnalysis.analysis.psa.PSAnalysis object at 0x7f4540a52c50>, filename = 'annotated.png', linkage = 'ward', count_sort = False, distance_sort = False, figsize = 8, annot_size = 6.5

    def plot_annotated_heatmap(self, filename=None, linkage='ward',             \
                               count_sort=False, distance_sort=False,           \
                               figsize=8, annot_size=6.5):
        """Plot a clustered distance matrix.
    
        Uses method `linkage` and plots annotated distances in the matrix. Rows
        (and columns) are identified using the list of strings specified by
        :attr:`PSAnalysis.labels`.
    
        If `filename` is supplied then the figure is also written to file (the
        suffix determines the file type, e.g. pdf, png, eps, ...). All other
        keyword arguments are passed on to :func:`matplotlib.pyplot.imshow`.
    
        Parameters
        ----------
        filename : str
             save figure to *filename* [``None``]
        linkage : str
             name of linkage criterion for clustering [``'ward'``]
        count_sort : bool
             see :func:`scipy.cluster.hierarchy.dendrogram` [``False``]
        distance_sort : bool
             see :func:`scipy.cluster.hierarchy.dendrogram` [``False``]
        figsize : float
             set the vertical size of plot in inches [``4.5``]
        annot_size : float
             font size of annotation labels on heat map [``6.5``]
    
        Returns
        -------
        Z
          `Z` from :meth:`cluster`
        dgram
          `dgram` from :meth:`cluster`
        dist_matrix_clus
          clustered distance matrix (reordered)
    
    
        Note
        ----
        This function requires the seaborn_ package, which can be installed
        with `pip install seaborn` or `conda install seaborn`.
    
        .. _seaborn: https://seaborn.pydata.org/
    
        """
        from matplotlib.pyplot import figure, colorbar, cm, savefig, clf
    
        try:
>           import seaborn.apionly as sns
E           ModuleNotFoundError: No module named 'seaborn.apionly'

../anaconda3/lib/python3.7/site-packages/MDAnalysis/analysis/psa.py:1866: ModuleNotFoundError

During handling of the above exception, another exception occurred:

self = <MDAnalysisTests.analysis.test_psa.TestPSAnalysis object at 0x7f451f2d1410>, psa = <MDAnalysis.analysis.psa.PSAnalysis object at 0x7f4540a52c50>
tmpdir = local('/tmp/pytest-of-yuxiang/pytest-1/test_dendrogram_produced_annot0')

    @pytest.fixture()
    def plot_annotated_heatmap(self, psa, tmpdir):
        pytest.importorskip('seaborn')
        psa.run(metric='hausdorff')
        with tmpdir.as_cwd():
>           results = psa.plot_annotated_heatmap(filename="annotated.png")

../anaconda3/lib/python3.7/site-packages/MDAnalysisTests/analysis/test_psa.py:89: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <MDAnalysis.analysis.psa.PSAnalysis object at 0x7f4540a52c50>, filename = 'annotated.png', linkage = 'ward', count_sort = False, distance_sort = False, figsize = 8, annot_size = 6.5

    def plot_annotated_heatmap(self, filename=None, linkage='ward',             \
                               count_sort=False, distance_sort=False,           \
                               figsize=8, annot_size=6.5):
        """Plot a clustered distance matrix.
    
        Uses method `linkage` and plots annotated distances in the matrix. Rows
        (and columns) are identified using the list of strings specified by
        :attr:`PSAnalysis.labels`.
    
        If `filename` is supplied then the figure is also written to file (the
        suffix determines the file type, e.g. pdf, png, eps, ...). All other
        keyword arguments are passed on to :func:`matplotlib.pyplot.imshow`.
    
        Parameters
        ----------
        filename : str
             save figure to *filename* [``None``]
        linkage : str
             name of linkage criterion for clustering [``'ward'``]
        count_sort : bool
             see :func:`scipy.cluster.hierarchy.dendrogram` [``False``]
        distance_sort : bool
             see :func:`scipy.cluster.hierarchy.dendrogram` [``False``]
        figsize : float
             set the vertical size of plot in inches [``4.5``]
        annot_size : float
             font size of annotation labels on heat map [``6.5``]
    
        Returns
        -------
        Z
          `Z` from :meth:`cluster`
        dgram
          `dgram` from :meth:`cluster`
        dist_matrix_clus
          clustered distance matrix (reordered)
    
    
        Note
        ----
        This function requires the seaborn_ package, which can be installed
        with `pip install seaborn` or `conda install seaborn`.
    
        .. _seaborn: https://seaborn.pydata.org/
    
        """
        from matplotlib.pyplot import figure, colorbar, cm, savefig, clf
    
        try:
            import seaborn.apionly as sns
        except ImportError:
            raise ImportError(
                """ERROR --- The seaborn package cannot be found!
    
                The seaborn API could not be imported. Please install it first.
                You can try installing with pip directly from the
                internet:
    
                  pip install seaborn
    
                Alternatively, download the package from
    
                  http://pypi.python.org/pypi/seaborn/
    
                and install in the usual manner.
>               """
            )
E           ImportError: ERROR --- The seaborn package cannot be found!
E           
E                           The seaborn API could not be imported. Please install it first.
E                           You can try installing with pip directly from the
E                           internet:
E           
E                             pip install seaborn
E           
E                           Alternatively, download the package from
E           
E                             http://pypi.python.org/pypi/seaborn/
E           
E                           and install in the usual manner.

../anaconda3/lib/python3.7/site-packages/MDAnalysis/analysis/psa.py:1882: ImportError
_______________________________________________________________________ ERROR at setup of TestPSAnalysis.test_plot_nearest_neighbors _______________________________________________________________________

self = <MDAnalysis.analysis.psa.PSAnalysis object at 0x7f4547d1a990>, filename = 'nn.png', idx = 0, labels = ('Path 1', 'Path 2'), figsize = 4.5, multiplot = False, aspect_ratio = 1.75, labelsize = 12

    def plot_nearest_neighbors(self, filename=None, idx=0,                      \
                               labels=('Path 1', 'Path 2'), figsize=4.5,        \
                               multiplot=False, aspect_ratio=1.75,              \
                               labelsize=12):
        """Plot nearest neighbor distances as a function of normalized frame
        number.
    
        The frame number is mapped to the interval *[0, 1]*.
    
        If `filename` is supplied then the figure is also written to file (the
        suffix determines the file type, e.g. pdf, png, eps, ...). All other
        keyword arguments are passed on to :func:`matplotlib.pyplot.imshow`.
    
        Parameters
        ----------
        filename : str
             save figure to *filename* [``None``]
        idx : int
             index of path (pair) comparison to plot [``0``]
        labels : (str, str)
             pair of names to label nearest neighbor distance
             curves [``('Path 1', 'Path 2')``]
        figsize : float
             set the vertical size of plot in inches [``4.5``]
        multiplot : bool
             set to ``True`` to enable plotting multiple nearest
             neighbor distances on the same figure [``False``]
        aspect_ratio : float
             set the ratio of width to height of the plot [``1.75``]
        labelsize : float
             set the font size for colorbar labels; font size for path labels on
             dendrogram default to 3 points smaller [``12``]
    
        Returns
        -------
        ax : axes
    
        Note
        ----
        This function requires the seaborn_ package, which can be installed
        with `pip install seaborn` or `conda install seaborn`.
    
        .. _seaborn: https://seaborn.pydata.org/
    
        """
        from matplotlib.pyplot import figure, savefig, tight_layout, clf, show
        try:
>           import seaborn.apionly as sns
E           ModuleNotFoundError: No module named 'seaborn.apionly'

../anaconda3/lib/python3.7/site-packages/MDAnalysis/analysis/psa.py:1975: ModuleNotFoundError

During handling of the above exception, another exception occurred:

self = <MDAnalysisTests.analysis.test_psa.TestPSAnalysis object at 0x7f4540a79450>, psa = <MDAnalysis.analysis.psa.PSAnalysis object at 0x7f4547d1a990>
tmpdir = local('/tmp/pytest-of-yuxiang/pytest-1/test_plot_nearest_neighbors0')

    @pytest.fixture()
    def plot_nearest_neighbors(self, psa, tmpdir):
        pytest.importorskip('seaborn')
        psa.run(metric='hausdorff')
        psa.run_pairs_analysis(neighbors=True)
        with tmpdir.as_cwd():
>           results = psa.plot_nearest_neighbors(filename="nn.png")

../anaconda3/lib/python3.7/site-packages/MDAnalysisTests/analysis/test_psa.py:98: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <MDAnalysis.analysis.psa.PSAnalysis object at 0x7f4547d1a990>, filename = 'nn.png', idx = 0, labels = ('Path 1', 'Path 2'), figsize = 4.5, multiplot = False, aspect_ratio = 1.75, labelsize = 12

    def plot_nearest_neighbors(self, filename=None, idx=0,                      \
                               labels=('Path 1', 'Path 2'), figsize=4.5,        \
                               multiplot=False, aspect_ratio=1.75,              \
                               labelsize=12):
        """Plot nearest neighbor distances as a function of normalized frame
        number.
    
        The frame number is mapped to the interval *[0, 1]*.
    
        If `filename` is supplied then the figure is also written to file (the
        suffix determines the file type, e.g. pdf, png, eps, ...). All other
        keyword arguments are passed on to :func:`matplotlib.pyplot.imshow`.
    
        Parameters
        ----------
        filename : str
             save figure to *filename* [``None``]
        idx : int
             index of path (pair) comparison to plot [``0``]
        labels : (str, str)
             pair of names to label nearest neighbor distance
             curves [``('Path 1', 'Path 2')``]
        figsize : float
             set the vertical size of plot in inches [``4.5``]
        multiplot : bool
             set to ``True`` to enable plotting multiple nearest
             neighbor distances on the same figure [``False``]
        aspect_ratio : float
             set the ratio of width to height of the plot [``1.75``]
        labelsize : float
             set the font size for colorbar labels; font size for path labels on
             dendrogram default to 3 points smaller [``12``]
    
        Returns
        -------
        ax : axes
    
        Note
        ----
        This function requires the seaborn_ package, which can be installed
        with `pip install seaborn` or `conda install seaborn`.
    
        .. _seaborn: https://seaborn.pydata.org/
    
        """
        from matplotlib.pyplot import figure, savefig, tight_layout, clf, show
        try:
            import seaborn.apionly as sns
        except ImportError:
            raise ImportError(
                """ERROR --- The seaborn package cannot be found!
    
                The seaborn API could not be imported. Please install it first.
                You can try installing with pip directly from the
                internet:
    
                  pip install seaborn
    
                Alternatively, download the package from
    
                  http://pypi.python.org/pypi/seaborn/
    
                and install in the usual manner.
>               """
            )
E           ImportError: ERROR --- The seaborn package cannot be found!
E           
E                           The seaborn API could not be imported. Please install it first.
E                           You can try installing with pip directly from the
E                           internet:
E           
E                             pip install seaborn
E           
E                           Alternatively, download the package from
E           
E                             http://pypi.python.org/pypi/seaborn/
E           
E                           and install in the usual manner.

../anaconda3/lib/python3.7/site-packages/MDAnalysis/analysis/psa.py:1991: ImportError
======================================================= 15416 passed, 67 skipped, 2 xfailed, 2 xpassed, 9147 warnings, 2 errors in 427.36s (0:07:07) ====================================================

**Comment by lilyminium** [comment]
`seaborn.apionly` is from an older version of seaborn; we should update that to `import seaborn as sns`.

In the meantime, try `conda install "seaborn>=0.7.0,<0.9"` -- does that fix it?

**Comment by xy127** [comment]
Hello,
I changed import seaborn.apionly as sns to import seaborn as sns in psa.py, and error is gone.
Thanks.

**Comment by lilyminium** [comment]
Closed by #2556. This is already in 1.0.0 @orbeckst
