### ISSUE TITLE
Adding H5MDWriter to H5MD.py

### ISSUE THREAD

**Issue by edisj** [MDAnalysis/mdanalysis#2866]
## Is your feature request related to a problem? ##

Currently in my pull request ([PR#2787](https://github.com/MDAnalysis/mdanalysis/pull/2787)), we've only implemented an H5MD file reader. I'd like to implement a writer as well using [H5PY's](http://docs.h5py.org/en/stable/index.html) libraries for writing HDF5 files. [H5MD](https://nongnu.org/h5md/h5md.html) files follow specific rules for the structure of groups and datasets. There's already a package, [pyh5md](https://github.com/pdebuyl/pyh5md), that can write H5MD files nicely, but it's no longer being maintained by its author, so we've decided to stick to H5PY for writing the files.

## Describe the solution you'd like ##

We've been given permission from Pierre de Buyl, the author of pyh5md, to borrow code from his library and implement it into H5MDWriter. I've already begun a draft that's mostly working (uploaded to my github [here](https://github.com/Becksteinlab/h5md_examples/blob/master/testing/h5mdwriter/H5MD.py#L522-L966)), where I modeled it after `NCDFWriter` and added/tweaked code from pyh5md. I would like to open a pull request as soon as the reader is merged.

## Describe alternatives you've considered ##

We could write the writer from scratch without using pyh5md, but that sounds a lot harder.

## Additional context ##

[H5MD format](https://nongnu.org/h5md/h5md.html)
[NCDFWriter](https://github.com/MDAnalysis/mdanalysis/blob/develop/package/MDAnalysis/coordinates/TRJ.py#L736-L1077) - the writer I used as a template to write mine
[pyh5md code](https://github.com/pdebuyl/pyh5md/blob/master/pyh5md/h5md_module.py) - used `TimeElement` class, `create_box()`, `default_chunks()`, and `element()`

**Comment by orbeckst** [comment]
- make a PR (or does it require #2787 to be merged first?)
- When we use pyh5md code then we 
   - add it as separate commit and set the author to @pdebuyl `--author="Pierre de Buyl <...>`
   - add pyh5md license information to the LICENSE file

**Comment by edisj** [comment]
It doesn't have to be merged first, I guess. I just thought it would be awkward to keep pushing commits to both PRs from the same file. Is there a more convenient way to handling that than, say, deleting `H5MDWriter`, pushing to reader PR, then deleting `H5MDReader` and pushing to the writer PR?

**Comment by orbeckst** [comment]
Yes, indeed, branches!

**Comment by orbeckst** [comment]
FYI: discussion on empyty boxes #1738

**Comment by pdebuyl** [comment]
H5MD allows "boundary" (a length D vector attribute) to be none.

https://nongnu.org/h5md/h5md.html#simulation-box

**Comment by orbeckst** [comment]
@edisj is your writer PR out of draft stage?

**Comment by edisj** [comment]
> @edisj is your writer PR out of draft stage?

yes - I've just pushed a working cleaned up version to the pull request #2869
