### ISSUE TITLE
consolidate modules under MDAnalysis.lib

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/mdanalysis#287]
Since @richardjgowers introduced `MDAnalysis.lib` recently, we should use this to clean up our name space a little bit. For instance, I propose:

* `KDTree` --> `lib.KDTree`
* `core.transformations` --> `lib.transformations`
* `core.util` --> `lib.util`; util could be split into file and string utility functions and mathematical functions.
* `core.log` --> `lib.log`

Basically, anything that can stand on its own without importing `core`, `coordinates`, `topology`, `selections` is a good candidate for `lib`.

Making it all work again after breaking it all will be a bit of work, heavily rely on the unit tests, and also require going through the docs to catch broken links, so a fair question is, if this is worthwhile?

**Comment by richardjgowers** [comment]
There's a lot of circular imports which mean you have to import in modules, so having lib be dependency free would be great for that.

Also if #286 goes ahead, moving stuff from analysis that wants coverage into lib would be a good idea.

it'll be annoying to do, but I think it'd be good to spring clean the namespace

**Comment by orbeckst** [comment]
Good point about moving some analysis stuff over, e.g. some of the RMSD calculations could go there, but my impression is that a lot of the analysis code needs core modules, doesn't it?

**Comment by richardjgowers** [comment]
It depends if the dependencies in core also get moved over! 

So the line is, general tools into lib, more specific analysis into analysis? And lib is always dependency free internally

**Comment by orbeckst** [comment]
> So the line is, general tools into lib, more specific analysis into analysis? And lib is always dependency free internally.

Yes, that's a good guide line. Let's go with it.

**Comment by richardjgowers** [comment]
So something I'm not sure on, `.core.distances` and `core.parallel.distances`.  These should probably move to lib too?  I think then the cython wrappers are `_distances` and the user friendly front ends are `distances`?  Maybe `lib._cython.distances` for the thin wrappers? (And `lib._openmp.distances`)

So more methodically, current contents are:
 * AtomGroup -> stays
 * distances -> maybe to lib?
 * log -> to lib
 * parallel.distances -> same fate as distances above
 * Selection -> stays
 * Timeseries -> maybe to analysis?  Has dependencies so can't go to lib
 * transformations -> to lib
 * units -> dependency free, move to lib? move to top namespace? `MDAnalysis.units`?
 * util -> to lib

**Comment by orbeckst** [comment]
On 25 May, 2015, at 12:19, Richard Gowers wrote:

> So something I'm not sure on, .core.distances and core.parallel.distances. These should probably move to lib too?

Yes, conceptually they belong there.

> I think then the cython wrappers are _distances and the user friendly front ends are distances?
> Maybe lib._cython.distances for the thin wrappers? (And lib._openmp.distances)

Shouldn't lib._cython.distances be lib._serial.distances because the openmp would also be written in cython?

You could also keep using the underscore for the compiled modules, eg  lib._serial._distances 

I agree with the following unless otherwise noted:

> 
> So more methodically, current contents are:
> 
> 	� AtomGroup -> stays
> 	� distances -> maybe to lib?
> 	� log -> to lib
> 	� parallel.distances -> same fate as distances above
> 	� Selection -> stays
> 	� Timeseries -> maybe to analysis? Has dependencies so can't go to lib

Timeseries is a bit weird but I think it has to stay. It could also go under coordinates... or if we ever get around to implement more of it, get its own toplevel name space. For right now, leave it in core.

> 	� transformations -> to lib
> 	� units -> dependency free, move to lib? move to top namespace? MDAnalysis.units?

Makes sense at the top because everyone else is using it.

There's also an awful lot of code in core/__init__.py (the flags registry, which are really "traits" as I learned later). That could become its own core module that is imported appropriately in __init__.py � or perhaps more appropriate, make it MDAnalysis.config at the top level.

> 	� util -> to lib

Moving all this stuff will break lots of scripts. We probably need to plan for a transition period where we fake the old relationships with "from  imports" so that people can still run their old code as they used to. I would fence the imports with an if clause and a flag like "flags['compatibility_imports'] == True"  (which we will set as the default for the near future; we can the main test suite with False):

```
import MDAnalysis.config
if MDAnalysis.config.flags['compatibility_imports']:
   warnings("This will go away in 1.0", DeprecationWarning)
   from MDAnalysis.config import flags
   from MDAnalysis import units
   ...
```





--
Oliver Beckstein * orbeckst@gmx.net
skype: orbeckst  * orbeckst@gmail.com

**Comment by richardjgowers** [comment]
I'd rather not use a flag, maybe just keep a stub where the moved modules are, which raises a Deprecation warning then imports the new location of the module.. so `core.transformations` becomes

``` python
raise DeprecationWarning

from ..lib.transformations import (list of things)
```

Then after a while we can just delete the stubs?

**Comment by orbeckst** [comment]
That works, too. (Just use warnings.warn() and also do a logger.warn() message).

**Comment by orbeckst** [comment]
@richardjgowers would you be willing to heap #287 onto your plate?

**Comment by orbeckst** [comment]
@richardjgowers – un-assign yourself if you get fed up with moving files around – but know that you are performing a valuable service ;-)

**Comment by richardjgowers** [comment]
With `core.util` (soon to be `lib.util`), you mentioned splitting out the mathematics and the file stuff which is a good idea.  Would it make sense to make something like `lib.io` which has all our generic file handling things in?  This would then feed into both `coordinates` and `topology`

**Comment by orbeckst** [comment]
On 20 Jun, 2015, at 06:42, Richard Gowers wrote:

> With core.util (soon to be lib.util), you mentioned splitting out the mathematics and the file stuff which is a good idea. Would it make sense to make something like lib.io which has all our generic file handling things in? This would then feed into both coordinates and topology

Something like lib.io would be good, just not sure about the name "io", which is already claimed by a standard lib module. I'd rather avoid the potential conflicts when someone does "from .lib import io". Maybe you can come up with a distinct name: inout, fileio, mdaio, ... (anything better...)

Similar, "lib.math" would run in the same problem, perhaps "lib.geom"  or "lib.geometry" ... or something else entirely?

**Comment by orbeckst** [comment]
Are you done with the big spring/summer cleaning?

Kudos!!!!

Btw, it totally slipped my mind that `units` is already a name clash.... but at least [units](https://pypi.python.org/pypi/units/) is not in the standard library.

**Comment by richardjgowers** [comment]
I still need to move core.distances to lib.distances but that's it.

With name clashes, what numpy seems to do is prefix stuff with 'npy' (`numpy.lib.npyio`), so we could do the same with mda (`mdaio`, `mdaunits`)

**Comment by orbeckst** [comment]
On 29 Jun, 2015, at 03:43, Richard Gowers wrote:

> With name clashes, what numpy seems to do is prefix stuff with 'npy' (numpy.lib.npyio), so we could do the same with mda (mdaio, mdaunits)

It's not very pretty but I can't think of a better way so I suggest we do that for anything that conflicts with the standard library.

**Comment by richardjgowers** [comment]
Ok so once that PR gets merged this is finished, then next time the docs get rebuilt I need to check I've not mangled them before we next release.
