### ISSUE TITLE
Allow select_atoms to select chain

### ISSUE THREAD

**Issue by xiki-tempula** [MDAnalysis/mdanalysis#2875]
## Is your feature request related to a problem? ##
The PDB standard defined location 22 as chain ID.
The charmm standard defined the segment id being a 4 letter ID starting at 73.

Currently, mda assumes that the segment id is chain id when segment id is in the absence and will ignore the chain id when the segment id is given.

Ideally one could select chain based on chainid. 

`u.select_atoms('chainid A')` or `u.select_atoms('chain A')` if we do it in the pymol way

Related to #2874

**Comment by mieczyslaw** [comment]
It seems to be not so simple when there is no segID to accept column 22 -  if one chain has chainID set in column 22, and another has segID set, MDA segid list will contain only the chain set as segid, it won't add chains with chainID set in column 22. Maybe a bit unusual mix of positions, but good to repair this as well (or raise an exception that the position need to be consistent).

**Comment by orbeckst** [comment]
## Chain vs Segment
### chain
A **chain** is a polymer term, specifically, from PDB files ([ATOM chainId](https://www.wwpdb.org/documentation/file-format-content/format33/sect9.html#ATOM) and see [TER](https://www.wwpdb.org/documentation/file-format-content/format33/sect9.html#TER) and [SEQRES](https://www.wwpdb.org/documentation/file-format-content/format33/sect3.html#SEQRES) for clarification) and originally means one polymer, as expressed for SEQURES (my emphasis)
> SEQRES records contain a listing of the consecutive chemical components **covalently linked in a linear fashion to form a polymer.** The chemical components included in this listing may be standard or modified amino acid and nucleic acid residues. It may also include other residues that are linked to the standard backbone in the polymer. Chemical components or groups covalently linked to side-chains (in peptides) or sugars and/or bases (in nucleic acid polymers) will not be listed here. 

Each SEQRES entry has a corresponding **chainId** in ATOM records and should be terminated with a TER (although in the wild this is often omitted).

### Segment
A **segment** originates (as far as I know) from PSF files and is generally used to mark up a collection of molecules. This is often used to label single proteins or all lipids or all waters or the whole solvent. The [charmmtutorial.org: CHARMM:The Basics: Molecule Metadata](https://www.charmmtutorial.org/index.php/CHARMM:The_Basics#Molecule_Metadata) treats "chain" and "segment" as equivalent
> Residues are further grouped into chains, or segments, which represent major functional units of the protein. 

but then shows an example where all water molecules are in a *segment* with SEGID W.

In practice, *segments* are used as a convenient container for collections of "residues", where residues can either be building blocks of a polymer or individual molecules such as lipids or waters or bare ions.

## selection keyword
A quick survey indicates that **chain** is probably a good 

### VMD
[VMD's selections](https://www.ks.uiuc.edu/Research/vmd/current/ug/node89.html) have the [keywords](https://www.ks.uiuc.edu/Research/vmd/current/ug/node90.html)
* _chain_ (str): the one-character chain identifier
* _fragment_ (num): a set of connected residues 
* _segname_ (str): segment name

### CHARMM
MDAnalysis selections were modelled after CHARMM so unsurprisingly (see [charmmtutorial.org: Atom Selection](https://www.charmmtutorial.org/index.php/Essential_CHARMM_Features#Atom_Selection) and [c42b1 select](https://www.charmm.org/charmm/documentation/by-version/c42b1/params/doc/select/)
* _segid_ (num): segment with numerical segment ID

### PyMOL
See [pymolwiki.org: Selection_Algebra](https://pymolwiki.org/index.php/Selection_Algebra)

* _chain_ (char): Chain identifier
* _segi_ (char): Segment identifier (label_asym_id from mmCIF) 
* _model_ (str): Atoms from object "1ubq"  (e.g., "model 1ubq")

Related operators
* _bysegi_ (expr): Expands expr to complete segments
* _bychain_ (expr): Expands expr to complete chains 
* _bymolecule_ (expr): Expands expr to complete molecules (connected with bonds) 
* _byfragment_ (expr): ?

### mdtraj
mdtraj does not seem to store chains/segids, at least based on [mdtraj: Atom Selection Reference](http://mdtraj.org/1.9.3/atom_selection.html#reference) it only lets users select the internal chainid :
* _chainid_ (num): Chain index (0-based)

Feel free to correct me on any of the above.
