### ISSUE TITLE
Fail to pickle last frame of DCD, XDR files

### ISSUE THREAD

**Issue by yuxuanzhuang** [MDAnalysis/mdanalysis#2878]
## Expected behavior ##

The trajectory can be pickled no matter which frame it is current in.

## Actual behavior ##

XDR and DCD readers cannot pickle the last frame.
Raising the EOFError

## Code to reproduce the behavior ##

```python
u = mda.Universe(GRO_MEMPROT, XTC_MEMPROT)
u.trajectory[4] #  last frame
pickle.loads(pickle.dumps(u.trajectory))
EOFError: Trying to seek over max number of frames
```

## Current version of MDAnalysis ##

- Which version are you using? (run `python -c "import MDAnalysis as mda; print(mda.__version__)"`) 2.0.0 dev
- Which version of Python (`python -V`)? 3.8
- Which operating system? Ubuntu 20

**Comment by orbeckst** [comment]
The two small changes can be backported.
- [ ]  package/MDAnalysis/lib/formats/libmdaxdr.pyx https://github.com/MDAnalysis/mdanalysis/pull/2723/files/fae47973849ba1a227985583df9c5215cc9f20ae#r462499182
- [ ] package/MDAnalysis/lib/formats/libdcd.pyx  https://github.com/MDAnalysis/mdanalysis/pull/2723/files/fae47973849ba1a227985583df9c5215cc9f20ae#r462499386
