### ISSUE TITLE
Atomnames methods should handle empty group

### ISSUE THREAD

**Issue by lilyminium** [MDAnalysis/mdanalysis#2879]
## Expected behavior ##

`u.residues[[]]._get_prev_residues_by_resid()` returns an empty residue group. Same for

* _get_next_residues_by_resid
* psi_selections
* omega_selections
* chi1_selections

## Actual behavior ##

IndexError due to not checking length first.

```python
>>> u.residues[[]].omega_selections()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/lily/pydev/mdanalysis/package/MDAnalysis/core/topologyattrs.py", line 862, in omega_selections
    nxtres = residues._get_next_residues_by_resid()
  File "/Users/lily/pydev/mdanalysis/package/MDAnalysis/core/topologyattrs.py", line 670, in _get_next_residues_by_resid
    u = residues[0].universe
  File "/Users/lily/pydev/mdanalysis/package/MDAnalysis/core/groups.py", line 527, in __getitem__
    return self.level.singular(self.ix[item], self.universe)
IndexError: index 0 is out of bounds for axis 0 with size 0
```

## Code to reproduce the behavior ##

``` python
import MDAnalysis as mda
from MDAnalysis.tests.datafiles import PSF, DCD,  GRO, PDB, TPR, XTC, TRR,  PRMncdf, NCDF

u = mda.Universe(PSF, DCD)
u.residues[[]].omega_selections()

```

## Current version of MDAnalysis ##

- Which version are you using? (run `python -c "import MDAnalysis as mda; print(mda.__version__)"`) develop 2.0.0-dev
- Which version of Python (`python -V`)? 3.7
- Which operating system? MacOS

## Update ##
This has been partially fixed by #3089. The error message for methods such as ``omega_selections()`` is now:

```python
>>> import MDAnalysis as mda
>>> from MDAnalysis.tests.datafiles import PSF, DCD
>>> u = mda.Universe(PSF, DCD)
>>> u.residues[[]].omega_selections()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "mdanalysis/package/MDAnalysis/core/topologyattrs.py", line 1082, in omega_selections
    for r in nxt]
TypeError: 'int' object is not iterable
```

**Comment by aditya-kamath** [comment]
Hi @lilyminium, I have been looking at this issue and a quick fix I figured was to simply add a try-catch in the atomnames methods and simply return the residues if there is an index error.  However, this seems to solve this for three of them but psi_selections and omega_selections are a bit more tricky. I reckon that another way is to compare the groups with empty groups in the beginning of the methods and return empty groups. Not sure which way is more efficient.

**Comment by IAlibay** [comment]
@aditya-kamath even a partial fix here for some of the methods failing here would be appreciated. Please do open a PR if you would like to.

**Comment by lilyminium** [comment]
Only partially fixed by #3089.

**Comment by kainszs** [comment]
How is the second PR handled? @yuxuanzhuang

**Comment by yuxuanzhuang** [comment]
Hello @SampurnaM, it looks like @kainszs has already started working on this issue. I noticed you have another pull request open for tqdm. Could you focus on that one instead?

**Comment by SampurnaM** [comment]
Yes, of course, my bad - I only noticed the previous work after starting the PR in this issue, and so found another issue to work on.
I will close my PR. Should I also delete the branch? @yuxuanzhuang 
@kainszs : I didn't mean to mess up your solutions, I should have noticed before submitting my PR - I am sorry.

**Comment by yuxuanzhuang** [comment]
> Yes, of course, my bad - I only noticed the previous work after starting the PR in this issue, and so found another issue to work on. I will close my PR. Should I also delete the branch? @yuxuanzhuang @kainszs : I didn't mean to mess up your solutions, I should have noticed before submitting my PR - I am sorry.

No worries :) As for the branch, since it's only present in your fork, you're free to either keep it or delete it.
