### ISSUE TITLE
HoomdXML parser won't read in mass and charges

### ISSUE THREAD

**Issue by CalCraven** [MDAnalysis/mdanalysis#2888]
## Using topology_format='XML' should properly read in charges and masses from a hoomdxml file for analysis such as radius of gyration. ##

universe = md.Universe(toppath,dcdpath,topology_format='XML')
masses = universe.atoms.masses
print(masses)
[0.0, 0.0, ... 0.0]

## Code to reproduce the behavior ##

``` python
import MDAnalysis as mda
from MDAnalysis.tests.datafiles import DCD, XML

u = mda.Universe(XML, DCD,topology_format = 'XML')

print(u.atoms.masses)

....
```

I've pinpointed the source of the error. In line 147 and 150 of HoomdXMLParser.py, the attributes you are looking for are named incorrectly. The following changes fixes the bug in a local version of mdanalysis. I can draft a PR if that sounds good to you, since I will be using this modified version for some work and should have it running properly.

```python
147 if not 'masses' in attrs:
147(new) if not 'mass' in attrs:

150 if not 'charges' in attrs:
150(new) if not 'charge' in attrs:
```

## Current version of MDAnalysis ##

- Which version are you using? (run `python -c "import MDAnalysis as mda; print(mda.__version__)"`)  version 1.0.0
- Which version of Python (`python -V`)? python 3.6
- Which operating system? Mac OS

**Comment by IAlibay** [comment]
> I've pinpointed the source of the error. In line 147 and 150 of HoomdXMLParser.py, the attributes you are looking for are named incorrectly. The following changes fixes the bug in a local version of mdanalysis. I can draft a PR if that sounds good to you, since I will be using this modified version for some work and should have it running properly.

Thanks for raising this issue @CalCraven, please do open a PR that would be awesome!
