### ISSUE TITLE
EinsteinMSD documentation: msd_per_particle attribute.

### ISSUE THREAD

**Issue by mdaviesNCL** [MDAnalysis/mdanalysis#2895]
## Expected behavior ##

EinsteinMSD documentation refers to the attribute msd_per_particle for accessing the numpy array containing individual msd curves. 

## Actual behavior ##

Actual code seems to use msds_by_particle as the attribute instead.

## Code to reproduce the behavior ##

``` python
import MDAnalysis as mda
from MDAnalysis.tests.datafiles import PSF, DCD,  GRO, PDB, TPR, XTC, TRR,  PRMncdf, NCDF
from MDAnalysis.analysis.msd import EinsteinMSD
u = mda.Universe(PSF, DCD)
msd = EinsteinMSD(u)
print(msd.msd_per_particle)
....

```

## Current version of MDAnalysis ##

- Which version are you using? (run `python -c "import MDAnalysis as mda; print(mda.__version__)"`) 2.0.0-dev0
- Which version of Python (`python -V`)? 3.7.0
- Which operating system?

**Comment by IAlibay** [comment]
Thanks for pointing this out @mdaviesNCL, I've opened a PR to fix the typo.
