### ISSUE TITLE
Erroneous examples for rotateby

### ISSUE THREAD

**Issue by RMeli** [MDAnalysis/mdanalysis#2901]
The examples in the documentation of `transforms.rotate.rotateby` are not up-to-date since they call `transformations.rotate` instead of `transforms.rotate.rotateby`. 

https://github.com/MDAnalysis/mdanalysis/blob/3ea6e430b2820fd9d367f800d036a9c3ee87721a/package/MDAnalysis/transformations/rotate.py#L41-L70

I'll provide a quick fix.

**Comment by orbeckst** [comment]
Thanks, @RMeli !
