### ISSUE TITLE
atoms.segments.resnames contains all Universe residues, not the selected ATOM record_types

### ISSUE THREAD

**Issue by mieczyslaw** [MDAnalysis/mdanalysis#2905]
I have a simple PDB file:
```
ATOM   2106  N   GLU C 168      78.235  52.282  86.579  1.00306.74           N
ATOM   2107  CA  GLU C 168      77.849  53.465  87.343  1.00310.29           C
ATOM   2108  C   GLU C 168      78.146  53.306  88.831  1.00321.74           C
ATOM   2109  O   GLU C 168      77.545  52.476  89.513  1.00326.61           O
TER    2122      GLU C 168
HETATM 2123  N   RN7 C 503      76.722  32.855  57.578  1.00172.21           N
HETATM 2124  C   RN7 C 503      75.401  34.671  58.648  1.00142.48           C
```

I'd like to select only ATOM record types and get the sequence, see the code below to reproduce the issue. 

`atoms.segments.resnames` contains the HETATM residue which is not selected.

Interestingly, `atoms.resnames` does not but this one gives one list item per atom, instead of sequence. 

How to get the sequence of only selected residues?

## Expected behavior ##
['GLU'] list should be returned

## Actual behavior ##
['GLU', 'RN7'] list is returned, it contains HETATM which shouldn't be there as `u.select_atoms("record_type ATOM")`
 was used to get atom group.

It looks like `atoms.segments.resnames` is still a view on the universe, even though inside AtomGroup selection, which is very confusing.

## Code to reproduce the behavior ##
```
from MDAnalysis import Universe

u = Universe("test.pdb")
atoms = u.select_atoms("record_type ATOM")
chains = atoms.segments.segids.tolist()
for i in range(len(chains)):
    resnames = atoms.segments.resnames[i].tolist()
    print(resnames)
```

## Current version of MDAnalysis ##
MDAnalysis 1.0.0, Python 3.8.3, Linux

**Comment by lilyminium** [comment]
Hi @mieczyslaw, that's because `atoms.segments.resnames` selects the residue names of *all* the residues in the segments (i.e. chains) that are in your selected AtomGroup. Your PDB file has them all in the one chain called "C" which should show up in your `atoms.segments.segids` as `["C"]`. Does `atoms.residues.resnames` get you what you're after?

**Comment by mieczyslaw** [comment]
> atoms.residues.resnames

Thanks @lilyminium for replying so quickly; yes, `atoms.residues.resnames` behaves better, but how to get the sequence by chain? E.g., let's add chain D:
 
```
ATOM   2106  N   GLU C 168      78.235  52.282  86.579  1.00306.74           N
ATOM   2107  CA  GLU C 168      77.849  53.465  87.343  1.00310.29           C
ATOM   2108  C   GLU C 168      78.146  53.306  88.831  1.00321.74           C
ATOM   2109  O   GLU C 168      77.545  52.476  89.513  1.00326.61           O
TER    2122      GLU C 168
HETATM 2123  N   RN7 C 503      76.722  32.855  57.578  1.00172.21           N
HETATM 2124  C   RN7 C 503      75.401  34.671  58.648  1.00142.48           C
TER
ATOM   2106  N   GLU D 168      78.235  52.282  86.579  1.00306.74           N
ATOM   2107  CA  GLU D 168      77.849  53.465  87.343  1.00310.29           C
ATOM   2108  C   GLU D 168      78.146  53.306  88.831  1.00321.74           C
ATOM   2109  O   GLU D 168      77.545  52.476  89.513  1.00326.61           O
TER    2122      GLU D 168

```

**Comment by orbeckst** [comment]
Tangentially: residues also have a [sequence()](https://docs.mdanalysis.org/1.0.0/documentation_pages/core/topologyattrs.html#MDAnalysis.core.topologyattrs.Resnames.sequence) method:
```python
>>> u.atoms.select_atoms("protein").residues.sequence()
SeqRecord(seq=Seq('MRIILLGAPGAGKGTQAQFIMEKYGIPQISTGDMLRAAVKSGSELGKQAKDIMD...ILG'), id='<unknown id>', name='<unknown name>', description='<unknown description>', dbxrefs=[])
```

**Comment by mieczyslaw** [comment]
> Tangentially: residues also have a [sequence()](https://docs.mdanalysis.org/1.0.0/documentation_pages/core/topologyattrs.html#MDAnalysis.core.topologyattrs.Resnames.sequence) method:
> 
> ```python
> >>> u.atoms.select_atoms("protein").residues.sequence()
> SeqRecord(seq=Seq('MRIILLGAPGAGKGTQAQFIMEKYGIPQISTGDMLRAAVKSGSELGKQAKDIMD...ILG'), id='<unknown id>', name='<unknown name>', description='<unknown description>', dbxrefs=[])
> ```

Thanks @orbeckst! So the way to get the sequence by chain would be to:
1. get the list of chains with `u.segments.segids.tolist()`
2. loop through the chains list and create a selection (record_type ATOM and segid s)
3. finally use .residues.sequence() or .residues.resnames()

**Comment by orbeckst** [comment]
Yes, pretty much, but you can streamline it by not extracting the chain IDs manually. I also don't know how to select HETATM so I am using a protein selection in the example:
```python
import MDAnalysis as mda
import io

pdb = io.StringIO("""
ATOM   2106  N   GLU C 168      78.235  52.282  86.579  1.00306.74           N
ATOM   2107  CA  GLU C 168      77.849  53.465  87.343  1.00310.29           C
ATOM   2108  C   GLU C 168      78.146  53.306  88.831  1.00321.74           C
ATOM   2109  O   GLU C 168      77.545  52.476  89.513  1.00326.61           O
TER    2122      GLU C 168
HETATM 2123  N   RN7 C 503      76.722  32.855  57.578  1.00172.21           N
HETATM 2124  C   RN7 C 503      75.401  34.671  58.648  1.00142.48           C
TER
ATOM   2106  N   GLU D 168      78.235  52.282  86.579  1.00306.74           N
ATOM   2107  CA  GLU D 168      77.849  53.465  87.343  1.00310.29           C
ATOM   2108  C   GLU D 168      78.146  53.306  88.831  1.00321.74           C
ATOM   2109  O   GLU D 168      77.545  52.476  89.513  1.00326.61           O
TER    2122      GLU D 168
""")
u = mda.Universe(pdb, format="PDB")

for seg in u.segments:
    p_seg = seg.atoms.select_atoms("protein")
    seq = p_seg.residues.sequence(name="chain_"+seg.segid)
    print(seq)
```
gives
```
ID: <unknown id>
Name: chain_C
Description: <unknown description>
Number of features: 0
Seq('E')
ID: <unknown id>
Name: chain_D
Description: <unknown description>
Number of features: 0
Seq('E')
```

**Comment by mieczyslaw** [comment]
Thanks! So the main rule to make it working correctly is to loop through segments and then select, rather than selecting and looping through segments (which counter-intuitively still return the view on the whole chain, as explained by @lilyminium).

BTW, another pretty useful selection: `record_type ATOM and not (name H* or name OXT)) or record_type HETATM` :)

**Comment by mieczyslaw** [comment]
Similarly, when using a selection mentioned above, `record_type ATOM and not (name H* or name OXT)`, if one wants to access atoms grouped by residues, one possibility would be to use `atoms.residues.names`. Surprisingly, this contains hydrogen atoms (H*), whereas `atoms.names` doesn't, but it isn't grouped by residue. I suppose the solution would be to loop through residue this time and call `select_atoms`.

**Comment by orbeckst** [comment]
https://userguide.mdanalysis.org/1.0.0/groups_of_atoms.html#groups-of-atoms explains the hierarchy: The logic is that segments contains residues, which contain atoms. Each atom can only be a member of one residue and reach residue can only be a member of one segment.

When you ask for `residues.atoms` then you get "all the atoms in the ResidueGroup". If you ask for `atomgroup.residues` then you get "all the residues that have atoms in `atomgroup`". In particular, `len(atomgroup) <= len(atomgroup.residues.atoms)` because if, for instance, `atomgroup = u.select_atoms("name CA")` then `atomgroup.residues.atoms` will be all atoms in the protein. The fact that you can easily move between levels of the hierarchy with the `g.atoms`, `g.residues`, `g.segments` attributes (where `g` is either `AtomGroup`, `ResidueGroup`, or `SegmentGroup`) turned out to be a very powerful way to navigate structures that also leads to pretty readable code. Just remember: if you want all atoms in the group then work with `.atoms`, if you want to work with all residues, use `.residues`, and for all segments, `.segments`.

If you start thinking about the segments/residues/atoms hierarchy in the way I outlined then it should be less surprising and hopefully clearer how to get what you want.

**Comment by mieczyslaw** [comment]
Thank you @orbeckst !

**Comment by orbeckst** [comment]
Did this answer all your questions or is there something that you think needs fixing/better documenting?

**Comment by mieczyslaw** [comment]
If you don't mind, I would be more than happy to have a go and update UserGuide page mentioned above to highlight the use cases we mentioned above and what the user shouldn't do.

**Comment by orbeckst** [comment]
Ok, good, then please open an issue for the user guide and reference this issue. Once I see that there’s a UG issue open I can close this one.

**Comment by mieczyslaw** [comment]
> Ok, good, then please open an issue for the user guide and reference this issue. Once I see that there’s a UG issue open I can close this one.
> […](#)
> On Aug 12, 2020, at 2:47 PM, Mieczyslaw Torchala ***@***.***> wrote: If you don't mind, I would be more than happy to have a go and update UserGuide page mentioned above to highlight the use cases we mentioned above and what the user shouldn't do.

Issue https://github.com/MDAnalysis/mdanalysis/issues/2909. This one can be closed @orbeckst. Thanks.

**Comment by lilyminium** [comment]
I should have mentioned this earlier but "split" can also do it, something like the below (untested):

```
>>> ags = u.select_atoms("record_type ATOM").split("segment")
>>> for ag in ags:
>>>     print(ag.segments.segids)
['C']
['D']
```
