### ISSUE TITLE
coordinates/PDB.py PDB 3.2 vs. 3.3 consistency

### ISSUE THREAD

**Issue by mieczyslaw** [MDAnalysis/mdanalysis#2906]
As suggested by @IAlibay, I am adding here a ticket on consistency issue in `package/MDAnalysis/coordinates/PDB.py`.

It mentions implementing a subset of 3.2 standard, but CRYST1 link points to 3.3. Is there anything stopping us from moving with all the links to 3.3? Is there anything there which is not compatible with 3.3? 

## Current version of MDAnalysis ##
MDAnalysis 1.0.0

**Comment by orbeckst** [comment]
I don't think that we do anything specific to 3.2 – that's just the slow churn of history. Updates are welcome, especially as 3.3 is the final standard, as far as I understand it.

**Comment by mieczyslaw** [comment]
done as a part of #2880 (as requested by @IAlibay)

**Comment by mieczyslaw** [comment]
@orbeckst, this can be closed as addressed in #2880
