### ISSUE TITLE
Update UserGuide groups_of_atoms.html with description of unexpected behaviour

### ISSUE THREAD

**Issue by mieczyslaw** [MDAnalysis/mdanalysis#2909]
## Is your feature request related to a problem? ##
As discussed in issue https://github.com/MDAnalysis/mdanalysis/issues/2905, when accessing AtomGroup `atoms` created by selection `record_type ATOM` for a PDB containing both ATOMs and HETATMs, looping through `atoms.segments.resnames` will return all residues in chains (including HETATM record types, the ones we didn't want).

Similarly, when using another selection, `record_type ATOM and not (name H* or name OXT)`, if one wants to access atoms grouped by residues, the first guess could be to use atoms.residues.names. Surprisingly, this contains hydrogen atoms (H*), whereas atoms.names doesn't, but it isn't grouped by residue. 

@lilyminium and @orbeckst explained the logic behind data views.

## Describe the solution you'd like ##
I'd like to add two examples above to `groups_of_atoms.html` showing the logic how to correctly access the data in the presented two use cases (getting residues and getting atoms from selected AtomGroup).

**Comment by orbeckst** [comment]
@mieczyslaw could you please raise the issue in the User Guide issue tracker itself https://github.com/MDAnalysis/UserGuide/issues ? Sorry, I wasn't clear about this when I asked for, I just forgot that it's not clear to everyone that the User Guide is a separate repository. Thank you!

**Comment by mieczyslaw** [comment]
Thanks @orbeckst , created https://github.com/MDAnalysis/UserGuide/issues/100, this one can be closed then.
