### ISSUE TITLE
make empty sphzone / cyzone selections consistent with 'around'

### ISSUE THREAD

**Issue by xiki-tempula** [MDAnalysis/mdanalysis#2915]
## Is your feature request related to a problem? ##
Since sphzone will do a center of geometry calculation first, if an empty atomgorup is passed to the sphzone, a not very useful error message will be given.

```
Traceback (most recent call last):
    water = u.select_atoms( 'resname SOL and sphzone 3 (resid 12 and name HE)')
  File "/Users/grte2001/GitHub/mdanalysis/package/MDAnalysis/core/universe.py", line 677, in select_atoms
    return self.atoms.select_atoms(*args, **kwargs)
  File "/Users/grte2001/GitHub/mdanalysis/package/MDAnalysis/core/groups.py", line 2863, in select_atoms
    selections[0].apply(self))
  File "/Users/grte2001/GitHub/mdanalysis/package/MDAnalysis/core/selection.py", line 136, in apply
    rsel = self.rsel.apply(group)
  File "/Users/grte2001/GitHub/mdanalysis/package/MDAnalysis/core/selection.py", line 168, in apply
    return func(self, group)
  File "/Users/grte2001/GitHub/mdanalysis/package/MDAnalysis/core/selection.py", line 333, in apply
    ref = sel.center_of_geometry().reshape(1, 3).astype(np.float32)
ValueError: cannot reshape array of size 0 into shape (1,3)
```

## Describe the solution you'd like ##
~An error message which says the selection is empty could be given.~

EDIT: Following the discussion below and on #3026 we want these selections to behave like `around`, i.e., just return an empty AtomGroup. — @orbeckst 

## Describe alternatives you've considered ##
Just return an empty atomgroup.

**Comment by IAlibay** [comment]
That's odd, I can't seem to reproduce this locally with:

```python
u = mda.Universe(GRO, XTC)
u.select_atoms('resname SOL and sphzone 3 (resid 12 and name HA)')
```

**Comment by xiki-tempula** [comment]
@IAlibay Sorry, I noticed that I have made an error and this is a different problem.

**Comment by IAlibay** [comment]
So the behaviour here is inconsistent between around & sphzone/cyzone. In the former if the selection is an empty atomgroup we just return an empty atomgroup:
https://github.com/MDAnalysis/mdanalysis/blob/23074c64f5de2795756c44eb16e488d4f1d253f0/package/MDAnalysis/core/selection.py#L276-L280
 whilst in the latter selections that check isn't being made.

My proposal here would be to align everything to `around`. IMHO it's a more commonly used selection keyword and the behaviour would more likely be the one that would be expected?

**Comment by orbeckst** [comment]
I agree with https://github.com/MDAnalysis/mdanalysis/issues/2915#issuecomment-676236983 - make `sphzone/cyzone` behave in the same way as `around` and return and empty AtomGroup.

**Comment by orbeckst** [comment]
Note that some more details are shown in the duplicate issue #3026.

**Comment by sulays** [comment]
Hi, I was going through the code and found out that many other selections are also not consistent with `around` and they don't return an empty `AtomGroup` (e.g `sphlayer`). Should I create a PR for changes in all such selections?

**Comment by xiki-tempula** [comment]
Hi @sulays Thanks for your interest. I think this is a very good idea. It might be good to raise these selections as issues (explain what you expect and what you got) and then make a PR against them.
