### ISSUE TITLE
Make Universe store its kwargs for better persistence support

### ISSUE THREAD

**Issue by dotsdl** [MDAnalysis/mdanalysis#292]
As discussed in Becksteinlab/MDSynthesis#25, it would be useful for a `Universe` to hold on to its init kwargs so that these can be used by (semi-) persistence schemes to regenerate universes from its inputs. This could be as simple as storing the kwargs with

``` python
self._kwargs = kwargs.copy()
```

in the `Universe` init.

**Comment by orbeckst** [comment]
There are some caveats, though: The topology and trajectory formats can also take classes as "format" and these can essentially be arbitrary code (as long as it conforms to the topology and trajectory API). Perhaps something to be aware of, or do some scrubbing of self._kwargs() or try to store it as an in-memory pickle using cStringIO.

**Comment by dotsdl** [comment]
Hmmm...that does complicate things. Not to make this specific to how [MDSynthesis](https://github.com/Becksteinlab/MDSynthesis) is handling the persistence problem, but would storing the kwargs address all cases in which the topology and trajectory(s) live physically in the filesystem? Meaning, for universes generated from files, will storing the kwargs be enough to generate the same universe again (excluding modifications post-init)? The streamio is great, but I don't see how it can be used within the MDSynthesis persistence model.

**Comment by orbeckst** [comment]
On 29 May, 2015, at 12:13, David Dotson wrote:

> The streamio is great, but I don't see how it can be used within the MDSynthesis persistence model.

Perhaps it can't but then you need to reject certain inputs right away.

**Comment by kain88-de** [comment]
This has been reversed due to the topology refactor. We need to fix it again. I noticed because mdsynthesis tests are failing

**Comment by kain88-de** [comment]
OK this is entirely in MDSynthesis because some tests expected that the public kwargs are readonly and that there is a private `_kwargs`
