### ISSUE TITLE
remove universe.as_Universe

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/mdanalysis#2920]
`universe.as_Universe` is not really needed
https://github.com/MDAnalysis/mdanalysis/blob/45e56e8314c278e3eb98ed7a6029b74e7435e8be/package/MDAnalysis/core/universe.py#L1327-L1328 and can be removed.

EDIT: @IAlibay found in PR #2922 that LeafletFinder is also affected and will not anymore accept a filename as input

- [ ] remove for 2.0.0
- [x] deprecate as_Universe in 1.0.1 (see PR #2798 )
- [x] deprecate filename argument for LeafletFinder in 1.0.1

**Comment by IAlibay** [comment]
I _think_ the only use case of as_Universe is LeafletFinder, which to be honest is strange behaviour for MDAnalysis as a whole. Unless there's any objections, I'd suggest just making LeafletFinder's `universe` argument accept solely Universes.

**Comment by orbeckst** [comment]
Thanks for looking into what is affected. I added a deprecation note to LeafletFinder to the backport.
