### ISSUE TITLE
Py3 TODO comments in core.Universe

### ISSUE THREAD

**Issue by IAlibay** [MDAnalysis/mdanalysis#2921]
Just having a look through core.Universe and I'm noticing there's a lot of comments tagged as "Py3 TODO"
e.g.
https://github.com/MDAnalysis/mdanalysis/blob/45e56e8314c278e3eb98ed7a6029b74e7435e8be/package/MDAnalysis/core/universe.py#L141-L142

It's unclear to me what are intended by these, but now that we are solely py3+ we should either implement them or remove the comments?

**Comment by richardjgowers** [comment]
It might be argument unpacking changes that are py3 specific. I think you previously couldn't have named kwargs after a variable length list of args.  I think when @lilyminium was reworking Universe creation she ran into this a bit if you want to find the PR

**Comment by IAlibay** [comment]
I see, this is related to #2322, I don't think there's another opened issue for this, so I'll add it to the 2.0 milestone.
