### ISSUE TITLE
Optimizing H5MDReader's use of dataset indexing and __getitem__()

### ISSUE THREAD

**Issue by edisj** [MDAnalysis/mdanalysis#2924]
## Is your feature request related to a problem? ##

Following some benchmarks we've done on `H5MDReader`'s serial performance vs other file formats, we found that it lagged behind. Here's a graph:
<img src="https://user-images.githubusercontent.com/59893899/91628806-546d0680-e978-11ea-9056-009dc810134f.png" height="300">

A line profiler elucidated that the largest contributor to H5MD's slow I/O speeds was the `__getitem__()` method in dataset.py:
![h5mdprofile](https://user-images.githubusercontent.com/59893899/91628839-7feff100-e978-11ea-93fd-6fdb3933a318.PNG)

which makes things a little tricky because `H5MDReader` indexes a lot of datasets. Every time a frame is called, the positions, velocity, forces, box dimensions, and any datasets in the 'observables' group are indexed, which will call `__getitem__()`

## Describe the solution you'd like ##

1. Trim down some of the superfluous indexing in `H5MDReader`
2. Maybe give the user a prompt to suggest not to load velocity and force data if they're not using it, which would save a lot of I/O time

## Describe alternatives you've considered ##

None for now, will update

## Additional context ##

Here's a link to the report from my REU where the results come from: https://figshare.com/articles/journal_contribution/REU_Report_pdf/12861215

**Comment by orbeckst** [comment]
Can you link to your report, too, please?

**Comment by orbeckst** [comment]
Isn't the graph at the top of this issue outdated in that you found out that the performance problem is really how the h5md trajectory is structured? Given these insights, does PR #3293 really _fix_ this issue or isn't it more fair to say that that PR is simply a performance _Enhancement_?

**Comment by edisj** [comment]
I suppose you're right in that it doesn't really _fix_ the issue, but rather shows that there wasn't really an issue to begin with in terms of H5MD serial performance vs other formats.

Would it be better to simply close this issue separately, then, instead of linking it with #3293?

**Comment by orbeckst** [comment]
Yes, makes sense.

How about you state in your closing comment why you're closing it, then modify the PR to not link to this issue anymore.

**Comment by orbeckst** [comment]
I am happy with your PR #3293 so all is left here for you to close the issue.

(We _like_ closing issues as it makes us look more effective ;-) )

**Comment by edisj** [comment]
This issue is being closed as it was discovered that the slower than average serial IO performance of `H5MDReader` was caused by the default chunk shape applied to the datasets by h5py. See #3293 for more details on our updated performance metrics of serial H5MDReader.
