### ISSUE TITLE
Allow selection with elements attribute

### ISSUE THREAD

**Issue by RMeli** [MDAnalysis/mdanalysis#2925]
The `elements` attribute has been added to multiple parsers (#2858, #2627, #2456). It would be helpful to be able to select atoms using such attribute.

I would like the following to work:
```
select_atoms("not elements H")
```
while currently it results in an error: `MDAnalysis.exceptions.SelectionError: Unknown selection token: 'elements'`.

**Comment by orbeckst** [comment]
Yes, definitely. Good idea. I assume this should use the same fast integer matching technique that was added for #2751 .

**Comment by orbeckst** [comment]
I'd say the keyword should be **element** (singular) and not plural, though.
