### ISSUE TITLE
disable nsgrid neighbor search

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/mdanalysis#2930]
## Expected behavior ##

neighbor search with capped_distance returns reliable and consistent results

## Actual behavior ##

It doesn't.

* #2919 
* #2229 
* #2345
* #2670

See https://github.com/MDAnalysis/mdanalysis/issues/2229#issuecomment-529910570 for detailed analysis of problems.

## Course of action
Disable nsgrid-based neighbor search until we have a stable solution. Use PBC-pkdtree instead.

## Impact
* slower distance-based searches and analysis (e.g. RDF)
* correct results in all cases

## Code to reproduce the behavior ##
See linked issues.

## Current version of MDAnalysis ##

- Which version are you using? (run `python -c "import MDAnalysis as mda; print(mda.__version__)"`) 1.0.x, 2.0.0-dev
- Which version of Python (`python -V`)? any
- Which operating system? any

**Comment by IAlibay** [comment]
I'm working on a quick fix for this given the discussion in #2768 

Do we want to solely remove nsgrid from 1.0.1 (i.e. only target `master`), or do we want to do so for `develop` too?

**Comment by lilyminium** [comment]
Closed in #3004.
