### ISSUE TITLE
Remove element guessing by default in ParmedParser

### ISSUE THREAD

**Issue by IAlibay** [MDAnalysis/mdanalysis#2933]
## Is your feature request related to a problem? ##
As previously discussed #2630, #2651, etc... we probably don't want to be guessing by default if we can avoid it, particularly for elements where guess_types/elements (synonymous) is particularly error prone.

The ParmEdParser currently guesses by default elements if the atomic number doesn't match anything in `Z2SYMB`.
https://github.com/MDAnalysis/mdanalysis/blob/b2b7bcbdf4e2fe4e221d5e67842c90cf317375e5/package/MDAnalysis/topology/ParmEdParser.py#L219-L223

## Describe the solution you'd like ##

Change the behaviour of the ParmeEdParser. If the element can't be found, then just assign the element as an empty string (as we do for the TOPParser). 

## Describe alternatives you've considered ##
Alternatively we could either: a) not assign elements if there's a bad element, or b) keep things as they are.

**Comment by lilyminium** [comment]
> assign the element as an empty string (as we do for the TOPParser).

Sounds good!
