### ISSUE TITLE
Compiling the C part fails due to not importing unistd

### ISSUE THREAD

**Issue by lilyminium** [MDAnalysis/mdanalysis#2934]
## Expected behavior ##

`python setup.py develop` successfully compiles MDAnalysis for me.

## Actual behavior ##

```
mdanalysis/package/MDAnalysis/analysis/encore/dimensionality_reduction/src/spe.c:197:22: error:
      implicit declaration of function 'getpid' is invalid in C99
      [-Werror,-Wimplicit-function-declaration]
    srand(time(NULL)+getpid()*getpid());
```

This is because `spe.c` does not import `unistd` because it doesn't think the Mac is `__unix__`:

https://github.com/MDAnalysis/mdanalysis/blob/b2b7bcbdf4e2fe4e221d5e67842c90cf317375e5/package/MDAnalysis/analysis/encore/dimensionality_reduction/src/spe.c#L30-L32

I'm probably missing something because I managed to compile MDAnalysis a month ago without any modifications. I first noticed this about a week ago?

## Code to reproduce the behavior ##

``` bash
python setup.py develop
```

## Current version of MDAnalysis ##

- Which version are you using? (run `python -c "import MDAnalysis as mda; print(mda.__version__)"`) develop
- Which version of Python (`python -V`)? 3.7.6 and 3.8.5
- Which operating system? MacOS 10.15.5
- Compilers: clang 12.0.0

```console
$ gcc --version
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/c++/4.2.1
Apple clang version 12.0.0 (clang-1200.0.26.2)
Target: x86_64-apple-darwin19.5.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

$ clang --version
Apple clang version 12.0.0 (clang-1200.0.26.2)
Target: x86_64-apple-darwin19.5.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

**Comment by IAlibay** [comment]
If you run `gcc -dM -E - </dev/null | grep unix` does anything show up?

**Comment by lilyminium** [comment]
no :(

**Comment by orbeckst** [comment]
Just fyi: macOS 10.12.6
```
(base) yngvi:accepted oliver$ gcc -dM -E - </dev/null | grep unix
(base) yngvi:accepted oliver$ gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```
and
```
(base) yngvi:accepted oliver$ clang  -dM -E - </dev/null | grep unix
(base) yngvi:accepted oliver$ clang --version
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

I ran `python setup.py develop` in a Python 3.7.6 conda env without problems.

I looked for `unistd.h` with `locate unistd.h` and found various copies, with `/System/Library/Frameworks/Kernel.framework/Versions/A/Headers/sys/unistd.h` and `/usr/include/unistd.h` / `/usr/include/sys/unistd.h` looking like standard places.

**Comment by tylerjereddy** [comment]
@lilyminium Does using `__APPLE__` like here work: https://stackoverflow.com/a/5920028/2942522 ?

I suppose it might not hurt to include that extra case even if we believe that the `__unix__` check really should work.

**Comment by lilyminium** [comment]
Thanks @tylerjereddy, yes, using a macro that is defined or just removing the if condition (my interim but suboptimal solution) works. It's interesting that @orbeckst doesn't have `__unix__` but can still compile (and so could I before); maybe it's a clang version difference? `unistd.h` is on my laptop in various locations too.
