### ISSUE TITLE
'PDBReader' object has no attribute 'timeseries'

### ISSUE THREAD

**Issue by sujigeo** [MDAnalysis/mdanalysis#2948]
Hi,
I am using back-mapped trajectory from a coarse grain simulation. I want to evaluate the trajectory convergence in doing so i am using the following script 
ces_conv = encore.ces_convergence(u,  # universe
                                  10,  # window size
                                  select="name CA")  # default
I am getting the following error 
 'PDBReader' object has no attribute 'timeseries'

In the backmapped trajectory file has the frame no instead of the time. Further in the example at "  https://userguide.mdanalysis.org/1.0.0/examples/analysis/trajectory_similarity/convergence.html#Using-default-arguments-with-dimension-reduction-ensemble-similarity" wrongly uses selection="name CA" instead of select="name CA". Any help would be greatly appreciated

Thank you

**Comment by orbeckst** [comment]
@sujigeo could you please show the code that you used to run your analysis (starting at when you make the Universe). The copy and paste the complete error output. Thank you.

**Comment by hmacdope** [comment]
Fixed in #3890
