### ISSUE TITLE
Docs don't build due to not finding ParmEd's site

### ISSUE THREAD

**Issue by lilyminium** [MDAnalysis/mdanalysis#2951]
## Expected behavior ##

Docs build successfully.

## Actual behavior ##

```
Warning, treated as error:
failed to reach any of the inventories with the following issues:
intersphinx inventory 'https://parmed.github.io/ParmEd/html/objects.inv' not fetchable due to <class 'requests.exceptions.HTTPError'>: 404 Client Error: Not Found for url: https://parmed.github.io/ParmEd/html/objects.inv
```

Docs fail at an early step (intersphinx looking for other libraries documentation). ParmEd's site is down. Relevant issue here:

https://github.com/ParmEd/ParmEd/issues/1106

Unfortunately this will affect the docs-building test/s until the site is up again. Not much we can do about it unless we remove ParmEd from intersphinx detection.

If you would like to test the doc build locally, you could comment out ``'https://parmed.github.io/ParmEd/html/': None,`` in `package/doc/sphinx/source/conf.py` (near the bottom)

**Comment by orbeckst** [comment]
If the ParmEd docs don’t get fixed soon we should just comment out our intersphinx linking.

**Comment by orbeckst** [comment]
ParmEd docs are up again.
