### ISSUE TITLE
https://docs.mdanalysis.org/ gives 404

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/mdanalysis#2962]
## Expected behavior ##

https://docs.mdanalysis.org shows the most recent release docs

## Actual behavior ##

I get 404 page not found.

## Code to reproduce the behavior ##
Open https://docs.mdanalysis.org in browser

```
404

File not found

The site configured at this address does not contain the requested file.

If this is your site, make sure that the filename case matches the URL.
For root URLs (like http://example.com/) you must provide an index.html file.

Read the full documentation for more information about using GitHub Pages.
GitHub Status — @githubstatus
```

**Comment by orbeckst** [comment]
@lilyminium I think the recent PRs #2955 #2960 broke our top level redirection (or there's a broken PageRule).

**Comment by orbeckst** [comment]
Note that https://userguide.mdanalysis.org/ works just fine and redirects to https://userguide.mdanalysis.org/1.0.0/index.html

**Comment by lilyminium** [comment]
:( the most recent merge into `develop` deleted `index.html`, possibly because I only tested it on master. I added it manually while I make it more robust https://docs.mdanalysis.org
