### ISSUE TITLE
Expose "stable" docs endpoint

### ISSUE THREAD

**Issue by bdice** [MDAnalysis/mdanalysis#2966]
## Is your feature request related to a problem? ##
I refer to MDAnalysis in the [documentation for freud](https://freud.readthedocs.io/en/stable/topics/datainputs.html#mdanalysis-readers) through an [intersphinx mapping](https://www.sphinx-doc.org/en/master/usage/extensions/intersphinx.html). I saw that the docs have moved to docs.mdanalysis.org. It would be nice to have a "stable" version of the MDAnalysis docs that could be referenced.

## Describe the solution you'd like ##
Add a "stable" docs version pointing to the latest stable release. Something like https://docs.mdanalysis.org/stable/. This is also how some other Python projects label their docs, e.g.
- https://numpy.org/doc/stable/
- https://scikit-learn.org/stable/

## Describe alternatives you've considered ##
I could pin my library to link to the 1.0.0 docs but that would become out of date as new MDAnalysis versions are released.

**Comment by orbeckst** [comment]
Thanks @bdice , we (I mean, @lilyminium ) is working hard on making all of this version switching magic work. Perhaps we can generate yet another set of redirects to "stable" when we publish a release? 

We have a PageRule that rewrites `https://docs.mdanalysis.org/<PATH>` to `https://docs.mdanalysis.org/1.0.0/<PATH>` but that does not seem to work for https://docs.mdanalysis.org/objects.inv (only https://docs.mdanalysis.org/1.0.0/objects.inv works).

**Comment by bdice** [comment]
@orbeckst @lilyminium That would be great! I use ReadTheDocs for deployment/hosting and it handles both a "stable" (release) and "latest" (development branch) build. I'm not sure how that works on your end, but it sounds like you have the right idea in mind for a fix. Much appreciated. 👍

**Comment by lilyminium** [comment]
It looks like numpy just has the same docs available at https://numpy.org/doc/stable/ and https://numpy.org/doc/1.19 with no redirects, we could do the same thing with MDAnalysis and `docs.mdanalysis.org/stable` and `docs.mdanalysis.org/1.0.0` ? Currently URLs like docs.mdanalysis.org/latest redirect to docs.mdanalysis.org/1.0.0 but that doesn't work for downloading an `objects.inv`. (Interestingly, www.mdanalysis.org/docs/ does redirect intersphinx to `docs.mdanalysis.org/1.0.0`, but we may want to retire that PageRule someday.)

**Comment by bdice** [comment]
Intersphinx threw a warning when it followed the redirect from www.mdanalysis.org/docs/ to docs.mdanalysis.org/1.0.0, which is the only way I knew this was a potential issue. Didn't want to count on an old link to stay alive. 😉

**Comment by lilyminium** [comment]
https://docs.mdanalysis.org/dev/ and https://docs.mdanalysis.org/stable/ should now exist as endpoints.

**Comment by bdice** [comment]
@lilyminium Thanks again! I confirm that `stable` worked for me. 👍
