### ISSUE TITLE
Having a circular delta function in the MDAnalysis.lib.mdamath for computing the difference between dihedral angles

### ISSUE THREAD

**Issue by xiki-tempula** [MDAnalysis/mdanalysis#2969]
## Is your feature request related to a problem? ##
It is quite common that one might want to know the absolute difference between two dihedral angles or between two dihedral angle n-dimensional arrays, so it would be nice if such function exists in `MDAnalysis.lib.mdamath`.

## Describe the solution you'd like ##
I think the interface can mimic the scipy Circular statistical functions

``` python
def circdelta(sample1, sample2, high=2*pi, low=0, nan_policy='propagate'):
    """
    Compute the circular difference between sample1 and sample2 in a range.
    Parameters
    ----------
    samples1 : array_like
        Input array 1.
    samples2 : array_like
        Input array 2.
    high : float or int, optional
        High boundary for circular delta range.  Default is ``2*pi``.
    low : float or int, optional
        Low boundary for circular delta range.  Default is 0.
    nan_policy : {'propagate', 'raise', 'omit'}, optional
        Defines how to handle when input contains nan. 'propagate' returns nan,
        'raise' throws an error, 'omit' performs the calculations ignoring nan
        values. Default is 'propagate'.
    Returns
    -------
    circdelta : array_like
        Circular delta.
    Examples
    --------
    >>> from MDAnalysis.lib.mdamath import circdelta
    >>> circdelta(0.1, 5)
    1.38
    >>> circmean([0.1, 2], [5, 3])
    [1.38, 1]
    """

```

**Comment by orbeckst** [comment]
What about trying to get it into scipy? Or would it not fit anywhere there, @tylerjereddy ?

**Comment by tylerjereddy** [comment]
There's no harm in trying--normally new features are proposed on the mailing list first: scipy-dev@python.org 

I'd probably need to see a diagram of the angle comparison to fully understand what is being calculated. Not sure if the convenience is a huge gain over the rotation calculations available in i.e., `scipy.spatial.transform`, but the team would let you know.

**Comment by IAlibay** [comment]
@xiki-tempula did you get anywhere with getting this into scipy?

**Comment by xiki-tempula** [comment]
https://github.com/scipy/scipy/issues/13673 They say there isn't such a function in scipy and if I want to have one I need to implement it myself.

**Comment by V0lantis** [comment]
> [scipy/scipy#13673](https://github.com/scipy/scipy/issues/13673) They say there isn't such a function in scipy and if I want to have one I need to implement it myself.

This is not what @tupui said I believe. He said :

> You could try to ask on the mail list or if you're confident this is actually wanted propose a PR.

If you are not interested in implementing it, it could give it a try :-)

**Comment by IAlibay** [comment]
From an MDAnalysis standpoint, are we ok saying this will be dealt with upstream or would you prefer we keep this issue open here @xiki-tempula ? (I guess maybe we should wait and see what the general feeling is towards such a feature on the scipy mailing list first?)

**Comment by tupui** [comment]
To clarify things, I don't feel competent enough to propose a PR myself as I am hearing about this from the first time. I could review the work or help with making a PR though if needed.

**Comment by xiki-tempula** [comment]
@V0lantis Yes, it is true that the wording is a bit different but you know, in practice, it might be close. Feel free to implement it, if you felt confident with it. 
@IAlibay Yes, I think we could close this issue.
