### ISSUE TITLE
Add python 3.9 support

### ISSUE THREAD

**Issue by IAlibay** [MDAnalysis/mdanalysis#2974]
## Is your feature request related to a problem? ##

Python 3.9 is now officially out 🎉 https://docs.python.org/3.9/whatsnew/3.9.html

We probably should aim to support it soon-ish?

Currently waiting on 3.9 to be released on conda before a test PR can be raised.

## Additional context ##

Related issue: #2688

**Comment by richardjgowers** [comment]
inversely, do we *not* support it currently? I.e. was anything we used broken by it? (likely not...)

**Comment by IAlibay** [comment]
> inversely, do we *not* support it currently? I.e. was anything we used broken by it? (likely not...)

Highly doubt anything will change (at least until we decide to start type hinting everything).

Just needs adding to the test matrix == reward :)

**Comment by tylerjereddy** [comment]
Will take a while for the ecosystem to build out wheels for 3.9 too--I'm working on that for SciPy, but we're also trying to get out Linux ARM64 wheels at the same time so a bit crazy..

**Comment by jbarnoud** [comment]
> inversely, do we not support it currently? I.e. was anything we used broken by it? (likely not...)

I installed develop on python 3.9 and could run the tests fine. I got an error (#2979) but it was unrelated to the version of python. I got many tests skipped, though (361) so some of them may have failed.

**Comment by Seanny123** [comment]
To expand on what @markf94 has submitted, it's not that MDAnalysis code doesn't support Python 3.9, it's the package specification that needs to be updated, so it can work with stricter package manages such as Poetry.

Looking at the MDAnalysis Roadmap, I understand if this doesn't happen until 2.0 is released.

**Comment by IAlibay** [comment]
Indeed, we purposely aren't making 1.0.x py3.9 compatible. 1.0.x is now a legacy bugfix only release which will support py2.7, and py3.5-3.8 (although support for py2.7 and py3.5 is getting increasingly hard to guarantee).

Work is currently in progress to bring py3.9 along to 2.0.0, however not all our optional dependencies have a py3.9 release (at least last I checked).

> To expand on what @markf94 has submitted, it's not that MDAnalysis code doesn't support Python 3.9, it's the package specification that needs to be updated, so it can work with stricter package manages such as Poetry.

@Seanny123  I'm not sure I understand what you mean here. I've not used poetry before so maybe I'm completely wrong, but from the error message that @markf94 shows it seems to be correctly capturing from setup.py that the python version doesn't fit the specs? Any input on how we can improve our setup to better fit more package managers is appreciated.

**Comment by markf94** [comment]
Yeah `poetry` is very strict when it comes to package versions. @Seanny123 basically said that there is nothing preventing you guys from making `MDAnalysis` officially Python 3.9 compatible by updating your `setup.py` since your code would still work. However, I understand your reasoning behind not doing that yet because of your dependencies.
