### ISSUE TITLE
Add sort method to the atomgroup

### ISSUE THREAD

**Issue by xiki-tempula** [MDAnalysis/mdanalysis#2976]
## Is your feature request related to a problem? ##
I have an edgy case, where I have two small molecules, they share a common substructure. I want to superimpose them based on the common substructure. The difficulty is that the common substructure doesn't have the same order of atoms.

Given a `mapping` dictionary which maps atoms from molecule 1 (key) to molecule 2 (value), the superimposition is done like this, where I need to manually reorder the ordered atomgroup.

```python
from MDAnalysis.analysis.align import alignto
substructure_1 = []
substructure_2 = []
for id1, id2 in mapping.items():
    substructure_1.append(molecule_1.select_atoms('bynum {}'.format(id1))
    substructure_2.append(molecule_2.select_atoms('bynum {}'.format(id2))
substructure_1 = sum(substructure_1)
substructure_2 = sum(substructure_2)
alignto(substructure_1, substructure_2)

# move to the original rank
new_substructure_1 = []
for id in sorted(substructure_1.ids):
    new_substructure_1.append(substructure_1.select_atoms('bynum {}'.format(id))
substructure_1 = sum(new_substructure_1)
alignto(molecule_1, substructure_1, select='bynum {}'.format(' '.join(substructure_1.ids)))
```

## Describe the solution you'd like ##
So if the atomgroup has a sort method, I could then just sort the atomgroup with one line. `substructure_1.sort(key=lambda atom: atom.id)`

```python
from MDAnalysis.analysis.align import alignto
substructure_1 = []
substructure_2 = []
for id1, id2 in mapping.items():
    substructure_1.append(molecule_1.select_atoms('bynum {}'.format(id1))
    substructure_2.append(molecule_2.select_atoms('bynum {}'.format(id2))
substructure_1 = sum(substructure_1)
substructure_2 = sum(substructure_2)
alignto(substructure_1, substructure_2)

# move to the original rank
substructure_1.sort(key=lambda atom: atom.id)
alignto(molecule_1, substructure_1, select='bynum {}'.format(' '.join(substructure_1.ids)))
```

**Comment by IAlibay** [comment]
Just going to copy @RMeli here, whom I believe was working on something with a lot of overlap with this.

**Comment by xiki-tempula** [comment]
@IAlibay Thanks for the quick reply.
I think the key issue here is to replace

```python
new_substructure_1 = []
for id in sorted(substructure_1.ids):
    new_substructure_1.append(substructure_1.select_atoms('bynum {}'.format(id))
substructure_1 = sum(new_substructure_1)
```
with
`substructure_1.sort(key=lambda atom: atom.id)`

Not the maximum common substructure problem, which is just to provide one context.

**Comment by richardjgowers** [comment]
So an AtomGroup is really just `.ix` and `.universe` and everything else is derived from that.  Calling sort on `.ix` and remaking the atomgroup, i.e. `universe[np.sort(ag.ix)]` should work?  I'm trying to think what will break if we sort `self.ix` in place, probably all the cached things (which hopefully all live in `._cache`...)

**Comment by jbarnoud** [comment]
>  I'm trying to think what will break if we sort self.ix in place, probably all the cached things (which hopefully all live in ._cache...)

So far we have been regarding the AtomGroup as an unmutable object and I think it has a positive impact on the library.

I would recommand something in the lines of

```
ag1 = ...
order = np.argsort(ag1.ids)
ag2 = ag1[order]
```
