### ISSUE TITLE
ENCORE uses deprecated features of sklearn

### ISSUE THREAD

**Issue by jbarnoud** [MDAnalysis/mdanalysis#2986]
## Expected behavior ##

Running the tests throws no warning, and the library does not use deprecated features of the libraries it depends on.

## Actual behavior ##

Running the tests warns about ENCORE using deprecated features of scikit-learn:

```
MDAnalysisTests/analysis/test_encore.py: 13 warnings
  /home/jon/miniconda3/envs/py38/lib/python3.8/site-packages/sklearn/cluster/_kmeans.py:932: FutureWarning: 'precompute_distances' was deprecated in version 0.23 and will be removed in 0.25. It has no effect
    warnings.warn("'precompute_distances' was deprecated in version "

MDAnalysisTests/analysis/test_encore.py: 13 warnings
  /home/jon/miniconda3/envs/py38/lib/python3.8/site-packages/sklearn/cluster/_kmeans.py:938: FutureWarning: 'n_jobs' was deprecated in version 0.23 and will be removed in 0.25.
    warnings.warn("'n_jobs' was deprecated in version 0.23 and will be"

MDAnalysisTests/analysis/test_encore.py::TestEncoreClustering::test_clustering_AffinityPropagation_direct
MDAnalysisTests/analysis/test_encore.py::TestEncoreClustering::test_clustering_two_different_methods
MDAnalysisTests/analysis/test_encore.py::TestEncoreClustering::test_sklearn_affinity_propagation
  /home/jon/miniconda3/envs/py38/lib/python3.8/site-packages/sklearn/cluster/_affinity_propagation.py:146: FutureWarning: 'random_state' has been introduced in 0.23. It will be set to None starting from 0.25 which means that results will differ at every function call. Set 'random_state' to None to silence this warning, or to 0 to keep the behavior of versions <0.23.
    warnings.warn(("'random_state' has been introduced in 0.23. "
```

## Code to reproduce the behavior ##

`pytest analysis/test_encore.py`

## Current version of MDAnalysis ##

- Which version are you using? (run `python -c "import MDAnalysis as mda; print(mda.__version__)"`) 2.0.0-dev0 64a7c051f1a51ff2a89b9da9257a21cea0ef00fa
- Which version of Python (`python -V`)? Python 3.8.5
- Which operating system? Ubuntu 20.04 on WSL

**Comment by thadanipaarth** [comment]
Is this issue still open @jbarnoud @orbeckst @lilyminium? I'd like to work on it!

**Comment by lilyminium** [comment]
@thadanipaarth do go ahead! Please see the [user guide](https://userguide.mdanalysis.org/stable/contributing_code.html#) for resources on contributing to MDAnalysis.

**Comment by thadanipaarth** [comment]
@lilyminium I have opened a [PR](https://github.com/MDAnalysis/mdanalysis/pull/3178). Please have a look at it!
