### ISSUE TITLE
Loading forces to universe when creating an in-memory trajectory of a sub-system

### ISSUE THREAD

**Issue by mehradans92** [MDAnalysis/mdanalysis#3015]
## Is your feature request related to a problem? ##

Yes

## Describe the solution you'd like ##

I am interested in creating a subsystem universe and include the forces from the initial setting.  

I have considered this but it doesn't seem to work. 

```
protein = u.select_atoms('resname PHE')

u_coordinates = AnalysisFromFunction(lambda ag: ag.positions.copy(),
                                   protein ).run().results

u_forces = AnalysisFromFunction(lambda ag: ag.forces.copy(),
                                   protein).run().results

u2 = mda.Merge(protein)            # create the protein-only Universe

u2.load_new(u_coordinates, format=MemoryReader)  # load related coordinates into Universe

u2.load_new(u_forces , format=MemoryReader)   # load related forces into Universe
```

**Comment by orbeckst** [comment]
@mehradans92 I encourage you to post your question to the user list https://groups.google.com/group/mdnalysis-discussion — maybe there's a way to do what you want with the available tools. Once it becomes clear that there's no obvious way to do it then it's clear that there's a demonstrated need for the feature.

**Comment by mehradans92** [comment]
Thanks Oliver. I posted my question in the group.

**Comment by orbeckst** [comment]
Please feel free to re-open the issue, especially if nothing useful comes from the mailing list – that would also be a sign that there's something missing: either a feature or documentation.
