### ISSUE TITLE
CI; unpin h5py

### ISSUE THREAD

**Issue by IAlibay** [MDAnalysis/mdanalysis#3023]
As detailed in #3019 the 3.0 release of h5py was causing widespread test failures.

Currently CI is pinned to 2.10, however we should:

1. Investigate what caused the issue (is this an issue with MDA or h5py?)
2. Attempt to unpin

and / or

3. Define the pin in setup? (maybe under `extras_require`?)

**Comment by yuxuanzhuang** [comment]
Seem to be an easy fix for h5py 3.0---it raises IndexError instead of ValueError now:) I will step in.

**Comment by orbeckst** [comment]
@edisj please see this issue for the h5py error that you also ran into.
