### ISSUE TITLE
NCDFWriter inconsistent with NCDFReader

### ISSUE THREAD

**Issue by tclick** [MDAnalysis/mdanalysis#3030]
## Is your feature request related to a problem? ##
The NCDFWriter only accepts the '.ncdf' extension while the reader can handle both '.ncdf' and '.nc'

## Describe the solution you'd like ##
As the problem above suggests, it might be useful to add '.nc' exntension to the NCDFWriter.

**Comment by orbeckst** [comment]
What is the error that you get? Can you show an example use case?

In general you should always be able to explicitly give the format with a `format` kwarg.

**Comment by IAlibay** [comment]
To be fair, our lack of support for `.ncdf` writing does break out docs.

https://github.com/MDAnalysis/mdanalysis/blob/e9d0e88ed40a810273af4cf1c742058b1a761b66/package/MDAnalysis/coordinates/__init__.py#L205-L209

...nevermind those that got written in the class docstring (that might be on me oops... 🙄 ).

Fix incoming.
