### ISSUE TITLE
Remove support for ts as an input to the ParmedConverter

### ISSUE THREAD

**Issue by IAlibay** [MDAnalysis/mdanalysis#3031]
## Context

As discussed in https://github.com/MDAnalysis/mdanalysis/pull/3029#issuecomment-729047942 the ParmedConverter currently takes either an atomgroup/universe or timestep as an input. However as of #2754, support for passing timestep objects to writers was removed.

Given this, it might make sense to remove support for `ts`?

Maybe we should deprecate for 1.0.x and remove for 2.0?

**Comment by avitomar12** [comment]
Hey @IAlibay  Is it possible to give reference to the code for this issue?

**Comment by IAlibay** [comment]
@avitomar12 we are referring to: https://github.com/MDAnalysis/mdanalysis/blob/6282385644d672cf7023584347e35048935ab429/package/MDAnalysis/coordinates/ParmEd.py#L137

Particularly the class' ability to take timestep objects as an input.

@lilyminium should we try to get the deprecation warning through in 1.1.0 for this?

**Comment by lilyminium** [comment]
I don't know how many people actually use this code instead of just the convert_to function. Did we have a deprecation warning when we removed ts from the other writers?

**Comment by IAlibay** [comment]
Yup: https://github.com/MDAnalysis/mdanalysis/blob/4365f3b07c1bf2ebcf16424b26162102954c5b90/package/MDAnalysis/coordinates/base.py#L2225-L2230

**Comment by lilyminium** [comment]
Okies, sounds good. I'll do that and the chainID deprecation.

**Comment by kitsiosvas** [comment]
Hi, @IAlibay is this issue taken? I would like to work on this if not.

**Comment by IAlibay** [comment]
@kitsiosvas as far as I am aware there are no PRs open on for this issue. Whilst @avitomar12 indicated they may want to work on it ten days ago, MDAnalysis has decided to take a PR-first approach (i.e. the first PR open is the one we will review, see: https://github.com/MDAnalysis/mdanalysis/wiki/GSoC-FAQ#can-i-claim-an-issue-to-work-on). So please do feel free to open a PR addressing the issue.

**Comment by IAlibay** [comment]
This was taken care of for 1.1. Needs forward porting.

**Comment by kitsiosvas** [comment]
@IAlibay Apologies for my delay on working for this issue. I want to inform you that I will not be able to work on this. If anyone else wants to take it, I haven't opened a PR yet so it's free. Again, apologies.

**Comment by IAlibay** [comment]
> @IAlibay Apologies for my delay on working for this issue. I want to inform you that I will not be able to work on this. If anyone else wants to take it, I haven't opened a PR yet so it's free. Again, apologies.

No worries, thanks for letting us know :)
