### ISSUE TITLE
ITPParser doesn't like some relative paths

### ISSUE THREAD

**Issue by richardjgowers** [MDAnalysis/mdanalysis#3037]
## Actual behavior ##

Relative paths (when going "upwards"/`../`) in the ITPParser seem to fail.

I think that all is needed is for `find_path` to have an `abspath` call early on, as absolute paths seem to work fine.

## Code to reproduce the behavior ##

```bash
cp file.itp ./
mkdir something
cd something
```

``` python
import MDAnalysis as mda
from MDAnalysis.tests.datafiles import PSF, DCD,  GRO, PDB, TPR, XTC, TRR,  PRMncdf, NCDF

u = mda.Universe('../file.itp', format='ITP')

....

```

## Current version of MDAnalysis ##

- Which version are you using? (run `python -c "import MDAnalysis as mda; print(mda.__version__)"`)
- Which version of Python (`python -V`)?
- Which operating system?

**Comment by aditya-kamath** [comment]
Hi @richardjgowers , I am student just learning how to develop code. In this situation, I found find_path in the ITPParser file, but I am unable to locate where the abspath function is at? Sorry, this might seem like a trivial question.

**Comment by tylerjereddy** [comment]
@aditya-kamath This may help: https://docs.python.org/3/library/os.path.html#os.path.abspath

**Comment by aditya-kamath** [comment]
Thanks @tylerjereddy !
