### ISSUE TITLE
DensityAnalysis with empty selection

### ISSUE THREAD

**Issue by TBGAnsell** [MDAnalysis/mdanalysis#3055]
Hello, I am trying to use DensityAnalysis for an atomselection that is initially empty but which becomes filled over the course of the trajectory. DensityAnalysis fails if the selection is initially empty despite using updating=True:

eg commands used:
```python
site=u.select_atoms("byres resname LIG and around 6 protein", updating=True)
D=DensityAnalysis(site, delta=1).run()
```
I have got around by filling with a random atom but obviously not ideal.

**Comment by orbeckst** [comment]
Good point. That's definitely an edge case that we did not consider.

A really stupid workaround would be to 
1. first run the selection yourself
2. note the first frame that it's not empty
3. start the analysis on that frame

```python
u = mda.Universe(topol, traj)
site = u.select_atoms("byres resname LIG and around 6 protein", updating=True)
for ts in u.trajectory:
   if len(site) > 0:
       start = ts.frame
       break
else:
    raise ValueError("No atoms in selection over whole traj")

D = DensityAnalysis(site, delta=1, start=start).run()
```

**Comment by orbeckst** [comment]
Making DensityAnalysis more robust would be good. Potential approaches
- Follow https://github.com/MDAnalysis/mdanalysis/issues/3055#issuecomment-739089297 and read until a frame with an appropriate selection appears. Make sure that the normalization of the final histogram is still correct.
- Introduce a dummy count or just create and empty histogram.
- ... your own idea?

A challenge would also be to select the correct box size for the histogram (perhaps default to the simulation box unless provided by user?)

If you're interested in solving this issue in preparation for e.g. GSOC or you just want to get into contributing then we suggest you look at the code for DensityAnalysis, try to understand what's happening there and how the above problem comes about, and then use this issue to discuss your approach to solving it. You're also welcome to put up a PR that we can comment on.

**Comment by aditya-kamath** [comment]
Hi @orbeckst, I am a student looking at some starter issues here to prep for GSOC. 
In this case- Do you reckon it will be okay if I just write a if condition in ( _prepare) to catch this situation and output - 
_grid=[[[0.]]]
_edges=[array([-0.5,  0.5]), array([-0.5,  0.5]), array([-0.5,  0.5])]
_arange=None
_bins=1
_density=None
My idea is to give a dummy density which will hopefully not affect the other images.

**Comment by aditya-kamath** [comment]
Okay! I think I understand what you mean. Perhaps for now I can write a simple if condition to display an error and exit when this happens.

**Comment by orbeckst** [comment]
>  I think probably the easiest answer for this specific issue may just be to capture the edge case, fail and tell users that no atoms were found in the given selection and that they should use a user defined grid instead.

On reflection, I agree with @IAlibay. (With small numbers of molecules, the automatic grid dimension determination does not make a lot of sense, which was added with water density in mind.)

----

If you're getting into working on DensityAnalysis then figuring out other ways to determine the grid would be interesting next steps, especially when the trajectory was structurally superimposed before the analysis and the box is effectively rotating around the solute. If the simulation was done under PBC and **if** we were to store actual box vectors (as opposed to re-oriented ones where `e1` is always `[1, 0, 0]`) then we could reconstruct the full infinite system and "cut out" the brick-like box shape around the solute at every step.

(If this last paragraph does not make a lot of sense to you then don't worry – it's a thought for potential future projects.)

**Comment by orbeckst** [comment]
Btw, does [`DensityAnalysis`](https://docs.mdanalysis.org/stable/documentation_pages/analysis/density.html#MDAnalysis.analysis.density.DensityAnalysis) fail if `xdim`, `ydim`, `zdim` and `gridcenter` are provided _and_ there is nothing selected in a frame?

**Comment by lilyminium** [comment]
> Btw, does DensityAnalysis fail if xdim, ydim, zdim and gridcenter are provided and there is nothing selected in a frame?

Yup, it's [this call to  get the minimum of an empty array of positions](https://github.com/MDAnalysis/mdanalysis/blob/0de538ea70a88f4107d3101b029d48d1e100b1ff/package/MDAnalysis/analysis/density.py#L397-L398).

We do it when the box is defined to check if an atom selection is outside the bounds, and warn the user if so. A solution to this may want to consider first checking if there are positions to get the minimum/maximum of.

**Comment by TBGAnsell** [comment]
As lilminium says - it does fail when box dimensions are specified. I feel that maybe some context here may also be useful. I was using the original code to create a binary mask for a global LIG density and therefore the same box dimensions and gridcenter were specified.

**Comment by IAlibay** [comment]
> A solution to this may want to consider first checking if there are positions to get the minimum/maximum of.

Agreed, it's an extra try/except, we could probably just pass `coord` to `_set_user_grid` and then have the checks be done in one go there.

**Comment by aditya-kamath** [comment]
@IAlibay, I tried what you suggested - the Try Except on the `smin` `smax` and passing the input on to `_set_user_grid` however as it turns out `_set_user_grid` needs smin and smax as an input. Now, I cant calculate smin and smax because there's no coords.

**Comment by aditya-kamath** [comment]
I don't think I can default `smin` `smax` to 0 either, the `BINS` generation will fail.  The quickest fix  I can think for this is to just fail if no atoms are given. But then again, that doesn't exactly fix anything!

**Comment by IAlibay** [comment]
@aditya-kamath my comment above was just a suggestion about how the issue could be tackled, it is very much possible that it is not the right/cleanest answer (although do note that I do mention passing `coords` to `_set_user_grid` which would mean not needing to pass `smin` or `smax`).

The aim of the any PR here, as mentioned by @lilyminium, is to work out how to optimally check that there are no atoms in the current frame's selection before or during the assignment of `smin` and `smax`. It will likely mean that the way/order in which `smin` and `smax` are obtained might need to to be shuffled around and/or that arguments to `_set_user_grid` will change.

> The quickest fix I can think for this is to just fail if no atoms are given. But then again, that doesn't exactly fix anything!

Note, we do want it to fail when we aren't using a user defined grid.

**Comment by aditya-kamath** [comment]
Yeah, you're absolutely right! There must be a way to break this cycle. I'll try to figure it out..
