### ISSUE TITLE
Error in msd algorithm of MDAnalysis

### ISSUE THREAD

**Issue by EnthusiasticTeslim** [MDAnalysis/mdanalysis#3064]
Great contribution by MDAnalysis team! I tried using the msd approach in MDAnalysis and got an error message ModuleNotFoundError: No module named 'MDAnalysis.analysis.msd'. Other analysis modules such as import MDAnalysis.analysis.align works perfectly. Kindly advise on how to solve this issue. Thanks! Regards.

For installation, I use this:
pip install --upgrade MDAnalysis
pip install --upgrade MDAnalysisTests

For msd calculation, i use this approach:

import MDAnalysis as mda
import MDAnalysis.analysis.msd as msd
from MDAnalysis.tests.datafiles import RANDOM_WALK, RANDOM_WALK_TOPO

**Comment by IAlibay** [comment]
@EnthusiasticTeslim what version of MDAnalysis did pip install?

Can you do the following:

```python
import MDAnalysis as mda
print(mda.__version__)
```

**Comment by EnthusiasticTeslim** [comment]
I got the following:

1.0.0

**Comment by IAlibay** [comment]
@EnthusiasticTeslim unfortunately the MSD code never made it to the 1.0 release. It's available on the current development branch (future 2.0 release). You'll have to install the development code if you want to use it, see here for more details: https://userguide.mdanalysis.org/stable/contributing_code.html#creating-a-development-environment

**Comment by EnthusiasticTeslim** [comment]
Thank you. Do I need to uninstall the current one?

**Comment by IAlibay** [comment]
I would probably encourage you to have a separate conda environment for the development branch.

I _think_ pip will remove the current release MDA version, but you might want to keep it around (especially since 2.0 is still some time away from being released).

**Comment by IAlibay** [comment]
@EnthusiasticTeslim I'm going to close this issue since it doesn't seem to relate to an active bug.

However I do encourage you to post on the mailing list to discuss further re: develop installation, etc... There will be more folks there who will be able to share their experiences with it.

**Comment by EnthusiasticTeslim** [comment]
Thank you very much for your response. Sincere gratitude!

**Comment by EnthusiasticTeslim** [comment]
I got it to work. Thanks for the guide!
