### ISSUE TITLE
drop AppVeyor CI

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/mdanalysis#3065]
AppVeyor has been a great service for us, especially when it was the only one that provided Windows testing. The CI landscape has changed and AppVeyor has been consistently slower than GH-actions and Azure Pipelines. Furthermore, ci-helpers stopped active support #3017 .

I would suggest we remove AppVeyor testing from our CI on both 
- [x] develop and
- [ ] master.

Coverage might drop because AppVeyor uses conda installation whereas our Azure Pipelines use pip and are more limited in the available packages (e.g., RDKit is not on pip). 

Nevertheless, we can make the change now and raise a new issue to establish a Azure Pipeline with conda if necessary.

**Comment by IAlibay** [comment]
Just re-opening so that we don't forget to get rid of the yaml file on `master` (I've asked for it to be done as part of #3067).

**Comment by orbeckst** [comment]
PR #3067 was merged and dropped AppVeyor on master, too, so I am closing.
