### ISSUE TITLE
Improve docs for MSD class and add detailed example to userguide.

### ISSUE THREAD

**Issue by hmacdope** [MDAnalysis/mdanalysis#3074]
Clearer docs around what best practices are for calculation of MSDs are probably needed. For example a more prominent note that you should use unwrapped trajectories is needed.

There is also a reasonable amount of assumed knowledge in the docs as they are currently and it seems to be tripping people up. The language should be improved to be more accessible. A detailed example in the user guide would be handy in this respect.

**Comment by spursbyte** [comment]
I want to work on this issue. Can you please provide me more info?

**Comment by IAlibay** [comment]
@spursbyte It's not immediately clear to us what you would like more information about. As it's an issue that covers a large amount of information (being related to the theoretical basis of the analysis method), is there a particular area that you would like to have more information about?

Before I carry on, I should note that this may not be the best issue to tackle as a "first contribution". I don't want to assume your pre-existing technical knowledge, but I just wanted to make you (and others) aware, that this is the kind of issue that really requires both previous experience with MDAnalysis as a user, and domain knowledge (re: the mathematical underpinnings of MSD calculations).

From my understanding of the issue, this would require two things:
1) A worked userguide example (see here for examples: https://github.com/MDAnalysis/UserGuide/tree/master/doc/source/examples/analysis)
2) Sprucing up of the docstring for https://github.com/MDAnalysis/mdanalysis/blob/develop/package/MDAnalysis/analysis/msd.py
Looking specifically to detail any assumptions in running the analysis (as @hmacdope mentions, thinks like dealing with PBC), and generally more information about the technicalities for the method so as to make it less likely that folks will make mistakes when using it. I believe that @hmacdope opened this issue after the following discussion: https://groups.google.com/g/mdnalysis-discussion/c/6m8rWx2kkY4/m/TYkllRZYCAAJ, so this should be accounted for as part of the context of any changes to the docstring.

**Comment by spursbyte** [comment]
@IAlibay ok is there any first time issue that you can help me out with as i am new to open source contributons and would like to contribute to the organization..

**Comment by IAlibay** [comment]
@spursbyte I would suggest emailing on the MDAnalysis developer list: https://groups.google.com/group/mdnalysis-devel

My advice would probably be to look for issues tagged "Difficulty-easy" and "GSOC".
