### ISSUE TITLE
Hoping to Please Check in on an Offsets Question

### ISSUE THREAD

**Issue by dasharon** [MDAnalysis/mdanalysis#3077]
Dear MDAnalysis Team,

I have really been enjoying using MDAnalysis! If possible, I hope to please check in on a question:

When I load trajectories with the code (using MDAnalysis version 0.20.1):

> import MDAnalysis
> univ_1 = MDAnalysis.Universe("traj_1.tpr", "traj_1.xtc")
> univ_2 = MDAnalysis.Universe("traj_2.tpr", "traj_2.xtc")
> univ_3 = MDAnalysis.Universe("traj_3.tpr", "traj_3.xtc")

I receive the message (once):

> .../anaconda3/lib/python3.7/site-packages/MDAnalysis/coordinates/XDR.py:196: UserWarning: Reload offsets from trajectory
>  ctime or size or n_atoms did not match
>   warnings.warn("Reload offsets from trajectory\n "

However, when I rerun this code, I no longer see the message. Trajectory data is loading without issues. This [link](https://github.com/MDAnalysis/mdanalysis/issues/1988) discusses this error in the context of another error, and looking at the source code [here](https://docs.mdanalysis.org/stable/_modules/MDAnalysis/coordinates/XDR.html) it looks like there may be an issue with the time, number of atoms, or size. 

If possible, I hope to please check in: why is this message appearing the first time I run the code, but not subsequently? Does this message indicate cause for concern regarding the validity of trajectory analysis results, in light of not noticing issues with the loaded trajectory files?

I would be very grateful for any advice or suggestions you could please provide, and I thank you for making MDAnalysis an excellent toolkit!

With very many thanks,
Dina

**Comment by orbeckst** [comment]
Hello @dasharon – we keep the issue tracker for bug reports or enhancements. We only answer questions on the mailing list as this makes it easier for developers to focus on these different things. Also, on the mailing list other users can chime in. Please ask at https://groups.google.com/group/mdnalysis-discussion – Thank you!

**Comment by dasharon** [comment]
Dear Professor Beckstein,

I thank you so much for sharing these very helpful updates with me! I apologize for asking my question in the wrong place, and I have asked the question on the mailing list. I thank you and your colleagues for making MDAnalysis an excellent toolkit!

With very many thanks,
Dina
