### ISSUE TITLE
Unpin pytest on CI

### ISSUE THREAD

**Issue by IAlibay** [MDAnalysis/mdanalysis#3082]
Follow up from #3081 

`pytest` was pinned due to Windows OS failures, probably due to some upstream issues.

I'm opening this issue so that we remember to look into what happened here and aim to unpin as soon as we can.

**Comment by lilyminium** [comment]
Thanks @IAlibay! An additional reminder to future readers that it was also pinned on GH Actions for Linux and Mac. The issue was Python 3.8 specific.

**Comment by IAlibay** [comment]
See here for some extra discussions on the subject: https://github.com/MDAnalysis/mdanalysis/pull/3139#issuecomment-797795850
