### ISSUE TITLE
Error importing MDAnalysis.tests.datafiles

### ISSUE THREAD

**Issue by luponzo86** [MDAnalysis/mdanalysis#3084]
## Expected behavior ##

Succesfull import of module `MDAnalysis.tests.datafiles` after installing `MDAnalysisTests` via `pip`

## Actual behavior ##
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-5-2f9c58525a71> in <module>()
----> 1 from MDAnalysis.tests.datafiles import PSF, DCD

/srv/home/lponzoni/anaconda3/envs/ifpe/lib/python3.7/site-packages/MDAnalysis/tests/datafiles.py in <module>()
     41 
     42 try:
---> 43     from MDAnalysisTests.datafiles import *
     44 except ImportError:
     45     print("*** ERROR ***")

/srv/home/lponzoni/anaconda3/envs/ifpe/lib/python3.7/site-packages/MDAnalysisTests/__init__.py in <module>()
    124 try:
    125     import matplotlib
--> 126     matplotlib.use('agg', warn=False)
    127 except ImportError:
    128     pass

TypeError: use() got an unexpected keyword argument 'warn'
```

## Code to reproduce the behavior ##

``` python
from MDAnalysis.tests.datafiles import PSF, DCD

```

## Current version of MDAnalysis ##

- Which version are you using? 1.0.0
- Which version of Python (`python -V`)? Python 3.7.8
- Which operating system? Linux

**Comment by RMeli** [comment]
Hi @luponzo86 , unfortunately this is a known issue ( #2938,  #3041) and should be fixed in the next release. In the meantime you can use pin matolotlib to `matplotlib<3.3` as explained in  #2938.

**Comment by luponzo86** [comment]
Sounds good, thanks! Apologies for the duplicate issue
