### ISSUE TITLE
Found Deadlink in [learning Mdanalysis page](https://userguide.mdanalysis.org/stable/contributing_code.html)

### ISSUE THREAD

**Issue by sparkingdark** [MDAnalysis/mdanalysis#3090]
when I clicked on the [quickstart guide](https://userguide.mdanalysis.org/examples/quickstart.html) under tutorial section I got the error 404 may be the file is missing ,
another deadlink is available as well in Documentation section the same link quickstart guide.

https://user-images.githubusercontent.com/50295688/103532068-940ca780-4eb0-11eb-9218-4313817bd9d4.mp4

I can try to fix it if the original link given or I add the file quickstart.html with proper instructions available.

**Comment by lilyminium** [comment]
Thank you for finding this, @sparkingdark! Hopefully this will get fixed soon (it is actually in a different site-focused repository, so has very little to do with the code here.) In the mean time, if you would like to have a look at the quick start guide, it's [here](https://userguide.mdanalysis.org/stable/quickstart.html).

**Comment by sparkingdark** [comment]
Thanks for sending the resources

**Comment by lilyminium** [comment]
Closed in https://github.com/MDAnalysis/MDAnalysis.github.io/pull/163.
