### ISSUE TITLE
Atomgroup index with None give back the full Atomgroup

### ISSUE THREAD

**Issue by xiki-tempula** [MDAnalysis/mdanalysis#3092]
## Expected behavior ##
If I use None as atomgroup index, I expect to obtain an empty atom group.

```
>>> u = mda.Universe(crd)
>>> u.atoms[None]
<AtomGroup with 0 atoms>
```

## Actual behavior ##
The original atomgroup is returned

```
>>> u = mda.Universe(crd)
>>> u.atoms[None]
<AtomGroup with 1 atom>
>>> u.atoms[None].names
array([['N', 'H1', 'H2', ..., 'CL', 'CL', 'CL']], dtype=object)
```

## Code to reproduce the behavior ##

``` python
import MDAnalysis as mda
from MDAnalysis.tests.datafiles import PSF, DCD,  GRO, PDB, TPR, XTC, TRR,  PRMncdf, NCDF

u = mda.Universe(PSF, DCD)
u.atoms[None].names
#array([['N', 'HT1', 'HT2', ..., 'C', 'OT1', 'OT2']], dtype=object)

```

## Current version of MDAnalysis ##

- Which version are you using? (run `python -c "import MDAnalysis as mda; print(mda.__version__)"`) 2.0.0-dev0
- Which version of Python (`python -V`)? 3.8
- Which operating system? OSX

**Comment by IAlibay** [comment]
Mm this is indeed annoying behaviour, although as @richardjgowers points out, this is numpy default behaviour, i.e. passing `None` returns the entire array 😖

**Comment by xiki-tempula** [comment]
@IAlibay well this doesn't explain

```
>>> u.atoms[None]
<AtomGroup with 1 atom>
>>> len(u.atoms[None])
1
```
If the entire array is returned.

**Comment by IAlibay** [comment]
Discussing this off-github with @richardjgowers, looks like the issue might be here?

https://github.com/MDAnalysis/mdanalysis/blob/0de538ea70a88f4107d3101b029d48d1e100b1ff/package/MDAnalysis/core/groups.py#L526

where the default Numpy behaviour is coming back to bite us (i.e. it returns an array of the array of ix, instead of the array of ix). There's probably a clean pythonic way to deal with this, but I can't think of one off the top of my head.

**Comment by jbarnoud** [comment]
In numpy, indexing with `None` is a shortcut for indexing with `numpy.newaxis`. This does not make sense for our groups. I think we should do the same as regular lists and raise a `TypeError`, even if it comes with an explicit test for `None`.

**Comment by zemanj** [comment]
> In numpy, indexing with `None` is a shortcut for indexing with `numpy.newaxis`.

In fact, `numpy.newaxis` **is** `None`. So testing for `None` and raising an exception would definitely defeat using `numpy.newaxis`. Don't get me wrong, I don't see why using `numpy.newaxis` for indexing `AtomGroup`s would be useful.
I'm all in favor of changing the behavior in one or the other way.

**Comment by IAlibay** [comment]
Sure `TypeError` sounds good to me :)

**Comment by jbarnoud** [comment]
> In fact, `numpy.newaxis` **is** `None`.

Indeed. My point was that `None` creates a new axis which makes no sense for a group in mda. So I think we agree.
