### ISSUE TITLE
Selecting 'protein' by atoms.select_atoms

### ISSUE THREAD

**Issue by Multi-Kocky** [MDAnalysis/mdanalysis#3100]
Hi, When I tried to calculate RMSD, I should select protein first. In my trajectory, there are several same proteins, I only want to select one protein in the system. I've tried `select_atoms('protein')` and `select_atoms('resid 2:9')`, they all selected all proteins.

When I checked the residues by `list(u.residues)`, the outcome is like below, so the residues number (2-9) are iterative until listed all the residues of protein.
`[<Residue PHE, 2>,
 <Residue CYS, 3>,
 <Residue PHE, 4>,
 <Residue TRP, 5>,
 <Residue LYS, 6>,
 <Residue THR, 7>,
 <Residue CYS, 8>,
 <Residue THR, 9>,
 <Residue PHE, 2>,
 <Residue CYS, 3>,
 <Residue PHE, 4>,
 <Residue TRP, 5>,
 <Residue LYS, 6>,
 <Residue THR, 7>,
 <Residue CYS, 8>,
 <Residue THR, 9>...`

I'm wondering if there are any methods can select first top 8 residues, so that it will select only one protein.

Thank you!

**Comment by jbarnoud** [comment]
Hi @Multi-Kocky,

Please use the mailing list for usage questions: <https://groups.google.com/group/mdnalysis-discussion>. We try to keep the issue board for issues we have to fix.

Regarding your question, there are different ways of solving your problem. I would go for indexing over residues, something in the vein of `universe.select_atoms('protein').residues[1:8].atoms`.

**Comment by Multi-Kocky** [comment]
> Hi @Multi-Kocky,
> 
> Please use the mailing list for usage questions: https://groups.google.com/group/mdnalysis-discussion. We try to keep the issue board for issues we have to fix.
> 
> Regarding your question, there are different ways of solving your problem. I would go for indexing over residues, something in the vein of `universe.select_atoms('protein').residues[1:8].atoms`.

Sorry for that and thanks for your solution.
