### ISSUE TITLE
python_requires not working?

### ISSUE THREAD

**Issue by IAlibay** [MDAnalysis/mdanalysis#3103]
We are currently testing the release of 1.0.1 on testpypi (https://test.pypi.org/project/MDAnalysis/1.0.2/ please ignore the 1.0.2 tag, we originally uploaded 1.0.1 but that was broken so we've had to bump up the version number).

Currently `setup.py` on master has the following:
https://github.com/MDAnalysis/mdanalysis/blob/658a73d127716c6e1f5d4bcfd6dd5b12ecf71cef/package/setup.py#L629

My understanding is that this should not allow py3.5 to get installed (although I think technically we are meant to still support 3.5 in 1.0.x?). However, for some reason it's still possible for me to pip install it from a py3.5.6 environment.

Any ideas @MDAnalysis/coredevs ?

**Comment by tylerjereddy** [comment]
Hey, can you try using wildcards on those exclusions, like `!=3.5.*`

I think it may be the PEP440 version specifiers in use: https://www.python.org/dev/peps/pep-0440/#version-specifiers

**Comment by IAlibay** [comment]
Thanks @tylerjereddy! At least locally this fixes a `pip install -e .` call.

**Comment by IAlibay** [comment]
Technically fixed in #3104 but further setup issues (apparently linked to `python_requires`) have appeared in #3110

**Comment by IAlibay** [comment]
This has been fixed however I'm keeping it open because there's a typo in the string:

https://github.com/MDAnalysis/mdanalysis/blob/bc95e31af1bd1a583161318ab381d005452d48ea/package/setup.py#L629

Also @orbeckst from the history it looks like you added this line in `master`, do we want to also have this in `develop`? It looks like a cleaner solution than the current `sys.version_info` check under develop (not sure if it's as strict though)?

**Comment by IAlibay** [comment]
Closing as fixed in `master` with #3139. We should discuss about porting this over to `develop` for 2.0 eventually though.
