### ISSUE TITLE
no conda package for 1.0.0 Python 2.7 

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/mdanalysis#3105]
## Expected behavior ##

Our docs say "install with conda" and "python 2.7 supported in 1.x" so **I expect to be able to install a Python 2.7 1.0.x with conda.**

Note that there is value in having a Python 2.7 version as this is a useable language frozen in time and thus ideal for scientific computing (I think Konrad Hinsen mentioned this somewhere in his blog or on twitter... can't find the reference)

**Note**: IIRC we had decided that Python 2.7 would not be supported under Windows so the above only applies to Linux and macOS. We should have a table that states which MDA release is supported on which OS/python version. Maybe this could be autogenerated from the metadata in setup.py + some manual editing

## Actual behavior ##

The last conda-installable release for python 2.7 is 0.20.1

## Code to reproduce the behavior ##

```bash
conda create -c conda-forge -n mda27 python=2.7 mdanalysis mdanalysistest
conda list -n mda27 mdanalysis
```
gives
```
# packages in environment at ~/anaconda3/envs/mda27:
#
# Name                    Version                   Build  Channel
mdanalysis                0.20.1           py27h4a8c4bd_0    conda-forge
mdanalysistests           0.20.1                   py27_0    conda-forge
```

The relevant conda packages for 1.0 do not exist in https://anaconda.org/conda-forge/mdanalysis/files?version=1.0.0

## Current version of MDAnalysis ##

- Which version are you using? 1.0.0 (desired)
- Which version of Python (`python -V`)? 2.7
- Which operating system? macOS Catalina (but will apply to Linux, too)

**Comment by IAlibay** [comment]
😩 this would explain some of the user errors that got reported over the last few months.

Assuming we can fix all the py2.7 & py3.5 issues and release 1.0.1 do we want to also do a 1.0 py2.7 release or skip it?

**Comment by orbeckst** [comment]
Skip 1.0... if we can get 1.0.1 out as conda py 2.7 I am more than happy.

This is probably a conda-forge issue in that the package does not get built.

**Comment by IAlibay** [comment]
It doesn't look like conda-forge supports 2.7 or 3.5 releases, so we might have to make this PyPI only unfortunately. Maybe someone with more experience in the @MDAnalysis/coredevs knows better here?

**Comment by richardjgowers** [comment]
I think we can specially request one, we can do that for .2

**Comment by IAlibay** [comment]
Update: we currently don't have py2.7 or py3.5 conda packages for 1.1.1. If we want them we'll need someone to do look into how to force conda-forge to generate them (I can't find anything in the docs for it).

**Comment by IAlibay** [comment]
@orbeckst now that we've fully moved out of py2.7, is this still something you want to achieve historically? I think we're at a point where architecture just doesn't support 2.7 anymore. Close or keep open?

**Comment by orbeckst** [comment]
please close it!
