### ISSUE TITLE
Transformations example

### ISSUE THREAD

**Issue by ksy141** [MDAnalysis/mdanalysis#3107]
Hello, this is not a bug (the code itself works well), however, I think the documentation of transformations needs some updates. The documentation on this website (https://docs.mdanalysis.org/1.0.0/documentation_pages/transformations/rotate.html) provides the following example. 

>>> ts = u.trajectory.ts
>>> angle = 90
>>> ag = u.atoms()
>>> d = [0,0,1]
>>> rotated = MDAnalysis.transformations.rotate(angle, direction=d, ag=ag)(ts)

If I follow this example, I receive two errors. The suggested changes are:
1) u.atoms() --> u.atoms
TypeError: 'AtomGroup' object is not callable

2) MDAnalysis.transformations.rotate 
I think it should be something like ...
>>> from MDAnalysis.transformations.rotate import rotateby
>>> rotated = rotateby(angle, direction=d, ag=ag)(ts)

Thanks!
Best,
Siyoung

python 3.8.5 / MDAnalysis 1.0.0 / MacOS

**Comment by IAlibay** [comment]
Thanks for the report @ksy141 

This is already fixed in the docs for our current v2.0 development version. Due to the way docs work we can't retroactively fix docs after a release has been made.

It seems like we forgot to port it back to v1.0.1 but we're already in a pseudo code freeze due to the upcoming release. I'll see if we can sneak the change in anyways.

**Comment by ksy141** [comment]
Thank you, @IAlibay! Do you have a timeline for releasing MDAnalysis v2.0 and publishing its accompanying paper?

**Comment by IAlibay** [comment]
Unfortunately not :( I very much hope it'll be "this year" for both. The upcoming paper probably won't be 2.0 specific but rather 1.0+. The original aim was to release v2.0 in 2020, but given the current situation, progress on everything is slow.

**Comment by ksy141** [comment]
Thank you, @IAlibay. Looking forward to v2.0 and a "complete self-contained paper".

**Comment by IAlibay** [comment]
I'm going to re-open this and put it as a milestone for 1.0.2 so we don't forget to backport the fix.

**Comment by IAlibay** [comment]
Closed via commit by @lilyminium
