### ISSUE TITLE
nearest image convention not properly calculated

### ISSUE THREAD

**Issue by poojitharamachandra** [MDAnalysis/mdanalysis#3112]
HI,

i am using 
MDAnalysis.lib.distances.distance_array(positions,positions,box=(l,l,l,0,0,0))

l=20.1 (nm)

but the results look like this

 [[[ 0.         13.6231144  17.83480742 ... 17.70136915 14.06992827
    15.3524243 ]
   [13.6231144   0.          6.61980563 ...  7.7938563  12.32506303
     4.86189317]
   [17.83480742  6.61980563  0.         ...  1.94133922 12.51396951
     2.514811  ]
   ...
   [17.70136915  7.7938563   1.94133922 ...  0.         12.64458525
     3.18566019]
   [14.06992827 12.32506303 12.51396951 ... 12.64458525  0.
    10.95942417]
   [15.3524243   4.86189317  2.514811   ...  3.18566019 10.95942417
     0.        ]]
   [ 3.29959492 10.93963627  4.33400872 ...  0.          5.6312794
    15.57785516]
   [ 5.69004236 14.0949911   8.32622612 ...  5.6312794   0.
    15.9222739 ]
   [12.71880624 18.4785511  14.20266531 ... 15.57785516 15.9222739
     0.        ]]

the distances should not exceed 17.4 (10.05*sqrt(3))
should i give any special argument here?

**Comment by lilyminium** [comment]
What kind of distances do you get if you use a cell with 90 degree angles (i.e. ``box=(l, l, l, 90, 90, 90)``)? It may be that the distance function doesn't know how to handle a box with angles of 0 degrees.

**Comment by poojitharamachandra** [comment]
what are these angles ?

**Comment by lilyminium** [comment]
The first three values of the [cell](https://en.wikipedia.org/wiki/Triclinic_crystal_system#/media/File:Triclinic.svg) `box` are the lengths of each side (x, y, z). The last three digits of the `box` are the angles of the cell (alpha, beta, gamma). If you set the angles to 90 degrees, that makes it cubic.

**Comment by poojitharamachandra** [comment]
thanks.  this solved the issue!

**Comment by poojitharamachandra** [comment]
is there any way, i can calculate the direction also (+-x , +-y, +-z)  along with the distance?

**Comment by orbeckst** [comment]
@poojitharamachandra for general questions, please ask on the mailing list https://groups.google.com/group/mdnalysis-discussion. Thanks.
