### ISSUE TITLE
np.int, np.float etc now deprecated

### ISSUE THREAD

**Issue by lilyminium** [MDAnalysis/mdanalysis#3113]
## Expected behavior ##

Tests pass

## Actual behavior ##

They appear to be failing because numpy 1.20 has deprecated `np.int` and `np.float`.

https://github.com/MDAnalysis/mdanalysis/pull/3013/checks?check_run_id=1810195527#step:10:537

We should switch to the built-in `int`/`float` types, or choose the more precise `np.int32/64` etc.

## Code to reproduce the behavior ##

``` python
import MDAnalysis as mda
from MDAnalysis.tests.datafiles import PSF, DCD,  GRO, PDB, TPR, XTC, TRR,  PRMncdf, NCDF

u = mda.Universe(PSF, DCD)

....

```

## Current version of MDAnalysis ##

- Which version are you using? (run `python -c "import MDAnalysis as mda; print(mda.__version__)"`) develop
- Which version of Python (`python -V`)?
- Which operating system?

**Comment by IAlibay** [comment]
For some reason I thought @tylerjereddy already fixed this.

Quickly grep-ing around, in package looks like it's affecting:
- nsgrid (probably should just change that one to np.intp?)
- maybe some util stuff? I'm assuming by https://numpy.org/devdocs/user/basics.types.html that np.float_ and np.int_ are fine

For testsuite:
- test_helix_analysis (switching to intp is fine there)
-

**Comment by tylerjereddy** [comment]
I think I fixed some of them, hopefully, but I guess a few slipped through. NumPy also accidentally made shuffling all memoryviews a warning, so I may need to release a patched scipy soon because it bricked hausdorff distance.

**Comment by IAlibay** [comment]
> I think I fixed some of them, hopefully, but I guess a few slipped through.
Yeah looks like it was just a couple of minor leftover things :) 

This really is just highlighting the need to re-implement numpy-dev cron CI jobs (#3052), I'll have a look after 1.0.1 hopefully.
