### ISSUE TITLE
Common AnalysisBase framework for storing results

### ISSUE THREAD

**Issue by PicoCentauri** [MDAnalysis/mdanalysis#3115]
I'm working together with @joaomcteixeira to implement a [command line interface](https://github.com/PicoCentauri/mda_cli) for MDAnalysis. Our implementation is mostly finished 🥳. Currently, we are preparing the repo for moving to the mda organization and make it ready for CI, PYPI, Conda, etc. 

However, one important part is still missing. For saving the data a common structure for the results of each analysis class would be helpful. We already started a discussion but since some structural changes to the Analysis Framework and most likely to all analysis classes are necessary I move the discussion.

@orbeckst suggested three possibilities and I will use the rdf class as an example for the API. The current implementation for running and accessing the results looks like 

```python
rdf = InterRDF(ag1, ag2).run()
plt.plot(rdf.bins, rdf.rdf)
```

## 1. Reserved attribute names
For example, `self.results` could always be a data structure containing computed data. This data structure could either be 
a dictionary 

```python
rdf = InterRDF(ag1, ag2).run()
plt.plot(rdf.results["bins"], rdf.results["rdf"])
```

or attributes

```python
rdf = InterRDF(ag1, ag2).run()
plt.plot(rdf.results.bins, rdf.results.rdf)
```

## 2. Trailing underscore attributes (like sklearn-style)
In scikit-learn, computed variables get an underscore affixed (e.g. `.results_`).

```python
rdf = InterRDF(ag1, ag2).run()
plt.plot(rdf.bins_, rdf.rdf_)
```

## 3. Flexible annotation
A dictionary containing a list of attributes for computed data. This dictionary could look like

```python
self._annotation = {'bins': 'OUTPUT', 'rdf': 'OUTPUT',}
```
 
Here, `OUTPUT` could mark anything that is always computed after `run()` and should be saved. Possible other tags such as "OPTIONAL" for something that might be computed by an auxiliary method. With this approach only a few changes to the classes themselves are necessary. Their python api stays untouched as shown above.

---

My favorite is the first approach using attributes. It combines all results into a structure common for all classes. For me as a user this also handy. I can quickly access all results without always checking the documentation for the correct name.

Regardless of the method we choose, the MDACLI will find 'results' attributes and save them. If a numpy array, we could use `np.save()` to CSV, if it's a `pd.DataFrame`, we use `to_csv()`...

If you have better ideas we are of course open for discussion.

**Comment by joaomcteixeira** [comment]
Great post @PicoCentauri ,

Thanks for summarizing it so well.

For reference, the issue that seeded this project is https://github.com/MDAnalysis/mdanalysis/issues/2377

I like the `.results` attribute. `results` can be a `dict` or even a dedicated `class` that can provide a general API to save the results. Feels natural also to iterate over its `items()`.

**Comment by PicoCentauri** [comment]
Is there any opinion on the draft? Maybe from the @MDAnalysis/coredevs. 

If we decide for a strategy we can push the `CLI` closer to a first working version. Thanks again for looking at this issue.

**Comment by orbeckst** [comment]
Did you survey the existing classes? How many do use `results`? More importantly, how many use `results` in a way that's not compatible with the above suggestion **1**? For example, for RDF `results` should be a dict storing bins and rdf values but actually store the rdf (I think that's _not_ true for RDF but for e.g., RMSD or RMSF, where the independent variable is something like `times` or `resids`). In this case, user code will break when you change the meaning of an existing attribute.

This might be a moot point if you decide that you are directly going for MDAnalysis 2.0.0 where we can make breaking changes more easily although even then we should limit breaking user code. *If you will break user code you must put a deprecation note into 1.1.0* (see #3159 )!

Therefore, it would be easier to use a different attribute name or to use the annotation approach **3**. (I really dislike the underscore approach, which also does not give you a nice way to collect the attributes... I don't consider introspecting and pattern matching attribute names particularly "nice"... but that's my very personal opinion).

**Comment by lilyminium** [comment]
I also like the `results` attribute. results could contain all the output of `run()`, adding to the class rather than replacing an existing attribute. This would be especially relevant for classes like PCA, where both the eigenvectors and eigenvalues are important.

iirc at least 2 classes use `results` -- I think `encore` may be one. None use `output` as an attribute, I believe.

**Comment by PicoCentauri** [comment]
Thanks for your feedback. I did a little investigation of the existing analysis classes. An existing `results` attribute is used by three classes (`GNMAnalysis`, `LinearDensity`, `PersistenceLength`) as well by the `AnalysisFromFunction` base class.

_In brief, we can use a `results` attribute with acceptable(?) breaking changes in the `GNMAnalysis` and the `LinearDensity` class._

# Detailed Analysis

## `GNMAnalysis` 

results are stored as a list
https://github.com/MDAnalysis/mdanalysis/blob/6282385644d672cf7023584347e35048935ab429/package/MDAnalysis/analysis/gnm.py#L271

## `LinearDensity` 

creates a nested dictionary
https://github.com/MDAnalysis/mdanalysis/blob/6282385644d672cf7023584347e35048935ab429/package/MDAnalysis/analysis/lineardensity.py#L100

where for each dimension several values are stored
https://github.com/MDAnalysis/mdanalysis/blob/6282385644d672cf7023584347e35048935ab429/package/MDAnalysis/analysis/lineardensity.py#L112

## `PersistenceLength`

Creates a 1D array 

https://github.com/MDAnalysis/mdanalysis/blob/6282385644d672cf7023584347e35048935ab429/package/MDAnalysis/analysis/polymer.py#L202

## `AnalysisFromFunction`

Stores the return values of the function inside a list of the `results` attribute

https://github.com/MDAnalysis/mdanalysis/blob/6282385644d672cf7023584347e35048935ab429/package/MDAnalysis/analysis/base.py#L267

Besides these ones, I didn't found any class that is using `results` as an attribute. To use `results` some (breaking) changes are necessary in the `GNMAnalysis ` (`list` to `dict` with a key for each list element) and in `LinearDensity` (nested dict to flat dict with `pos` -> `pos_x` for example). The `PersistenceLength` works directly and the `AnalysisFromFunction` is not affected at all.

We could also use `output` as a key attribute as @lilyminium suggested. I didn't found any class that is using `output`. However, attributes like `output` and `results` could confuse users and lead to duplicated code. I would stick with results if somehow possible.

**Comment by joaomcteixeira** [comment]
Hi all,
Great analysis @PicoCentauri 

I believe there won't be any incompatibility with `results`. For `GNMAnalysis` and `LinearDensity` we can create a `results` `@property.getter` that converts the `list` to `dict` (maybe using `dict.fromkeys`) or flats the nested dict.

In conclusion, for those classes which results are not a dictionary, a `@property` method can be used as a parser to convert the native result structures to a `dict`. That could be also a requirement when writing future analysis classes.

What do you think?

**Comment by orbeckst** [comment]
Thanks for the analysis, @PicoCentauri . This looks as if `results` is viable. 

Then the next steps are
- What incompatible changes do you need to make to existing code?
  -  Any incompatible changes should be _deprecated_ (admittedly, @IAlibay declared a freeze on 1.1.0 so you need to check with him).
  - User Guide examples would need updating 
- Define what `results` is allowed to contain.

If you can make it work without breaking changes (I didn't quite understand where @joaomcteixeira 's property getters would be implemented – in mdacli? ) then you'll have a much easier ride.

**Comment by orbeckst** [comment]
Btw, this discussion is also relevant for the idea that's been floated on Discord to spin out analysis into "mdkits" that can be maintained separately. Ultimately, each analysis would still appear as if it lived under MDAnalysis.analysis so nothing would immediately change for mdacli.

**Comment by IAlibay** [comment]
> Any incompatible changes should be deprecated (admittedly, @IAlibay declared a freeze on 1.1.0 so you need to check with him).

I'd very much appreciate it if we didn't have any new features. That being said we're unlikely to be moving towards a release until after the end of the month, plus there's a few things that need doing. If it's a simple warning that can go through quick review I think we can live with that.

**Comment by PicoCentauri** [comment]
Thanks for your comments! 

I'm also not really getting your idea @joaomcteixeira... :(. I would also suggest that we implement tiny breaking changes in `LinearDensity`, `GNMAnalysis` and `PersistenceLength` to have a consistent `results` attribute in all analysis classes. What do you think?

I can file a PR on Sunday/Monday implementing a warning for the three classes, @IAlibay. The PR will only contain a statement that the structure of the results attribute will change for the 2.0 release.

**Comment by joaomcteixeira** [comment]
My point was just that we could make the `results` attribute to be a `@property` with its proper getter and setter where the getter could be a parser to convert from the internal format of the analysis class to the common format we decide upon. The `@property.getter` parser could accommodate and solve situations such as you described @PicoCentauri (I believe):

> Besides these ones, I didn't found any class that is using results as an attribute. To use results some (breaking) changes are necessary in the GNMAnalysis (list to dict with a key for each list element) and in LinearDensity (nested dict to flat dict with pos -> pos_x for example). The PersistenceLength works directly and the AnalysisFromFunction is not affected at all.

If `v1.1.0` will be the last of `v1` so we can perfectly think under the frame of `v2` already.

Thanks, everyone, and sorry for my late replies.

**Comment by orbeckst** [comment]
@PicoCentauri @joaomcteixeira is PR #3233 the only open mdacli PR that has to go into 2.0.0 or is there anything else?

This Friday is the hard deadline set by @IAlibay .

**Comment by PicoCentauri** [comment]
Yes PR #3233 is the only piece of code we need for finishing the CLI 🎉. 

However, for the beginning we can only support the three classes (`GNMAnalysis`, `LinearDensity`, `PersistenceLength`) that we switch to the new `results` attribute. For the time after 2.0.0 I suggest that every time an analysis class is touched we start storing the results into the new attribute and throw a deprecation if the old attributes are accessed. I create an issue once PR #3233 is merged and 2.0.0 is out.

**Comment by IAlibay** [comment]
Ideally, especially for the purposes of the upcoming workshop, we should try to move things to using `results` before the 2.0 merge (especially given that the 1.1.1 warning messages mentioned that all the AnalysisBase derived classes would change...).
If we can get #3233 merged by the end of the day tomorrow, I'm going to make some space in my calendar and try to modify at the very least the high use analysis classes Friday/Saturday.

**Comment by PicoCentauri** [comment]
Wow, nice @IAlibay! I also have some time on the weekend and can help you. Maybe we prepare a list of the analysis classes that definitely need to be adjusted. When this list is ready we can split the classes. Do you want to deprecate the old attributes with something like

```python
@property
def example_result(self):
    warnings.warn("old_results is deprecated and will be removed in the future.")
    return self.results.example_result
```

or just remove them?

**Comment by IAlibay** [comment]
> Wow, nice @IAlibay! I also have some time on the weekend and can help you. Maybe we prepare a list of the analysis classes that definitely need to be adjusted. When this list is ready we can split the classes. Do you want to deprecate the old attributes with something like
> 
> ```python
> @property
> def example_result(self):
>     warnings.warn("old_results is deprecated and will be removed in the future.")
>     return self.results.example_result
> ```
> 
> or just remove them?

@PicoCentauri Ah maybe I'm misremembering last month, didn't we deprecate them all in 1.1.1?

If not, then yeah I guess that'd be the easiest way to do it. We do have a deprecation decorator somewhere I think.

Just having a quick look through, the following should be relatively easy to get done; contacts, density, dihedral, msd, rmsd/rmsf (depending on which bits need storing).

I've not been really keeping up with the #3233 that much, so I'm kinda guessing on the amount of work required. It looks like it's near merging anyways, so if it goes through this evening then I can have a play with it tonight and see how feasible this really is.

**Comment by PicoCentauri** [comment]
> @PicoCentauri Ah maybe I'm misremembering last month, didn't we deprecate them all in 1.1.1?

No we just [deprecate](https://github.com/MDAnalysis/mdanalysis/commit/de8933ad6cdb01ec13f328e80c7589cd0c968c0c) the four I mentioned above. These have to change because they already use a `results` attribute. All the classes still could live with the new and the old syntax for a while.

> Just having a quick look through, the following should be relatively easy to get done; contacts, density, dihedral, msd, rmsd/rmsf (depending on which bits need storing).

Cool, this should be done until the end of the weekend.

> I've not been really keeping up with the #3233 that much, so I'm kinda guessing on the amount of work required. It looks like it's near merging anyways, so if it goes through this evening then I can have a play with it tonight and see how feasible this really is.

(Hopefully,) we designed the `Results` class that the effort is not that high. If merged I can quickly create an example for one class.

**Comment by orbeckst** [comment]
> All the classes still could live with the new and the old syntax for a while.

When we had the discussion about how to move forward, we didn't want to break all of Analysis so we were looking for a way for old and new to co-exist for a while. In hindsight, we could have made a more radical cut but with 1.1.1 out, that's water under the bridge. 

So under semver, 2.x will have `.results` in addition to the old accessors. We can make the old accessors managed attributes that access elements in `.results`. A bit clunky but transparent and no data duplication and we can decorate them with warnings.
