### ISSUE TITLE
align.fasta2select ERROR (UnboundLocalError: local variable 'GAP' referenced before assignment)

### ISSUE THREAD

**Issue by cagfa1** [MDAnalysis/mdanalysis#3124]
## Expected behavior ##

I want to align a 'mobile' pdb structure onto a 'reference' pdb structure in order to calculate RMSD values. The align_proteins function should output a .pdb file of the 'mobile' structure after alignment. 

## Actual behavior ##

The align_proteins code uses MDAnalysis.align.fasta2select function but returns the error "UnboundLocalError: local variable 'GAP' referenced before assignment".

    UnboundLocalError                         Traceback (most recent call last)
    <ipython-input-8-e986b2065e42> in <module>
          1 reference = '5S8S.pdb' #https://www.rcsb.org/structure/5S8S
          2 mobile = '5S8R.pdb' #https://www.rcsb.org/structure/5S8R
    ----> 3 align_proteins(reference, mobile)
    
    <ipython-input-6-a0388a994ae0> in align_proteins(reference, mobile)
         41     reference_resids = [a.resid for a in reference.select_atoms('protein').select_atoms('name CA and not altloc B')]
         42     mobile_resids = [a.resid for a in mobile.select_atoms('protein').select_atoms('name CA and not altloc B')]
    ---> 43     align_dict = align.fasta2select('alignment.aln', is_aligned=True, ref_resids=reference_resids, target_resids=mobile_resids)
         44 
         45     #selection resulting from align_dict not organized in the same way for the two files:
    
    ~/anaconda3/envs/panda_docking/lib/python3.7/site-packages/MDAnalysis/analysis/align.py in fasta2select(fastafilename, is_aligned, ref_resids, target_resids, ref_offset, target_offset, verbosity, alnfilename, treefilename, clustalw)
       1150     for ipos in range(alignment.get_alignment_length()):
       1151         aligned = list(alignment[:, ipos])
    -> 1152         if GAP in aligned:
       1153             continue  # skip residue
       1154         template = "resid %i"
    
    UnboundLocalError: local variable 'GAP' referenced before assignment

## Code to reproduce the behavior ##

    import os
    import MDAnalysis as mda
    from MDAnalysis.analysis import align, rms
    
    def align_proteins(reference, mobile):

    #here reference will is experimental structure and mobile the docked complex
    reference = mda.Universe(reference).select_atoms('all')
    mobile = mda.Universe(mobile).select_atoms('all')

    # Rename histidine and remove alternative conformation to permit alignment
    for residue_reference in reference.residues:
        if residue_reference.resname in ['HIP', 'HIE', 'HID']:
            residue_reference.resname = 'HIS'

    for residue_mobile in mobile.residues:
        if residue_mobile.resname in ['HIP', 'HIE', 'HID']:
            residue_mobile.resname = 'HIS'

    # #Creats alignment file
    alignment = align.sequence_alignment(mobile.select_atoms('protein and not altloc B'), reference.select_atoms('protein and not altloc B'))
    fasta = '>ref\n{}\n>mobile\n{}'.format(alignment[0], alignment[1])
    file_fasta = open('alignment.aln',"w+")
    file_fasta.write(fasta)
    file_fasta.close()

    # Collection residue numbers and align structures
    reference_resids = [a.resid for a in reference.select_atoms('protein').select_atoms('name CA and not altloc B')]
    mobile_resids = [a.resid for a in mobile.select_atoms('protein').select_atoms('name CA and not altloc B')]
    align_dict = align.fasta2select('alignment.aln', is_aligned=True, ref_resids=reference_resids, target_resids=mobile_resids)

    #Just align on C-alphas
    new_reference_selection =  align_dict['reference'].replace('( backbone or name CB )', 'name CA')
    new_mobile_selection = align_dict['mobile'].replace('( backbone or name CB )', 'name CA');
    new_align_dict = {'mobile': new_mobile_selection, 'reference': new_reference_selection}

    align.alignto(mobile.select_atoms('not altloc B'), reference.select_atoms('not altloc B'), select=new_align_dict)

    mobile.write('mobile_final.pdb')

    return mobile

    reference = '5S8S.pdb'
    mobile = '5S8R.pdb'
    align_proteins(reference, mobile)

- Which version are you using? 1.0.0
- Which version of Python? Python 3.7.9
- Which operating system? Linux OR MacOS 10.14

**Comment by sulays** [comment]
Hi @lilyminium, I am looking at some starter issues to prep for GSoC and would like to work on this issue. 
I think the problem is that the variable `GAP` is assigned inside the for loop if statement scope in `MDAnalysis.align.fasta2select` function. 
```    
for iseq, a in enumerate(alignment):
    # need iseq index to change orig_resids
    if orig_resids[iseq] is None:
        # build default: assume consecutive numbering of all
        # residues in the alignment
        GAP = "-"
        length = len(a.seq) - a.seq.count(GAP)
        orig_resids[iseq] = np.arange(1, length + 1)
    else:
        orig_resids[iseq] = np.asarray(orig_resids[iseq])
```
So if there are no gaps then gap never gets initialized and it gives the `UnboundLocalError` . So the solution will be assigning `GAP` outside the if statement. Is this okay?

**Comment by lilyminium** [comment]
Hi @sulays, welcome to MDAnalysis! That does sound promising -- put up a pull request that links to this issue with your fix and a test, and we will review it. If you need help getting started, please check out the [user guide](https://userguide.mdanalysis.org/stable/index.html), particularly the [Contributing](https://userguide.mdanalysis.org/stable/contributing.html) section and [Contributing code](https://userguide.mdanalysis.org/stable/contributing_code.html) section.

Also, seeing as you are interested in GSOC, we do encourage you to introduce yourself to us on the developer mailing list as early as possible :-) (more info in [this blog post](https://www.mdanalysis.org/2021/03/09/gsoc2021/))

**Comment by sulays** [comment]
Do I need to write a specific test for the changes I make? @lilyminium

**Comment by IAlibay** [comment]
@sulays yep, if this bug was found it means we didn't cover this edge case, so you'll want to have a test that at the very least checks that this is no longer happening.
