### ISSUE TITLE
abspaths slipping into SOURCES and breaking windows conda build

### ISSUE THREAD

**Issue by richardjgowers** [MDAnalysis/mdanalysis#3129]
https://github.com/conda-forge/mdanalysis-feedstock/pull/28

^^ On the 1.0.1 builds Windows is failing because some of the sources in the sdist are given as absolute paths.

This is a good description:

https://github.com/pyFFTW/pyFFTW/pull/250/files

It looks like we started trying to use `abspath` to get RTD to work here:

https://github.com/MDAnalysis/mdanalysis/pull/2749

probably because of our slightly unusual repo structure

**Comment by IAlibay** [comment]
Fixed with #3130
