### ISSUE TITLE
Error in Introductory Example (https://www.mdanalysis.org/pages/basic_example/)

### ISSUE THREAD

**Issue by ajpowelsnl** [MDAnalysis/mdanalysis#3131]
## Expected behavior ##

Hello,

I am trying to make your basic MDAnalysis example (given here -- https://www.mdanalysis.org/pages/basic_example/), work but I am getting some simple matplotlib errors that should be easy to fix / update.

I will be happy to assist in the fix up, but since I do not really know this package, I will defer the the principal maintainers / developers. 

I believe the error can be fixed by simply removing the offending "warn" keyword argument in "matplotlib.use('agg', warn=False)" types of statements.  A simple test suggests as much:

matplotlib.use('agg')

The statement above gives no error.  It would be ideal to use the most recent version of matplotlib with the fix in MDAnalysis. 

Here is my matplotlib version:

matplotlib.__version__

matplotlib.__version__

'3.3.4'

## Actual behavior ##

The second line in the import statements below throws an error with matplotlib, one of its dependencies:

import MDAnalysis
from MDAnalysis.tests.datafiles import PSF, DCD   # test trajectory
import numpy.linalg

## Code to reproduce the behavior ##

#Here is the code:

import MDAnalysis
from MDAnalysis.tests.datafiles import PSF, DCD   # test trajectory
import numpy.linalg

# Here is the resulting stacktrace:

import MDAnalysis

from MDAnalysis.tests.datafiles import PSF, DCD   # test trajectory

import numpy.linalg

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-1-16200c87edb1> in <module>
      1 import MDAnalysis
----> 2 from MDAnalysis.tests.datafiles import PSF, DCD   # test trajectory
      3 import numpy.linalg

/opt/anaconda3/lib/python3.8/site-packages/MDAnalysis/tests/datafiles.py in <module>
     41 
     42 try:
---> 43     from MDAnalysisTests.datafiles import *
     44 except ImportError:
     45     print("*** ERROR ***")

/opt/anaconda3/lib/python3.8/site-packages/MDAnalysisTests/__init__.py in <module>
    124 try:
    125     import matplotlib
--> 126     matplotlib.use('agg', warn=False)
    127 except ImportError:
    128     pass

TypeError: use() got an unexpected keyword argument 'warn'

``` python
import MDAnalysis as mda
from MDAnalysis.tests.datafiles import PSF, DCD,  GRO, PDB, TPR, XTC, TRR,  PRMncdf, NCDF

u = mda.Universe(PSF, DCD)

....

```

## Current version of MDAnalysis ##

- Which version are you using? (run `python -c "import MDAnalysis as mda; print(mda.__version__)"`)

mda.__version__

'1.0.0'

- Which version of Python (`python -V`)?

'3.8.8 | packaged by conda-forge | (default, Feb 20 2021, 16:12:38) \n[Clang 11.0.1 ]'

- Which operating system?

OSX 10.14.6 (OS Mojave)

**Comment by IAlibay** [comment]
Hi @ajpowelsnl this has already been addressed in our development versions but we are still in the process of deploying the bugfix release for it. For more information see: #2938 (including the temporary fix for this).

Since this is a duplicate, I'm going to close this issue, but feel free to re-open if you think there are things that still need addressing.
