### ISSUE TITLE
CI for py2.7 and py3.5 are now consistently failing - master branch

### ISSUE THREAD

**Issue by IAlibay** [MDAnalysis/mdanalysis#3140]
## Expected behavior ##

All CI tests pass

## Actual behavior ##

The CI tests we have running on Travis for 2.7 and 3.5 are now consistently failing: https://travis-ci.com/github/MDAnalysis/mdanalysis/pull_requests

From a quick look I suspect it's a conflict (there's a few cases of netcdf4 being mentioned).

We probably need to get these fixed so we can validate 1.0.2.

**Comment by richardjgowers** [comment]
Tbh drop them from the CI matrix and we can test them manually for the .2 release.

**Comment by IAlibay** [comment]
I did get 3.5 to work again, but yeah fair, 2.7 is being really difficult.

**Comment by lilyminium** [comment]
Closed by #3143
