### ISSUE TITLE
RDKitParser cannot create Universe from empty ROMol

### ISSUE THREAD

**Issue by lilyminium** [MDAnalysis/mdanalysis#3142]
## Expected behavior ##

A Universe created from an ROMol with no atoms gives a Universe with no atoms.

## Actual behavior ##

The parser assumes there's at least one atom (which would be the vast majority of cases).
```
        # check if multiple charges present
>       atom = mol.GetAtomWithIdx(0)
E       RuntimeError: Pre-condition Violation
E       	no atoms
E       	Violation occurred on line 182 in file Code/GraphMol/ROMol.cpp
E       	Failed Expression: getNumAtoms() > 0
E       	RDKIT: 2020.09.1
E       	BOOST: 1_72
```

## Code to reproduce the behavior ##

``` python
>>> from rdkit import Chem
>>> import MDAnalysis as mda
>>> mol = Chem.Mol()
>>> mol.GetNumAtoms()
0
>>> u = mda.Universe(mol, format="RDKIT")
[11:47:28]

****
Pre-condition Violation
no atoms
Violation occurred on line 182 in file /Users/runner/miniforge3/conda-bld/rdkit_1606302405544/work/Code/GraphMol/ROMol.cpp
Failed Expression: getNumAtoms() > 0
****

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "mdanalysis/package/MDAnalysis/core/universe.py", line 334, in __init__
    topology = _topology_from_file_like(self.filename,
  File "mdanalysis/package/MDAnalysis/core/universe.py", line 120, in _topology_from_file_like
    topology = p.parse(**kwargs)
  File "mdanalysis/package/MDAnalysis/topology/RDKitParser.py", line 181, in parse
    atom = mol.GetAtomWithIdx(0)
RuntimeError: Pre-condition Violation
	no atoms
	Violation occurred on line 182 in file Code/GraphMol/ROMol.cpp
	Failed Expression: getNumAtoms() > 0
	RDKIT: 2020.09.1
	BOOST: 1_72
```

## Current version of MDAnalysis ##

- Which version are you using? (run `python -c "import MDAnalysis as mda; print(mda.__version__)"`) current develop
- Which version of Python (`python -V`)? 3.8.4
- Which operating system? MacOS

**Comment by lilyminium** [comment]
@cbouy you could add this to your latest PR if you like, it's a quick check or try/except.

**Comment by IAlibay** [comment]
Thanks for the quick reply here @cbouy :) (I swear I'll get to reviewing your PRs ASAP [current list is 1.0.2 -> RDKIT stuff -> 2.0 (we got a 2 month deadline for 2.0, so hopefully deadlines are going to push us to review faster 😅 )]

**Comment by lilyminium** [comment]
Thanks @mehulmj! If you put up a pull request and link this issue, it will get reviewed. If you need help getting started, please check out the [user guide](https://userguide.mdanalysis.org/stable/index.html), particularly the [Contributing](https://userguide.mdanalysis.org/stable/contributing.html) section and [Contributing code](https://userguide.mdanalysis.org/stable/contributing_code.html) section.

**Comment by aditya-kamath** [comment]
If @mehulmj wants to take this up that's great! Although, I can take a look at it if it's just a try/except..

**Comment by IAlibay** [comment]
> If @mehulmj wants to take this up that's great! Although, I can take a look at it if it's just a try/except..

@aditya-kamath in the interest of making sure we don't get multiple PRs for a single issue & also having adequate numbers of gsoc-starter issues, I would suggest letting @mehulmj having a first go at it. Should a PR not happen within a reasonable amount of time (maybe couple of days to a week depending on how many GSOC students appear looking for issues), then it's ok for others to open PRs on the issue.

I realise that both your current PRs seem to be waiting on mentor responses, so in this case I can understand you looking to do more whilst waiting. Given that you have fixed a few smaller issues, might I suggest looking for a bigger thing to fix? In the interest of helping MDA achieve its 2.0 goals, maybe picking up one of the writers to upgrade tests for in #516 or maybe one of the base classes in #919 ?

**Comment by aditya-kamath** [comment]
Sounds good! I'll take up one of those instead!
