### ISSUE TITLE
DensityAnalysis user defined grid coordinates are silently ignored if a grid centre is not provided. 

### ISSUE THREAD

**Issue by hmacdope** [MDAnalysis/mdanalysis#3148]
## Expected behavior ##
If grid dimensions (`xdim, ydim, zdim`) are provided to `DensityAnalysis` but a grid centre (`gridcenter`) is not set,the user should receive an exception or warning that the grid dimensions are being ignored. This is noted in the docs, but a warning should probably be issued. 

## Actual behavior ##

If grid dimensions (`xdim, ydim, zdim`) are provided to `DensityAnalysis` but a grid centre (`gridcenter`) is not set, the grid dimensions are silently ignored. 

## Code to reproduce the behavior ##

``` python
import MDAnalysis as mda
from MDAnalysis.tests.datafiles import TPR, XTC
from MDAnalysis.analysis import density

u = mda.Universe(TPR, XTC)
ow = u.select_atoms("name OW")
D = density.DensityAnalysis(ow, xdim=1.0,ydim=1.0,zdim=1.0)
D.run()
print(D.density.edges)

....

```

## Current version of MDAnalysis ##

- Which version are you using? (run `python -c "import MDAnalysis as mda; print(mda.__version__)"`)
- 2.0.0-dev0
- Which version of Python (`python -V`)?
-3.7.5
- Which operating system?
-Ubuntu 19.10 (Eoan Ermine)

**Comment by avitomar12** [comment]
Hey @hmacdope I would like work on the issue.

**Comment by IAlibay** [comment]
@avitomar12 please do go ahead and raise a PR.

**Comment by biogen98** [comment]
Hey @avitomar12, sorry I just saw you comment when making the pull request. 
I started working on the issue this morning and I was not aware that I should let this know.

**Comment by avitomar12** [comment]
@biogen98 Have you resolved the issue or something is missing?

**Comment by biogen98** [comment]
@avitomar12 The issue is now resolved. Apologies again for the inconvenience.
