### ISSUE TITLE
NCDFReader cannot get dt for single frame trajectories

### ISSUE THREAD

**Issue by wuchiz** [MDAnalysis/mdanalysis#3166]
## Expected behavior ##

I want to load mutiple netcdf trajectories files using
mda.Universe('cba_wat.prmtop',['1.forw.nc','2.forw.nc']

## Actual behavior ##
It report error when there is a nc file only including single frame. And it succeds when all the nc files all have more than one frames.

error is listed as follow
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-3-3715b2a4ac01> in <module>
----> 1 data = mda.Universe('../../../cba_wat.prmtop',['1.forw.nc','2.forw.nc'])

~/anaconda3/envs/pytorch/lib/python3.8/site-packages/MDAnalysis/core/universe.py in __init__(self, *args, **kwargs)
    387 
    388         if coordinates:
--> 389             self.load_new(coordinates, format=format, in_memory=in_memory,
    390                         in_memory_step=in_memory_step, **kwargs)
    391 

~/anaconda3/envs/pytorch/lib/python3.8/site-packages/MDAnalysis/core/universe.py in load_new(self, filename, format, in_memory, in_memory_step, **kwargs)
    580         kwargs['n_atoms'] = self.atoms.n_atoms
    581 
--> 582         self.trajectory = reader(filename, format=format, **kwargs)
    583         if self.trajectory.n_atoms != len(self.atoms):
    584             raise ValueError("The topology and {form} trajectory files don't"

~/anaconda3/envs/pytorch/lib/python3.8/site-packages/MDAnalysis/coordinates/chain.py in __init__(self, filenames, skip, dt, continuous, **kwargs)
    290 
    291         self.n_frames = np.sum(n_frames)
--> 292         self.dts = np.array(self._get('dt'))
    293         self.total_times = self.dts * n_frames
    294 

~/anaconda3/envs/pytorch/lib/python3.8/site-packages/MDAnalysis/coordinates/chain.py in _get(self, attr)
    499     def _get(self, attr):
    500         """Get value of `attr` for all readers."""
--> 501         return [reader.__getattribute__(attr) for reader in self.readers]
    502 
    503     def _get_same(self, attr):

~/anaconda3/envs/pytorch/lib/python3.8/site-packages/MDAnalysis/coordinates/chain.py in <listcomp>(.0)
    499     def _get(self, attr):
    500         """Get value of `attr` for all readers."""
--> 501         return [reader.__getattribute__(attr) for reader in self.readers]
    502 
    503     def _get_same(self, attr):

~/anaconda3/envs/pytorch/lib/python3.8/site-packages/MDAnalysis/coordinates/base.py in dt(self)
   1471     def dt(self):
   1472         """Time between two trajectory frames in picoseconds."""
-> 1473         return self.ts.dt
   1474 
   1475     @property

~/anaconda3/envs/pytorch/lib/python3.8/site-packages/MDAnalysis/coordinates/base.py in dt(self)
    859             pass
    860         try:
--> 861             dt = self.data['dt'] = self._reader()._get_dt()
    862             return dt
    863         except AttributeError:

~/anaconda3/envs/pytorch/lib/python3.8/site-packages/MDAnalysis/coordinates/TRJ.py in _get_dt(self)
    698 
    699     def _get_dt(self):
--> 700         t1 = self.trjfile.variables['time'][1]
    701         t0 = self.trjfile.variables['time'][0]
    702         return t1 - t0

~/anaconda3/envs/pytorch/lib/python3.8/site-packages/scipy/io/netcdf.py in __getitem__(self, index)
    966     def __getitem__(self, index):
    967         if not self.maskandscale:
--> 968             return self.data[index]
    969 
    970         data = self.data[index].copy()

IndexError: index 1 is out of bounds for axis 0 with size 1

## Code to reproduce the behavior ##

``` python
import MDAnalysis as mda
from MDAnalysis.tests.datafiles import PSF, DCD,  GRO, PDB, TPR, XTC, TRR,  PRMncdf, NCDF

u = mda.Universe(PSF, DCD)

....

```

## Current version of MDAnalysis ##
1.0.1
- Which version are you using? (run `python -c "import MDAnalysis as mda; print(mda.__version__)"`)
 Which version of Python (`python -V`)?
- Which operating system?

**Comment by IAlibay** [comment]
@wuchiz if you open the single frame trajectory on its own, does it open properly?

**Comment by IAlibay** [comment]
Can confirm this is reproducible. Here is some code to reproduce this behaviour:

```python
import MDAnalysis as mda
from MDAnalysisTests.datafiles import PFncdf_Top, PFncdf_Trj

u = mda.Universe(PFncdf_Top, PFncdf_Trj)
u.atoms.write('oneframe.ncdf')

u2 = mda.Universe(PFncdf_Top, [PFncdf_Trj, 'oneframe.ncdf'])
```

Switching the position of the one frame netcdf still leads to the error, but reading it alone isn't an issue.

**Comment by wuchiz** [comment]
> @wuchiz if you open the single frame trajectory on its own, does it open properly?
> 
> Also can you confirm how these files were generated? (i.e. through one of AMBER's MD engines?)

I can open the single frame trajectory properly
so you mean i must place the one frame file in the end of the list?

**Comment by wuchiz** [comment]
> @wuchiz if you open the single frame trajectory on its own, does it open properly?
> 
> Also can you confirm how these files were generated? (i.e. through one of AMBER's MD engines?)

I can open the single frame trajectory properly
so you mean i must place the one frame file in the end of the list?

**Comment by wuchiz** [comment]
> @wuchiz if you open the single frame trajectory on its own, does it open properly?
> 
> Also can you confirm how these files were generated? (i.e. through one of AMBER's MD engines?)

I can open the single frame trajectory properly
so you mean i must place the one frame file in the end of the list?

**Comment by wuchiz** [comment]
I can open a single frame file properly. Just can't open mutiple files

**Comment by IAlibay** [comment]
> so you mean i must place the one frame file in the end of the list?
No, sorry in my previous comment (https://github.com/MDAnalysis/mdanalysis/issues/3166#issuecomment-799076733) I was pointing out that it doesn't matter what order you pass it, it will still fail.

The issue is essentially down to the fact that `_get_dt` fails for single frame trajectories.
Probably the easiest way to fix this is just to put a try/except in there and return the 1 ps default value.
Also worth noting here whilst I'm looking at `_get_dt`, the default for the TRZ reader when failing to get dt is different from the default in `base`.

**Comment by wuchiz** [comment]
> Can confirm this is reproducible. Here is some code to reproduce this behaviour:
> 
> ```python
> import MDAnalysis as mda
> from MDAnalysisTests.datafiles import PFncdf_Top, PFncdf_Trj
> 
> u = mda.Universe(PFncdf_Top, PFncdf_Trj)
> u.atoms.write('oneframe.ncdf')
> 
> u2 = mda.Universe(PFncdf_Top, [PFncdf_Trj, 'oneframe.ncdf'])
> ```
> 
> Switching the position of the one frame netcdf still leads to the error, but reading it alone isn't an issue.

But have many nc files. most of them have a single frame. so how can i solve it?

**Comment by IAlibay** [comment]
@wuchiz I'm not sure of the circumstances, but we're getting multiple repeated messages from you. Is this intentional?

**Comment by wuchiz** [comment]
sorry for that, the network connetion to github is poor. so i refresh the website. then there are mutiple repeated messages.

**Comment by IAlibay** [comment]
> > Can confirm this is reproducible. Here is some code to reproduce this behaviour:
> > ```python
> > import MDAnalysis as mda
> > from MDAnalysisTests.datafiles import PFncdf_Top, PFncdf_Trj
> > 
> > u = mda.Universe(PFncdf_Top, PFncdf_Trj)
> > u.atoms.write('oneframe.ncdf')
> > 
> > u2 = mda.Universe(PFncdf_Top, [PFncdf_Trj, 'oneframe.ncdf'])
> > ```
> > 
> > 
> > Switching the position of the one frame netcdf still leads to the error, but reading it alone isn't an issue.
> 
> But have many nc files. most of them have a single frame. so how can i solve it?

In order to read multiple frames at once, this issue will require fixing our code base. I have outlined the necessary steps to do so above, and hopefully someone will get around to implementing this fix in the near future. If you would like to contribute a PR for this you are more than welcome to do so.

In the mean time, I'm not sure what the best alternative is. Off the top of my head, I guess you could possible load the frames individually into and then pass them to a MemoryReader instance? Although that seems quite messy, maybe one of the other devs will have a better solution here?

**Comment by IAlibay** [comment]
> sorry for that, the network connetion to github is poor. so i refresh the website. then there are mutiple repeated messages.

No worries, sorry to hear that :(

**Comment by wuchiz** [comment]
Thanks for your help! I use netcdf.MFDataset to read mutilpe file. it can read mutiple files at the same time. then i can pass them to MemoryReader. But still hope someone can fix this bug in near future.

**Comment by orbeckst** [comment]
@IAlibay should the issue be renamed and listed as a defect?

**Comment by IAlibay** [comment]
> @IAlibay should the issue be renamed and listed as a defect?

Done
