### ISSUE TITLE
error when load mutiple netcdf trajectory files

### ISSUE THREAD

**Issue by wuchiz** [MDAnalysis/mdanalysis#3167]
## Expected behavior ##

I want to load mutiple netcdf trajectories files using
mda.Universe('cba_wat.prmtop',['1.forw.nc','2.forw.nc']

## Actual behavior ##
It report error when there is a nc file only including single frame. And it succeds when all the nc files all have more than one frames.

error is listed as follow
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-3-3715b2a4ac01> in <module>
----> 1 data = mda.Universe('../../../cba_wat.prmtop',['1.forw.nc','2.forw.nc'])

~/anaconda3/envs/pytorch/lib/python3.8/site-packages/MDAnalysis/core/universe.py in __init__(self, *args, **kwargs)
    387 
    388         if coordinates:
--> 389             self.load_new(coordinates, format=format, in_memory=in_memory,
    390                         in_memory_step=in_memory_step, **kwargs)
    391 

~/anaconda3/envs/pytorch/lib/python3.8/site-packages/MDAnalysis/core/universe.py in load_new(self, filename, format, in_memory, in_memory_step, **kwargs)
    580         kwargs['n_atoms'] = self.atoms.n_atoms
    581 
--> 582         self.trajectory = reader(filename, format=format, **kwargs)
    583         if self.trajectory.n_atoms != len(self.atoms):
    584             raise ValueError("The topology and {form} trajectory files don't"

~/anaconda3/envs/pytorch/lib/python3.8/site-packages/MDAnalysis/coordinates/chain.py in __init__(self, filenames, skip, dt, continuous, **kwargs)
    290 
    291         self.n_frames = np.sum(n_frames)
--> 292         self.dts = np.array(self._get('dt'))
    293         self.total_times = self.dts * n_frames
    294 

~/anaconda3/envs/pytorch/lib/python3.8/site-packages/MDAnalysis/coordinates/chain.py in _get(self, attr)
    499     def _get(self, attr):
    500         """Get value of `attr` for all readers."""
--> 501         return [reader.__getattribute__(attr) for reader in self.readers]
    502 
    503     def _get_same(self, attr):

~/anaconda3/envs/pytorch/lib/python3.8/site-packages/MDAnalysis/coordinates/chain.py in <listcomp>(.0)
    499     def _get(self, attr):
    500         """Get value of `attr` for all readers."""
--> 501         return [reader.__getattribute__(attr) for reader in self.readers]
    502 
    503     def _get_same(self, attr):

~/anaconda3/envs/pytorch/lib/python3.8/site-packages/MDAnalysis/coordinates/base.py in dt(self)
   1471     def dt(self):
   1472         """Time between two trajectory frames in picoseconds."""
-> 1473         return self.ts.dt
   1474 
   1475     @property

~/anaconda3/envs/pytorch/lib/python3.8/site-packages/MDAnalysis/coordinates/base.py in dt(self)
    859             pass
    860         try:
--> 861             dt = self.data['dt'] = self._reader()._get_dt()
    862             return dt
    863         except AttributeError:

~/anaconda3/envs/pytorch/lib/python3.8/site-packages/MDAnalysis/coordinates/TRJ.py in _get_dt(self)
    698 
    699     def _get_dt(self):
--> 700         t1 = self.trjfile.variables['time'][1]
    701         t0 = self.trjfile.variables['time'][0]
    702         return t1 - t0

~/anaconda3/envs/pytorch/lib/python3.8/site-packages/scipy/io/netcdf.py in __getitem__(self, index)
    966     def __getitem__(self, index):
    967         if not self.maskandscale:
--> 968             return self.data[index]
    969 
    970         data = self.data[index].copy()

IndexError: index 1 is out of bounds for axis 0 with size 1

## Code to reproduce the behavior ##

``` python
import MDAnalysis as mda
from MDAnalysis.tests.datafiles import PSF, DCD,  GRO, PDB, TPR, XTC, TRR,  PRMncdf, NCDF

u = mda.Universe(PSF, DCD)

....

```

## Current version of MDAnalysis ##
1.0.1
- Which version are you using? (run `python -c "import MDAnalysis as mda; print(mda.__version__)"`)
 Which version of Python (`python -V`)?
- Which operating system?

**Comment by IAlibay** [comment]
Looks like an accidental duplicate issue -- closing this one
