### ISSUE TITLE
Allow specification of ProgressBar keyword arguments in the AnalysisBase run method

### ISSUE THREAD

**Issue by ianmkenney** [MDAnalysis/mdanalysis#3190]
The ProgressBar (subclass of tqdm) in the AnalysisBase doesn't currently take in keyword arguments nor does it give much access to the underlying functionality of tqdm. In particular, the position keyword argument cannot be changed to adjust the location of the bar on screen. When spreading analyses across multiple processes, the rendered bars are constantly overwriting each other.

https://github.com/MDAnalysis/mdanalysis/blob/6282385644d672cf7023584347e35048935ab429/package/MDAnalysis/analysis/base.py#L186

**Comment by amdnsr** [comment]
Please assign this issue to me. I aim to submit a patch for this issue as soon as possible.

**Comment by IAlibay** [comment]
@amdnsr as detailed in the [GSOC FAQ](https://github.com/MDAnalysis/mdanalysis/wiki/GSoC-FAQ), MDAnalysis has decided to take a PR-first approach to GSOC-labelled issues. We won't assign issues, but instead will always review the first PR that is raised against a specific issue.

**Comment by Nitin-patil2209** [comment]
Hii I would like to work on this issue can you give me little information about this issue
