### ISSUE TITLE
Use a Universe object in a user-defined class?

### ISSUE THREAD

**Issue by ksy141** [MDAnalysis/mdanalysis#3192]
Hello, I've been using MDAnalysis heavily for my research. Such a great tool, thanks! As I use more and more of MDAnalysis, I need to write my own analysis tool/class that takes a universe object. The example below is a very basic thing I should understand how it works. (I don't want to make this kind of class, of course, it's just a very simple example to help me understanding MDAnalsyis.) If anyone could explain this, I'd appreciate it. I think it's relevant to how MDAnalysis takes care of a Universe object. Thanks.

```python
import MDAnalysis as mda
import MDAnalysisData
import numpy as np
from MDAnalysis import transformations

peptide = MDAnalysisData.datasets.fetch_membrane_peptide()
u = mda.Universe(peptide.topology, peptide.trajectory)

class Do_Something:
    def __init__(self):
        pass

    def shift(self, u):
        for ts in u.trajectory:
            u.atoms.positions += np.array([0, 0, 20])
        return u

class Do_Something2:
    def __init__(self, u):
        self.u = u

    def shift(self):
        for ts in self.u.trajectory:
            self.u.atoms.positions += np.array([0, 0, 20])


print('Original Z_com: %d' %u.atoms.center_of_mass()[2]) #output = 36
do  = Do_Something()
newu = do.shift(u)
print('Returned Univ: %d'  %newu.atoms.center_of_mass()[2]) #output = 36

do2 = Do_Something2(u)
do2.shift()
print('Do2 Z_com: %d' %u.atoms.center_of_mass()[2]) # output = 36

# MAKE A WHOLE
workflow = [transformations.unwrap(u.atoms)]
u.trajectory.add_transformations(*workflow)
print('TRANSFORMATION COMPLETE')  ### DONE WELL

# THE BELOW TAKES FOREVER
newu2 = do.shift(u)
print('AFTER TRANSFORM: ', newu2.atoms.center_of_mass()[2])
```

My questions are as followed:
1) Should I use Do_Something vs Do_Something2?
2) Why do both Do_Something and Do_Something2 not change the Z coordinates? They all returned 36.
3) After transformation, why does Do_Something take forever? It doesn't return any errors, but just being stuck at Do_Something. I confirmed that Do_Something2 has the same issue if applied after transformation.

I want to achieve this without using transfer_to_memory() because my trajectories are usually larger than my memory. Thanks!
Best,
Siyoung

MDAnalysis: 1.0.1
Linux Mint 20.1 Ulyssa \n \l

**Comment by orbeckst** [comment]
Hello @ksy141 , welcome to MDAnalysis. We're glad you find it useful.

Could you please ask your question on the [mailing list](https://groups.google.com/group/mdnalysis-discussion) or on the [discord server](https://www.mdanalysis.org/2021/03/20/discord/) (see https://www.mdanalysis.org/#participating ). We only use the issue tracker for bugs or feature requests/development. You'll get many more people (both developers and other users) looking at your question.

Thank you!

**Comment by orbeckst** [comment]
Just to add: if you think that something is a bug then an issue is the right place. In this case, please follow the template that is presented to you when you open the issue as a bug.
