### ISSUE TITLE
how to install

### ISSUE THREAD

**Issue by ARUN1321** [MDAnalysis/mdanalysis#3198]
I tried using pip to install mdnalysis
so i fallowed the two commands
1.pip install --upgrade MDAnalysis
2.pip install --upgrade MDAnalysisTests

so in the first command i got this issue
Collecting MDAnalysis
  Using cached MDAnalysis-1.0.0.tar.gz (19.6 MB)
Requirement already satisfied: numpy>=1.13.3 in c:\users\admin\appdata\local\programs\python\python39\lib\site-packages (from MDAnalysis) (1.19.4)
Collecting biopython>=1.71
  Using cached biopython-1.78.tar.gz (16.9 MB)
Collecting networkx>=1.0
  Using cached networkx-2.5-py3-none-any.whl (1.6 MB)
Collecting GridDataFormats>=0.4.0
  Using cached GridDataFormats-0.5.0-py2.py3-none-any.whl (2.0 MB)
Requirement already satisfied: six>=1.4.0 in c:\users\admin\appdata\local\programs\python\python39\lib\site-packages (from MDAnalysis) (1.15.0)
Collecting mmtf-python>=1.0.0
  Using cached mmtf_python-1.1.2-py2.py3-none-any.whl (21 kB)
Collecting joblib>=0.12
  Using cached joblib-1.0.1-py3-none-any.whl (303 kB)
Requirement already satisfied: scipy>=1.0.0 in c:\users\admin\appdata\local\programs\python\python39\lib\site-packages (from MDAnalysis) (1.5.4)
Requirement already satisfied: matplotlib>=1.5.1 in c:\users\admin\appdata\local\programs\python\python39\lib\site-packages (from MDAnalysis) (3.3.3)
Collecting mock
  Using cached mock-4.0.3-py3-none-any.whl (28 kB)
Collecting tqdm>=4.43.0
  Using cached tqdm-4.59.0-py2.py3-none-any.whl (74 kB)
Collecting gsd>=1.9.3
  Using cached gsd-2.4.1.tar.gz (135 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting cython<1,>=0.29.0
  Using cached Cython-0.29.22-py2.py3-none-any.whl (980 kB)
Requirement already satisfied: python-dateutil>=2.1 in c:\users\admin\appdata\local\programs\python\python39\lib\site-packages (from matplotlib>=1.5.1->MDAnalysis) (2.8.1)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\admin\appdata\local\programs\python\python39\lib\site-packages (from matplotlib>=1.5.1->MDAnalysis) (1.3.1)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3 in c:\users\admin\appdata\local\programs\python\python39\lib\site-packages (from matplotlib>=1.5.1->MDAnalysis) (2.4.7)
Requirement already satisfied: cycler>=0.10 in c:\users\admin\appdata\local\programs\python\python39\lib\site-packages (from matplotlib>=1.5.1->MDAnalysis) (0.10.0)
Requirement already satisfied: pillow>=6.2.0 in c:\users\admin\appdata\local\programs\python\python39\lib\site-packages (from matplotlib>=1.5.1->MDAnalysis) (8.0.1)
Collecting msgpack>=0.5.6
  Using cached msgpack-1.0.2-cp39-cp39-win_amd64.whl (68 kB)
Collecting decorator>=4.3.0
  Using cached decorator-4.4.2-py2.py3-none-any.whl (9.2 kB)
Using legacy 'setup.py install' for MDAnalysis, since package 'wheel' is not installed.
Using legacy 'setup.py install' for biopython, since package 'wheel' is not installed.
Building wheels for collected packages: gsd
  Building wheel for gsd (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\users\admin\appdata\local\programs\python\python39\python.exe' 'c:\users\admin\appdata\local\programs\python\python39\lib\site-packages\pip\_vendor\pep517\_in_process.py' build_wheel 'C:\Users\admin\AppData\Local\Temp\tmpmdu3s8c_'
       cwd: C:\Users\admin\AppData\Local\Temp\pip-install-ecwic9_e\gsd_6341b56d54c64fce975e62689cbb967b
  Complete output (23 lines):
  C:\Users\admin\AppData\Local\Temp\pip-build-env-w3gok2si\overlay\Lib\site-packages\setuptools\dist.py:642: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
    warnings.warn(
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.9
  creating build\lib.win-amd64-3.9\gsd
  copying gsd\hoomd.py -> build\lib.win-amd64-3.9\gsd
  copying gsd\pygsd.py -> build\lib.win-amd64-3.9\gsd
  copying gsd\version.py -> build\lib.win-amd64-3.9\gsd
  copying gsd\__init__.py -> build\lib.win-amd64-3.9\gsd
  copying gsd\__main__.py -> build\lib.win-amd64-3.9\gsd
  package init file 'gsd\test\__init__.py' not found (or not a regular file)
  creating build\lib.win-amd64-3.9\gsd\test
  copying gsd\test\conftest.py -> build\lib.win-amd64-3.9\gsd\test
  copying gsd\test\test_fl.py -> build\lib.win-amd64-3.9\gsd\test
  copying gsd\test\test_hoomd.py -> build\lib.win-amd64-3.9\gsd\test
  copying gsd\test\test_largefile.py -> build\lib.win-amd64-3.9\gsd\test
  copying gsd\test\test_gsd_v1.gsd -> build\lib.win-amd64-3.9\gsd\test
  running build_ext
  building 'gsd.fl' extension
  error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
  ----------------------------------------
  ERROR: Failed building wheel for gsd
Failed to build gsd
ERROR: Could not build wheels for gsd which use PEP 517 and cannot be installed directly

so please help me in installing mdnalysis using pip

**Comment by 1ut** [comment]
You have to install C++ compiler to install mdanalysis using pip.

**Comment by mquevill** [comment]
See the note here about installing on Windows: https://userguide.mdanalysis.org/stable/installation.html

**Comment by IAlibay** [comment]
This really is a question for the mailing list ([and has already been asked there by the author](https://groups.google.com/g/mdnalysis-devel/c/0EUuJyKo1Pw/m/6n8TqssJCgAJ)). In light of this I am closing this issue. Please open a separate issue if there is a bug/feature related to all this that needs our attention.

**Comment by ARUN1321** [comment]
Okay sir
