### ISSUE TITLE
Increase density code test coverage

### ISSUE THREAD

**Issue by IAlibay** [MDAnalysis/mdanalysis#3207]
## Is your feature request related to a problem? ##
The current density code only has 82.04% test coverage (see [here](https://codecov.io/gh/MDAnalysis/mdanalysis/src/develop/package/MDAnalysis/analysis/density.py) )
The general aim is that we should get 100% coverage for everything.

## Describe the solution you'd like ##
Tests to cover the uncovered areas

## Additional context
This is an issue aimed at providing a simple issue for first time contributing GSoC students to work on.

**Comment by thealphacod3r** [comment]
@IAlibay by clicking on the link you provided, it says Github API : Forbidden!

Can you confirm if this is right??

**Comment by IAlibay** [comment]
Yeah it seems like codecov doesn't like being linked to...

Essentially we're looking at missing coverage for:
lines 738-739
lines 754-755
lines 771-774
lines 803-808
And then all of `convert_density`.

**Comment by ojeda-e** [comment]
Hi @IAlibay, if nobody is working on this I'd like to help. I understand the GSoC deadline is soon and wouldn't like to preclude an applicant to submit a PR. Thanks.

**Comment by IAlibay** [comment]
@ojeda-e if possible I would ask that you leave this one to a first time contributor (at least until after the GSoC deadline). These coverage issues were mostly opened as "quick things to do as PRs", and are more ideally suited for first time contributors. If you wish to contribute another PR, there are other issues labelled GSoC-starter and help-wanted which need addressing.

**Comment by ojeda-e** [comment]
Ok, np!

**Comment by ojeda-e** [comment]
Hi @IAlibay. PR #3249 submitted ready to review. 

Thanks.
