### ISSUE TITLE
Improve diffusionmap coverage

### ISSUE THREAD

**Issue by IAlibay** [MDAnalysis/mdanalysis#3208]
## Is your feature request related to a problem? ##
The coverage for diffusionmap is only 96.55% covered, with lines 312 and 338 uncovered.

## Describe the solution you'd like ##
Add tests to raise this to 100% (the warning maybe hard to trigger, but maybe a dummy single atom system could be constructed to trigger the frame limit?

## Additional context ##
This is an issue aimed at providing a simple issue for first time contributing GSoC students to work on.

**Comment by ojeda-e** [comment]
Hi @IAlibay, I submitted a PR to solve this issue. Coverage for diffusionmap raised to 100%. PR #3223
