### ISSUE TITLE
Raise helix_analysis coverage

### ISSUE THREAD

**Issue by IAlibay** [MDAnalysis/mdanalysis#3209]
## Is your feature request related to a problem? ##
The new helix_analysis module only has 97.33% coverage, with no coverage for lines 389 and 476.

Whilst someone is there, please also remove the `from __future__` import on the `develop` branch.

## Describe the solution you'd like ##
Tests to increase coverage to 100%

## Additional context ##
This is an issue aimed at providing a simple issue for first time contributing GSoC students to work on.

**Comment by ojeda-e** [comment]
Interested, I'll work on it!

**Comment by IAlibay** [comment]
@ojeda-e Please do open a PR. Also if you haven't done so yet, please introduce yourself as a GSoC applicant on the developer mailing list.

**Comment by ojeda-e** [comment]
Thank you @IAlibay, PR #3219 open to fix issue.
