### ISSUE TITLE
Empty MDAnalysis.analysis.utils?

### ISSUE THREAD

**Issue by IAlibay** [MDAnalysis/mdanalysis#3213]
MDAnalysis.analysis.utils just exists, but I can't seem to think of any reason why. Looks like a leftover of #2256.

Unless there's a good reason not to, I'll go ahead and remove it.

**Comment by p-j-smith** [comment]
Sorry that was my and @bieniekmateusz's fault. We originally put `MDAnalysis.lib.correlations.autocorrelation` and `MDAnalysis.lib.correlations.correct_intermittency` into `MDAnalysis.analysis.utils`, but we moved them to their current place after discussion with @orbeckst. It should be fine to remove. Thanks for clearing up our mess!
