### ISSUE TITLE
Add CI runner with older versions of chemfiles

### ISSUE THREAD

**Issue by Luthaf** [MDAnalysis/mdanalysis#3216]
> Can you open an issue about covering this so we don't forget? I was working on a weekly cron CI job somewhere else, I can probably just add a workflow that installs older versions of chemfiles.

_Originally posted by @IAlibay in https://github.com/MDAnalysis/mdanalysis/pull/3126#r607320587_

**Comment by Luthaf** [comment]
For the record, I don't plan on supporting more than one release of chemfiles until I reach version 1.0. I can support the master/dev version and the latest release (version 0.10.x right now), but I will not have the time to add patches or make new release in the 0.9 series. 

I can see the advantage for users to ensure that one more version of the API is supported in MDAnalysis, but if someone runs into an issue with 0.9.3, I would rather point them to version 0.10 instead.

**Comment by IAlibay** [comment]
Setting as fixed with #3499 since it's no longer required. We may re-visit once several versions of Chemfiles need supporting again.
