### ISSUE TITLE
Allow setting user box dimensions to a multidimensional array.

### ISSUE THREAD

**Issue by hmacdope** [MDAnalysis/mdanalysis#3217]
## Is your feature request related to a problem? ##

You should be able to set the box size manually over your whole trajectory. Related to #2691, however the fix in #3175 (NOTE: currently pending merge) only sets the box dimensions to a constant  `[a, b, c,alpha, beta, gamma]`.

## Describe the solution you'd like ##

This can be done easily with a multidimensional array of shape `timesteps, [a, b, c,alpha, beta, gamma]` and something like the below:

```python
def set_traj_dimensions(input_dims, u):
    for i, ts in  enumerate(u.trajectory):
		ts.dimensions = input_dims[i,:] 
```

## Additional context ##

You cannot work on this issue until #3175  is merged.

**Comment by lilyminium** [comment]
You’d probably want an OTF transformation like PR #3175, as changes to ts.dimensions won’t persist throughout the loop.

**Comment by yizhuang1** [comment]
Hi, is this thread still available for GSoC? I'd like to make a contribution. Thanks!

**Comment by hmacdope** [comment]
@yizhuang1 yes it! Go ahead and make a PR. :)

**Comment by nancyalaswad90** [comment]
Hi everyone 😊

Please advise me on how we distinguish between the active or close issues?

**Comment by orbeckst** [comment]
As @ljwoods2 correctly pointed out in https://github.com/MDAnalysis/mdanalysis/discussions/4400 , the current implementation https://github.com/MDAnalysis/mdanalysis/blob/734314b8b7b70617a92eb505f75844e6837505ca/package/MDAnalysis/transformations/boxdimensions.py#L37 already allows setting the box dimension from an array for all frames of the trajectory. This behavior was added in f50a0978c3b3401e663448b511583fee4d476d84 as part of PR #4258 .
