### ISSUE TITLE
Why is test_altloc.py in utils?

### ISSUE THREAD

**Issue by lilyminium** [MDAnalysis/mdanalysis#3222]
## Expected behavior ##

I guess I would expect it to be in topology/.

## Actual behavior ##

It's in utils: https://github.com/MDAnalysis/mdanalysis/blob/develop/testsuite/MDAnalysisTests/utils/test_altloc.py

## Code to reproduce the behavior ##

``` python
import MDAnalysis as mda
from MDAnalysis.tests.datafiles import PSF, DCD,  GRO, PDB, TPR, XTC, TRR,  PRMncdf, NCDF

u = mda.Universe(PSF, DCD)

....

```

## Current version of MDAnalysis ##

- Which version are you using? (run `python -c "import MDAnalysis as mda; print(mda.__version__)"`) develop
- Which version of Python (`python -V`)?
- Which operating system?

**Comment by richardjgowers** [comment]
Yeah just looks like it got put in the wrong place when the tests got refactored.  Can be moved I guess?
