### ISSUE TITLE
Update docs to be sphinx 3+ compatible

### ISSUE THREAD

**Issue by lilyminium** [MDAnalysis/mdanalysis#3224]
## Is your feature request related to a problem? ##

Sphinx is pinned to 1.8.5 which is a pretty old version. I think it has something to do with https://github.com/MDAnalysis/mdanalysis/issues/2667.

## Describe the solution you'd like ##

Update the documentation so we don't have to pin sphinx to such an old version. However, we likely do have to pin it to mesh well with the RTD theme -- the user guide recently pinned its versions to `sphinx==3.4.2` and `sphinx_rtd_theme==0.5.1` to fix a search problem. https://github.com/MDAnalysis/UserGuide/pull/141

## Describe alternatives you've considered ##

Don't and hope for the best.

**Comment by orbeckst** [comment]
This is going to be a fair amount of busy-work fixing docs. Perhaps we start a PR and then anyone who wants some good karma can contribute by fixing errors in a few files.

**Comment by orbeckst** [comment]
Now our CI doc build **build_docs** is failing, e.g. https://github.com/MDAnalysis/mdanalysis/pull/3421/checks?check_run_id=3690514153

```
running build_sphinx
Running Sphinx v1.8.5
/usr/share/miniconda/envs/test/lib/python3.7/site-packages/setuptools/dist.py:487: UserWarning: Normalizing '2.1.0-dev0' to '2.1.0.dev0'
  warnings.warn(tmpl.format(**locals()))

Warning, treated as error:
Sphinx 1.x is deprecated with sphinx_rtd_theme, update to Sphinx 2.x or greater
Error: Process completed with exit code 1.
```
