### ISSUE TITLE
A 'Powered by MDAnalysis' badge

### ISSUE THREAD

**Issue by mnmelo** [MDAnalysis/mdanalysis#3227]
It'd be good to have some sort of feedback on which larger scale projects use MDAnalysis
- as visibility metrics in grant applications;
- for warm fuzzy open-source feelings.

Encouraging our users to display a 'Powered by MDAnalysis' [Shields.io](https://shields.io) badge could serve that purpose, plus giving extra visibility. Here's a starting example, with default gray/orange color combination:

[![Powered by MDAnalysis](https://img.shields.io/badge/Powered%20by-MDAnalysis-orange.svg)](https://www.mdanalysis.org)

Or, after a bit more work, with the overlaid .ico logo:

EDIT: github seems to have a proxy/caching system for outside image urls and the logo makes this too big. Try [this link instead](https://img.shields.io/badge/Powered%20by-MDAnalysis-orange.svg?logoWidth=15&logo=data:image/x-icon;base64,AAABAAEAISAAAAEAIACoEQAAFgAAACgAAAAhAAAAQAAAAAEAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAkv//AJL//wCS//8Akv//AJL//wCS//8Akv//AJL//wCS//8AAAAAgICA/4CAgP+AgID/gICA/4CAgP+AgID/gICA/4CAgP+AgID/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAkv9XAJL//QCS//8Akv//AJL//wCS//8Akv//AJL+/wCS/8KWfGlJgICA/ICAgP+AgID/gICA/4CAgP+AgID/gICA/4CAgP6AgICsgICAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAkv5NAJL//QCS//4Akv//AJL//wCS//8Akv//AJH//wCS/7OPfXBhgICA/4CAgP+AgID/gICA/4CAgP+AgID/gICA/4CAgP6AgICmAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAkv8LAJL/9wCR//8Akv/+AJL//wCS//8Akv//AJH+/wKR/EODf3yfgICA/4CAgP+AgID/gICA/4CAgP+AgID/gICA/oCAgP+AgIBmAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACS/wAAAAAAAJL/TACS//kAkv//AJL//wCS//8Akf7/AJL/lZR9ayN/gID7gICA/4CAgP+AgID+gICA/4CAgP+AgID/gICA/4CAgMiAgIABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACU/yEAkv+qAJH+6QCR/s0Akv9Re4CEJoB/f/OAgID/gYGB/4KCgvyAgID/f39//4CAgP+AgID/gICAr4CAgAkAAAAAgICAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAgIAAAAAAAICAgCKAgIBogICAm4F/foiYfGc7uXdHJKl6VyyFf3p8gICA/X19fcjCwsL/wsLC///////CwsL/XFxceYODg2F/f38tAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgICAW4CAgOqAgID/gICA/4CAgP+AgID/gICA+YCAgP+AgID/fHx8mQMDA8cAAAD6AAAA/wAAAP8AAAD/AAAA5gAAAEMAAAAAAAAAAICAgAAAAAAAAJL/AAAAAAAAAAAAAJL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAgIAdgICA7YCAgP6AgID/gICA/4CAgP+AgID/gICA/4CAgP9/f3/pDAwMrgAAAP8AAAD+AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAAJAAAAAAAAAAAAAAAAAJL+DgCR/0EAkv8lAJH+AgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAgIBugICA/4CAgP+AgID/gICA/4CAgP+AgID/gICA/4CAgP/CwsL/AAAA3wAAAP4AAAD/AAAA/wAAAP8AAAD/AAAA/gAAAP8AAACUAAAAAACS/wAAkv8lAJL/4gCS//8Akv//AJH+iAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAgICrgICA/4CAgP+AgID/gICA/4CAgP+AgID/gICA/4CAgP//////AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAADbAAAAAAAAAAAAkv9vAJL+/wCS//4Akv//AJH/6wCS/xQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAgIClgICA/4CAgP+AgID/gICA/4CAgP+AgID/gICA/4CAgP/CwsL/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP4AAADxAAAAAAAAAAAAkv5lAJH//wCS//4Akv//AJL/6wCR/wsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAgIBXgICA/4CAgP+AgID/gICA/4CAgP+AgID/gICA/4CAgP/CwsL/AAAA0gAAAP4AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP4AAAD2AAAAJwAAAAAAkv4MAJH/0QCS//8Akf7/AJL/SgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAgIARgICA14CAgP+AgID+gICA/oCAgP6AgID/gICA/4CAgP6enp7/HBwcngAAAP8AAAD/AAAA/gAAAP8AAAD+AAAA/wAAAP8AAAD+AAAAhQAAAAAAAAAAAAAAAACS/iQAkf4DAAAAAACS/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgICAJYCAgMmAgID/gICA/4CAgP+AgID/gICA+4CAgP+AgID/f39/ywgICHoAAAD5AAAA/wAAAP8AAAD/AAAA/wAAAPUAAAD/AAAA/wAAAGYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAgIAAgICAAAAAAACAgIAzgICAcoCAgF+AgIAJAAAAAAAAAACAgIBXf39/54CAgPmenp7/z8/P/8LCwv//////wsLC/56env9dXV1hAwMDsAAAAP8AAAC1AAAAJwAAAAkAAAAMAAAAVAAAAIoAAABwAAAAGgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgICAAAAAAAAAAAAAgICAD39/f8WAgID/g4OD/4SEhPiBgYH/f39//39/f/+BgYH/h4eHyP////8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/gAAAIgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAkv8AAAAAAAAAAACAgIAAAAAAAICAgAmAgIDxgICA/4CAgP+AgID/gICA/4CAgP9/f3//gICA/4CAgPQAAAD/AAAA/wAAAP8AAAD/AAAA/gAAAP8AAAD+AAAA/wAAAP8AAAB/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAkv8bAJH+bQCS/z0AAAAACJD2AICAgACAgICTgICA/4CAgP+AgID/gICA/4CAgP+AgID/gICA/n9/f/+zs7P/AAAA8gAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP4AAADZAAAADwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAkv/NAJH//wCS//8Akv4QAAAAAAAAAACAgIBpgICA/oCAgP+AgID/gICA/4CAgP+AgID/gICA/4CAgP7e3t7/AAAA6wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAADzAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAkv/PAJL//wCS//8Akv8PAAAAAAAAAACAgIBSgICA+4CAgP+AgID/gICA/4CAgP+AgID/gICA/4CAgP//////AAAA7AAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAADzAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAkv8cAJL/cACS/0AAAAAAAJL/AAAAAACAgIAmgICA+4CAgP6AgID/gICA/4CAgP+AgID/gICA/n9/f//Pz8//AAAA8gAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP4AAADZAAAADwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAkv4AAAAAAAAAAAAAAAAAAAAAAICAgAAAAAAAgICAqoCAgP+AgID/gICA/oCAgP9/f3//gICA/4CAgPaenp7/AAAA/wAAAP8AAAD/AAAA/gAAAP8AAAD/AAAA/wAAAP8AAAB9AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAN7e3v+CgoL+gICA/39/f/+BgYH/3t7e//////8AAAD/AAAA/wAAAPUAAAD/AAAA/wAAAP8AAAD/AAAA+gAAAIsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAASAAAAbZ6env/CwsL////////////Pz8//BQUFuQAAAP8AAACrAAAAJQAAABMAAAATAAAASwAAAIIAAABnAAAAHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAHIAAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAF8AAAAAAAAAAACR/hQAjvkKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAewAAAP8AAAD/AAAA/gAAAP8AAAD/AAAA/wAAAP8AAAD+AAAAhAAAAAAAkPwaAJH+uACS/9sAkv/UAJL/bQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPAAAA3gAAAP4AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP4AAAD2AAAAJgAAAAAAkv/CAJH+/wCS//4Akv/+AJL//QCS/0oAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAaAAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAADwAAAAAACS/xoAkv//AJL//gCS//8Akv//AJL+/wCS/50AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAbAAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAADbAAAAAACS/yUAkv7/AJL//gCS//8Akv//AJL//wCS/6YAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAASAAAA6QAAAP4AAAD/AAAA/wAAAP8AAAD/AAAA/gAAAP8AAACSAAAAAAAAAAAAkv/dAJL//wCS/v4Akv//AJL//wCS/lwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAkgAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAPIAAAAKAAAAAAAAAAAAkv8rAJL/1gCS/v8Akv/8AJL+ewCR/wIAkf4AAAAAAAAAAAAAAAAAAAAAAAAAAADgCAP/gAAAAPAIA/+AAAAA8AgD/4AAAADwEAf/gAAAAPgQB/+AAAAA/GAP/4AAAADzwP//gAAAAMAAf/+AAAAAgAA//4AAAACAABw/gAAAAAAAHD+AAAAAAAAcP4AAAACAABx/gAAAAIAAD/+AAAAAwBAP/4AAAAD/wCPfgAAAAP/gAAOAAAAA//AAA4AAAAD/8AABgAAAAPx4AAGAAAAA/HgAAYAAAAD/+AABgAAAAP/4AAOAAAAA//wAA4AAAAD//APfgAAAAP/wD/+AAAAA/+AMf4AAAAD/wBg/gAAAAP/AGB+AAAAA/8AYH4AAAAD/wBg/gAAAAP/APH+AAAAA)
Hopefully, inclusion in a `README.md` would still be possible.

(The base64-encoded .ico is appended to the shields.io url)

Tracking said badges might be as straightforward as crafting a targeted Google query. As an example, for the NumFOCUS badge (#2460): [https://www.google.com/search?q="-NumFOCUS-orange.svg"](https://www.google.com/search?q="-NumFOCUS-orange.svg")

Opinions?

**Comment by richardjgowers** [comment]
I think this idea was raised before somewhere and I was in favour then... I like the second logo with the little molecule bit too.

**Comment by lilyminium** [comment]
I like both logos, but the little molecule one goes the extra mile! And making tracking easier is a big plus.

**Comment by mnmelo** [comment]
Thanks for the feedback. I'll test it in a branch whether github can render the icon-logo in README.md, or if it's an overall limitation. If it's the latter, then I guess we'll have to stick to the plain-text version.

(@richardjgowers, I searched the issues about it but could only find the one issue about the NumFOCUS badge. Maybe in the mailing lists?)

**Comment by mnmelo** [comment]
Hey, I fixed it using a shrunk (16x16) logo :)
Check out README.rst in the PR (don't forget to switch on the 'rich-diff') or in branch [feature-MDA_badge-3227](https://github.com/MDAnalysis/mdanalysis/tree/feature-MDA_badge-3227).

**Comment by cbouy** [comment]
10/10 ✨ I'd definitely use it for [ProLIF](https://github.com/chemosim-lab/ProLIF)

**Comment by mnmelo** [comment]
That's great! The PR updating the `README.rst` will be merged soon, but the markup examples are already up in the [website](https://www.mdanalysis.org/pages/citations/#powered-by-mdanalysis) for everyone's use!

**Comment by mnmelo** [comment]
A shout out to @cbouy and [ProLIF](https://github.com/chemosim-lab/ProLIF). As far as I can tell, the very first to [implement](https://github.com/chemosim-lab/ProLIF/commit/5e10ee989cc0eac0dca499a1cb1e1926ae06d925) our badge!
