### ISSUE TITLE
Fail Installation

### ISSUE THREAD

**Issue by JoelTV2021** [MDAnalysis/mdanalysis#3228]
Hi MDAnalysis developers!!

I don't understand why have those errors because the first time that I installing and running pytest was successful and now I try to run pytest with this command> 
$pytest --disable-pytest-warnings --pyargs MDAnalysisTests

And the terminal same this messages>

platform linux2 -- Python 2.7.18, pytest-4.5.0, py-1.10.0, pluggy-0.11.0
rootdir: /home/joel
plugins: xdist-1.34.0, forked-1.3.0, hypothesis-4.54.2
collected 15668 items / 7 errors / 3 skipped / 15658 selected                                                                                                                                             

================================================================================================= ERRORS ==================================================================================================
___________________________________________________ ERROR collecting miniconda2/lib/python2.7/site-packages/MDAnalysisTests/coordinates/test_fhiaims.py ___________________________________________________
ImportError while importing test module '/home/joel/miniconda2/lib/python2.7/site-packages/MDAnalysisTests/coordinates/test_fhiaims.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
miniconda2/lib/python2.7/site-packages/MDAnalysisTests/coordinates/test_fhiaims.py:35: in <module>
    from MDAnalysisTests.datafiles import FHIAIMS
E   ImportError: cannot import name FHIAIMS
___________________________________________________ ERROR collecting miniconda2/lib/python2.7/site-packages/MDAnalysisTests/coordinates/test_namdbin.py ___________________________________________________
ImportError while importing test module '/home/joel/miniconda2/lib/python2.7/site-packages/MDAnalysisTests/coordinates/test_namdbin.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
miniconda2/lib/python2.7/site-packages/MDAnalysisTests/coordinates/test_namdbin.py:35: in <module>
    from MDAnalysisTests.datafiles import NAMDBIN, PDB_small
E   ImportError: cannot import name NAMDBIN
___________________________________________________ ERROR collecting miniconda2/lib/python2.7/site-packages/MDAnalysisTests/coordinates/test_parmed.py ____________________________________________________
ImportError while importing test module '/home/joel/miniconda2/lib/python2.7/site-packages/MDAnalysisTests/coordinates/test_parmed.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
miniconda2/lib/python2.7/site-packages/MDAnalysisTests/coordinates/test_parmed.py:35: in <module>
    from MDAnalysisTests.datafiles import (
E   ImportError: cannot import name PSF_cmap
_________________________________________________________ ERROR collecting miniconda2/lib/python2.7/site-packages/MDAnalysisTests/lib/test_log.py _________________________________________________________
ImportError while importing test module '/home/joel/miniconda2/lib/python2.7/site-packages/MDAnalysisTests/lib/test_log.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
miniconda2/lib/python2.7/site-packages/MDAnalysisTests/lib/test_log.py:28: in <module>
    from MDAnalysis.lib.log import ProgressMeter, ProgressBar, echo
E   ImportError: cannot import name ProgressBar
____________________________________________________ ERROR collecting miniconda2/lib/python2.7/site-packages/MDAnalysisTests/topology/test_fhiaims.py _____________________________________________________
ImportError while importing test module '/home/joel/miniconda2/lib/python2.7/site-packages/MDAnalysisTests/topology/test_fhiaims.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
miniconda2/lib/python2.7/site-packages/MDAnalysisTests/topology/test_fhiaims.py:30: in <module>
    from MDAnalysisTests.datafiles import FHIAIMS
E   ImportError: cannot import name FHIAIMS
______________________________________________________ ERROR collecting miniconda2/lib/python2.7/site-packages/MDAnalysisTests/topology/test_itp.py _______________________________________________________
ImportError while importing test module '/home/joel/miniconda2/lib/python2.7/site-packages/MDAnalysisTests/topology/test_itp.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
miniconda2/lib/python2.7/site-packages/MDAnalysisTests/topology/test_itp.py:31: in <module>
    from MDAnalysisTests.datafiles import (
E   ImportError: cannot import name ITP
__________________________________________________ ERROR collecting miniconda2/lib/python2.7/site-packages/MDAnalysisTests/transformations/test_wrap.py ___________________________________________________
ImportError while importing test module '/home/joel/miniconda2/lib/python2.7/site-packages/MDAnalysisTests/transformations/test_wrap.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
miniconda2/lib/python2.7/site-packages/MDAnalysisTests/transformations/test_wrap.py:30: in <module>
    from MDAnalysis.transformations import wrap, unwrap
E   ImportError: cannot import name unwrap
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 7 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
============================================================================= 3 skipped, 1 warnings, 7 error in 5.41 seconds

**Comment by orbeckst** [comment]
How did you install MDAnalysis?

Which version of MDAnalysis was installed?

**Comment by IAlibay** [comment]
@JoelTV2021 is this still an ongoing issue? If we don't hear any further updates we will close the issue in a couple of days.

**Comment by orbeckst** [comment]
Without further information we cannot do much more here and I'll close the issue.

@JoelTV2021 please feel free to request this issue be re-opened. 

(You can also check if the newly released 1.1.1 fixes the problem.)
