### ISSUE TITLE
Testing for memleaks

### ISSUE THREAD

**Issue by mnmelo** [MDAnalysis/mdanalysis#323]
Recent issues (#312, #297) showed it'd be very useful to report uncollectable objects in our tests. Two solutions below (as I wrote this and tested further I became in favor of solution 2):

1.
A very simple way to do this is to have a `teardown_package` module-level function that runs `gc.collect()` and then checks whether `gc.garbage` is empty. Nose automatically runs this at the very end of the tests and we get one check for leaks during the entire test run.

The problems with this approach are:
- In my hands the presence of such a function kept nose from parallelizing. It apparently did spread out into multiple threads but they all ran, extra slow, in only one core (I'm guessing it did threading instead of multiprocessig and ran into GIL slowness, but I could be totally wrong).
- In order to be comprehensive we want our run to be serial anyway, otherwise memleaks in child test processes are missed.

I don't know if the testing of Travis builds is done in parallel. If so, then this becomes more problematic than just slowing down testing during development.

A solution might be to check if the `--processes` flag is set, and if so skip the definition of `teardown_package` (couldn't find exactly how to access the flag, though). A workflow for development would then be to run parallel until all passes, and finally run once in serial to check for memleaks (if you're debugging memleaks then tough luck, you're stuck with having to repeatedly run in serial).
Again, if Travis tests in parallel then this would mean memleaks don't get tested there.

2.
A second approach is to create a class, say, `MemleakTest` that subclasses TestCase. Through some hacking we can get our `MemleakTest` to wrap `tearDown` within its own `tearDown`method that invokes `gc.collect()` and then checks whether `gc.garbage` is empty. Each test class we need to memleak-check just has to inherit from `MemleakTest`.
After fiddling around this seems pretty straightforward to do. `gc` ends up being imported in every test call, but there's no performance hit once it's already loaded, right?
I'll push a branch soon.

**Comment by richardjgowers** [comment]
FYI, Travis is serial

**Comment by mnmelo** [comment]
That gives some points to option 1.

Option 2 has the added benefit that the offending tests can be pinpointed, since the check is run once per test instead of only at the end of the entire run.

**Comment by richardjgowers** [comment]
So one option is to put the tests for memory leaking in a file that isn't ran by Travis or picked up by nose (anything starting with "test_" gets picked up, so call it "memory_leak_test.py"), and have it as an optional test.  So it would be more like a convenience for developers, and something to check before releases.

I think the chance of us breaking this is low, and we'll know when we're likely to run into it (eg. we've played with `__del__`), so running it manually isn't a problem?
