### ISSUE TITLE
PyTNG integration into MDA.

### ISSUE THREAD

**Issue by hmacdope** [MDAnalysis/mdanalysis#3237]
## Is your feature request related to a problem? ##

A TNG file-reader should be in MDA! 

## Describe the solution you'd like ##

We have a working one in PyTNG, but it is not integrated with MDA itself yet.

How should we go about doing this (@orbeckst, @richardjgowers)? Sub-module? Copied source code?

The Cython in PyTNG needs to be compiled so it will have to be integrated with the MDA build step at some level.

**Comment by orbeckst** [comment]
Can we make it a stand-alone module that gets conda or pip installed? That's what we've been moving towards with pretty much any dependency.

**Comment by orbeckst** [comment]
Having it as a stand-alone package will also make it more re-usable for other packages.

**Comment by orbeckst** [comment]
Does PyTNG have a working _writer_ or only the _reader_ ?

**Comment by orbeckst** [comment]
cc @IAlibay who will likely want to know in which new and exciting ways a PyTNG dependency will break CI...

**Comment by hmacdope** [comment]
@orbeckst conda or pip install is perfect. Only the *Reader* currently works. I have plans for a writer and also want to cover topology info in due course, but this is a bit down the line. Would you want to hold for a writer as well or just start with a reader?

**Comment by orbeckst** [comment]
Start with a reader!! 

We have many formats for which we don't have a writer. Most people are initially just interested in a reader (I think...). However, if a format turns out to be really useful then people might want to start converting raw trajectories. Especially if you can integrate conversion into a workflow with other costly transformations such as centering/making molecules whole then it becomes quite attractive to do everything inside MDA.

**Comment by IAlibay** [comment]
> cc @IAlibay who will likely want to know in which new and exciting ways a PyTNG dependency will break CI...

As far as I'm aware the only extra requirement here is cython, which we are already planning to introduce as an MDA core requirement in the future.

The only thing I can think _might_ require some effort is validating PyTNG on MacOS & Windows (especially the 32bit builds). But that'll be up to PyTNG to support upstream.

**Comment by hmacdope** [comment]
@IAlibay there are currently no upstream windows or macos CI builds so will have to fix that.

**Comment by richardjgowers** [comment]
I think it makes sense for `PyTNG` to exist as a standalone library that provides data as numpy arrays (or maybe more specifically, accepts numpy arrays as arguments to fill).  Then we have a tiny bit of work to do in this package to get that data into a `Timestep` object.  This is similar to the existing libmdaxdr / XTCReader split we currently have.

**Comment by hmacdope** [comment]
Now that I have fixed the PyTNG build on windows I am hoping to press forward on this ASAP.
