### ISSUE TITLE
Switch GNMAnalysis to AnalysisBase.

### ISSUE THREAD

**Issue by PicoCentauri** [MDAnalysis/mdanalysis#3243]
## Is your feature request related to a problem? ##

The `GNMAnalysis` currently uses its own logic for the trajectory analysis. The AnalysisBase class provides the 
same  functionality and should be used as a parent class.

## Describe the solution you'd like ##

 1. Change the parent class of  `GNMAnalysis` to `AnalysisBase`
https://github.com/MDAnalysis/mdanalysis/blob/fa074966bfe21c85bde8e4b61cd29ef8aecd692a/package/MDAnalysis/analysis/gnm.py#L192

2.  Move the code in the `run` method that is outside the loop to `_prepare` and everything that is inside to `_single_frame`
https://github.com/MDAnalysis/mdanalysis/blob/fa074966bfe21c85bde8e4b61cd29ef8aecd692a/package/MDAnalysis/analysis/gnm.py#L309

**Comment by orbeckst** [comment]
@IAlibay please see comments on PR #3244 — if you don't want it in 2.0 please remove.
