### ISSUE TITLE
Sdist should bundle up the Cython generated .cpp/.c files

### ISSUE THREAD

**Issue by richardjgowers** [MDAnalysis/mdanalysis#3252]
With #3250 the .c/.cpp files generated by Cython (we have real .c files too) aren't tracked in version control.  The command `python setup.py sdist` now needs to include these in the `.tar.gz` that it creates.

Docs for how to do this are here: https://docs.python.org/3/distutils/sourcedist.html

**Comment by IAlibay** [comment]
Do we actually want to add the C/C++ files, aren't we looking to make cython a dependency?

**Comment by richardjgowers** [comment]
Yeah alternatively we could add cython as a dependency and ship the pyx
instead

**Comment by tylerjereddy** [comment]
I believe it is more common to cythonize and ship the C/C++ files, although my sample size of other projects is a bit narrow.

**Comment by IAlibay** [comment]
Just testing this for the beta release, looks like it just works fine as-is.

**Comment by IAlibay** [comment]
Closing as fix not needed?
