### ISSUE TITLE
TRZ reader default dt value differs from base default value

### ISSUE THREAD

**Issue by IAlibay** [MDAnalysis/mdanalysis#3257]
## Expected behavior ##

The default value for `dt` is the same across all readers.

## Actual behavior ##

As pointed out in #3256 the TRZ reader defaults to 0 instead of the base value of 1.0. I propose in 2.1.0 that we just change it to align the behaviour with the other readers (as per the warning I added in #3256).

**Comment by richardjgowers** [comment]
The 0 value only happens when there's only one frame so this is very minor.  But yeah we can fix this once 2.0 is out the door.

**Comment by IAlibay** [comment]
I'm fixing some TRZ behaviour somewhere else [for 2.0.0], I might just throw the warning in there so we can make 2.1.0 the "get rid of all the warnings" release.
