### ISSUE TITLE
OpenMM converter docs should be under Converters

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/mdanalysis#3262]
## Expected behavior ##

With PR #2917 (OpenMM, #2863) merged, I expected to see docs under converters https://docs.mdanalysis.org/2.0.0-dev0/documentation_pages/converters.html 

## Actual behavior ##

Only the [OpenMM topology parser](https://docs.mdanalysis.org/2.0.0-dev0/documentation_pages/topology/OpenMM.html) and [OpenMM coordinate reader](https://docs.mdanalysis.org/2.0.0-dev0/documentation_pages/coordinates/OpenMM.html) are visible.

## Current version of MDAnalysis ##

- Which version are you using? (run `python -c "import MDAnalysis as mda; print(mda.__version__)"`) docs 2.0.0-dev

**Comment by IAlibay** [comment]
@orbeckst is this good to close now?

**Comment by orbeckst** [comment]
yes, thanks
