### ISSUE TITLE
Incorrect versionadded for helix_analysis?

### ISSUE THREAD

**Issue by IAlibay** [MDAnalysis/mdanalysis#3267]
The helix_analysis docstring says that it was added in version 1.0.0

https://github.com/MDAnalysis/mdanalysis/blob/2c714fccd95d8b05f807e38175557e398199b1d6/package/MDAnalysis/analysis/helix_analysis.py#L32

However, it's not (unless I'm missing something) in 1.1.1 (or at least current `master`).

**Comment by IAlibay** [comment]
If this is indeed 2.0.0, then we need to add it to the list of #3261 things that need to be dealt with before we release 2.0.0 (so that we don't have to deprecate later).

**Comment by orbeckst** [comment]
Seems to be a mistake, it never made it into 1.x. We only state that helanal is gone and helix_analysis will be in 2.0.0.
