### ISSUE TITLE
update helix_analysis to use .results

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/mdanalysis#3268]
Follow the new AnalysisBase API for the new helix_analysis and store results in `.results` instead of class attributes.

This should be done for 2.0.0 #3254 so that we don't have to start this new analysis module with deprecations in place.

See omnibus issue #3261 for background and details. See PR #3263 as an example (DensityAnalysis) but note that _no deprecations are necessary_ — just change where the results are stored and update the docs.

- [ ] use attributes in`self.results` instead of `self`
- [ ] update docs
- [ ] add an entry in CHANGELOG under Changes (for completeness)

**Comment by orbeckst** [comment]
@fiona-naughton @lilyminium (or anybody else) helping hands would be much appreciated!!

(See https://github.com/MDAnalysis/mdanalysis/issues/3261#issuecomment-833836242 ...)

**Comment by orbeckst** [comment]
When you look at this issue please also fix #3267 .

**Comment by lilyminium** [comment]
is there a deadline for this :)

**Comment by IAlibay** [comment]
> is there a deadline for this :)

gotta be merged before we release 2.0.0, Friday ;) [mayyybeee Saturday, but really Friday]
