### ISSUE TITLE
update hydrogenbonds.WaterBridgeAnalysis to use .results

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/mdanalysis#3270]
Follow the new AnalysisBase API and store results in hydrogenbonds.WaterBridgeAnalysis in `.results` instead of class attributes.

See omnibus issue #3261 for beackground and details. See PR #3263 as an example (DensityAnalysis)
- [ ] put all generated data into `self.results` instead of `self`
- [ ] keep managed attributes in place with deprecation message
- [ ] test deprecation messages/old attribute access
- [ ] update CHANGELOG: one entry in Changes (use .results) and one entry in Deprecations (attribute access to be removed in 3.0.0)

**Comment by RMeli** [comment]
I can do this one @orbeckst

**Comment by orbeckst** [comment]
Thank you @RMeli . I updated the instructions in #3261 **Approach** to give everyone a template.

**Comment by RMeli** [comment]
@orbeckst is there any recommended way to proceed when results are defined as properties?

https://github.com/MDAnalysis/mdanalysis/blob/da46e8406b863503004daa06686ba86da0428f39/package/MDAnalysis/analysis/hydrogenbonds/wbridge_analysis.py#L1520

**Comment by orbeckst** [comment]
The intent of `results` is to enable auto-detection of any simulation output that could be used for downstream processing or output by mdacli; @PicoCentauri and @joaomcteixeira should chime in an say what they'd expect of WaterBridgeAnalysis.

It looks to me that the intent was that one could generate a new timeseries if one sets a different `self.output_format`. But then a cleaner solution is to make it a public `generate_timeseries(output_format=None)` method that defaults to `self.output_format`.  @xiki-tempula , is this a problem?

As @lilyminium suggested, I would add a `_conclude` that does something like
```
def _conclude(self):
     self.results.timeseries = self.generate_timeseries()
```
Are there any other results that one might to output? 
* What about `network` — I don't understand why it's being made a property to wrap around `self._network`. Is this something that counts as a result?   
*  `table` should  become `results.table`. The format of table would be ideal for output so it would be convenient to  just generated it in `_conclude` but I don't know if we should increase the memory footprint when it's not used otherwise.

**Comment by orbeckst** [comment]
If `table` is not used internally then the better approach for `generate_table()` is to be a function that just returns it. I like the data format of table better but ultimately that's something that the user needs to decide. For right now, let's _not_ include `results.table` but deprecate `.table` and say that in 3.0.0, `generate_table()` will return the table. Does this sound sensible @xiki-tempula ?

Given that the network is a result, I agree with  your approach.

**Comment by orbeckst** [comment]
I am reviewing the PR. Let's change `generate_table()` right away to _also_ return `table` and keep `self.table` around for 2.x.

**Comment by xiki-tempula** [comment]
> It looks to me that the intent was that one could generate a new timeseries if one sets a different self.output_format. But then a cleaner solution is to make it a public generate_timeseries(output_format=None) method that defaults to self.output_format. @xiki-tempula , is this a problem?

So originally, I tried to deprecate the hydrogen bond analysis by allowing the WaterBridgeAnalysis to give the same result when the `order=0`. So the `output_format` can be set to adopt the hydrogen bond analysis format but I guess it is irrelevant now and the default should work.

> What about network — I don't understand why it's being made a property to wrap around self._network. Is this something that counts as a result?

Due to the nature of the water interaction network, the most natural way would be to represent it as a network, but that would be hard to analyse, so the _network was originally a private variable. Then I noticed a paper that uses the _network variable, so I made it into a public one.

> If table is not used internally then the better approach for generate_table() is to be a function that just returns it. I like the data format of table better but ultimately that's something that the user needs to decide. For right now, let's not include results.table but deprecate .table and say that in 3.0.0, generate_table() will return the table. Does this sound sensible @xiki-tempula ?

Yes, I think it is a sensible approach.
