### ISSUE TITLE
Update AlignTraj and AverageStructure to use new .results

### ISSUE THREAD

**Issue by IAlibay** [MDAnalysis/mdanalysis#3278]
Follow the new AnalysisBase API and store results in align.AlignTraj and align.AverageStructure in `.results` instead of class attributes.

See omnibus issue #3261 for background and details. See PR #3263 as an example (DensityAnalysis)
- [ ] put all generated data into `self.results` instead of `self`
- [ ] keep managed attributes in place with deprecation message
- [ ] test deprecation messages/old attribute access
- [ ] update CHANGELOG: one entry in Changes (use .results) and one entry in Deprecations (attribute access to be removed in 3.0.0)

Note: needs to be done in 2.0.0 if #3277 gets merged.

**Comment by orbeckst** [comment]
PR #3277 was merged so this one needs to happen.
