### ISSUE TITLE
Issue with importing MDAnalysis

### ISSUE THREAD

**Issue by lochanaranatunga** [MDAnalysis/mdanalysis#3286]
I have used MDAnalysis in google colabs with mini conda and it was working well. But now when I am tring to import MDAnalysis this error popping up

**This is the code**

!wget -O mini.sh https://repo.anaconda.com/miniconda/Miniconda3-4.6.14-Linux-x86_64.sh 
!bash ./mini.sh -b -f -p /usr/local
!conda install -q -y --prefix /usr/local -c conda-forge mdanalysis
import sys
sys.path.append('/usr/local/lib/python3.7/site-packages/')
import MDAnalysis as mda

**Error** 

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-4-48ef76e6a780> in <module>()
----> 1 import MDAnalysis as mda

3 frames
/usr/local/lib/python3.7/site-packages/MDAnalysis/lib/util.py in <module>()
    209 from ..exceptions import StreamWarning, DuplicateWarning
    210 try:
--> 211     from ._cutil import unique_int_1d
    212 except ImportError:
    213     raise ImportError("MDAnalysis not installed properly. "

MDAnalysis/lib/_cutil.pyx in init MDAnalysis.lib._cutil()

ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject

**Comment by orbeckst** [comment]
I am closing this issue as this is something that could be discussed in our forums first. At the moment there's not enough information to indicate that this is an MDAnalysis bug.

Feel free to request that this issue be re-opened.
