### ISSUE TITLE
Nose testing, plugins, and the use of numpy.testing

### ISSUE THREAD

**Issue by mnmelo** [MDAnalysis/mdanalysis#331]
Sorry for the long post. Please bear with me because I need your guidance!

In trying to enhance testing to perform memleak detection (#326) I found that the only way to fully extend `nose` is through plugins.
Other approaches using `setUp` and `tearDown` fixtures might work but seem at the moment very hackish and too intrusive (from the discussion in #326: we want to be able to memleak test, possibly on a test-by-test basis, but we shouldn't be forced to do so every time we test nor for all tests.)

Now, `nose` plugins are great but in order for `nose` to use them they must be either:
1- A package that's installed system-wide (or at least in the user's package repository);
2- Loaded at runtime by the script that calls `nose.main()`.

I think we can all agree that option 1 is overkill and unnecessarily messy. Option 2 holds promise, but there is, of course, a catch: tests must be run from a script. This means that running `nosetests MDAnalysisTests` from the command-line won't load the plugin since no launch script will be run.

So, any advance in this front would require breaking the command-line usability of `nosetests` and testing would have to be done by running `MDAnalysis.tests.test()` from within a python script in which the plugin(s) are loaded. (`nosetests` is also just a python script, but a very simple one that can't load any extra plugins).

A similar issue happened with the `KnownFailure` plugin from `numpy`. We have the decorators in place, the plugin is there to output `K` instead of `S`, and the wiki even gives examples where the output has `K` and `KNOWNFAIL`. But commit 073b075dd3ec980eacd7920c3ea747cfe5ed18ca shows that we ditched that because `nosetests` bypasses the loading of `numpy`'s plugins.

What can we do? I see some ways out:
2.1- We break the use of `nosetests` from the command-line and freely use plugins;
2.2- We try to implement plugins in a way that, when `nosetests` is called from the command-line and the plugins aren't loaded tests still work fine, but with limited functionality (for instance, the `KnownFailure` plugin falling back to the `SKIP` behavior we have now).

Option 2.1 is simple to implement and doesn't even mean we can no longer run tests from the command-line. It's enough to write up a slightly smarter version of `nosetests` that preloads all our plugins. We could even call it `nosetests` just the same and have it live in our `MDAnalysisTests` package dir.
This also means that travis building shouldn't be affected; we need only run this script instead of the dumb `nosetests`.

Option 2.2 is probably the most friendly to all, but entails more work for current and future plugins. My idea is that we can set some flags in the testing environment depending on whether plugins are loaded, and then have the tests behave accordingly.

The options are more complementary than alternative: we can have option 2.2 and still have the script that fires up the plugin-enabled testing.

Personally, I lean more towards 2.1 but ultimately I think this depends on how our devs typically run the tests. So please, opinions!

**Comment by mnmelo** [comment]
I'm doing some changes and I'm actually being able to use external plugins, but still cleanly fallback to vanilla behavior when running from the command-line `nosetests`. I guess option 2.2 is viable after all.

Updates soon.

**Comment by tylerjereddy** [comment]
Also, worth checking to ensure that both serial and parallel versions of the unit tests continue to remain well-behaved with any adjustments. It is quite nice to be able to run a ~90 second parallel test of the full suite (minus whatever plugin stuff is added) at the command line.

**Comment by orbeckst** [comment]
Ultimately, travis-ci has to work because it is quickly becoming the touch stone for decisions to merge, release, etc.

**Comment by orbeckst** [comment]
PS: @tylerjereddy – I totally agree with you
```
nosetests -v --parallel-processes=24 --process-timeout=120
```
took 40 seconds vs ~30 Mins in serial. (I added this also to the intro of the [UnitTests](/MDAnalysis/mdanalysis/wiki/UnitTests) page. (Btw, I cleaned up that wiki page a little bit but much more could be done, including moving details into a separate page or splitting it into a page for users and one for devs.)

**Comment by mnmelo** [comment]
Not to worry, I'm trying to keep everyone's usage in mind.

What I have so far (code to be uploaded soon for scrutiny, once I finish up below):
- External plugins can be loaded (including our own or numpy's). This means I can now again use `KnownFailure` numpy plugin. I went ahead and also implemented a stderr capturing plugin, so that we can have neat dotted output without all that noise (all customizable, of course). All these are now in a neat `plugins` submodule.
- Invocation from the command-line with `nosetests` works just the same, falling back to a plugin-less experience.
- Multiprocess testing works fine with either approach.
- The memleak testing plugin (the reason for this whole overhaul) is almost done. It can only do a test-by-test check but it's not intrusive and it's up to the developer to ask for it (`--with-memleak`). The only remaining problem is that, since it can only test for leaks *post-facto*, the error display is a bit off (namely, if the test leaks you still get an `ok` or `.`, and only then is the error printed). Final accounting still comes out ok, so this is mostly cosmetic.

I'll try to clean that last part up and submit asap.
Incidentally, do any `nose` gurus out there want to chip in on how to delay the `printLabel` call until the `stopTest` calls?
My approach is to try and replace its function so that it writes to a buffer. If a memleak is later detected in `stopTest`, I print my error, otherwise I print the `printLabel` buffer.

**Comment by richardjgowers** [comment]
I don't think errors happening after the test are a problem, the check is done after the actual test, so pass then fail tells me the test itself passed but didn't clean up properly.

**Comment by mnmelo** [comment]
Yup, I thought of claiming that too in order to have less work, but then I thought it only makes sense to report memleaks for tests that finish cleanly (no point in doing it for a case that's broken anyway).
