### ISSUE TITLE
Improve HELANAL docstring

### ISSUE THREAD

**Issue by PicoCentauri** [MDAnalysis/mdanalysis#3313]
## Is your feature request related to a problem? ##

Following the discussion of https://github.com/MDAnalysis/mdanalysis/pull/3308#r633977107 the docstring of the HELANAL class could be improved. First of all 

https://github.com/MDAnalysis/mdanalysis/blob/e6b3c2fe208c506b6f61b9f9d58f46be9d09e22d/package/MDAnalysis/analysis/helix_analysis.py#L309-L310

should mention that this only is of use when `len(groups) > 1`. Additionally, an example in the module docstring would be great.

## Describe the solution you'd like ##

Improve the docstring.

## Describe alternatives you've considered ##

 Leave everything as it is

**Comment by ojeda-e** [comment]
I think this is a good `good first issue` too @lilyminium

**Comment by robotjellyzone** [comment]
Hi, @PicoCentauri @IAlibay can you please tell me where can I get the example to be added to the module docstring? also, in this task, I just have to add a comment that `len(groups)>1` & example right?

**Comment by PicoCentauri** [comment]
> Hi, can you please tell me where can I get the example to be added to the module docstring?

For a proper example you may take a look at the test cases for multiple groups here 

https://github.com/MDAnalysis/mdanalysis/blob/54d9e4e4425349aa9876d00614a032536d565588/testsuite/MDAnalysisTests/analysis/test_helix_analysis.py#L382-L391

and here

https://github.com/MDAnalysis/mdanalysis/blob/54d9e4e4425349aa9876d00614a032536d565588/testsuite/MDAnalysisTests/analysis/test_helix_analysis.py#L411-L435

>  also, in this task, I just have to add a comment that I just have to add a comment that len(groups)>1 & example right?

Exactly, inform the user that this option only is active if more than 1 `select` string is given.

**Comment by robotjellyzone** [comment]
> > Hi, can you please tell me where can I get the example to be added to the module docstring?
> 
> For a proper example you may take a look at the test cases for multiple groups here
> 
> https://github.com/MDAnalysis/mdanalysis/blob/54d9e4e4425349aa9876d00614a032536d565588/testsuite/MDAnalysisTests/analysis/test_helix_analysis.py#L382-L391
> 
> and here
> 
> https://github.com/MDAnalysis/mdanalysis/blob/54d9e4e4425349aa9876d00614a032536d565588/testsuite/MDAnalysisTests/analysis/test_helix_analysis.py#L411-L435
> 
> > also, in this task, I just have to add a comment that I just have to add a comment that len(groups)>1 & example right?
> 
> Exactly, inform the user that this option only is active if more than 1 `select` string is given.

also @PicoCentauri , can you please tell me at what position the example must be added ? should i place it there in the parameter section only where split_residue_sequences desciption is written?

**Comment by robotjellyzone** [comment]
is this comment & example fine @PicoCentauri @micaela-matta  @lilyminium  ? if it will be fine then i will push my commits

![image](https://user-images.githubusercontent.com/36916536/163432007-f5c7ec7d-3f74-4d94-b4ed-2fb458b4f398.png)

**Comment by PicoCentauri** [comment]
This looks good for the beginning. Can you create a PR and I can give some detailed comments.
