### ISSUE TITLE
"smarts" selection keywork issue an advice I cannot follow if the structure has no hydrogens

### ISSUE THREAD

**Issue by jbarnoud** [MDAnalysis/mdanalysis#3319]
## Expected behavior ##

When selecting atoms using the `smarts` keyword on a system that does not have hydrogen it either:

* just works
* tells me it cannot work
* tells me how to make it work

## Actual behavior ##

I get an error message that gives me an advice that I cannot follow:
```
AttributeError: No hydrogen atom could be found in the topology, but the converter requires all hydrogens to be explicit. You can use the parameter ``NoImplicit=False`` when using the converter to allow implicit hydrogens and disable inferring bond orders and charges. You can also use ``force=True`` to ignore this error.
```

I cannot pass the suggested keywords to `select_atoms`.

## Code to reproduce the behavior ##

``` python
import MDAnalysis as mda
u = mda.fetch_mmtf('3cs9')

# MMTF does not fill the elements attribute
u.add_TopologyAttr('elements', u.atoms.types)
u.select_atoms('smarts c3ccncc3c4nc(Nc1cc(NC(=O)c2ccccc2)ccc1)ncc4')
```

## Current version of MDAnalysis ##

- Which version are you using? '2.0.0-dev0'
- Which version of Python (`python -V`)? '3.7.6 | packaged by conda-forge | (default, Jan  7 2020, 21:48:41) [MSC v.1916 64 bit (AMD64)]'
- Which operating system? Windows

**Comment by cbouy** [comment]
@jbarnoud #3324 will fix this!
However once this is merged, your current selection will be empty as your SMARTS query specifies aromaticity (lowercase atoms) and bond order (`=O`), but these will not be present in the converted molecule as you will be skipping them when using `NoImplicit=False`
Using `C3CCNCC3C4CC(NC1CC(NC(O)C2CCCCC2)CCC1)NCC4` should work though
