### ISSUE TITLE
Deprecation Warning in MDAnalysis.lib.nsgrid.FastNS

### ISSUE THREAD

**Issue by pitorodoptusdaktus** [MDAnalysis/mdanalysis#3321]
## Expected behavior ##
When FastNS function is used, the resulting neighbor query is as expected. However, even without using any methods of the function, a deprecation warning is raised.

## Actual behavior ##
The deprecation warning says somewhere in the code, 'np.int', which is an alias for python int, is used instead of python int, np.int32, or np.int64. 

Warning itself:
DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

## Code to reproduce the behavior ##
I couldn't find where it's raised from. However, according to the warning, we can say that all the np.int data types should be replaced by either python int, np.int32, or np.int64. 

## Current version of MDAnalysis ##

- 1.0.0
- 3.9.2
- Windows 10

**Comment by IAlibay** [comment]
@pitorodoptusdaktus can you try upgrading to 1.1.1? This should be fixed in that release.

Also python 3.9 is not supported by the 1.x branch, 1.0.0 allowed it purely because we didn't cap the maximum version.

**Comment by orbeckst** [comment]
@pitorodoptusdaktus did the upgrade solve the issue?

Note that the upgrade from 1.0.0 to 1.1.1 is highly recommended due to critical fixes in the neighbor searching code.

**Comment by orbeckst** [comment]
I am closing this issue as it should be fixed in 1.1.1. If you find out that this is not the case, please comment here and we will re-open. Thank you.

**Comment by pitorodoptusdaktus** [comment]
Sorry for the late comment; I checked it, and it is fixed. 

Thank you.
