### ISSUE TITLE
Check the use of `make_whole` in BAT

### ISSUE THREAD

**Issue by IAlibay** [MDAnalysis/mdanalysis#3326]
Follow up from #3132 

In #3132 we changed the BAT.py code such that `make_whole` is applied when dimensions is `None`. Before the condition was `if (self._root.dimensions[:3] == 0).any()`.

The assumption is that this was the intended behaviour. We should double check this. @daveminh could you check this please?

**Comment by orbeckst** [comment]
Thanks @daveminh , then we can close this issue because everything is correct.
