### ISSUE TITLE
HOOMD XML topology parser

### ISSUE THREAD

**Issue by khuston** [MDAnalysis/mdanalysis#333]
MDAnalysis seems to be missing a HOOMD XML topology parser. I found out it's not too hard writing one  using the XML ElementTree API (part of the Python standard library). One issue is that HOOMD XML format doesn't include data nodes for atom names, residue ids, or residue names:
http://codeblue.umich.edu/hoomd-blue/doc/page_xml_file_format.html
so presumably they would have to be given placeholder values, or copied from some other value like the atom type.

```python
    import xml.etree.ElementTree as ET

    class HoomdXMLParser(TopologyReader):
        def parse(self):
            tree = ET.parse(self.filename)
            root = tree.getroot()
            configuration = root.find('configuration')
            natoms = int(configuration.get('natoms'))
```
Filling out the attributes, checking that the number of values equals the number of atoms
```python
        try:
            mass = configuration.find('mass')
            masses = [float(x) for x in mass.text.strip().split('\n')]
            if len(masses) != 0 and len(masses) != natoms:
                raise IOError("Number of masses is neither zero nor natoms")
        except:
            for elem in elems:
                masses.append(get_atom_mass(elem))
```
Returning the structure
```python
        for i in range(natoms):
            atoms.append(Atom(i, names[i], atypes[i], resname, resid, segid, masses[i], charges[i], universe=self._u))
        structure = {'atoms': atoms}
        return structure
```
With this kind of topology parser, MDAnalysis is able to read in a DCD trajectory using a HOOMD XML topology. It'd be nice if such a parser were in the main release.

**Comment by orbeckst** [comment]
We're always keen to add new formats but without someone of the core devs using it, we very much rely on people like you to get the work started. If you can implement it and do a pull request we will very likely add it.

Any code that goes into the core is scrutinized extra carefully, as described under [Contributing Code](https://github.com/MDAnalysis/mdanalysis/wiki/ContributingCode). We'll need unit tests (including small example input files that will become part of the unit tests) and of course the new feature should not break anything. Dependencies on the standard lib are fine.

There's also a new feature where you can build your Reader outside MDAnalysis and then pass it as a "format" to `Universe` (@richardjgowers can say more about this).

**Comment by richardjgowers** [comment]
Hey Kyle

Sounds like a good idea, and what you've written will probably work fine.  Missing data is ok, just make sure it's got proper placeholder values and that the lack of info there is documented.

You should be able to test your reader by passing the class as a keyword argument to the Universe construction:

``` python
class HoomdXMLParser(TopologyReader):
    def parse(self):
        # stuff

import MDAnalysis as mda

u = mda.Universe('topology.xml', 'traj.dcd', topology_format=HoomdXMLParser)

```

If you can get this working, then I can guide you through the rest of putting it into MDAnalysis, it would make a great addition.

Richard

**Comment by khuston** [comment]
Nice, I didn't know about the topology_format keyword argument. It seems to work. The following runs without problem, after which I'm able to access the atom positions read in from the dcd file, and select by atom type.

    # coding: utf-8
    import MDAnalysis as mda
    TopologyReader = mda.topology.base.TopologyReader
    get_atom_mass = mda.topology.core.get_atom_mass
    guess_atom_charge = mda.topology.core.guess_atom_charge
    guess_atom_element = mda.topology.core.guess_atom_element
    Atom = mda.core.AtomGroup.Atom
    import xml.etree.ElementTree as ET
    
    class HoomdXMLParser(TopologyReader):
        def parse(self):
            ...

    u = mda.Universe('init_BOX_768_4.xml','trajectory_768_4.dcd',topology_format=HoomdXMLParser)

I was also able to modify \_\_init\_\_.py in the topology folder, so the following works without error:

    u = mda.Universe('topology.xml', 'traj.dcd')

But I don't know whether there's more to adding a topology reader than that. I haven't written any unit tests before, so I'll have to read about that.

**Comment by richardjgowers** [comment]
Looking promising.  If you've dropped a file like `HoomdXMLParser.py` into `MDAnalysis/topology/`, next to the other parsers and imported that into the `__init__` there, then I think that's everything.

So for unit tests, there's a pattern you can copy.  In `testsuite/MDAnalysisTests/test_topology` there's a class which defines the tests that all topology parsers must pass.

https://github.com/MDAnalysis/mdanalysis/blob/develop/testsuite/MDAnalysisTests/test_topology.py#L146

You then define a class which just has a few reference variables:

https://github.com/MDAnalysis/mdanalysis/blob/develop/testsuite/MDAnalysisTests/test_topology.py#L191

These define both the test file, and some expected results (eg how many atoms should your parser find)

Finally, you create a class which mixes these two, which makes a complete set of tests (ie the tests and the expected answers)

https://github.com/MDAnalysis/mdanalysis/blob/develop/testsuite/MDAnalysisTests/test_topology.py#L202

Our testing method (nosetests) looks at names to determine what is a test, so classes beginning with `Test` and methods/functions beginning with `test_` get treated like tests.

The other (possibly) confusing thing there is how the datafiles (the `.xml` file) are defined.  All the files for the tests are placed in `testsuite/MDAnalysisTests/data/` and then defined in this file:

https://github.com/MDAnalysis/mdanalysis/blob/develop/testsuite/MDAnalysisTests/datafiles.py

And then you import that handle into `test_topology`.

Hopefully that helps!

**Comment by khuston** [comment]
Thanks for those very detailed instructions. nosetests ran without any problems, so I changed the reference number of atoms to make sure the test actually ran, and indeed it failed when using the incorrect number. Are any tests needed beyond the base _TestTopology?

    class RefHoomdXML(object):
        """Hoomd XML test data and answers
        """
        topology = HoomdXMLdata
        parser = MDAnalysis.topology.HoomdXMLParser.HoomdXMLParser
        ref_numatoms = 769
        ref_numresidues = 1
    
    class TestHoomdXML(_TestTopology, RefHoomdXML):
        """Testing Hoomd XML file"""

**Comment by richardjgowers** [comment]
Cool cool.  I think it's easiest at this point if you start a pull request, and we can see what extra tests might be appropriate.

https://github.com/MDAnalysis/mdanalysis/wiki/ContributingCode

**Comment by orbeckst** [comment]
With the merge of #335 this is done.
