### ISSUE TITLE
TRRWriter doesn't use ts.data['step'] when copying TRR file

### ISSUE THREAD

**Issue by edisj** [MDAnalysis/mdanalysis#3350]
I'm not entirely sure if this is a bug because I'm not entirely sure what `ts.data['step']` is _supposed_ to be. But in any case, I think copying a file by writing the entire thing to a new file should maintain all of the data in the original file, which in this case it's not.

## Expected behavior ##

Writing an entire trajectory to a new file should maintain all of the data.

## Actual behavior ##

The `ts.data['step']` information is lost when copying a TRR file by writing with MDAnalysis

## Code to reproduce the behavior ##

``` python
import MDAnalysis as mda
from MDAnalysis.tests.datafiles import TPR_xvf, TRR_xvf

u = mda.Universe(TPR_xvf, TRR_xvf)

for ts in u.trajectory:
    print (ts.data['step'])
0
25000
50000

with mda.Writer('copied_file.trr', n_atoms=u.trajectory.n_atoms) as W:
    for ts in u.trajectory:
        W.write(u)

copied_u = mda.Universe(TPR_xvf, 'copied_file.trr')

# now has different steps
for ts in copied_u.trajectory:
    print (ts.data['step'])
0
1
2

```

## Current version of MDAnalysis ##

- Which version are you using? (run `python -c "import MDAnalysis as mda; print(mda.__version__)"`)
2.0.0-dev0
- Which version of Python (`python -V`)?
Python 3.8.5
- Which operating system?
Windows 10 Home

**Comment by edisj** [comment]
Sorry I should have searched the issues earlier but this looks like the same issue as  https://github.com/MDAnalysis/mdanalysis/issues/1101

**Comment by richardjgowers** [comment]
@edisj I *think* `ts.data` is basically a dict where anything non-standard is thrown.  E.g. this value is in the file, but it doesn't fit cleanly into a field in `Timestep`.  I think the issue here is that `TRRWriter` should be checking if `ts.data['step']` exists and using that instead of (what I assume is currently) `ts.frame`.

For clarity we use `ts.frame` is the index of the frame within the trajectory, which is different from the integrator timestep.

**Comment by hmacdope** [comment]
From my experience with `step` in the TNG format i'm fairly sure it is the integration timestep in ps.

**Comment by ianmkenney** [comment]
@richardjgowers see PR #3432, that should have fixed it. The timestep data is now the same for all frames.

``` python
import MDAnalysis as mda
from pathlib import Path

test_datadir = Path('beckstein/Library/mdanalysis/testsuite/MDAnalysisTests/data/')

def load_test_universe():
    return mda.Universe(str(test_datadir / 'adk_oplsaa.gro'), str(test_datadir / 'adk_oplsaa.trr'))

def load_new_universe():
    return mda.Universe(str(test_datadir / 'adk_oplsaa.gro'), 'new.trr')

def write_traj(u, outfile):
    with mda.Writer(outfile, n_atoms=u.trajectory.n_atoms) as W:
        for ts in u.trajectory:
            W.write(u)

if __name__ == "__main__":
    u = load_test_universe()
    write_traj(u, 'new.trr')
    u_new = load_new_universe()

    assert all([ts.data == ts_new.data for 
                ts, ts_new in zip(u.trajectory, u_new.trajectory)])
```
