### ISSUE TITLE
Doc error

### ISSUE THREAD

**Issue by xiki-tempula** [MDAnalysis/mdanalysis#3355]
## Expected behavior ##
In the web page https://userguide.mdanalysis.org/stable/installation.html#development-versions

it is said that 

```
git clone https://github.com/MDAnalysis/mdanalysis
cd mdanalysis
# assuming you have already installed required dependencies
pip install -e .
```

which should be

```
git clone https://github.com/MDAnalysis/mdanalysis
cd mdanalysis/package
# assuming you have already installed required dependencies
pip install -e .
```

**Comment by lilyminium** [comment]
Thanks @xiki-tempula, I opened this issue in the User Guide repository https://github.com/MDAnalysis/UserGuide/issues/160
