### ISSUE TITLE
Document id selection keyword

### ISSUE THREAD

**Issue by lilyminium** [MDAnalysis/mdanalysis#3359]
## Is your feature request related to a problem? ##

The selection docs have `bynum` but not `id`. `id` is more helpful in the sense that it actually selects the right `id` values, unlike `bynum` which is just `index` + 1.

## Describe the solution you'd like ##

Document `id`.

**Comment by IAlibay** [comment]
Reviving this conversation, what's the difference between `id` and `index`?

**Comment by lilyminium** [comment]
`id` is a topology attribute that is a label. You could define it to be anything you like. Conventionally, it corresponds to the serial number in the PDB format, i.e. starts from 1, but because it's a label it can skip numbers etc. `index` is the underlying position of where the atom is within the linear array of atoms in the universe. You cannot set it and it must be continuous. It corresponds to the meaning of indices in the Python structures of lists and arrays. It starts from 0 as follows Python convention. `bynum` is the same thing as an index in R, i.e. starts from 1.

The same difference applies to resindex and resnum/resid, although selection for resid includes icodes.

```python
>>> import MDAnalysis as mda
>>> from MDAnalysis.tests.datafiles import PDB
>>> u = mda.Universe(PDB)
/Users/lily/pydev/mdanalysis/package/MDAnalysis/topology/PDBParser.py:315: UserWarning: Element information is missing, elements attribute will not be populated. If needed these can be guessed using MDAnalysis.topology.guessers.
  warnings.warn("Element information is missing, elements attribute "
>>> u.atoms.ids = 0
>>> u.atoms.ids
array([0, 0, 0, ..., 0, 0, 0])
>>> u.atoms.indices = 1
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/lily/pydev/mdanalysis/package/MDAnalysis/core/groups.py", line 286, in __setattr__
    super(_TopologyAttrContainer, self).__setattr__(attr, value)
  File "/Users/lily/pydev/mdanalysis/package/MDAnalysis/core/groups.py", line 249, in setter
    return attr.__setitem__(self, values)
  File "/Users/lily/pydev/mdanalysis/package/MDAnalysis/core/topologyattrs.py", line 464, in __setitem__
    return self.set_atoms(group, values)
  File "/Users/lily/pydev/mdanalysis/package/MDAnalysis/core/topologyattrs.py", line 523, in set_atoms
    raise AttributeError("Atom indices are fixed; they cannot be reset")
AttributeError: Atom indices are fixed; they cannot be reset
```

**Comment by orbeckst** [comment]
Your explanation of *id* vs *index* would be helpful in the docs. And then it makes sense to advertise *id*, too. In particular, anyone working with PDB files would probably be happy to hear that the PDB SERIAL is captured in *id* (is it?).

**Comment by umak1106** [comment]
Hello , I am Uma Kadam an Outreachy applicant . I would like to work on this issue if you allow . Could you also please give me a link to your selection docs ? 
@IAlibay

**Comment by orbeckst** [comment]
Hello @umak1106 , you don't have to ask to work on an issue. We do not "reserve issues". Rather, we review the first pull request that references an issue. So your next step is to clone the MDAnalysis repository, fix the issue in your local repo, and **create a Pull Request** (and mention this issue #3359 number in the text).

In the User Guide, look under [Contributing to the main code base](https://userguide.mdanalysis.org/stable/contributing_code.html) for how to get started developing on MDAnalysis.

**Comment by umak1106** [comment]
> Hello @umak1106 , you don't have to ask to work on an issue. We do not "reserve issues". Rather, we review the first pull request that references an issue. So your next step is to clone the MDAnalysis repository, fix the issue in your local repo, and **create a Pull Request** (and mention this issue #3359 number in the text).
> 
> In the User Guide, look under [Contributing to the main code base](https://userguide.mdanalysis.org/stable/contributing_code.html) for how to get started developing on MDAnalysis.

According to my understanding of the id selection keyword I have tried to document it in the selection docs .Kindly tell me what changes I am supposed to make in my PR.
