### ISSUE TITLE
InterRDF and InterRDF_s are not symmetric

### ISSUE THREAD

**Issue by gdonval** [MDAnalysis/mdanalysis#3362]
## Expected behavior ##

The (very familiar and classic) RDF equation from the documentation is symmetric with respect to the inputs: the RDF between atom `A` and atom `B` should be the same as the RDF between atom `B` and atom `A`.

## Actual behavior ##

```
rdf = InterRDF_s(universe, [[all_atom1, all_atom2]])
rdf.run()
assert np.allclose(rdf.rdf[0][1, 0], rdf.rdf[0][0, 1])
```

That assertion fails.

## Current version of MDAnalysis ##

- Which version are you using? 1.1.1
- Which version of Python (`python -V`)? 3.8
- Which operating system? Linux

## Examples ##

Those are illustrations of the problem:

- `plt.plot(rdf.bins, rdf.rdf[0][1, 0])`:

![image](https://user-images.githubusercontent.com/2644113/125687185-fd0295cc-877e-44b8-9ec0-4f09bb0ff364.png)

- `plt.plot(rdf.bins, rdf.rdf[0][0, 1])`:

![image](https://user-images.githubusercontent.com/2644113/125687227-dfb01c96-7852-42f6-ab0a-1cacfd235edd.png)

**Comment by gdonval** [comment]
The bug was elsewhere, no problem here. Closing.

**Comment by IAlibay** [comment]
> The bug was elsewhere, no problem here. Closing.

@gdonval please do post about the issue/resolution you encountered here if you think it's relevant. Might help the next person accidentally encountering the same issue.

**Comment by gdonval** [comment]
Sure, the problem stemmed from the fact that I was iterating over a list of residues in this fashion:

```
for i, res1 in enumerate(universe.residues):
    for j, res2 in enumerate(universe.residues):
        if i <= j:
            continue
        rdf = InterRDF(res1.atoms, res2.atoms)
        [...]
```

Everything works well then. After all in this way, I iterate over all possible combinations (except self-self but that's expected).

**But** the variant with `InterRDF_s(universe, [[res1.atoms, res2.atoms]])` or, says, `InterRDF(res1.atoms[0:1], res2.atoms[1:2])` *are incorrect*. In those cases, some combinations are missing and the correct solution, in the case of `InterRDF_s` is obtained by averaging `rdf.rdf[0][i, j]` and `rdf.rdf[0][j, i]` for all i, j (or by changing `i <= j` by `i  == j` above).

So all a silly mistake because I can't get my combinations right.
