### ISSUE TITLE
Investigate pins for various CI components (pytest-cov, coverage, msmb_theme)

### ISSUE THREAD

**Issue by IAlibay** [MDAnalysis/mdanalysis#3372]
Follow up from #3369 
Related to #3224 

Our docs build infrastructure is starting to be a bit flaky, particularly in #3369 we've had to pin pytest-cov due to some dependency resolution issues we were having when installing it at the same time as the sphinx components.

We should aim to check a) if all the pins are still necessary, b) what steps we should take to remove these pins.

My understanding is that some of this is related to the fact that we can't upgrade to the latest sphinx (see #3224), so we probably will want to fix that first.

**Comment by orbeckst** [comment]
Maybe recent doc_build failure should have been mentione here instead of https://github.com/MDAnalysis/mdanalysis/issues/3224#issuecomment-926016473 ?

**Comment by IAlibay** [comment]
> Maybe recent doc_build failure should have been mentione here instead of [#3224 (comment)](https://github.com/MDAnalysis/mdanalysis/issues/3224#issuecomment-926016473) ?

Both are pretty much appropriate 🙃 

The simplest answer is to pin temporarily, but we really need to sit down and unpin everything and see what's breaking everything.
