### ISSUE TITLE
knownfailure decorator isn't always honored.

### ISSUE THREAD

**Issue by mnmelo** [MDAnalysis/mdanalysis#338]
In trying to wrap up #331 I found out that the `@knownfailure` decorator sometimes causes a test to not be run (not to confuse with run but skipped if an exception occurs, which is the function of the decorator).

The following, in particular, doesn't work as expected:
Create a MDAnalysisTests/test_kf.py with the following
```python
from MDAnalysisTests import knownfailure
from numpy.testing import assert_, TestCase

class TestKF(TestCase):
    def test_1():
        pass

    @knownfailure
    def test_2():
        assert_(False)
```

running `nosetests MDAnalysisTests/test_kf.py` yields the following:
```
.
----------------------------------------------------------------------
Ran 1 test in 0.001s

OK
```
Notice that only one test was run and there's no mention to `test_2` being skipped. If I make nose very verbose I can see that `test_2` gets its name clobbered by the name of the function returned by the decorator (`knownfailure_decorator`), and therefore doesn't get selected:
```
nose.selector: DEBUG: wantMethod <unbound method TestKF.test_1>? True
nose.selector: DEBUG: wantMethod <unbound method TestKF.knownfailure_decorator>? None
```

I'm trying to track this down, and understand why it works on some occasions but not in others (after all, the decorator does work in other places in the test suite). It's not a very serious problem because the consequence is that we don't run a test that were going to skip anyway. We miss output, and tracking of tests that should fail but don't.

For reference I tested this in `develop` and `master`, with same results.

**Comment by mnmelo** [comment]
Ok, found the problem: since we're wrapping the decorator in a decorator-creating function, we actually have to always write the decorator as `@knownfailure()` instead of just `@knownfailure`. The cases where we were passing arguments to `@knownfailure` (non-default exception to catch, for instance) work fine and are properly reported as `SKIP`.

As an example, `test_atomgroups.py` has 4 occurrences of the wrong use of the decorator, but running `nosetests` on it returns clean, without even a `SKIP` count, because the tests were simply ignored.

I'll fix current usage, and point it out in the docs so future tests correctly use the decorator.

**Comment by mnmelo** [comment]
And with fixing this I already spotted a knownfailure that now passes on `MDAnalysisTests.test_atomgroup.TestAtomGroup.test_set_resname_single`.

The decorator was added with e01b6ec13ea39429e614d5c5f9445014a03df1f1, apparently related to #202. @richardjgowers, can you check if it is time to remove the decorator or if something is otherwise off?

**Comment by richardjgowers** [comment]
I think those are still open issues, so they just need to be changed to `@knownfailure()`

**Comment by richardjgowers** [comment]
Oh right, just reread this, if they pass then they're not known failures..... I think the `_many` ones should fail, but I think `_single` should pass.

**Comment by mnmelo** [comment]
Ok, I'll add that to the commit.
