### ISSUE TITLE
MOL2Parser requires ATOM optional fields

### ISSUE THREAD

**Issue by RMeli** [MDAnalysis/mdanalysis#3385]
## Expected behavior ##

I expect MDAnalysis to be able to parse standard MOL2 files.

## Actual behavior ##

If I understand correctly the [MOL2 standard](https://web.archive.org/web/*/http://chemyang.ccnu.edu.cn/ccb/server/AIMMS/mol2.pdf), a `<TRIPOS>ATOM` data line only requires the 6 following fields: `atom_id atom_name x y z atom_type`. However, the `MOL2Parser` expects also the following optional fields to be present `[subst_id [subst_name [charge [status_bit]]]]` (actually, only the first three; see #2318). 

## Code to reproduce the behavior ##

```python
from io import StringIO

import MDAnalysis as mda

print(mda.__version__)

mol2="""\
@<TRIPOS>MOLECULE
MOL2
2
SMALL
NO_CHARGES


@<TRIPOS>ATOM
  1 N1       6.8420     9.9900    22.7430 N.am
  2 N2       4.4000     9.1300    20.4710 N.am
"""

u = mda.Universe(StringIO(mol2), format='MOL2')
```

```
2.0.0-dev0
Traceback (most recent call last):
  File "/Users/rmeli/Documents/git/software/mdanalysis/package/MDAnalysis/core/universe.py", line 122, in _topology_from_file_like
    topology = p.parse(**kwargs)
  File "/Users/rmeli/Documents/git/software/mdanalysis/package/MDAnalysis/topology/MOL2Parser.py", line 153, in parse
    aid, name, x, y, z, atom_type, resid, resname, charge = a.split()[:9]
ValueError: not enough values to unpack (expected 9, got 6)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test2.py", line 20, in <module>
    u = mda.Universe(StringIO(mol2), format='MOL2')
  File "/Users/rmeli/Documents/git/software/mdanalysis/package/MDAnalysis/core/universe.py", line 338, in __init__
    **kwargs)
  File "/Users/rmeli/Documents/git/software/mdanalysis/package/MDAnalysis/core/universe.py", line 140, in _topology_from_file_like
    "Error: {2}".format(topology_file, parser, err))
ValueError: Failed to construct topology from file None with parser <class 'MDAnalysis.topology.MOL2Parser.MOL2Parser'>.
Error: not enough values to unpack (expected 9, got 6)
```

## Current version of MDAnalysis ##

- Which version are you using? `2.0.0-dev0`
- Which version of Python? `ython 3.7.10`
- Which operating system? `macOS 11.5.1`

## Additional Information

This is linked to #2318 and my fix in #2319 was only partial. Other fields should be optional (especially important if `NO_CHARGES` in `@<TRIPOS>MOLECULE` is present).

The problematic line is the following:

https://github.com/MDAnalysis/mdanalysis/blob/09f50ecc0c4425f089059b53d1f11edee9bbecb6/package/MDAnalysis/topology/MOL2Parser.py#L140

**Comment by orbeckst** [comment]
If no charges are present then I would expect the topology to *not contain charge information*. This is a much safer approach than trying to guess charges, which we cannot do well anyway. If the topology does not contain charges it will simply not have methods such as `total_charge()` but everything else (EDIT: that does not require charge information) will work.

@RMeli @IAlibay @richardjgowers @lilyminium does this sound sensible?

**Comment by IAlibay** [comment]
Not read the full context of this discussion, but yeah charge is an optional topology attribute, if there's no charge then we shouldn't guess it (which would require rdkit anyways)

**Comment by orbeckst** [comment]
Following up on https://github.com/MDAnalysis/mdanalysis/pull/3598#issuecomment-1087974402 : I *think* **resname** and **resid** are always required in our [topology system](https://docs.mdanalysis.org/stable/documentation_pages/core/topology.html) so using a default of "UNK" and 1 seems reasonable to me. (But I am happy to be corrected!)

**Comment by Mrqeoqqt** [comment]
Hi @IAlibay Should I discard the charge attribute when any of the charge is empty? Is there any possibility that the part of atoms in .mol2 file have charges but the others don't?

**Comment by RMeli** [comment]
> If no charges are present then I would expect the topology to not contain charge information.

Same, this is what I was trying to say in https://github.com/MDAnalysis/mdanalysis/pull/3598#discussion_r841588579

> I think resname and resid are always required in our [topology system](https://docs.mdanalysis.org/stable/documentation_pages/core/topology.html) so using a default of "UNK" and 1 seems reasonable to me.

I was not aware of this. If they are required fields, then the chosen default values are very sensible. But charges should be discarded (especially since they are optional).

**Comment by orbeckst** [comment]
On discord, @richardjgowers said:

> currently required are resnums, resids and segids, but not resnames.  XYZParser is good to look at since it's the most minimal data parser: https://github.com/MDAnalysis/mdanalysis/blob/develop/package/MDAnalysis/topology/XYZParser.py
> Hmm but strangely `Topology` never enforces this minimum set, but I'm imagining the selection language and elsewhere assumes they exist... A bit of a grey area I'll admit

@lilyminium pointed to the [list of canonical attributes](https://userguide.mdanalysis.org/stable/topology_system.html#canonical-attributes) and confirmed that **resname** is not essential.

This means that 
* resid = 1 is a good default
* resname can be left empty and then will not be included in the Topology; do *not* set it to a default value
* charges are optional so if not present, do *not* include in Topology (just as @RMeli said)

**Comment by orbeckst** [comment]
More discussion (https://github.com/MDAnalysis/mdanalysis/pull/3598#discussion_r843367930): At the moment I am proposing to fail with a `ValueError` if some lines contain optional data (such as a resname, aka subst_name) and others don't. From the definition for `@<TRIPOS>ATOM`
```
atom_id atom_name x y z atom_type [subst_id [subst_name [charge [status_bit]]]]
 ```
it looks as if this would be allowed but then things become difficult for our topology object and we would have to guess or set a resname for some atoms but not others, would need to check that a default resid (subst_id) is compatible with what we guessed, or for charge, would need to set some charges to 0 or guess while others were read from the file. I'd much rather have consistent handling of all optional data: If optional data values are present for one atom then they need to be present for all of them.

**Comment by RMeli** [comment]
> I'd much rather have consistent handling of all optional data: If optional data values are present for one atom then they need to be present for all of them.

I totally agree with this.
