### ISSUE TITLE
DOC: add citation file

### ISSUE THREAD

**Issue by tylerjereddy** [MDAnalysis/mdanalysis#3402]
Seems like a nice thing to do so we can get a link like below on our main GitHub page. Probably just needs a PR similar to https://github.com/scipy/scipy/pull/14630 with a `CITATION.bib` in repo root with the two main papers I suppose.

![image](https://user-images.githubusercontent.com/7903078/130548405-10136911-b16d-4143-bde6-3bc89358a022.png)

**Comment by IAlibay** [comment]
@lilyminium point out this (https://twitter.com/tgamblin/status/1420157496711208969) in the discord when it first got announced, not sure I follow the issue being discussed, it this something we need to account for?

**Comment by tylerjereddy** [comment]
Not sure--SciPy and NumPy both adopted a `.bib` file to get the link to show up a bit more prominently. That debate seems to be for a `.cff` file vs. a `.bib` file.

That said, many newer folks are now driving things forward with MDA now, so maybe some debate on the citation target to be had.

**Comment by orbeckst** [comment]
A MDA paper is overdue but until then we should just have our two primary citations available. We can switch it out as soon as we update our "what to cite".

Citation numbers have been really helpful for us to demonstrate impact so being clear about what to cite helps us.
