### ISSUE TITLE
Move ConverterBase to the `converters.base`?

### ISSUE THREAD

**Issue by IAlibay** [MDAnalysis/mdanalysis#3404]
Just having a look at things, and I realise that ConverterBase essentially is just a small subclass of IOBase, but I wonder if it might make more sense to have that in `converters.base` so that it's more logically situated?

**Comment by orbeckst** [comment]
yes – I noticed it when I was updating the docs for 2.0

**Comment by orbeckst** [comment]
Of course, we'll need to have a deprecated shim in it's old place until 3.0.

**Comment by orbeckst** [comment]
I'll just say that we want to do this and remove the proposal tag.

**Comment by orbeckst** [comment]
@ianmkenney please make sure that this issue is also on your TODO list. Thanks.
