### ISSUE TITLE
H5PY 3.4.0 causes H5MD writer tests fail with PermissionError on Windows (investigate temporary pin)

### ISSUE THREAD

**Issue by IAlibay** [MDAnalysis/mdanalysis#3406]
## Expected behavior ##

All tests pass.

## Actual behavior ##

For the Windows runners TestH5MDWriterWithRealTrajectory.test_write_with_drivers[core] fails due to a permission error in writing the H5MD file.

## Code to reproduce the behavior ##

See: https://dev.azure.com/mdanalysis/mdanalysis/_build/results?buildId=2576&view=logs&j=af49e0b6-b01c-50c5-fac7-b346db9f76f5&t=6e9d53c4-1948-52bf-f8ab-45d3eec15dc0&l=821

**Comment by orbeckst** [comment]
Do we have any inkling as to why?

@edisj ?

**Comment by edisj** [comment]
I’ll be home in ~1.5 hrs, can take a look then

**Comment by IAlibay** [comment]
I wonder if this is linked to the 3.4.0 release (it got released 4 days ago), no issues linked to this issue at this point though.

**Comment by IAlibay** [comment]
See #3407 - seems like an issue with the 3.4.0 release of h5py. If someone has the spare capacity / time we should report it upstream.

With regards to moving forward, it's probably best to just pin to <3.4.0?

**Comment by edisj** [comment]
That seems like the best short term fix to me. There was a bug fix listed here https://docs.h5py.org/en/latest/whatsnew/3.4.html relating to the `core` and `stdio` drivers and using `mode='a'`, however `H5MDWriter` only uses `mode='w'`. I looked through a few of the PRs linked and I haven't found anything to do specifically with Windows or `mode='w'`

**Comment by orbeckst** [comment]
Did we ever reproduce the failure locally?

Has anyone the time to bisect h5py releases to pinpoint the ones that fail? We could exclude known bad releases for #3711 (or separately).

**Comment by IAlibay** [comment]
It doesn't look like this is a thing anymore? Closing.
