### ISSUE TITLE
Change in AnalysisFromFunction API breaks example for in-memory creation of trajectory from sub-system

### ISSUE THREAD

**Issue by melomcr** [MDAnalysis/mdanalysis#3412]
## Expected behavior ##

According to the [documentation](https://docs.mdanalysis.org/2.0.0/documentation_pages/coordinates/memory.html#creating-an-in-memory-trajectory-of-a-sub-system), it should be possible to load coordinates for a sub-system of a loaded universe using the `AnalysisFromFunction` module and the following code (taken from the docs):

```
u = mda.Universe(PDB, XTC)
protein = u.select_atoms("protein")

u2 = mda.Merge(protein).load_new(
         AnalysisFromFunction(lambda ag: ag.positions.copy(),
                              protein).run().results,
         format=MemoryReader)
```

## Actual behavior ##

Using the same code and version 2.0 of MDAnalysis, the above code returns an error:
`TypeError: The input has to be a numpy.ndarray that corresponds to the layout specified by the 'order' keyword.`

## Proposed change to correct the behavior in the documentation ##

The problem comes from a change in the `AnalysisFromFunction` API,which does not return a numpy.ndarray with coordinates anymore, but returns a dictionary with three elements: "timeseries", "frames", and "times".
Therefore, the example can be fixed with a simple change: selecting the "timeseries" key from the results.

```
u = mda.Universe(PDB, XTC)
protein = u.select_atoms("protein")

u2 = mda.Merge(protein).load_new(
         AnalysisFromFunction(lambda ag: ag.positions.copy(),
                              protein).run().results['timeseries'],
         format=MemoryReader)
```

## Current version of MDAnalysis ##

MDAnalysis version: 2.0.0
Python version: 3.9.6
OS: Ubuntu 18.04.5 LTS

**Comment by IAlibay** [comment]
Thanks for reporting this, it sounds like a reasonable proposed change. Would you like to open a PR for this @melomcr ?

**Comment by melomcr** [comment]
Sure, @IAlibay , the PR is submitted. I just modified the relevant lines in the docs that used results from `AnalysisFromFunction`. I think that would be enough, but let me know if you feel like a highlighted "Note" warning about the API change would be necessary.
