### ISSUE TITLE
Move to container based infrastructure on Travis

### ISSUE THREAD

**Issue by richardjgowers** [MDAnalysis/mdanalysis#342]
Travis looks like it's moved to using a new system, which is better apparently.  The only change I think we need is we can't use `sudo` any more.

We can also cache things to speed up the build, which could also be useful.

http://docs.travis-ci.com/user/migrating-from-legacy/

**Comment by richardjgowers** [comment]
Build time went from 25 to 18 mins which is cool

**Comment by orbeckst** [comment]
Is it worthwhile to [enable a cache for pip](http://docs.travis-ci.com/user/caching/#pip-cache) ?

**Comment by orbeckst** [comment]
Ah – I guess that was a moot point, given that all other Python dependencies come with `miniconda`.

**Comment by richardjgowers** [comment]
Yeah I've not looked at using that cache too much yet.  There's probably some trickery we could use to make miniconda install into the cache.  Or because the apt packages are all cached in a way, we might be able to revert from using miniconda altogether. Might be worth looking into once we're doing py 2 & 3 builds
