### ISSUE TITLE
distance.analysis module not found

### ISSUE THREAD

**Issue by germanbarcenas** [MDAnalysis/mdanalysis#3427]
## Expected behavior ##
I want to use this function 
https://docs.mdanalysis.org/2.0.0/documentation_pages/analysis/distances.html?highlight=distance#MDAnalysis.analysis.distances.dist

I want to import this as 
'import MDAnalysis as mda'

## Actual behavior ##
MDA does not import this this module
`AttributeError: module 'MDAnalysis.analysis' has no attribute 'distances'`

## Code to reproduce the behavior ##

``` python
import MDAnalysis as mda
from MDAnalysis import analysis

distance21=mda.analysis.distances.dist(u.select_atoms(1:5)u.select_atoms(100:105))

```

## Current version of MDAnalysis ##
2.0.0

- Which version of Python (`python -V`)?
3.8.8
- Which operating system?
* Spyder version: 5.1.5 None
* Python version: 3.8.8 64-bit
* Qt version: 5.12.9
* PyQt5 version: 5.12.3
* Operating System: Windows 10

This is my first time posting here so any other general tips on asking the question would be appreciated. Thanks(: yall have made studying MD simulations much more accessible!

**Comment by lilyminium** [comment]
Hi @germanbarcenas, welcome to MDAnalysis! You just need to import the distances module from MDAnalysis.analysis, like:

```
from MDAnalysis.analysis import distances

distance21 = distances.dist(u.select_atoms(1:5)u.select_atoms(100:105))
```

If you have any other questions do feel free to reach us on the mailing list (https://groups.google.com/group/mdnalysis-discussion) or Discord server (https://discord.gg/fXTSfDJyxE)!

**Comment by germanbarcenas** [comment]
Ahh okay so it was just the syntax of importing the submodule that I wasn't getting. Okay thank you!
