### ISSUE TITLE
Move benchmarks to > 3.7

### ISSUE THREAD

**Issue by hmacdope** [MDAnalysis/mdanalysis#3430]
## Expected behavior ##

Since support has been dropped for  2.7 and 3.6  should bump the benchmarks from the current 2.7 python up to whatever version  is appropriate. 

This is  mainly a reminder to change the value in `asv.conf.json`  from:
```
    "pythons": ["2.7"],
```
to whatever version is appropriate once bench environment is setup.

Linked to https://github.com/MDAnalysis/benchmarks/issues/11

## Actual behavior ##

 tests fail to run unless pythons=2.7 is commented out.
## Code to reproduce the behavior ##

running the benchmarks with `asv run` or `asv continuous`

**Comment by orbeckst** [comment]
See also https://github.com/MDAnalysis/benchmarks/issues/11

**Comment by orbeckst** [comment]
https://github.com/MDAnalysis/benchmarks/issues/11 has been closed and the benchmarks are running again.

**Comment by orbeckst** [comment]
oops, have to fix this in MDA ...
