### ISSUE TITLE
Fail to select new segment using segid just added to the universe

### ISSUE THREAD

**Issue by rsu007-Ran** [MDAnalysis/mdanalysis#3437]
## Expected behavior ##

I was trying to add a new segment to the universe and select that segment from the universe. When I select the atoms assigned to the new segment by the previous step, python returns an index error.  

## Actual behavior ##

```
Traceback (most recent call last):
 File "<stdin>", line 1, in <module>
 File "~/python3.6/site-packages/MDAnalysis/core/universe.py", line 677, in select_
atoms
   return self.atoms.select_atoms(*args, **kwargs)
 File "~/python3.6/site-packages/MDAnalysis/core/groups.py", line 2916, in select_a
toms
   selections[0].apply(self))
 File "~/python3.6/site-packages/MDAnalysis/core/selection.py", line 173, in apply
   return func(self, group)
 File "~/python3.6/site-packages/MDAnalysis/core/selection.py", line 549, in apply
   nmidx = nmattr.nmidx[getattr(group, self.level)]
IndexError: index 2 is out of bounds for axis 0 with size 2
```

## Code to reproduce the behavior ##

```
>>> import MDAnalysis as mda
>>> from MDAnalysis.tests import datafiles as data

>>> u = mda.Universe(data.RNA_PSF, data.RNA_PDB)
>>> u.segments.segids
array(['POT', 'RNAA', 'SOLV'], dtype=object)

>>> atomP = u.add_Segment(segid='P')
>>> P_atoms = u.select_atoms("name P")
>>> P_atoms.residues.segments = atomP

>>> u.segments.segids
array(['POT', 'RNAA', 'SOLV', 'P'], dtype=object)

>>> u.select_atoms("segid P”)
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-22-201611c1d061> in <module>
----> 1 u.select_atoms("segid P”)
...
...
IndexError: index 3 is out of bounds for axis 0 with size 3
```
## Current version of MDAnalysis ##

- Which version are you using? (run `python -c "import MDAnalysis as mda; print(mda.__version__)"`)
- 1.1.1
- Which version of Python (`python -V`)?
- Python 3.6.13
- Which operating system?
- Linux Opensuse

**Comment by lilyminium** [comment]
Thanks for raising this with the example, @rsu007-Ran!

@richardjgowers this looks like the name dictionary isn't updating?

@rsu007-Ran if you need this to work fast, I think downgrading to the previous version (0.20.1?) may work.

**Comment by rsu007-Ran** [comment]
> @rsu007-Ran if you need this to work fast, I think downgrading to the previous version (0.20.1?) may work.

Thanks for advice, I will take a look into downgrading to previous version to see if it works

**Comment by richardjgowers** [comment]
@lilyminium yep, on it.
