### ISSUE TITLE
Using dcd file in Universe

### ISSUE THREAD

**Issue by devanshipandya** [MDAnalysis/mdanalysis#3439]
When I run:
u = MDAnalysis.Universe(psf, dcd)
where psf and dcd are my own topology and trajectory files loaded and from my computer and opened, I get the error:
'_io.TextIOWrapper' object has no attribute 'encode'

This error doesn't arise when I make a universe with just the psf file, is there anything I need to do in order to make the dcd file compatible?

**Comment by IAlibay** [comment]
@devanshipandya can you give us a bit more information about your system (operating system, python version) & MDAnalysis version?

Also what happens if you load one of the MDAnalysisTest DCD files?

That is, if you run:

```python
import MDAnalysis as mda
from MDAnalysisTests.datafiles import PSF, DCD

u = mda.Universe(PSF, DCD)
```

**Comment by devanshipandya** [comment]
Linux OS, MDAnalysis Version 0.18.0, Python 3.6
Running the test files works exactly as expected, but I want to be able to use my files. Thanks!!

**Comment by hmacdope** [comment]
@devanshipandya would you be able to attach your dcd file so I can investigate locally?

**Comment by devanshipandya** [comment]
Github doesn't support uploading .dcd files so i converted the dcd to txt and attached, let me know if you can see it!

**Comment by hmacdope** [comment]
I can't. You can make a post on the mailing list and attach it there. https://groups.google.com/g/mdnalysis-discussion

**Comment by devanshipandya** [comment]
Message posted with dcd file in onedrive link because it was too large to attach. thanks!

**Comment by orbeckst** [comment]
Have you tried a modern version of MDAnalysis, namely 1.1.1 or 2.0.0? Your version 0.18.0 is very out of date and even if there was a bug in it, we would not fix it and simply tell you to use a newer version. If the problem persists in 2.0.0 then we will consider it as a bug.

**Comment by orbeckst** [comment]
Did you manage to successfully read your DCD file in another program such as CHARMM or VMD?

**Comment by orbeckst** [comment]
@devanshipandya could you please provide more information?

**Comment by IAlibay** [comment]
This conversation has moved to the user list (https://groups.google.com/g/mdnalysis-discussion/c/lRX8_XTKv90) and given the lack of further responses I will be closing this issue.
