### ISSUE TITLE
Coverage fails with mda_nosetests

### ISSUE THREAD

**Issue by mnmelo** [MDAnalysis/mdanalysis#344]
I'm just bringing this into an issue after our discussion in PR #341.

The test overhaul broke the coverage accounting, and quite mysteriously so. However, after some wrong results I reported in PR #341 (I forgot to delete cached coverage results), I was able to solve the issue.

What happens is that MDAnalysis *mustn't* be loaded before the coverage check starts, since all that import code won't be run again under coverage's watch.

The loading of MDAnalysisTests is already pretty much independent of MDAnalysis. This is a GoodThing™ because we shouldn't run the testee before actually start monitoring for errors.
There's only two imports of MDAnalysis in `MDAnalysisTests.__init__.py`:
- an import of `MDAnalysis.lib.util.py`, which I can fix by making it happen only at individual test runtime;
- an import to check whether MDAnalysis' version is compatible with MDAnalysisTests'. I'm moving that into its own test.

We must further instate a ban on importing from MDAnalysis in `MDAnalysisTests.__init__.py`, `MDAnalysisTests.plugins.__init__.py` or any plugin code. I think that this is anyway good practice for what I mentioned above.

This also means that running tests with coverage from the interpreter will fail unless:
 1. MDAnalysisTests.run(argv=["--with-coverage","--cover-package=MDAnalysis"]) is used directly; and
 1. MDAnalysis hasn't been imported yet.

I'll be pushing soon and updating the wiki, but do give opinions.

**Comment by richardjgowers** [comment]
That's a nasty bug to find, but it does match what we saw with the coverage report; individual functions were being seen as run, but importing the module wasn't (all our `__init__` were "uncovered").
