### ISSUE TITLE
Add march=native build to cron job

### ISSUE THREAD

**Issue by hmacdope** [MDAnalysis/mdanalysis#3442]
## Is your feature request related to a problem? ##

Enabling of an advanced "march=native" build `setup.cfg` Issue #3428 PR #3429 means that it should be tested, including on ARM and PowerPC in the weekly cron job.

## Describe the solution you'd like ##

Add build(s) with `march=native` to the weekly cron job. We may need to have a git patch apply a change to setup.cfg OR have some way of enabling the march=native build independent of setup.cfg, eg a command line flag to setup.py.

**Comment by IAlibay** [comment]
The lazy person in me is just going to do a sed call, that's the least painful way.

**Comment by hmacdope** [comment]
@IAlibay @orbeckst is there a canonical way to pass installation options on the command line ? I think having this as a flag rather than a "comment this back in" is probably cleaner.

**Comment by richardjgowers** [comment]
ENV variables? Not sure if they’re officially supported but sniffing for
C_FLAGS would seem sane.

**Comment by IAlibay** [comment]
env variables are a bit meh IMHO. I'm pretty sure you can pass it via the setuptools CLI by subclassing something, I'll have to have a poke through some docs later.

**Comment by IAlibay** [comment]
I guess our current setup is built for env variables, so it's probably best to stick with that, it's in the setup docs so I assume they _should_ be officially supported.

**Comment by IAlibay** [comment]
To expand on this - right now (on current develop) if you were to assign the env variable "MDA_MARCH=True" then it would trigger the march variable.

**Comment by hmacdope** [comment]
I am going to close this for now, as we decided in #3429 to allow an option for **any** compiler flags rather than just `march=native`, making this issue obsolete.

**Comment by IAlibay** [comment]
I'm not sure I agree we should close - we're still going to document the use of march=native as a flag right? So we should test it...

**Comment by hmacdope** [comment]
I guess my understanding of discussion in #3429 was that we were going to rely on the user to **specify** any additional compiler flags (it would be blank by default).

 But I see now that if we **document** the use of a flag specifically, we should test for it (if that is an okay use of CI resources?).

Sorry for the perhaps premature close.

**Comment by IAlibay** [comment]
>  (if that is an okay use of CI resources?).

It's a reminder for a weekly Cron job we'll probably add in the near future, it's not a waste of CI if it's the one job once a week IMHO.

**Comment by hmacdope** [comment]
Do we still feel this is warranted? We give an example using custom compiler flags to do an advanced `march` build in userguide, but `march=native` still requires direct user input in `setup.cfg`

**Comment by IAlibay** [comment]
Let's just leave this open for now. I'm planning to restart looking into adding that cron job during the winter break, if we get it in then great, if not then it doesn't matter.

**Comment by IAlibay** [comment]
Unless there's any objections I think I'm going to go ahead and close this.

As much as I would like to test that the correct optimisation options work on on arm / ppc64le, we're already doing these normally on a weekly cron with leftover Travis credits. We already warn folks to make sure they test before they run their jobs, and the weekly gh action cron job tests on x86_64. I'd say that's probably good enough.

**Comment by hmacdope** [comment]
Agreed :)
