### ISSUE TITLE
Issues with MDAnalysis, version 1.1.1

### ISSUE THREAD

**Issue by AlessioD77** [MDAnalysis/mdanalysis#3450]
Hi,
I am trying to execute a python module in anaconda on ubuntu which requires version 1.1.1 of MDAnalysis. I have created a separate conda environment with the prerequisite versions of packages installed (hence 1.1.1). In terminal using this environment, running conda list shows that I have mdanalysis 1.1.1 installed however when trying to execute the aforementioned module I get an ModuleNotFound error stating that there is no module named MDAnalysis.

If I run which python it returns as /home/user/anaconda3/bin/python which I think is the right place. I am running python 3.8.8 and Ubuntu 21.10

**Comment by RMeli** [comment]
`/home/user/anaconda3/bin/python` looks like the Python interpreter of the base environment. Have you activated the new environment with `conda activate ENVIRONMENT`? The path should look something like `/home/user/anaconda3/envs/ENVIRONMENT/bin/python` if I'm not mistaken.

**Comment by AlessioD77** [comment]
Hi,

I have run `conda activate environment` and yet it still returns as the above mentioned path

**Comment by RMeli** [comment]
What do you get with `conda env list`?

**Comment by lilyminium** [comment]
@ilovepistacchios that's really odd. To diagnose, would you please attach a screenshot of your terminal with the following commands?

```bash
conda activate $my_env_name
conda list mdanalysis
which python
python -c "import MDAnalysis; print(MDAnalysis.__version__)"
```

**Comment by AlessioD77** [comment]
So with `conda env list` i get the following:

```
# conda environments:
#
base                     /home/alekoj/anaconda3
Glycoshield           *  /home/alekoj/anaconda3/envs/Glycoshield
```

and with what @lilyminium suggested I get:

```
$ conda list mdanalysis
# packages in environment at /home/alekoj/anaconda3/envs/Glycoshield:
#
# Name                    Version                   Build  Channel
mdanalysis                1.1.1            py37hcd2ae1e_0    conda-forge
```

```
$ which python
/home/alekoj/anaconda3/bin/python
```
```
$ python -c "import MDAnalysis; print(MDAnalysis.__version__)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'MDAnalysis'
```

**Comment by IAlibay** [comment]
@ilovepistacchios this is definitely an issue with your conda environment

If doing `conda activate Glycoshield` followed by `which python` doesn't return `/home/alekoj/anaconda3/envs/Glycoshield/python` then it's likely an issue in the way your shell is interacting with conda.

In any case this is not an issue with MDAnalysis. I'll leave this issue open for a few more hours should further debugging be feasible, but I may ask that this be discussed either on the mailing list or discord in the longer term.

**Comment by AlessioD77** [comment]
Hi,
after checking my glycoshield environment, I found that it was missing some files including the `bin/python` directory. I deleted and remade the environment and it seems to have fixed the issue. Many thanks for everyone's help!

**Comment by IAlibay** [comment]
Awesome to hear it worked out! I'll close the issue.
