### ISSUE TITLE
CRD trajectory from CPPTRAJ doesn't load

### ISSUE THREAD

**Issue by stepdasha** [MDAnalysis/mdanalysis#3462]
I am trying to load the CRD trajectory, that I have after running CPPTRAJ. The trajectory loads fine with VMD, but MDAnalysis doesn't load when I run:

```python 
system1 = mda.Universe(./prmtop, ./traj.crd)
```

## I get an error
ValueError: Check CRD format at line 0: Cpptraj Generated trajectory

## Current version of MDAnalysis ##

- MdAnalysis version 2.0.0
- Python 3.7.12

**Comment by IAlibay** [comment]
@stepdasha could you provide some more information here please?

1. In your example line, is the lack of quotes around the prmtop and traj.crd a typo?
2. Can you provide the entire error message please?
3. Can you provide information on the actual format you mean by CRD here? Usually in amber CRD would refer to an inpcrd (i.e. an ASCII restart), but in MDAnalysis this refers to a CHARMM CARD structure file.

**Comment by stepdasha** [comment]
@IAlibay Sorry for not being more explicit. 
1. yeah, I just didn't want to write the whole path to the file.
2. 
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/tmp/ipykernel_16848/3994670954.py in <module>
----> 1 system1 = mda.Universe(pdb, files)
      2 ref = mda.Universe(pdb, files)
      3 #set ref to 0 frame and calculate rmsd
      4 system1.trajectory[-1]
      5 ref.trajectory[0]

~/barn/miniconda3x86/envs/arvind/lib/python3.7/site-packages/MDAnalysis/core/universe.py in __init__(self, topology, all_coordinates, format, topology_format, transformations, guess_bonds, vdwradii, in_memory, in_memory_step, *coordinates, **kwargs)
    354         if coordinates:
    355             self.load_new(coordinates, format=format, in_memory=in_memory,
--> 356                         in_memory_step=in_memory_step, **kwargs)
    357 
    358         if transformations:

~/barn/miniconda3x86/envs/arvind/lib/python3.7/site-packages/MDAnalysis/core/universe.py in load_new(self, filename, format, in_memory, in_memory_step, **kwargs)
    545         kwargs['n_atoms'] = self.atoms.n_atoms
    546 
--> 547         self.trajectory = reader(filename, format=format, **kwargs)
    548         if self.trajectory.n_atoms != len(self.atoms):
    549             raise ValueError("The topology and {form} trajectory files don't"

~/barn/miniconda3x86/envs/arvind/lib/python3.7/site-packages/MDAnalysis/coordinates/base.py in __init__(self, filename, convert_units, n_atoms, **kwargs)
   2323 
   2324         self._ts_kwargs = ts_kwargs
-> 2325         self._read_first_frame()
   2326 
   2327     def copy(self):

~/barn/miniconda3x86/envs/arvind/lib/python3.7/site-packages/MDAnalysis/coordinates/CRD.py in _read_first_frame(self)
     80                     errmsg = (f"Check CRD format at line {linenum}: "
     81                               f"{line.rstrip()}")
---> 82                     raise ValueError(errmsg) from None
     83 
     84         self.n_atoms = len(coords_list)

ValueError: Check CRD format at line 0: Cpptraj Generated trajectory 
```
3. my actual format is the output from cpptraj. 
I load .nc  Amber trajectory binary file to CPPTRAJ, and got a .crd from CPPTRAJ.

**Comment by IAlibay** [comment]
@stepdasha thanks for the extra info.

So yeah, I think the issue here just seems that the `CRD` file type in MDAnalysis is reserved for CARD files, whilst the "crd" type from AMBER is actually named "TRJ" in MDAnalysis (unfortunately lots of clashing file names across comp chem space).

Can you try doing

```python
system = mda.Universe('prmtop', 'traj.crd', format="TRJ")
```
?

**Comment by stepdasha** [comment]
@IAlibay Thanks, that helped. 
Yeah, agree, the variety of file types' names in comp chem could make it quite frustrating sometime.

**Comment by IAlibay** [comment]
> @IAlibay Thanks, that helped. Yeah, agree, the variety of file types' names in comp chem could make it quite frustrating sometime.

Awesome, good this hear it worked out. I'm closing this issue as resolved (please do re-open or ping the mailing list if there's anything else you would like to raise).
