### ISSUE TITLE
Suggestion of the bugfix hole.py create_vmd_surface function 

### ISSUE THREAD

**Issue by mavstrikova** [MDAnalysis/mdanalysis#3476]
The function create_vmd_surface is not working if you compute hole analysis starting from a specific frame.

hole.py Line 799:   ` for i, sphpdb in zip(self.frames, self.sphpdbs[self.frames])`
leads to index mismatch between two arrays if self.frames[0] != 0.

The fix that worked for me `for i, sphpdb in zip(self.frames, self.sphpdbs[np.indices(self.frames.shape, sparse = True)])`

Not sure if this is the most elegant solution, but it seems to work :)

**Comment by IAlibay** [comment]
@mavstrikova thanks for the bug report / fix.

Could you confirm which version of MDAnalysis this relates to? I _think_ the code changed in 2.0.0, and we would be interested to know if the bug still exists.

**Comment by orbeckst** [comment]
Looking at the 2.0 hole.py and utilities.py files, this seems to refer to 1.1 hole.

**Comment by IAlibay** [comment]
Ok can confirm that this is still an issue in 2.0.0.

Essentially this is causing the issue (self.sphpdbs is indexed linearly whilst we're trying to access it via a frame index, hence causing issues):

https://github.com/MDAnalysis/mdanalysis/blob/7df5a6157843d1f2a5c9e9d3ba8347eaf9f345de/package/MDAnalysis/analysis/hole2/hole.py#L887-L888

PR to fix this is incoming.
