### ISSUE TITLE
Error While testing MDAnalysisTests

### ISSUE THREAD

**Issue by VicCruces** [MDAnalysis/mdanalysis#3481]
I was following the instructions of the tutorial **https://www.mdanalysis.org/MDAnalysisTutorial/installation.html.**
Which means that I executed the following commands:
-  conda install mdanalysis
-  conda install MDAnalysisTests
-  pytest --disable-pytest-warnings --pyargs MDAnalysisTests

The installation seems correct, but at the end of the  "MDAnalysisTests", I got a strange error that seems related
with closing a file as the following link shows:
**https://stackoverflow.com/questions/18952716/valueerror-i-o-operation-on-closed-file**

## Output ##

.conda/envs/mda/lib/python3.9/site-packages/MDAnalysisTests/utils/test_units.py .................                                                                                     [ 99%]
.conda/envs/mda/lib/python3.9/site-packages/MDAnalysisTests/visualization/test_streamlines.py ..                                                                                      [100%]

==================================================== 16633 passed, 308 skipped, 1 xfailed, 2 xpassed, 7157 warnings in 551.27s (0:09:11) ====================================================
Exception ignored in: <function ReaderBase.__del__ at 0x7fabae663670>
Traceback (most recent call last):
  File "/home/vcruces/.conda/envs/mda/lib/python3.9/site-packages/MDAnalysis/coordinates/base.py", line 2180, in __del__
    self.close()
  File "/home/vcruces/.conda/envs/mda/lib/python3.9/site-packages/MDAnalysis/coordinates/PDB.py", line 458, in close
    self._pdbfile.close()
  File "/home/vcruces/.conda/envs/mda/lib/python3.9/site-packages/MDAnalysis/lib/util.py", line 734, in close
    self.flush()
  File "/home/vcruces/.conda/envs/mda/lib/python3.9/site-packages/MDAnalysis/lib/util.py", line 840, in flush
    return self.stream.flush()
ValueError: I/O operation on closed file.

**Anyways, I would like to thanks in advance**

**Comment by IAlibay** [comment]
@VicCruces thanks for the report - the "ValueError: I/O operation on closed file" during testing is actually "normal", i.e. it is related to https://github.com/MDAnalysis/mdanalysis/issues/3386 where one of the PDB tests causes an extra operation on a closed file stream. As long as the tests don't generate any errors then it's fine to assume that the installation went well.

**Comment by VicCruces** [comment]
Thanks a lot for your quick reply. I am sorry about opening this Issue I didn't see issue #3386.
Shall I close this issue?

**Comment by IAlibay** [comment]
> Thanks a lot for your quick reply. I am sorry about opening this Issue I didn't see issue #3386.

No worries at all, it's always better to check these things. Plus we much prefer getting duplicate issues than no reports at all. 

> Shall I close this issue?

Sure, I'll close it with this comment.
