### ISSUE TITLE
Azure Pipeline Windows 16 deprecation

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/mdanalysis#3509]
## Expected behavior ##
Azure Pipeline Windows CI always runs.

## Actual behavior ##

On PR #3480 the Azure pipeline jobs were auto-cancelled due a brownout to alert us about the deprecation

```
##[error]This is a scheduled windows-2016 brownout. The windows-2016 environment is deprecated and will be removed on March 15, 2022. For more details, see https://github.com/actions/virtual-environments/issues/4312
,##[error]The remote provider was unable to process the request.
```

## Code to reproduce the behavior ##
https://dev.azure.com/mdanalysis/mdanalysis/_build/results?buildId=2889&view=logs&j=1cdae27b-58e8-5c64-01e2-519b6cdf4b73

see https://github.com/actions/virtual-environments/issues/4312

## TODO

Probably upgrade Azure environment.

**Comment by orbeckst** [comment]
cc @IAlibay @tylerjereddy

**Comment by tylerjereddy** [comment]
Ah yeah, need to watch out for our incompatibility with newer MSVC though per gh-3399 and gh-3248.

May need to xfail that test on Windows for now and reference the original issue so we can bump the CI up.

**Comment by IAlibay** [comment]
Sorry it's partly fault for not pushing to review https://github.com/MDAnalysis/mdanalysis/pull/3399.

> May need to xfail that test on Windows for now and reference the original issue so we can bump the CI up.

Yeah I think that'd be the best way at this rate. Let's move #3399 to just replace the matrix to just use windows-2019 fully rather than switching later?

**Comment by tylerjereddy** [comment]
alright, give me a bit..

**Comment by tylerjereddy** [comment]
ok, I pushed in an attempt to do that, feel free to push if I screwed something up though
