### ISSUE TITLE
Segmentation fault for large vectors in distances.distance_array

### ISSUE THREAD

**Issue by sef43** [MDAnalysis/mdanalysis#3512]
## Expected behavior ##

MDAnalysis.lib.distances.distance_array should work for large vectors.

## Actual behavior ##
MDAnalysis.lib.distances.distance_array has a segmentation fault for vectors of length >50000.
I think this may be due to integer overflow in the array indexing in the C code in lib/include/calc_distances.h, the line:
  `*(distances+i*numconf+j) = sqrt(rsq);`

## Code to reproduce the behavior ##

``` python
import numpy as np
import MDAnalysis


N=50000
print(N,N*N)
a=np.random.rand(N,3)
b=np.random.rand(N,3)

d=MDAnalysis.lib.distances.distance_array(a,b)
```
Output for me is:

```
50000 2500000000
Segmentation fault
```

## Current version of MDAnalysis ##

- Which version are you using?  2.0.0
- Which version of Python (`python -V`)? Python 3.8.5
- Which operating system? Linux (HPE Cray Linux)

**Comment by hmacdope** [comment]
This does look like an overflow problem as 50,000^2 is larger than `INT_MAX`. This can be fixed by switching to `int64` indexing or using an unsigned int type (personally I think `int64` makes most sense)

Ping @MDAnalysis/coredevs? Any change should probably be consistent across all the C routines.

**Comment by richardjgowers** [comment]
Yeah we probably should just move to long longs.

**Comment by jbarnoud** [comment]
If only people could stop increasing the size of their simulations :P

**Comment by richardjgowers** [comment]
A full N x N distance array isn’t a good idea, (capped distances!) but it
shouldn’t segfault either.

**Comment by jbarnoud** [comment]
Note as well that `i` and `j` cannot be negative, so using an unsigned type would give some more leeway. Regarding the segfault itself,  testing that N*M < MAX_TYPE for whatever type we end up using would be a good idea.

**Comment by hmacdope** [comment]
I'm happy to make the required changes if people are okay with that. 

`unsigned int` would give us [0, 4294967295] so up to ~65536 max input points. This is not a super improvement IMO. 

`int64` would give us [0,  9,223,372,036,854,775,807] so ~3037000499 max input points. 

`uint64` is double the range of int64  but I think int64 covers enough.

**Comment by jbarnoud** [comment]
Is there any reason *not* to use an unsigned type? Surely, `int64` is enough, but still half of the range is unused. What would be the benefit of `int64` compared to `uint64`?

**Comment by hmacdope** [comment]
I suppose there is nothing *specific* apart from superstition that using `unsigned` anything can have unintended effects when not careful. But that is pure dogma talking. 

 I'm open to either. :)

**Comment by richardjgowers** [comment]
Somewhere in the back of my head I have that signed & unsigned is treated
differently by compilers wrt the optimisations they make.  That said, I
can't remember which was better.  It was something that Jakub pointed out
in distopia...

**Comment by hmacdope** [comment]
While we are changing types we could improve `size_t` or even `Py_ssize_t` (`ssize_t`) compliance for array indicies, but this is a bit pedantic.

> Somewhere in the back of my head I have that signed & unsigned is treated differently by compilers wrt the optimisations they make.

[This](https://www.airs.com/blog/archives/120) is an interesting and old blog post on the topic which advocates for the use of signed loop indicies. 

IIRC we had the **reverse** situation in distopia where only `size_t` would effectively autovectorise. See discussion on [this](https://github.com/MDAnalysis/distopia/issues/21#issuecomment-729338212) issue. All this is highly dependent on compiler flags also (SIMD  of varying levels used extensively in distopia).
