### ISSUE TITLE
need tests for MDAnalysis.selections

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/mdanalysis#353]
The selection writer (*not* the atom selections) are not being tested at the moment.We should have some basic tests.

I am renaming `test_selections.py` to `test_atomselections.py` and then we can start working on a `test_selections.py` for this purpose.

**Comment by orbeckst** [comment]
I did the rename in c3333ce4e10027b87ada98c53fcdb947875c4037 .

**Comment by orbeckst** [comment]
I started on this issue, add more tests to `test_selections.py`.

**Comment by richardjgowers** [comment]
Creeping closer to that 90% mark!
