### ISSUE TITLE
GSD: Deprecation warning (read_frame?)

### ISSUE THREAD

**Issue by IAlibay** [MDAnalysis/mdanalysis#3534]
Running test_pickleio.py::test_GSD_pickle throws the following DeprecationWarning:

```
site-packages/gsd/hoomd.py:844: DeprecationWarning: Deprecated, trajectory[idx]
```

Looks like it's specifically down to the `gsd_io.read_frame` call on line 167.

MDA Version: 2.1.0-dev0

**Comment by HenokB** [comment]
Hi, @IAlibay could you explain to me about this issue?

**Comment by richardjgowers** [comment]
Hi Henok, theres a deprecation warning from the gsd library which has been
tracked down to a certain line. It’s likely we have to change how we’re
using the gsd library to avoid a future problem. To fix this issue,
investigate how/if the gsd library has changed and modify our code
accordingly.
