### ISSUE TITLE
ENCORE uses an non existing method

### ISSUE THREAD

**Issue by jbarnoud** [MDAnalysis/mdanalysis#3539]
ENCORE uses an non existing method `AtomGroup.get_selection_atom_string`: https://github.com/MDAnalysis/mdanalysis/pull/3479#issuecomment-1029249778

Ping @mtiberti and @wouterboomsma

**Comment by orbeckst** [comment]
@mtiberti @wouterboomsma could you please let us know what you had intended with this method?

**Comment by mtiberti** [comment]
Hi, sorry for the delay and thanks for noticing this - I did some digging and it is indeed a leftover of when we had our own `Ensemble` class. It should be fine to replace it with `reference.select_atoms(select)`. Should I open a PR?

**Comment by orbeckst** [comment]
PR would be good. The main thing is a test that checks the code path.

**Comment by jbarnoud** [comment]
Thank you Matteo. If you find the time, it would be good if you could 
indeed.
