### ISSUE TITLE
Build badge on MDAnalysisTests readme needs updating

### ISSUE THREAD

**Issue by IAlibay** [MDAnalysis/mdanalysis#3557]
The badge still points to travis, just needs switching to gh actions CI.

**Comment by inomag** [comment]
Hi @IAlibay , I would like to work on this issue. But, I had a doubt. The readme file doesn't contain any extension. Should I rename it as README.md first?

**Comment by IAlibay** [comment]
@inomag - no this isn't a user facing readme so it doesn't need any further changes beyond changing the link at this point in time.

I don't know if you happen to be a potential GSoC contributor, but given organisations were announced today I'll just make this clear here for anyone that might be a candidate to be a contributor. This issue does not meet the minimum requirements for a meaningful merged commit to MDAnalysis.

**Comment by inomag** [comment]
Thanks @IAlibay . It's ok if this issue does not meet the minimum requirement. I just want to explore the codebase.

**Comment by inomag** [comment]
I will make the edit and create a PR
