### ISSUE TITLE
Manually provide masses charges and sizes to non-standard particle types

### ISSUE THREAD

**Issue by SerpentByte** [MDAnalysis/mdanalysis#3561]
## Is your feature request related to a problem? ##

I mostly work with coarse-grained simulation techniques and use GROMACS for simulations. Therefore the bead types I used for atoms are not recognised. This creates a warning "UserWarning: Failed to guess the mass for the following atom types". This assumes the mass of whatever it can find in the periodic table, else sets the masses to zero.

## Describe the solution you'd like ##

What can be done it to pass an optional parameter in the function Universe, where a GROMACS .itp can be read to determine the charge, sizes and masses of the particles.

## Describe alternatives you've considered ##

One can always manually set the masses, but then it is cumbersome.

## Additional context ##

Also it says that my Universe does not contain any charge information. Wonder why it does that..

**Comment by jbarnoud** [comment]
Thank you for reporting this issue. The warning you are talking about is way too familiar to me!

It is already possible to load the topology from an ITP (or even better, a TPR file), though. In such case, the masses (but also the whole topology, including the charges) will be read from the file:

```python
import MDAnalysis as mda

universe = mda.Universe('my_topology.itp', 'my_structure.gro')
```

Does that solve your issue, or did I miss something?

**Comment by SerpentByte** [comment]
Wow this is nice to know. Thanks!
