### ISSUE TITLE
TST, MAINT: modernizing Encore tests with `np.all()`

### ISSUE THREAD

**Issue by tylerjereddy** [MDAnalysis/mdanalysis#3568]
There are a few issues with the Encore tests in `testsuite/MDAnalysisTests/analysis/test_encore.py `. One that stands out is the usage of `assert np.all()`, which gives inferior failure reports compared to `assert_allclose()` et al.

Consider:

```python
In [2]: arr = np.array([1, 2, 3])

In [3]: assert np.all(arr == [1, 2, 4])
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-3-08a34a54ff2a> in <module>
----> 1 assert np.all(arr == [1, 2, 4])

AssertionError: 

In [4]: from numpy.testing import assert_allclose

In [5]: assert_allclose(arr, [1, 2, 4])
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-5-f488012b8860> in <module>
----> 1 assert_allclose(arr, [1, 2, 4])

    [... skipping hidden 1 frame]

~/python_venvs/python_395/lib/python3.9/site-packages/numpy/testing/_private/utils.py in assert_array_compare(comparison, x, y, err_msg, verbose, header, precision, equal_nan, equal_inf)
    842                                 verbose=verbose, header=header,
    843                                 names=('x', 'y'), precision=precision)
--> 844             raise AssertionError(msg)
    845     except ValueError:
    846         import traceback

AssertionError: 
Not equal to tolerance rtol=1e-07, atol=0

Mismatched elements: 1 / 3 (33.3%)
Max absolute difference: 1
Max relative difference: 0.25
 x: array([1, 2, 3])
 y: array([1, 2, 4])

```

**Comment by tylerjereddy** [comment]
Probably for a separate issue, but the multi-line slash-continued assertions like this are probably best avoided as well--you'd basically have to refactor the code to figure out the `False` statement if it did fail anyway.

![image](https://user-images.githubusercontent.com/7903078/159099947-da753ce3-eced-439c-aae0-38d04ef32795.png)

**Comment by hmacdope** [comment]
@tylerjereddy would you mind if I label this `GSOCStarter`? Could be a good first contribution.

**Comment by IAlibay** [comment]
I'm not sure I agree that this constitutes enough for a GSoC starting contribution. Ideally we want folks solving something that would lead to at least the implementation of a new test, swapping out numpy calls and formatting doesn't seem like enough?

@MDAnalysis/gsoc-mentors please weigh in.

**Comment by ojeda-e** [comment]
I agree with @IAlibay with having a GSoC contribution that involves a new unit test. However, and as @hmacdope pointed out, it could be a good first contribution. Maybe labeling with `good-first-issue` instead?

**Comment by lilyminium** [comment]
I agree with @IAlibay and @ojeda-e, IMO the gsoc-starter issues are to get familiar with what the GSOC project will need, which will involve at least some form of testing.

**Comment by hmacdope** [comment]
No worries :)

**Comment by aditi2906** [comment]
Hey,
I would like to work on this issue..Can you please help me understand what parametric value should I pass for rtol and atol if I use assert_allclose()?

**Comment by lilyminium** [comment]
Thanks for having a look @aditi2906. I think the default values should be alright, really -- otherwise what kind of tolerance we expect would depend on the particular test.
