### ISSUE TITLE
Fix typos in the docs - multiple PRs welcome!

### ISSUE THREAD

**Issue by lilyminium** [MDAnalysis/mdanalysis#3580]
**From https://github.com/MDAnalysis/UserGuide/issues/194 -- @micaela-matta**

This issue is designed to be incrementally achieved through multiple PRs. 

There are a few typos in the user guide, this issue will collect as many as we can find starting with the short list below.
Feel free to fix any typos/formatting errors we haven't noticed and add them in the comments!

- units and conversions [page]( https://docs.mdanalysis.org/2.1.0-dev0/documentation_pages/units.html?highlight=unit%20conversion#conversions), note box: "in the future me might" 
- units and conversions [page]( https://docs.mdanalysis.org/2.1.0-dev0/documentation_pages/units.html?highlight=unit%20conversion#conversions), above the note box: fix LaTeX formatting for `rho/rho0 = n/(N_A * M**-1) / rho0 where [n] = 1/Volume, [rho] = mass/Volume`
- units and conversions [page]( https://docs.mdanalysis.org/2.1.0-dev0/documentation_pages/units.html?highlight=unit%20conversion#conversions), `MDAnalysis.units.water`: fix scientific notation in`and molar mass 18.016 g mol**-1`
- density analysis [page](https://docs.mdanalysis.org/2.1.0-dev0/documentation_pages/analysis/density.html), units and conversions [page]https://docs.mdanalysis.org/2.1.0-dev0/documentation_pages/units.html?highlight=unit%20conversion#conversions) (and probably many other pages): the symbol `Å`  appears many times in different formats (`ångströms`, `Å**-3`, `Angstroms` etc). Depending on the context in the page, keep LaTeX equation style or replace with the standard symbol `Å` and correct scientific notation.

**Comment by ValentinaWalters** [comment]
Hello @lilyminium @richardjgowers. I am an outreachy intern applicant and I'll like to be assigned to this task

**Comment by IAlibay** [comment]
@ValentinaWalters - as a general rule we do not assign folks to issues in MDAnalysis, especially for outreachy and gsoc. MDAnalysis works on a "first PR" basis, where we will give priority review to the first opened pull request that is opened against a specific issue. To keep things fair we ask that folks only work on one issue at a given time, this way we don't get collisions with lots of folks trying to fix the same issue.

**Comment by micaela-matta** [comment]
@ValentinaWalters I would also add to what @IAlibay said: as stated above this issue is designed to be incrementally achieved through multiple PRs (from different applicants)

**Comment by ValentinaWalters** [comment]
Ok thanks @micaela-matta @IAlibay . I'll work on this and draft a PR soon

**Comment by pranayrauni** [comment]
Hi, I'm an Outreachy 2022 applicant. I'm getting issue after creating virtual env.  I'm unable to activate. 


![n](https://user-images.githubusercontent.com/59686672/162186530-99abbd73-99b7-426b-b827-157085a189ad.png)

**Comment by aditi2906** [comment]
Hey! 
since you have created another directory of my-project-env...firstly change directory (cd) into that and then try running source bin/activate.

**Comment by ValentinaWalters** [comment]
@pranayrauni hey have you created a file(my project) directly on conda or miniconda ?

**Comment by micaela-matta** [comment]
@pranayrauni see the section of the [guide](https://userguide.mdanalysis.org/stable/contributing_code.html#with-pip-and-virtualenv) "with pip and virtualenv". Which directory are you trying to activate the environment from?

**Comment by pranayrauni** [comment]
> Hey! since you have created another directory of my-project-env...firstly change directory (cd) into that and then try running source bin/activate.

Hi, Issue has been resolved. I had to make some changes in command to make it work properly. I have created dev env on my windows machine. BTW thanks for your suggestion.

**Comment by lilyminium** [comment]
For anyone looking at this issue, there's a bit of work to do to find the actual page to edit to fix the typo!

The first step is to find the web page that the typo is on. In the top comment, the pages are linked -- otherwise, you can browse the documentation yourself.

From there you need to work backwards to find the file that creates the web page. For a page with the URL `https://docs.mdanalysis.org/2.1.0-dev0/documentation_pages/units.html`, the important part is `documentation_pages/units.html`. That indicates that the page is built from the ` mdanalysis/package/doc/sphinx/source/documentation_pages/units.rst ` file: https://github.com/MDAnalysis/mdanalysis/blob/develop/package/doc/sphinx/source/documentation_pages/units.rst

Sometimes in a `rst` file there is writing -- you should go look at it. Often, however, there's no actual text. Instead, it gets the documentation from the `MDAnalysis.units` module, as described there with `automodule`. What this actually means is it gets the docstring from the `mdanalysis/package/MDAnalysis/units.py` file. Therefore, that would be the file you need to edit.

You might see an rst file (e.g. https://github.com/MDAnalysis/mdanalysis/blob/develop/package/doc/sphinx/source/documentation_pages/analysis/hole2.rst) that sources something like `MDAnalysis.analysis.hole2`. However, there is no matching `mdanalysis/package/MDAnalysis/analysis/hole2.py` file. Instead, `hole2` is also a directory. In this case, `MDAnalysis.analysis.hole2` sources from the `mdanalysis/package/MDAnalysis/analysis/hole2/__init__.py` file.

**Comment by aditi2906** [comment]
@lilyminium can we fix the PEP8 issues in the documentation under this issue?
