### ISSUE TITLE
Change code snippets from python 2 to python 3 in the documentation

### ISSUE THREAD

**Issue by micaela-matta** [MDAnalysis/mdanalysis#3582]
This issue can be open for multiple PRs.

in the 'Overview over MDAnalysis' [page](https://docs.mdanalysis.org/2.1.0-dev0/documentation_pages/overview.html) of the user guide, some leftover python 2 syntax should be updated to python 3 syntax.

Example: `>>> print u.atoms`  should be replaced by  `>>> print(u.atoms)` 

Find any other obsolete code snippets in other pages of the user guide to add to this issue.

**Comment by lilyminium** [comment]
Ahh, I think this might be a better issue for the core repo -- those docs are built from there. That being said, I'm sure there are examples of outdated Python here!

**Comment by HenokB** [comment]
In the [overview](https://docs.mdanalysis.org/2.1.0-dev0/documentation_pages/overview.html) page
Example:  `>>> print "frame = %d: d = %f Angstroem, Rgyr = %f Angstroem" % (ts.frame, d, rgyr)` should be replaced by`>>> print ("frame = %d: d = %f Angstroem, Rgyr = %f Angstroem" % (ts.frame, d, rgyr))`

**Comment by HenokB** [comment]
In the [overview](https://docs.mdanalysis.org/2.1.0-dev0/documentation_pages/overview.html) page
`>>> print u.trajectory`  should be replaced with `>>> print (u.trajectory)`

**Comment by orbeckst** [comment]
@HenokB this already looks good. Please raise a PR. We can then comment specifically on your suggested fix.

The docs live in https://github.com/MDAnalysis/mdanalysis/tree/develop/package/doc/sphinx/source/documentation_pages (unless the code is somewhere in the code itself...). An easy way to find files that contain specific texts is to use `git grep '>>> print "'`.

**Comment by HenokB** [comment]
> @HenokB this already looks good. Please raise a PR. We can then comment specifically on your suggested fix.
> 
> The docs live in https://github.com/MDAnalysis/mdanalysis/tree/develop/package/doc/sphinx/source/documentation_pages (unless the code is somewhere in the code itself...). An easy way to find files that contain specific texts is to use `git grep '>>> print "'`.

Thanks and just finished a PR
