### ISSUE TITLE
add plots for Ramachandran and Janin plots

### ISSUE THREAD

**Issue by micaela-matta** [MDAnalysis/mdanalysis#3584]
*Issue*

The example code for [analysis data files](https://docs.mdanalysis.org/2.1.0-dev0/documentation_pages/analysis/data.html?highlight=contourf#analysis-data-files) uses `contourf` but shows no plots. 

*Task*

Add [Ramachandran](https://docs.mdanalysis.org/2.1.0-dev0/documentation_pages/analysis/dihedrals.html#figure-ramachandran) and [Janin](https://docs.mdanalysis.org/2.1.0-dev0/documentation_pages/analysis/dihedrals.html#figure-janin) plot figures.

**Comment by umak1106** [comment]
Sorry I misread it yesterday 😅.  I'll rectify my PR today.

**Comment by micaela-matta** [comment]
Hi @umak1106, I'm not sure I saw your introduction post in our [mailing list](https://groups.google.com/g/mdnalysis-devel) or [Discord server](https://www.mdanalysis.org/2021/03/20/discord). Are you an Outreachy applicant?

We ask all GSOC/Outreachy applicants to first introduce themselves by posting on the mailing list. And please note that we encourage all GSOC/Outreachy applicants to only have a single PR open at a time, this ensures an equitable distribution of issues for all. See also our [wiki page](https://github.com/MDAnalysis/mdanalysis/wiki/Outreachy)  and [FAQ](https://github.com/MDAnalysis/mdanalysis/wiki/Outreachy-FAQ).

**Comment by umak1106** [comment]
> Hi @umak1106, I'm not sure I saw your introduction post in our [mailing list](https://groups.google.com/g/mdnalysis-devel) or[Discord server](https://www.mdanalysis.org/2021/03/20/discord). Are you an Outreachy applicant?
> We ask all GSOC/Outreachy applicants to first introduce themselves by posting on the mailing list. We encourage all GSOC/Outreachy applicants to only have a single PR open at a time, this ensures an equitable distribution of issues for all.

Yes am an Outreachy applicant.  
I didn't know about the one PR rule but I'll follow it from now onward . 
And I'll introduce myself on the mailing list too.

**Comment by Sukeerti1** [comment]
Hi, I'm Sukeerti , Outreachy applicant. I went through the following links
https://github.com/MDAnalysis/mdanalysis/blob/develop/package/MDAnalysis/analysis/dihedrals.py
Line number 517 and 667 requires changes to be done. Also
https://github.com/MDAnalysis/mdanalysis/blob/develop/package/MDAnalysis/analysis/data/filenames.py requires some modification..
I went through https://docs.mdanalysis.org/2.1.0-dev0/documentation_pages/analysis/dihedrals.html#figure-ramachandran . Can I get any help to understand it more clearly.
