### ISSUE TITLE
Add ASV benchmark badge to README

### ISSUE THREAD

**Issue by ojeda-e** [MDAnalysis/mdanalysis#3586]
Add a new badge in README to link to the site https://www.mdanalysis.org/benchmarks/. Use reStructuredText syntax.

It should look something like: ![image](https://user-images.githubusercontent.com/27988163/160877592-d5e67297-e687-4220-8ebd-e473840684b7.png)

Adding a line with more info on benchmarks is optional and subjected to the approval of Outreachy mentors.

**Comment by IAlibay** [comment]
img.shields.io will probably come in useful here

**Comment by RMeli** [comment]
As per https://github.com/MDAnalysis/mdanalysis/issues/3557#issuecomment-1062214371, is this a valid Outreachy task?

**Comment by ojeda-e** [comment]
Thanks for pointing it out @RMeli, I missed that conversation. I will leave it up to Outreachy mentors to remove the outreachy-task label.

**Comment by IAlibay** [comment]
Not an outreachy mentor disclaimer - I would say it is an outreachy task but not a gsoc one. Because of how outreachy works we expect a greener technical background entry point for candidates.
