### ISSUE TITLE
create NAMD.DCDWriter and CHARMM DCDWriter

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/mdanalysis#359]
~~Similar to LAMMPS.DCDReader have a NAMD version.~~

EDIT: actually, we only need different *writers* because of the different unitcell representation in the DCD https://github.com/MDAnalysis/mdanalysis/issues/359#issuecomment-313987227

**Comment by dotsdl** [comment]
Should be as simple as copying the ``MDAnalysis.coordinates.LAMMPS`` module into  a ``MDAnalysis.coordinates.NAMD`` module that makes the appropriate overrides for NAMD from the CHARMM DCD reader. Or would it make more sense to consolidate, if there's not much (or any?) difference between the NAMD and LAMMPS DCD spec?

**Comment by orbeckst** [comment]
Technically, the Charmm.DCDReader is really more NAMD.DCDReader (because the underlying reader is VMD/molfile), with some Charmm specifics like detecting unitcells patched in at the Python level.

We should make the NAMD.DCD reader the "base" and then derive from that one, which at the moment really only means setting default times. In principle we can directly use the LAMMPS DCD Reader as the NAMD.DCDReader base class.

Pretty much the only issue (that I can see at the moment) is that *writing* a DCD will always produce a DCD with NAMD convention for the unitcell representation.

**Comment by orbeckst** [comment]
We don't need a NAMD reader but a NAMD DCDWriter (with unitcell with angle cosines) and a CHARMM DCDWriter (with unitcell as symmetric box vectors) – see Wiki [File Formats: DCD](https://github.com/MDAnalysis/mdanalysis/wiki/FileFormats#dcd).

**Comment by orbeckst** [comment]
This may all be terribly outdated and nobody really asked for it in almost 10 years so I am closing my original issue.
