### ISSUE TITLE
change "from MDAnalysis import *" to more specific imports

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/mdanalysis#3602]
## Expected behavior ##
Docs show examples following Python best practices, in particular with regard to avoiding blanket imports of the form
```python
# AVOID THIS:
from MDAnalysis import *
```

## Actual behavior ##

The examples on the [overview](https://docs.mdanalysis.org/stable/documentation_pages/overview.html) page contain multiple cases of 
```python
from MDAnalysis import *
```

## Desired solution ##
Replace `from MDAnalysis import *` with accessing the required classes and functions within the module. For example. instead of `u = Universe(PSF, DCD)` write
```python
import MDAnalysis as mda

u = mda.Universe(PSF, DCD)
```
This is also how we recommend importing MDAnalysis, so it's important to have this common pattern early in the docs.

**Comment by tejaswari7** [comment]
I would like to take this issue please assign it to me

**Comment by orbeckst** [comment]
Hello @tejaswari7 , we don’t assign issues, we simply review the first PR that references the issue. So just submit a PR and we then look at your work. 

Have you already introduced yourself on the developer mailing list?

Please also only work on one issue at a time.
