### ISSUE TITLE
[CI] AZP runners are flaky and failing a lot on reading XTC files

### ISSUE THREAD

**Issue by IAlibay** [MDAnalysis/mdanalysis#3614]
See: https://dev.azure.com/mdanalysis/mdanalysis/_build/results?buildId=3392&view=logs&j=4e8a2b8d-dc2d-525e-b5b0-9e8ff470f57f&t=0a1bec29-feee-5c18-7b4e-468834a8c1e8&l=674

It seems like a weird mix of CI and maybe numpy?

**Comment by IAlibay** [comment]
@tylerjereddy I was wondering if you might have any insights here.

**Comment by IAlibay** [comment]
Suddenly stopped failing as much... maybe it's just purely upstream

**Comment by tylerjereddy** [comment]
Nothing super-obvious without doing a detailed diff of succeeding vs. failing logs. I know upstream there has been discussion of migrating as much as possible from Azure to GHA for reliability/quality, etc. The other advantage is being able to run the CI completely locally using the [`act` tool](https://github.com/nektos/act) for GHA, which is indeed quite slick for iterating.

**Comment by IAlibay** [comment]
This seems fine for now so I'm going to close. My 2 cents is I'm reluctant to move all of CI to one provider in case we face another Travis situation, but it's something that we should bring up for wider discussion.
