### ISSUE TITLE
Testing for core.Selections

### ISSUE THREAD

**Issue by richardjgowers** [MDAnalysis/mdanalysis#362]
Coverage for the Selection system is 79%, it looks like many distance based selections have been missed out.

I know @mnmelo is working on Selections currently, so may wait on him commenting before writing some new tests.

**Comment by mnmelo** [comment]
I just opened #371 on the overhaul of the selection module.

Either we wait until then to expand testing, or push for it asap, so that the overhaul occurs already under better testing.

**Comment by orbeckst** [comment]
We need the tests one way or the other and before we get #371 into the mainline I'd actually like to know that the old system is fully working. So I'd say there's no harm in adding a test whenever you feel like ;-).
