### ISSUE TITLE
TypeError: object of type 'Universe' has no len()

### ISSUE THREAD

**Issue by yang-guoli** [MDAnalysis/mdanalysis#3628]
## Code to reproduce the behavior ##

``` python
import MDAnalysis as mda
from MDAnalysis.analysis import hole2
import matplotlib.pyplot as plt
import numpy as np
pdb = './hypersound_dynamic_400.pdb'
u = mda.Universe(pdb)
ha = hole2.hole(u,
                      executable='./hole2/exe/hole',
                      vdwradii_file=None,
                      cpoint=None,
                      random_seed=31415)
ha.create_vmd_surface()
```

it has error as follows:
![image](https://user-images.githubusercontent.com/73353085/162905175-508e64cc-b42f-4a1a-a18d-98a4fc4c7a10.png)

I just started learning MDanalisys, I don't know how to solve this problem, can you give me some help？

**Comment by lilyminium** [comment]
@yang-guoli the `hole` function expects a PDB filename, i.e. "hypersound_dynamic_400.pdb". If you want to run on a Universe, please use the `HoleAnalysis` class. The documentation for hole2 is here: https://docs.mdanalysis.org/stable/documentation_pages/analysis/hole2.html
