### ISSUE TITLE
Implement an AuxReader that supports GROMACS EDR files

### ISSUE THREAD

**Issue by BFedder** [MDAnalysis/mdanalysis#3629]
## Is your feature request related to a problem? ##
When running MD simulations, it is often desirable to plot 'energy' terms like the potential energy, temperature, pressure, etc. of the system. The data to be plotted generally has to be extracted from output files and written to intermediate files to facilitate plotting. This is inconvenient when done for many simulations and/or many energy terms.

## Describe the solution you'd like ##
@orbeckst, @jbarnoud and I had a discussion about this on the developer mailing list (https://groups.google.com/g/mdnalysis-devel/c/trOqoYcS5uk), where a possible solution is described with mock-up code. 
Essentially, I suggest new energy file readers be added to the auxiliary framework of MDAnalysis that can parse the energy output files of GROMACS, Amber, NAMD, OpenMM, etc. 
For GROMACS, a lot of what would need to be done is already possible thanks to panedr (https://github.com/jbarnoud/panedr). 
Integrating these readers among the current aux readers would allow users to associate energy data with trajectories, and for example filter timesteps by associated potential energy. 
I think expanding the capabilities of MDAnalysis and enabling the parsing of a thus far untapped block of MD output data makes sense. 

## Describe alternatives you've considered ##
Keep things as they are and not add energy file readers.

**Comment by IAlibay** [comment]
@BFedder following from today's discussion - this might also be a good place to link to when wanting to discussing things related to your GSoC project

**Comment by orbeckst** [comment]
An AUX GROMACS EDRReader is part of @BFedder 's  GSOC project #3714 and we are now looking into how to get [MDAnalysis/panedr](https://github.com/MDAnalysis/panedr) into shape so that it can be used as a dependency.
