### ISSUE TITLE
replace atoms.coordinates() with atoms.positions in benchmarks

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/mdanalysis#3638]
## Expected behavior ##

Benchmarks run with latest release.

## Actual behavior ##

Some benchmarks use outdated and removed `AtomGroup.coordinates()` instead of `AtomGroup.positions`.

## Code to reproduce the behavior ##

Output from `git grep 'coordinates()` for the benchmarks:
```
benchmarks/benchmarks/analysis/rms.py:        # ag.coordinates()
benchmarks/benchmarks/analysis/rms.py:            self.A = self.u.atoms.coordinates().copy()[:num_atoms]
benchmarks/benchmarks/analysis/rms.py:            self.B = self.u.atoms.coordinates().copy()[:num_atoms]
```
(Follow-up from #3467 )

## Current version of MDAnalysis ##

- Which version are you using? (run `python -c "import MDAnalysis as mda; print(mda.__version__)"`) develop 2.2.0

**Comment by orbeckst** [comment]
See https://github.com/MDAnalysis/benchmarks for the benchmark repo with the [README](https://github.com/MDAnalysis/mdanalysis/blob/develop/benchmarks/README.rst) giving an introduction on how to run [ASV](https://asv.readthedocs.io/en/stable/index.html) locally.

The [benchmarks wiki](https://github.com/MDAnalysis/mdanalysis/wiki) also has some notes.

**Comment by aditi2906** [comment]
@orbeckst I want to work on this issue.. However, the readme of [benchmarks repo](https://github.com/MDAnalysis/benchmarks)
does not give a good headstart on how to run asv locally. Can you help me with it.
Thankyou

**Comment by orbeckst** [comment]
Please see https://github.com/MDAnalysis/mdanalysis/blob/develop/benchmarks/README.rst
