### ISSUE TITLE
ImportError: attempted relative import with no known parent package

### ISSUE THREAD

**Issue by thinkbeyondit83** [MDAnalysis/mdanalysis#3648]
I am working on my linux machine and getting the error: ImportError: attempted relative import with no known parent package. The files are unable to run. 
I had normally installed MDAnalysis in my local. Then why is it not in the environment varaible.And if it has to be in the environemnt variable exactly which folder path should I pick?

- Which version are you using? (run `python -c "import MDAnalysis as mda; print(mda.__version__)"`) 2.2.0
- Which version of Python (`python -V`)? 3.8.10
- Which operating system? Linux

**Comment by orbeckst** [comment]
Given that you can get the version, it seems that you correctly installed MDAnalysis.

Please provide more detail of what you're trying to do:
- show the code that you are trying to run
- show the full error output
- how did you install MDAnalysis
- in which directory are you (`pwd` output)

Please note that it really helps us when you fill in the issue reports according to the template that you see, namely telling us what you were trying to do, what you expected to happen, what actually happened, and how to reproduce the error

**Comment by thinkbeyondit83** [comment]
Code trying to run: python mdanalysis/package/MDAnalysis/core/universe.py
error output: Traceback (most recent call last):
  File "/home/morty/mdanalysis/package/MDAnalysis/core/universe.py", line 75, in <module>
    from .. import _TOPOLOGY_ATTRS, _PARSERS
ImportError: attempted relative import with no known parent package

- MDanalysis installed following steps in [https://userguide.mdanalysis.org/stable/contributing_docs.html#forking-and-cloning-the-user-guide](https://userguide.mdanalysis.org/stable/contributing_docs.html#forking-and-cloning-the-user-guide
)
- pwd:  /home/morty

**Comment by lilyminium** [comment]
@thinkbeyondit83 the files in the MDAnalysis repository are not scripts and not really written to be run from the command line as you are doing. Could I ask what you are trying to do? Normally users are expected to import from MDAnalysis and write their own scripts.

**Comment by thinkbeyondit83** [comment]
In case I want to annotate the codebase and find the result to certain functions I will have to seprately import the library in ipython or jupyter and run to find the result?

**Comment by lilyminium** [comment]
Yes, that would be the best way to execute a function. I'm not sure what you mean by annotating the code-base; for that I assume you would need a code editor of some kind.

**Comment by thinkbeyondit83** [comment]
Yes I am using one. Thankyou for the clarification. I am closing the issue since my doubt has been answered
