### ISSUE TITLE
Getting fragments from an atom selection includes atoms outside of selection

### ISSUE THREAD

**Issue by Michael-C-Strobel** [MDAnalysis/mdanalysis#3658]
## Expected behavior ##
When accessing the fragments on an AtomGroup generated from a selection, the fragments should not include atoms outside of the AtomGroup.

## Actual behavior ##
The fragments will include atoms outside of the AtomGroup.

## Code to reproduce the behavior ##

``` python
u = mda.Universe('protein.mol2')
u_no_h = u.select_atoms("not type H")
u_no_h.atoms.fragments

# The following will be the same
print(sum([len(x.atoms) for x in u_no_h.atoms.fragments]))
print(len(u.atoms))
# This value will differ
print(len(u_no_h.atoms))
```

## Current version of MDAnalysis ##
- MDA version 2.1.0
- Python 3.7.11
- CentOS 7

**Comment by richardjgowers** [comment]
Hi @Michael-C-Strobel thanks for raising this.  This is actually the desired behaviour, something like "get fragments to which these atoms belong".  I can see that you're actually trying to do something like "split this atomgroup into fragments", so this might work:

```python
frags = u.atoms.fragments
frags_noh = [f.select_atoms('not type H') for f in frags]
```

**Comment by Michael-C-Strobel** [comment]
Thank you! I wasn't sure whether this was the intended behavior. The code you posted should do what I was hoping for.

Out of curiosity, is there any way to perform an atom selection on AtomGroups or Universes so that they no longer reference the original?

**Comment by richardjgowers** [comment]
Not sure I follow what you mean with referencing the original.  If you're talking about creating an independent copy, this isn't really possible as all data lives inside the Universe, and AtomGroups are just views onto this master data.

**Comment by lilyminium** [comment]
If you're ok with the cost of creating a new universe, you could do:

```
u2 = mda.Merge(u_no_h)
```

and that will only contain fragments belonging to the `u_no_h` group.

**Comment by Michael-C-Strobel** [comment]
Yes, that's exactly what I was looking for. Thank you both very much!
