### ISSUE TITLE
doc build test fails due incorrect code-block syntax throughout the docs

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/mdanalysis#3674]
## Expected behavior ##

Documentation build test passes when docs are not changed.

## Actual behavior ##

Doc build failed for PR #3415 , apparently the current sphinx version takes a stricter view on 

See https://github.com/MDAnalysis/mdanalysis/runs/6536174554?check_suite_focus=true

specifically
```
/home/runner/work/mdanalysis/mdanalysis/package/MDAnalysis/analysis/density.py:docstring of MDAnalysis.analysis.base.AnalysisBase.run:16: ERROR: Error in "code-block" directive:
maximum 1 argument(s) allowed, 14 supplied.
```

## Code to reproduce the behavior ##

```reST
.. code-block:: python
   import MDAnalysis as mda
   from MDAnalysisTests.datafiles import TPR, XTC
   from MDAnalysis.analysis import rms
   ...
```

this should probably have a newline inserted:

```reST
.. code-block:: python

   import MDAnalysis as mda
   from MDAnalysisTests.datafiles import TPR, XTC
   from MDAnalysis.analysis import rms
   ...
```

## Current version of MDAnalysis ##

See PR #3415

**Comment by IAlibay** [comment]
Self assigning since we'll need this fixed as a priority for 2.2.0

**Comment by orbeckst** [comment]
I am currentlty going through and trying to find everything... don't do anything rash.

**Comment by orbeckst** [comment]
sorry, should have assigned to me

**Comment by orbeckst** [comment]
Just didn't want to fix it as part of the other PR

**Comment by IAlibay** [comment]
Ah great thanks!

**Comment by orbeckst** [comment]
I didn't read the error message properly. This is related to the original PR, which modified the base class. It's not a general problem. Closing.
