### ISSUE TITLE
DL_POLY vs DL_POLY Classic

### ISSUE THREAD

**Issue by rafaelpap** [MDAnalysis/mdanalysis#3678]
## Is your feature request related to a problem? ##
The parser for HISTORY and CONFIG files for DL_POLY does not work with files from DL_POLY Classic.
The format is slightly different for the HISTORY file.
1. The second line has 5 values in DL_POLY and 4 values in DL_POLY Classic. The current parser only used the first 3 values.
2.  The lines for each atom have 5 values in DL_POLY and 4 values in DL_POLY Classic.

## Describe the solution you'd like ##
I would like to be able to read both versions of HISTORY files.

## Describe alternatives you've considered ##
I believe that minimal changes in 
MDAnalysis/coordinates/DLPoly.py
and 
MDAnalysis/topology/DLPolyParser.py
could solve the problem.
For instance:

```
diff DLPoly.py.ORIG DLPoly.py
147,148c147,148
<         header = np.int64(self._file.readline().split())
<         self._levcfg, self._imcon, self.n_atoms, _, _ = header
---
>         header = np.int64(self._file.readline().split()[:3])
>         self._levcfg, self._imcon, self.n_atoms = header

```
and

```
diff DLPolyParser.py.ORIG DLPolyParser.py
137c137
<             while not len(line.split()) == 5:
---
>             while not (len(line.split()) == 4 or len(line.split()) == 5):

```

**Comment by hmacdope** [comment]
Hi @rafaelpap, thanks for the bug report! 

We would welcome any contribution to fix this issue along with some tests for a DL_POLY classic file.

It seems like you have the start of a fix already. If you would like to contribute this fix to MDAnalysis, check out our [contributor guide](https://userguide.mdanalysis.org/stable/contributing.html). We would welcome your PR!

**Comment by rafaelpap** [comment]
Ok, I'll try. It will be my first PR ever.

**Comment by hmacdope** [comment]
If you are having any trouble just ping me using '@hmacdope' and I can give you a hand :)

**Comment by rafaelpap** [comment]
Thanks I just made the pull request. I hope I have done something decent.

**Comment by orbeckst** [comment]
Thanks for your contribution, @rafaelpap !
