### ISSUE TITLE
Mac OS CI

### ISSUE THREAD

**Issue by richardjgowers** [MDAnalysis/mdanalysis#368]
https://github.com/travis-ci/travis-ci/issues/2312
http://docs.travis-ci.com/user/multi-os/

So I think this should be possible from what I've read so far.  Python isn't officially supported on travis with mac os, but there's lots of workarounds that people have used. 

The first few files in this PR show how you can have separate install recipes for linux/mac os
https://github.com/catkin/catkin_tools/pull/196/files

**Comment by giampaolo** [comment]
I am also interested in doing the same thing for https://github.com/giampaolo/psutil but it is not clear to me how to use https://github.com/MacPython/terryfy.

**Comment by kain88-de** [comment]
And what would be the benefit of that? As far as I've seen MDAnalysis isn't using any system-specific code? I doubt that we can find special osx bugs with that, I would assume that most errors on osx are rather due to the way users have installed python.

**Comment by orbeckst** [comment]
I think @kain88-de has a valid point here, so I am closing this for the time being (we have plenty of things to do ;-) ).

**Comment by orbeckst** [comment]
Re-opening in the light of #459.
