### ISSUE TITLE
Bump required nose version?

### ISSUE THREAD

**Issue by mnmelo** [MDAnalysis/mdanalysis#369]
In order to have proper test multiprocessing+coverage one needs `nose>=1.3.7`. (see PR #367)

Just multiprocessing+plugins (excluding coverage) already required `nose>=1.1.0`.

None of these requirements are currently strict. The 1.1.0 requirement is worked around by disabling plugins if a recent enough version isn't found.
The testing code simply fails when running in parallel+coverage unless `nose>=1.3.7`, though most of us didn't actually feel it since
 1. we probably all run a recent nose version;
 1. we don't often test coverage locally;
 1. travis' builds, that do test coverage, were being run serially.

I vote to officially bump MDAnalysisTest's requirement for `nose>=1.3.7` (which will also allow a cleanup of workaround code). Is there any obvious inconvenience?

I'm including this update in PR #367.

**Comment by orbeckst** [comment]
Fine with me. I just merged #367 which de-facto closes this issue so I am closing manually.
