### ISSUE TITLE
awk call in deploy.yaml does not work on macos-latest

### ISSUE THREAD

**Issue by IAlibay** [MDAnalysis/mdanalysis#3693]
Not too problematic since it only affects testing, but this line fails on the macos-latest runners:

https://github.com/MDAnalysis/mdanalysis/blob/eab18cb8418ddb1dd72b44f474833de4a2999884/.github/workflows/deploy.yaml#L240

I suspect reverting to `ver=$(grep "__version__ =" package/MDAnalysis/version.py | awk '{print $3}')` will probably fix things.

**Comment by orbeckst** [comment]
I think you need to use
```
awk '/__version__ =/ {print $3; exit}' package/MDAnalysis/version.py
```
i.e., `exit` instead of `quit`.

I tested on 10.15.7... which is not latest, though.

**Comment by orbeckst** [comment]
Or just leave out the `exit` — just adds a few µs.
