### ISSUE TITLE
tests should use results.rmsf to avoid DeprecationWarning

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/mdanalysis#3695]
## Expected behavior ##

Our tests do not use deprecated constructs that will be removed. 

## Actual behavior ##

Tests trigger `DeprecationWarning` for uses of using the `rmsf` attribute instead of `results.rmsf`
```
analysis/test_encore.py::TestEncore::test_ensemble_superimposition
analysis/test_encore.py::TestEncore::test_ensemble_superimposition
analysis/test_encore.py::TestEncore::test_ensemble_superimposition_to_reference_non_weighted
analysis/test_encore.py::TestEncore::test_ensemble_superimposition_to_reference_non_weighted
  /usr/share/miniconda/envs/test/lib/python3.8/site-packages/MDAnalysis/analysis/rms.py:885: DeprecationWarning: The `rmsf` attribute was deprecated in MDAnalysis 2.0.0 and will be removed in MDAnalysis 3.0.0. Please use `results.rmsd` instead.
    warnings.warn(wmsg, DeprecationWarning)

analysis/test_encore.py::TestEncore::test_rmsd_matrix_with_superimposition
  /usr/share/miniconda/envs/test/lib/python3.8/site-packages/MDAnalysis/analysis/rms.py:718: DeprecationWarning: The `rmsd` attribute was deprecated in MDAnalysis 2.0.0 and will be removed in MDAnalysis 3.0.0. Please use `results.rmsd` instead.
    warnings.warn(wmsg, DeprecationWarning)
```

## Code to reproduce the behavior ##

Run the tests listed above.

## Current version of MDAnalysis ##

- Which version are you using? (run `python -c "import MDAnalysis as mda; print(mda.__version__)"`) 2.2.0
- Which version of Python (`python -V`)? 3.8
- Which operating system? Linux

**Comment by v-parmar** [comment]
Hey @orbeckst, The tests you've listed are triggering warnings for using deprecated constructs in the MDAnalysis library. The specific attributes (rmsf and rmsd) that are being used have been deprecated and will be removed in future versions of the library. 

To resolve this issue, I think you need to update your tests to use the new constructs as specified in the Deprecation Warning message. The new construct is **results.rmsd** which should be used instead of **rmsf** and **rmsd**.

**Comment by orbeckst** [comment]
Yes, these are good instructions for anyone who'd want to take on this issue.

**Comment by v-parmar** [comment]
I want to take this issue. Can you tell me from which file I have to take the code to run the above test?

**Comment by orbeckst** [comment]
If you want to work on this PR, please submit a pull request (as per our GSOC FAQ, we don’t “reserve work”, we just look at the first one who addresses a a problem). 

Look at the User Guide to learn how to run tests locally. 

The output above also shows you the test_*.py files that are raising the warnings (although there might be more). 

I’d run the tests locally with

     pytest | tee out.txt

and redirect the output to a file (I use bash as my command line, your approach may differ) and then  search for “ Please use `results.” to find all occurrences. 

You can then run specific tests by provinding the appropriate test file to pytest, eg

     pytest testsuite/MDAnalysisTests/analysis/test_encore.py

This should give you the idea.
