### ISSUE TITLE
Add m1 support on the conda-forge feedstock for 2.2.0

### ISSUE THREAD

**Issue by IAlibay** [MDAnalysis/mdanalysis#3702]
The first build of 2.2.0 will be without m1 support, we will add afterwards.

We have to follow this process as far as I understand: https://conda-forge.org/blog/posts/2020-10-29-macos-arm64/#how-to-add-a-osx-arm64-build-to-a-feedstock

edit updated docs are here: https://conda-forge.org/docs/maintainer/knowledge_base.html#apple-silicon-builds

**Comment by orbeckst** [comment]
With PR https://github.com/conda-forge/mdanalysis-feedstock/pull/44 and https://github.com/conda-forge/mdanalysistests-feedstock/pull/31 we have M1 packages. Users have confirmed that the packages work. Thank you @IAlibay !

**Comment by orbeckst** [comment]
PR https://github.com/MDAnalysis/MDAnalysis.github.io/pull/233 for a quick blog update.
