### ISSUE TITLE
Provide Ndarray or AtomGroup to distance routines

### ISSUE THREAD

**Issue by hmacdope** [MDAnalysis/mdanalysis#3708]
## Is your feature request related to a problem? ##

We should encourage AtomGroups  as the currency of choice for passing between routines. A major place where this is not the case is in the routines in `distances.py` which can only accept a NumPy array which is then  converted to a `float*` in  `calc_distances.h`.

 It would be fantastic to be able to leverage the power of the routines in `calc_distances.h` directly with an `AtomGroup`

## Describe the solution you'd like ##

Taking `distance_array` as an example it could have the type hinted signature:

```python
def distance_array(reference: Union[np.ndarray, AtomGroup], configuration: Union[np.ndarray, AtomGroup], box: Optional[np.ndarray] = None, result=None,
                   backend: str = "serial") -> None:
```

After some benchmarking in https://github.com/hmacdope/Distance_array_wrapper @richardjgowers and myself settled on using a batched algorithm with a coordinate buffer and preloading of the indices as the most performant option.

This may require partial Cythonization of the `AtomGroup` object, but due to a lot of meta-programming around the `AtomGroup` class itself it may be best to replace only the data intensive portion of the AtomGroup with an Extension type.

**Comment by orbeckst** [comment]
A (late) comment here: We used to say that anything in lib may not use anything in core. The idea to have lib be "numpy only". Circular imports are an issue but we also said that , at least in principle, lib should be generally useable.

*If* we want to keep it that way, the distance routines + AG would need to live elsewhere. 

This can be up for discussion. Perhaps start one on the developer list (if on discord we don't have a record and it's hard to link to the discussion in the future).

**Comment by hmacdope** [comment]
@orbeckst  i have made a [thread](https://groups.google.com/g/mdnalysis-devel/c/X6LnuFA2CQw/m/WDQsN_MeDQAJ?utm_medium=email&utm_source=footer) on the devel mailing list. People can contribute opinions there or here. :)

**Comment by richardjgowers** [comment]
I think the addition of interchangeably using AG or np array in distance-like functions is very important.  I don't think we should introduce a new set of functions that implement this, and throwing this `Union` argument into the existing functions is the correct approach.

If we wanted to respect the rule of `lib` doesn't import any other MDA stuff we could, but we'd still have to import it into lib for backwards compatibility reasons, so it would be aesthetic only.  I think messing up the structure to keep this rule seems like foolish consistency.

**Comment by hmacdope** [comment]
I will quote my comment on #3730 here @orbeckst  @richardjgowers  @jbarnoud :

>This [a specific import] is a circular import unless done at the top level. You can always use a top level import >to get around the circular-ness but whether it is good practice is another question.
>
>The circular import occurs between lib.util and core.groups. I think this can be fixed by moving @check_coords >to its own module in lib because groups.py imports lib.util but doesn't require check_coords. Would people be >happy with this solution?
>
>Or we can hit it with a hammer and use a top level import. Or we can look into a different solution. Let me >know what you think.
