### ISSUE TITLE
OpenMP backend for self_distance_array is broken for tricinic boxes

### ISSUE THREAD

**Issue by hmacdope** [MDAnalysis/mdanalysis#3725]
## Expected behavior ##

The OpenMP distance backend for `self_distance_array` is broken for triclinic boxes on current develop.
There doesn't appear to be a problem with orthorhombic boxes (the `_calc_self_distance_array_ortho` code path) or without a box ( the `calc_self_distance_array`) code path or any of the serial code. There also doesn't appear to be an issue with `distance_array`.

 The problem seems to be limited to `calc_self_distance_array_triclinic` only and isn't picked up by the `TestTriclinicDistances::test_selfdist`  test in `test_distances.py`

## Actual behavior ##

Using the OpenMP backend for `self_distance_array` with a triclinic box segfaults or returns rubbish.  

## Possible Fix

Reverting recent changes to the scoping of OpenMP constructs in commits `4f7087f99f63b5a8f837be894a1027b051b25ca7` and `33d119cc7e0e534993c7af40537768a1df5de81c` (PR #3706 )
 seems to fix the issue.  Perhaps a good place to start is by  reverting these two commits?

I am no OpenMP expert so I couldn't pin down the exact issue. 

## Code to reproduce the behavior ##

``` python
import numpy as np
import MDAnalysis as mda
from MDAnalysis.lib.distances import self_distance_array
from MDAnalysis.tests.datafiles import TRIC

U_tric = mda.Universe(TRIC)
pos_tric = U_tric.coord.positions
box_tric = U_tric.coord.dimensions
self_da_serial_tric = self_distance_array(pos_tric, box=box_tric, backend='serial') # all good
self_da_openmp_tric = self_distance_array(pos_tric, box=box_tric, backend='openmp') #  <-- may segfault
np.testing.assert_allclose(self_da_serial_tric, self_da_openmp_tric) # nope
```

## Current version of MDAnalysis ##

- Which version are you using? (run `python -c "import MDAnalysis as mda; print(mda.__version__)"`) 2.3.0-dev0
- Which version of Python (`python -V`)? 3.9
- Which operating system? Ubuntu

**Comment by richardjgowers** [comment]
This is a little worrying because CI should have caught it? Unless it's some bizarre bug that only shows up with some compiler etc.

**Comment by RMeli** [comment]
Oh boy... that's my bad! I was a bit over-zealous to remove the `private` clause here:
https://github.com/MDAnalysis/mdanalysis/blob/a2f9e9457175ac67185e397adc6c6ad67eb9bce0/package/MDAnalysis/lib/include/calc_distances.h#L505-L514

Sorry about that! I can provide a fix, together with an additional test (for future refactoring).

**Comment by hmacdope** [comment]
Yeah the current test case doesn't seem to catch it. 

Something like the code to reproduce in this issues is likely sufficient, testing that the two backends return the same. 

Note that if you get a segfault it may not always  show up as a test failure, which I noted in the wiki. 

We are happy with a hotfix? I can close #3726 which is a revert if so.
