### ISSUE TITLE
make MDAnalysisTests conda package "noarch" instead of arch/os specific

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/mdanalysis#3727]
## Is your feature request related to a problem? ##
The MDAnalysisTests conda package at https://github.com/conda-forge/mdanalysistests-feedstock is created as a OS and architecture-dependent package even though it only contains Python code. This leads to delays in updating the package (e.g., for new archs such as osx-arm64).

## Describe the solution you'd like ##
Publish as a **noarch** package.

## Describe alternatives you've considered ##
Keep as is for now, it's working right now.

## Additional context ##
* initial discussion https://github.com/conda-forge/mdanalysistests-feedstock/pull/31
* PR https://github.com/conda-forge/mdanalysistests-feedstock/pull/33 implementing the noarch package

**Comment by orbeckst** [comment]
A new noarch package [noarch/mdanalysistests-2.2.0-pyhd8ed1ab_1.tar.bz2](https://anaconda.org/conda-forge/mdanalysistests/2.2.0/download/noarch/mdanalysistests-2.2.0-pyhd8ed1ab_1.tar.bz2) is up on anaconda.

I have some questions in https://github.com/conda-forge/mdanalysistests-feedstock/issues/36 and assuming that these questions are not a problem, we can close this issue.

**Comment by IAlibay** [comment]
Closing as completed.
