### ISSUE TITLE
<< error drying trajectories >>

### ISSUE THREAD

**Issue by icamps** [MDAnalysis/mdanalysis#3732]
## Expected behavior ##

Remove water and ions from full time trajectories.
Works well in v2.1dev but fail in last final version.

## Actual behavior ##

Got errors. Image attached.
![Screenshot from 2022-06-04 15-38-00](https://user-images.githubusercontent.com/13273938/175317325-7873d9e3-5b4d-4df7-b184-24b3c60e790f.png)

## Code to reproduce the behavior ##

```
from MDAnalysisTests import datafiles as data
	u2 = mda.Universe(data.TPR, data.XTC)
       complexx_temp = u2.select_atoms(sel_prot, sel_lig)
      # New Universe just with protein+ligand (dry)
      u = mda.Merge(complexx_temp).load_new(
         AnalysisFromFunction(lambda ag: ag.positions.copy(),
                              complexx_temp).run().results,
         format=MemoryReader)

```

## Current version of MDAnalysis ##

- Which version are you using? 2.2
- Which version of Python (`python -V`)? Python 3.10.4
- Which operating system? Ubuntu 22.04 (up to date)

**Comment by jbarnoud** [comment]
The issue is that, in your example, the coordinate array is not in `results` but in `results.timeseries`. This changed in version 2.0.0 to be in line with the other analyses switching to the `Results` object for their results. Here is a runnable example:

```python
import MDAnalysis as mda
from MDAnalysis.analysis.base import AnalysisFromFunction
from MDAnalysisTests import datafiles as data
u2 = mda.Universe(data.TPR, data.XTC)
complexx_temp = u2.select_atoms('protein')
# New Universe just with protein+ligand (dry)
u = mda.Merge(complexx_temp).load_new(
 AnalysisFromFunction(lambda ag: ag.positions.copy(),
                      complexx_temp).run().results.timeseries,
                      format='memory')
```

What surprises me is that your example worked with MDAnalysis 2.1. From what I can see I would expect it not to.

**Comment by icamps** [comment]
Hi @jbarnoud changing `results` to `results.timeseries` fixes the problem!

Thank you very much.
