### ISSUE TITLE
About preprocessing of trajectory for Density analysis

### ISSUE THREAD

**Issue by TianmingQu** [MDAnalysis/mdanalysis#3758]
Hi, I am trying to use the density analysis in MDanalysis and I have some questions about the preprocessing of the trajectory:

For the second and third requirement, how should I break the PBC for all the molecules and how can I remapped all the solvent molecules?

Best,
Tianming

**Comment by orbeckst** [comment]
Hello @TianmingQu , could you please ask your questions either on the user mailing list or in our discord — see https://www.mdanalysis.org/#participating for links?

We try to keep the issue tracker focused on issues related to the code and the docs. If you feel that you're running into a short-coming in the documentation then please raise an issue. If you follow the issue template then that will help us better to address the problem.

Thank you.
