### ISSUE TITLE
Make fixtures in `test_distances` use return just the `Universe`  and not the trajectory as well

### ISSUE THREAD

**Issue by hmacdope** [MDAnalysis/mdanalysis#3759]
## Is your feature request related to a problem? ##

Coming from some discussion on #3730 and a comment by @orbeckst: https://github.com/MDAnalysis/mdanalysis/pull/3730#discussion_r910184346

The trajectory fixtures and their naming in `test_distances.py ` are slightly confusing as they return the universe **and** the trajectory.
This is confusing and a little bit of an anti-pattern.  An example is  the following fixture:

```python
@pytest.fixture()
def DCD_Universe():
    universe = MDAnalysis.Universe(PSF, DCD)
    trajectory = **universe.trajectory**
    return universe, trajctory
```

## Describe the solution you'd like ##

Move to only returning the `Universe ` and  have each test call trajectory if required. 
## Describe alternatives you've considered ##

Leave it the way it is?

**Comment by hsadia538** [comment]
@hmacdope Hello, I want to work on this. Can you help me get started?

**Comment by ojeda-e** [comment]
Hi @hsadia538, thanks for your interest in contributing to MDAnalysis!

As described in the issue, the current fixture `DCD_Universe` returns two elements: a universe and a trajectory. Usually, fixtures return only one element. In this particular case, we would prefer a fixture that returns an MDA universe only. Something like:
```
@pytest.fixture()
def DCD_Universe():
    universe = MDAnalysis.Universe(PSF, DCD)
    return universe
```
Then, by using a fixture that returns a universe _only_, we could update other unit tests in `test_distances.py` and retrieve the associated trajectory only if the unit test really needs it.

If you open a PR, please reference this issue as suggested by the template. 
Thanks!

**Comment by hmacdope** [comment]
@hsadia538 would you be able to introduce yourself on the MDAnalsysis[ developer mailing list](https://groups.google.com/g/mdnalysis-devel) if you haven't already done so? . Its a good central place to meet the developers, discuss ideas and be a part of the community! Its is also really good for our record keeping :)

**Comment by hsadia538** [comment]
@hmacdope I have already joined the developer's list but wasn't sure exactly how to get started.
I will do so now!
