### ISSUE TITLE
Change mmtf reading of formal charges from the `charges` attribute to `formalcharges`

### ISSUE THREAD

**Issue by IAlibay** [MDAnalysis/mdanalysis#3762]
## Expected behavior ##

The contents of `charges` is always expected to contain partial charges.

## Actual behavior ##

For mmtf, formal charges are fed into `charges`, which a) leads to confusing attribute contents, b) now differs from what the PDB reader does.

## Code to reproduce the behavior ##

See https://github.com/MDAnalysis/mdanalysis/blob/d5c7cb9a7807b06c169b418dd5c6c072c33580f5/package/MDAnalysis/topology/MMTFParser.py#L188

## Proposal ##

Switch to using `FormalCharge` instead.

That being said, this is possibly a breaking changing for 2.x? I see it as a *bug* but most folks probably don't. I'm not really sure how we would suitably warn users about the change though.

**Comment by richardjgowers** [comment]
A non breaking change is to duplicate the attribute, which would actually require a different attribute annoyingly (one which defines two attributes to supply)

**Comment by IAlibay** [comment]
I was originally thinking we could do the old bfactor trick for warnings, 

https://github.com/MDAnalysis/mdanalysis/blob/d5c7cb9a7807b06c169b418dd5c6c072c33580f5/package/MDAnalysis/core/topologyattrs.py#L361-L366

But I'm not sure we can suitably pass across the reader class to TopologyAttrs to specifically do that when it's the MMTF reader.

**Comment by richardjgowers** [comment]
Yeah I’m not against nasty hacks for this tbh…

**Comment by orbeckst** [comment]
mmtf will leave the library (mmtf-python's license is not LGPLv2.1+ compatible and it's deprecated) so I'll close as won't fix.
