### ISSUE TITLE
Issue with Documentation for Atom object property "pos"

### ISSUE THREAD

**Issue by rramji** [MDAnalysis/mdanalysis#3764]
## Expected behavior ##

Tutorial in the docs at https://docs.mdanalysis.org/stable/documentation_pages/overview.html implies that Atom has a property called `pos`, when in actuality the property is `position`. Requesting an update to this example on the website.

## Actual behavior ##

The provided code block fails to run, creating confusion for new users, wastes user time. The same example is listed at https://www.mdanalysis.org/pages/basic_example/ where the `position` property is called correctly

## Code to reproduce the behavior ##

``` python
import MDAnalysis
from MDAnalysis.tests.datafiles import PSF,DCD  # test trajectory
import numpy.linalg
u = MDAnalysis.Universe(PSF,DCD)  # always start with a Universe
nterm = u.select_atoms('segid 4AKE and name N')[0]  # can access structure via segid (s4AKE) and atom name
cterm = u.select_atoms('segid 4AKE and name C')[-1]  # ... takes the last atom named 'C'
bb = u.select_atoms('protein and backbone')  # a selection (a AtomGroup)
for ts in u.trajectory:  # iterate through all frames
    r = cterm.pos - nterm.pos  # end-to-end vector from atom positions  ### THIS LINE ERRORS OUT 
    d = numpy.linalg.norm(r)   # end-to-end distance
    rgyr = bb.radius_of_gyration()  # method of a AtomGroup; updates with each frame
    print("frame = %d: d = %f Angstroem, Rgyr = %f Angstroem" % (ts.frame, d, rgyr))

```

## Current version of MDAnalysis ##

- mdanalysis 2.1.0
- Python 3.9.7, MDAnalysis installed with conda
- Linux / Ubuntu

**Comment by orbeckst** [comment]
Thank you for the report, this example is definitely outdated.

**Comment by hsadia538** [comment]
@orbeckst  I built the user guide coed but was unable to find the page with the above example. I was able to map the path based on the live User guide but in code, the `HREF` tag points to the live page rather than a relative path to that page. And its not there in the folder as well. Am I missing something?
See below for reference:
<img width="1042" alt="image" src="https://user-images.githubusercontent.com/24232785/182501837-bb96df0b-e969-4562-b720-391bcd88f391.png">

**Comment by orbeckst** [comment]
The problematic example is in the docs that are generated from the code and _not_ in the User Guide. (In your https://github.com/MDAnalysis/mdanalysis/issues/3764#issuecomment-1203365995 you see the link to the generated docs.) Look for the file [package/doc/sphinx/source/documentation_pages/overview.rst](https://github.com/MDAnalysis/mdanalysis/blob/develop/package/doc/sphinx/source/documentation_pages/overview.rst) in the MDAnalysis/mdanalysis repository.
