### ISSUE TITLE
remove x3dna in 3.0 (Unpacking errors in x3dna)

### ISSUE THREAD

**Issue by jbarnoud** [MDAnalysis/mdanalysis#3788]
At least 2 lines in the legacy x3dna module use unpacking with too many values to unpack.

https://github.com/MDAnalysis/mdanalysis/blob/97ec6df207fa934095ffb093daadf319ca2bfb38/package/MDAnalysis/analysis/legacy/x3dna.py#L204

https://github.com/MDAnalysis/mdanalysis/blob/97ec6df207fa934095ffb093daadf319ca2bfb38/package/MDAnalysis/analysis/legacy/x3dna.py#L213-L216

In both occurrences, the left side expects 6 values, but 12 are provided on the right.

This issue was identified by mypy in #3752.

**Comment by IAlibay** [comment]
Can we just  set x3dna for removal in 3.0? Are people still using it? I'm not super sure why we even keep untested code in MDA, especially code which by all appearances seems to cost $1k to purchase?

**Comment by jbarnoud** [comment]
It is not only untested, it is broken and only shows up on our radar when we do some sort of full sweep of the code.

**Comment by orbeckst** [comment]
Remove in 3.x — I can't remember why we kept it for 2.x.

**Comment by orbeckst** [comment]
I am not sure if we need to go to any length to have the code spit out deprecation warnings. Given that it's in legacy anyway, I suggest to just
- add deprecation note to CHANGELOG
- add deprecation note to docs
