### ISSUE TITLE
migration guide for 0.10 to 0.11 transition

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/mdanalysis#381]
With the [big API changes](/MDAnalysis/mdanalysis/issues?utf8=%E2%9C%93&q=milestone%3A0.11+label%3AAPI) in the **0.11.0 release**, we need documentation to support the users in transitioning their existing code. @tylerjereddy already started the wiki page [MDAnalysis 0.11 unifying release user guide](/MDAnalysis/mdanalysis/wiki/MDAnalysis-0.11-unifying-release-user-guide).

This page (and possibly others, as needed, such as the [Releases Notes for 0.11.0](/MDAnalysis/mdanalysis/wiki/ReleaseNotes0110)) have to be up-to-date and complete before the release so that we can send users to those pages.

**Comment by tylerjereddy** [comment]
MDAnalysis 0.11 user guide sections that require developer verification (please edit and fill in as below if you are comfortable verifying an example covering a particular API change):

| API Change | Verified by a Developer ? |
|------------------|------------------------------------|
|[Removed Contact Matrix progress meter](https://github.com/MDAnalysis/mdanalysis/wiki/MDAnalysis-0.11-unifying-release-user-guide#removed-contact-matrix-progress-meter) | |
|[New Timestep behaviour] (https://github.com/MDAnalysis/mdanalysis/wiki/MDAnalysis-0.11-unifying-release-user-guide#new-timestep-behaviour)||
|[atomgroup methods to properties and select_atoms replacing selectAtoms](https://github.com/MDAnalysis/mdanalysis/wiki/MDAnalysis-0.11-unifying-release-user-guide#atomgroup-methods-to-properties-and-select_atoms-replacing-selectatoms)| Tyler |

**Comment by mnmelo** [comment]
The `global` selection keyword, proposed in #268, deprecates the `fullgroup` one, and I thought it'd be good to bundle this change together with the 0.11 breaking changes.

I just submitted PR #394 with the update, and will add a section on the migration guide.

**Comment by orbeckst** [comment]
Note on deprecations: anything that was deprecated should be changed. A user who has applied all changes in the guide should not see any deprecation warnings any more.
