### ISSUE TITLE
Travis job for ARM is systematically failing

### ISSUE THREAD

**Issue by jbarnoud** [MDAnalysis/mdanalysis#3815]
## Expected behavior ##

The Travis job for ARM, like all other CI jobs, passes on develop.

## Actual behavior ##

The job systematically fails with the following error:

```
____________ ERROR collecting MDAnalysisTests/lib/test_distances.py ____________

ImportError while importing test module '/home/travis/build/MDAnalysis/mdanalysis/testsuite/MDAnalysisTests/lib/test_distances.py'.

Hint: make sure your test modules/packages have valid Python names.

Traceback:

/opt/python/3.8.3/lib/python3.8/importlib/__init__.py:127: in import_module

    return _bootstrap._gcd_import(name[level:], package, level)

/home/travis/build/MDAnalysis/mdanalysis/testsuite/MDAnalysisTests/lib/test_distances.py:23: in <module>

    from tkinter import FALSE

/opt/python/3.8.3/lib/python3.8/tkinter/__init__.py:36: in <module>

    import _tkinter # If this fails your Python may not be configured for Tk

E   ModuleNotFoundError: No module named '_tkinter'
```

The issue appeared first here: <https://app.travis-ci.com/github/MDAnalysis/mdanalysis/jobs/578634668>. The corresponding commit does not look related.

## Code to reproduce the behavior ##

See https://app.travis-ci.com/github/MDAnalysis/mdanalysis/builds

## Current version of MDAnalysis ##

Develop branch on Travis CI for ARM.

**Comment by tylerjereddy** [comment]
For MacOS ARM CI I had to add `brew install python-tk@3.10` over in gh-3780 to avoid the same problem, so maybe we could apply a similar strategy for the Linux flavor of ARM (maybe not using `brew` though).

Someone was saying there are better options than Travis CI (finite resource limits, etc.) for linux ARM as well, though I've not tried them and that's a separate matter.

**Comment by IAlibay** [comment]
Ah that's a pain - I'll self assign to avoid several of us using Travis credits at the same time (I'll have a poke at things later this week), if you're looking into it please give it a shout here!

Re Travis alternative - I believe there's an effort to get direct AWS CI access (rather than going through Travis) on the NF side of things, I can add it to our AWS requirements we will bring to the summit.

edits: typos
