### ISSUE TITLE
Chunked trajectory reader with `xarray`? 

### ISSUE THREAD

**Issue by hmacdope** [MDAnalysis/mdanalysis#3817]
## Is your feature request related to a problem? ##

Following discussion on #238 I think it might be a good idea to revisit the idea of a chunked  trajectory reader.  @richardjgowers and I had some very productive discussions with some of the `xarray`, `Dask` and `zarr` people at Scipy, who all indicated that chunked reading of files was a big performance gain to be made and that perhaps the xarray or zarr frameworks could help. 

Xarray has a backed for chunked reading and lazy loading that `Dask` understands. See [here](https://docs.xarray.dev/en/stable/internals/how-to-add-new-backend.html?highlight=chunk) for details. 

 This may be helpful for any parallelisation work we may want to do (tagging @yuxuanzhuang), Something to investigate is whether we can get this system to cooperate with our more specialist file formats.

@richardjgowers and I also investigated using [Zarr](https://zarr.readthedocs.io/en/stable/) to do the chunking. This was also a promising direction but was a little bit of a hack of the Zarr format. 

Another option is to cook up the chunking ourselves. This shouldn't be impossible, but we may lose out on the ability to integrate with Dask easily and/or tighter integration with something like Xarray, which I argue would be good for interoperability. 

## Describe the solution you'd like ##

We should be able to read a trajectory file in a chunked manner. This would reduce the need to wait for data to come of disk and help with pipe-lining.  It may also allow us to talk to parallelisation engines such as Dask. 

## Considerations

-  May require special time-step with a multi frame buffer
-  How does this interact with all of the other code that relies on ts = single frame?
-  Do this at the C, Cython or Python level?
-  How does this interact with some file formats that have on-disk chunking (eg HDF5, see [here](https://support.hdfgroup.org/HDF5/doc/Advanced/Chunking/))

**Comment by hmacdope** [comment]
Sorry I made a hash of this issue, hopefully it's digestable now.

**Comment by jbarnoud** [comment]
I am only interpreting what you are saying here, so I may be completely off-base. I would suggest keeping the TimeStep as a single frame even if it is only a view on top of a multi-frames buffer object. This way we do not have to change anything that depends on TimeSteps which makes the project much more viable.

**Comment by hmacdope** [comment]
This has moved mostly to `zarrtraj` [mdakit](https://github.com/Becksteinlab/zarrtraj)
