### ISSUE TITLE
Remove `--fast-math` from compile flags?

### ISSUE THREAD

**Issue by IAlibay** [MDAnalysis/mdanalysis#3821]
Based on recent issues highlighted on denormals behaviour, do we want to just get rid of that flag?

**Comment by jbarnoud** [comment]
What is the performance hit for getting rid of it? But since it is contagious, we probably want to remove it.

**Comment by orbeckst** [comment]
After having read through all of the stuff that @lilyminium had posted, I am in favor of removing it.

**Comment by jbarnoud** [comment]
Just for the sake of it, I did run the [script](https://gist.github.com/moyix/2154125d0cb9947ec0525fb49449fab7) for the [article](https://moyix.blogspot.com/2022/09/someones-been-messing-with-my-subnormals.html).

While we do [reference the `-ffast-math` option](https://github.com/MDAnalysis/mdanalysis/blob/e7ee5a4a077c2179d6037ba634240ce7ebcb76ef/package/setup.py#L270-L271), the script did not find any issue. This makes it difficult for me to assess the effectiveness of a fix.

For the record, this is what I did:
```bash
pip install -e ./package/
python ~/src/fast_check_for_ffast_math.py $(find ./ -name '*.so')
```

**Comment by jbarnoud** [comment]
I should add that we are not in the list compiled as part of the article: https://moyix.net/~moyix/ffast_summary.html

**Comment by jbarnoud** [comment]
Also, we need to make sue we do not introduce a regression about #2722.
