### ISSUE TITLE
Make networkx an optional dep?

### ISSUE THREAD

**Issue by IAlibay** [MDAnalysis/mdanalysis#3822]
Networkx is solely used by a single analysis module (leaflet.py). It may make sense to make this an optional dependency?

**Comment by orbeckst** [comment]
Sure. 

By now we seem to have settled on a typical pattern for dealing with optional packages: flag availability with HAS_PACKAGE from a try/except ImportError, raise exception inside function/class if not available. Guard tests.

**Comment by richardjgowers** [comment]
Yes.

**Comment by hmacdope** [comment]
> Sure.
> 
> By now we seem to have settled on a typical pattern for dealing with optional packages: flag availability with HAS_PACKAGE from a try/except ImportError, raise exception inside function/class if not available. Guard tests.

Should we make this official policy in Docs / Userguide/ wiki?

**Comment by IAlibay** [comment]
Mmm I don't know just yet, there was plan with some OMSF folks to move this to a separate package that uses importlib creatively. Not sure where that got.

**Comment by orbeckst** [comment]
We should have a written policy on optional packages. I'll put a note on agenda for the next meeting.
