### ISSUE TITLE
import nglview error: 

### ISSUE THREAD

**Issue by xibing** [MDAnalysis/mdanalysis#3835]
I just installed MDAnalysis, and I'm following the tutorial. 
However, when I typed the following commands in jupyter notebook:
import nglview as nv
I got error message like:
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/tmp/ipykernel_34722/4157016293.py in <module>
----> 1 import nglview as nv

~/.local/lib/python3.7/site-packages/nglview/__init__.py in <module>
      2 
      3 # for doc
----> 4 from . import adaptor, datafiles, show, widget
      5 from ._version import get_versions
      6 from .adaptor import *

~/.local/lib/python3.7/site-packages/nglview/show.py in <module>
     11                       RdkitStructure,
     12                       TextStructure)
---> 13 from .widget import NGLWidget
     14 
     15 __all__ = [

~/.local/lib/python3.7/site-packages/nglview/widget.py in <module>
     17 import traitlets
     18 
---> 19 from . import color, interpolate
     20 from .adaptor import Structure, Trajectory
     21 from .component import ComponentViewer

~/.local/lib/python3.7/site-packages/nglview/color.py in <module>
    112 
    113 
--> 114 ColormakerRegistry = _ColormakerRegistry()

~/.local/lib/python3.7/site-packages/nglview/base.py in getinstance()
      8     def getinstance():
      9         if cls not in instances:
---> 10             instances[cls] = cls()
     11         return instances[cls]
     12     return getinstance

~/.local/lib/python3.7/site-packages/nglview/color.py in __init__(self, *args, **kwargs)
     45         try:
     46             get_ipython() # only display in notebook
---> 47             self._ipython_display_()
     48         except NameError:
     49             pass

~/.local/lib/python3.7/site-packages/nglview/color.py in _ipython_display_(self, **kwargs)
     52         if self._ready:
     53             return
---> 54         super()._ipython_display_(**kwargs)
     55 
     56     def __repr__(self):

AttributeError: 'super' object has no attribute '_ipython_display_'
---------------------------------------------------------------------------

**Comment by IAlibay** [comment]
Hi @xibing thanks for opening this issue.

Unfortunately this is an issue upstream of MDAnalysis, please refer to this issue: https://github.com/nglviewer/nglview/issues/1032

**Comment by IAlibay** [comment]
Since this issue does not appear to be related to the MDAnalysis codebase itself, I will go ahead and close it.

Please do re-open if you think otherwise.

If you have any further questions related to installation or using MDAnalysis we would be happy to chat on the mdanalysis user mailing list or our discord server: https://www.mdanalysis.org/#participating
