### ISSUE TITLE
MAINT: Cython lint

### ISSUE THREAD

**Issue by tylerjereddy** [MDAnalysis/mdanalysis#3838]
I saw [`cython-lint`](https://github.com/MarcoGorelli/cython-lint) [used successfully upstream](https://github.com/scipy/scipy/pull/17014) and ran it on MDAnalysis out of curiosity (below). Maybe some straightforward fixups we could accept.

`cython-lint MDAnalysis/lib/*.pyx MDAnalysis/coordinates/*.pyx MDAnalysis/analysis/encore/*.pyx`

```
MDAnalysis/lib/c_distances.pyx:38:24: 'fabs' imported but unused
MDAnalysis/lib/c_distances.pyx:299:17: 'j' defined but unused
MDAnalysis/coordinates/timestep.pyx:130:24: 'asiterable' imported but unused
MDAnalysis/coordinates/timestep.pyx:131:30: 'auxreader' imported but unused
MDAnalysis/coordinates/timestep.pyx:132:30: 'AuxReader' imported but unused
MDAnalysis/coordinates/timestep.pyx:133:16: 'units' imported but unused
MDAnalysis/coordinates/timestep.pyx:135:5: '_READERS' imported but unused
MDAnalysis/coordinates/timestep.pyx:135:15: '_READER_HINTS' imported but unused
MDAnalysis/coordinates/timestep.pyx:136:5: '_SINGLEFRAME_WRITERS' imported but unused
MDAnalysis/coordinates/timestep.pyx:137:5: '_MULTIFRAME_WRITERS' imported but unused
MDAnalysis/coordinates/timestep.pyx:138:5: '_CONVERTERS' imported but unused
MDAnalysis/coordinates/timestep.pyx:142:21: 'bool' imported but unused
MDAnalysis/coordinates/timestep.pyx:143:26: 'int64_t' imported but unused
MDAnalysis/coordinates/timestep.pyx:144:8: 'cython' imported but unused

```

**Comment by hmacdope** [comment]
:sweat_smile: oops, timestep.pyx is my fault.

**Comment by shalearkane** [comment]
Can you assign me this issue?

**Comment by hmacdope** [comment]
> MDAnalysis/coordinates/timestep.pyx:132:30: 'AuxReader' imported but unused

@shalearkane you are free to work in this if you want. Have a look at our [contributing guide ](https://userguide.mdanalysis.org/stable/contributing.html) and make a PR. Ping me if you are having any trouble.
