### ISSUE TITLE
Problem with Hole class

### ISSUE THREAD

**Issue by gormanstock** [MDAnalysis/mdanalysis#384]
Hello,

It would seem whenever someone tries to set the cpoint for the hole class that it is actually being stored as the cvect instead. This causes an error no matter what the syntax.
<img width="564" alt="cpoint" src="https://cloud.githubusercontent.com/assets/5720588/9118631/cfb853a8-3c3f-11e5-9662-494fe83e7096.png">

**Comment by orbeckst** [comment]
Hi @gormanstock , I can confirm the problem

```python
import MDAnalysis
from MDAnalysis.tests.datafiles import PDB_HOLE, XTC_HOLE
from MDAnalysis.analysis.hole import HOLE, HOLEtraj

# run hole on a single frame, set the options that don't work
H = HOLE(PDB_HOLE, cvect=[0, 1, 0], cpoint=[0, 0, 4], sample=1.0, ... )
H.run(inpfile="hole_debugging.inp")
```
and `hole_debugging.inp` contains
```
! Input file for Oliver Smart's HOLE program
! written by MDAnalysis.analysis.hole.HOLE
! filename = .../mdanalysis/testsuite/MDAnalysisTests/data/1grm_single.pdb
COORD  ./tmp3jzLKu/1grm_single.pdb
RADIUS /Users/oliver/tmp/simple2.rad
SPHPDB hole.sph
SAMPLE 1.000000
ENDRAD 22.000000
IGNORE SOL WAT TIP HOH K   NA  CL
SHORTO 0

CPOINT 0 1 0

CVECT  0 1 0
```

i.e. `CPOINT` is *not* `0 0 4`.

**Comment by gormanstock** [comment]
Yes exactly, I've fixed it in my code but I'm not too familiar with github
so I didn't try to submit anything.

On Thu, Aug 6, 2015 at 4:00 PM, Oliver Beckstein <notifications@github.com>
wrote:

> Hi @gormanstock <https://github.com/gormanstock> , I can confirm the
> problem
>
> import MDAnalysisfrom MDAnalysis.tests.datafiles import PDB_HOLE, XTC_HOLEfrom MDAnalysis.analysis.hole import HOLE, HOLEtraj
> # run hole on a single frame, set the options that don't work
> H = HOLE(PDB_HOLE, cvect=[0, 1, 0], cpoint=[0, 0, 4], sample=1.0, ... )
> H.run(inpfile="hole_debugging.inp")
>
> and hole_debugging.inp contains
>
> ! Input file for Oliver Smart's HOLE program
> ! written by MDAnalysis.analysis.hole.HOLE
> ! filename = .../mdanalysis/testsuite/MDAnalysisTests/data/1grm_single.pdb
> COORD  ./tmp3jzLKu/1grm_single.pdb
> RADIUS /Users/oliver/tmp/simple2.rad
> SPHPDB hole.sph
> SAMPLE 1.000000
> ENDRAD 22.000000
> IGNORE SOL WAT TIP HOH K   NA  CL
> SHORTO 0
>
> CPOINT 0 1 0
>
> CVECT  0 1 0
>
> i.e. CPOINT is *not* 0 0 4.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MDAnalysis/mdanalysis/issues/384#issuecomment-128487106>
> .
>



-- 
--Gorman Stock

**Comment by orbeckst** [comment]
If you copy and past the code or, even better, just dump it into a [gist](https://gist.github.com/) and link it, I will create a commit with your name.

**Comment by gormanstock** [comment]
https://gist.github.com/gormanstock/8fd9de4fa250c5d9c44f#file-hole-py
I really only changed one line... I don't know if that merits putting me with the other authors :D

**Comment by orbeckst** [comment]
It does, by the standards that we have been applying. If you contribute, you're an author. (We like to think of MDAnalysis as a truelu *open* source project and try to be welcoming and also properly attribute all contributions.)

**Comment by gormanstock** [comment]
Ok then, put me down as Gorman Stock.

**Comment by orbeckst** [comment]
Gorman,

Many thanks: I will user [hole.py, line 799](https://gist.github.com/gormanstock/8fd9de4fa250c5d9c44f#file-hole-py-L799). Thanks a lot. (What an embarrassing mistake...)

**Comment by gormanstock** [comment]
No problem, I'll report back if I have any more trouble running the hole analysis.

**Comment by orbeckst** [comment]
I will close when the code goes in.

Do you have an email that I can add to the commit message – typically the email that your GitHub account is linked to so that GitHub will know that this is your commit?

**Comment by gormanstock** [comment]
gormanstock@gmail.com

**Comment by orbeckst** [comment]
Thanks, I will just delete the comment with your plain email again.
