### ISSUE TITLE
LAMMPS dump file unwrap trajectory and import velocities and forces

### ISSUE THREAD

**Issue by jaclark5** [MDAnalysis/mdanalysis#3843]
## Is your feature request related to a problem? ##
LAMMPS trajectories can be written in two way, (1) xu yu zu in dump to allow diffusion coefficients to be computed. and (2) x y z ix iy iz, where the image flags keep track of which image of the wrapped box that a particle is in. In theory, this means one could unwrap the box, however this information is lost upon import into MDAnalysis.
In addition, MDAnalysis does not import velocities and forces from dump files.

## Additional context ##
I'm aware of the other LAMMPS related pull request but all changes there refer to the LAMMPSParser in topology, not MDAnalysis/coordinates/LAMMPS.py

**Comment by jaclark5** [comment]
Unlike my other recent Pull Requests, I haven't updated the docs or tests for this one. Since there is ongoing work with LAMMPS compatibility, I wanted opinions. I've been using these changes for my work for about a year.

**Comment by hmacdope** [comment]
Thanks for the contribution @jaclark5! See my comments on the PR :)

**Comment by hmacdope** [comment]
As an additional comment, there are some ongoing changes to LAMMPS reading but most of those PRs havn't had any activity for a little bit so feel free to make changes as we are not holding for any LAMMPs stuff at the moment.
