### ISSUE TITLE
Isolayer selection

### ISSUE THREAD

**Issue by jaclark5** [MDAnalysis/mdanalysis#3845]
## Is your feature request related to a problem? ##
There are currently methods of selecting a spherical or cylindrical "shell" where atoms are at least r_min away but less than r_max away, however it would be nice if there was something for flexible.

## Describe the solution you'd like ##
Such an isolayer selection tool could:
1) find a flexible shell region relative to a polymer backbone, where it is sort of cylindrical but not quite
2) Select the second hydration shell of ions, while excluding water than is in the first shell of another ion.

**Comment by richardjgowers** [comment]
Re point 2) @orionarcher recently wrote a lot of great a code related solvation here: https://github.com/MDAnalysis/solvation-analysis
