### ISSUE TITLE
HBond Analysis, efficiency, usability, LAMMPS friendliness

### ISSUE THREAD

**Issue by jaclark5** [MDAnalysis/mdanalysis#3847]
## Expected behavior ##

- The language in the documentation specifies the cutoffs in hbond analysis to be the min or max *allowed* which implies inclusive logical statements
- LAMMPS files only have types (at the moment, it is possible that molecule numbers and types could be saved as resnames and names) making this package unusable.
- A result of nan from the function is difficult to decipher
- guess_donor function takes a long time when hydrogen atoms are already known

## Actual behavior ##

- The cutoffs in hbond analysis code use exclusive statements.
- LAMMPS files cannot be used with this function
- One must be developer savy  enough to comb through the package to find out why a value of NaN was given.
- guess_donor function could use bonding information since hydrogen types are called anyway and would be faster, instead of existing distance cutoff.

**Comment by richardjgowers** [comment]
Hi @jaclark5 !

I'd fully agree that the current hydrogen bonds analysis code is very bio-leaning, so expects residues & resnames, and could be more general.
