### ISSUE TITLE
XYZ files from LAMMPS Traj don't use types

### ISSUE THREAD

**Issue by jaclark5** [MDAnalysis/mdanalysis#3851]
## Expected behavior ##

* Write out XYZ with atom types when names or elements are not available (applicable when LAMMPS files are imported)

## Actual behavior ##

* If atom names or elements are not available, all Xs are used in the XYZ file.

## Current version of MDAnalysis ##

- Which version are you using? 2.4.0-dev0
- Which version of Python? Python 3.9.13
- Which operating system? MacOS 11.6

**Comment by RMeli** [comment]
A while ago I had a long (offline) discussion with @IAlibay about readers and writers, and IIRC the conclusion was that MDAnalysis should be able to read most of the files out in the wild, but only write standard-compliant files. I don't think there is an official XYZ standard (see comment on [Open Babel's description](https://openbabel.org/wiki/XYZ_%28format%29)), but maybe the writer should just fail if the elements attribute is absent? Users could still abuse the writer functionality by manually assigning the atom types attribute to the elements attribute, if they wish to do so.

**Comment by IAlibay** [comment]
> A while ago I had a long (offline) discussion with @IAlibay about readers and writers, and IIRC the conclusion was that MDAnalysis should be able to read most of the files out in the wild, but only write standard-compliant files. I don't think there is an official XYZ standard (see comment on [Open Babel's description](https://openbabel.org/wiki/XYZ_%28format%29)), but maybe the writer should just fail if the elements attribute is absent? Users could still abuse the writer functionality by manually assigning the atom types attribute to the elements attribute, if they wish to do so.

Yeah that was pretty much what my previously mentioned "concern" was. As far as I'm aware the "community agreed" standard for XYZ is that the first column is elements. That being said, I'm open to trying to understand why types are needed here and if there's a new tool out there that specifically needs types then one option would be to just offer a subclass?

**Comment by hmacdope** [comment]
AFAIK types are just the currency of the LAMMPS world. I agree with @RMeli that if you want the types to be the "elements" you should have to set that manually through the attribute.

**Comment by IAlibay** [comment]
Unless there's an alternative opinion from the core team I'm unfortunately going to label this as wontfix - if there's a standard that LAMMPS has that we then want to implement then I'm going to ask that it comes as a subclass of the XYZ parser rather than an amendment.
