### ISSUE TITLE
How to create a Universe with sliced trajectory?

### ISSUE THREAD

**Issue by lucl13** [MDAnalysis/mdanalysis#3860]
Is there anyway to specify the frame slicing range when creating a Universe object?

**Comment by lilyminium** [comment]
Hi @lucl13, welcome to MDAnalysis. Short answer: not really, but you can usually work around this.

Long answer: usually when a Universe is created, only a single frame's coordinates is loaded into memory. Going to another frame involves reading from the files on disk. One way to get around this is to load into memory, e.g.:


```python
>>> import MDAnalysis as mda
>>> from MDAnalysis.tests.datafiles import TPR, XTC
>>> u = mda.Universe(TPR, XTC, in_memory=True)
>>> len(u.trajectory)
10
```

From there you can create a new universe (e.g. with the first, fourth, and fifth frames):

```python
>>> u2 = mda.Universe(TPR, u.trajectory.coordinate_array[[0, 3, 4]])
>>> len(u2.trajectory)
3
```

However, this is frequently not necessary, as you can slice trajectories while iterating over them:

```python
>>> for timestep in u.trajectory[[0, 3, 4]]:
...    print(timestep.time)
...
0.0
300.0000228881836
400.0000305175781
```

or pass `frames` in analyses (in MDAnalysis 2.2.0 and up):

```python
>>> from MDAnalysis.analysis import rms
>>> r = rms.RMSD(u, select="backbone").run(frames=[0, 3, 4])
>>> r.results.rmsd
array([[0.00000000e+00, 0.00000000e+00, 6.39120343e-07],
       [3.00000000e+00, 3.00000023e+02, 7.53671026e+00],
       [4.00000000e+00, 4.00000031e+02, 7.29534342e+00]])
```

or `start, stop, step` (for older versions):

```python
>>> r = rms.RMSD(u, select="backbone").run(start=1, stop=5, step=2)
>>> r.results.rmsd
array([[  1.        , 100.00000763,   8.16775382],
       [  3.        , 300.00002289,   7.53671026]])
```

Hope that helps. In the future, please ask questions on our [mailing list](https://groups.google.com/group/mdnalysis-discussion) or [Discord](https://www.mdanalysis.org/2021/03/20/discord/), as we use the issue tracker to track bugs and feature requests.
