### ISSUE TITLE
Python 3.11

### ISSUE THREAD

**Issue by IAlibay** [MDAnalysis/mdanalysis#3878]
Python 3.11 is now out 🚀 

As usual, making sure CI is fully 3.11 compliant is going to take a long while, mostly for conda-forge to catch up, and then for all our optional upstream deps to release 3.11 builds.

We've been testing against 3.11-rc.2 and everything seems fine, so we can probably start with pure python builds in the immediate term.

This issue exists to keep track of everything we need to do:

- [x] Update the twice weekly pure Python cron jobs to include 3.11 instead of 3.11-rc.2
- [x] Update the setup classifiers to include 3.11
- [x] Update main CI (conda-forge / mamba installs) to include 3.11 as a minimum deps 3.11 install
- [x] Update main CI to have a full deps 3.11 install
- [x] Update CD to include cp3.11 wheel building: https://github.com/MDAnalysis/mdanalysis/blob/develop/.github/workflows/deploy.yaml#L39
- [x] Update CD testpypi checks to include 3.11 https://github.com/MDAnalysis/mdanalysis/blob/develop/.github/workflows/deploy.yaml#L192
- [x] Add 3.11 to azure pipelines yaml call
- [x] Update cirrus build to use 3.11
- [x] Bump up asv benchmarks to also be py3.11

**Comment by orbeckst** [comment]
Given that 3.11 is supposedly increasing performance by 10-30% we should add it to the ASV benchmarks, too. (Not in this issue…more as a reminder to myself and anyone interested.)

**Comment by orbeckst** [comment]
Can we close this issue? Aren't we fully supporting 3.11 by now?

**Comment by IAlibay** [comment]
> Can we close this issue? Aren't we fully supporting 3.11 by now?

Please see the two missing tasks.

Most of our optional deps (including h5py which is required for azure pipelines) do not support py3.11 yet.

edit: by support I mean wheels here, technically h5py probably works fine with py311, but we can't build the wheels natively in azure pipelines without a lot of extra work.
