### ISSUE TITLE
Improve DCD reader typing and performance. 

### ISSUE THREAD

**Issue by hmacdope** [MDAnalysis/mdanalysis#3882]
The Cython DCD reader could do with a little bit of an update. There was a large regression in its performance compared to the other readers as measured by the ASV benchmarks around 6ae0eb12  See attached screen-cap of the ASV benchmarks. 

There is room for improvement in the typing used in the cython. Cython can be very particular about the use of types wherever possible. Inspection of the annotated html indicates there is room for improvement that will hopefully help with performance. 

![Screenshot from 2022-10-26 15-35-43](https://user-images.githubusercontent.com/24581003/197935511-fecdbdb6-e820-48b7-abfe-6e7a628921b7.png)

**Comment by Luthaf** [comment]
I found that the performance of MDA DCD reader depends a lot on the OS/filesystem combo (cf https://github.com/chemfiles/benchmarks/). I don't understand how that would happen, but might be interesting to investigate.

**Comment by hmacdope** [comment]
@Luthaf from reading the benchmarks it looks like a huge performance loss on your ubuntu benchmark? Interesting I will keep in mind.

**Comment by IAlibay** [comment]
I suspect the M1's SoC architecture might have quite some involvement here?
