### ISSUE TITLE
change `cimport numpy as np` to `cimport numpy as cnp` for consistency

### ISSUE THREAD

**Issue by hmacdope** [MDAnalysis/mdanalysis#3908]
## Is your feature request related to a problem? ##

We should be consistent with the way we cimport numpy in the codebase. 

Lots of places currently use
```cython
 cimport numpy as np
```

While the more modern approach and the one taken in some PRs #3777 , `timestep.pyx` and a few random other existing places is to

```cython 
 cimport numpy as cnp
```

Personally I prefer the second one (and its the one used by pandas) as it is much clearer when the C API is being used vs python API. 
@tylerjereddy  do you know if there is a standard for scipy?

Regardless of which way we go we should be consistent if possible.

Let me know what you think on this issue and if we come to a conclusion I can raise a seperate issue for taking some action. 
Might be a nice easy `good-first-issue` etc.

**Comment by Hakarishirenai** [comment]
Hey @hmacdope, can i take up this issue ?

**Comment by hmacdope** [comment]
For sure, but first let me check with @MDAnalysis/coredevs . Would we like to have consistence and if so 'cnp' or 'np'

**Comment by Hakarishirenai** [comment]
Thank You @hmacdope 
Please let me know about it too.

**Comment by RMeli** [comment]
+1 on this, `scikit-learn` did it as well a while ago: https://github.com/scikit-learn/scikit-learn/issues/23295

**Comment by hmacdope** [comment]
I think people would be keen to have `cnp` consistently (at least me and @RMeli). I think you could reasonably get started on a PR @Hakarishirenai.

**Comment by HunterZ17** [comment]
I'm interested in the issue. Is it available to work on?

**Comment by tylerjereddy** [comment]
both are used in SciPy, but I'm pretty sure I agree that if you want to focus on using `cnp` that makes sense for consistency/clarity. Indeed I bet SciPy would accept a similar patch.

**Comment by hmacdope** [comment]
We have an open PR but it is currently stale #3978, I will ping there, but if no response will consider stale/

**Comment by hmacdope** [comment]
@HunterZ17 no action so PR is stale, feel free to go ahead and make a PR yourself

**Comment by AnoopANair** [comment]
Im interested. Is this issue currently open?

**Comment by RMeli** [comment]
Hi @AnoopANair. Yes, this issue is still open. You can see some initial work in https://github.com/MDAnalysis/mdanalysis/pull/4101, which has been closed without merging.

**Comment by Sumit112192** [comment]
@hmacdope, I tried to address this issue. However, it is failing some tests. I had specific questions regarding this issue. 

- We have `np.ndarray` in the code. So, while changing to `cnp`, do we have to change it to `cnp.ndarray` everywhere or only at certain places? And if at certain places, which one's to change?

- And how to run the benchmark tests locally?
