### ISSUE TITLE
[depend: relicensing] Post 2.4.0 contributions

### ISSUE THREAD

**Issue by IAlibay** [MDAnalysis/mdanalysis#3917]
## Is your feature request related to a problem? ##

The 2.4.0 release will happen roughly around the end of the community comment period for the MDAnalysis relicensing effort.
After this, **should we decide to go ahead with LGPLv3+**, we should aim to work out what we do with any new contributions.

## Describe the solution you'd like ##

- Whilst we are contacting existing code authors, change the license such that we indicate that contributions pre-2.5.0 were originally contributed under GPLv2+, and that new contributions since 2.5.0 are contributed over LGPLv3+.
  - Make this clear in PR templates
  - Change this accordingly once relicensing occurs

## Additional context ##
See: https://www.mdanalysis.org/2022/11/07/relicensing/

**Comment by IAlibay** [comment]
@MDAnalysis/coredevs this proposal would mean having a PR freeze between the 1st of December (the v2.4.0 release date) and the 6th of December (end of community consultation period).

**Comment by orbeckst** [comment]
Yes to all of the above. A short PR freeze is sensible. 

We might have to copy&paste the new licensing note on any open PR and state that when this PR is merged it will be under LGPL and if the author(s) don't like it, please say so and then we close the PR  without merging.

We will also need to state somewhere in LICENSE or elsewhere that code post the 2.4.0 release tag/commit hash is under LGPLv3+ and include a copy of the license text (if we don't do this already).

**Comment by IAlibay** [comment]
I'm trying to draft something ahead of time, I _think_ we might be able to copy wording from other projects (I think _maybe_ cpython?).

**Comment by hmacdope** [comment]
PR freeze is ok with me :)

**Comment by IAlibay** [comment]
So I've been thinking more about the wording here, and I'm trying to work out if we'll need to also change the header files.

Technically `# Released under the GNU Public Licence, v2 or any higher version` remains true, because the we _release_ the files under GPLv2+ for now. But I wonder if we should add extra wording there 🤔 A lot of mix-license packages do happen to do this.

I'm tempted to say we won't at this point but will make it clear under LICENSE itself?

**Comment by orbeckst** [comment]
I would just add an explanatory sentence to the LICENSE file together with the tag/SHA1 of the commit that signifies the start of introduction of LGPLv3+ code.
