### ISSUE TITLE
import numpy as np

### ISSUE THREAD

**Issue by kain88-de** [MDAnalysis/mdanalysis#392]
I've noticed that `numpy` is always imported with it's full name instead of the more standart `import numpy as np`. I'm incredibly used to that from other projects (anything in the python scientific stack) and my own code.  I write `np.<function i want to use>` all the time and then wonder why my code-linter is lighting the line with an error. It would be nice to adopt the more standart  `import numpy as np` in the whole library.

**Comment by mnmelo** [comment]
I for one also use `numpy.function` instead of the shorter standard, and was happy when saw MDAnalysis does the same.
I prefer the extra readability, and, of course, by now I'm too used to it to, so that weighs on my opinion too.

In any case, I do see it's a widespread standard, one which saves three keystrokes per function call, and I won't make much of a fuss if the majority of the devs vote to switch to that.

**Comment by tylerjereddy** [comment]
I still use the explicit `numpy.function` fairly regularly in my own work. I always felt it was consistent with the explicit over implicit zen of python. That said, the shorthand is becoming something of a standard. I can see arguments both ways. When pandas is abbreviated as `pd` and scipy as `sp` and numpy as `np`, it can sometimes seem to get a little out of hand!

**Comment by hainm** [comment]
`np` is commonly used so I think it's fine to use it.

**Comment by dotsdl** [comment]
I am for this change as well. Unless there are objections, I suggest adding this to [0.12](https://github.com/MDAnalysis/mdanalysis/milestones/0.12).

**Comment by richardjgowers** [comment]
I think I've been changing numpy to np where I've been getting annoyed with long lines, so I guess I'm in favour.

I think it'd be good to make a wiki page with some sort of loose style guide which includes stuff like this.

**Comment by orbeckst** [comment]
There seems to be a consensus (or at least no fierce opposition) for using
```python
import numpy as np
```
so let's do that.

While we are at it, we should probably [also avoid direct imports of numpy objects](https://docs.python.org/2/howto/doanddont.html#from-module-import-name1-name2) 
```python
from numpy import sin, cos
```
and consistently use
```python
import numpy as np
np.sin(...)
```
instead.

I don't think that any of the other major packages are used as extensively in MDAnalysis so I would prefer keeping long versions of `scipy`, `biopython` and friends. We might have used `import networkx as nx` somewhere, though, so I can't claim that everything is 100% consistent. if anyone has strong feelings about this, change it back to `networkx` ;-).

**Comment by kain88-de** [comment]
@orbeckst 

I started preparing a PR to change the usage of numpy consistently. I should be through with the revision of all changes today or tomorrow.
