### ISSUE TITLE
Improve deprecation warning for DCDReader copying timestep 

### ISSUE THREAD

**Issue by hmacdope** [MDAnalysis/mdanalysis#3923]
Issue for proper paper trail

Add a deprecation warning for the DCDReader copying timestep unlike the other readers. Behaviour documented in #3889.

paraphrasing:

### Expected behavior ###

The readers should all have the same behaviour with respect to iterating through the trajectory and changing the base values in the `position` attribute. 

### Actual behavior ###

The DCD reader creates a new **copy** of the current timestep which allows the coordinates in each frame to vary independently.

**Comment by orbeckst** [comment]
@IAlibay pointed out on discord that the current deprecation warning is not very helpful
```
DeprecationWarning: DCDReader currently makes independent timesteps by copying 
self.ts while other readers update self.ts inplace. This behaviour will be changed in 3.0 
to be the same as other readers 
```

I suggested to either link to a FAQ (to be written) or to this issue:
```
DeprecationWarning: DCDReader currently makes independent timesteps by copying 
self.ts while other readers update self.ts inplace. This behaviour will be changed in 3.0 
to be the same as other readers. Read more at 
https://github.com/MDAnalysis/mdanalysis/issues/3923 to learn if this change in 
behavior might affect you.
```

If we link to this issue from the DeprecationWarning then we need to be more clear about what changes for users, which code patterns are affected, and how to rewrite code.

**Comment by hmacdope** [comment]
Re-opening for @orbeckst and @IAlibay comments. 

We should:

- [ ] Add more info on #3889 itself. 
- [ ] link to the issue number in docstring 
- [ ] make the deprecation warning more comprehensive.

Some helpful chatGPT suggestions include 

```
This difference in behavior could lead to inconsistencies and confusion for users who are working with multiple reader classes, and it is being changed in the 3.0 release to make all readers behave the same way. In the 3.0 release, the DCDReader class will  update the self.ts attribute in place, just like the other readers.

```
