### ISSUE TITLE
Error: invalid literal for int() with base 10: 'ITEM: TIMESTEP'

### ISSUE THREAD

**Issue by jamesdalg** [MDAnalysis/mdanalysis#3926]
## Expected behavior ##
I would expect that MDAnalysis would import this  topology without generating an error. It seems to have trouble that there is a timestep in the file. Is there a way to tell the xyz importer to work with timestep data?

## Actual behavior ##

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/MDAnalysis/core/universe.py", line 110, in _topology_from_file_like
    topology = p.parse(**kwargs)
  File "/usr/local/lib/python3.10/dist-packages/MDAnalysis/topology/XYZParser.py", line 84, in parse
    natoms = int(inf.readline().strip())
ValueError: invalid literal for int() with base 10: 'ITEM: TIMESTEP'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/IPython/core/interactiveshell.py", line 3457, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-28-4445a68204c3>", line 1, in <module>
    u = mda.Universe("/code/lammps/alpha_globin/alphaglobin_mES_simulations/results_20prot/dump.46_DNA.xyz")
  File "/usr/local/lib/python3.10/dist-packages/MDAnalysis/core/universe.py", line 346, in __init__
    topology = _topology_from_file_like(self.filename,
  File "/usr/local/lib/python3.10/dist-packages/MDAnalysis/core/universe.py", line 125, in _topology_from_file_like
    raise ValueError(
ValueError: Failed to construct topology from file /code/lammps/alpha_globin/alphaglobin_mES_simulations/results_20prot/dump.46_DNA.xyz with parser <class 'MDAnalysis.topology.XYZParser.XYZParser'>.
Error: invalid literal for int() with base 10: 'ITEM: TIMESTEP'

## Code to reproduce the behavior ##

``` python
import MDAnalysis as mda
u = mda.Universe("dump.46_DNA.xyz")

....

```
File is included below:
[dump.44_DNA.zip](https://github.com/MDAnalysis/mdanalysis/files/10055665/dump.44_DNA.zip)

## Current version of MDAnalysis ##

- Which version are you using? (run `python -c "import MDAnalysis as mda; print(mda.__version__)"`)
- 2.3.0
- Which version of Python (`python -V`)?
- /usr/bin/python3.10
- Which operating system?
- Ubuntu 22.04

**Comment by hmacdope** [comment]
It looks to me like the actual contents of the file are a `LAMMPS` Dump file. Instead try 

```python
import MDAnalysis as mda
u = mda.Universe("dump.46_DNA.xyz", format='LAMMPSDUMP')
```

MDAnalysis is guessing based on the extension that it is an XYZ file but that doesn't seem to be the case.

**Comment by hmacdope** [comment]
@jamesdalg did this solve your issue?

**Comment by jamesdalg** [comment]
@hmacdope 

I ended up doing the following and it worked like a charm:
```
u = mda.Universe(lammps_result_file, atom_style="ATOMS id type xs ys zs ix iy iz", format="LAMMPSDUMP")
```
It may work without the atom_style line. I'll try it without. I hope so, because that would make it easy to combine multiple experiments with slightly different atom styles.

One last question: will calling Universe like this pick up multiple timestamps? I know this data only has one per file, but assuming that I have a file with multiple, will it still function?

**Comment by hmacdope** [comment]
@jamesdalg 

Yep this will pick up multiple timesteps!  The following pattern allows you to iterate through the timesteps.

```python
u = mda.Universe(...)
for ts in u.trajectory:
    print(ts)
```

Or you can run one of the boxed analyses on your universe directly. See the [analysis docs ](https://docs.mdanalysis.org/stable/documentation_pages/analysis_modules.html) for more info.

**Comment by jamesdalg** [comment]
Awesome! Thanks!!
