### ISSUE TITLE
Error with PQRParser for coordinate below -100 Å

### ISSUE THREAD

**Issue by AChatzigoulas** [MDAnalysis/mdanalysis#3932]
Hello MDAnalysis devs,

I found a bug in the PQRParser. When I try to parse a PQR file of a structure with an atom coordinate of -100 Å and below, I get the following error:

```
ValueError: Failed to construct topology from file bla.pqr with parser <class 'MDAnalysis.topology.PQRParser.PQRParser'>.
Error: not enough values to unpack (expected 10, got 9)
```

 An example of a line in the PQR file that produce this error is: 
```
ATOM   5346  O   ASN A 664     -34.085 -67.825-100.826  1.00 69.31           O 
```

I think the reason for this error is obvious. Centering the protein to (0, 0, 50) solves this probles. I would appreciate if you could make the  PQRParser more robust.

Thank you

**Comment by hmacdope** [comment]
Thanks for raising an issue. Would you be able to attach the file so that we can build a test around it? Cheers.

**Comment by orbeckst** [comment]
How did you produce your PQR file? 

We only really [parse files that are whitespace delimited](https://docs.mdanalysis.org/stable/documentation_pages/coordinates/PQR.html). 

> **Warning**
> Fields must be white-space separated or data are read incorrectly. PDB formatted files are not guaranteed to be white-space separated so extra care should be taken when quickly converting PDB files into PQR files using simple scripts.

The current PQR parser does not have a defect, it reads according to specifications.

If your file is produced by a commonly used tool then it may be worthwhile to *enhance* the PQR reader to deal with badly formatted PQR files.

**Comment by AChatzigoulas** [comment]
I use [pdb2pqr](https://github.com/Electrostatics/pdb2pqr) but I didn't know about the  ```--whitespace``` option. This solves the problem. Thank you very much.
