### ISSUE TITLE
MAINT: xdrlib is going away in Python 3.13

### ISSUE THREAD

**Issue by tylerjereddy** [MDAnalysis/mdanalysis#3934]
On latest `develop` in Python 3.11: `MDAnalysis/topology/TPRParser.py:160: DeprecationWarning: 'xdrlib' is deprecated and slated for removal in Python 3.13`

I can't quite tell if this will be dealt with naturally by gh-3929 or not, but doesn't seem to be an explicit objective there?

See also: https://peps.python.org/pep-0594/#xdrlib

**Comment by IAlibay** [comment]
@tylerjereddy we're replacing this with a vendored package of xdrlib (you can see this under the mda-xdrlib repo), I'm just finishing up an action for releases and tidying up some docs and we should be good to go.

**Comment by tylerjereddy** [comment]
ah, great, I only searched our open issues I guess

**Comment by tylerjereddy** [comment]
I wonder if `AttributeError: 'PosixPath' object has no attribute 'encode'` will go away as well--that seems to happen when initiating universes with `pathlib` components I think:

```
    self._xdr = self._file(self.filename)
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "MDAnalysis/lib/formats/libmdaxdr.pyx", line 177, in MDAnalysis.lib.formats.libmdaxdr._XDRFile.__cinit__
AttributeError: 'PosixPath' object has no attribute 'encode'

```

**Comment by tylerjereddy** [comment]
Ah, that's gh-2497, not sure if that will auto-close with the new effort, but it is already open anyway.

**Comment by jbarnoud** [comment]
I am looking at the TPR parser at the moment. What is the status of this issue? I see https://github.com/MDAnalysis/mda-xdrlib and https://pypi.org/project/mda-xdrlib/ but it does not seem to be used, is it?

**Comment by IAlibay** [comment]
@jbarnoud it just needs deploying using this fancy action I am making (generalising for mdakits has been a bit difficult) but more pressing issues got pushed ahead. We have two years and it's a direct import swap (quite literally), so I wouldn't worry about it too much for now.
