### ISSUE TITLE
update docs for calc_dihedral to indicate output range

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/mdanalysis#3936]
The docs for dihedral calculations do not state the range of angles that are returned.

Based on the use of [atan2()](https://linux.die.net/man/3/atan2) from the C standard lib in
https://github.com/MDAnalysis/mdanalysis/blob/497f45e23c834780f9ca172b3e4d4ad7602136bc/package/MDAnalysis/lib/include/calc_distances.h#L761 the answer should be [–π, π].

**Comment by Hakarishirenai** [comment]
Hey @orbeckst, I would like to take up this issue!

**Comment by orbeckst** [comment]
Thank you for contributing. Please simply submit a PR and link it to this issue. Someone will review your PR and provide feedback and help there. It’s ok if the PR is a work in progress. Our user guide has an introduction to how to get started contributing.

**Comment by Hakarishirenai** [comment]
In the Following 3 functions at "mdanalysis/package/MDAnalysis/lib/distances.py ", in doc string, return should mention the range [–π, π],right ?
- calc_dihedral
- calc_dihedral_ortho
- calc_dihedral_triclinic

**Comment by orbeckst** [comment]
I’m not 100% sure that these are all of them but fixing the docs for those would be already good. 

There are various dihedral-related methods in the topology system and in the analysis module (analysis.dihedrals), which use calc_dihedrals and return angles in degrees. One could look at their docs as a follow-up issue.

**Comment by Hakarishirenai** [comment]
I had a mistake in the above comment, calc_dihedrals is the only method's docstring that needs to be updated and all others where actually being called inside of it.
