### ISSUE TITLE
Add support for pickling of ResidueGroup and SegmentGroup

### ISSUE THREAD

**Issue by pgbarletta** [MDAnalysis/mdanalysis#3947]
## Is your feature request related to a problem? ##

Currently, `AtomGroup` can be pickled but `ResidueGroup` and `SegmentGroup` can't.

```
import pickle
import MDAnalysis as mda
from MDAnalysis.tests.datafiles import TPR, XTC

u = mda.Universe(TPR, XTC)

with open('atoms.pkl', 'wb') as f:        # this works
    pickle.dump(u.atoms, f)
with open('residues.pkl', 'wb') as f:        # this doesn't
    pickle.dump(u.residues, f)
with open('segments.pkl', 'wb') as f:        # neither does this
    pickle.dump(u.segments, f)
```

## Describe the solution you'd like ##

Add a general pickling support to `BaseGroup`.

## Describe alternatives you've considered ##

Add pickling support to `ResidueGroup` and `SegmentGroup` separately as `AtomGroup` has, [here](https://github.com/MDAnalysis/mdanalysis/blob/develop/package/MDAnalysis/core/groups.py#L118), and [here](https://github.com/MDAnalysis/mdanalysis/blob/develop/package/MDAnalysis/core/groups.py#L2528).

**Comment by orbeckst** [comment]
This issue was closed with PR #3953 .
