### ISSUE TITLE
[deprecation] Bio.pairwise2 is deprecated in favor of Bio.Align.PairwiseAligner

### ISSUE THREAD

**Issue by IAlibay** [MDAnalysis/mdanalysis#3950]
We're currently getting warnings about the above, we should amend align.py as necessary.

EDIT: Based on discussion on PR https://github.com/MDAnalysis/mdanalysis/pull/3951 we'll deprecate and remove in 3.0.

**Comment by IAlibay** [comment]
I'm adding this to the 2.4.0 milestone since we're getting these warnings everywhere.

**Comment by orbeckst** [comment]
I created https://github.com/MDAnalysis/UserGuide/issues/244 to document the functionality without the need for `sequence_alignment()`.
