### ISSUE TITLE
PrimitivePDBReader is not permissive

### ISSUE THREAD

**Issue by kain88-de** [MDAnalysis/mdanalysis#396]
I write my own PDB-files in a C++ tool which don't contain all the information I could put into a PDB. I skip everything after the coordinates. See this [gist](https://gist.github.com/kain88-de/be072c0ca87bf3b208f4) for an example.
This is still a valid PDB file, in the sense that it is parsed by most mayor tools (VMD, PyMOL).

The default PrimitivePDBReader can't read this file since version 0.10.0.. The previous version still worked. The BioPython parser can handle this even though it issues some warnings.

The bigger problem is that I now have to load the files with `permissive=False`. 

As a solution either the PrimitivePDBReader has to be fixed to allow for missing values when parsing atoms are set the BioPython parser as the default permissive parser.

I guess a test with my PDB file should also be added.

**Comment by richardjgowers** [comment]
Hey

Yeah I tinkered with the PDB reader in 0.10.  If you can add a basic failing example as a test then we can rejig the reader to handle this properly.  The Reader is all Python code, so it should be a pretty easy fix

**Comment by kain88-de** [comment]
I was wondering where such a test-case would be added ideally. I haven't found the tests yet that create universes from all the different file-formats supported and check if the coordinates are ok.

**Comment by richardjgowers** [comment]
Test_coordinates if I remember right. The Reader object can work on it's
own too and fill its .ts attribute (a Timestep object) with coords.

**Comment by kain88-de** [comment]
So i played a bit with VMD and Bio Python. As it turns out you can leave out quite a huge amount
of stuff there. 

VMD needs field: ATOM, x, y, z
BioPython needs: ATOM, icode, x, y, z

So now it depends how much of this flexibility should be supported in the Primitive Reader.
What field would MDA need to still be useful (My guess is that xyz is enough)

My PDB reference
http://www.wwpdb.org/documentation/file-format-content/format33/sect9.html#ATOM

**Comment by richardjgowers** [comment]
I think the Reader just needs to read all information it is given.  If it's only given atom, x, y, z then it should manage with that.  I think the sparsest format we have so far is XYZ which just has atomname and x, y, z.  But I think mda should be able to load up without atom names...

There's also #212 open which is looking at performance.  Currently PDB is pretty slow, maybe a Cython pass would make it faster?

**Comment by orbeckst** [comment]
If we label it primitive or permissive "PDB" reader then I have no problem with it being very nonchalant about what it takes from such a butchered "PDB" file. I suppose, the only remaining scraps of the PDB specs are the columns in which certain quantities reside?

Btw, I am very much in favor of a cython (or similar) rewrite of our PDB reading/parsing. If we can get rid of the Biopython PDB reader then I would not be sad, either...

**Comment by kain88-de** [comment]
This is still a problem for reading PDB-trajectories. See [PDB.py](https://github.com/MDAnalysis/mdanalysis/blob/develop/package/MDAnalysis/coordinates/PDB.py#L623). I'll have time in the evening to make a fix and unit-test

**Comment by richardjgowers** [comment]
Yeah I missed that, the PDB Reader is pretty ugly.  Ideally there should be a single lump of code that reads a frame, not two versions (one in `__init__`, another in `_read_next_timestep`).  If you felt like refactoring so that coordinate reading only happens in `_read_next_timestep`, that might be better.  

Then again, the current `__init__` reads the entire file, which is fugly, it should be able to work lazily, but I'm not 100% certain of what PDB format is, so maybe it's more complicated than I thought.  So maybe a quick fix is best for now.........

**Comment by kain88-de** [comment]
Oh PDB sucks. I have a simulation where I would like to specify more then 26 Domains, which is impossible in a single PDB model since chains are only classified with a single letter.

Although I would be fairly ok now to get a more lazy PDB reader. If people have a general use case where different models are defined in a PDB they can switch to the BioPython reader.

**Comment by orbeckst** [comment]
Just as an FYI, there's also the XPDB ("extended PDB") reader in MDAnalysis, which reads 5-digit resids. We could make XPDB our super-lazy reader.

Docs on our XPDB are a bit sparse: http://pythonhosted.org/MDAnalysis/documentation_pages/topology/ExtendedPDBParser.html

On 9 Sep, 2015, at 08:21, kain88-de wrote:

> Oh PDB sucks. I have a simulation where I would like to specify more then 26 Domains, which is impossible in a single PDB model since chains are only classified with a single letter.
> 
> Although I would be fairly ok now to get a more lazy PDB reader. If people have a general use case where different models are defined in a PDB they can switch to the BioPython reader.
> 

--
Oliver Beckstein * orbeckst@gmx.net
skype: orbeckst  * orbeckst@gmail.com

**Comment by kain88-de** [comment]
@richardjgowers 

I think there isn't much we can to besides going through every line. We just have to count the number of frames. But I guess there might be a smarter way to count the number of 'MODEL' strings

**Comment by richardjgowers** [comment]
I'm not an expert on PDB, but it is possible to make the Reader yield frames until it reaches the end of the file.  The Reader doesn't have to know the number of frames to iterate.  The current counting of frames and remembering line numbers is more defensive than it needs to be.

**Comment by kain88-de** [comment]
But the universe object needs to know the number of frames. So we need to go through the whole file anyway.

**Comment by richardjgowers** [comment]
It's doesn't *need* to know, it's calculated lazily.  You can probably do a lot of stuff without bumping into n_frames :)
