### ISSUE TITLE
Modernize testsuite setup.py

### ISSUE THREAD

**Issue by IAlibay** [MDAnalysis/mdanalysis#3967]
There's a few QOL we can clean up in the testsuite setup.py.

For one we should probably merge what's in the package_data incldue with MANIFEST.

**Comment by orbeckst** [comment]
Is this issue suitable as a GSOC starter issue??

**Comment by IAlibay** [comment]
> Is this issue suitable as a GSOC starter issue??

No I would prefer that anything that might affect deployment doesn't get tangled with GSoC. In any case this QoL stuff really isn't starter friendly or enough for a full on project.

**Comment by IAlibay** [comment]
Fixed with #4463
