### ISSUE TITLE
inconsistent unit in time attribute of trajectory reader

### ISSUE THREAD

**Issue by khuston** [MDAnalysis/mdanalysis#397]
I was having a problem with the time units from LAMMPS DCD files, and after reading a past issue on this and reading the trajectory reader docs, I wrote this loop:

    for timeunit in ['AKMA','fs']:
        for format in ['DCD','LAMMPS']:
            u = MDA.Universe('structure.dat','2.3.Trajectory.dcd',topology_format='DATA',format=format,units=units,timeunit=timeunit)
            print 'timeunit: %s, format: %s'%(timeunit,format)
            print '  delta: %d'%u.trajectory.delta
            print '  skip_timestep: %d'%u.trajectory.skip_timestep
            print '  dt: %d'%u.trajectory.dt
            print '  totaltime: %d'%u.trajectory.totaltime
            print '  time[1] :%d'%u.trajectory.next().time

This produces the following output, which was expected except for the very last value, which is the time of the second frame for format='LAMMPS' and timeunit='fs'.  The dt and totaltime are correctly calculated, but time[1] is not calculated in the same units as dt and totaltime:

    timeunit: AKMA, format: DCD
      delta: 1
      skip_timestep: 10000
      dt: 488
      totaltime: 489370
      time[1] :488
    timeunit: AKMA, format: LAMMPS
      delta: 1
      skip_timestep: 10000
      dt: 488
      totaltime: 489370
      time[1] :488
    timeunit: fs, format: DCD
      delta: 1
      skip_timestep: 10000
      dt: 488
      totaltime: 489370
      time[1] :488
    timeunit: fs, format: LAMMPS
      delta: 1
      skip_timestep: 10000
      dt: 10
      totaltime: 10010
      time[1] :488

This doesn't seem like the desired behavior. Any ideas how this might be fixed?

**Comment by richardjgowers** [comment]
Hey

Thanks for the report, yeah looks like something isn't working.  As a start, can you make a PR with some failing tests (that loop but as a test) and mark them with the expected failure decorator and we can work from there?

**Comment by khuston** [comment]
I tried a simple test in _TestTimestepInterface:

    def test_dt(self):
        assert(self.u.trajectory.dt,self.ts.dt)

Funnily enough, I didn't get an error for LAMMPS (because it's reading from a .data file), but I did get errors for TRR, XTC, and TRZ. I'm not sure if this is testing the same problem, but it seems so. I'll add a case for LAMMPS+DCD and then submit the pull request.

**Comment by orbeckst** [comment]
Many thanks —that looks weird and worrisome. Do you have a short, small LAMMPS DCD to share? I don't think that there's one in the tests cases.

For the included CHARMM DCD, it seems to be fine:
```python
import numpy as np
import MDAnalysis; from MDAnalysis.tests.datafiles import PSF, DCD
u = MDAnalysis.Universe(PSF, DCD)
print(np.all([ts.time == u.trajectory.time for ts in u.trajectory]))
```
gives `True`. (And indeed the times are 0, 1, ... 97 [ps].)

You can also check (for DCD): `header = u.trajectory._dcd_header()`. For the CHARMM DCD, `header['delta'] == 0.020454827696084976`, which is the correct integrator timestep of 1fs in AKMA.

The included NAMD DCD (`w = MDAnalysis.Universe(PSF_NAMD_TRICLINIC, DCD_NAMD_TRICLINIC)`) only has one frame and the header gives `delta = 1` (i.e. 1 ps because NAMD decides to record time between saved frames in ps).

**Comment by richardjgowers** [comment]
@khuston Thanks for the tests.  Did you want to have a crack at this? If so I have a quick look and try and tell you where to start looking

**Comment by khuston** [comment]
Sure, I'll have a go at it, and I'd appreciate any hints.

**Comment by richardjgowers** [comment]
So with the TRZ format, what is happening is that the Timestep doesn't have access to the Reader.  To calculate `dt` for TRZ format you need to look at the `time` one step, and then next and do the difference.  If the Timestep doesn't have access to the Reader, then it can't do this calculation, or even ask for it to be done.  

So the logic for the `Timestep.dt` property needs to be
 - do I have `dt` info already (Timesteps can be given this via a kwarg on init, or might have the info for whatever reason), if so, just return this
 - if not, do I have a pointer to a Reader, and can the Reader tell me (this step is new!)
 - otherwise guess 1.0

The big change here is that a `Timestep` will have to have access to the `Reader`.  This needs to be added as some sort of optional property.  Ideally also, this will be added into `base.Timestep` rather than into each specific format.

**Comment by orbeckst** [comment]
@khuston , I assigned this issue to you. @richardjgowers might have to help with the TRZ, which is his baby.

**Comment by khuston** [comment]
I submitted pull request #402 that resolves the ```test_dt``` errors.

I tried for a while to add the scheme you describe @richardjgowers where if timestep.data['dt'] is undefined, then the timestep will ask the reader for dt. I implemented this by:

- Upon instantiation of timestep, run through the frames in inspect.stack() until an instance is found that is a subclass of Reader, and store that reader instance in self.reader
- When timestep is asked for dt, if self.data['dt'] is undefined, then try self.reader.dt. Otherwise, just return 1.0.

In this way, the timestep can get a pointer to the reader without any changes to the reader itself.

But only the XTC, TRR, and TRZ readers calculate dt themselves. The base reader obtains dt from the timestep after init, so in general the timestep couldn't ask its reader for dt. I also saw failures during timestep copying when I tried this -- specifically the _unitcell copy was failing. I couldn't figure out how assigning ```timestep.reader``` was causing failures in the timestep copy comparison for other attributes. Anyway, I cut my losses and settled for the easiest fixes.

**Comment by richardjgowers** [comment]
Yeah, this fix is cleaner in lots of ways, the only problem is that `self.ts.dt = self.dt` forces 2 frames to be loaded.  I'll have a think if there's a neat way to fix TRZ XTC and TRR

**Comment by khuston** [comment]
I thought the reader rewinds after dt is called, and dt is cached, so the reader only computes dt once anyway. Or do I misunderstand?

**Comment by richardjgowers** [comment]
Yeah it doesn't break anything, it just means that initialising the Reader loads 3 frames (first frame, second to look at t2 - t1, then first frame again), rather than just one.

**Comment by khuston** [comment]
Ah, I get it.

**Comment by richardjgowers** [comment]
I think TRZ XTC and TRR overriding `dt` is the real problem.

If we renamed the Reader's finding of dt to something like `_get_dt`, and added having a Reader linked to a Timestep as an option.. then the `dt` property could look like:

``` python
class TRZReader
    # somewhere in init:
    self.ts = Timestep(........)
    self.ts._reader = self


class Timestep:
    @property
    def dt(self):
        try:
            return self.data['dt']
        except KeyError:
            pass
        try:
            dt = self.data['ts'] = self._reader._get_dt()
            return dt
        except AttributeError:
            pass
         # raise warning etc about default dt of 1.0
         return 1.0

```

So what we've added is an additional attempt at finding dt by seeing if we have an attached Reader that knows how to `_get_dt`.  Have I missed anything obvious?

**Comment by khuston** [comment]
Nothing that's obvious to me, but maybe something subtle. I tried this out:
https://github.com/khuston/mdanalysis/compare/Issue397...khuston:Issue397_get_dt
and I get failures in 1) equality between timesteps, 2) test_TS_indices, and 3) test_TS_slice for XTC and TRR. These failures are in the same places as earlier when the timestep tried getting the reader by inspecting the stack.

**Comment by richardjgowers** [comment]
That's a strange one, it's failing on `_pos` too... which is apparently unrelated.  I'm taking a look at it

**Comment by richardjgowers** [comment]
Ok I think I've got it @khuston .  The failing test was very weird because I was unable to recreate them in ipython.  I ended up rewriting the tests (they were kinda ugly) and they now all pass.  Thanks for the fix!
