### ISSUE TITLE
pytng reader tests generate a lot of warnings

### ISSUE THREAD

**Issue by IAlibay** [MDAnalysis/mdanalysis#3986]
## Is your feature request related to a problem? ##

Running tests generates 611 warnings, by comparison PDB coordinate tests (which is generally the worst for the coordinate readers) only generates 268.

A lot of these warnings are repeated stride block issues and therefore could easily be filtered out.

## Describe the solution you'd like ##
Add some warnings filters to the TNG tests.

## Additional context ##
Issue #2980

**Comment by AnonymousCodes911** [comment]
I would like to work on this issue, please assign and  guide me through.

**Comment by hmacdope** [comment]
Hi @AnonymousCodes911 you are free to work on the issue. Have a read of our [contributing guide](https://userguide.mdanalysis.org/stable/contributing.html) to get started. Feel free to ping me with questions.

**Comment by MohitKumar020291** [comment]
Hello @hmacdope I want to make some changes to contributing guide , I cannot find it in code base. Where can I find them or it is not available in code base.

**Comment by IAlibay** [comment]
@MohitKumar020291 if you mean this contributing guide https://userguide.mdanalysis.org/stable/contributing.html then the correct place for this is here: https://github.com/MDAnalysis/UserGuide

For any further non-issue questions such as these please do contact us either on the mailing list or discord (see: https://www.mdanalysis.org/#participating).

**Comment by MohitKumar020291** [comment]
@IAlibay I did checkout #2930 but not found any clue. I am absolute new to this .Can you please give some similar issues?

**Comment by ooprathamm** [comment]
@IAlibay ran test_tng file in testsuite , it only gave 2 warnings

**Comment by ooprathamm** [comment]
@IAlibay tng_tests only giving 2 warnings(skipped 89)

**Comment by IAlibay** [comment]
> @IAlibay tng_tests only giving 2 warnings(skipped 89)
> 

@ooprathamm did you install the optional dependency pytng?

**Comment by ooprathamm** [comment]
@IAlibay made a pull request for the same #4010 
(Somehow pull request didn't get linked)
