### ISSUE TITLE
incorrect subheadings in docs overview pages

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/mdanalysis#3998]
## Expected behavior ##

Docs for classes and functions do not show up in table of content lists at the module level at 
* https://docs.mdanalysis.org/stable/documentation_pages/coordinates_modules.html
* https://docs.mdanalysis.org/stable/documentation_pages/topology_modules.html
* https://docs.mdanalysis.org/stable/documentation_pages/lib_modules.html
* https://docs.mdanalysis.org/stable/documentation_pages/analysis_modules.html

## Actual behavior ##
For a number of  modules, the classes appear in the list, e.g.,

* [6.2. CRD structure files in MDAnalysis — MDAnalysis.coordinates.CRD](https://docs.mdanalysis.org/stable/documentation_pages/coordinates/CRD.html)
* [CRDReader](https://docs.mdanalysis.org/stable/documentation_pages/coordinates/CRD.html#MDAnalysis.coordinates.CRD.CRDReader)
* [CRDWriter](https://docs.mdanalysis.org/stable/documentation_pages/coordinates/CRD.html#MDAnalysis.coordinates.CRD.CRDWriter)

See more in the screen shots below and on the pages listed under **Expected behavior** 

![image](https://user-images.githubusercontent.com/237980/213304053-30ffa0fb-cecb-4443-b0d1-d51d39456e43.png)
![image](https://user-images.githubusercontent.com/237980/213304993-801abdc9-8f0d-4855-90a7-a81b67e403b4.png)

Other pages where the same thing happens are listed above under *Expected behavior*.

Also note https://github.com/MDAnalysis/mdanalysis/pull/4011#pullrequestreview-1294850027 — the [2.3.0 docs](https://docs.mdanalysis.org/2.3.0/documentation_pages/coordinates_modules.html) still look correct, starting with the [2.4.0 docs](https://docs.mdanalysis.org/2.4.0/documentation_pages/coordinates_modules.html) the layout problems start. **We need to understand why the sphinx output changed.**

## Current version of MDAnalysis ##

- Which version are you using? (run `python -c "import MDAnalysis as mda; print(mda.__version__)"`) docs 2.4.1 (stable)

**Comment by MohitKumar020291** [comment]
@orbeckst I want to work on it , may I know what changes do you want see?

**Comment by orbeckst** [comment]
Hello @MohitKumar020291 , only the actual section headings should appear in the generated listings. Have a look at the corresponding restructured text (reST, rst) files — perhaps there's something wrong with how the Sphinx [.. toctree::](https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#directive-toctree) directive is used or there's something wrong with the levels of headings.

You might need to read up on [working with the MDAnalysis documentation](https://userguide.mdanalysis.org/stable/contributing_code.html#working-with-the-code-documentation), using [sphinx](https://www.sphinx-doc.org/en/master/usage/index.html)  and [restructured text](https://www.sphinx-doc.org/en/master/usage/restructuredtext/). 

I recommend you first learn how to *build the documentation locally* so that you can make changes and immediately see what changed (instead of having to wait for the CI).

**Comment by ooprathamm** [comment]
@orbeckst Unable to build documentation locally . 
python setup.py build_sphinx -E  - throws import error 
python setup.py build_ext --inplace - doesn't populate doc/html

**Comment by hmacdope** [comment]
Try going to the `package/doc/sphinx/` folder and doing `make html`

**Comment by ooprathamm** [comment]
![Screenshot 2023-01-26 083448](https://user-images.githubusercontent.com/89736193/214749768-91478427-251e-44c2-8c4d-93e98163ae57.jpg)

@hmacdope python setup.py build_ext --inplace and make html both throw same error. there seems to be an issue with sphinx v 5.3

**Comment by hmacdope** [comment]
> ![Screenshot 2023-01-26 083448](https://user-images.githubusercontent.com/89736193/214749768-91478427-251e-44c2-8c4d-93e98163ae57.jpg)
> 
> 
> 
> @hmacdope python setup.py build_ext --inplace and make html both throw same error. there seems to be an issue with sphinx v 5.3 
> 
> 
> 
> 

You will need to install pybibtex

**Comment by ooprathamm** [comment]
@orbeckst @hmacdope tried fixing this doc issue in my pr (#4011)

**Comment by chandra20500** [comment]
Hi @orbeckst I want to work on this issue could you please assign this to me.

**Comment by orbeckst** [comment]
@chandra20500  if no-body else is working on an issue as evidenced by a linked PR, just go ahead an submit a PR. See also our GSOC FAQ https://github.com/MDAnalysis/mdanalysis/wiki/GSoC-FAQ#can-i-claim-an-issue-to-work-on 

We do not reserve or assign issues. We just evaluate work presented.

**Comment by IAlibay** [comment]
To add here @chandra20500 - it not appropriate to spam the same message to 7 different issues at the same time. Please concentrate on one issue you want to work on.

**Comment by ooprathamm** [comment]
@orbeckst as this issue is not gsoc starter issue anymore, can i reopen my pr

**Comment by hmacdope** [comment]
> @orbeckst as this issue is not gsoc starter issue anymore, can i reopen my pr

I would say yes!

**Comment by orbeckst** [comment]
yes

**Comment by ooprathamm** [comment]
@orbeckst as I don't have write access, I request you to please reopen #4011
