### ISSUE TITLE
LAMMPS bond/angle/dihedral types are wrongly deleted

### ISSUE THREAD

**Issue by jaclark5** [MDAnalysis/mdanalysis#4001]
## Expected behavior ##

Correct number of bond/angle/dihedral types are written to lammps data file.

## Actual behavior ##

Method, core.topologyobjects._removeDupes(), wrongly removes bond/angle/dihedral types. This function is written for cases where the bond/angle/dihedral types are defined as a tuple of atom types, so that if both bond (1,2) and (2,1) are present, the two will be merged. However, in lammps the types are defined as integers in string format, so if there are more than 20 types, then bond 12 and 21 will be merged.

**Comment by hmacdope** [comment]
I think this might be related to #3818. Let me dig
