### ISSUE TITLE
switch CI to build HOLE from osmart/hole2 or use conda-forge package

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/mdanalysis#4012]
We are in the process of retiring the MDA hole2 fork in favor of continuing maintenance on the original https://github.com/osmart/hole2 (see discussion on https://github.com/MDAnalysis/hole2/issues/2 ).

Once PR https://github.com/osmart/hole2/pull/2 is merged and the build system is updated, we can switch over our CI to building HOLE from there.

Alternatively, wait for our conda-forge HOLE package https://github.com/osmart/hole2/issues/6 and directly use that.

**Comment by orbeckst** [comment]
There are now [cf packages for hole2 on Linux and macOS](https://anaconda.org/conda-forge/hole2) so we should switch our CI to using those.

**Comment by orbeckst** [comment]
@IAlibay do you want to delegate this task?

**Comment by IAlibay** [comment]
fixed in #4131 I think
