### ISSUE TITLE
MDAnalysis.analysis.rms.rmsd docs do not show versionchanged entries

### ISSUE THREAD

**Issue by IAlibay** [MDAnalysis/mdanalysis#4014]
## Expected behavior ##

Docstring shows any versionchanged entries that have been added to the docstring.

## Actual behavior ##

Despite having `versionchanged` entries, the docs for https://docs.mdanalysis.org/dev/documentation_pages/analysis/rms.html#MDAnalysis.analysis.rms.rmsd don't seem to be showing them.

It's possibly down to the number of empty lines there should be between the doctest block and the versionchange entries, but it will need further investigation.

## Current version of MDAnalysis ##

Happening in the current dev branch of MDAnalysis.

**Comment by 1e9abhi1e10** [comment]
you are saying to add these things ?
```
versionadded:: 0.7.7
versionchanged:: 0.11.0
Added :class:`RMSF` analysis.
versionchanged:: 0.16.0
Refactored RMSD to fit AnalysisBase API
```

**Comment by IAlibay** [comment]
> you are saying to add these things ?
> ```
> versionadded:: 0.7.7
> versionchanged:: 0.11.0
> Added :class:`RMSF` analysis.
> versionchanged:: 0.16.0
> Refactored RMSD to fit AnalysisBase API
> ```
> 

They are currently present in the docstring, we just need to amend things so that they get rendered by sphinx.

**Comment by MeetB7** [comment]
Hey, I am just a beginner and this will be my first issue. Can you  @IAlibay assign me this issue and help me understand what do I have to do and how?

**Comment by IAlibay** [comment]
@MeetB7 - we unfortunately don't assign issues to folks unless they are part of a wider set of project items. In this case whomever first opens a pull request with the necessary changes would get their code ammendments reviewed.

> help me understand what do I have to do and how?

It's a bit difficult for me to capture what additional information you might need here. Could I maybe turn this around and ask what of the above given information are you unsure about / needs clarification?

I would also urge you to have a look at the contributing portion of the userguide if you haven't done so yet: https://userguide.mdanalysis.org/stable/contributing_code.html

**Comment by MeetB7** [comment]
@IAlibay if they already exist in docstring, what do you mean by 'amend things' so they get rendered 
Ps: And I'm like new new to open source and it feels overwhelming. That might've been my first comment ever. 
Thank you!

**Comment by IAlibay** [comment]
> if they already exist in docstring, what do you mean by 'amend things' so they get rendered

So here what we mean is that in the ideal world sphinx should have picked up that these versionchanged entries are present and should be showing them in the rendered docs (see https://docs.mdanalysis.org/dev/documentation_pages/analysis/rms.html#MDAnalysis.analysis.rms.rmsd). However it doesn't, which mean that we need to fix the docstring in such a way that sphinx can pick them up and render them. Usually this is a small change in the amount of empty lines, but the correct answer will require delving into the sphinx documentation and doing some trial and error locally to see what changes are necessary for it to work.

**Comment by chandra20500** [comment]
HI, I Want to work on this issue please assign this to me

**Comment by MeetB7** [comment]
hey @IAlibay can you review my pr #4022 please
Thank you!
