### ISSUE TITLE
Documentation of Hydrogen Bond Analysis, missing ")"

### ISSUE THREAD

**Issue by MoSchaeffler** [MDAnalysis/mdanalysis#4026]
## Expected behavior ##

Code template to calculate the hydrogen bonds between different groups should work by copy and paste.

In the documentation (https://docs.mdanalysis.org/stable/documentation_pages/analysis/hydrogenbonds.html#module-MDAnalysis.analysis.hydrogenbonds.hbond_analysis) there are ")" missing in lines:

hbonds.hydrogens_sel = f"({protein_hydrogens_sel}) or ({water_hydrogens_sel}"
hbonds.acceptors_sel = f"({protein_acceptors_sel}) or ({water_acceptors_sel}"

It should be:

hbonds.hydrogens_sel = f"({protein_hydrogens_sel}) or ({water_hydrogens_sel})"
hbonds.acceptors_sel = f"({protein_acceptors_sel}) or ({water_acceptors_sel})"

## Actual behavior ##

Error massage:
" SelectionError: Unexpected token: 'None' Expected: ')' "

## Code to reproduce the behavior ##

run:
'''
import MDAnalysis
from MDAnalysis.analysis.hydrogenbonds.hbond_analysis import (
  HydrogenBondAnalysis as HBA)

u = MDAnalysis.Universe(psf, trajectory)

hbonds = HBA(
  universe=u,
  between=['resname TIP3', 'protein']
  )

protein_hydrogens_sel = hbonds.guess_hydrogens("protein")
protein_acceptors_sel = hbonds.guess_acceptors("protein")

water_hydrogens_sel = "resname TIP3 and name H1 H2"
water_acceptors_sel = "resname TIP3 and name OH2"

hbonds.hydrogens_sel = f"({protein_hydrogens_sel}) or ({water_hydrogens_sel}"
hbonds.acceptors_sel = f"({protein_acceptors_sel}) or ({water_acceptors_sel}"

hbonds.run()
'''

## Current version of MDAnalysis ##

Error does not depend on version, only  a small mistake in the documentation

**Comment by orbeckst** [comment]
Thank you for the report @MoSchaeffler . Do you want to fix it yourself?

If so please see our [Contribution Guide](https://userguide.mdanalysis.org/stable/contributing.html). In this case, you might be able to directly edit https://github.com/MDAnalysis/mdanalysis/blob/develop/package/MDAnalysis/analysis/hydrogenbonds/hbond_analysis.py on GitHub ("Edit file" icon) and create a Pull Request (PR) this way.
