### ISSUE TITLE
TPRParser does not support TPX version 129 from Gromacs 2023

### ISSUE THREAD

**Issue by bosonie** [MDAnalysis/mdanalysis#4047]
Gromacs2023 is out and, similarly to what happened with previous releases,  `TPRParser` complains about the TPX version.
The actual error is:
```
NotImplementedError: Your tpx version is 129, which this parser does not support, yet
```
What is the course of actions in this cases? Just to have a timeline for when we will be able to use Gromacs2023 and MDAnalysis.

Thanks!

**Comment by orbeckst** [comment]
Someone will need to reverse-engineer the new TPX file format version and implement it in our TPR reader.

@jbarnoud are you able to look at this?

**Comment by jbarnoud** [comment]
This version was surprisingly easy to deal with. I just submitted a pull request.

**Comment by orbeckst** [comment]
@bosonie if you want the feature, you have to either wait for release 2.5.0 or [install the development version](https://userguide.mdanalysis.org/stable/installation.html#development-versions).
