### ISSUE TITLE
Check that cythonisation of XDR reader didn't introduce C `int` overflow bug similar to that in #4039

### ISSUE THREAD

**Issue by hmacdope** [MDAnalysis/mdanalysis#4053]
Cythonisation of the DCD reader in #3888  resulted in an int overflow bug as detailed in #4039  and fixed in #4084.

Given I did something similar for the XDR reader in #3892, we should check that no similar bugs were introduced.

**Comment by IAlibay** [comment]
I've tested this in two ways:

1. Create a ~ 16 GB XTC trajectory of 100000 frames as per https://github.com/MDAnalysis/mdanalysis/issues/4039 using the `TPR` system.
2. Create a small 10000000 frames (~ 1.2 GB) XTC trajectory for a subset of the `TPR` system.

And then trying to load both to memory. In both cases I didn't encounter any issues.

**Comment by hmacdope** [comment]
@ianmkenney to test quickly on a large XTC privately and then good to go

**Comment by ianmkenney** [comment]
I iterated over a `TRR` file:
```
04:18 PM >>> du -sh production.trr 
292G    production.trr
```

and I didn't get a segfault

```
In [3]: u = mda.Universe("top.dms", "production.trr")

In [4]: from tqdm import tqdm

In [5]: for ts in tqdm(u.trajectory):
   ...:     pass
   ...: 
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 191666/191666 [45:15<00:00, 70.58it/s]

In [6]: mda.__version__
Out[6]: '2.5.0-dev0'

In [7]: u.atoms
Out[7]: <AtomGroup with 136294 atoms>
```

Hope that helps!

**Comment by hmacdope** [comment]
With that I think we can close. Thanks @ianmkenney!
