### ISSUE TITLE
include charge information in psf file reader 

### ISSUE THREAD

**Issue by NeilJ-Thomson** [MDAnalysis/mdanalysis#4086]
Greetings from the PENSA team!
We are creating some functionality which wraps around the HydrogenBondAnalysis module. 
To improve the generality of the function, it would be very useful to read in the .psf charge topology, as is done with the .tpr file charge topology. 
Including the .psf charges in the creation of the universe would be really useful.
Many thanks

**Comment by yuxuanzhuang** [comment]
Hi! Welcome to MDAnalysis. I think MDAnalysis can read charges from psf files:

```python
import MDAnalysis as mda
from MDAnalysisTests.datafiles import PSF, DCD

u = mda.Universe(PSF, DCD)
print(u.atoms.charges)
> [-0.30000001  0.33000001  0.33000001 ...
 -0.67000002]
```
If it somehow doesn't work for your psf file. Could you please provide one corresponding file for diagnosis?

**Comment by NeilJ-Thomson** [comment]
Apologies, I cannot reproduce the error. This is working for me. Thank you
