### ISSUE TITLE
HydrogenBondAnalysis 'between' keyword returns incorrect donor-acceptor distances

### ISSUE THREAD

**Issue by p-j-smith** [MDAnalysis/mdanalysis#4091]
Hi, I saw a [question](https://groups.google.com/g/mdnalysis-discussion/c/NNBDSUXz_MU) on the discussion forum about using the `between` keyword of `HydrogenBondAnalysis`.

After looking into it I've found an issue whereby using the `between` keyword leads to the incorrect donor-atom distances being returned. This is because when the hydrogen bonds are filtered to remove those formed by atoms not in the `between` selection, [the donors, hydrogens, and acceptors are filtered](https://github.com/MDAnalysis/mdanalysis/blob/develop/package/MDAnalysis/analysis/hydrogenbonds/hbond_analysis.py#L685) but not the distances.

The donor-hydrogen-acceptor angles are not affected because these are calculated _after_ the filtering has been done.

## Code to reproduce the behavior ##

``` python
import numpy as np

import MDAnalysis as mda
from MDAnalysis.analysis.hydrogenbonds.hbond_analysis import HydrogenBondAnalysis
import MDAnalysisData

np.set_printoptions(suppress=True, precision=3)

data = MDAnalysisData.ifabp_water.fetch_ifabp_water()
u = mda.Universe(data.topology, data.trajectory)

hbonds = HydrogenBondAnalysis(
    universe=u,
    hydrogens_sel='index 1',
    acceptors_sel='index 2188',
    d_a_cutoff=3.30,
    d_h_a_angle_cutoff=150,
)
hbonds.run(stop=1)
print(f"{hbonds.results.hbonds=}")

hbonds_between = HydrogenBondAnalysis(
    universe=u,
    hydrogens_sel='resname TIP3 or protein',
    acceptors_sel='resname TIP3 or protein',
    d_a_cutoff=3.30,
    d_h_a_angle_cutoff=150,
    between=["index 0", "index 2188"],  # between uses donor atoms, not hydrogens
)
hbonds_between.run(stop=1)
print(f"{hbonds_between.results.hbonds=}")
```
Output:
```
hbonds.results.hbonds=array([[   0.   ,    0.   ,    1.   , 2188.   ,    2.741,  165.581]])
hbonds_between.results.hbonds=array([[   0.   ,    0.   ,    1.   , 2188.   ,    2.981,  165.581]])
```
The timestep, donor, hydrogen, and acceptor atoms, and the angle are all correct.
However, the donor-atom distance (5th column) is wrong.

I'll try to find some time in the next couple of days to submit a fix.

## Current version of MDAnalysis ##

- Which version are you using? (run `python -c "import MDAnalysis as mda; print(mda.__version__)"`)
2.5.0-dev0
- Which version of Python (`python -V`)?
Python 3.10.8
- Which operating system?
macOS 12.6.3

**Comment by orbeckst** [comment]
Thank you for looking into the email report _and_ verifying it _and_ raising the issue, @p-j-smith !

**Comment by p-j-smith** [comment]
> Thank you for looking into the email report and verifying it and raising the issue, @p-j-smith !

No worries! It's been a while since I've had time to keep up with what's going on with MDAnalysis, but it's nice to come back to it 😄
