### ISSUE TITLE
analysis.density isn't unit-tested and the docs example doesn't work

### ISSUE THREAD

**Issue by kain88-de** [MDAnalysis/mdanalysis#410]
I noticed this when I removed the KDTree module, without a comment from @orbeckst I would have missed this module. Unfortunately the example in the doc string is also not working, because the atomselection will give an empty selection. It will work with another selection.

Does anyone have an idea if there is already some good data in the testfiles for a unit-test?

**Comment by orbeckst** [comment]
There's no good unit test. We could mock up something with one of the trajectories in the test files that contain water. Basically, see if you can get the example running, record some summary statistics, and use these as a baseline for a test.

I added some data to [MDAnalysis/gridDataFormats Issue #3](/MDAnalysis/GridDataFormats/issues/5#issuecomment-137849400) but that's not really suitable for unit tests.

**Comment by orbeckst** [comment]
This issue is being addressed as part of #544 .

**Comment by orbeckst** [comment]
Closed with PR #563 and issued #544.
