### ISSUE TITLE
Add kwarg to make a `Universe` with multiple frames from scratch

### ISSUE THREAD

**Issue by xhgchen** [MDAnalysis/mdanalysis#4110]
## Is your feature request related to a problem? ##
There is currently no way to make a `Universe` with multiple frames from scratch directly in `MDAnalysis.core.universe`.  By default, users can only generate a `Universe` with 1 frame using `empty()`. The only way around that is to make the `Universe` using `empty()` first, initialize the desired coordinates, then `load_new()`. Here is one example of doing so from @orbeckst:
```
u = mda.Universe.empty(11, trajectory=True)
n_frames = 5
coord = np.random.normal(size=(n_frames, u.atoms.n_atoms, 3))
u.load_new(coord)
```
Adding a kwarg to make this doable in one step would make the process more intuitive. I can see it being used in unit tests, where we try to avoid loading files. Tests for anything that subclasses AnalysisBase could benefit. One example is [PR#4105](https://github.com/MDAnalysis/mdanalysis/pull/4105/files). I feel it would also be a good functionality to have in general for anyone wanting to construct a `Universe` from scratch.

## Describe the solution you'd like ##
Add a kwarg `n_frames` to `empty()`:
https://github.com/MDAnalysis/mdanalysis/blob/bdb1352f4743aa2101ba2d6b3c9c4fbeb5ae8584/package/MDAnalysis/core/universe.py#L393-L400

## Describe alternatives you've considered ##
Continue using the current approach with `load_new()` but add it to the [docs](https://docs.mdanalysis.org/stable/documentation_pages/core/universe.html#MDAnalysis.core.universe.Universe.empty) and [User Guide](https://userguide.mdanalysis.org/stable/examples/constructing_universe.html) so that users are actually aware it is possible. It is still missing from the documentation.

**Comment by orbeckst** [comment]
I'd be in favor of adding n_frames as it completes the "build Universe from scratch" approach. In the absence of a way to append to a trajectory #3875 this seems to be a more elegant solution that having to use `load_new()`.

**Comment by xhgchen** [comment]
If we agree that this is a worthwhile addition, I would be happy to give this issue a try after merging my current PR.

**Comment by orbeckst** [comment]
How would you like `n_frames` to work from a user's perspective? Can you write down a mock-up of how one would use it if it were implemented already?

**Comment by xhgchen** [comment]
The user would enter the kwarg `n_frames` to specify how many frames they want in the trajectory. If they wanted a `Universe` with 100 atoms and 10 frames, they would use:
```
u = mda.Universe.empty(100, n_frames=10)
```
From a user's perspective, I feel that it would be most straightforward for everything to work like in the [User Guide's constructing a Universe from scratch page](https://userguide.mdanalysis.org/stable/examples/constructing_universe.html) i.e. a trajectory with multiple frames behaving the same as a trajectory with a single frame.

If the user has an array of coordinates for the trajectory called `coords`, it would be easiest for the following to work regardless of whether the trajectory has a single frame or multiple frames:
```
u.atoms.positions = coords
```
If we decide this approach makes sense and is worth all the effort, then it would have to work for velocities, forces, and bonds as well.

But looping through is not a bad alternative and would not require editing the code extensively (while the above idea likely would):
```
for i, ts in enumerate(u.trajectory):
    u.atoms.positions = coords[i]
```

**Comment by orbeckst** [comment]
> If the user has an array of coordinates for the trajectory called coords, it would be easiest for the following to work regardless of whether the trajectory has a single frame or multiple frames:
> 
>      u.atoms.positions = coords

I would not like to support this syntax as it totally breaks how `.positions` is used everywhere else.

You'll either need to use `load_new()` for the empty Universe or directly work with the underlying [MemoryReader](https://docs.mdanalysis.org/stable/documentation_pages/coordinates/memory.html) in `u.trajectory`: you can directly set the underlying arrays (although I _think_ there are only methods for coordinates and for everything else you'll need to work with the underlying attributes).

Alternatively, provide the coords (and velocities and forces and dimens) to `empty()` although that goes against the semantics of "empty".

**Comment by xhgchen** [comment]
Appreciate the clarification. Since that syntax is not a good idea, would it be okay for me to turn the [draft PR](https://github.com/MDAnalysis/mdanalysis/pull/4140) into an active PR? Based on our initial discussion and the docs, I do feel the `kwarg` itself is worth adding for the flexibility of not having to `load_new()` to replace the initial `empty()`.

**Comment by orbeckst** [comment]
yes, sure
