### ISSUE TITLE
using duecredit in MDAnalysis

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/mdanalysis#412]
From a [tweet](https://twitter.com/katyhuff/status/639861398965612544) by @katyhuff I learned about [duecredit](https://github.com/duecredit/duecredit), a module that makes it easy to associate code with academic citations.

A library such as MDAnalysis, that relies on the [work of many](https://raw.githubusercontent.com/MDAnalysis/mdanalysis/develop/package/AUTHORS),  needs to clearly give credit were credit is due. We already try to do this with a [list of citations](http://www.mdanalysis.org/pages/citations/) but that is still easily missed by a user and is also not very convenient to update. [duecredit makes citing of specific code easy](https://github.com/duecredit/duecredit#duecredit-101), by compiling a bibliography of the _code pieces that you used_ (even in BibTeX) for you. Given that citations are still the currency of recognition in academia and given that the primary audience of MDAnalysis is academia, it is important that we acknowledge all the work that goes into contributing code to an open source software project.

Comments?

**Comment by hainm** [comment]
@orbeckst 

excerpt from duecredit github

`
Scientific software often, if not always, uses 3rd party libraries (e.g., NumPy, SciPy, atlas) which might not even be visible at the user level. Therefore they are rarely referenced in the publications despite providing the fundamental core for solving a scientific problem at hands.
`

If user used ``sklearn``, built on top of numpy and scipy. numpy uses bla bla, the bla bla uses other packages... What's your general 'idiom' in citing?

**Comment by richardjgowers** [comment]
So if I've read the module correctly,
 - it does nothing by default
 - if MDAnalysis is run with either a special environment variable or a python argument it'll make a nice citation list depending on what was used
 - if duecredit isn't installed it fails cleanly (is completely optional)

So if all that is true then I'm in favour.

**Comment by kain88-de** [comment]
Yeah sounds good.  It will definitely save me the manual search for papers to cite that I did so far.

**Comment by orbeckst** [comment]
@hainm :
> If user used sklearn, built on top of numpy and scipy. numpy uses bla bla, the bla bla uses other packages... What's your general 'idiom' in citing? 

For example, for [arXiv:1505.04807](http://arxiv.org/abs/1505.04807) (which implements [Path Similarity Analysis](https://pythonhosted.org/MDAnalysis/documentation_pages/analysis/psa.html) in MDAnalysis) we are citing everything that we directly touch or use specific parts of:

* MDAnalysis
* scipy (for some of the clustering)
* matplotlib and seaborn for plotting

We did not cite numpy or Python explicitly.

**Comment by hainm** [comment]
Thanks.

**Comment by orbeckst** [comment]
So we want to use this but probably not for 0.13 --- I suggest to bump it up to 1.0. If it gets done earlier, even better!

**Comment by theaverageguy** [comment]
Can I get some help on this?

**Comment by jbarnoud** [comment]
@theaverageguy Sure. What help do you need?

**Comment by ayushsuhane** [comment]
I can try to work on it. Can anyone help me with the requirements?

**Comment by orbeckst** [comment]
(sorry pressed wrong button... didn't want to close)

**Comment by ayushsuhane** [comment]
I added the required scripts for duecredit . Please review  #1789
