### ISSUE TITLE
WaterBridge: IndexError if distance_type = "heavy" 

### ISSUE THREAD

**Issue by i2nico** [MDAnalysis/mdanalysis#4136]
https://github.com/MDAnalysis/mdanalysis/blob/6c50334239c2fe14b86caea16c1fe46462b70ae0/package/MDAnalysis/analysis/hydrogenbonds/wbridge_analysis.py#L1198

Hello everyone, 

I was calculating water-bridges and encountered the following issue:
If I use _**distance_type = "heavy"**_, I get an IndexError:

File ~/miniconda3/envs/MD_simulation/lib/python3.10/site-packages/MDAnalysis/analysis/hydrogenbonds/wbridge_analysis.py:1265, in WaterBridgeAnalysis._donor2acceptor(self, donors, h_donors, acceptor)
     1237     d = tmp_donors[index]
     1238     a = tmp_acceptors[index]
     1239     result.append((h, d, a, self._expand_index(h),
     1240                    self._expand_index(a),
-> 1241                    distances[index], angles[index]))
     1242 return result

I had a quick look at the code and it seems like there is a logic error:

First, we are looking for valid distances: (which is fine)
https://github.com/MDAnalysis/mdanalysis/blob/6c50334239c2fe14b86caea16c1fe46462b70ae0/package/MDAnalysis/analysis/hydrogenbonds/wbridge_analysis.py#L1207-L1211

If we now want to check respective angles, we are creating a list of temporary donors, since a heavy donor atom can have multiple hydrogens: (which is also fine)
https://github.com/MDAnalysis/mdanalysis/blob/6c50334239c2fe14b86caea16c1fe46462b70ae0/package/MDAnalysis/analysis/hydrogenbonds/wbridge_analysis.py#L1216-L1224

Afterwards, we are considering H-Bonds as valid, if respective angle was within a certain cutoff, however the indices of _angles_ and _distances_ do not match anymore... (since we had to consider multiple hydrogens attached to the donor atoms)
https://github.com/MDAnalysis/mdanalysis/blob/6c50334239c2fe14b86caea16c1fe46462b70ae0/package/MDAnalysis/analysis/hydrogenbonds/wbridge_analysis.py#L1234-L1242

Edit: For now, I do not return respective distances, since I am not interested in them... :)

At least that is what I understood...
Best wishes,
Nico

**Comment by orbeckst** [comment]
This may be fixed with PR #4066 — @xiki-tempula ?

**Comment by xiki-tempula** [comment]
Yes. this shall be fixed by https://github.com/MDAnalysis/mdanalysis/pull/4066
