### ISSUE TITLE
Specify atom sequence to Dihedral to ensure correct torsion is calculated.

### ISSUE THREAD

**Issue by Dan-Burns** [MDAnalysis/mdanalysis#4138]
## Expected behavior ##

Dihedral should return a specified angle rather then the angle that is assumed from the atom id sequence in the atomgroup.

When providing an atomgroup to Dihedral, the atoms are put in the sequence they occur in the topology (a,b,c,d = resnums 1,4,6,8).  It would be good to be able to specify the sequence of atoms (a,b,c,d = resnums 6,1,4,8).

## Actual behavior ##

I have a small molecule that I provide an atomgroup to Dihedral. 
`selection =  'bynum 17870 or bynum 17872 or bynum 17873 or bynum 17865'`

I inspect the atoms in the selection:
```
for atom in u.select_atoms(selection):
    print(f'{atom.name}: {atom.id}')
```
which returns:
```
P: 17865
C1: 17870
C2: 17872
O2: 17873
```
This gives angles in the range of -30 degrees but the correct angle defined by the sequence of atoms I am after is around 60 degrees.

I could call calc_dihedral on the atoms coordinates for each frame.  An option in Dihedral to specify the sequence of atom numbers might be good to avoid confusion if possible. 

Thank you,
Dan

## Current version of MDAnalysis ##

- Which version are you using? 2.3.0

**Comment by orbeckst** [comment]
If you create an AtomGroup from a single selection, the the AtomGroup is ordered (to remove duplicates). If you need the order then create the AG with multiple selections:
```python
dih_ag = u.select_atoms("bynum 17870", "bynum 17872", "bynum 17873", "bynum 17865")
```

Does this solve your problem?

See also https://userguide.mdanalysis.org/stable/selections.html at the top of the page.

**Comment by orbeckst** [comment]
Btw, if you do _not_ care about order then you can write the original selection more compactly as 
```python
selection =  'bynum 17870 17872 17873 17865'
```

**Comment by Dan-Burns** [comment]
Yes that does solve it - Thank you, Oliver! Never suspected the manual could solve my problem 🧐.

Dan
