### ISSUE TITLE
highlight API breaking changes in CHANGELOG for 0.11.0

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/mdanalysis#415]
The [CHANGELOG](https://raw.githubusercontent.com/MDAnalysis/mdanalysis/develop/package/CHANGELOG) for 0.11.0 needs a bit of love:

- [x] highlight changes that break the API in a separate section
- [x] check spelling and fix other typos
- [x] refer to issues consistently (``Issue #XXX``)
- [x] put a short note that this release breaks the API and add a link to https://github.com/MDAnalysis/mdanalysis/wiki/MDAnalysis-0.11-unifying-release-user-guide

**Comment by richardjgowers** [comment]
Ok I think I've done this
