### ISSUE TITLE
Bilayer membrane with an ion-channel compound inside it

### ISSUE THREAD

**Issue by Haniyehbaluch** [MDAnalysis/mdanalysis#4165]
Hi.
I want to make a bilayer membrane with an ion-channel compound inside it.
I made a polymer structure with 268 atoms including C, N, H, and Br by using Avogadro software, then I converted it to a PDB file with Vmd software...
but the PDB file does not read on charmmgui.org
what should I do?
please answer!

**Bilayer membrane** , **polymer**, **PDB format** , **Residues ID**

**Comment by IAlibay** [comment]
@Haniyehbaluch - this doesn't seem to be related to MDAnalysis usage?

This issue tracker is specifically for raising issues related to MDAnalysis library. If this is a usage / off topic, may I encourage either asking on our mailing list or discord server?

**Comment by IAlibay** [comment]
@Haniyehbaluch if you can respond here that would be great.

**Comment by IAlibay** [comment]
Closing for now due to lack of further information. Please reopen if necessary.
