### ISSUE TITLE
GSD 3.0 fails w/ pytest-xdist/cov

### ISSUE THREAD

**Issue by IAlibay** [MDAnalysis/mdanalysis#4172]
See: https://dev.azure.com/mdanalysis/mdanalysis/_build/results?buildId=5846&view=logs&j=20ededa3-d725-5c28-882d-f9e714f63884&t=ee6fadee-24b3-58c2-f7a0-e9750bae5c01

**Comment by IAlibay** [comment]
Upstream discussion: https://github.com/glotzerlab/gsd/issues/255#issuecomment-1595031852

**Comment by IAlibay** [comment]
Only reason the Windows and MacOS runners are affected right now is because the conda-forge release isn't up yet...

**Comment by joaander** [comment]
GSD 3.0.1 fixes this error. In my testing on https://github.com/glotzerlab/gsd/issues/257 you can also work around this by importing gsd (`import gsd`) in the main thread prior to launching child threads.

**Comment by IAlibay** [comment]
Fixed, gsd is now an optional dependency and 3.0.1+ only.
