### ISSUE TITLE
[docs] core/topologyattrs page format is broken

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/mdanalysis#4177]
## Expected behavior ##
All docs pages are well-formatted.

## Actual behavior ##
Doc page [11.3.3. Topology attribute objects — [MDAnalysis.core.topologyattrs](https://docs.mdanalysis.org/stable/documentation_pages/core/topologyattrs.html) is not formatted correctly (see screen shot, sorry, long)

- footer with authors on the side
- classes and functions are partially hideen by side menu and at end instead of integrated into page

![image](https://github.com/MDAnalysis/mdanalysis/assets/237980/3b5c4d77-e4af-4eef-9cfd-2dfd1b062e13)

## Code to reproduce the behavior ##

Load https://docs.mdanalysis.org/stable/documentation_pages/core/topologyattrs.html#MDAnalysis.core.topologyattrs.Masses.radius_of_gyration in desktop web browser

## Current version of MDAnalysis ##

- docs version 2.5.0

**Comment by IAlibay** [comment]
Do we have an idea of when this started going wrong? The rtd page looks meh but not as broken.

I'm wondering if this is a sphinx 7 issue (maybe even 7.0.1).

**Comment by orbeckst** [comment]
Given that #4194 indicates more widespread issues with doc formatting, I added a big red label...

**Comment by lilyminium** [comment]
Should be fixed temporarily in #4196 -- I also rebuilt docs manually. https://docs.mdanalysis.org/stable/documentation_pages/core/topologyattrs.html#MDAnalysis.core.topologyattrs.Masses.radius_of_gyration looks fixed to me now, but would appreciate a second look to confirm!
