### ISSUE TITLE
Remove 'Documentation' page in wiki

### ISSUE THREAD

**Issue by dotsdl** [MDAnalysis/mdanalysis#418]
The [Documentation](https://github.com/MDAnalysis/mdanalysis/wiki/Documentation) page on the wiki needs an update, but it is worth considering whether it should exist at all since it is easy for it to fall out of sync with the package (and the sphinx docs), if not forgotten entirely.

I'm in favor of getting rid of it. If there are elements in it that aren't present in the sphinx docs, they should be transferred there. I do like that the page gives a brief summary of how to use the package.

Keep in mind we also have an extended [tutorial](http://www.mdanalysis.org/MDAnalysisTutorial/) that probably needs upkeep now, too.

**Comment by richardjgowers** [comment]
Yep I say kill it.  The wiki is meant to be for code development docs imo

**Comment by kain88-de** [comment]
Rather have a visible link to the docs in the README.

**Comment by orbeckst** [comment]
I agree that the _Documentation_ wiki page can go... well, I basically agree with everything that @dotsdl said.

The `README` could have a docs badge at the top, the short summary paragraph, and then the rest, which is really for developers. We have a lot of decent docs so I'd rather direct people to the docs than to make them think that they should be using the `README`.

**Comment by richardjgowers** [comment]
Ok I've done the README fixes

**Comment by orbeckst** [comment]
I checked the Documentation page, did not find any content that was worth saving (should be all in the real docs by now or was old), so I deleted the page from the wiki and the side bar.

RIP original MDAnalysis documentation.

**Comment by dotsdl** [comment]
*pours liquor on the kitchen floor*
