### ISSUE TITLE
pyproject.toml does not contain RDKIT

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/mdanalysis#4185]
## Expected behavior ##

pyproject.toml contains all necessary dependencies

## Actual behavior ##

RDKIT (for the converter) is missing; I'd expect it to be in the extra format dependencies:

https://github.com/MDAnalysis/mdanalysis/blob/6532f7bf0d844c7c524d1c5924ea760dc963750c/package/pyproject.toml#L74-L81

## Current version of MDAnalysis ##

develop

**Comment by orbeckst** [comment]
Specifically
```
.github/actions/setup-deps/action.yaml:    default: 'rdkit>=2020.03.1'
```

**Comment by IAlibay** [comment]
Yeah for a long while rdkit didn't have a pypi distribution, since it does now we can just add it.

**Comment by orbeckst** [comment]
makes sense

**Comment by IAlibay** [comment]
Should we be adding in Parmed too?

**Comment by orbeckst** [comment]
yes, I think for developers, rather be complete
