### ISSUE TITLE
Add timeout to GitHub Actions that run after a PR

### ISSUE THREAD

**Issue by ztimol** [MDAnalysis/mdanalysis#4192]
## Is your feature request related to a problem? ##

The Github Actions pipeline checks that run after a pull request continues indefinitely from time to time. A particular job fails to end as expected and appears stuck/frozen.

This may be due to an issue with the newly implemented code or a GitHub Actions issue (possibly a frozen docker container or a disconnect in the apis between the containers and the front-end).

This is not entirely unusual and I have experienced it in both GitHub and Azure pipelines for this and other projects.

Also, not all users are able to cancel running jobs. A timeout to cancel these jobs would prevent them running for excessive lengths.

## Describe the solution you'd like ##

Add a timeout command to the yml pipelines such that each job automatically cancels after a set period of time. 60 minutes may be a good number to go with initially as the currents jobs seem to rarely last longer than 30 minutes (could be significantly mistaken on this though). However, longer or shorted period can be chosen.

## Describe alternatives you've considered ##

No change to current setup. Actions that do no end by themselves will be canceled automatically after 6 hours (the default). Depending on permissions set only certain users may be able to cancel running jobs.

## Additional context ##

Docs/Notes

https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idtimeout-minutes

https://stackoverflow.com/questions/59073731/set-default-timeout-on-github-action-pipeline

**Comment by IAlibay** [comment]
Sure, I can probably add it in. It'll need some time because we need to work out exactly what the resonable timings are for every job type.
