### ISSUE TITLE
[docs] MSD docstrings not displaying correctly

### ISSUE THREAD

**Issue by xhgchen** [MDAnalysis/mdanalysis#4194]
## Expected behavior ##
[MSD docs page](https://docs.mdanalysis.org/stable/documentation_pages/analysis/msd.html) is displayed with the correct alignment and the text is easily readable.

## Actual behavior ##
Docstrings in the [MSD docs page](https://docs.mdanalysis.org/stable/documentation_pages/analysis/msd.html) are stuck under the left sidebar. This seems to be similar to #4177 

![Screenshot from 2023-07-11 14-10-49](https://github.com/MDAnalysis/mdanalysis/assets/110699064/1cfe081f-08e9-40ec-95e3-382e6cade37b)

## Current version of MDAnalysis ##
docs version 2.5.0

**Comment by IAlibay** [comment]
Seems to be somewhat linked to https://github.com/MDAnalysis/mdanalysis/issues/4177

There's something going wrong with our docs.

@MDAnalysis/coredevs this requires addressing as a priority.

**Comment by xhgchen** [comment]
I can also confirm that this was not an issue until very recently, though I am not sure exactly when it started going wrong. I am certain it was displaying correctly from February until the beginning of GSoC 2023. I am not sure about end of June-early July but I think it was probably fine in the beginning of June.

**Comment by xhgchen** [comment]
Update: I realized the authors list is also displaying strangely - it appears underneath the blurbs and is not very readable. This is also visible in #4177 

![Screenshot from 2023-07-13 14-46-32](https://github.com/MDAnalysis/mdanalysis/assets/110699064/747cd0c6-cd0e-4170-85eb-b87d156e3698)

**Comment by lilyminium** [comment]
I opened #4196 to fix this, but it'll only affect docs from 2.6.0-dev0 and onwards. I've rebuilt docs for 2.5.0 and pushed manually for now. Could you please check that https://docs.mdanalysis.org/stable/documentation_pages/analysis/msd.html looks ok to you? :)

**Comment by xhgchen** [comment]
@lilyminium Nice! Yes, it looks good on my end now too :)

**Comment by lilyminium** [comment]
Fixed in #4196
