### ISSUE TITLE
Examples library

### ISSUE THREAD

**Issue by richardjgowers** [MDAnalysis/mdanalysis#420]
So we have a large number of [examples](https://github.com/MDAnalysis/mdanalysis/tree/develop/package/examples) that need checking after 0.11.0 (both because of API and to check if they work)

I was thinking we should modernise these into ipython notebooks, I did one a while ago as an example (and need to update for 0.11.0):

https://github.com/richardjgowers/richardjgowers.github.io/blob/master/eth_hbonds_files/eth_hbonds.ipynb

These should ideally be examples of common analysis (RDFs, MSD, etc) that take up after the tutorial leaves off (so assume a very basic understanding of MDA).  I was also thinking these could all exist on our website, which is a repo itself:

https://github.com/MDAnalysis/MDAnalysis.github.io

So I think what is needed is a few volunteers to write/check/review these

**Comment by orbeckst** [comment]
Modernizing the examples is a high-kudos undertaking!

I don't think that all of them are useful as Jupyter notebooks, or at least it would be good to still have a simple text file representation. Reading Konrad Hinsen's post [Beyond Jupyter: what’s in a notebook?](https://khinsen.wordpress.com/2015/09/03/beyond-jupyter-whats-in-a-notebook/) reminded me that notebooks are not a good format to store code in—simple ASCII files are *much* better for that. 

I agree with you (and Hinsen) that notebooks are good for teaching, especially if we intersperse them with explanations and images.

We do have a beta version of the [MDAnalysis Tutorial](http://www.mdanalysis.org/MDAnalysisTutorial/) as a Jupyter notebook, [MDAnalysisTutorial.ipynb](http://nbviewer.ipython.org/github/MDAnalysis/MDAnalysisTutorial/blob/master/notebooks/MDAnalysisTutorial.ipynb).

**Comment by hainm** [comment]
You can embed both notebook and script (autogenerated) in rst file.

Check the script at the bottom here: http://amber-md.github.io/pytraj/doc/build/html/tutorials/hbonds.html

http://amber-md.github.io/pytraj/doc/build/html/_sources/tutorials/hbonds.txt

**Comment by orbeckst** [comment]
I am moving this to a later milestone.

**Comment by kain88-de** [comment]
I recently had the thought that we could polish some of the examples and publish them as notebooks on our new blog.

**Comment by orbeckst** [comment]
On 28 Dec, 2015, at 15:25, kain88-de wrote:

> I recently had the thought that we could polish some of the examples and publish them as notebooks on our new blog.

Good idea, and I think @dotsdl said that the notebook to rst (or markdown?) export was not too bad.

**Comment by richardjgowers** [comment]
I'm closing this because it's either a [website](https://github.com/MDAnalysis/MDAnalysis.github.io) or [Cookbook](https://github.com/MDAnalysis/MDAnalysisCookbook) repo issue now

**Comment by orbeckst** [comment]
Can you or the original author (?) re-raise on cookbook and reference MDAnalysis/mdanalysis#420 ?

On 18 Jan, 2016, at 09:34, Richard Gowers wrote:

> I'm closing this because it's either a website or Cookbook repo issue now
> 
> �
> Reply to this email directly or view it on GitHub.
> 

--
Oliver Beckstein * orbeckst@gmx.net
skype: orbeckst  * orbeckst@gmail.com
