### ISSUE TITLE
Issue using SMARTS selection string

### ISSUE THREAD

**Issue by diaghil** [MDAnalysis/mdanalysis#4206]
## Expected behavior ##

I am trying to use a SMARTS selection string together with another selection string targeting a ligand from a PDB file. My goal is to target specific kinds of atomic interactions between the ligand and protein residues contained in the PDB.

## Actual behavior ##

Trying to use 'smarts' as a selection token returns the following error in MDAnalysis version 1.0.0:
MDAnalysis.exceptions.SelectionError: Unknown selection token: 'smarts'

## Code to reproduce the behavior ##

``` python
import MDAnalysis as mda
from MDAnalysis.tests.datafiles import PSF, DCD,  GRO, PDB, TPR, XTC, TRR,  PRMncdf, NCDF

u = mda.Universe(PDB, DCD, refresh_offsets=True)
selection ='smarts [#7;R]'
lig_md=u.select_atoms(selection)


....

```

## Current version of MDAnalysis ##

MDAnalysis 0.16.2 on Python 2.7.14, Red Hat Enterprise Linux Workstation

**Comment by RMeli** [comment]
Hi @diaghil. Version `0.16.2` of MDAnalysis is _very_ old. As far as I'm aware, [SMARTS selection require the `RDKitConverter`](https://docs.mdanalysis.org/stable/documentation_pages/selections.html#simple-selections), which was added only in version 2.0.0 (IIRC). 

I'd suggest to update to the latest version of MDAnalysis: `2.5.0`. You will also need to install RDKit.

**Comment by RMeli** [comment]
PS: I see you are using Python 2.7. Python 2 reached [EOL the 1st of January 2020](https://www.python.org/doc/sunset-python-2/) and it is therefore no longer supported by MDAnalysis `2.x`.

**Comment by orbeckst** [comment]
@diaghil you should be able to create a conda environment with Python 3.10 and install MDAnalysis 2.5 with RDKIT (which is needed for the functionality) as described in our [Quick Start Installation Instructions](https://www.mdanalysis.org/pages/installation_quick_start/).

There's nothing we can do for you with 0.16.2 so I am closing the issue but feel free to let us know on the closed issue if you've been able to install and run the new version.

For questions about installation and general usage, please [join our mailing list or discord](https://www.mdanalysis.org/#participating) and ask there — there's a big community of users and developers around MDAnalysis that can help.
