### ISSUE TITLE
[CI] conda & pypi post deployment tests

### ISSUE THREAD

**Issue by IAlibay** [MDAnalysis/mdanalysis#4208]
We don't have CI infrastructure in place to regularly check that our deployments actually work post-release.

Generally we tend to pick stuff up from the `develop` branch and then push it back as a bugfix, but we probably should also regularly check that things still work / we haven't forgotten to push a bugfix.

It's a simple enough fix, we just need to add stuff to our cron runner.

**Comment by orbeckst** [comment]
Good idea! I didn’t think this would be necessary but that just shows that as soon you think a test is superfluous, you get bitten by something that such a test would have caught.
