### ISSUE TITLE
Release 2.6.x

### ISSUE THREAD

**Issue by IAlibay** [MDAnalysis/mdanalysis#4228]
We should make a new release. My aim will be to probably get it done this weekend.

Are there any important things that haven't been dealt with that should make it into this release?

**Comment by IAlibay** [comment]
pinging @MDAnalysis/coredevs

**Comment by IAlibay** [comment]
#4198 might be a good one to get done, that'll significantly improve how we handle numpy ABI things

**Comment by orbeckst** [comment]
Can this be closed, given that 2.6.0 was out in mid-August?

**Comment by IAlibay** [comment]
2.6.0 was never really out 🙃 - 2.6.1 is more or less done, just waiting on blog post changes / approval.

**Comment by IAlibay** [comment]
I'm closing this as done because I need to clear stuff off my task list - @fiona-naughton the blog post is pretty much done, I'm leaving this to you to merge & publicise at your leisure.
