### ISSUE TITLE
Fixing spelling of Boltzmann constant typo in MDAnalysis.units is an API break

### ISSUE THREAD

**Issue by hmacdope** [MDAnalysis/mdanalysis#4229]
Fixing #4213 with #4214 by @xhgchen  adjusting the spelling of Boltzmann constant typo in MDAnalysis.units is technically an API break, in that if anyone relied on pulling the constant by name we broke that for them.  

Pinging @MDAnalysis/coredevs do we think this is an issue or not.

**Comment by xhgchen** [comment]
I used `git grep` to find all instances of the typo in the MDAnalysis repo itself and made the changes accordingly, so I do not think I broke anything in the core library. The question now is whether any MDAKits or other software used it. I think an easy fix would be to allow both the correct and incorrect spellings as keys (and perhaps deprecate the incorrect spelling).

**Comment by hmacdope** [comment]
Thats sounds like a perfectly reasonable and easy fix, along with a deprecation warning for the old spelling.

**Comment by xhgchen** [comment]
I would be happy to look into making this change tomorrow, unless someone else is keen on it or has a better approach :)

**Comment by IAlibay** [comment]
I'm going to let the other @MDAnalysis/coredevs weigh in here - please work out if you this needs changing & make sure it is actioned by end of week. (it's blocking the next release)

**Comment by orbeckst** [comment]
I agree with @xhgchen — make the wrong spelling available again for the next two 2.x releases. 

Add a deprecation note to CHANGELOG and docs. 

I’d skip having code issue a warning as it sounds like a very low impact deprecation… or am I wrong there?

**Comment by IAlibay** [comment]
> I’d skip having code issue a warning as it sounds like a very low impact deprecation… or am I wrong there?

Subclassing the dictionary and wrapping `__getitem__` with a warning is a suitably low cost thing, I'd say let's just have the warning if we can.

**Comment by tylerjereddy** [comment]
If you consider it a "bug fix" the API break should formally be allowed I think, since bug fixes > API issues, but making the incorrect spelling available for a bit longer seems reasonable if folks want it.
