### ISSUE TITLE
[CI] Add py3.12 pre-release tests

### ISSUE THREAD

**Issue by IAlibay** [MDAnalysis/mdanalysis#4233]
Looks like scipy about to release py3.12 wheels: https://github.com/scipy/scipy/pull/19040

We should also start looking at testing our ability to support py3.12. This effectively amounts to bumping up the matrix for this action and seeing what breaks: https://github.com/MDAnalysis/mdanalysis/blob/develop/.github/workflows/gh-ci-cron.yaml#L174

Blockers:
- [x] Scipy 1.11.2 needs to get released
- [ ] We will need to wait for whatever dependency isn't compatible (might be a good starting point for making more things optional).

**Comment by tylerjereddy** [comment]
I released SciPy `1.11.2` with `3.12` wheels on Thursday, so checked that item off above.
