### ISSUE TITLE
[future] NINF removal in python 2.0 causing cron ci to fail

### ISSUE THREAD

**Issue by IAlibay** [MDAnalysis/mdanalysis#4238]
Cron CI is failing because of namspace changes affecting the use numpy.NINF in `pandas` (yes it's an accidental dependency it seems, not sure exactly from where yet).

Fix has been made upstream, we just need to add `pandas` to our list of future installs.

**Comment by tylerjereddy** [comment]
Hmm, indirect dependency on `pandas`? In case it isn't obvious, I suppose you're referring to the alias pruning in NumPy here: https://numpy.org/neps/nep-0052-python-api-cleanup.html#cleaning-up-the-main-namespace

and in particular:

> np.inf and np.nan have 8 aliases between them, of which most can be removed.

I know I did a quick scan of MDA `develop` branch and it seemed reasonably clean for a bunch of those cleanups a while back.
