### ISSUE TITLE
Possible bug in Hydrogen Bond Analysis module (release 2.6.0)

### ISSUE THREAD

**Issue by dillonrmccarthy** [MDAnalysis/mdanalysis#4254]
## Expected behavior ##
I am trying to measure the hydrogen bonds found between two selections on a per-frame basis by iterating through the trajectory. For each time step `ts`, the script should produce the number of hydrogen bonds formed between my selection at a given frame. 

## Actual behavior ##
When using a sliced version of the trajectory, the code works as expected, and returns the number of hydrogen bonds found between selections (using `between=[sel]`) for each frame. I return the shape of the `hbond.results.hbonds` array in order to get the total number of hydrogen bonds. During testing, I only processed the first 10 frames and I observed the expected behavior.  

However, when I process the whole trajectory, I end up stuck on the first frame, and the code does not advance through the trajectory causing me to be stuck in a loop. 

## Code to reproduce the behavior ##

``` 
#=================================================
#!/usr/bin/micro/envs/mdanalysis/bin/python

import MDAnalysis as mda
from MDAnalysis.analysis.hydrogenbonds.hbond_analysis import HydrogenBondAnalysis as HBA
import warnings
warnings.filterwarnings('ignore',category=DeprecationWarning)
import numpy as np
import sys,os,re

#=================================================
#traj readin
dms,dcd = sys.argv[1],sys.argv[2]
u = mda.Universe(dms,dcd)
_times = np.array([u.trajectory.time for ts in u.trajectory]) #fix incorrect recording interval in dmc/dcd
steps = np.array(range(len(_times)))
times = (steps*20/1000) #correct time for simulation @ each timestep

from my_modules import GetBetweenAsl as gasl
asl = gasl(dms) #list of between selections. asl = list of atom selections pairs [[asl_1, asl_2], [asl_3, asl_4], ... [asl_n, asl_n+1]]

#=================================================
for ts in u.trajectory[0:10]:
    hbonds = HBA(universe=u, between=asl[0]) #only processing first between selection.
    hbonds.run(frames=[ts.frame])
    print(ts.frame, hbonds.results.hbonds.shape)
```
the output of this script is:
```
>>> 0 (1, 6)
>>> 1 (2, 6)
>>> ...
>>> 9 (1, 6)
```

However, the following code causes issues. 

```
for ts in u.trajectory:
    hbonds = HBA(universe=u, between=asl[0]) #only processing first between selection.
    hbonds.run(frames=[ts.frame])
    print(ts.frame, hbonds.results.hbonds.shape)
```
The output of this is:
```
>>> 0 (1, 6)
>>> 1 (2, 6)
>>> ...
>>> 1 (2, 6)
```
After the first frame, it does stays stuck on ts=1. Using `for ts in mda.log.ProgressBar(u.trajectory):`, I can see that the progress bar shows I am advancing through the trajectory as normal. However, printing `ts` or `ts.frame` still shows I am stuck on frame 1. 

I am not sure what is causing this. My current workaround is to "slice" the trajectory with `u.trajectory[:-1:]` instead.
 
## Current version of MDAnalysis ##
- Which version are you using? MDAnalysis = 2.6.0
- Which version of Python? 3.11.0
- Which operating system? RHEL Server Version 7.9 (Maipo)

**Comment by hmacdope** [comment]
Hey @dillonrmccarthy, 

The analysis classes in MDAnalysis use `run` to iterate over the whole trajectory, meaning you don't have to do the loop yourself. 

Try removing the loop over frames all together:

```python
hbonds = HBA(universe=u, ...) 
hbonds.run()
 ```

**Comment by dillonrmccarthy** [comment]
@hmacdope 
I guess I was being a bit disingenuous with my description. 

for each frame, I want to return only the 4 "strongest" hydrogen bonds. I define a hydrogen bond being stronger than another by whether the distance between the donor–acceptor distance and hbond angle are smaller and closer to 180 degrees respectively. 

For my script, this meant producing a relatively large number of measured hbonds/frame/selection, then sorting out only the top hbonds at each frame after the results were returned. I figured it was more simple to do this on a per/frame basis, and append the results to my own dataframe. This is because, as I understand it, `hbonds.results.hbonds` is returned as an array of shape [n,6], where n is the number of total hydrogen bonds found. This approach required I first breaking apart the array into other arrays of shape [n,6] based on the value of array[:,0], then concatenate these results back together to produce a final array of shape [m,6], where m=4*frames. 

Maybe I am incorrect, though, and it would be more simple to just do `hbonds.run()`. I am not skilled in MDAnalysis or python, so its very possible I am making a ton of mistakes here.

**Comment by hmacdope** [comment]
I would recommend using run to produce the full dataset and then post-processing. Iterating twice seems to be failure prone as you have noted, although it should probably just work. Let me know if you need any help with it.

**Comment by dillonrmccarthy** [comment]
@hmacdope 

Thanks, I think I will do this. Unfortunately the script takes ~20/30 hours to run in this manner, so I will probably need to either use Dask for multicore processing, or break the script into different ones.

I also might give writing my own HBond analysis script a go this weekend, which could be more efficient. 

 Either way, a day isnt so bad so I think. Thank you for your help, I sincerely appreciate it. 
 
 Not sure if I should close this issue, though, as I dont know if my original description was an actual bug

**Comment by hmacdope** [comment]
If it is taking too long you can use the `start, stop, step` kwargs to `run()` to only sub-select a smaller number of frames. This can also be useful for testing. 

eg :

```python
hbonds = HBA(universe=u, ...) 
hbonds.run(start=x, stop=y, step=z)
```

**Comment by p-j-smith** [comment]
As @hmacdope mentioned, what you're doing is not working probably because the analysis will also iterate over the trajectory/frames selected and then reset the trajectory to the first frame. If you really want to run the analysis one frame at a time, and slicing the trajectory seems to avoid your issue, you could take a slice that covers the whole trajectory:
```python
for ts in u.trajectory[:]:
    hbonds = HBA(universe=u, between=asl[0]) #only processing first between selection.
    hbonds.run(frames=[ts.frame])
    print(ts.frame, hbonds.results.hbonds.shape)
```
or iterate over an array of frame indices rather than the trajectory itself:
```python

for frame in np.arange(u.trajectory.n_frames):
    hbonds = HBA(universe=u, between=asl[0]) #only processing first between selection.
    hbonds.run(frames=[frame])
    print(frame, hbonds.results.hbonds.shape)
```

Also, to make the analysis faster, you should specify an `acceptors_sel` and `hydrogens_sel` and set `update_selections=False`. I'm assuming this should be possible as you're using the `between` keyword, which requires non-updating selections.

Currently, at each frame all hydrogen bonds will be found, and then they will be filtered based on your `between` selections. By specifying `acceptors_sel` and `hydrogens_sel` you will reduce the number of hydrogen bonds that are found prior to the filtering with the `between`selection. And by setting `update_selections=False` you will avoid the cost of selecting atoms at each frame, as [noted in the hydrogen bonds tutorial](https://userguide.mdanalysis.org/stable/examples/analysis/hydrogen_bonds/hbonds.html#Find-water-water-hydrogen-bonds).

If you have any follow-up questions about usage of `HydrogenBondAnalysis`, I'd suggest asking in the [MDAnalysis discussion forum](https://groups.google.com/g/mdnalysis-discussion) rather than in this issue

**Comment by orbeckst** [comment]
I'll close this issue as it does not seem to be a bug per se but ultimately a usage question. Thank you @p-j-smith and @hmacdope for your insights.
