### ISSUE TITLE
simple setting of frame

### ISSUE THREAD

**Issue by euhruska** [MDAnalysis/mdanalysis#426]
I have some issue to random-access a particular frame in a trajectory. I know how to loop through a full trajectory, that's not the issue. I'm not sure if I missed something, but selecting a particular timeframe should be very simple.

**Comment by richardjgowers** [comment]
Heya

If you do `u.trajectory[i]`, then that's the frame that's loaded when you access coordinates later on


``` python
import MDAnalysis as mda

u = mda.Universe(your, files)

# this will be data from frame 0
u.atoms.positions

# tell the reader to load a given frame
u.trajectory[10]

# this will now be data from frame 10 (with 0 based numbering)
u.atoms.positions

```
