### ISSUE TITLE
[Docs] document limits of DielectricConstant

### ISSUE THREAD

**Issue by IAlibay** [MDAnalysis/mdanalysis#4262]
Follow-up from https://github.com/MDAnalysis/mdanalysis/pull/4249#issuecomment-1696077930

As per: https://github.com/MDAnalysis/mdanalysis/pull/4249#issuecomment-1696077930

The limits of DielectricConstant, especially regarding free charge, should be better documented.

**Comment by IAlibay** [comment]
pinging @PicoCentauri

**Comment by PicoCentauri** [comment]
Thanks @IAlibay
