### ISSUE TITLE
alignto argument fails

### ISSUE THREAD

**Issue by euhruska** [MDAnalysis/mdanalysis#427]
For the function MDAnalysis.analysis.align.alignto I try to use argument strict, but it fails. Without "strict" it works.

MDAnalysis.analysis.align.alignto(u, u2, select="all", mass_weighted=True,  strict=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: alignto() got an unexpected keyword argument 'strict'

**Comment by richardjgowers** [comment]
Can you check what version that you're running? (`print MDAnalysis.__version__`)

**Comment by euhruska** [comment]
Oh, I guess that explains it, old version: 0.8.1

**Comment by richardjgowers** [comment]
Easiest way to upgrade is `pip install --upgrade MDAnalysis`
