### ISSUE TITLE
Move on from build_sphinx

### ISSUE THREAD

**Issue by lilyminium** [MDAnalysis/mdanalysis#4277]
## Problem ##

I think sphinx and setuptools integration is gone from 7 onwards -- see failures in https://github.com/MDAnalysis/mdanalysis/pull/4276

I didn't think sphinx_rtd_theme supported 7.0 anyway but they should do from the next release, so let's fix this now than later.

**Comment by IAlibay** [comment]
Yeah it's a thing across the entire org I think.

**Comment by IAlibay** [comment]
Switching this to sphinx-build will probably do the trick? https://github.com/MDAnalysis/mdanalysis/blob/8d20cdcb8e7cdbfea18ef14d2ae2bd9df19f2d0a/.github/actions/build-src/action.yaml#L87-L91
