### ISSUE TITLE
online docs give 404 error

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/mdanalysis#4279]
The online docs at https://docs.mdanalysis.org/ give a 404 error. The docs should be visible.

![image](https://github.com/MDAnalysis/mdanalysis/assets/237980/0b461533-cb80-4603-91c4-40a0fba7115c)

**Comment by IAlibay** [comment]
fixed, we traversed to a non existing directory and messed things up - we should consider using one of the fun reusable actions that probably have way way more safety than our long bash script.

**Comment by orbeckst** [comment]
thanks!!
