### ISSUE TITLE
PDBQTParser.parse() assigns wrong field to charges

### ISSUE THREAD

**Issue by pgbarletta** [MDAnalysis/mdanalysis#4282]
Related to #4207 .

On page 27 from the [PDBQT reference](https://autodock.scripps.edu/wp-content/uploads/sites/56/2021/10/AutoDock4.2.6_UserGuide.pdf) (the most recent reference I could find for the PDBQT format), the PDBQT ATOM register is specified with this C-style string:

```
“ATOM%5d%-4s%1s%-3s%1s%4d%1s%8.3f%8.3f%8.3f%6.2f%6.2f%4s%6.3f%2s \n",
atom_serial_num, atom_name, alt_loc, res_name, chain_id, res_num, ins_code, x, y, z,
occupancy, temp_factor, footnote, partial_charge, atom_type
```
Going backwards from the end, we see that the partial charge takes up 6 columns and then there're 4 columns for a string called 'footnote'. The [current implementation](https://github.com/MDAnalysis/mdanalysis/blob/a1aff6638184a90ae36b879720b2fa78dee1d1ee/package/MDAnalysis/topology/PDBQTParser.py#L143C1-L144C1) of `PDBQTParser.parse()` tries to cast those 10 columns as a float, which may end up giving errors if someone decided to use those columns.

**Comment by IAlibay** [comment]
I wonder if part of this might be flexibility because there were some pdbqt writers out there that were a bit.. inconsistent? Maybe @orbeckst has historical memory on this here

**Comment by orbeckst** [comment]
I don't remember anything about the PDBQT parser, sorry... that's very old code.

If we have a recent reference then we should change to follow the standard.

**Comment by pgbarletta** [comment]
The  .pdf I linked in the original comment is the closest reference I could find in their [website](https://autodock.scripps.edu/documentation/documentation/), and its last edit is from 2014. I think it should be the go-to reference

**Comment by orbeckst** [comment]
Ok, then implement the latest and link to the standard doc.
