### ISSUE TITLE
BUG (?): CRD format disagreement vs. CHARMM-GUI

### ISSUE THREAD

**Issue by tylerjereddy** [MDAnalysis/mdanalysis#4290]
I drafted a regression test below for a scenario where MDAnalysis is perfectly happy to read in a CRD file where there is no space between the atom name and the x coordinate, and the space(s) are replaced by integers. This arose in the "real world" when one of my postdocs (Emvia) was trying to use CHARMM-GUI to generate GROMACS input from a `.psf` and `.crd` file. The original output was from `psfgen` (I think) and it had two issues: 1) the xyz coordinates sometimes had no spaces between them (MDAnalysis agreed with CHARMM-GUI this was not acceptable), 2) the problem I just described (only CHARMM-GUI thought this was not acceptable).

I don't know who is correct on this, certainly `psfgen` is likely incorrect but likely nothing I can do about that (?), I guess we could ping @nk53 on CHARMM-GUI side? I think MDAnalysis may need to make an adjustment here to require the spacing if I had to guess, but not entirely sure. The reason it is useful for MDA to agree with i.e. CHARMM-GUI on this is that it can be quite helpful for debugging issues--if CHARMM-GUI complains then we can easily use MDAnalysis as a proxy for parsing issues where we have direct access to the latest source, etc. That and "format sanity" in the ecosystem of course.

```diff
--- a/testsuite/MDAnalysisTests/coordinates/test_crd.py
+++ b/testsuite/MDAnalysisTests/coordinates/test_crd.py
@@ -137,3 +137,18 @@ class TestCRDWriterMissingAttrs(object):
         # Check missing attr is as expected
         assert_equal(getattr(u2.atoms, missing_attr),
                      self.req_attrs[missing_attr])
+
+
+def test_crd_atom_name_x_gap(tmpdir):
+    # MDAnalysis is not sensitive to an overrun
+    # between atom name and x coordinate
+    # but CHARMM-GUI will choke on this
+    # with an error similar to:
+    # Error: Could not find atom (segid=0.00000, resid=, atom=N) in the system.
+    with tmpdir.as_cwd():
+        with open(CRD) as orig_file:
+            with open("newfile.crd", "w") as outfile:
+                for line in orig_file:
+                    newline = line.replace("HT1  -11.44700", "HT123211.44700")
+                    outfile.write(newline)
+        u = mda.Universe("newfile.crd")
```

**Comment by tylerjereddy** [comment]
To be clear that test passes, but we should perhaps adjust it to check that an error is raised if action is needed on our side.

**Comment by orbeckst** [comment]
As far as I can tell, this is how CHARMM writes coordinates in CARD (crd) files (from `coorio.src` from the free 20170707 version):
* extended: `fm2 = '(2I10,2X,A8,2X,A8,3F20.10,2X,A8,2X,A8,F20.10)'`
* normal: `fm2 = '(2I5,1X,A4,1X,A4,3F10.5,1X,A4,1X,A4,F10.5)'`

and it writes
```fortran
                   WRITE(IUNIT,fm2) &
                        I,IRES,RES(IRES),ATYPE(I),Xyz(1,I),xYz(2,I),xyZ(3,I),SID,RID,WMAIN(I)
```

The atom name/x-coordinate corresponds to `ATYPE(I),Xyz(1,I)` and in extended format to `A8,3F20.10` and `A4,3F10.5` in normal format. There is no `1X` between them so it looks to me that the CHARMM source says that there does not have to be a space between atom and x-coordinate.

My conclusion is that MDAnalysis CRDReader/Writer correctly implement CHARMM's view of the CARD format.

**Comment by tylerjereddy** [comment]
Ok, if that's still the case then it is a CHARMM-GUI bug then I suppose.

**Comment by tylerjereddy** [comment]
I opened a small forum post/ticket over on their site: https://www.charmm-gui.org/forum/viewtopic.php?f=5&t=435

Hopefully they can confirm.

**Comment by nk53** [comment]
Hi all, thanks for reporting this issue. I'll look into it as soon as I can.

**Comment by tylerjereddy** [comment]
I updated the cross-listed bug report to include a tarball with two sample files (PSF, CRD) that can be read directly into CHARMM-GUI FF converter to reproduce the error message (MDAnalysis remains happy to read those ones).

They were generated as minor adjustments to our current test data files `PSF_NAMD, PDB_NAMD`.

https://www.charmm-gui.org/forum/viewtopic.php?p=1135#p1135

**Comment by nk53** [comment]
I see a few problems:

FF Converter's PSF/CRD parsing, uses `str.split()` to separate fields, which obviously does not conform to the official format. However, the PSF example in the linked CHARMM-GUI forum post is malformed at residue 12:
```
      61 A002 11   PHE  O    O     -0.510000       15.9990           0
      62 A002 12   HAO  C    CG2O1   0.511000       12.0110           0
      63 A002 12   HAO  O    OG2D1  -0.455000       15.9994           0
      64 A002 12   HAO  C11  CG2O1   0.515000       12.0110           0
      65 A002 12   HAO  N10  NG2S1  -0.480000       14.0070           0
      66 A002 12   HAO  O11  OG2D1  -0.462000       15.9994           0
      67 A002 12   HAO  C8   CG2R61   0.157000       12.0110          0
```
Long atom type names cause subsequent fields to be over-indented. Since they are space-delimited, the PSF reads fine; only the CRD has issues.

Also, at this line of the CRD file:
```
  106    5 TYR  HE222211.87800  -1.28300  -6.62400 A002 13     0.00000
```
A strict reading of the CRD format implies that the atom name must be HE22 and the X coordinate is `2211.87800`. However, the PSF contains no atom named HE22, but several named HE2. This suggests that the written X coordinate is too large for the field width (10) and that extended format should be used instead. (Although, really, the X coordinate of this one atom being so different from any of its attached atoms makes me think that the structure is unreasonable)

If psfgen really produces space-delimited PSF files, then I worry that I will break VMD users' ability to use FF Converter. I suppose I could put an option on the site to toggle strict PSF/CRD parsing, or I could use strict CRD format only and stick to the current approach for PSF files (this would be the easiest for me).

What do you think?

**Comment by tylerjereddy** [comment]
The `PSF` issue you mention does happen in the actual test file used in the MDAnalysis repo here: https://github.com/MDAnalysis/mdanalysis/blob/develop/testsuite/MDAnalysisTests/data/namd_cgenff.psf#L68.

I'll let other MDA devs comment on that one--I don't normally work with these formats, I was just looking for reliable consistency between tools that consume/produce them for debugging sanity, etc.

Note that as the discussion above suggests, that CRD file has been synthetically modified to generate the problem intentionally at the atom you highlight, because MDAnalysis is happy with it, and CHARMM-GUI is not, and I wasn't prepared to share the exact case that arose "naturally." So, yes, it is "fake" but it is a realistic representation of something that arose in the wild from `psfgen` I believe.

Strict format parsing for CRD may be useful, the deviation from the "specification" did make it harder for my team to debug the CHARMM-GUI complaint relative to MDA source code for parsing.

**Comment by nk53** [comment]
OK, I have a local code change that causes FF converter to use the official CRD format. Unless I hear otherwise in the next day, I will finalize that change, but leave our current PSF parsing approach untouched.

**Comment by tylerjereddy** [comment]
Sounds good to me, at least!

**Comment by tylerjereddy** [comment]
I don't think there's any action item remaining for MDAnalysis here. If you think there's something wrong with our PSF test data file maybe that belongs in a separate issue anyway.

Thanks for clarifying on the CHARMM-GUI side.
