### ISSUE TITLE
GROMOS11 trajectory reader

### ISSUE THREAD

**Issue by JoStoe** [MDAnalysis/mdanalysis#4291]
GROMOS11 is a software to conduct molecular dynamics simulation. As of MDAnalysis version 2.6, GROMOS11 trajectories are not supported. To enable the research group I'm working with to use MDAnalysis, we would need the ability to read GROMOS trajectories.

I will implement the feature myself and make a pull request as soon as the reader is production ready.

Best regards,
Johannes

**Comment by hmacdope** [comment]
Fantastic!

**Comment by orbeckst** [comment]
There were some possible improvements identified for the reader in the review on PR #4292 
* performance improvements (reader itself and when used in CHAINREADER)
* have MDA internally convert special GROMOS11 PBC treatments to triclinic

Please feel free to raise separate issues that could then be addressed separately.
