### ISSUE TITLE
Python 3.12 cannot pickle PickleBufferIOPicklable instances

### ISSUE THREAD

**Issue by IAlibay** [MDAnalysis/mdanalysis#4299]
This is one of the biggest issues we're facing with Py3.12:

https://github.com/MDAnalysis/mdanalysis/actions/runs/6277097391/job/17048178820?pr=4265#step:8:375

As far as I can tell there's isn't anything super obvious in the changelog that would cause this.

**Comment by yuxuanzhuang** [comment]
This should be due to https://github.com/python/cpython/pull/104370

But allegedly, only protocol 0 and 1 should be disallowed so I am not sure what's happening here. I am also not able to test on Python 3.12 at the moment.

PEP ref: https://peps.python.org/pep-0687/

**Comment by harryhritik12** [comment]
Hey, I would like to solve this issue.

**Comment by IAlibay** [comment]
@harryhritik12 - Apologies, I believe this is already in progress of being fixed by #4300
