### ISSUE TITLE
Remove mdanalysis.analysis.data and make files live with the rest of the test data. 

### ISSUE THREAD

**Issue by hmacdope** [MDAnalysis/mdanalysis#4313]
There is a strange orphan directory with some `janin` data that we should move to be with the rest of the test data.

**Comment by IAlibay** [comment]
This isn't test data though - it's used in the plotting method for contours. It's also a rather widely used method that we have expertise in so I'm not sure moving it out to an mdakit makes sense.

**Comment by orbeckst** [comment]
These data belong to analysis. I think you can close this issue.

**Comment by IAlibay** [comment]
Closing, but thanks still to @hmacdope for poking at things for 3.0, it's the only way we'll find out all the historical stuff.
