### ISSUE TITLE
Switch everything touching PyPi to OpenID connect

### ISSUE THREAD

**Issue by IAlibay** [MDAnalysis/mdanalysis#4326]
The recommend workflow for uploading things to PyPi is now through OpenID connect.

I've yet to get to grips with the full pipeline for this, so I'll slowly start doing migrations.

There's a bunch of things I don't have keys for, so I'll be pinging folks for access or to update things themselves as things progress.

**Comment by IAlibay** [comment]
MDA direct repos to update:
- [x] Core library - PR #4325 
    - [x] MDAnalysis testpypi trusted publisher
    - [x] MDAnalysis pypi trusted publisher
    - [x] MDAnalysisTests testpypi trusted publisher
    - [x] MDAnalysisTests pypi trusted publisher
- [x] PyTNG - PR https://github.com/MDAnalysis/pytng/pull/107
    - [x] testpypi trusted publisher - @orbeckst or @hmacdope for access
    - [x] pypi trusted publisher - @orbeckst or @hmacdope for access
- [x] panedr / pyedr https://github.com/MDAnalysis/panedr/pull/72
    - testpypi trusted publisher: pyedr - we don't own this
    - testpypi trusted publisher: panedr - we don't own this
    - [x] pypi trusted publisher: pyedr
    - [x] pypi trusted publisher: panedr
- [x] mda-xdrlib https://github.com/MDAnalysis/mda-xdrlib/pull/9
    - [x] testpypi trusted publisher
    - [x] pypi trusted publisher
- [x] griddataformats https://github.com/MDAnalysis/GridDataFormats/pull/136
    - [x] testpypi trusted publisher
    - [x] pypi trusted publisher
- [x] mdanalysis-sphinx-theme https://github.com/MDAnalysis/mdanalysis-sphinx-theme/pull/72
    - [x] testpypi trusted publisher @lilyminium @orbeckst @IAlibay for access
    - [x] pypi trusted publisher @lilyminium @orbeckst @IAlibay for access

MDAKits under the org:

- [x] mdaencore - @IAlibay @orbeckst or @ianmkenney for access 
- [x] PathSimAnalysis (needs update to pypi-deployment) - @orbeckst or @ianmkenney @IAlibay for access https://github.com/MDAnalysis/PathSimAnalysis/pull/7
- [x] waterdynamics (needs update to pypi-deployment) - @orbeckst or @ianmkenney @IAlibay for access https://github.com/MDAnalysis/waterdynamics/pull/17

MDAKits under the org that don't have deployment workflows but we should still know who has access:
- membrane-curvature - @ojeda-e for access
- transport-anslysis - @hmacdope or @orionarcher for access
- solvation-anlysis - @orionarcher for access

**Comment by orbeckst** [comment]
Thanks for collecting the list and getting the process started. Let me know if you need anything. I don't know what one has to do in order to enable OpenID on PyPi.

**Comment by IAlibay** [comment]
> Thanks for collecting the list and getting the process started. Let me know if you need anything. I don't know what one has to do in order to enable OpenID on PyPi.

I've not tried a deployment yet, but it's not that much work, you just need to know the right yaml file & environment - https://docs.pypi.org/trusted-publishers/adding-a-publisher/

**Comment by IAlibay** [comment]
@jbarnoud I don't have management access to `panedr` on pypi - could you add the trusted publisher or add me as a manager?

**Comment by jbarnoud** [comment]
I just made you owner on pypi.

**Comment by IAlibay** [comment]
> I just made you owner on pypi.
> […](#)
> On 27 October 2023 19:06:13 CEST, Irfan Alibay ***@***.***> wrote: @jbarnoud I don't have management access to `panedr` on pypi - could you add the trusted publisher or add me as a manager? -- Reply to this email directly or view it on GitHub: [#4326 (comment)](https://github.com/MDAnalysis/mdanalysis/issues/4326#issuecomment-1783239869) You are receiving this because you were mentioned. Message ID: ***@***.***>

Thanks!

**Comment by IAlibay** [comment]
Putting on my coredev hat for a second - there are at least a couple of sole ownership projects across the org, that's rather dangerous.

Could I ask that anything which we end up having maintenance of have at least two coredevs in charge?

Pinging @lilyminium for the sphinx theme and @orbeckst for pathsimanalysis and waterdynamics.

Not sure what the deal is with maintenance of membrane-curvature and solvation-analysis, pinging @ojeda-e and @orionarcher for discussion.

**Comment by orbeckst** [comment]
@IAlibay (as `IAlibay`) was invited for pathsimanalysis but the invite expired. I re-invited you for pathsimanalysis and also for waterdynamics.

**Comment by orbeckst** [comment]
Added more invites for IAlibay:
- pypi: pytng
- testpypi: waterdynamics, pathsimanalysis, mdaencore

**There's no testpypi pytng.** — do you want to create it @IAlibay ?

**Comment by IAlibay** [comment]
> There's no testpypi pytng. — do you want to create it @IAlibay ?

Yes, it's a good opportunity to test out the next "anticipated publishing" portion of PyPi!

**Comment by IAlibay** [comment]
Ok I'm stopping at the core library upstream dependencies for now - we haven't tried an actual deployment beyond the pypi-deployment tests, so it's possible that all the PRs I've opened aren't 100% correct.

I propose we merge the PyTNG one and then do a release and see how that goes?

**Comment by orbeckst** [comment]
sounds good, 🤞

**Comment by IAlibay** [comment]
pytng went up fine - everything else _should_ work (assuming no typos).

**Comment by lilyminium** [comment]
I added GH as a trusted publisher and also @IAlibay and @orbeckst as owners to mda-sphinx-theme on pypi and testpypi.

**Comment by orbeckst** [comment]
thanks!
