### ISSUE TITLE
Array to scalar deprecation warning

### ISSUE THREAD

**Issue by IAlibay** [MDAnalysis/mdanalysis#4339]
From nightly wheels cron CI:

2023-11-03T03:16:21.1300895Z   /home/runner/work/mdanalysis/mdanalysis/package/MDAnalysis/analysis/nuclinfo.py:302: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
2023-11-03T03:16:21.1302468Z     phase_ang = (atan2(D, C) + (pi / 2.)) * 180. / pi

**Comment by Yash-g17** [comment]
Hello I feel this is a good first issue for me , would be glad to take this up

**Comment by orbeckst** [comment]
@Yash-g17 sorry for the delayed response. You (and anybody else) is very welcome to take on any issue. Please create a PR and in the issue text include this issue number, which links your PR to this issue.

**Comment by laksh-krishna-sharma** [comment]
May I work on this issue with a little bit of your guidance?

**Comment by laksh-krishna-sharma** [comment]
Hello @orbeckst , may i work on this issue with a bit of your guidance

**Comment by orbeckst** [comment]
Thank you for your interest. Please see my previous answer https://github.com/MDAnalysis/mdanalysis/issues/4339#issuecomment-2019085039 .

**Comment by dimeneman** [comment]
I want to contribute in this issue. Please assign it to me .

**Comment by orbeckst** [comment]
Hello @dimeneman , we do not assign issues — please create a PR and link it to this issue and then we can review it.

**Comment by orbeckst** [comment]
Except that PR #4730 is already open. We will re-review that one first. 

I would not recommend starting a PR while another one for the same issue is open.

**Comment by tanishy7777** [comment]
Since there is no PR open I am opening a new PR
