### ISSUE TITLE
Confusing error message for empty AtomGroup write

### ISSUE THREAD

**Issue by annalauradelregno** [MDAnalysis/mdanalysis#434]
Hi 

I was trying to print out a selection from a system, and I got the following error message:
```
>>> u = mda.Universe('new.gro')
>>> u.atoms
<AtomGroup with 32668 atoms>
>>> ag = u.select_atoms('name doesntexist')
>>> ag
<AtomGroup with 0 atoms>
>>> ag.write('new2.gro')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/MDAnalysis/core/AtomGroup.py", line 2839, in write
    trj = self.universe.trajectory  # unified trajectory API
AttributeError: 'NoneType' object has no attribute 'trajectory'
```

I eventually figured out it was because my AtomGroup was empty, but the error message could be a lot better here

Thanks

**Comment by dotsdl** [comment]
Agreed. At the very least this requires a simple check that the length of the `AtomGroup` early in the call to `AtomGroup.write`. Will add.
