### ISSUE TITLE
First interaction CI action is failing - review need / implement alternative solution

### ISSUE THREAD

**Issue by IAlibay** [MDAnalysis/mdanalysis#4349]
Looks like it's been going on for a few days: https://github.com/actions/first-interaction/issues

I guess the first question to ask is:

1. Given that we no longer need new contributors to give us their email address for licensing puproses, do we still think this action is still necessary?
2. If the answer is yes, how do we feel about just a simple pygithub implementation?

**Comment by hmacdope** [comment]
Hmmmmmm, thats annoying. IMO its probably not worth re-doing ourselves seeing as we have many other higher priority things to do and we end up having to remind people to do the listed things the time anyway. The main use IMO is to visually remind for a first contribiutor.  I made it to begin with, so if people feel differently, I can try a pygithub implementation.

**Comment by IAlibay** [comment]
> I can try a pygithub implementation.

We've already got an implementation of "raise a comment via pygithub" for the registry, so I (edit here I meant "help with the port", sorry I'm rushing around on a Sunday evening) can just port this over if needed.

**Comment by IAlibay** [comment]
Actually even better - darker bot does exactly that already, it would just need a cut down version with a "is this a newcomer" guard: https://github.com/MDAnalysis/mdanalysis/blob/develop/maintainer/ci/darker-outcomes.py

**Comment by IAlibay** [comment]
Here's a quick example from (edit: work I was doing) elsewhere on how to pull down if someone is a first time contributor, that should hopefully be enough for anyone that might need to implement this:

```
import os
from github import Github
g = Github(os.environ['GITHUB_TOKEN'])
repo = g.get_repo('MDAnalysis/mdanalysis')
pr = repo.get_pull(4348)
pr.raw_data['author_association']
>>> 'FIRST_TIME_CONTRIBUTOR'
pr = repo.get_pull(4346)
pr.raw_data['author_association']
>>> 'FIRST_TIME_CONTRIBUTOR'
pr = repo.get_pull(4345)
pr.raw_data['author_association']
>>> 'MEMBER'
```

**Comment by IAlibay** [comment]
I'm probalby going to tag @jennaswa here - the idea of having some kind of "first interaction" with newcomers to a project is very much a thing that several projects have touted as "good for their community".

Generally folks have advocated for a non-automated interaction, however en lieu of having sufficient time on our hands, this might be the only reasonable solution.

**Comment by IAlibay** [comment]
This seems to be fixed upstream now so I'm closing for now. We can revisit later if we have the spare cycles.
