### ISSUE TITLE
Change benchmarks default python to be >3.8

### ISSUE THREAD

**Issue by hmacdope** [MDAnalysis/mdanalysis#4351]
Benchmarks are currently configured to use python 3.8 by default:

https://github.com/MDAnalysis/mdanalysis/blob/develop/benchmarks/asv.conf.json#L24

 which won't even configure with our minimum in pyproject.toml (3.9) as mentioned in #4346 

With incoming NEP29 change to 3.10 I propose we change to 3.10 as default base for benchmarks. 

What do you think @orbeckst (I know you run a lot of the benchmarks. )

**Comment by orbeckst** [comment]
Sounds good, will look at your PR #4352
