### ISSUE TITLE
pytest --disable-pytest-warnings --pyargs MDAnalysisTests results

### ISSUE THREAD

**Issue by hanahg** [MDAnalysis/mdanalysis#4353]
Hi,
I am tring to installing MDAnalysis by pip.
After installation I try the following command:

pytest --disable-pytest-warnings --pyargs MDAnalysisTests
============================= test session starts ==============================
platform linux -- Python 3.10.12, pytest-7.4.3, pluggy-1.3.0
rootdir: /home/fhaghighi
plugins: hypothesis-6.91.0
collected 18992 items / 7 skipped

and the result:
 18196 passed, 795 skipped, 6 xfailed, 2 xpassed, 6508 warnings in 413.42s (0:06:53) =

I don't know if I should do anything else or that is ok?

Thanks for help

**Comment by IAlibay** [comment]
Hi @hanahg,

This seems like a fine outcome of running the tests :) No further changes are necessary.

If possible would it be possible to ask these types of questions either on our discord or our user mailing list? The issue tracker is more in the realm of "things are broken" (like your previous issue) or "I would like this new feature" and aren't answered by everyone. You will get more folks responding to usability questions on discord/the mailing lists. Please see https://www.mdanalysis.org/#participating for more information.

**Comment by hanahg** [comment]
Thank you ,
even though I installed Jupyter using  "pip install nodejs", it doesn't work:
'jupyter command `jupyter-notebook` not found
