### ISSUE TITLE
Errors due to ```make html```

### ISSUE THREAD

**Issue by HeetVekariya** [MDAnalysis/mdanalysis#4362]
## Expected behavior ##
- When ```make html``` command executed in side ```mdanalysis/package/doc/sphinx``` directory then it must create html for the docs

#### Currently it gives two errors:
1) Due to ```html_static_path```
```bash
Warning, treated as error:
html_static_path entry '_static' does not exist
make: *** [Makefile:42: html] Error 2
```

2) Due to indentation:
```bash
sphinx.errors.SphinxWarning: /home/heet/Work/Development/mdanalysis/package/MDAnalysis/coordinates/FHIAIMS.py:docstring of MDAnalysis.coordinates.base.ProtoReader.timeseries:8:Explicit markup ends without a blank line; unexpected unindent.
```

## Code to reproduce the behavior ##

``` bash
cd mdanalysis/package/doc/sphinx && make html

```

## Current version of MDAnalysis ##

- Which version are you using? (run `python -c "import MDAnalysis as mda; print(mda.__version__)"`)
  - 2.7.0-dev0
- Which version of Python (`python -V`)?
  - Python 3.10.13
- Which operating system?
  - Ubuntu

**Comment by HeetVekariya** [comment]
@lilyminium

- After doing `html_static_path = []` it still gives error like 
```bash

Warning, treated as error:
/home/heet/Work/Development/mdanalysis/package/MDAnalysis/coordinates/FHIAIMS.py:docstring of MDAnalysis.coordinates.base.ProtoReader.timeseries:8:Explicit markup ends without a blank line; unexpected unindent.
make: *** [Makefile:42: html] Error 2
```

should be fixed in the same PR ?
- If yes then please guide me how can i tackle it.

**Comment by lilyminium** [comment]
Ah sure, they're unrelated errors but a fix would be welcome there too, and both of them are likely small fixes. 

> If yes then please guide me how can i tackle it.

To start off with I would google the error and have a look at the specified docstring -- looks like there's something wrong with the docstring of the `MDAnalysis.coordinates.base.ProtoReader.timeseries` method, near-ish the 8th line (as indicated by `MDAnalysis.coordinates.base.ProtoReader.timeseries:8` -- although I usually find that the error is not actually in that line but around it somewhere)

**Comment by HeetVekariya** [comment]
> Ah sure, they're unrelated errors but a fix would be welcome there too, and both of them are likely small fixes.
> 
> > If yes then please guide me how can i tackle it.
> 
> To start off with I would google the error and have a look at the specified docstring -- looks like there's something wrong with the docstring of the `MDAnalysis.coordinates.base.ProtoReader.timeseries` method, near-ish the 8th line (as indicated by `MDAnalysis.coordinates.base.ProtoReader.timeseries:8` -- although I usually find that the error is not actually in that line but around it somewhere)

Update me when you find the solution, i will include it in this PR only with a separate commit.

**Comment by lilyminium** [comment]
Hi Heet,

We generally expect the person who finds the fix to open the PR, as that’s the most straightforward approach — therefore, if you would like to include the fix, we would expect you to find it. I was suggesting there what I would normally do as advice on troubleshooting. You’re welcome to just open a PR with the fix to the `_static` directory if you’d like. However, if you are keen to fix this docstring as well, you could start with the steps I outlined earlier.

Cheers,
Lily

**Comment by HeetVekariya** [comment]
- Sorry @lilyminium for directly asking the solution, it was my mistake.
- You are correct, it is the contributor who have to find the solution for the issue, though he/she can take help from maintainers but should not ask the solution to find for them.

- I have find the code which causes the ```indentation``` error and solved it.
- To tackle both the bugs in one issue, i have updated the issue description.

**Comment by lilyminium** [comment]
Hi @HeetVekariya, no worries at all, our conventions aren't always obvious!  Thank you very much for finding the errors and opening the PR!
