### ISSUE TITLE
Support fancy indexing of trajectory readers

### ISSUE THREAD

**Issue by dotsdl** [MDAnalysis/mdanalysis#437]
It would be really convenient to be able to obtain some kind of timeseries measurement across all frames, filter based on the measurement, and then feed the frame numbers of interest directly to the trajectory reader to visit each of those frames in turn at some later time. For example,

```python
import MDAnalysis as mda
from MDAnalysisTests.datafiles import GRO, XTC
import pandas as pd

u = mda.Universe(GRO, XTC)
protein = u.select_atoms('protein')

# collect data of interest for all frames
rgyr = pd.np.zeros(len(u.trajectory))
time = pd.np.zeros(len(u.trajectory))
frame = pd.np.zeros(len(u.trajectory), dtype=int)

for i, ts in enumerate(u.trajectory):
    frame[i] = ts.frame
    time[i] = ts.time
    rgyr[i] = protein.radius_of_gyration()
    
df = pd.DataFrame({'time': time, 'rgyr': rgyr}, index=frame, columns=['time', 'rgyr'])
```
and then later, using our collected data
```python
# later, iterate through frames for which 
# data of interest fits certain criteria
indices = df[df['rgyr'] < 23].index.values

# this would be awesome
for ts in u.trajectory[indices]:
    # get something else
```

I *think* all this would require is specifying in the `__getitem__` method for the Reader that a non-string iterable should be taken as a sequence of indices to iterate through.

Note that this will only work well in general for sorted indices; for non-sorted or repeated indices, this will only be performant for Readers that support random access.

**Comment by richardjgowers** [comment]
Yeah this sounds sane enough.  And yeah, you just need to mangle `__getitem__` a bit to recognise a sequence of integers.  All readers have a `_read_frame` method which raises NotImplementedError until it's overriden. If I remember right, slicing like [::2] is just converted to a range function which spits out frame indices, so effectively acts like randomly seeking the frames.

**Comment by orbeckst** [comment]
Did #439 close this issue?

**Comment by orbeckst** [comment]
The commit message for #439 says it fixes this issue, so I'll do just that.

**Comment by orbeckst** [comment]
P.S.: @richardjgowers , I think that including #437 forces us to release the next release as 0.12.0 (and not 0.11.1) because that is an API change, not just a fix.
