### ISSUE TITLE
MDAnalysis compilation fails on OSX clang 16 [xdrfile]

### ISSUE THREAD

**Issue by IAlibay** [MDAnalysis/mdanalysis#4397]
This is coming out of the conda-forge runners on osx builds:

```
  MDAnalysis/lib/formats/src/xdrfile.c:2535:3: error: incompatible function pointer types initializing 'unsigned int (*)(XDR *)' (aka 'unsigned int (*)(struct XDR *)') with an expression of type 'int64_t (XDR *)' (aka 'long long (struct XDR *)') [-Wincompatible-function-pointer-types]
                  xdrstdio_getpos,                /* get offset in the stream */
                  ^~~~~~~~~~~~~~~
  MDAnalysis/lib/formats/src/xdrfile.c:2536:3: error: incompatible function pointer types initializing 'int (*)(XDR *, unsigned int)' (aka 'int (*)(struct XDR *, unsigned int)') with an expression of type 'int (XDR *, int64_t, int)' (aka 'int (struct XDR *, long long, int)') [-Wincompatible-function-pointer-types]
                  xdrstdio_setpos,                /* set offset in the stream */
                  ^~~~~~~~~~~~~~~
```

**Comment by hmacdope** [comment]
@IAlibay I will investigate :)

**Comment by hmacdope** [comment]
I wonder if we are building with `-Werror`, ?

**Comment by IAlibay** [comment]
@hmacdope here's the compiler invocation command:

x86_64-apple-darwin13.4.0-clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /Users/runner/miniforge3/conda-bld/mdanalysis_1703722261723/_h_env_placehold/include -fPIC -O2 -isystem /Users/runner/miniforge3/conda-bld/mdanalysis_1703722261723/_h_env_placehold_/include -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -isystem /Users/runner/miniforge3/conda-bld/mdanalysis_1703722261723/_h_env_placehold/include -fdebug-prefix-map=/Users/runner/miniforge3/conda-bld/mdanalysis_1703722261723/work=/usr/local/src/conda/mdanalysis-2.7.0 -fdebug-prefix-map=/Users/runner/miniforge3/conda-bld/mdanalysis_1703722261723/_h_env_placehold=/usr/local/src/conda-prefix -D_FORTIFY_SOURCE=2 -isystem /Users/runner/miniforge3/conda-bld/mdanalysis_1703722261723/_h_env_placehold/include -mmacosx-version-min=10.9 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -I/Users/runner/miniforge3/conda-bld/mdanalysis_1703722261723/work/MDAnalysis/lib/formats -I/Users/runner/miniforge3/conda-bld/mdanalysis_1703722261723/_h_env_placehold/lib/python3.10/site-packages/numpy/core/include -I/Users/runner/miniforge3/conda-bld/mdanalysis_1703722261723/work/MDAnalysis/lib/formats/include -I/Users/runner/miniforge3/conda-bld/mdanalysis_1703722261723/work/MDAnalysis/lib/formats -I/Users/runner/miniforge3/conda-bld/mdanalysis_1703722261723/_h_env_placehold/include/python3.10 -c MDAnalysis/lib/formats/libmdaxdr.c -o build/temp.macosx-10.9-x86_64-cpython-310/MDAnalysis/lib/formats/libmdaxdr.o -std=c99 -O3 -funroll-loops -fsigned-zeros

**Comment by IAlibay** [comment]
Just in case this helps, here's the link to the build section that is failing: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=850127&view=logs&j=9c5ef928-2cd6-52e5-dbe6-9d173a7d951b&t=c66c4975-bbef-551b-2ee6-85005a231b12&l=1242

**Comment by IAlibay** [comment]
Can confirm that sticking to clang 15 avoids the issue: https://github.com/conda-forge/mdanalysis-feedstock/pull/63

In this particular case, unless there are any objections, we'll deploy with clang 15 and we can do a minor patch for clang 16 once it's fixed.

**Comment by hmacdope** [comment]
> Can confirm that sticking to clang 15 avoids the issue: https://github.com/conda-forge/mdanalysis-feedstock/pull/63
> 
> 
> 
> In this particular case, unless there are any objections, we'll deploy with clang 15 and we can do a minor patch for clang 16 once it's fixed.

Sounds good 👌
