### ISSUE TITLE
tempfiles in tests aren't deleted after test

### ISSUE THREAD

**Issue by kain88-de** [MDAnalysis/mdanalysis#440]
The test do not clean up when they are finished. Leading to a full-hard drive when they are run a lot.
During some developing and testing to see when all tests pass it just used up something like 8GB on my root partition. 

This is mostly a problem when replacing/refactoring one of the core components.  It turns into a real problem for people for restart their computer once a month or less.

A solution is to use [tempdir](https://bitbucket.org/another_thomas/tempdir). It has a handy `run_in_tempdir` decorator. That will create a tmp directory and delete it again after the test.

### Test-files that use mkstemp

- [ ] test_atomgroup.py
- [ ] test_modelling.py
- [ ] test_log.py
- [ ] test_mol2.py
- [ ] test_analysis.py (partially done, see #706 )
- [ ] test_streamio.py
- [x] test_coordinates.py [#469]
- [ ] test_altloc.py
- [ ] test_persistence.py
- [ ] test_pdbqt.py

**Comment by richardjgowers** [comment]
I thought we always used tempfile for everything?  Is it that something isn't using this? Or is tempfile not cleaning up properly?

**Comment by kain88-de** [comment]
Nope. We are using `tempfile.mkstemp`. According to the [docs](https://docs.python.org/2/library/tempfile.html) the user is responsible for deleting the file afterwards.

**Comment by richardjgowers** [comment]
Hmmm, so would replacing `mkstemp` with `TemporaryFile` solve this?

**Comment by kain88-de** [comment]
I don't think so. Our API requires to use filename and not file-objects because some of the extensions have their own file-objects implemented (eq the XDR library).  The `tempdir` library would be a nice solution. It's a small tested wrapper around `tempdir`.  It would only be a requirement for the tests not the actual library.

I used it [here](https://github.com/kain88-de/mdanalysis/blob/cython-xdrlib/testsuite/MDAnalysisTests/test_xtc.py).  We just need to add a decorate for functions that write thinks and then forget about temp-dir and files in that function.

**Comment by richardjgowers** [comment]
Yeah I had a read of tempdir and it looks like it's just a nice wrapper around tempfile, so I like it.

**Comment by orbeckst** [comment]
`@run_in_tempdir()` looks sensible. 

@kain88-de , in principle the `tearDown` methods are supposed to be written in such a way that all files are cleaned up but I suppose that automatically created index files  for e.g. xtc are typically not included in the clean up procedure. (A `Reader` method that cleans up an index file might be a sensible addition to the API.)

**Comment by orbeckst** [comment]
@kain88-de , I assigned this issue to you for the time being. Is the required [tempdir](https://bitbucket.org/another_thomas/tempdir) package on PyPi, i.e. can we easily make it a dependency of the `MDAnalysisTests` package?

**Comment by kain88-de** [comment]
Yes it is on PyPi and enabled in the xtc branch.

**Comment by hainm** [comment]
@orbeckst 

What's about this decorator? it works fine with me

https://github.com/hainm/pytraj/blob/master/pytraj/utils/context.py#L7-L14

**Comment by kain88-de** [comment]
@hainm This is the same as the `tempdir` package without tests and the decorator. 

I'd prefer using tempdir since it's less code we have to maintain and it's tested

**Comment by hainm** [comment]
@kain88-de 

yeah, as long as the package ``tempdir`` support bot py2 and 3 (since mdanalysis will target py3 too)

**Comment by kain88-de** [comment]
I created a list at the top with all files which need to be changed to use tempdir
