### ISSUE TITLE
add cython code to coverage report

### ISSUE THREAD

**Issue by kain88-de** [MDAnalysis/mdanalysis#443]
Cython has recently gained support for coverage our of box [1]. It might be worth to have that code covered as well since we aim to replace all CPython-extensions with Cython in the long run.

[1] http://blog.behnel.de/posts/coverage-analysis-for-cython-modules.html

**Comment by richardjgowers** [comment]
Yeah that looks like a good idea.

**Comment by souravsingh** [comment]
I would like to work on the issue.

**Comment by kain88-de** [comment]
@souravsingh sure just assign your self to the issue.

You should also look over the [cython-mailing](https://groups.google.com/forum/#!forum/cython-users) list for any problems that you will encounter. 

Before you try to get a coverage report for MDAnalysis I suggest you create a small test cython project and try to get a working coverage report for your test project. That removes a lot of variables and should speed up testing since the compilation phase will be much shorter.

**Comment by kain88-de** [comment]
https://gitlab.com/logan/cython-template-project

This is an example repository that claims to have the coverage of cython files working. For anybody interested in taking this.

**Comment by orbeckst** [comment]
Maybe this commit [attempt to add coverage](https://gitlab.com/logan/cython-template-project/commit/2f5a260f11d557aae38c3500ab5d9dd98dd0b4fe) in https://gitlab.com/logan/cython-template-project is helpful in that it lists some changes that seem to pertain to getting cython coverage.

**Comment by kain88-de** [comment]
Btw this works very well in combination with pytest See https://github.com/MDAnalysis/pytng

@utkbansal something you can look into after a complete transition to pytest

**Comment by utkbansal** [comment]
@kain88-de Sure

**Comment by richardjgowers** [comment]
https://medium.com/@dfdeshom/better-test-coverage-workflow-for-cython-modules-631615eb197a

**Comment by orbeckst** [comment]
@richardjgowers @seb-buch , is our [codecov](https://codecov.io/gh/MDAnalysis/mdanalysis) able to display the coverage of cython files?

**Comment by seb-buch** [comment]
Based on a test commit (see PR #2032), codecov should be able to handle cython files now (well when the PR is merged). You can see the codecov results for the test commit here: https://codecov.io/gh/seb-buch/mdanalysis/tree/fcff85079d61a6c3e2570965ce570af1930af07b/package/MDAnalysis

As I mentioned in PR #2029, Cython coverage currently flags `cdef` functions/methods and `ctypedef` lines as not covered even if these lines are obviously executed. See for instance [_cutil.pyx](https://codecov.io/gh/seb-buch/mdanalysis/src/fcff85079d61a6c3e2570965ce570af1930af07b/package/MDAnalysis/lib/_cutil.pyx). As consequence the reported coverage rate is lower than what it actually is.

**Comment by orbeckst** [comment]
Hooray! 

Some of the cdefs are apparently counted (show up green). Can you exclude them from coverage reporting until cython/cython#1461 is fixed or should we low-ball coverage??

**Comment by richardjgowers** [comment]
I’ve got a fix for coveragerc waiting, just letting the first commit finish
on travis
