### ISSUE TITLE
In old `AnalysisBase` subclasses, `self._trajectory` is sometimes used instead of `self._sliced_trajectory`

### ISSUE THREAD

**Issue by marinegor** [MDAnalysis/mdanalysis#4432]
## Expected behavior ##
The discussion is here: https://github.com/MDAnalysis/mdanalysis/discussions/4426#discussioncomment-8153049

The conclusion was to fix this behavior in following subclasses (based on `git grep` below) in `MDAnalysis/analysis`:

- ~~bat.py~~
- diffusionmap.py
- ~~hole2/hole.py~~
- ~~hydrogenbonds/hbond_analysis.py~~
- ~~hydrogenbonds/hbond_autocorrel.py~~
- ~~waterdynamics.py~~

EDIT: removed those that are obsolete (like `waterdynamics` and `hole2`, or don't actually iterate in a wrong way (like `bat`, `hbond_analysis`)

**Comment by IAlibay** [comment]
P.S. waterdynamics and hole2 are their own separate repo now - pinging @fiona-naughton and @lilyminium

**Comment by lilyminium** [comment]
Thanks for raising this @marinegor and the ping @IAlibay, I've raised a separate issue in the new repo as a reminder.

**Comment by marinegor** [comment]
Ok, after further inspection, I figured that only `diffusionmap` isn't using it correctly. Others are either obsolete, or do it correctly, or (like `hbond_autocorrel.py`) implement their own `run()` method.

**Comment by IAlibay** [comment]
Just coming back to this one, waterdynamics doesn't use AnalysisBase so shouldn't be affected.
