### ISSUE TITLE
Windows port of MDAnalysis

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/mdanalysis#450]
So far we have not been successful in building MDAnalysis for Windows. #150 explored some of the problems but part of the issue is that none of the core developers seem to be using Windows so that there are few incentives. For the distribution of MDAnalysis it would be very good if we had a binary Windows package available. 

I am looking for suggestions on how to make this happen. This includes questions such as
- What parts of the library are problematic?
- What kind of environment would be needed for development (e.g. Windows versions, compilers, Python distribution, etc) – I could probably provide a properly equipped instance somewhere.
- How is Python used on Windows?
- Can we use e.g. http://www.appveyor.com/ for continuous integration? For hints on how to do this see the Python Packaging [Supporting Windows using Appveyor](http://python-packaging-user-guide.readthedocs.io/en/latest/appveyor/) guide.
- What incentives would _you_ need to work on a Windows port?

**Comment by cing** [comment]
Back when I was commenting on that issue, I did end up compiling everything (it's possible!). At that time I was supervising two students with Windows-only laptops and now those students are gone. So, no need for Windows for me, but someone out there might still be interested?

**Comment by hainm** [comment]
Not sure who is using Windows for analyzing MD data.

**Comment by kain88-de** [comment]
It shouldn't be that much of a problem. mdtraj has an [appveyor build](https://github.com/mdtraj/mdtraj/tree/master/devtools/appveyor-ci). It should be possible for us to use their configuration as well.

**Comment by orbeckst** [comment]
The wiki page [MDAnalysis on Windows](https://github.com/MDAnalysis/mdanalysis/wiki/MDAnalysis-on-Windows) (very much work in progress...) collects recipes on how to get MDAnalysis working under Windows. 

Users should feel free to edit the wiki page.

**Comment by kain88-de** [comment]
I talked with @richardjgowers  We both agree our official standpoint should be we don't support windows and recommend using the windows 10 subsystem until we have a windows dev.

**Comment by orbeckst** [comment]
Just for the future: how to use appveyor https://github.com/rmcgibbo/python-appveyor-conda-example (as referenced from https://conda.io/docs/travis.html )

**Comment by kain88-de** [comment]
The ci-helpers we use also support appveyor.

**Comment by orbeckst** [comment]
Without a windows dev we are not going to spend resources on a Windows port.

Please re-open when we have someone committed to a native windows port.

**Comment by orbeckst** [comment]
For the record: since 0.19.2, Windows is fully supported under Python 3.

@richardjgowers earned a 🍺 for his efforts .

**Comment by kain88-de** [comment]
@tylerjreddy also earned his beer with his continuous work and test
information on windows.

**Comment by orbeckst** [comment]
> 
> 
> @tylerjreddy also earned his beer with his continuous work and test
> information on windows.

Absolutely, the next time I see @tylerjreddy in person I'm happy to pay debts!

(What I referred to was the last push that got the Windows support in the release before the workshop, the last 3% or so that built on all the work primarily by Tyler before.)
