### ISSUE TITLE
MDAnalysisTests.coordinates not included in 2.8.0 dev installation

### ISSUE THREAD

**Issue by ljwoods2** [MDAnalysis/mdanalysis#4507]
## Expected behavior ##

In 2.7.0, base trajectory reader/writer tests can be imported like this after MDAnalysisTests installation (even if installed using pip method described below)

``` python
from MDAnalysisTests.coordinates.base import MultiframeReaderTest
```

## Actual behavior ##

In the current 2.8.0 develop branch, this yields an error:

"from MDAnalysisTests.coordinates.base import (MultiframeReaderTest,
E   ModuleNotFoundError: No module named 'MDAnalysisTests.coordinates'"

This makes it impossible for mdakits that inherit tests from MDAnalysisTests.coordinates.base to test with mda 2.8.0

## Code to reproduce the behavior ##

Develop branch was installed using an identical method to the install-mdanalysis github action (https://github.com/MDAnalysis/install-mdanalysis/blob/main/action.yaml):

```
conda create -n mdatest python=3.10
conda activate mdatest
python -m pip install 'git+https://github.com/MDAnalysis/mdanalysis@develop#egg=MDAnalysis&subdirectory=package'
python -m pip install 'git+https://github.com/MDAnalysis/mdanalysis@develop#egg=MDAnalysisTests&subdirectory=testsuite'
```

I believe the cause of this behavior is the change from setup.py in the testsuite to pyproject.toml

## Current version of MDAnalysis ##

- Which version are you using? (run `python -c "import MDAnalysis as mda; print(mda.__version__)"`)
2.8.0
- Which version of Python (`python -V`)?
3.10.0
- Which operating system?
Ubuntu 22.04
Also occurs on github actions VMs (can hunt down specific versions of each if relevant):
ubuntu-latest
macOS-latest
windows-latest

**Comment by IAlibay** [comment]
I've been looking at this a bit recently and even in fresh installs I can't reproduce this in proper source installs. I'm thinking this might be an issue with the git install.

**Comment by ljwoods2** [comment]
> I've been looking at this a bit recently and even in fresh installs I can't reproduce this in proper source installs. I'm thinking this might be an issue with the git install.

Got it, I got it to work using this:
```
pip install -e 'git+https://github.com/MDAnalysis/mdanalysis@develop#egg=MDAnalysisTests&subdirectory=testsuite'
```
If doing an editable install doesn't make sense for the github action, maybe the action could change to a git clone and then install?

Alternatively, explicitly telling setuptools to look at every single module seems to work (tested on a fork here https://github.com/ljwoods2/mdanalysis/blob/testmodules/testsuite/pyproject.toml)
Though this would definitely add some bloat since there would have to be a line for every single module

```
[tool.setuptools.packages.find]
namespaces = false
include=[
    "MDAnalysisTests",
    "MDAnalysisTests.coordinates",
    "MDAnalysisTests.data",
     ...
```

**Comment by IAlibay** [comment]
> Alternatively, explicitly telling setuptools to look at every single module seems to work

Yeah I saw that on my end too but I'm very reluctant to go with that option. I'll keep digging, there's probably a missing setting somewhere that I'm missing.

**Comment by IAlibay** [comment]
On the editable installs thing:

I personally don't think it's a bad idea to go editable, _however_, I am concerned that this is actually just masking a deeper issue.
If you look at the pip build logs you can see that only `MDAnalysis.data` is being added when doing a VCS install with pip, it's as if  automatic discovery just didn't happen.

**Comment by IAlibay** [comment]
I'm going to have to take a break from this for today, but I suspect something along the lines of #4508 is the fix here - I might have misunderstood what `include` really means / how it interacts with automatic package discovery when applied "strictly".

That being said, I can't seem to be able to reproduce the "old" package discovery issues I had before, I wonder if that's because setuptools has updated since.

**Comment by ljwoods2** [comment]
That makes sense to me, I tested the same and everything seems to be discovered using the default discovery settings. It may even be possible to remove the [tool.setuptools.packages] configuration lines entirely. I was able to do that in my mdakit
