### ISSUE TITLE
AtomGroup.sequence() broken

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/mdanalysis#451]
#385 broke the `AtomGroup.sequence` method:
```python
import MDAnalysis; from MDAnalysis.tests.datafiles import  PDB
u = MDAnalysis.Universe(PDB)
p = u.select_atoms("protein and resid 1-4")
print(p.sequence(format="string"))
```
gives
```
MMMMMMMMMMMMMMMMMMMRRRRRRRRRRRRRRRRRRRRRRRRIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
```
but should actually give
```
MRII
```
(same for the other format options)

**Comment by orbeckst** [comment]
More precisely, it is not documented that one should be using
```python
AtomGroup.residues.sequence()
```
although I would like to be able to say
```python
seq = u.select_atoms("protein").sequence()
```
which seems more natural and is in fact the *[documented behavior](http://www.mdanalysis.org/mdanalysis/documentation_pages/core/AtomGroup.html#MDAnalysis.core.AtomGroup.AtomGroup.sequence)* from 0.10.0

**Comment by richardjgowers** [comment]
I was going to push 0.11.1 tonight, if this is a quick fix I can wait?

**Comment by orbeckst** [comment]
On 28 Sep, 2015, at 18:28, Richard Gowers wrote:

> I was going to push 0.11.1 tonight, if this is a quick fix I can wait?

We have new stuff so this has to be a 0.12.0; with semver we can only put fixes into patch releases. Basically, semantic versioning says that nothing in the API changes in patches but we have e.g. the new occupancy API changes and changes in the analysis.psa.

Can you wait until tomorrow, I'll probably have  this issue fixed tonight.

**Comment by richardjgowers** [comment]
Yep ok to both

**Comment by orbeckst** [comment]
On 28 Sep, 2015, at 18:39, Richard Gowers wrote:

> Yep ok to both

fyi, just pushed an update to the release number and added semver to CHANGELOG.
