### ISSUE TITLE
Running encores with multiple cores

### ISSUE THREAD

**Issue by kmorisa** [MDAnalysis/mdanalysis#4538]
Good morning,

I would like to know if there is anything wrong with:
ces0, details0 = encore.similarity.ces(list(data.values()), ncores=8)
because my dashboard seems to show that only one cpu has been used for the calculation.
I have 32 cpus available.

Thank you.

**Comment by orbeckst** [comment]
This seems to be a duplicate of https://github.com/MDAnalysis/mdaencore/issues/64 so I am closing it.  

Note that ENCORE was moved to its own MDAKit and we will remove it from MDAnalysis itself soon. Thus we are encouraging any discussions/issue to be at https://github.com/MDAnalysis/mdaencore/

**Comment by orbeckst** [comment]
@kmorisa please go to https://github.com/MDAnalysis/mdaencore/issues/64 and hopefully the ENCORE maintainers can contribute to the discussion and find a solution.

**Comment by kmorisa** [comment]
Yes, that is exactly what I am experiencing.
Thank you for your guidance.

**Comment by orbeckst** [comment]
As detailed in the referenced issue, parallelization is only about different parameters and not per ensemble. Thus, the reported behavior is normal.

**Comment by kmorisa** [comment]
Thank you for letting me know, and I understand!
