### ISSUE TITLE
upgrade TPR reader for Gromacs 5.x

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/mdanalysis#456]
The TPR reader does not read Gromacs 5.x input files but @jbarnoud started this work (as announced on the [developer list](http://developers.mdanalysis.org))

> I am updating the TPR parser to support the pbx100 format produced by gromacs 5. My current version passes the unit tests, and it can read the gromacs 5 TPR file I wanted MDAnalysis to read. The unit tests for the TPR parser test TPR files produced by versions of gromacs from 4.0 to 4.6.1; I would like to add tests for TPR files produced with more recent versions of gromacs. Ideally, I would like these TPR files to be produced using inputs as close as possible as the inputs used for the already existing tests. Yet, I do not find what input files were used. Could anybody point me toward these files?

I don't have the input files for the 2lyz or ab42 tprs but perhaps @zyxue (who wrote the TPR reader) can provide them, e.g. as an attachment to this issue?

Otherwise, try @richardjgowers 's suggestion (which seems to work for me):
```
echo System | gmx convert-tpr -s ab42_gmx_4.6.1.tpr -o ab42_gmx_5.0.5.tpr
```

**Comment by zyxue** [comment]
Sorry, but I cannot find the original gro files anymore. I think any structure file should be fine as long as you know the number of molecules and atoms in it. The particular system you use to generate a tpr file shouldn't matter much.

**Comment by jbarnoud** [comment]
On 29/09/15 20:15, zyxue wrote:
>
> Sorry, but I cannot find the original gro files anymore. I think any 
> structure file should be fine as long as you know the number of 
> molecules and atoms in it. The particular system you use to generate a 
> tpr file shouldn't matter much.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/MDAnalysis/mdanalysis/issues/456#issuecomment-144141999>.
>
I used Richard Gowers's suggestion to use `gmx convert-tpr` and it 
worked. I have some cleaning to do and I will submit a pull request.
