### ISSUE TITLE
Package tests failing due to normalilzation change

### ISSUE THREAD

**Issue by IAlibay** [MDAnalysis/mdanalysis#4573]
## Expected behavior ##

CI passes

## Actual behavior ##

CI fails in the sdist build & pip install checks because the package tarball is being normalized to lower case rather than the actual package name, i.e. "mdanalysis.tar.gz" instead of "MDAnalysis.tar.gz".

**Comment by RMeli** [comment]
Fixed by https://github.com/MDAnalysis/mdanalysis/pull/4572
