### ISSUE TITLE
Geometric definition of hydrogen bonds similar to gmx bond

### ISSUE THREAD

**Issue by remaker789** [MDAnalysis/mdanalysis#4626]
I found the geometric definitions of hydrogen bonds is different between MDAnalysis and gmx hbond, especially the angle. MDAnalysis uses the D-H-A angle, however, gmx hbond uses the H-D-A angle. The difference in angle may result in different counts of hydrogen bonds in MDAnalysis and gmx hbond.

**Comment by orbeckst** [comment]
Hello @remaker789 , yes, that's true. There are different, equally valid definitions of H-bonds. Presumably you could convert between the two definitions?

Is there anything specific that you would consider a bug in MDAnalysis or in the docs? What should happen?

**Comment by remaker789** [comment]
Thanks for your reply. There is no bug in MDAnalysis. Indeed I preferred to use the definition of hydrogen bonds of `gmx hbond`, so I have changed some codes of the file `MDAnalysis\analysis\hydrogenbonds\hbond_analysis.py` to achieve the similar definition of hydrogen bonds as `gmx hbond`.

**Comment by orbeckst** [comment]
Ok, good to know that this works for you. 

I’m closing this issue because there’s nothing specific for us to do but please feel free to open it again (or open a new one) if you think something needs to be done.
