### ISSUE TITLE
MDAnalysis.analysis module not available

### ISSUE THREAD

**Issue by juliasubbotina** [MDAnalysis/mdanalysis#4627]
## Problem ##
Hello, I am trying to do a fresh installation of  `MDAnalysis`. I tried different options (pip, conda, from git for dev.2.8.), but had the same outcome - no `mda.analysis` module available.  
 `conda install  MDAnalysis -c MDAnalysis`
Dependencies - the most recent versions, complied with `mdanalysis `distribution.  Working from my specified conda environment. 

What can be the issue?

## Actual behavior ##
`python -c "import MDAnalysis as mda; print(mda.analysis)"`

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'MDAnalysis' has no attribute 'analysis'
```
![Screenshot 2024-06-28 110346](https://github.com/MDAnalysis/mdanalysis/assets/82937099/8211a3af-57b4-4acf-9c3c-96b2594963dd)

## Version, system parameters ##

- Which version are you using? (run `python -c "import MDAnalysis as mda; print(mda.__version__)"`)
_2.7.0_
- Which version of Python (`python -V`)?
_Python 3.12.4_
- Which operating system?
 _x86_64 GNU/Linux 
Red Hat Enterprise Linux Server 7.9 (Maipo)_

**Comment by yuxuanzhuang** [comment]
Hi! Analysis modules in MDAnalysis are not imported by default. You need to explicitly import the desired module, for example: `from MDAnalysis.analysis import rms`

**Comment by juliasubbotina** [comment]
Thanks, this worked.
