### ISSUE TITLE
`fetch_mmtf` no longer works

### ISSUE THREAD

**Issue by IAlibay** [MDAnalysis/mdanalysis#4634]
## Expected behavior ##

Calling `fetch_mmtf` will return an MMTF of the provided PDB entry.

## Actual behavior ##

Calling `fetch_mmtf` leads to the following error:

```python
URLError: <urlopen error [Errno -2] Name or service not known>
```

## Why ##

As of the 2nd of July 2024, the PDB no longer services MMTF files, which means that attempts at retreiving such files no longer works.

## Suggested path forward ##

My suggestion would be to remove the `fetch_mmtf` method and deprecate the MMTF Reader as no longer relevant.

## Current version of MDAnalysis ##

- Which version are you using? (run `python -c "import MDAnalysis as mda; print(mda.__version__)"`) develop
- Which version of Python (`python -V`)? 3.10+
- Which operating system? Any

**Comment by RMeli** [comment]
Thanks @IAlibay, the suggested path forward sounds sensible to me.

**Comment by orbeckst** [comment]
Yes, I agree.

I would like to remove MMTFReader but on the off-chance that some has actual mmtf files they want to read, they get fair warning.

**Comment by orbeckst** [comment]
Removing MMTF also helps us with relicensing https://www.mdanalysis.org/2023/09/22/licensing-update/#removing-apache-20-dependencies
