### ISSUE TITLE
BLD: build failure with Python 3.13.0rc1 free-threaded

### ISSUE THREAD

**Issue by tylerjereddy** [MDAnalysis/mdanalysis#4651]
With Python `3.13.0rc1` out and ABI-stable I did some initial checks of our build status. We currently fail to build with Cython `3.1.0a0` (needed for free-threaded support) for the exact same reason as https://github.com/scikit-learn/scikit-learn/issues/28977. 

I confirmed this patch allows us to build, bumping our C lang standard to `C11`. Any objections to doing that or known reasons we can't do it? That's basically how they dealt with it upstream, albeit in a different build system.

```diff
--- a/package/setup.py
+++ b/package/setup.py
@@ -259,7 +259,7 @@ def extensions(config):
     use_openmp = config.get('use_openmp', default=True)
     annotate_cython = config.get('annotate_cython', default=False)
 
-    extra_compile_args = ['-std=c99', '-O3', '-funroll-loops',
+    extra_compile_args = ['-std=c11', '-O3', '-funroll-loops',
                           '-fsigned-zeros'] # see #2722
     define_macros = []
     if config.get('debug_cflags', default=False):
```

I'll try to take a look at the tests after that.

**Comment by hmacdope** [comment]
:+1:  thanks @tylerjereddy C11 is bog standard now, I think we can move forward changing the std. I am not sure if we need to change MSVC standard flag also (not even sure if we set them).
