### ISSUE TITLE
MAINT: a few mutable default arguments are back

### ISSUE THREAD

**Issue by tylerjereddy** [MDAnalysis/mdanalysis#4655]
Oli dealt with this 9 years ago in gh-590, but a few cases have accumulated since then. It is fairly low priority but easy to fix.

Can check locally with i.e., `ruff.toml` like this:

```
[lint]
ignore = ["E501"]
select = ["B006", "B008"]
```

`ruff check package`

Some obscure bug happened because of this in another project so I just thought of it again.

**Comment by Plomo-02** [comment]
Hello, can I be assigned to this issue?

**Comment by RMeli** [comment]
@Plomo-02 we do not assign issues. Since there is no other open PR against this issue, feel free to work on it and open a PR when you are ready for review.

**Comment by tanishy7777** [comment]
I have tried to fix this issue in the above PR (#4810). Please let me know if any further changes are to be made for this issue. 
@RMeli @tylerjereddy
