### ISSUE TITLE
`MDAnalysis.analysis.distances`: Implement parallelization or mark as unparallelizable

### ISSUE THREAD

**Issue by marinegor** [MDAnalysis/mdanalysis#4661]
Given a newly implemented parallelization (https://docs.mdanalysis.org/dev/documentation_pages/analysis/parallelization.html), implement it for all classes in `analysis.distances` module. You may use `analysis.RMSD` example in `develop` as a reference.

You need to add:

 - appropriate implementation of result aggregation for AnalysisBase subclasses in `analysis.distances` module
 - a boilerplate fixture(s) to `testsuite/analysis/conftest.py`, analogous with existing ones
 - a client_ fixtures to all tests using in `testsuite/MDAnalysisTests/analysis/test_distances.py`, and modify the way run() method is called

**Comment by talagayev** [comment]
What is the procedure if it does not have `AnalysisBase` subclasses, which would be the case here for `analysis.distances`. Should `analysis.distances` be rewritten to have an `AnalysisBase` subclass?

**Comment by marinegor** [comment]
@talagayev imo the rewrite should happen in a separate PR (and there could be also a respective issue). Apart from that, I think it'd be a good contribution :)

**Comment by talagayev** [comment]
@marinegor Agree, makes sense to first rewrite it in a PR, and the in the follow up PR make the implementation of the parallelization, thanks for the reply :)

**Comment by orbeckst** [comment]
See #4817 — these functions do not need to care about parallelization or AnalysisBase.
