### ISSUE TITLE
Array dimensions error during parallelization testing

### ISSUE THREAD

**Issue by talagayev** [MDAnalysis/mdanalysis#4685]
Currently the testing of parallelization delivers an error during the testing of `test_dihedral_single_frame` due to the len of the arrays.

This issue appears in #4682 

## Expected behavior ##

The expected behavior would be a successful passing of the test. 

## Actual behavior ##

Currently this error appears:

`test_dihedrals.py::TestDihedral::test_dihedral_single_frame[client_Dihedral0] - ValueError: all the input array dimensions except for the concatenation axis m...`

## Code to reproduce the behavior ##

This pytest present in #4682 reproduces the error:

``

``` python

    def test_dihedral_single_frame(self, atomgroup, client_Dihedral):
        dihedral = Dihedral([atomgroup]).run(start=5, stop=6, **client_Dihedral)

....

```

## Current version of MDAnalysis ##

- Which version are you using?  2.8.0-dev0
- Which version of Python? 3.12.5
- Which operating system? Linux

**Comment by orbeckst** [comment]
If `n_frames < n_workers` we get empty arrays that don't combine nicely.

Probably best approach is to reduce the workers.

**Comment by orbeckst** [comment]
@marinegor do you have thoughts on to how to best address this issue?

**Comment by marinegor** [comment]
@orbeckst @talagayev my guess would be that it's not `vstack` that you need for aggregation but `hstack`, which is invariant to the first dimension (frame number, in this case) of stacked arrays with angles.

I mean here: https://github.com/MDAnalysis/mdanalysis/blob/09e29c8c9d5f7fd51a406bca618bcc269c35afec/package/MDAnalysis/analysis/dihedrals.py#L459

**Comment by RMeli** [comment]
I think n_workers > n_frames doesn't make much sense. I think it would be best to automatically set n_workers = n_frames and print a warning.

**Comment by marinegor** [comment]
Agreed
