### ISSUE TITLE
Documenting guessed attributes

### ISSUE THREAD

**Issue by IAlibay** [MDAnalysis/mdanalysis#4696]
## Current status

All populated attributes, including guessed ones are listed directly in the Reader documentation. This is a convenient place to look at "what do I expect to get (and how) when I use this Reader for my Universe".

## After PR #3753 

After this PR, Reader docs no longer list guessed attributes.

## The ask

Since we will keep guessed by default attributes until 3.0, ideally we need to inform our users of what they should expect. This could take various forms:

1. We could just list the guessed attributes again in the Reader docs (i.e. "These attributes are also guessed on Universe creation")
2. We could mention that there will be attributes guessed at Universe creation time and link to som guesser docs
3. Something else

cc @lilyminium

**Comment by lilyminium** [comment]
My vote for a combination 1+2 -- move the type and mass guessing to a general guessing doc (that is linked to from each parser page?), and keep any other individually guessed attributes in the separate Parser pages for now. This would hopefully make it easier to update as well as guesser behaviour changes in 3.0.

**Comment by IAlibay** [comment]
> that is linked to from each parser page?

My vote would be to do this if possible - it may just be me but I rely heavily on the reader API docs for "what will I get on universe creation and where did it come from". So linking from there would be great.
