### ISSUE TITLE
Warn about and deprecate element guessing in ITP parser

### ISSUE THREAD

**Issue by IAlibay** [MDAnalysis/mdanalysis#4698]
## Behaviour post #3753 

In #3753 element guessing is added to the ITP parser in order to partially guess masses.

## Intended behaviour

Ideally we want:
1. To make sure users are aware of any guessing that happens
2. With 3.0+, remove any automatic guessing

## Proposal

We add a DeprecationWarning on ITP element guessing that lets users know that this behaviour is happening, and that it will go away in 3.0.

cc @lilyminium

**Comment by lilyminium** [comment]
Agreed, this is basically a workaround to ensure current behaviour consistency but it's a painful one.
