### ISSUE TITLE
New guesser interface broke behaviour downstream

### ISSUE THREAD

**Issue by IAlibay** [MDAnalysis/mdanalysis#4748]
Several mdakits' CI broke overnight with the following error: ValueError: there is no reference attributes in this universeto guess types froma

This means that the new guessers interface did a breaking change that we aren't aware of.

This will need to be fixed before the 2.8 release.

**Comment by lilyminium** [comment]
I'm just out but can look at this in an hour or so!

**Comment by IAlibay** [comment]
Prolif also fails because we removed the guessers interface: ModuleNotFoundError: No module named 'MDAnalysis.topology.guessers'

**Comment by IAlibay** [comment]
Similarly pytim fails because it attempts to call `guess_types` but it no longer exists: https://github.com/MDAnalysis/MDAKits/actions/runs/11422930196/job/31781508635#step:10:33

**Comment by IAlibay** [comment]
cc @Marcello-Sega - this is where we're tracking the breaking changes from the guessers update: https://github.com/MDAnalysis/MDAKits/issues/217

**Comment by IAlibay** [comment]
I have raised #4749, #4750, and #4751 as issues that need fixing before the release.

**Comment by orbeckst** [comment]
@lilyminium and @IAlibay I put both your names on this omnibus issue as the two people with best insight into what needs to be done.

You also already created PRs addressing _all_ the sub-issues (thank you!) so I assigned the issues to the PR authors so that it's clear that we are actively working on the problems.

Please ask for help where needed.

**Comment by orbeckst** [comment]
I created the post https://github.com/MDAnalysis/mdanalysis/discussions/4758 as an official note.

**Comment by IAlibay** [comment]
This is now done as far as I know.
