### ISSUE TITLE
Expose tables under topology for 2.x

### ISSUE THREAD

**Issue by IAlibay** [MDAnalysis/mdanalysis#4753]
Related to #4748 

## Expected behavior ##

In a non-API breaking release, I would expect to find the things I used to use in the same place, unless it was a bug and/or a DeprecationWarning had been raised for a while.

## Actual behavior ##

MDAnalysis.topology.tables no longer exists in the current develop.

## Proposal ##

We add it back with a warning.

**Comment by lilyminium** [comment]
+1, sounds good to me, following the same logic as in #4751

**Comment by orbeckst** [comment]
Can we also add a `DeprecationWarning`, given that it will go away and people seem to be using it directly?
