### ISSUE TITLE
Unclear Error When Using to_guess=['bonds'] with Existing Bonds in Topology

### ISSUE THREAD

**Issue by yuxuanzhuang** [MDAnalysis/mdanalysis#4759]
## Expected Behavior ##

The `to_guess=['bonds']` option should work correctly even when bonds are already present in the topology. If bonds exist, the function should either skip guessing or provide an appropriate message, unless `force_guess` is explicitly set.

## Actual Behavior ## 

When attempting to use the new guesser with bonds already present in the topology, an unclear error message occurs:

`AttributeError: 'NoneType' object has no attribute 'level'`

This error does not provide sufficient information about the underlying issue.

## Code to reproduce the behavior ##

``` python
import MDAnalysis as mda
from MDAnalysis.tests.datafiles import CONECT

u = mda.Universe(CONECT, to_guess=['bonds'])

> AttributeError: 'NoneType' object has no attribute 'level'

u = mda.Universe(CONECT, force_guess=['bonds'])
print(u.atoms.bonds)
> <TopologyGroup containing 1922 bonds>

```

## Current version of MDAnalysis ##

- Which version are you using? (run `python -c "import MDAnalysis as mda; print(mda.__version__)"`) 
2.8.0-dev0
- Which version of Python (`python -V`)?
3.11
- Which operating system?
MacOS

**Comment by lilyminium** [comment]
Hmm, I think conceptually one should be able to guess bonds/angles/dihedrals etc. in the `to_guess` list, and have the behaviour differ from `force_guess` -- where MDA adds the guessed items additively with `to_guess`, and replaces existing bonds etc with `force_guess`. Thoughts? I prototyped something in #4761 but uncovered another bug in #4762
