### ISSUE TITLE
delete_bonds not deleting all bonds

### ISSUE THREAD

**Issue by lilyminium** [MDAnalysis/mdanalysis#4762]
## Expected behavior ##

If I call `u.delete_bonds(u.bonds)`, I expect all bonds to be deleted.

## Actual behavior ##

This doesn't always happen. If I had to guess where to look, it'd be in `_Connection._delete_bonds` where there's some indexing logic that could be error-prone. 

## Code to reproduce the behavior ##

``` python
>>> import MDAnalysis as mda
>>> from MDAnalysis.tests.datafiles import PDB_conect
>>> u = mda.Universe(PDB_conect)
>>> u.bonds
<TopologyGroup containing 8 bonds>
>>> u.delete_bonds(u.bonds)
>>> u.bonds
<TopologyGroup containing 1 bonds>
>>> u.delete_bonds(u.bonds)  # second time's the charm
>>> u.bonds
<TopologyGroup containing 0 bonds>
```

## Current version of MDAnalysis ##

- Which version are you using? (run `python -c "import MDAnalysis as mda; print(mda.__version__)"`) develop
- Which version of Python (`python -V`)? 3.10.12
- Which operating system? ARM Mac

**Comment by lilyminium** [comment]
Another:

```
>>> import MDAnalysis as mda
>>> from MDAnalysis.tests.datafiles import CONECT
>>> u.atoms.bonds
>>> u = mda.Universe(CONECT)
>>> u.bonds
<TopologyGroup containing 72 bonds>
>>> u.delete_bonds(u.bonds)
>>> u.bonds
<TopologyGroup containing 72 bonds>
```

**Comment by IAlibay** [comment]
@lilyminium since this is blocking #4759 - is this a blocker for the release?

**Comment by lilyminium** [comment]
I think so... otherwise I can't test properly :/ unless I write the test to be incorrect on purpose.

**Comment by IAlibay** [comment]
> I think so... otherwise I can't test properly :/ unless I write the test to be incorrect on purpose.

Ok thanks, I've added it to the milestone.
