### ISSUE TITLE
`ModuleNotFoundError: No module named 'pybtex' ` when running `make doctest`

### ISSUE THREAD

**Issue by Syedmahmood777** [MDAnalysis/mdanalysis#4826]
# Expected Behaviour
When running the make doctest command, all doctests should execute successfully without errors, provided that all necessary dependencies are installed. The dependencies listed on the website or documentation should include all required modules for running the tests.

# Actual Behaviour
Running make doctest raises a `ModuleNotFoundError` indicating that the pybtex module is not found. This prevents the doctest from completing as expected. Additionally, pybtex is not mentioned in the list of requirements provided on the website or documentation, which makes it unclear that this module is necessary for running doctests.

` There is a programmable error in your configuration file:`  
`Traceback (most recent call last):  
  File "C:\Users\WELCOME\Envs\mdanalysis-dev\Lib\site-packages\sphinx\config.py", line 529, in eval_config_file
    exec(code, namespace)  # NoQA: S102`  
   ` File "C:\Users\WELCOME\Downloads\md\mdanalysis\package\doc\sphinx\source\conf.py", line 19, in <module>  from pybtex.style.formatting.unsrt import Style as UnsrtStyle`  
    
`ModuleNotFoundError: No module named 'pybtex'`

# Reproduce Issue  
To reproduce the issue:
1. Go to `package/doc/sphinx`
2. Run `make doctest`

# Current Versions
- MDAnalysis version: 2.9.0-dev0
- Python version: Python 3.12.2
- Operating system: Windows 10

Contributes to [DOC] doctest MEGA-issue #3925

**Comment by orbeckst** [comment]
I am looking at https://userguide.mdanalysis.org/stable/contributing_code.html#building-mdanalysis and there the package *sphinxcontrib-bibtex* is included. Does that one have *pybtex* as a dependency?

**Comment by orbeckst** [comment]
In our CI we explicitly install *pybtex* for building docs https://github.com/MDAnalysis/mdanalysis/blob/f4e0f0b695419eab7ae169310069e91579667d58/.github/workflows/gh-ci.yaml#L172 so it seems to be necessary.

@Syedmahmood777 where did you look to learn what you need to install for creating the docs and run the doc tests?

**Comment by Syedmahmood777** [comment]
Apologies for raising the request, it was a fault on my side.

**Comment by orbeckst** [comment]
@Syedmahmood777 don't worry. I'd still be interested to hear where you looked? Our docs _should_ make it possible for contributors to run the tests and if they don't then we want to know so that we can improve them. Thus, feedback such as yours is very valuable!

**Comment by Syedmahmood777** [comment]
@orbeckst I went through [Contributing to the main code on MDAnalysis](https://userguide.mdanalysis.org/stable/contributing_code.html) to set up the environment, but ran `make doctests` without installing docutils dependencies.  

When the above error popped up, I checked contributing docs (link above) which didn't have pybtex mentioned explicitly, hence why I raised the issue.
