### ISSUE TITLE
MDAnalysis.analysis.density.convert_density() method has an invalid default unit value

### ISSUE THREAD

**Issue by recombinatrix** [MDAnalysis/mdanalysis#4829]
## Expected behavior ##

This is a small one.  Some of the methods in `MDAnalysis.analysis.density` have invalid defaults.

`density.convert_density()` has a default of `unit='Angstrom'`, but this is not a permitted value.  As a result, if  `density.convert_density()` is run with no options specified, it fails with an error.  From the documentation, I suspect the permitted default would be `unit='Angstrom^{-3}'`

## Code to reproduce the behavior ##

```
from MDAnalysis.analysis.density import DensityAnalysis
u = Universe(TPR, XTC) # some universe with a thing you want to measure, in my case I was looking at sodium ions but I've used water for the example.
ow = u.select_atoms("name OW")
D = DensityAnalysis(ow, delta=1.0)
D.run()
D.density.convert_density()
```

expected outcome:  it runs a density calculation

actual outcome:  

```
ValueError: The name of the unit (Angstrom supplied) must be one of:
dict_keys(['Angstrom^{-3}', 'A^{-3}', 'Å^{-3}', 'nm^{-3}', 'nanometer^{-3}', 'Molar', 'SPC', 'TIP3P', 'TIP4P', 'water'])
```

## Current version of MDAnalysis ##

MDAnalysis 2.7.0
Python 3.10.14
Ubuntu 20.04.4

**Comment by Sanskriti0805** [comment]
hello , shall i work upon this one ?

**Comment by tanishy7777** [comment]
@recombinatrix  I think that the issue seems to be specific to the `convert_density()` function, and I’ve addressed it in my PR. Please let me know if you’re aware of any other functions with a similar issue.

**Comment by RMeli** [comment]
> hello , shall i work upon this one ?

Hi @Sanskriti0805. We don't assign issues to people, you are free to open on open issues that interest you. You can open a PR solving an issue, and we will look at it. In this case, however, @tanishy7777 was rather quick in opening a PR for this issue (https://github.com/MDAnalysis/mdanalysis/pull/4833) and we review on a first-come-first-served basis based on PRs.
