### ISSUE TITLE
ResidueGroup and SegmentGroup __repr__ should give number of elements, not full list

### ISSUE THREAD

**Issue by dotsdl** [MDAnalysis/mdanalysis#486]
It would be more consistent with `AtomGroup.__repr__` if `ResidueGroup.__repr__` and `SegmentGroup.__repr__` gave the total number of elements represented instead of a full listing of these elements. Although the number of segments might always be pretty small, the number of residues can be quite a lot, especially for larger protein systems.

Thoughts?

**Comment by richardjgowers** [comment]
Haha yeah, accidentally repring a large ResidueGroup is sometimes a little painful.  I think just displaying len would be a better solution, and maybe an even better solution would be to copy numpy style and show contents for small RGs, and `....` if they're long.

**Comment by orbeckst** [comment]
numpy style would be nice; but as a quick fix using len() seems ok. I am swayed by the consistent look and feel.

**Comment by orbeckst** [comment]
Only one thing [to say](https://www.youtube.com/watch?v=-ZxHAZChcYU).

**Comment by dotsdl** [comment]
This is fixed in #363, fyi.
