### ISSUE TITLE
remove generated html docs from repo/tarball?

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/mdanalysis#491]
Should we continue to
- keep the sphinx-generated HTML docs inside revision control (i.e., inside the git repo)
- package them with the release tar ball

Since the developer docs are automatically pushed and always available at http://devdocs.mdanalysis.org it does not seem that important that one always pulls them into one's local repo.

Bundling the docs with the release tar ball increases the size of the tarball but we are not even installing the docs (or the examples) anywhere with a typical `pip install MDAnalysis` so it seems dead-weight at the moment for most people. And the release docs are always at http://docs.mdanalysis.org .

**Comment by tylerjereddy** [comment]
As we recently discussed, I don't think the html docs that a user / developer builds locally should be placed under version control. `git status` produces a huge mess then, and I know that `scipy` doesn't version control the docs `build` directory, which means less git manipulation for me when testing things out.

**Comment by richardjgowers** [comment]
Yep, I'm with @tylerjereddy We can include a zip of the docs alongside the github release, pypi gets the docs uploaded manually already.

**Comment by orbeckst** [comment]
Ok, so we will remove the docs from git. @tylerjereddy do you want to do this? Just grab the issue (I assigned it to me accidentally due to fat fingers on a tiny phone screen...)

We still have to decide if we want to bundle the docs. Perhaps leave them out for the next release and bring them back if someone complains?? I suppose that repackagers might actually want to have the docs so that they can be included into eg a deb or rpm. Or make sure that 
```
python setup.py build_sphinx
```

actually works.

**Comment by dotsdl** [comment]
Something to consider: we only have the docs for the *current* release available online. I think it would be useful to host the docs for previous releases as well in the same place, if we can. I know this can be done, and many sphinx themes support it(?) but I don't know where to start to set that up.

**Comment by orbeckst** [comment]
@rmcgibbo mentioned somewhere how they set up their doc generation to keep multiple versions for mdtraj. IIRC, it basically boiled down to storing the docs in separate sub directories corresponding to releases and latest and then editing the paths into the theme files. It requires work.

We would need to use a sphinx theme that supports the switching or add it ourselves or add a simple  landing page to select the version of interest (although given that the state of the art seems to be a js menu as in the RTD theme, users would probably expect fancy menu instead of clicking a boring link).  But all of this is a separate issue from this one.

**Comment by dotsdl** [comment]
> But all of this is a separate issue from this one.

Agreed. I think this makes sense as something we do post-1.0, and isn't really a priority right now.

**Comment by kain88-de** [comment]
> I suppose that repackagers might actually want to have the docs so that they can be included into eg a deb or rpm

Generating the docs from the sphinx sources can be easily added to the package build process (at least for deb). So I don't think we need to worry to much about that.

**Comment by tylerjereddy** [comment]
Does `python setup.py build_sphinx` actually work in the project root at the moment? It doesn't for me.
Furthermore, building docs the "old" way with `make html` in the sphinx source folder gives me this traceback:

```
  1 # Sphinx version: 1.2.2
  2 # Python version: 2.7.6
  3 # Docutils version: 0.11 release
  4 # Jinja2 version: 2.7.1
  5 # Loaded extensions:
  6 Traceback (most recent call last):
  7   File "/Users/treddy/Library/Python/2.7/lib/python/site-packages/sphinx/cmdline.py", line 253, in main
  8     warningiserror, tags, verbosity, parallel)
  9   File "/Users/treddy/Library/Python/2.7/lib/python/site-packages/sphinx/application.py", line 107, in __init__
 10     confoverrides or {}, self.tags)
 11   File "/Users/treddy/Library/Python/2.7/lib/python/site-packages/sphinx/config.py", line 229, in __init__
 12     execfile_(filename, config)
 13   File "/Users/treddy/Library/Python/2.7/lib/python/site-packages/sphinx/util/pycompat.py", line 105, in execfile_
 14     exec code in _globals
 15   File "conf.py", line 99, in <module>
 16   File "/Users/treddy/github_projects/mda_doc_adjustment/mdanalysis/package/MDAnalysis/__init__.py", line 151, in <module>
 17     from .lib import log
 18   File "/Users/treddy/github_projects/mda_doc_adjustment/mdanalysis/package/MDAnalysis/lib/__init__.py", line 30, in <module>
 19     from . import distances  # distances relies on mdamath
 20   File "/Users/treddy/github_projects/mda_doc_adjustment/mdanalysis/package/MDAnalysis/lib/distances.py", line 40, in <module>
 21     from ._distances import (calc_distance_array,
 22 ImportError: No module named _distances
```
 What's going on here? Does anyone routinely compile docs locally and does `make html` work for them?

If we can resolve that, then it is also worth noting that there are various ways to "untrack" git files. My current suggestion is to use `git rm --cached -r html`, and there may be an argument for adding an entry to .gitignore as well, or even putting a new .gitignore inside html/ to preserve that folder but prevent tracking of internal files. Conversely, there are also arguments in favour of using something like `git update-index --assume-unchanged [path]`.

**Comment by richardjgowers** [comment]
Sphinx needs to see the compiled Cython modules as well to grab their docs.  I've been building the docs from a developer install (`python setup.py develop`) which builds the extensions next to the source.  There's probably a neater way where you tell Sphinx where the installed MDAnalysis lives.

I didn't know build_sphinx was a thing before

**Comment by rathann** [comment]
Hi, Fedora packager here. Please document a working way to build the docs or a downloadable HTML docs tarball for the current (and past, preferably) release.

**Comment by richardjgowers** [comment]
https://github.com/MDAnalysis/mdanalysis/wiki/WritingDocumentation#build-the-docs-with-sphinx

This should do it, you'll need to do a develop build (so the .so files are next to the source) otherwise you'll get errors in building the docs.

We do upload a tarball of the docs to pypi (which becomes http://pythonhosted.org/MDAnalysis/) but I can't see where you can download this?

**Comment by rathann** [comment]
Thanks. Plain `python setup.py develop` wasn't working for me in the buildroot, but adding `-d $PWD` did the trick. Of course, a downloadable tarball would limit the required build dependencies (sphinx and napoleon extension) and save a bit of build time.
