### ISSUE TITLE
visualization.streamplot Documentation Display Issues

### ISSUE THREAD

**Issue by tylerjereddy** [MDAnalysis/mdanalysis#497]
The streamplot visualization modules are not showing up in the development docs (i.e., http://www.mdanalysis.org/mdanalysis/documentation_pages/visualization/streamlines.html).

The same modules are exhibiting new formatting issues (i.e., look at the parameter names) in the release docs (i.e., http://pythonhosted.org/MDAnalysis/documentation_pages/visualization/streamlines.html).

I am not sure how widespread these issues are, but the streamplotting modules I wrote seem to be more harshly affected than some others. I do remember writing them in a numpy-style that was a bit different than much of the rest of MDA, but they rendered quite nicely at the time. As there was additional discussion of pushing in numpy-style direction recently it may not be unreasonable to expect that these should render properly.

Anyways, for now just pointing this out.

**Comment by richardjgowers** [comment]
So the release docs are built locally and uploaded to Pypi manually, and the dev docs are built on travis automagically, so I think it's probably the travis doc build not working

**Comment by kain88-de** [comment]
About the numpy style issues. I think that is a problem with the chosen Sphinx template but I haven't looked into it.

**Comment by orbeckst** [comment]
Hm, in the current development docs the streamlines do not render at all: http://www.mdanalysis.org/mdanalysis/documentation_pages/visualization/streamlines.html

@tylerjereddy , you could also update the citation – it's your paper :-).

**Comment by orbeckst** [comment]
Other numpy-style docs render fine, e.g., I recently re-wrote the [hole docs](http://www.mdanalysis.org/mdanalysis/documentation_pages/analysis/hole.html) and paid extra attention to the Style Guide and they render fine.

**Comment by tylerjereddy** [comment]
The linked hole docs don't render that well for me in Safari (see below). Are there really supposed to be asterisks around the parameter names visible in the html? I think argument categories like 'parameters' are supposed to be bannered / highlighted in the html render as well, although that's probably less crucial.


<img width="1029" alt="hole" src="https://cloud.githubusercontent.com/assets/7903078/18609762/24db98d2-7d02-11e6-8059-366ea991f248.png">

If we compare that html render with a nice example from the scipy library, I think you'll agree they have it cleaner:

<img width="865" alt="vor" src="https://cloud.githubusercontent.com/assets/7903078/18609821/fe2dd528-7d02-11e6-86df-286a550ee079.png">

**Comment by richardjgowers** [comment]
I think there's superfluous `*` around the variable names that aren't needed to make things bold.  The timestep docs seem to render well and follow the numpy style in the source

http://pythonhosted.org/MDAnalysis/documentation_pages/coordinates/base.html#MDAnalysis.coordinates.base.Timestep

**Comment by tylerjereddy** [comment]
Ah, those are a bit better, although the general look is basically the same, at least in my browser.

**Comment by orbeckst** [comment]
If you look at the 0.16.0 docs you will see that the hole docs were completely adapted to NumPy style and render ok http://www.mdanalysis.org/mdanalysis/documentation_pages/analysis/hole.html

The sphinx style determines how headings such as parameters are shown, eg as banners. 

Feel free to hack the style or propose a new one. I would, however, like to keep the color scheme consistent with the logo---branding (and at least it does not look like RTD). 

--
Oliver Beckstein
email: orbeckst@gmail.com

**Comment by tylerjereddy** [comment]
I can't reproduce the development doc build problem on my local machine (i.e., the streamplot module shows up after `make html` with a local development build). Do we have a specific reason for using a separate build process for release vs. development docs? Shouldn't the processes be identical beyond the branch that is used for the source files? There's obviously something I don't fully understand there.

Do we, by default, generate and retain the detailed logs for the html documentation build process for both release and development docs, or can we at least temporarily enable that on a side branch or something? Looking through a typical travis log (including the raw text option) doesn't seem to reveal too much. I can find the `make html` command in the `.travis.yml` and that does look the same for both master and development branches.

**Comment by kain88-de** [comment]
@tylerjereddy the line is [here](https://github.com/MDAnalysis/mdanalysis/blob/37d107ef260b82ad17a75cf89f528900bf3223ae/.travis.yml#L81). I can't reproduce the problem locally in a new conda environment either using the travis commands. This is kind of strange. I also don't see anything in the deploy script why that wouldn't be picked up.

**Comment by orbeckst** [comment]
When I try to build the docs locally I fail to import the gridData package (even though it's pip-installed) and then sphinx fails to import the density module and thus the density docs are not built. When I try to run tests or use the density module then it works just fine. That is just to say that sometimes weird things appear to happen under sphinx so it might well be that the visualization module fails to import under sphinx and then the docs will not be generated.

For testing on travis you probably need to change the logic in the `.travis.yml` file so that the docs are generated even for a PR but then make sure to comment out the `deploy_docs.sh` call. 

> Do we have a specific reason for using a separate build process for release vs. development docs? Shouldn't the processes be identical beyond the branch that is used for the source files? 

Mostly history — MDAnalysis predates pretty much every modern CI environment and as you know, only things get done that someone spends some time on implementing... For instance, for the longest time RTD was not an option because it couldn't build our C-extensions and so we decided to have travis build our development docs and host them as GitHub pages. The RTD docs shortcomings might have changed but no-one could be bothered to the check it out because the current process mostly works. The release docs have been hosted on PyPi since the beginning and that is a manual process... or at least it used to be. I am sure it could be automated somehow, e.g., using Travis for deployment as well.

**Comment by orbeckst** [comment]
Just fyi: just tried buildin docs in a fresh virtual env with pip and failed to build streamplot docs because matplotlib was missing – check that this ever gets installed on travis.

```
/Volumes/Data/oliver/Biop/Library/python/mdanalysis/package/doc/sphinx/source/documentation_pages/visualization/streamlines.rst:4: WARNING: autodoc: failed to import module u'MDAnalysis.visualization.streamlines'; the following exception was raised:
Traceback (most recent call last):
  File "/Users/oliver/.virtualenvs/mdanalysis/testing/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 529, in import_object
    __import__(self.modname)
  File "/Volumes/Data/oliver/Biop/Library/python/mdanalysis/package/MDAnalysis/visualization/__init__.py", line 24, in <module>
    import streamlines
  File "/Volumes/Data/oliver/Biop/Library/python/mdanalysis/package/MDAnalysis/visualization/streamlines.py", line 35, in <module>
    '2d streamplot module requires: matplotlib.path for its path.Path.contains_points method. The installation '
ImportError: 2d streamplot module requires: matplotlib.path for its path.Path.contains_points method. The installation instructions for the matplotlib module can be found here: http://matplotlib.org/faq/installing_faq.html?highlight=install
/Volumes/Data/oliver/Biop/Library/python/mdanalysis/package/doc/sphinx/source/documentation_pages/visualization/streamlines_3D.rst:4: WARNING: autodoc: failed to import module u'MDAnalysis.visualization.streamlines_3D'; the following exception was raised:
Traceback (most recent call last):
  File "/Users/oliver/.virtualenvs/mdanalysis/testing/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 529, in import_object
    __import__(self.modname)
  File "/Volumes/Data/oliver/Biop/Library/python/mdanalysis/package/MDAnalysis/visualization/__init__.py", line 24, in <module>
    import streamlines
  File "/Volumes/Data/oliver/Biop/Library/python/mdanalysis/package/MDAnalysis/visualization/streamlines.py", line 35, in <module>
    '2d streamplot module requires: matplotlib.path for its path.Path.contains_points method. The installation '
ImportError: 2d streamplot module requires: matplotlib.path for its path.Path.contains_points method. The installation instructions for the matplotlib module can be found here: http://matplotlib.org/faq/installing_faq.html?highlight=install
```

**Comment by orbeckst** [comment]
I think the first full build – it's based on the travis run number, see .travis.yml file.

> On 23 Dec, 2016, at 17:09, Max Linke <notifications@github.com> wrote:
> 
> @orbeckst what setup is used for the docs build minimal or full I can't see that locking at the travis yaml. If the minimalis used then some packages are missing that are needed to build the docs.

--
Oliver Beckstein * orbeckst@gmx.net
skype: orbeckst  * orbeckst@gmail.com

**Comment by kain88-de** [comment]
I just checked the docs appear again

**Comment by orbeckst** [comment]
Thanks for checking, didn't have the time to do it.

Fröhliche Weihnachten!

> On 26 Dec, 2016, at 00:09, Max Linke <notifications@github.com> wrote:
> 
> I just checked the docs appear again
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

--
Oliver Beckstein * orbeckst@gmx.net
skype: orbeckst  * orbeckst@gmail.com
