### ISSUE TITLE
analysis.density does not work with .XTC files

### ISSUE THREAD

**Issue by ldomic** [MDAnalysis/mdanalysis#504]
I am using MDAnalysis version 0.12.1-dev and tried to use analysis.density module on XTC trajectory.

    u = mda.Universe("md.gro", "md.xtc")
    D = density_from_Universe(u, delta=1.0, atomselection="resname CHOL")

It runs fine for a while and then throws out the following error:
``` cython
Histograming   7400 atoms in frame    96/101  [ 95.0%]

Histograming   7400 atoms in frame    98/101  [ 97.0%]

Histograming   7400 atoms in frame   100/101  [ 99.0%]

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-135-51c377b2462d> in <module>()
      1 u = mda.Universe("no_water.gro", "no_water_all.xtc")
----> 2 D = density_from_Universe(u, delta=1.0, atomselection="resname CHOL")

/Users/lauradomicevica/.local/lib/python2.7/site-packages/MDAnalysis-0.12.1.dev0-py2.7-macosx-10.5-x86_64.egg/MDAnalysis/analysis/density.pyc in density_from_Universe(universe, delta, atomselection, metadata, padding, cutoff, soluteselection, use_kdtree, **kwargs)
    518         grid += h  # accumulate average histogram
    519     print("")
--> 520     n_frames = u.trajectory.n_frames / u.trajectory.skip
    521     grid /= float(n_frames)
    522 

AttributeError: 'XTCReader' object has no attribute 'skip' ```

**Comment by orbeckst** [comment]
I thought @richardjgowers had fixed that recently in #490 ? Have you recently pulled from the develop branch?

**Comment by orbeckst** [comment]
P.S.: @ldomic – you manage to run MDAnalysis in Mac OS X 10.5? – so I am not the one using the oldest Mac OS X ... 10.6.8

**Comment by richardjgowers** [comment]
You need 0.13.0dev to get the fix for this.  A work around is setting `u.trajectory.skip = 1`

**Comment by tylerjereddy** [comment]
And just to be clear for an end user--I think this means you'd basically have to `git clone` from the link on the github page for MDAnalysis and then setup with something like:
```
python setup.py build
python setup.py install --user
```

**Comment by ldomic** [comment]
Updating to 0.13.0dev using the method described above by @tylerjereddy fixed the issue. 

@orbeckst No, this computer is 10.10.5 (not quite El Capitan yet). I had much more problems installing MDAnalysis on my Linux machine than on the Mac.

**Comment by kain88-de** [comment]
@ldomic could you elaborate on the problems you had with Linux, maybe even in a separate bug. Don't know if we can fix them bug it doesn't hurt to try

**Comment by tylerjereddy** [comment]
@kain88-de Those issues were described on the mailing list (https://groups.google.com/forum/#!msg/mdnalysis-discussion/IuChgqXJIVQ/k6JHI0Th58AJ) but never resolved. Seemed to be a problem with `conda` or disk space on that particular machine rather than something MDAnalysis-specific. I'll close this issue now, but another can be opened for that other problem if appropriate. I'm sure @ldomic would appreciate suggestions to fix that problem if you've seen it before though.
