### ISSUE TITLE
When should a writer need an `n_atoms` argument?

### ISSUE THREAD

**Issue by kain88-de** [MDAnalysis/mdanalysis#511]
I noticed a little inconsistency in the arguments a writer can be initialized with. For example in the XYZ format it is the `n_atoms` argument for the writer it optional, while the XTC/DCD writer explicitly want to have one. Which is the preferred default?

Another thing is the `<any reader>.Writer` generally also seems to have an optional `n_atoms` kwarg. With the readers atom number as default.  Could we maybe opt to say that for `<any reader>.Writer` we never accept the n_atoms kwarg and instead setup the writer the topology defined in the reader?

**Comment by richardjgowers** [comment]
I've not played with the Writer code much, but I thought `n_atoms` was always required.  I can't really think of a case where you'd need a Writer but couldn't say how many atoms you're writing.  Unless some formats support a changing number of atoms?

For the second point, I think the idea there is you can get a Writer that matches units etc. for writing a subsection of the trajectory.  Like writing a system without the solvent.

**Comment by kain88-de** [comment]
This means  `coordinates.<XXX>Writer(fname)` should fail normally, expect for formats like PDB, XYZ, GRO? 

As for the second part. Currently we have to write.

```python
u = mda.Universe(topo, raw_traj)
sel = u.select_atoms('protein')
with u.trajectory.writer('processed_traj', n_atoms=sel.n_atoms()) as w:
    for ts in u.trajectory:
         w.write(sel)
```

But wouldn't it be more natural to have an API like this?

```python
u = mda.Universe(topo, raw_traj)
sel = u.select_atoms('protein')
with u.trajectory.writer('processed_traj', sub_selection=sel) as w:
    for ts in u.trajectory:
         w.write(sel)
```

**Comment by richardjgowers** [comment]
Yeah it should fail without any indication of size afaik.

It wouldn't be hard to accept either an int or AG?

**Comment by kain88-de** [comment]
Ok then I add a test that the normal writer fails when only no `n_atoms` keyword is given. And I think the other part should be a separate bug to track it (but yeah it should possible to allow an AtomGroup and int).

**Comment by orbeckst** [comment]
I think I can close this, given #517.
