### ISSUE TITLE
Amber ncdf writing does not preserve data types from input

### ISSUE THREAD

**Issue by tylerjereddy** [MDAnalysis/mdanalysis#518]
As originally observed in #506, if MDAnalysis reads an input `.ncdf` file with `float` data types for `coordinates` and `time` values, the writer will output a larger `.ncdf` file using the `double` data type for those two parameters. Other data types appear to be preserved.

As I'm not an AMBER user I don't know much about the range of precisions that are permitted for the binary files, but if both `float` and `double` are allowed in the standard, then MDAnalysis should probably write the output in the same precision as the input. Alternatively, a flag might be specified for this? This all depends on what the standard is and what the devs think would be reasonable behaviour.

There could also be other issues with the writing process, but this is the most obvious problem I could find that would explain the inflated file size of `.ncdf` files written by MDAnalysis.

**Comment by richardjgowers** [comment]
I think currently all data is forced into float32 type by all Readers, so I don't think we can actually write "real! float64 data out.

**Comment by tylerjereddy** [comment]
@richardjgowers Yeah, the prevalence of `9999` style repeats might imply some type of floating point truncation thing?

input file  -----------------------------------   | --------------------      output file  ----------------------------------------
<img width="708" alt="resized_float_ncdf" src="https://cloud.githubusercontent.com/assets/7903078/10916669/7899e888-8254-11e5-9a18-f31c856eb160.png">

**Comment by richardjgowers** [comment]
Yeah it's essentially just made up by numpy.  

It'd be good to have a kwarg to specify precision, with the default being float32.

**Comment by orbeckst** [comment]
For a start, just properly writing float32 (without a kwarg) would be a very acceptable solution.

Thanks @tylerjereddy for looking into this!
