### ISSUE TITLE
MOL2 writing of modified AtomGroup coords writes original coords

### ISSUE THREAD

**Issue by dotsdl** [MDAnalysis/mdanalysis#521]
Loading a mol2 topology+coords, modifying the positions of the atoms, and then writing out again with the AtomGroup yields the original coords, not the modified ones. This example shows the behavior:

```python
import MDAnalysis as mda
from MDAnalysisTests.datafiles import mol2_molecule

u = mda.Universe(mol2_molecule)

u.atoms.positions += 1
newpos = u.atoms.positions

u.atoms.write('newpos_attempt.mol2')
(u.atoms.positions == newpos).all()                  # yields false; positions got re-read from file


u_att = mda.Universe('newpos_attempt.mol2')
(u_att.atoms.positions == newpos).all()             # yields false; positions got re-read from file before written
```

The problem occurs in [MDAnalysis.coordinates.MOL2, line 316](https://github.com/MDAnalysis/mdanalysis/blob/f9eb342b9365c19ec6d703e39829590ed7f7b09e/package/MDAnalysis/coordinates/MOL2.py#L316), where the trajectory reader is told to go to the current frame, thus losing the modified positions.

Thanks to @ppxasjsm for finding this one.

**Comment by richardjgowers** [comment]
Yeah that `write` function is just nuts.. It's meant to just do one frame, so should be inside a loop to do a trajectory.

Seems pretty major, you on it @dotsdl or want me to?

**Comment by dotsdl** [comment]
I've got this. Just going to make the write method do what it should and only write the current timestep.

**Comment by kain88-de** [comment]
@dotsdl While you are at it. Care to port the tests to the new base reader/writer tests?

**Comment by dotsdl** [comment]
Yes. :D

**Comment by richardjgowers** [comment]
@kain88-de is spreading his new religion everywhere!

**Comment by kain88-de** [comment]
@richardjgowers like the test as much as I do just admit it.

@dotsdl thanks.  You can mark it off later in #516

**Comment by orbeckst** [comment]
Just note that according to #227 there are severe limitations on the MOL2 writer, i.e. it might not pass all the tests in the Gospel of @kain88-de .

**Comment by orbeckst** [comment]
@jandom , I think the MOL2 code is pretty much your baby  (and I assume that @dotsdl would not mind getting help, given the amount of other non-MDA stuff that I tend to heap on him... ask him one day how I am being referred to in his Acknowledgement slides...) so if you still know the code you might be able to get a fix rolling?

**Comment by dotsdl** [comment]
Happy to hand this off to @jandom if you want it. :D

**Comment by dotsdl** [comment]
Hey @jandom, are you interested in tackling this one? I think it *might* be an easy fix, but porting the tests to the new scheme may be a little more involved (not sure).

**Comment by jandom** [comment]
@dotsdl @richardjgowers sorry for lack of response, thank you so much for tackling this one guys!
