### ISSUE TITLE
coveralls misses most of the files

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/mdanalysis#527]
@richardjgowers's [answer to my question why coverage fell to 85%](https://groups.google.com/d/msg/mdnalysis-devel/BZlpaDb6VXU/3Ke6hztgAwAJ) is that coveralls only recognizes a paltry 13 source files at the moment. But it's not clear why and how to fix it.

**Comment by orbeckst** [comment]
Something bad with unicode, see e.g. https://travis-ci.org/MDAnalysis/mdanalysis#L3622 : 
```
MDAnalysis.py   NotPython: Couldn't parse '/home/travis/miniconda/envs/pyenv/lib/python2.7/site-packages/MDAnalysis/__init__.py' as Python source: 'encoding declaration in Unicode string' at line 0
MDAnalysis/coordinates/CRD.py   NotPython: Couldn't parse '/home/travis/miniconda/envs/pyenv/lib/python2.7/site-packages/MDAnalysis/coordinates/CRD.py' as Python source: 'encoding declaration in Unicode string' at line 0
```

and *many* more like those. Perhaps an update in condas??

**Comment by kain88-de** [comment]
Which 13 files are recognized by coveralls? `file` should be able to tell us if there is a difference in encoding these files are saved in.

**Comment by orbeckst** [comment]
As a note: When I do `python setup.py sdist` for MDAnalysisTests then the tests under `analysis/*.py`  are not apparently included, possibly because `analysis/__init__.py` is missing. I think this should be added (and we exclude `analysis` and `visualization` from coverage via `.coveragerc` (#286)).

**Comment by richardjgowers** [comment]
The files that are included in the coverage report are all missing the line:
`# -*- Mode: python; tab-width: 4; indent-tabs-mode:nil; coding:utf-8 -*-`

**Comment by orbeckst** [comment]
On 13 Nov, 2015, at 20:42, Richard Gowers wrote:

> The files that are included in the coverage report are all missing the line:
> # -*- Mode: python; tab-width: 4; indent-tabs-mode:nil; coding:utf-8 -*-

According to PEP-whatever this is (or used to be) how you flag files with the proper encoding.

And it worked for a long time so I suspect that something changed in conda/coveralls.

**Comment by kain88-de** [comment]
AFAIK this is still the case. This is also the only way I know to let the old python 2.7 interpreter know that utf-8 symbols are in the source file. My best guess would also go into the direction of conda/coveralls.

@orbeckst [PEP 263](https://www.python.org/dev/peps/pep-0263/)

**Comment by richardjgowers** [comment]
Yeah, not saying that's the problem, just that's the pattern we're seeing.

**Comment by orbeckst** [comment]
@richardjgowers I made you issue owner because you have been looking into this recently (thanks!) but this should not discourage anyone else trying to solve this major annoyance.
It's always very frustrating when things break even though you haven't changed anything...

**Comment by kain88-de** [comment]
So I think I coveralls has problems with UTF-8 Characters. Files with UTF-8 characters which my OS recognizes as UTF8 won't get parsed by coveralls

**Comment by orbeckst** [comment]
@kain88-de 's PR #582 will solve the problem by working around a likely bug in `coverage` but before merging we need to know if the change creates a problem for `vi`/`vim` users in that they might not automatically recognize files as utf-8 encoded anymore. See #582 for details. Feedback from `vi` users is needed.
