### ISSUE TITLE
set_resids should propagate to Residue dynamically

### ISSUE THREAD

**Issue by tylerjereddy** [MDAnalysis/mdanalysis#531]
As it stands, using `set_resids()` will only update the resids of underlying `atom` objects. For the new resids to propagate up the object chain to the `Residue` objects themselves, one has to reselect from the `universe`, which (I would argue) doesn't feel very pythonic. There is a warning about this behaviour in the MDAnalysis documentation (http://pythonhosted.org/MDAnalysis/documentation_pages/core/AtomGroup.html?highlight=set_resids#MDAnalysis.core.AtomGroup.ResidueGroup.set_resids). The fact that resids have topology implications and can lead to undesirable merging of residues probably makes this issue more important. When building a system I had to resort to manually setting the `Residue.id` before realizing that the "intended" approach was to reselect from the universe again to update the resids of the residue objects.

The basic explanation for this sort of behaviour at the above warning and elsewhere in the MDAnalysis docs (i.e., `MDAnalysis.Merge()` examples, etc.) relates to the way MDAnalysis builds the residues up internally. Conversely, if I can manually set `Residue.id` without reselecting from the universe, would it really be that hard to make this behaviour the default when changing the resids of the underlying atoms?

Example:

``` python
import MDAnalysis
from MDAnalysis.tests.datafiles import GRO, XTC

u = MDAnalysis.Universe(GRO, XTC)
first_ten_residues = u.select_atoms('all').residues[:10]

first_ten_residues.resids
#array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

new_resids = first_ten_residues.resids + 50
new_resids
#array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60])

for index, residue in enumerate(first_ten_residues):
    residue.set_resids(new_resids[index])

first_ten_residues.resids # how many users intuitively expect this to remain unchanged?
#array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

first_ten_residues[0].resids
#array([51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51,
       51, 51])

u.select_atoms('all').residues[:10].resids
#array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60])
```

**Comment by orbeckst** [comment]
Is this vaguely related to things discussed in #424 ? 

You could try adding something to the `set_resid()` method that also updates `self`, at least then the behavior would make a bit more sense.

In think other "older" ResidueGroups will simply not update and contain stale information. Short of registering all ResidueGroups that are ever made and keeping track of them in a registry in their Universe or always rebuilding ResidueGroups I can't think of a solution that would do that --- and both of these solutions are pretty awful.

**Comment by richardjgowers** [comment]
This should get fixed with the new system

**Comment by orbeckst** [comment]
@richardjgowers should this get the **solved by 363** seal?

**Comment by richardjgowers** [comment]
@orbeckst yes because the only residue info an Atom carries is which Residue it belongs to (as the index of the Residue), any further info lives in the Residue only.

**Comment by richardjgowers** [comment]
Staleness of resids is gone now 363 has merged, although you'd need to set via the residuegroup. 

```python
u = mda.Universe(GRO, XTC)

rg = u.atoms.residues[:10]

new_resids = rg.resids + 50

rg.resids = new_resids

# Check the resid according to atoms
u.atoms[:10].resids
array([51, 51, 51, 51, 51, 51, 51, 51, 51, 51], dtype=int32)

```
