### ISSUE TITLE
LeafletFinder fails on numpy sort error

### ISSUE THREAD

**Issue by mnmelo** [MDAnalysis/mdanalysis#533]
I ran into a bug in which the `leaflet.LeafletFinder` raises a `ValueError: axis(=-1) out of bounds` because a `np.sort` is attempted on a set object:
``` python
return [np.sort(component) for component in NX.connected_components(self.graph)]
```
I can reproduce it by hand:
``` python
import numpy as np
testset = set([1,1,2,2,3,3,4,4])
np.sort(testset)

---------------------------------------------------------------------------
/usr/local/lib/python2.7/dist-packages/numpy/core/fromnumeric.pyc in sort(a, axis, kind, order)
    817     else:
    818         a = asanyarray(a).copy(order="K")
--> 819     a.sort(axis, kind, order)
    820     return a
    821 

ValueError: axis(=-1) out of bounds
```

I guess that this must be a newly introduced bug/feature in the numpy I'm running (1.10.1) since LeafletFinder always has worked fine for me, and there have been no recent changes to this part of its code.

The easy fix is to convert the set to a list prior to sorting, but I wonder if I'm missing something...
``` python
np.sort(list(testset))
array([1, 2, 3, 4])
```

**Comment by richardjgowers** [comment]
https://groups.google.com/forum/#!topic/mdnalysis-discussion/U16Ja00UQMQ

I think this is the same as @philipwfowler saw here.

I guess it doesn't hurt to put in the list call to fix this?

**Comment by mnmelo** [comment]
Ah, sorry I missed that, only searched the issues opened here. It is indeed the same, and we all come to the conclusion it must have been something on numpy's side (I guess the way a set is handled?)

I'm submitting that quick fix, together with a test for the leaflet finder, which was missing entirely.

**Comment by mnmelo** [comment]
I noticed the analysis directory wasn't being installed by setup.py. I fixed it by adding an empty __init__.py to it. Was it an oversight or did we really want to keep it out?

**Comment by richardjgowers** [comment]
I think it might be because analysis has extra dependencies (scipy etc)

**Comment by mnmelo** [comment]
Ah, missed/forgot that discussion. I'll add the test but leave the `__init__.py` out, then.
