### ISSUE TITLE
residue label  methods:  Residue.label() and ResidueGroup.labels()

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/mdanalysis#540]
When working with proteins, you often want to quickly use a label for residues, such as R10 or D164 (in 1-letter amino acid codes) or Arg10 or Asp164 (with 3-letter codes). Such labels are especially nice as DataFrame column names.

It would be convenient to have something like

``` python
res = universe.select_atoms("protein")
res.labels()  # --> ["M1", "G2", "G3", "R4", ...]
res[1].label() # --> "G2"

res.labels(long=True)  # --> ["Met1", "Gly2", "Gly3", "Arg4", ...]
res[1].label(long=True) # --> "Gly2"
```

Code similar to the following could be added to `core.AtomGroup.ResidueGroup`.

``` python
shortlabels = ["{0}{1}".format(MDAnalysis.lib.util.convert_aa_code(resname), resnum) for resname, resnum in zip(self.resnames, self.resnums)]
longlabels = ["{0}{1}".format(resname, resnum) for resname, resnum in zip(self.resnames, self.resnums)]
```
- Would this be generally useful? 
  - Yes.
- How to deal with non-amino acid residues? Just put `X` or `UNK` or the actual resname? 
  - `X`, `UNK` (PDB/IUPAC convention)
- Make it an array.
- Decide if it might be better as two managed properties, `label` and `shortlabel` (instead of a method with a kwarg).
  - managed properties seem more intuitive; names are up for debate
  - (However, a method could take additional options such as `uppercase=True` to give `["MET1", "GLY", "GLY3", "ARG4", ...]` or `separator=" "` to give `["Met 1", "Gly 2", "Gly 3", "Arg 4", ...]` — how common are these use cases??)

If there's support then this would be an easy project for someone who wants to contribute.
## References
- [IUPAC Amino Acid Abbreviations](http://www.ncbi.nlm.nih.gov/Class/MLACourse/Modules/MolBioReview/iupac_aa_abbreviations.html)

**Comment by dotsdl** [comment]
I think we could make a `TopologyAttr` for this. Should be pretty straightforward, though it would depend on `resname` and `resid` being defined.

Next question: would it depend on `resid` or `resnum`? This is where it might be a big complicated. :/

**Comment by orbeckst** [comment]
Is there an advantage to use a `TopologyAttr` over generating it dynamically?
I would make it depend on `resnum` by default; use of `resnum` vs `resid` could be determined by a kwarg `use="resnum"` or `use="resid"`: another reason why I would make it a method.

**Comment by richardjgowers** [comment]
We could add it as a method attached to a TopologyAttr, I've been making
these work with masses recently. They start in the TA but get transplanted
into the AtomGroup on init, so they could use either resid or resnum.

**Comment by orbeckst** [comment]
I'll take your comments as an "implement with the new topology system" ;-).

**Comment by orbeckst** [comment]
I removed the "easy" label because as it stands, it requires working on #363. 

(@mnmelo just advised a potential GSoC applicant not to dig into this issue for this very reason so by removing the tag we shouldn't have to do this again.)

**Comment by orbeckst** [comment]
Not much enthusiasm here so I am closing. If anyone is interested, raise it from the dead!
