### ISSUE TITLE
misleading setup message

### ISSUE THREAD

**Issue by hainm** [MDAnalysis/mdanalysis#541]
I accidentally tried to install MDA in python3. This is the error I got

```
*** package "numpy" not found ***
MDAnalysis requires a version of NumPy (>=1.5.0), even for setup.
Please get it from http://numpy.scipy.org/ or install it through your package manager.
make: *** [install] Error 255
```

There are two imports here: https://github.com/MDAnalysis/mdanalysis/blob/develop/package/setup.py#L157-L161

```python
        import __builtin__
        __builtin__.__NUMPY_SETUP__ = False
        import numpy as np
    except ImportError:
        print('*** package "numpy" not found ***')
```

**Comment by mnmelo** [comment]
Sorry, I was lazy when doing that first import. Shall I wrap it in a `try:` `except:` too and submit a PR?

**Comment by richardjgowers** [comment]
Yeah you can, it'll help py3k eventually happen.  I'm not sure we can really see if it works besides py3 installation failing at a later point though
