### ISSUE TITLE
GRO file reader fails with certain .gro files

### ISSUE THREAD

**Issue by CharlieLaughton** [MDAnalysis/mdanalysis#548]
After updating from MDAnalysis 0.11.0 to 0.12.1, certain .gro files give an error when loaded:
```
>>> import MDAnalysis as mda
>>> print mda.version.__version__
0.12.1
>>> u = mda.Universe("protein.gro")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/pazcal/Library/Python/2.7/lib/python/site-packages/MDAnalysis/core/AtomGroup.py", line 3790, in __init__
    self.load_new(coordinatefile, **kwargs)
  File "/Users/pazcal/Library/Python/2.7/lib/python/site-packages/MDAnalysis/core/AtomGroup.py", line 4339, in load_new
    trj_n_atoms=self.trajectory.n_atoms))
ValueError: The topology and GRO trajectory files don't have the same number of atoms!
Topology number of atoms 2495
Trajectory: protein.gro Number of atoms 2494
>>> 
```
The error is not consistent - some .gro files are read fine, others are not. The error message is always equivalent (one more atom when the file is read as a topology compared to when it is read as a trajectory, and the former number is the wrong one). The error does not happen using earlier releases of MDAnalysis.

An example of a .gro file that fails is attached (with .txt extension added to permit upload).
[Protein.gro.txt](https://github.com/MDAnalysis/mdanalysis/files/41703/Protein.gro.txt)

**Comment by tylerjereddy** [comment]
Confirmed -- also holds true in `0.13.0-dev0`

**Comment by richardjgowers** [comment]
Ok on it

**Comment by richardjgowers** [comment]
So what's happening is that it's reading the box information at the bottom as an atom.  I think this might be because the box format in this file seems to be different to what Gromacs would write (this file seems to have an extra column)

```
# BEFORE
    7.64092    7.91768    7.31922
# AFTER (now works)
   7.64092   7.91768   7.31922
```

Either way it should still work, so I'll fix this asap.

**Comment by orbeckst** [comment]
Thanks @richardjgowers --- the [GRO file format specs](http://manual.gromacs.org/current/online/gro.html) do indeed say that the box information is "free format, with space separated reals".
