### ISSUE TITLE
tests for analysis are not run on Travis (?)

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/mdanalysis#552]
From looking at e.g. the latest develop test on travis https://travis-ci.org/MDAnalysis/mdanalysis/builds/92784144 I don't see any of the tests in `analysis/test_*.py` running. I searched for "test_hbo" and "test_psa" in the page but could not find it.

Any idea why? Is it because they are not picked up in the `analysis` subdirectory?

**Comment by hainm** [comment]
have you tried locally?
