### ISSUE TITLE
Create preliminary benchmarks for topology parsing

### ISSUE THREAD

**Issue by dotsdl** [MDAnalysis/mdanalysis#555]
We need a quick way of testing our work on the topology refactor, which can later evolve into a more fully-fleshed out benchmarking suite for testing future development. For now, this can simply be a Jupyter notebook, but we should look into more mature frameworks such as [vbench](https://github.com/pydata/vbench).

**Comment by orbeckst** [comment]
Realistically, I don't see this happening... in any case, we are all happy with the new topology system and we have some initial benchmarks in @dotsdl 's notebook that exists as a gist https://gist.github.com/dotsdl/0e0fbd409e3e102d0458 .

**Comment by tylerjereddy** [comment]
@orbeckst 

I've used [asv](https://github.com/spacetelescope/asv) a lot for development work with scipy. It seems to work quite well. Perhaps we can discuss a little when I'm visiting. It wouldn't run as part of CI, but might be useful to evaluate i.e., PRs for specific portions of the code base and eventually prevent regressions as the performance tests grow to 'cover' more stuff.
