### ISSUE TITLE
spurious test failures

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/mdanalysis#556]
Tests started failing somewhat randomly as mentioned in the post  [mdnalysis-devel: spurious test failures](https://groups.google.com/d/msg/mdnalysis-devel/dP4N0F8nhlo/gUrfxSoRCgAJ)

**Without reliable unit tests, our development workflow is severely hampered. This needs to be fixed** but I have no idea how.

## Details ##

See https://travis-ci.org/MDAnalysis/mdanalysis/builds/94270229 for an example. All failures are in the coordinate tests and are of the form 

```
  File "/home/travis/miniconda/envs/pyenv/lib/python2.7/site-packages/MDAnalysisTests/coordinates/base.py", line 198, in test_get_writer_container 
    with tempdir.in_tempdir(): 
  File "/home/travis/miniconda/envs/pyenv/lib/python2.7/contextlib.py", line 17, in __enter__ 
    return self.gen.next() 
  File "/home/travis/miniconda/envs/pyenv/lib/python2.7/site-packages/tempdir.py", line 44, in in_tempdir 
    old_path = os.getcwd() 

OSError: [Errno 2] No such file or directory 
```

and the common theme appears to be **tempdir.in_tempdir()**.

## Initial discussion ##
Initial reports/discussion about these test failures started at https://github.com/MDAnalysis/mdanalysis/issues/551#issuecomment-161134129 and should continue here. 

On 1 Dec, 2015, at 17:10, @hainm wrote:

> it's better to run the test in single core to debug.

Maybe we should try `--processes=1` just to avoid any opportunity for race conditions. It is suspicious that tempdir.in_tempdir() appears to be always involved.

> How's about
>
>   cd  testsuite/MDAnalysisTests/coordinates
>   python test_netcdf.py

`python test_netcdf.py` does not do anything.

`./mda_nosetests coordinates/test_netcdf.py` works fine in serial or parallel. The whole 3300+ tests pass locally, with up to 24 threads... most of the time. When it fails for a few tests then these failures are not necessarily the same. See https://github.com/MDAnalysis/mdanalysis/issues/551#issuecomment-161134129 .

**Comment by orbeckst** [comment]
@hainm reported that a potentially similar error was reported in wbsoft/frescobaldi#554 although no solution was presented apart from the hint of "problems when creating a tempdir inside a tempdir".

**Comment by richardjgowers** [comment]
If we've accidentally nested tempdirs (calling Tempdir while inside a Tempdir decorated class?) that might be a way for that to happeb

**Comment by kain88-de** [comment]
But the errors seem to be random and I can't find such a nested pattern in the code where it fails.

**Comment by hainm** [comment]
@orbeckst should give beer to me.

```python

nosetests -vs   testsuite/MDAnalysisTests/analysis/test_helanal.py testsuite/MDAnalysisTests/analysis/test_psa.py

```
will cause error because someone go to temp folder in test_helanal.py but has never come back to working dir.

**Comment by hainm** [comment]
it's better to always use contextmanager.

**Comment by orbeckst** [comment]
On 2 Dec, 2015, at 16:53, Hai Nguyen wrote:

> @orbeckst should give beer to me.
> 
> nosetests -vs   testsuite/MDAnalysisTests/analysis/test_helanal.py testsuite/MDAnalysisTests/analysis/
> test_psa.py
> 
> will cause error because someone go to temp folder in test_helanal.py but has never come back to working dir.

I just heard from @dldotson and @richardjgowers that this fixes the problem: I am very happy,  so yes: I will gladly buy you a beer � find me at ACS (or find @dldotson or @slseyler at BPS who can buy you a beer in my name ;-) ).

**Comment by orbeckst** [comment]
I added a note to ban `os.chdir()` when [writing testcases](https://github.com/MDAnalysis/mdanalysis/wiki/UnitTests#writing-test-cases).

(And yes, the wiki page on testing needs a major clean-up.)

**Comment by orbeckst** [comment]
```
$ git grep chdir
testsuite/MDAnalysisTests/analysis/test_helanal.py:        os.chdir(self.tempdir)
testsuite/MDAnalysisTests/analysis/test_hole.py:        os.chdir(self.dir_name)
testsuite/ez_setup.py:        os.chdir(tmpdir)
testsuite/ez_setup.py:        os.chdir(subdir)
testsuite/ez_setup.py:        os.chdir(old_wd)
testsuite/ez_setup.py:        os.chdir(tmpdir)
testsuite/ez_setup.py:        os.chdir(subdir)
testsuite/ez_setup.py:        os.chdir(old_wd)
```

#558 should take care of all of this (and of course we should eliminate `ez_setup.py` etc from the testsuite....)

**Comment by orbeckst** [comment]
@hainm do you also want to fix `test_hole.py` with #558? Otherwise I can clean up my own mess in `test_hole.py` (which, by the way, is only run when you have `hole` available so it won't trigger the bug on travis).

**Comment by hainm** [comment]
@orbeckst I am leaving `test_hole.py` to you since I don't have HOLE installed (so not sure if the change is good or not).
