### ISSUE TITLE
The RMSD function always does a fit 

### ISSUE THREAD

**Issue by kain88-de** [MDAnalysis/mdanalysis#562]
A colleague of mine tried to use the `rmsd` function in `analysis.rms` today and was surprised by  the results. He expected that this function would **only** calculate the rmsd without performing any kind of optimization/alignment. But according to the docs that is exactly what this function is doing.

This is very counterintuitive and I'm also surprised by that behavior. I would have expected an `rmsd` function to return the rmsd and leave the inputs unchanged. 

I'm not sure what might be a good way to change the behavior here since some old code likely depends on this behavior.

**Comment by hainm** [comment]
that is the way rmsd work (at least in cpptraj). You need to do the translation and rotation. Making extra coords copy is very expensive.

**Comment by dotsdl** [comment]
I'm in agreement that `analysis.rms.rmsd` *shouldn't* do any fitting by default, and I've had this gripe for a while. Can we add a kwarg to tell it *not* to fit? That would at least keep from breaking old code that depends on the built-in fitting.

**Comment by orbeckst** [comment]
We probably should change the default behavior to _not fit_. It will be a minor API break but it should be done for 1.0 latest (and if anyone wants to do it now, for 0.13).
* [ ] [analysis.rms.rmsd()](http://www.mdanalysis.org/mdanalysis/documentation_pages/analysis/rms.html?highlight=rmsd#MDAnalysis.analysis.rms.rmsd): change default to not fitting; add kw `fit` to perform translational and rotational fit (basically, what `rmsd(..., center=True)` currently does)
* [ ] [analysis.rms.RMSD](http://www.mdanalysis.org/mdanalysis/documentation_pages/analysis/rms.html?highlight=rmsd#MDAnalysis.analysis.rms.RMSD): change default to not fitting; add kw `fit` to perform translational and rotational fit (basically, what the class currently does)

We are using the qcprot fast RMSD calculation and that immediately does the rotational superposition (not the translation). Admittedly, I didn't know if [MDAnalysis.lib.qcprot.FastCalcRMSDAndRotation](http://www.mdanalysis.org/mdanalysis/documentation_pages/lib/qcprot.html#MDAnalysis.lib.qcprot.FastCalcRMSDAndRotation) is actually faster than a naive numpy RMSD calculation
```python
def rmsd(x, y):
   return np.sqrt(np.sum(np.square(np.ravel(x - y)))/len(x))
```

so I timed it
```
import MDAnalysis as mda; from MDAnalysis.tests.datafiles import PSF, DCD
from MDAnalysis.analysis.rms import rmsd as rmsd_fast
u = mda.Universe(PSF, DCD)
p = u.select_atoms("protein")
A, B = p.coordinates(u.trajectory[0]),  p.coordinates(u.trajectory[-1])
%timeit rmsd_fast(A, B)
# 10000 loops, best of 3: 97.3 µs per loop
%timeit rmsd(A, B)
# 10000 loops, best of 3: 109 µs per loop
```

Perhaps it would be worthwhile to add a cythonized RMSD calculation to the `lib`, which should be able to beat the numpy implementation (which is currently *slower* than the qcprot which *also* does a rotational superposition). (Or perhaps someone will just write the numpy version in a better way...)

**Comment by hainm** [comment]
The numpy case is rmsd without fitting. What is the case of using it?

**Comment by cing** [comment]
+1 
Glad this was brought up. I've also noticed this issue in MDAnalysis and other packages RMSD calculations for a while now, so I've just been using the numpy implementation exclusively.

When I'm working with membrane proteins, I do alignment once on transmembrane helices, then I compute RMSD of individual loops/regions with respect to the crystal structure. Those regions are potentially flexible, so specifically aligning them to the crystal structure would underestimate RMSD.

**Comment by hainm** [comment]
This is exactly we do with cpptraj in amber

http://archive.ambermd.org/201108/0809.html

**Comment by kain88-de** [comment]
@orbeckst a cython version might be faster but the pure numpy version is good right now. I'm not sure if the pure rmsd could als go into a module called `analysis.metrics`. I have some code for other distance metrics that would fit quite nicely into it.

**Comment by orbeckst** [comment]
If the implementations are sufficiently general, i.e. take coordinates as input then I would suggest `lib.metrics` instead.
