### ISSUE TITLE
Test optional requirements no longer optional

### ISSUE THREAD

**Issue by jbarnoud** [MDAnalysis/mdanalysis#566]
Now that the test suite includes the tests for analyses, scipy and netcf are required to run the tests. These packages do not appear in the test suite setup.py, though. Therefore, the tests fail for a fresh minimal install of MDAnalysis in a fresh virtualenv.

**Comment by richardjgowers** [comment]
#124 was meant to fix this, but maybe not everything was caught.  #483 is adding a minimal build to travis so this is checked
