### ISSUE TITLE
Rewrite Parsers

### ISSUE THREAD

**Issue by richardjgowers** [MDAnalysis/mdanalysis#572]
All parsers need to have their output changed to a `Topology` object.  These should only now return values that are defined in the format (no guessing & no default values).

For details on the new structures, see:
https://github.com/MDAnalysis/mdanalysis/wiki/Guide-to-new-Topology-format

It is also possible to add in Attributes for values that were previously ignored

- [x] CRDParser
- [x] DLPolyParser
- [x] DMSParser
- [x] ExtendedPDBParser
- [x] GMSParser
- [x] GROParser
- [x] HoomdXMLParser
- [x] LAMMPSParser
- [x] MOL2Parser
- [x] PDBParser
- [x] PDBQTParser
- [x] PQRParser
- [x] PrimitivePDBParser
- [x] PSFParser
- [x] TOPParser
- [x] TPRParser
- [x] XYZParser

**Comment by orbeckst** [comment]
Is this really easy for a newcomer or "just" easy for someone in @MDAnalysis/coredevs ?

**Comment by richardjgowers** [comment]
I think I called it easy because it's (mostly) just filling numpy arrays with stuff from the file, rather than filling Atom objects.  So it's just converting the existing parsers really.

**Comment by jbarnoud** [comment]
What is the status of the tests? Are they still relevant? I am mostly concerned about `MDAnalysisTests.topology.test_topology._TestTopology` (that is `MDAnalysisTests.test_topology._TestTopology` in the `develop` branch). Indeed, I plan to tackle the TPR parser, most tests of which inherit from `_TestTopology`.

**Comment by richardjgowers** [comment]
Long story short, the current tests aren't very good because they need to create a Universe.  The new `Topology` object should work as a standalone object, so the new tests for topology won't have to involve a Universe.

I'll try and get a new test template done soon, but it will likely just have to inspect each of the numpy arrays inside each Attribute in the Topology object.

If you want to look at doing TPR, on the issue-363 branch, GROParser is a fairly good example of what needs to be done.

**Comment by richardjgowers** [comment]
@jbarnoud 
Base tests now exist, with an example for GRO

https://github.com/MDAnalysis/mdanalysis/blob/issue-363/testsuite/MDAnalysisTests/topology/base.py

https://github.com/MDAnalysis/mdanalysis/blob/issue-363/testsuite/MDAnalysisTests/topology/test_gro.py

**Comment by jbarnoud** [comment]
@richardjgowers
Great! I'll see what I can do for the TPR parser then.

Quick remark: it may be good to list the attributes a child of ``ParserBase`` must define in the docstring of the class. Of course, one can read the code or copy ``TestGROParser`` but it is better when a class has its own doc.

**Comment by dotsdl** [comment]
@richardjgowers clearly you had a relaxing vacation. :D

**Comment by richardjgowers** [comment]
Wasn't too bad in the end :D We need to get the benchmarks up really, show everyone why we're even bothering to get this done

**Comment by dotsdl** [comment]
Do you want help on that front? Did you check if the performance of any of these parsers improved from these changes alone?

**Comment by richardjgowers** [comment]
Yeah I was going to add the select_atoms benchmarks in too, so if you could
throw the notebook up and maybe add some quick selection benchmarks that'd
be good.

**Comment by richardjgowers** [comment]
Oh, and I've not checked individual parsers, but I expect none will be
slower, many will be faster. I did a little refactoring for a few.

**Comment by dotsdl** [comment]
@richardjgowers I'll throw it up as a gist today. Any selections in particular you think showcase the best the new behavior? Also, on which system?

**Comment by dotsdl** [comment]
Here's the link: https://gist.github.com/dotsdl/0e0fbd409e3e102d0458

Haven't added selections yet, but can update the notebook later on.
