### ISSUE TITLE
travis tests fail on scipy import

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/mdanalysis#576]
Currently, tests fail when scipy is imported, something related to libgfortran missing.

Something similar happened before MDAnalysis/GridDataFormats#17 and @tylerjereddy fixed it as part of #503 ; I assume it's yet another conda SNAFU.

**Comment by richardjgowers** [comment]
Yeah I caused this by pushing my polymer module.  It's a problem with conda/scipy/libgfortran

**Comment by orbeckst** [comment]
Always wonderful when someone else takes the blame (and the issue)! ;-)

**Comment by orbeckst** [comment]
Perhaps you can just apply @tylerjereddy 's patch 51eaa21b4434e002ccb59b9d21f17a89b4c1227b ?

**Comment by richardjgowers** [comment]
https://github.com/MDAnalysis/mdanalysis/commit/86b04458377a2ef9adf90289018262a0ab0442a0

Tried that here and it didn't work.  But I think it is the right fix for this issue

**Comment by orbeckst** [comment]
Maybe get rid of mkl?

**Comment by richardjgowers** [comment]
Yeah mkl did it

**Comment by orbeckst** [comment]
Huzzah!

On 10 Dec, 2015, at 11:14, Richard Gowers wrote:

> Yeah mkl did it
> 
> �
> Reply to this email directly or view it on GitHub.
> 

--
Oliver Beckstein * orbeckst@gmx.net
skype: orbeckst  * orbeckst@gmail.com
