### ISSUE TITLE
density_from_Universe Truth check

### ISSUE THREAD

**Issue by tylerjereddy** [MDAnalysis/mdanalysis#579]
Just poking around in this function after a mailing list question and noticed that:

```python
if cutoff > 0 and soluteselection is not None:
```
should be (more pythonic):

```python
if cutoff > 0 and soluteselection:
```

Absolute line reference:
https://github.com/MDAnalysis/mdanalysis/blob/e2065be4ef7d143312a632e85ee618223a0c3120/package/MDAnalysis/analysis/density.py#L540

**Comment by kain88-de** [comment]
That would actually change the meaning of the code. `soluteselection` could be set to false, in the current version the if still evaluates to true in your proposed version it evaluates to false. If we want to express that any valid python object is acceptable then `is not None` is to correct pythonic check IMHO. If `soluteselection` should only evaluate to `True` then we can change it.

**Comment by tylerjereddy** [comment]
I guess we should really express the type of `soluteselection` in the docstring, as per numpy doc standard, though it is fairly clear it should be a string from the example. That said, I suspect you are correct that the intention probably is to allow any python object, and my proposed change would not be an improvement at all.

**Comment by orbeckst** [comment]
I am flogging a dead horse here but I want to add that when checking for kwargs at default values that should be a container (list, dict, ...), testing `is not None` is the right (and unambiguous) way to do it. Even if it's not a container, it is much clearer (and more future-proof) than having to know what type the kwarg will (or should) be. 

Basically, as soon as you're potentially dealing with user input, be explicit (even if it comes at the price of pythonicity).
