### ISSUE TITLE
AtomGroup methods from TopologyAttrs (transplants)

### ISSUE THREAD

**Issue by richardjgowers** [MDAnalysis/mdanalysis#601]
So currently (on the issue-363 branch) arbitrary attributes can be defined (usually by a parser) and these are then accessible at the AtomGroup (and Atom, ResidueGroup etc) level.  For example

``` python
class Colour(TopologyAttr):
    level = 'atom'
    plural = 'colours'
    # code here

atomgroup.colours
# [red, blue, blue, red etc]
```

The next step in this is to allow a `TopologyAttr` to also define additional methods which appear in the `Groups` and `Components` namespace.  The code for these would live in the TA, but get moved over into the AtomGroup on Universe init.  This will look something like:

``` python
class Colour(TopologyAttr):
    # fancy code
    def complimentary_colours(ag):
        return complimentary[ag.colours]

atomgroup.colours
atomgroup.complimentary_colours()
```

Reasons for this approach
- Prevents the base AtomGroup class from becoming bloated with every imaginable method
- All code related to a given Attribute lives in the same module
- Can include extra Attributes & methods without installing MDA from source

TODO:
- [x] get it working for `Masses`
- [ ] write tests for adding arbitrary attribute (`Happiness`)
- [x] write dev wiki page for how this works

**Comment by dotsdl** [comment]
Once you have the test you mention, perhaps we'll close this. Up to you. It's enough for me if all the transplants we define actually work, but it is cool if we can show how easy it is to dynamically add things in.
