### ISSUE TITLE
MDAnalysis conda build

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/mdanalysis#608]
MDAnalysis should be available in conda.

@hainm showed how to do it in #571.

@orbeckst registered the anaconda channel  https://anaconda.org/MDAnalysis/mdanalysis — he can probably add whoever is going to do this as a maintainer or owner.

Note: Also needs a conda build for gridDataFormats.

**Comment by hainm** [comment]
conda build for griddata format is also in my PR too.

Hai

**Comment by orbeckst** [comment]
@kain88-de started work on it in #751 (and he's also an owner of the [anaconda MDAnalysis org](https://anaconda.org/MDAnalysis/).
