### ISSUE TITLE
can not write the pdb with updated occupancies

### ISSUE THREAD

**Issue by aakognole** [MDAnalysis/mdanalysis#620]
I had to change the occupancies for some atoms 
so I updated them like selection.atoms.occupancies = 10.00 
when I check the occupancies after that I can see them updated 
but then when I write the pdb file I do not see the changes.

On the other hand if I do that with beta factors it just works fine.

**Comment by tylerjereddy** [comment]
Just off the top of my head, I think you may only be able to access the values with `occupancies`, with a separate set method currently used for assigning new values.

Maybe try using `set_occupancies`? The docs for that method are here: http://pythonhosted.org/MDAnalysis/documentation_pages/core/AtomGroup.html?highlight=occupancies#MDAnalysis.core.AtomGroup.AtomGroup.set_occupancies

**Comment by richardjgowers** [comment]
Nah I've been able to reproduce it myself, I'll have a look

**Comment by aakognole** [comment]
@tylerjereddy 

I tried selection.atoms.set_occupancies(10.00) 
it updates them but again when I write the pdb file it's not there.

**Comment by richardjgowers** [comment]
Hi @aakognole this has been fixed on the develop branch, and should be fixed in the 0.13 release this weekend.
