### ISSUE TITLE
move example scripts to own cookbook repo

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/mdanalysis#627]
I think we could reduce the amount of stuff in the core library tar file and repository by moving the example scripts into their own repository. They would be more visible there and their maintenance could be somewhat decoupled from the main library.

Ultimately, we could turn this into a suite of small MDA-based tools that do common tasks, but from the command line and using a common driver command (think `git subcommand` or new gromacs `gmx subcommand`). Something like 
```
mda convert --topology=PSF DCD XTC
mda rmsd -o rmsd.dat PSF DCD
mda contacts --selection="protein and not name H*" TPR XTC
mda help
```

See also suggestion for example library #420.

**Comment by richardjgowers** [comment]
The command line thing is interesting, especially if we could make `AnalysisBase` automagically (or easily) be accessible via that thing.  So anything written in AnalysisBase can get easily moved over to a command line version.

Also, if we do do something cli, can we use [docopt](http://docopt.org/)? it's one of my favourite modules!

**Comment by kain88-de** [comment]
Removing the examples from here is a good idea. I had the idea that we could publish polished examples as notebooks on the blog and link to the cookbook repository.

About the CLI version. Maybe you should open another bug report or a topic on the devel list since it is
unrelated to creating a cookbook/example repository.

**Comment by richardjgowers** [comment]
Yeah I had a similar idea to Max, if we polished them up and made a blog post (notebook) for each that'd be the best format.

The Cli might even be a good gsoc project since its fairly self contained

**Comment by orbeckst** [comment]
Am Jan 18, 2016 um 7:22 schrieb kain88-de <notifications@github.com>:

> About the CLI version. Maybe you should open another bug report or a topic on the devel list since it is
> unrelated to creating a cookbook/example repository.

Yes, will do. It was just part of the brain dump...

In the short term I would make a new examples repo and move all examples there and then we can slowly process it. There might be a few links in the docs to the examples so that would need to be changed (@tylerjreddy ?).

**Comment by kain88-de** [comment]
> The Cli might even be a good gsoc project since its fairly self contained

That would be worth a try. Do you want to add it to the projects page?

**Comment by richardjgowers** [comment]
@orbeckst done, and links updated

@kain88-de yep, done

**Comment by orbeckst** [comment]
Awesome, many thanks!

On 18 Jan, 2016, at 09:31, Richard Gowers wrote:

> @orbeckst done, and links updated
> 
> @kain88-de yep, done
> 
> �
> Reply to this email directly or view it on GitHub.
> 

--
Oliver Beckstein * orbeckst@gmx.net
skype: orbeckst  * orbeckst@gmail.com
