### ISSUE TITLE
Apply Six fixes for Python 3

### ISSUE THREAD

**Issue by richardjgowers** [MDAnalysis/mdanalysis#632]
Omnibus issue for six fixes

List of issues to do:
 - [x] `izip` & `xrange` (#645)
 - [x] metaclasses (#633)
 - [x] `string_types` (#655)
 - [x] 'six.iteritems/key/values'
 - [ ] use of long integers

Resources for finding fixes:
http://python-future.org/compatible_idioms.html

**Comment by hainm** [comment]
- [ ] string_types

**Comment by kain88-de** [comment]
You should add iteritems and co as well. Six has a wrapper function for them.

**Comment by richardjgowers** [comment]
Yeah, I was hoping we'd all edit the list above :P

**Comment by orbeckst** [comment]
Do we actually use any explicit  [Python 2 `long`](http://python-future.org/compatible_idioms.html#long-integers) anymore?
```
git grep '[0-9]L' | egrep '^.*\.(py|pyx|pxd):'
```
shows zero results. Maybe @jbarnoud or @richardjgowers can comment.

There are explicit longs in the C code but that is fine.

**Comment by jbarnoud** [comment]
I removed all the use of long integer I found. I do not see any remaining; except for the ones in the TRZ parser, but these are only seen by python 2.

We should be good for this issue. I close it, the remaining occurrences will most likely be fixed as we go.
