### ISSUE TITLE
PDB writer, Atom type column (like CA) off by 1

### ISSUE THREAD

**Issue by dmerz75** [MDAnalysis/mdanalysis#639]
Hi,
The MDAnalysis.Writer seems to have the wrong space for PDB output?
The excerpt of code I use:

    def __init__(self,workdir,psf,dcd,destdir,idn):
        self.u = MDAnalysis.Universe(self.psf,dcd)

    def write_coords(self,resid_first,resid_last,start=0,stop=-1,step=1,sel=None):

       selection = "resid %d:%d" % (resid_first,resid_last)

       for ts in self.u.trajectory[start:stop:step]:
            coord_file = "interim_coord/interim_f%s_r-%s.pdb" % (str(ts.frame + 1),tag)
            if not os.path.exists(coord_file):
                W = MDAnalysis.Writer(coord_file,system.n_atoms)
                W.write(system)

    Possibly Incorrect, MDAnalysis 0.13 >>
    TITLE     MDANALYSIS FRAMES FROM 0, SKIP 1: Created by PrimitivePDBWriter
    REMARK     REMARKS FILENAME = dcd/2khosbd_D30_pull.dcd CREATED BY dcdio.c
    REMARK     REMARKS DATE: Wed Sep  9 20:56:23 2015
    CRYST1    0.000    0.000    0.000  90.00  90.00  90.00 P 1           1
    MODEL         1
    ATOM      1 CA   THR   383       7.582   6.482 -32.610  1.00  0.00          C 0.00
    ATOM      2 CA   GLY   384       7.319   5.109 -36.233  1.00  0.00          C 0.00
    ATOM      3 CA   ASP   385       7.347   4.972 -40.284  1.00  0.00          C 0.00

    Example from using MDAnalysis 0.7 >>
    TITLE     MDANALYSIS FRAME 0: Created by PrimitivePDBWriter
    REMARK     REMARKS FILENAME = dcd/2KHO_D30_pull.dcd CREATED BY dcdio.c
    REMARK     REMARKS DATE: Wed Sep  3 10:55:57 2014
    CRYST1    0.000    0.000    0.000  90.00  90.00  90.00 P 1           1
    ATOM      1  CA  ILE     4      10.108 -13.190 -19.973  1.00  0.00      SYST C 0
    ATOM      2  CA  ILE     5       9.260 -10.783 -23.097  1.00  0.00      SYST C 0
    ATOM      3  CA  GLY     6       8.193  -7.283 -24.581  1.00  0.00      SYST C 0
    ATOM      4  CA  ILE     7       7.700  -8.232 -28.547  1.00  0.00      SYST C 0
    ATOM      5  CA  ASP     8       7.633 -10.086 -31.674  1.00  0.00      SYST C 0

    Possibly Correcting 0.13 (inserted space left of the CA, and deleted 1 from right of RESNAME) >>
    TITLE     MDANALYSIS FRAMES FROM 0, SKIP 1: Created by PrimitivePDBWriter
    REMARK     REMARKS FILENAME = dcd/2khosbd_D30_pull.dcd CREATED BY dcdio.c
    REMARK     REMARKS DATE: Wed Sep  9 20:56:23 2015
    CRYST1    0.000    0.000    0.000  90.00  90.00  90.00 P 1           1
    MODEL         1
    ATOM      1  CA  THR   383       7.582   6.482 -32.610  1.00  0.00          C 0.00
    ATOM      2  CA  GLY   384       6.438   5.270 -35.861  1.00  0.00          C 0.00
    ATOM      3  CA  ASP   385       7.418   6.585 -39.348  1.00  0.00          C 0.00

**Comment by richardjgowers** [comment]
Hey,

Thanks for the report, yeah looks like we (I) got the alignment wrong there..

**Comment by richardjgowers** [comment]
So this will be fixed in 0.13.1, in the meantime if you want you can use the develop branch where this is currently fixed:

https://github.com/MDAnalysis/mdanalysis/wiki/DevelopmentBranch

Thanks again for the report

**Comment by dmerz75** [comment]
Will do, Thanks!
