### ISSUE TITLE
Insert or delete atom at given position in a Universe object

### ISSUE THREAD

**Issue by tomnewport** [MDAnalysis/mdanalysis#642]
I would like to be able to:

- Create an empty MDAnalysis Universe
- Create a new atom with a position, name, type etc.
- Insert the new atom into a universe (empty or loaded from file) with a specified index
- Delete existing atoms at a specified index
- Re-order the universe

Is this currently possible, and how would I go about doing it?

**Comment by tomnewport** [comment]
Creating an atom:
    MDAnalysis.core.AtomGroup.Atom(number, name, type, resname, resid, segid, mass, charge, residue=None, segment=None, radius=None, bfactor=None, resnum=None, serial=None, altLoc=None)

**Comment by dotsdl** [comment]
At the moment I don't think there is a clean way to create new `Atom` objects from scratch. However, if you already have one or more `Universe` objects generated from topology files, it's possible to effectively add and delete atoms using the [`Merge`](http://pythonhosted.org/MDAnalysis/documentation_pages/core/AtomGroup.html?highlight=merge#MDAnalysis.core.AtomGroup.Merge) function.

The entire topology system is being reworked at the moment (see [here](https://github.com/MDAnalysis/mdanalysis/wiki/Issue363-Changes#search_word=363) for a glimpse at what's coming), and we hope that it makes system-building with MDAnalysis easier/possible.

**Comment by dotsdl** [comment]
Others can chime in if they have found ways to do any of these that I'm unaware of.

**Comment by richardjgowers** [comment]
Yeah I don't think there's really a nice way to do this currently.
If it was me I'd:
 * `Merge` to create a Universe/AtomGroup of the size I wanted
 * save that as a pdb
 * reload the pdb as a new Universe
 * edit the Universe to my liking
 * save **this** Universe

**Comment by tomnewport** [comment]
Thanks all - I'll use a temporary hack-y workaround for the moment with a view to updating my code after [Issue #363](https://github.com/MDAnalysis/mdanalysis/issues/363) is implemented.
