### ISSUE TITLE
Atom types in PDB file should be align to the right

### ISSUE THREAD

**Issue by jbarnoud** [MDAnalysis/mdanalysis#648]
Atom types in PDB file should be align to the right, MDAnalysis aligns them to the left.

**Comment by kain88-de** [comment]
isn't this connected to #647?

**Comment by jbarnoud** [comment]
On 06/02/16 18:20, kain88-de wrote:
>
> isn't this connected to #647 
> <https://github.com/MDAnalysis/mdanalysis/issues/647>?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/MDAnalysis/mdanalysis/issues/648#issuecomment-180813895>.
>
It is connected in the sense that they are both formatting issues. They 
are not about the same field, though. This issue is about the atom type 
at the end of the ATOM line, while #647 is about the atom name.
