### ISSUE TITLE
DCD Module doesn't support Python 3

### ISSUE THREAD

**Issue by richardjgowers** [MDAnalysis/mdanalysis#659]
The DCD module doesn't currently support Python 3

Master py3 issue: #260 

There's a py3 compatible version based on our version here:
https://github.com/arose/simpletraj/tree/master/simpletraj/dcd

So hopefully this will be simple

**Comment by orbeckst** [comment]
See @arose 's comments on his work modifying the MDA DCD reader for [simpetraj](https://github.com/arose/simpletraj) with Py3, in https://github.com/MDAnalysis/mdanalysis/issues/260#issuecomment-175429668 .

**Comment by tylerjereddy** [comment]
Ok, let me take a look.

**Comment by tylerjereddy** [comment]
Note that with biophysics and other talks coming up I'm a bit inundated so progress here is quite slow lately. Do feel free to reassign the task if desired, otherwise I'll just occasionally chip away it.

**Comment by tylerjereddy** [comment]
I've removed my assignment to this for now in case somebody else wants to step in. Otherwise, I will probably chip away at it slowly.

**Comment by dotsdl** [comment]
I'll take it, but it won't be until November. If anybody else feels moved by the spirit before then, I'm happy to let them work on it.

**Comment by kain88-de** [comment]
When I have some partially working cython up I'll push it to this repo instead of my fork. Then we can work together on it.

I'm strongly in favor of a clean cython port because it will increase the maintainability of the code dramatically.

**Comment by orbeckst** [comment]
> On 20 Jul, 2016, at 13:06, Max Linke <notifications@github.com> wrote:
> 
> I'm strongly in favor of a clean cython port because it will increase the maintainability of the code dramatically.

Did you have a look at https://github.com/MDAnalysis/mdanalysis/blob/develop/package/MDAnalysis/coordinates/dcdtimeseries.pyx ? This is has a lot of cython code that shows how to use the VMD C code from “readdcd.h”.

Of course, it is later patched into the DCD object https://github.com/MDAnalysis/mdanalysis/blob/develop/package/MDAnalysis/coordinates/DCD.py#L600 which relies on the code in https://github.com/MDAnalysis/mdanalysis/blob/develop/package/MDAnalysis/coordinates/src/dcd.c – the very thing that needs to be rewritten.

Nevertheless, the reading of the trajectory in dcdtimeseries.pyx is independent from the reading in dcd.c so it should make for a useable starting point.

--
Oliver Beckstein * orbeckst@gmx.net
skype: orbeckst  * orbeckst@gmail.com

**Comment by kain88-de** [comment]
I've looked into that module. It is pretty old cython (rather pyrex) code that is close to the C-API of python. It's helpful but not as much as you would imagine.
