### ISSUE TITLE
XTC seeking frame offsets are wrong, if frame is stored beyond 2GB boundary

### ISSUE THREAD

**Issue by marscher** [MDAnalysis/mdanalysis#660]
First of all thank you very much for this major improvement of xdrlib!

You use xdr_read_int to obtain the frame size, which you then truncate to a 32bit boundary. But if you want to correctly seek to frames beyond 2**32-1 bytes, you need to use a larger data type. I've fixed this in mdtraj/mdtraj#1023.
Note that I've copied over your code to this branch. I hope this is ok. Did you actually had a re-licensing agreement with the Gromacs folks for GPL?

Please fell free to take/modify my solution there. It implies reading incompatible pointers :+1: (int vs. double) to achieve this. Another solution doesn't seem to be possible because the largest integral datatype xdrlib can read is int32. So I store the frame size in a int64 and pass it to xdr_read_double to handle larger offsets.

Best,
Martin

**Comment by marscher** [comment]
If you wonder why it already happens beyond 2G, you're using a signed int for framesize.

**Comment by kain88-de** [comment]
> Note that I've copied over your code to this branch. I hope this is ok. Did you actually had a re-licensing agreement with the Gromacs folks for GPL?

There is no re-licensing going on. We follow the license as stated in the files. They are using a modified BSD license there. You can check this by downloaded the library as available on the [gromacs](http://www.gromacs.org/Developer_Zone/Programming_Guide/XTC_Library) website.
The website mention that they are using a LGPL but that looks like outdated information.

**Comment by marscher** [comment]
Alright. May I kindly ask, if you have a contact of the original author Manuel Nuno Melo?

**Comment by richardjgowers** [comment]
@mnmelo paging Dr Melo

**Comment by marscher** [comment]
thank you!

**Comment by kain88-de** [comment]
@marscher could you elaborate your problems a little bit. 

Are you saying that the integer we use for `framebytes` is to small? That would mean you have trajectories where a frame contains more then 2GB worth of atoms.

Because our offsets itself are saved as signed 64bit integers which should be more then enough to index above 2GB.

**Comment by kain88-de** [comment]
I'm also not sure about your solution. You are now reading 8 bytes instead of 4. That should mess things up quite a bit.

How are you creating these trajectories?

**Comment by marscher** [comment]
I guess then my test data was wrong in the sense you mentioned. Only for super large systems (which are not practical or reachable at the moment) this would make sense. Thanks for taking a look!
