### ISSUE TITLE
trajectory iterator ignores stop=0

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/mdanalysis#672]
Passing 0 as the stop in the trajectory slice seems to be ignored: The following code should not iterate:
```python
import MDAnalysis as mda; from MDAnalysis.tests.datafiles import PSF, DCD
u = mda.Universe(PSF, DCD)
frames = [ts.frame for ts in u.trajectory[:0]]
assert len(frames) == 0
```
(gives instead 98).

Compare to the desired behavior
```python
>>> list(range(98))[:0]
[]
```

(I came across this while fixing the remaining comments from PR #624.)

**Comment by richardjgowers** [comment]
https://github.com/MDAnalysis/mdanalysis/blob/develop/package/MDAnalysis/coordinates/base.py#L1244

I think this is the offending line, `if stop:` should probably be `if stop is not None:`

**Comment by orbeckst** [comment]
On 27 Jan, 2016, at 12:47, Richard Gowers wrote:

> https://github.com/MDAnalysis/mdanalysis/blob/develop/package/MDAnalysis/coordinates/base.py#L1244
> 
> I think this is the offending line, if stop: should probably be if stop is not None:

Almost certainly. Thanks for checking.
