### ISSUE TITLE
add quantifiedcode-bot as an AUTHOR?

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/mdanalysis#674]
@quantifiedcode-bot has 6 commits. Should we add it (or rather, QuantfiedCode) to the AUTHORs list?

Should it be added to the CHANGELOG?

**Comment by dotsdl** [comment]
I don't think so. Humans only. :P

**Comment by richardjgowers** [comment]
Haha, it's a fun idea though

**Comment by hainm** [comment]
lol

**Comment by mnmelo** [comment]
Well, credit where it's due. I'm sure the people at quantifiedcode would appreciate it. And it did save a lot of trouble in some cases.

**Comment by orbeckst** [comment]
QuantifiedCode's @quantifiedcode-bot disclaims all everything so I think technically we are not obligated in any way to add authorship information. 

Nevertheless, I agree with @mnmelo that it has been valuable and I think it is appropriate to acknowledge it in some way. I would suggest to add the handle to the CHANGELOG when we use QC PRs and add a line to AUTHORS somewhere mentioning QC but not in the same list as the humans. 

Opinions?

**Comment by mnmelo** [comment]
I'm for. Maybe under a header `Other contributors` in the AUTHORS?

**Comment by hainm** [comment]
**serious** It's not hurt to add him/her/it as contributor.

**Comment by orbeckst** [comment]
PR #685 proposes to include QC under "Other contributions" as suggested by @mnmelo , which seemed a good compromise. If you care about these things please voice your opinion.
