### ISSUE TITLE
Large-file xtc/trr failure indexing, seeking and telling.

### ISSUE THREAD

**Issue by mnmelo** [MDAnalysis/mdanalysis#677]
@jbarnoud brought to my attention failures to read large (>2GB) .xtc files.

I dug in the code and found that along the recent inclusion of the newer Gromacs `xdrfile.c` some large-file-specific changes were not made, that were there in the old code. These are unrelated to the header-reading concepts discussed in #660.

Consequences of this bug are wrong seeks and tells of files larger than 2GB. Even finding the correct filesize, which depends on tell, fails.

The solution is essentially to type `xdrstdio_getpos` to return `off_t`, and to have `xdrstdio_setpos` take an `off_t` as its second argument. Since we're using the `_FILE_OFFSET_BITS=64` build flag, the `off_t` type behaves always 64 bit, even in 32 bit machines. I have a 32-bit virtualbox lying around from back then. I'll double check and make the PR.

Additionally, @kain88-de, the `_xdr.tell()` now returns the frame we're at, instead of the byte offset. It is now quite redundant and I vote to either remove it or revert to the old behavior of reporting the offset. `xdr.tell` is useful essentially for debugging, and so it's not a big deal for the API to have it removed, but would have made debugging this issue much faster. What do you say?

(edited to correctly name the fixed `xdrstdio` calls)

**Comment by kain88-de** [comment]
> The solution is essentially to type xdrstdio_getpos to return off_t, and to have xdrstdio_setpos take an off_t as its second argument. Since we're using the _FILE_OFFSET_BITS=64 build flag, the off_t type behaves always 64 bit, even in 32 bit machines. I have a 32-bit virtualbox lying around from back then. I'll double check and make the PR.

This behavior is gnu specific as far as I can tell. That is the reason I replaced it with an unsigned int. I couldn't find the type defined in the C standard only in POSIX. I would rather use `uint64_t` from `stdint.h`.  That one is defined in the C99-standard and it doesn't change depending on compile flags. 

> Additionally, @kain88-de, the _xdr.tell() now returns the frame we're at, instead of the byte offset. It is now quite redundant and I vote to either remove it or revert to the old behavior of reporting the offset. xdr.tell is useful essentially for debugging, and so it's not a big deal for the API to have it removed, but would have made debugging this issue much faster. What do you say?

That was by design. It is useful for people who only want to use the `XTCFile` and `TRRFile` classes. XTC is very good at compressing numerical data when you can sacrifice precision. For those it useful to know which frame they are on.  I also don't want to expose the actual offsets in the xtc file because then we are not encapsulating the libxdr anymore.

**Comment by richardjgowers** [comment]
If the `tell` was made to return the bytes it would probably also make generalising the offsets easier as every other file is going to use bytes too

**Comment by jbarnoud** [comment]
> > Additionally, @kain88-de, the _xdr.tell() now returns the frame we're at, instead of the byte offset. It is now quite redundant and I vote to either remove it or revert to the old behavior of reporting the offset. xdr.tell is useful essentially for debugging, and so it's not a big deal for the API to have it removed, but would have made debugging this issue much faster. What do you say?
> 
> 
> That was by design. It is useful for people who only want to use the XTCFile and TRRFile classes. XTC is very good at compressing numerical data when you can sacrifice precision. For those it useful to know which frame they are on. I also don't want to expose the actual offsets in the xtc file because then we are not encapsulating the libxdr anymore

There could be two method: one that returns the offset and one that returns the frame number.

**Comment by kain88-de** [comment]
> If the tell was made to return the bytes it would probably also make generalising the offsets easier as every other file is going to use bytes too

Not really. We need the special offset calculation for xdr files for performance reasons. All other file formats would have to do the same as well to avoid unpacking the coordinates as well for offset calculations. 



> There could be two method: one that returns the offset and one that returns the frame number.

sure you could have a *hidden* `_bytes_tell` method for debuging.

**Comment by jbarnoud** [comment]
(Note, that can somehow be related to #660)

**Comment by mnmelo** [comment]
@jbarnoud, it shouldn't be related to #660. That issue concerns the byte size of the `int` that'll hold the data-length of a single frame. Under current usage it's hard to get single frames larger than 2GB.

@kain88-de, my understanding is that the `off_t` types, and their connection to the `_FILE_OFFSET_BITS=64` build flag, come along with the availability of `ftello()`, and this is what `xdrlib.c` uses.
If we don't trust the existence of the `off_t`, we shouldn't use `ftello()` either, and that's a can of worms I'd rather leave unopened.

Of course, this breaks portability, but it was already broken before I changed the types back to `off_t`: windows doesn't have `ftello()`, for instance. Since we've been using `ftello()`/`off_t` for a couple of years now, without obvious ill effects, I'd say we stick to it. `int64_t` actually works just fine, at least in my two 64-bit and 32-bit test machines, but using `off_t` in incompatible systems, should break compilation, giving an early warning to the problem.

I'm also adding a `_bytes_tell()` and `_bytes_seek()` and some tests to them. I'll also add some tests that try to seek and tell from large offsets (these functions don't make the file actually grow, so it's fine to play with them).
