### ISSUE TITLE
New xdrlib information in AUTHORS and LICENSE is missing/outdated

### ISSUE THREAD

**Issue by mnmelo** [MDAnalysis/mdanalysis#679]
I'm opening this as a reminder so as not to let 0.14.0 ship without these fixes.

The new license aspects of xdrlib are outdated. The Gromacs base is now BSD.
We also haven't decided if the name libxdrfile2 stays, or if we call our modifications something else: with @kain88-de's cython approach (#441) and splitting of `xtc_seek.c`/`trr_seek.c` from `xdrfile.c` (#661) there is less of a clear new library to speak of.
@orbeckst has advocated keeping the name. I agree with that.
Right now we don't provide an actual `libxdrfile2.so` or `libxdrfile2.a`, but rather a mix of that with cython bindings (called `xdrlib.so`). This gets confusing but `xdrlib.so` could be renamed `libxdrfile2` to keep the external appearance and conform to the name we were using before.

**Comment by kain88-de** [comment]
> xdrlib.so could be renamed libxdrfile2 to keep the external appearance and conform to the name we were using before.

Sure we can also name it to libxdrfile2. Or libxdrfile3 to sow that  there has been an update.

**Comment by jbarnoud** [comment]
It could also be a different name to avoid confusion if the original libxdrfile get a major update. Also, `xdrlib.so` is confusing as there is a xdrlib module in the python standard library.

**Comment by orbeckst** [comment]
We should have a name different from the original gromacs one. 

- libxdrfile3
- libmdaxdr
- libgmxtraj
- libxtctrr

...

--
Oliver Beckstein
email: orbeckst@gmail.com


Am Jan 29, 2016 um 1:49 schrieb Jonathan Barnoud <notifications@github.com>:

**Comment by kain88-de** [comment]
I like `libmdaxdr`

**Comment by mnmelo** [comment]
I second @kain88-de's suggestion or something slightly more readable, like `libmda_xdr`.

More opinions?

**Comment by mnmelo** [comment]
Oops, it was actually @orbeckst's idea. Anyway, it has my vote (or the underscore version).
It also gets rid of the numbering (as in `libxdrfile2`), which gets mistaken for versioning.

**Comment by richardjgowers** [comment]
I don't think those names ever have underscores in them for some reason? (libblas, libgfortran, liblapack?)

**Comment by mnmelo** [comment]
Yea, a quick search through my own system shows that the usage of underscores seems to be mainly to distinguish different complile/linking versions of the same library.

So we stick to `libmdaxdr`. I'll make the changes. Anyone opposed?

**Comment by kain88-de** [comment]
No sounds good to me

**Comment by mnmelo** [comment]
@kain88-de, I'm having trouble finding the newer, BSD-licensed, version of libxdrfile from the Gromacs people. Could you point me to it?

**Comment by kain88-de** [comment]
http://www.gromacs.org/Developer_Zone/Programming_Guide/XTC_Library

This is the most recent version I can find, according to version numbers. The website says that it is licensed under LGPL but when you open the tarball you'll notice that the license in the files used is BSD. Surprisingly that is not the version they have in their git repository, the [git repo](http://repo.or.cz/gromacs/libxdrfile.git) has an older version licensed under LGPL.

**Comment by hainm** [comment]
@kain88-de you should contact GROMACS dev for correct answer.
