### ISSUE TITLE
Is TRZ title attribute handled as expected?

### ISSUE THREAD

**Issue by jbarnoud** [MDAnalysis/mdanalysis#688]
I am not familiar with the TRZ format, but I try to make the reader compatible with python 3 and I am surprised by how the title of TRZ files is handled (before any of my changes).

```python
In [1]: import MDAnalysis as mda
In [2]: from MDAnalysisTests.datafiles import (TRZ_psf, TRZ)
In [3]: universe = mda.Universe(TRZ_psf, TRZ)
In [4]: universe.trajectory.title
Out[4]: 'ABCDEFGHIJKLMNOPQRSTUVWXYZ12345678901234ABCDEFGHIJKLMNOPQRSTUVWXYZ12345678901234'
```

Is this really the title of the TRZ file? If not there is an issue here that may be worth fixing before making the reader python 3 compatible.

Also, for what I see, the title is not tested in `test_trz.py`.

**Comment by richardjgowers** [comment]
Hmm yeah I think that's correct.  I think I made it that in the test TRZ file so that it was 80 characters long (and I could see where it started and stopped).

**Comment by jbarnoud** [comment]
Great. It would be nice to have a test file with a shorter title to test how the title is read on a more realistic case, though. I can write the tests that make sure we read and write the title as expected, but I have no clue how to produce a TRZ file. @richardjgowers would it take you long? If it would, then don't bother it is not really important.

**Comment by richardjgowers** [comment]
Yeah I need to add a file with forces too, I'll do them both when I next do
a test coverage binge.
