### ISSUE TITLE
Long selections result in RuntimeError

### ISSUE THREAD

**Issue by tomnewport** [MDAnalysis/mdanalysis#695]
I have a selection in the form `selection = "resid 10 or resid 14 or resid 19 or resid 60 ... or resid 14598" ` for around 5,000 residues (`...` indicates more residue ids omitted). Running `universe.select_atoms(selection)` returns the following error:

```python
    lsel = self.lsel.apply(group)
  File "/*****/*****/MDAnalysis/core/Selection.py", line 138, in apply
    lsel = self.lsel.apply(group)
RuntimeError: maximum recursion depth exceeded
```

This seems like more of a problem with the user (me) than the software - what would be the correct way to select `resid in [10,14,19,60...14598]`.

**Comment by mnmelo** [comment]
Hi Tom.
The best way to act here is to index residues directly, as such:
```python
res_sel = universe.residues[[10,14,19,60,etc.]]
```
(and maybe offsetting the residue indices by 1, since they're 0-based in `universe.residues`.)

If you need to make further selections based on this set of residues you should use the `group` keyword:
```python
solvating = universe.select_atoms("resname SOL and around 10 group funky_residues",
                                   funky_residues = res_sel)
```
Let us know if it does the trick.

**Comment by richardjgowers** [comment]
I'm not sure if resids are always 1 based?  A way to do this without relying on resids being sequential from 1 is

``` python
u = mda.Universe('adk.psf','adk_dims.dcd')

import numpy as np

residx = [1, 5, 7]

u.residues[np.in1d(u.residues.resids, residx)]
```

So what's happening is `np.in1d(a, b)` creates a boolean mask of where `a` is in `b`, and then you're slicing u.residues with that boolean mask

**Comment by orbeckst** [comment]
Technically, that is a bug but in practice I am not really sure how to fix it without completely rewriting our parser.

For right now, the slicing work-around seems your best option, sorry!

**Comment by tomnewport** [comment]
Thanks - in the end I used a (possibly rather inefficient) workaround:

    residue_id_list = [1,3,10,65,...,11931]
    universe.select_atoms("group residue_list", residue_list=[residue for residue in universe.residues if residue in residue_id_list]

**Comment by richardjgowers** [comment]
Ok thanks, let us know if you have any other problems

**Comment by orbeckst** [comment]
@richardjgowers, we should leave the issue open or say "wont fix" because technically it's a bug. I leave it up to you. 


--
Oliver Beckstein
email: orbeckst@gmail.com


Am Feb 13, 2016 um 9:08 schrieb Richard Gowers <notifications@github.com>:

**Comment by richardjgowers** [comment]
Once 0.14 releases we can use the implicit or too (which isn't recursive),
so this will only apply to trying to OR enough different selections that we
hit the recursion limit (900ish)
