### ISSUE TITLE
Residues, Segments should refer to downward levels in index order

### ISSUE THREAD

**Issue by dotsdl** [MDAnalysis/mdanalysis#704]
This is an issue for the `issue-363` branch, featuring the new topology system.

The following illustrates the problem:

``` python
import MDAnalysis as mda
from MDAnalysisTests.datafiles import GRO, XTC

u = mda.Universe(GRO, XTC)

r = u.residues[3]

# should be in atom-index order...
r.atoms.ix

s = u.segments[0]

# should be in residue-index order...
s.residues.ix

# also should be in atom-index order...
s.atoms.ix
```

This problem appears rooted in the `MDAnalysis.core.topology.TransTable` object, specifically in how `_atom_order` and `_res_order` are built. I'm not immediately grokking the careful work that `MDAnalysis.lib.mdamath.one_to_many_pointers` does to make all this work, but @richardjgowers could probably easily fix the problem.

**Comment by richardjgowers** [comment]
got done in #1014
