### ISSUE TITLE
All knownfailure tests return errors with numpy 1.11

### ISSUE THREAD

**Issue by rathann** [MDAnalysis/mdanalysis#707]
I'm getting these errors when running tests on Fedora rawhide (pre-24). The all pass on Fedora 23, but I have no idea where to look for clues.
```
$ /usr/bin/python2 MDAnalysisTests-0.13.0/MDAnalysisTests/mda_nosetests -v --processes=4 --process-timeout=120
...
======================================================================
ERROR: test_dimensions (MDAnalysisTests.coordinates.test_pdb.TestPDBReader)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILDROOT/python-MDAnalysis-0.13.0-2.fc24.x86_64/usr/lib/python2.7/site-packages/MDAnalysisTests/plugins/knownfailure.py", line 45, in inner
    if _check_plugins_loaded() and loaded_plugins["KnownFailure"].enabled:
KeyError: 'KnownFailure'
-------------------- >> begin captured logging << --------------------
MDAnalysis.core.AtomGroup: DEBUG: Universe.load_new(): loading /builddir/build/BUILDROOT/python-MDAnalysis-0.13.0-2.fc24.x86_64/usr/lib/python2.7/site-packages/MDAnalysisTests/data/adk_open.pdb...
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: test_dimensions (MDAnalysisTests.coordinates.test_pdb.TestPSF_PDBReader)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILDROOT/python-MDAnalysis-0.13.0-2.fc24.x86_64/usr/lib/python2.7/site-packages/MDAnalysisTests/plugins/knownfailure.py", line 45, in inner
    if _check_plugins_loaded() and loaded_plugins["KnownFailure"].enabled:
KeyError: 'KnownFailure'
-------------------- >> begin captured logging << --------------------
MDAnalysis.topology.PSF: DEBUG: PSF file /builddir/build/BUILDROOT/python-MDAnalysis-0.13.0-2.fc24.x86_64/usr/lib/python2.7/site-packages/MDAnalysisTests/data/adk.psf: format STANDARD
MDAnalysis.core.AtomGroup: DEBUG: Universe.load_new(): loading /builddir/build/BUILDROOT/python-MDAnalysis-0.13.0-2.fc24.x86_64/usr/lib/python2.7/site-packages/MDAnalysisTests/data/adk_open.pdb...
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: test_PDBReader (MDAnalysisTests.test_streamio.TestStreamIO)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILDROOT/python-MDAnalysis-0.13.0-2.fc24.x86_64/usr/lib/python2.7/site-packages/MDAnalysisTests/plugins/knownfailure.py", line 45, in inner
    if _check_plugins_loaded() and loaded_plugins["KnownFailure"].enabled:
KeyError: 'KnownFailure'

----------------------------------------------------------------------
Ran 3383 tests in 219.355s

FAILED (SKIP=2, errors=3)
```

**Comment by rathann** [comment]
Versions of dependencies:

Name | version in F23 | version in F24
---- | --------------- | ---------------
Cython | 0.22-2.fc23 | 0.23.4-1.fc24
netcdf4-python | 1.1.6-2.fc23 |  1.1.6-4.fc24
numpy |  1.9.2-2.fc23| 1.11.0-0b2.fc24
python-biopython | 1.66-3.fc23 | 1.66-3.fc24
python-devel | 2.7.10-8.fc23 | 2.7.11-3.fc24
python-networkx | 1.9.1-4.fc23 | 1.10-1.fc24
python-nose | 1.3.7-4.fc23 | 1.3.7-7.fc24
python-setuptools | 18.0.1-2.fc23 | 19.6.2-2.fc24
python-sphinxcontrib-napoleon | 0.2.9-2.fc23 | N/A (included in python-sphinx)
python-sphinx | 1.2.3-4.fc23 | 1.3.1-4.fc24
python2-GridDataFormats | 0.3.2-2.fc23 | 0.3.2-2.fc24
python2-matplotlib | 1.4.3-11.fc23 | 1.4.3-11.fc24
python2-tempdir | 0.6-1.fc23 | 0.6-1.fc24

**Comment by mnmelo** [comment]
I'm looking into it.

**Comment by mnmelo** [comment]
After some fighting with a vagrant box I am being able to reproduce your error (didn't try F23).
Stay tuned.

**Comment by mnmelo** [comment]
Ok, found the problem.

The latest version of `numpy` changed its `KnownFailure` API. The class is now actually `KnownFailurePlugin`. The old name was also kept (for backwards compatibility, I presume). This breaks the internals of our wrapper around the plugin, which rely (unpythonically) on the class name.

We hadn't bumped into it ourselves probably because most of us are using stabler distros that package `numpy < 1.11`.

Fixing this is straightforward, but we usually don't backport. Is release 0.13.0 a must for you, or can you wait for the soon-to-be-released 0.14.0?

I'm relabeling the issue.

**Comment by kain88-de** [comment]
I didn't run into this problem. How new is that numpy release (I usually build all python packages myself with current releases)

**Comment by mnmelo** [comment]
Apparently it's still the beta for the next release. Fedora rawhide people really live on the bleeding edge!

I'll have to do more research to find out whether the API change is likely to stick until proper `numpy 1.11` release.

**Comment by mnmelo** [comment]
I found the [commit](https://github.com/numpy/numpy/commit/70c5052a9f07025c236033cf629506bb38eb6d97) where this change was made to numpy. It seems it will stick, and anyway I'll fix our plugin so that it's compatible either way.
@rathann, is it ok to wait for 0.14?

**Comment by rathann** [comment]
@mnmelo sure, no need to backport to 0.13.x as the package is still under review for inclusion into Fedora (and must thus build on Fedora development branch). I can wait for 0.14 or do the backport myself. Thanks a lot for identifying the issue!

**Comment by kain88-de** [comment]
@rathann so the fix works for you?

**Comment by rathann** [comment]
It does work, thank you.
