### ISSUE TITLE
analysis.rms.RMSD: group RMSD calculation should not superimpose

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/mdanalysis#720]
At the moment, doing a calculation for individual groups with `analysis.rms.RMSD(..., groupselections=[...])` calculates the RMSD for each sub-group with `qcp.CalcRMSDRotationalMatrix()`, which does an implicit rotational superposition (and there is no translational superposition at the moment so the results are not very meaningful). However, that was not the original intent of the subselection functionality (which is still marked _experimental_). We wanted to calculate the RMSD of parts after the whole protein was superimposed using a usually different selection in order to get a better understanding of which parts of the protein contribute more to the overall RMSD or are strongest affected by the superposition. 

Thus the RMSD for subgroups should just be calculated with the simple `rms.rmsd(..., superposition=False)` metric (after PR #714 is merged).

Additionally, one could add a keyword to switch the behavior to  do a full translation/rotation superposition; the function would then just do multiple RMSD calculations for multiple groups in one go.

**Comment by abhinavgupta94** [comment]
I am working on this issue. Can someone provide a little more insight into what exactly is required? How are multiple groups created for RMSD calculations?
