### ISSUE TITLE
Large .gro files (>100000 residues) have incorrect residue numbering

### ISSUE THREAD

**Issue by tomnewport** [MDAnalysis/mdanalysis#728]
I have .gro file with over 99999 residues, so there's a point where it looks like this:

```
99993W        W24409   5.197  38.171   2.358  0.0392  0.2897  0.1634
99994W        W24410  46.548  35.562   3.925  0.0041 -0.0044 -0.2686
99995W        W24411  41.678  11.567   4.117 -0.0489  0.2279  0.0398
99996W        W24412  32.466  10.908   2.439  0.0176  0.0328  0.2482
99997W        W24413  12.719  46.133   1.389  0.3063 -0.2728 -0.1758
99998W        W24414  15.130  10.483   9.969 -0.0133  0.2911  0.0727
99999W        W24415  11.716  36.838   1.308 -0.0390  0.1237  0.0310
    0W        W24416  40.024  47.039  11.701  0.0180 -0.0193  0.1456
    1W        W24417   8.068  42.350  10.090  0.1637 -0.0463  0.0713
    2W        W24418   4.284  28.808  10.156  0.1226  0.4642  0.0802
    3W        W24419  23.977  40.007  10.608 -0.0688  0.1545  0.1058
    4W        W24420  43.318  30.071   9.808 -0.1199 -0.1253 -0.1616
    5W        W24421   6.697  24.131  11.544 -0.0203  0.2435 -0.2320
    6W        W24422   1.650  36.335  10.132  0.0300 -0.1128 -0.3979
    7W        W24423   0.771  17.546   5.260  0.1603  0.0087  0.1779
    8W        W24424  49.619   4.969   9.924 -0.0225  0.0800 -0.4119
    9W        W24425  51.452  43.795   9.936  0.2769  0.0756 -0.1641
```

If I load this into MDAnalysis, the atom numbering is correct, however residue numbering is incorrect - as you can see below, residue 1 now includes a water molecule, which is incorrectly numbered as 1 (should be 100001).

```
    >>> universe.residues[0]
    <Residue POPE, 1>
    >>> universe.residues[0].atoms[-1]
    <Atom 324417: W of type W of resname W, resid 1 and segid SYSTEM>
    >>> u.atoms[224416].residue
    <Residue POPE, 1>
    >>> u.atoms[224416].resid
    1
```

Can I propose the following correction to `mdanalysis/package/MDAnalysis/topology/GROParser.py
` (line 45 onwards, new code surrounded by ###triple hashes###):

``` python
class GROParser(TopologyReader):
    format = 'GRO'

    def parse(self):
        """Parse GRO file *filename* and return the dict `structure`.
        Only reads the list of atoms.
        :Returns: MDAnalysis internal *structure* dict
        .. SeeAlso:: The *structure* dict is defined in
                     :func:`MDAnalysis.topology.base`.
        """
        segid = "SYSTEM"
        atoms = []
        with openany(self.filename, "rt") as grofile:
            grofile.readline()
            natoms = int(grofile.readline())
            ### ADDED CODE
            resid_correction = 0
            ### 
            for atom_iter in range(natoms):
                line = grofile.readline()
                try:
                    resid, resname, name = int(line[0:5]), line[5:10].strip(), line[10:15].strip()
                    ### ADDED CODE
                    resid = int(resid)
                    if resid == 0:
                        resid_correction += 100000
                    resid += resid_correction
                    ###
                    # guess based on atom name
                    elem = guess_atom_element(name)
                    atype = elem
                    mass = get_atom_mass(elem)
                    charge = guess_atom_charge(name)
                    # segid = "SYSTEM"
                    # ignore coords and velocities, they can be read by coordinates.GRO
                except:
                    raise IOError("Couldn't read the following line of the .gro file:\n"
                                  "{0}".format(line))
                else:
                    # Just use the atom_iter (counting from 0) rather than
                    # the number in the .gro file (which wraps at 99999)
                    atoms.append(Atom(atom_iter, name, atype, resname, resid,
                                      segid, mass, charge, universe=self._u))
        structure = {'atoms': atoms}

        return structure
```

(sorry for the lack of a proper pull request - I'm pushed for time today but I'll figure out how to do it in future)

**Comment by tylerjereddy** [comment]
I discussed with @tomnewport briefly (he sits behind me) and he will try to open a PR when he has some time.

**Comment by tylerjereddy** [comment]
For reference, the recent issue dealing with enormous .gro files:  #550

**Comment by richardjgowers** [comment]
Yeah the fix looks good, it just needs a test (should be able to use a small file with resids that wrap)

**Comment by orbeckst** [comment]
Just make sure that you don't hardcode the offset as 100,000 but instead use the highest one so far.

**Comment by dotsdl** [comment]
@richardjgowers just to note this shouldn't be a problem under the new topology system, since under that `resids` are just labels that don't have anything to do with actual residue identity, and also as written the GRO reader does not use the resid field to build the residue array anyway.

Is that correct? If so it's something we should check we don't regress on once we do that (awful) merge.

**Comment by richardjgowers** [comment]
@dotsdl I'm not entirely sure.  I think we said the resids should appear as-is, but the parser still needs to do a little work to give the wrapped resids a different resindex.

**Comment by dotsdl** [comment]
@richardjgowers the residues get whatever resindex the parser gives them; it is ultimately up to how the parser defines what a residue is from the file contents. Looking again at [the 363 GRO parser](https://github.com/MDAnalysis/mdanalysis/blob/issue-363/package/MDAnalysis/topology/GROParser.py#L72), it looks like it's set up to determine real residues based on resid alone, not contiguity. So, given that, this issue would be present for the parser as well.

**Comment by dotsdl** [comment]
Adding "fixed by 363" tag, not because 363 automatically fixes this, but that it *should* get fixed and done with.

**Comment by tylerjereddy** [comment]
Let's say I have an input `gro` file with > 100,000 residues that are incorrectly numbered, and possibly with some redundant residue numbers as well. If this issue is resolved, would MDAnalysis be able to trivially write a new `.gro` file with the correct (i.e. consecutive, non-redundant) residue numbers (i.e., all read/ write / access operations for the residues would use the consecutively numbered values from 1 to N residues)? I suppose the .tpr might be needed for this?

If so, then I would definitely be motivated to patch this as I need that functionality.

However, based on what @dotsdl is saying above, I think one might actually have to provide an additional 'contiguous_resids' type flag and associated code to the parser to enforce this kind of behaviour?

**Comment by orbeckst** [comment]
One problem will be that for writing to GRO you will still be limited by the format – basically, you will write a "broken" GRO file no matter what (and unless we implement Gromacs-style hacks, see https://github.com/MDAnalysis/mdanalysis/issues/550#issuecomment-160891166).

**Comment by tylerjereddy** [comment]
Ok, it seems that `u = MDAnalysis.Universe('topology.tpr', 'coords.gro')` will do the trick for now in any case.

**Comment by orbeckst** [comment]
Is this still an open issue or was this fixed together with #886?

**Comment by jbarnoud** [comment]
I just encountered that issue, so it is not solved yet. It actually gets worse: indeed the misnumbered residues now gets merged with the residues they share an index with.

As an example, I use the plasma membrane model that is available on the [martini force field website](http://cgmartini.nl/index.php/example-applications2/lipid-membranes) as [`plasma_membrane.zip`](http://cgmartini.nl/images/applications/plasma/plasma_membrane.zip).

The file starts with:

```
Generated by trjconv : Insane-lipids-sim t=   0.00000
523703
    1POPX   NC3    1  44.63  61.16   7.79
    1POPX   PO4    2  44.24  61.07   7.54
    1POPX   GL1    3  44.46  61.04   7.14
    1POPX   GL2    4  44.24  60.89   6.96
    1POPX   C1A    5  44.81  61.32   6.92
    1POPX   C2A    6  45.01  61.27   6.57
    1POPX   D3A    7  45.30  61.22   6.22
    1POPX   C4A    8  45.53  61.49   6.28
```
However the first residue is displayed as being a water bead with residue 0:

```python
>>> u.residues.resnames
array(['W', 'POPX', 'POPX', ..., 'W', 'W', 'W'], dtype=object)
```

Residue 1 contains some water:

```python
>>> u.residues[1].atoms.names
array(['NC3', 'PO4', 'GL1', 'GL2', 'C1A', 'C2A', 'D3A', 'C4A', 'C1B',
       'C2B', 'C3B', 'C4B', 'W', 'W', 'W'], dtype=object)
>>> u.residues[1].atoms.indices
array([     0,      1,      2,      3,      4,      5,      6,      7,
            8,      9,     10,     11, 302862, 402862, 502862])
```

The same system converted to PDB does not have the same issue.

**Comment by jbarnoud** [comment]
@richardjgowers I tried @tomnewport's fix and it works.

**Comment by richardjgowers** [comment]
Yeah I'm just doing that in the new parser with tests etc
