### ISSUE TITLE
Syntax error in `plot_nearest_neighbors()` method in `MDAnalysis.analysis.psa.py`

### ISSUE THREAD

**Issue by sseyler** [MDAnalysis/mdanalysis#738]
There is a syntax error on lines 1668–1670 where there is no operand before the `+` operator in the error string. (I [@sseyler] intend to correct this issue when I get a chance, if someone else doesn't get there before me.)

```python
if self._NN is None:
    err_str =                                                           \
            + "No nearest neighbor data; run "                          \
            + "'PSAnalysis.run_nearest_neighbors()' first."
```

**Comment by dotsdl** [comment]
Just replace this with:

```python
err_str = ("No nearest neighbor data; run "
           "'PSAnalysis.run_nearest_neighbors()' first.")
```

Strings adjacent to each other within parentheses are automatically concatenated.

**Comment by dotsdl** [comment]
Did the unit tests not catch this? Should add tests to test all parts of the class work as expected, even before execution of the main analysis.

**Comment by orbeckst** [comment]
See #597 ...

**Comment by dotsdl** [comment]
@sseyler could you please open a new issue detailing blind spots of current test coverage for `MDAnalysis.analysis.psa`? This particular problem has been fixed, but we want to guard against others that may be present in the codebase.
