### ISSUE TITLE
Box dimenions aren't updated when reading XTC/TRR files

### ISSUE THREAD

**Issue by kain88-de** [MDAnalysis/mdanalysis#740]
Currently we only update the positions/velocities/forces on XTC and TRR files. But the boxsize can change to. 

See https://groups.google.com/forum/#!topic/mdnalysis-discussion/pBKwaGvdumQ

**Comment by jbarnoud** [comment]
I found a way to quickly hack a fix for my immediate need. If you do not have time I can make it cleaner and submit a PR. Though, I am surprised that the XTC writer check that the box remains constant throughout the trajectory; what do you have against pressure coupling? :smile:

**Comment by kain88-de** [comment]
> what do you have against pressure coupling?

Unto thee it was shewed, that thou mightest know that the Thermodynamic Ensemble is **NVT**; there is none else besides it.

---

I have nothing against NPT. I just rarely use it. So I don't think about it a lot.

**Comment by orbeckst** [comment]
We need a test for checking proper reading of dimensions. Not reporting this properly is pretty bad.

**Comment by kain88-de** [comment]
I'll open a PR tomorrow when my laptop has internet again.  I also tests if box dimensions are handled correctly now. @jbarnoud did you notice anything else with xtc dimensions?

**Comment by jbarnoud** [comment]
Nothing else than the lack of update and the test in the writer. I 
expect the TRR to be the same.

**Comment by kain88-de** [comment]
I fixed it in both.
