### ISSUE TITLE
docs for LinearDensity missing

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/mdanalysis#746]
The actual class docs for `LinearDensity` at http://pythonhosted.org/MDAnalysis/documentation_pages/analysis/lineardensity.html are missing.

**Comment by richardjgowers** [comment]
The docs exist, I think it's just missing `.. automodule::`, and maybe `:members:`

http://www.sphinx-doc.org/en/stable/ext/autodoc.html

Should just be a case of copying what has worked in a neighbouring module
