### ISSUE TITLE
Depsy contributors

### ISSUE THREAD

**Issue by kain88-de** [MDAnalysis/mdanalysis#749]
See https://github.com/Impactstory/depsy/issues/47

Depsy doesn't list all our contributors right now because it is missing the github information.
The sparse docs suggest that they can parse that somehow from the PyPi metadata (no idea which field though).

My best guess would be that they look it up from the `download_url` field. We could point that to the github releases.

**Comment by richardjgowers** [comment]
https://github.com/MDAnalysis/mdanalysis/blob/develop/package/setup.py#L379

My guess is it's this line.  Maybe change this line so it slurps `AUTHORS`? (Might require reworking the format of AUTHORS to make it easily parsed)

**Comment by kain88-de** [comment]
They look only there because they can't figure out our github page from the PyPi meta-data. Other packages like [mdtraj](https://github.com/mdtraj/mdtraj/blob/1e37e386f21fb0d1d8a4134884b729d1b56d4876/setup.py#L243) also only list one author.

mdtraj is stating the `download_url` field so that might be used by them.

**Comment by richardjgowers** [comment]
Ah yeah weird, yeah maybe it's the link between pypi and github that's lacking

**Comment by kain88-de** [comment]
That field might be the way to establish the link. It would be nice to have anyway.

**Comment by orbeckst** [comment]
Yes, see https://groups.google.com/d/msg/mdnalysis-devel/qst3-Ri77n4/uQ_FMVI5CQAJ

**Comment by orbeckst** [comment]
However, I don't know how often (or if at all) depsy updates.

**Comment by orbeckst** [comment]
We could try changing the `download_url` to the GitHub tags although I feel kind of annoyed that we would need to change this away from PyPi where we have been hosting packages so far. I also can't get download stats for GitHub (I think); for pypi `vanity` works well and I actually use those numbers for proposals, as imperfect as they might be.

**Comment by orbeckst** [comment]
We can try it if no-one has any better ideas.

**Comment by kain88-de** [comment]
Is the download_url set automatically to PyPi? Because we don't explicitly set it in our setup.py

**Comment by orbeckst** [comment]
On 2 Mar, 2016, at 01:38, kain88-de wrote:

> Is the download_url set automatically to PyPi? Because we don't explicitly set it in our setup.py

Sorry, I hadn't even checked and just assumed. Then there seems to be little harm in just trying to set download_url to github (tags?).

--
Oliver Beckstein * orbeckst@gmx.net
skype: orbeckst  * orbeckst@gmail.com

**Comment by kain88-de** [comment]
http://depsy.org/package/python/GridDataFormats

for GridDataFormats the contributors are parsed correctly. In that package we point to github urls. So this might work.

**Comment by orbeckst** [comment]
Ok, change it.

On 2 Mar, 2016, at 16:47, kain88-de wrote:

> http://depsy.org/package/python/GridDataFormats
> 
> for GridDataFormats the contributors are parsed correctly. In that package we point to github urls. So this might work.
> 
> �
> Reply to this email directly or view it on GitHub.
> 

--
Oliver Beckstein * orbeckst@gmx.net
skype: orbeckst  * orbeckst@gmail.com

**Comment by orbeckst** [comment]
P.S.: If GridDataFormats is in th 96th percentile impact then there must be a LOT of dead wood on GitHub... not that I think the GridDataFormats is total rubbish but it clearly is also not one of these things that completely transforms the way we do science ;-)

On 2 Mar, 2016, at 16:47, kain88-de wrote:

> http://depsy.org/package/python/GridDataFormats
> 
> for GridDataFormats the contributors are parsed correctly. In that package we point to github urls. So this might work.
> 

--
Oliver Beckstein * orbeckst@gmx.net
skype: orbeckst  * orbeckst@gmail.com

**Comment by kain88-de** [comment]
Since they look and pypi I would assume that there is a LOT of dead wood on it. Counting all the packages which haven't been upgraded in years.

**Comment by orbeckst** [comment]
I'll hack it in. It's easy (so I am still able to do it ;-) ) but I also don't think that new contributors should be encouraged to edit our meta data.

**Comment by orbeckst** [comment]
I have no idea how often [Depsy](https://github.com/Impactstory/depsy/) updates. I am closing this issue for now and if we don't see any changes at https://github.com/MDAnalysis/mdanalysis then we can reconsider.
Once all committers are properly accounted for we can also close  Impactstory/depsy#47.

**Comment by orbeckst** [comment]
Afterthought: until we publish a new release on PyPi with the new meta data, I don't expect to see any changes.
