### ISSUE TITLE
IPython auto-import bug

### ISSUE THREAD

**Issue by kain88-de** [MDAnalysis/mdanalysis#754]
### Expected behaviour

importing mdanalysis into ipython on startup shouldn't have any effect on ipython

### Actual behaviour

when Import MDAnalysis into ipython during the start up (writing a file into the `startup` folder of the configration directory) I get a warning message out deprecated ipython display formatrs

For example save the following in `$HOME/.ipython/profile_default/startup/00-science.py`

```python
import MDAnalysis as mda
```

Then the first thing printed to the console after ipython has started will trigger the deprecation warnings.

### Currently version of MDAnalysis:
0.14.0

Ipython version = 4.0.3

**Comment by jbarnoud** [comment]
I get deprecation display format with a bunch of modules that are not related with MDAnalysis, especially matplotlib. I wonder if it is not related to jupyter moving faster than ather libraries we may use.

**Comment by kain88-de** [comment]
No the issue only pops up for me when I import MDAnalysis on startup. I'll check with the IPython devs what might be going on.

**Comment by khuston** [comment]
I guess my ipython is somewhat old now, I don't get deprecation warnings on 3.1.0

**Comment by orbeckst** [comment]
Is this here still an issue or can we close it?

**Comment by kain88-de** [comment]
It's still an issue for me. I haven't found out what causes this yet. But it might be a save bet that it is related to ipython rather then us.

**Comment by kain88-de** [comment]
Nope it's been us.
