### ISSUE TITLE
change_release.sh doesn't remove `-dev0`

### ISSUE THREAD

**Issue by kain88-de** [MDAnalysis/mdanalysis#776]
### Expected behaviour

`maintainer/change_release 0.15.0`

This should remove the `-dev0` ending in all the version strings we have.

### Actual behaviour

Only the numbers are replaced.

I'm not completely understanding the SED regexes that we are using here. The solution would either be to replace the SED regexes or to rewrite the script in python

**Comment by jdetle** [comment]
Hi there, I believe I fixed the problem.
