### ISSUE TITLE
atomgroup_intersection IndexError for empty TopologyGroup

### ISSUE THREAD

**Issue by khuston** [MDAnalysis/mdanalysis#780]
### Expected behaviour
If an empty bonds TopologyGroup is asked for its intersection with some atom group, it should return an empty TopologyGroup or an empty list.

### Actual behaviour
`IndexError: index 0 is out of bounds for axis 0 with size 0`

### Code to reproduce the behaviour

``` python
import MDAnalysis as mda
u = mda.Universe('atoms_without_bonds.pdb')
u.atoms.bonds.atomgroup_intersection(u.atoms)

```
I just noticed this while writing the LAMMPS data writer. The writer could check to make sure the topology group isn't of length zero first, but it seems like it'd be preferable if every writer didn't have to catch the error or check for `len(atoms.bonds) == 0`.

### Currently version of MDAnalysis:
0.13.0-dev0 (branch issue-363)

**Comment by khuston** [comment]
This is blocking `mda.Merge`, so I'm planning to just add a check to the beginning of `atomgroup_intersection`:

        # Issue #780 - if self is empty, return self
        if len(self._bix) == 0:
            return self

before it goes on to generate the mask. The problem is if the topology group is empty, the generated mask is not a list of bools, but a single bool value `False`, and then `return self[False]` goes on to cause an error.

**Comment by richardjgowers** [comment]
Hey, sorry missed this one.  Yeah, that can actually boil down to
```python
if not self:
    return self
```
But definitely leave a comment as it's very confusing!
