### ISSUE TITLE
Dynamic author list

### ISSUE THREAD

**Issue by richardjgowers** [MDAnalysis/mdanalysis#784]
So currently there's 2 lists of authors, there's AUTHORS and then there's the one everyone (including myself) forgets in `https://github.com/MDAnalysis/mdanalysis/blob/develop/package/doc/sphinx/source/conf.py`.  These lists are slightly different as AUTHORS is chronological, whereas for doc purposes we want almost alphabetical (see conf.py).

It would be preferable if `MDAnalysis.__authors__` got the author list, then sphinx could just import this like it does for version (again see conf.py).

The only thing I'm not sure about, is because AUTHORS exists in `package`, can we import it in `MDAnalysis.__init__` or does `setup.py` have to do some magic to make it visible to the python within the package?

**Comment by jbarnoud** [comment]
> The only thing I'm not sure about, is because AUTHORS exists in package, can we import it in MDAnalysis.__init__ or does setup.py have to do some magic to make it visible to the python within the package?

There is no guaranty that the AUTHOR file will be present at run time to populate `MDAnalysis.__authors__`. But `setup.py` could create a `__authors__.py` file with the list of authors. We would then import that file in `__init__.py`.

**Comment by richardjgowers** [comment]
Yeah I was going to write a nasty hack that opened `../AUTHORS` and realised that might be the case :D

**Comment by jbarnoud** [comment]
Currently, the doc lists Naveen first and Oliver last while the other authors are listed more or less alphabetically. Should I keep this like that? Or do I simply list the authors alphabetically?

**Comment by jbarnoud** [comment]
Also Elizabeth is second in the author list.

**Comment by jbarnoud** [comment]
ping @orbeckst

**Comment by jbarnoud** [comment]
Nevermind, the comment is clear that it is in purpose. I'll stick with that order.

**Comment by richardjgowers** [comment]
Sorry, I should have checked this when I merged, but it doesn't look like accents are working when you print from 
``` python
import MDAnalysis as mda
print mda.__authors__
u'S\xe9bastien Buchoux'
```
But it looks fine in [the docs](http://www.mdanalysis.org/mdanalysis/documentation_pages/overview.html) in the footer.

Is this just a limitation of how we have to store the string?

**Comment by jbarnoud** [comment]
If you print the list, then you print the repr of each of the strings it contains, not the strings themselves. The the u and the quote are good indications that it is not the string content that is printed.

if you print the names you have the accents displayed as expected:

```python
for name in MDAnalysis.__authors__:
    print name
```

```
...
Sébastien Buchoux
...
```

My PR broke some tests about relative imports, though. I'll submit a new PR to fix them.
