### ISSUE TITLE
MultiPDBWriter is returned even if multiframe is False

### ISSUE THREAD

**Issue by jbarnoud** [MDAnalysis/mdanalysis#788]
### Expected behaviour

When asking for a not multiframe PDB writer, the PDB writer should be a single frame writer.
### Actual behaviour

The writer is `MultiPDBWriter`.

The issue was uncovered by @abhinavgupta94 in #764.
### Code to reproduce the behaviour

``` python
import MDAnalysis as mda
writer = mda.Writer('test.pdb', multiframe=False)
```
### Currently version of MDAnalysis:

0.14.0-dev0

**Comment by jdetle** [comment]
I'll take a look at this tonight since it relates to #812

**Comment by jbarnoud** [comment]
This looks to be solved:

```
>>> import MDAnalysis as mda
>>> writer = mda.Writer('test.pdb', multiframe=False)
>>> writer
< PDBWriter 'test.pdb' >
>>> writer.multiframe
False
>>> mda.__version__
'2.0.0-dev0'
```
