### ISSUE TITLE
Coverage is not reported for the analyses

### ISSUE THREAD

**Issue by jbarnoud** [MDAnalysis/mdanalysis#804]
Since #743 got accepted, we mandate tests for the analysis modules. Yet, [coverall](https://coveralls.io/github/MDAnalysis/mdanalysis) does nor report the test coverage for these modules. This makes the review of PR like #803 more difficult.

**Comment by richardjgowers** [comment]
Yep just needs switching back now

**Comment by jbarnoud** [comment]
@richardjgowers what does it take? Is it something to change in .travis.yml? Ot in coverall config? I did not find the culprit in .travis.yml.

**Comment by jbarnoud** [comment]
Nevermind, found it in .coveragerc.
