### ISSUE TITLE
hbond analysis returns 1-based atom indices instead of canonical 0-based ones

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/mdanalysis#807]
As mentioned in https://github.com/MDAnalysis/mdanalysis/issues/801#issuecomment-202620721 , `MDAnalysis.analysis.hbonds.HydrogenBondAnalysis` stores the `donor_idx` and the `acceptor_idx` as atom index + 1. This is not properly documented and *very* confusing because one then has to subtract 1 for slicing (e.g. `u.atoms[hbanalysis.table.donor_idx - 1]`): if you're lucky, you get an `IndexError` for out of bounds, if you're unlucky you get wrong results without any hint that something went terribly wrong.

Possible solutions:

1. ~~Properly document current behavior with a big note.~~
2. ~~Break the code to return proper atom indices.~~
3. Add another column to the output with proper 0-based indices (name it `donor_atom_indices` and `acceptor_atom_indices` just to be clear) and document properly.... *and work towards deprecating the 1-based data*

Any opinions?

## History
* 2016-0-20: go with option **3** + deprecation

**Comment by orbeckst** [comment]
Folks such as @richardjgowers or @alejob who've been working with the h-bond analysis: do you have an opinion?

**Comment by orbeckst** [comment]
I would  go with Option **3** (backwards compatible but correct behavior available), and deprecate `donor_idx` and `acceptor_idx` for release 1.0.

**Comment by richardjgowers** [comment]
As long as it's properly defined and documented it should be fine, 0/1 based indexing is a common issue and people should always be wary.  I'm not 100% familiar with the Analysis module, but I'd think that the best thing to return would be an actual AtomGroup, as this is the most unambiguous form possible

**Comment by alejob** [comment]
I think that option 3 is the best and also deprecate `donor_idx` and `acceptor_idx` in version 1.0, to correct definitely this issue. I'd also add two warning message, the first because maybe people that has already implemented code with this hasn't realized about the issue and the second to warn about the future deprecated feature.

**Comment by jdetle** [comment]
So is anyone working on this? If not, I'll go ahead and try to get something going working with option 3.

**Comment by richardjgowers** [comment]
I'm not sure what the point of option 3 is, won't it just be the same as another column but -1? (ie making results heavier for no gain)

**Comment by jdetle** [comment]
That sounds true. So you're +1 for just updating the docs to reflect that its 1-based?

**Comment by orbeckst** [comment]
Option 3 will provide a way for doing it the sane way with 0-based indexing so that we can deprecate the 1-based column and then get rid of it in 1.0 or earlier. Sure, it adds two columns that are just "other column - 1" but I take that small memory cost over clarity any day.

As @alejob says, it would be bad to just change the indexing from one release to the other because analysis code would break in non-obvious ways.

Returning an AtomGroup is not really an option in the context of the results table. Especially with the light-weight AGs from #363 we could add additional result attributes with the actual AGs but for the table it's useful to have the indices themselves.

**Comment by orbeckst** [comment]
Let's go with option **3**.

**Comment by orbeckst** [comment]
@jdetle if you want to work on this, assign to yourself once you do some hacking so that no-one else duplicates effort.

**Comment by jdetle** [comment]
@orbeckst I'm trying to figure out how to do that right now, I don't think I have the gearbox needed next to the assignee form to do it myself.
