### ISSUE TITLE
pip Installation does not work for a python 3 user

### ISSUE THREAD

**Issue by jdetle** [MDAnalysis/mdanalysis#808]
### Expected behaviour
pip install --upgrade MDAnalysis should 'just work'

### Actual behaviour
`Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip_build_jdetlefs/mdanalysis/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-RLxJ_v-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip_build_jdetlefs/mdanalysis`

Storing debug log for failure in /home/jdetlefs/.pip/pip.log
From the log:
```
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/lib/python2.7/dist-packages/numpy/core/include -IMDAnalysis/coordinates/include -I/usr/include/python2.7 -c MDAnalysis/coordinates/src/dcd.c -o build/temp.linux-x86_64-2.7/MDAnalysis/coordinates/src/dcd.o
MDAnalysis/coordinates/src/dcd.c:21:20: fatal error: Python.h: No such file or directory
#include <Python.h>
```
### To reproduce the behavior
On a fresh ubuntu 14.04 system, install python 3.5 with conda, and then follow pip installation instructions. Do not install python-dev.

I recognize that its kind of silly to use pip after downloading conda, but I still think that if this intended for scientists the installation instructions should be idiot-proofed. It would save some people some time to tell them on the website:

"If you have installed python 3.5, **do not try to use pip to install**, use conda to install. If you dont already have a python 2.7 virtual environment created, enter in terminal:
```
conda create -n py27 python=2.7 
source activate py27

```
then enter
```
conda config --add channels MDAnalysis
conda install mdanalysis
```

**Comment by jbarnoud** [comment]
I do not know with conda, but the error looks like the one you get when you do not have python header installed (on linux it would be some `python-dev` or `python-devel` package missing). I would expect that your python 3 setup cannot compile any C extensions; am I right?

**Comment by kain88-de** [comment]
```bash
conda create -n py35 python=3.5
source activate py35
pip install MDAnalysis
```

this works for me. You seem to have a problem that the development header for python aren't installed.

Did you delete all user installed packages after switching to conda? Some stuff that is lingering there could mess things up for you.

**Comment by jdetle** [comment]
It definitely was the fact that I didnt `sudo apt-get python-dev` before entering` sudo pip install mdanalysis`. It's kind of besides the point though, if a user hasn't installed python-dev, should they be made aware of the fact that it might be an issue?

**Comment by mnmelo** [comment]
That's a good point. AFAIK we can't tell `pip` to install python headers, so we should definitely fail more gracefully here.

**Comment by richardjgowers** [comment]
Is this a pip problem or a MDA problem though? Would installing eg numpy this way raise the same error?

**Comment by kain88-de** [comment]
Yes it would. But this is also a conda problem. It should ship the Python headers.

**Comment by jdetle** [comment]
Ignoring the cause, this is a problem that can turn what should be a very simple installation into a bit of a headache. I am not the most competent linux user but I am also not the least, there should be _some_ indication that this could be an issue on the installation guide. I.e., "if you have installed python with conda, install mdanalysis with conda as well"

**Comment by mnmelo** [comment]
Indeed. While researching whether `pip` could install dev sources for us (apparently it can't, but haven't seen anywhere why...) I came across this [SO post](http://stackoverflow.com/questions/12870186/python-headers-are-required-to-build-mercurial) that shows that mercurial handles the error a bit more gracefully.
We could also add the extra info @jdetle is proposing to the cleaner error.

**Comment by kain88-de** [comment]
@jdetle that you don't have `Python.h` is strange. I can find it on my conda install for the python3 environments. Can you run `find . -name 'Python*'` in the conda directory. That should list all headers it is finding. You are looking for lines like `...python3.5m/Python.h`.

**Comment by kain88-de** [comment]
A graceful warning message would still be nice.

**Comment by jdetle** [comment]
I have it in my conda directory, so yes, the error was weird.

**Comment by orbeckst** [comment]
I also agree that there should be a better warning message.

However, our instructions for [installing from source](https://github.com/MDAnalysis/mdanalysis/wiki/Installing-from-source) do state that you need **the Python header files (typically in a package python-dev)**.

I don't understand why conda + pip fails, though. On Travis (see [travis.yml](https://github.com/MDAnalysis/mdanalysis/blob/develop/.travis.yml) we do exactly that: conda installation, then pip install, no special Ubuntu packages installed.

**Comment by jdetle** [comment]
It certainly was some some user error that I didn't catch.

**Comment by orbeckst** [comment]
What was the error? Because if this can happen to other users, we'd like to know!

**Comment by jdetle** [comment]
I honestly am not sure. After looking through my bash history, when I first tried at midnight on Monday (first mistake was trying to sysadmin after midnight), I was using pip install instead of sudo pip install, but my pip log doesn't indicate that as being problem. The pip log I saved said I didn't have the python header, and after `sudo apt-get install -y build-essential python-dev python-setuptools python-pip` the pip install worked fine. (This was after a successful installation on conda)

**Comment by jdetle** [comment]
And I had just cloned the repo before that, if that means anything.

**Comment by mnmelo** [comment]
@orbeckst: my bet is that travis does pack the Python headers, even though their [ci-environment docs](https://docs.travis-ci.com/user/ci-environment/) aren't explicit about it.

Also, not all distros separate dev headers from Python binaries. For instance, installing Python from the packages at [python.org](python.org) always installs these headers. This is probably why there isn't a header package that one can `pip install`.

**Comment by hainm** [comment]
FYI: MDA developers can try to use [auditwheel](https://github.com/pypa/auditwheel) to build wheel for Linux. This is somewhat similar to conda but you can upload to pypi and can use pip (and no header file issue).

(try: `pip install pytraj`, the installation happens within seconds (pytraj/cpptraj is much heavy (mostly C++)): https://pypi.python.org/pypi/pytraj/1.0.3

**Comment by orbeckst** [comment]
Yes, I know, [PEP 0513 manylinux1](https://www.python.org/dev/peps/pep-0513/) and [auditwheel](https://github.com/pypa/auditwheel)  look very interesting. Good to know that it works for [pytraj](https://github.com/Amber-MD/pytraj)!

**Comment by orbeckst** [comment]
I read through the comments again and don't really find anything that can be resolved; if we can reproduce the error we can maybe spit out a better error message but in this case I ask that someone opens a new issue with a clear goal.
