### ISSUE TITLE
simple rms.rmsd() ignores weights option

### ISSUE THREAD

**Issue by kain88-de** [MDAnalysis/mdanalysis#814]
The `analysis.rms.rmsd` function doesn't weight a calculated rmsd when the weights are given

### Currently version of MDAnalysis:
(run `python -c "import MDAnalysis as mda; print(mda.__version__)"`)
0.15dev

**Comment by jdetle** [comment]
So you ran the change release script in your branch to change the version or am I missing something?

**Comment by kain88-de** [comment]
The next version will be 0.15 but we haven't updated all version strings yet (ping @richardjgowers )

**Comment by jdetle** [comment]
Right, I'm just confused. My branches in my working directory are 0.14.1-dev0, should I change them before I start trying to work on this?

**Comment by kain88-de** [comment]
No leave them as it is @richardjgowers should change this.

**Comment by richardjgowers** [comment]
Yeah I'll just change the strings when we release

**Comment by jdetle** [comment]
I've started to work on it? I am trying to understand how the weights are supposed to be factored in and I can't find it in the docs? Do you have any instructional material I could look at?

https://github.com/jdetle/notebooks/blob/master/WeightedRMSD.ipynb

**Comment by jdetle** [comment]
I'm borrowing my advisor's MD book so I'll go ahead and take care of this in the next few days.

**Comment by orbeckst** [comment]
@jdetle , start by looking at how it's done in [qcp.InnerProduct()](https://github.com/MDAnalysis/mdanalysis/blob/develop/package/MDAnalysis/lib/qcprot.pyx#L189). Perhaps the referenced papers by Theobald also mention how to do the mass-weighting. Along the lines of
```
weighted_pos[i] = weight[i] * pos[i]
```
Note that we have to calculate the weights in such a way that an atom with average mass gets a weight of 1: we already do this in the `rmsd()` function and name these weights `realtive_weights`.

**Comment by jdetle** [comment]
Will do. Have a nice flight!

**Comment by orbeckst** [comment]
Simple mass weighted RMSD (using LaTeX notation although GH comments don't allow MathJax... :-p... copy and paste into eg http://arachnoid.com/latex/ )

$$
    RMSD(x) = \sqrt{ \frac{1}{M} \sum_{i=1}^N m_i (\vec{x}_i - \vec{x}_0)^2}
$$

where $M$ is the total mass  $\sum_{i=1}^N m_i$.

This directly translates into using the relative weights $w_i = m_i/M$.

**Comment by jdetle** [comment]
That makes sense, thanks.

**Comment by jdetle** [comment]
@kain88-de @orbeckst I mentioned this in #823 but im moving it here.

@kain88-de I forgot to mention that I already figured out last night that this doesnt fix the weighting issue.  In the current code there exists no mention of returning an rmsd with weighting when weights is not none. 

@orbeckst said: 
> Simple mass weighted RMSD (using LaTeX notation although GH comments don't allow MathJax... :-p... copy and paste into eg http://arachnoid.com/latex/ )
> 
> $$
> RMSD(x) = \sqrt{ \frac{1}{M} \sum_{i=1}^N m_i (\vec{x}_i - \vec{x}_0)^2}
> $$
> 
> where $M$ is the total mass $\sum_{i=1}^N m_i$.
> 
> This directly translates into using the relative weights $w_i = m_i/M$.

This leads me to believe line 192 in the diff should be `relative_weights = np.asarray(weights) / np.sum(weights)`

Then we would go ahead and say:
```
if weights is not None:
   return np.sqrt(np.sum(relative_weights*( (a - b) ** 2) ) / N )
```

where `(relative_weights*((a - b) ** 2)`  should be a 1-by-3 matrix.

**Comment by kain88-de** [comment]
You need some [fancy indexing magic](http://docs.scipy.org/doc/numpy/reference/arrays.indexing.html#numpy.newaxis) to make this work properly. The correct line should be

```python
(relative_weights[:, np.newaxis] * ((a - b) ** 2)
```

This basically tells numpy to treat `relative_weights` like an array with shape `(N, 3)` where each column contains the original `relative_weights` array.

**Comment by jdetle** [comment]
Okay, I'm indisposed for the next few hours but I'll get it done tonight.
On Tue, Apr 12, 2016 at 2:12 PM kain88-de <notifications@github.com> wrote:

> You need some fancy indexing magic
> <http://docs.scipy.org/doc/numpy/reference/arrays.indexing.html#numpy.newaxis>
> to make this work properly. The correct line should be
>
> (relative_weights[:, np.newaxis] * ((a - b) ** 2)
>
> This basically tells numpy to treat relative_weights like an array with
> shape (N, 3) where each column contains the original relative_weights
> array.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/MDAnalysis/mdanalysis/issues/814#issuecomment-209105119>
>
-- 
Have a wonderful day,
John J. Detlefs

**Comment by jdetle** [comment]
@kain88-de when I do the fancy indexing magic I end up getting a shape (855,1) nparray, I'll have to figure out how to fix this but it isn't instantly obvious.
