### ISSUE TITLE
Mol2 files cannot be loaded in 0.14.0

### ISSUE THREAD

**Issue by ldomic** [MDAnalysis/mdanalysis#816]
### Expected behaviour

To get a universe from a mol2 file.

### Actual behaviour
Error trace:
``` python
/Users/lauradomicevica/anaconda/lib/python2.7/site-packages/MDAnalysis/coordinates/MOL2.pyc in _read_frame(self, frame)
    126 
    127         self.ts.data['molecule'] = sections["molecule"]
--> 128         self.ts.data['substructure'] = sections["substructure"]
    129 
    130         # check if atom number changed

KeyError: 'substructure'
```
### Code to reproduce the behaviour
Download mol2 file from http://zinc.docking.org/substance/856218 (Not specific to a single file - just as a test)
``` python
import MDAnalysis as mda

u = mda.Universe("zinc_856218.mol2")


```

**Comment by richardjgowers** [comment]
@ldomic thanks for the report, should be fixed once #817 goes through. We were previously requiring that the files have a substructure section (like below) but I guess there's files without that too, so this isn't a strict requirement any more.

```
@<TRIPOS>SUBSTRUCTURE
  1 Q101  19 GROUP 4 **** **** 0
```

**Comment by ldomic** [comment]
Thank you. Great, I will wait for that. @richardjgowers - did you implement this requirement only in 0.14.0? My code stopped working literary overnight when I updated MDAnalysis.

**Comment by richardjgowers** [comment]
@ldomic maybe requirement was the wrong word.  We changed where we stored the substructure data, and in doing so assumed that all files would provide this, so now you're getting errors because we're trying to store data that doesn't exist.
