### ISSUE TITLE
DCDReader.timeseries(skip=XX) behaves differently from standard numpy slicing

### ISSUE THREAD

**Issue by wouterboomsma** [MDAnalysis/mdanalysis#818]
### Expected behaviour
I would expect u.trajectory.timeseries(u.atoms, skip=10) to give the same result as u.trajectory.timeseries(u.atoms)[:,::10,:].

### Actual behaviour
Currently, the behaviour of timeseries corresponds to u.trajectory.timeseries(u.atoms)[:,9::10,:]

### Code to reproduce the behaviour

``` python
>>> universe = MDAnalysis.Universe(PSF, DCD)
>>> array = universe.trajectory.timeseries(universe.atoms)
>>>
>>> skip = 10  # desired frame interval
>>>
>>> print array.shape                 # shape of original array
(3341, 98, 3)
>>> print array[0,0,:]                # first coordinate of original array
[ 11.73604393   8.50079727 -10.44528103]
>>>
>>> filtered_array = universe.trajectory.timeseries(skip=skip)
>>> print filtered_array.shape        # shape
(3341, 9, 3)
>>> print filtered_array[0,0,:]       # first coordinate is at skip-1
[ 13.43769073   7.64272451  -8.87260437]
>>>
>>> filtered_array_np = array[:,::skip,:]
>>> print filtered_array_np.shape     # shape different from timeseries()
(3341, 10, 3)
>>> print filtered_array_np[0,0,:]    # first coordinate is at 0
[ 11.73604393   8.50079727 -10.44528103]
>>>
>>> filtered_array_np2 = array[:,skip-1::skip,:]
>>> print filtered_array_np2.shape    # recover timeseries() shape
(3341, 9, 3)
>>> print filtered_array_np2[0,0,:]   # recover timeseries first index
[ 13.43769073   7.64272451  -8.87260437]
```

### Currently version of MDAnalysis:
0.14.1

**Comment by orbeckst** [comment]
Is this a vestige from the days when trajectory indices were 1-based? Or it just mirrored the behavior of the CHARMM CORREL functionality.

Either way, I agree with you that we should be consistent, and we are definitely striving for "Pythonic".

**Comment by orbeckst** [comment]
@wouterboomsma is this something that holds up #797 ?

**Comment by wouterboomsma** [comment]
No no, not at all. I just changed the memory reader to use the Pythonic indexing style - which makes it inconsistent with how the DCDreader currently works, assuming that the DCDreader will change in the future.

**Comment by jdetle** [comment]
@orbeckst @wouterboomsma This seems to be a problem with the `_dcdmodule.__read_timeseries` function. I can't say any more until I see the C code.

**Comment by orbeckst** [comment]
@jdetle , assigning to you, given that you're hacking away on it in PR #916 .
