### ISSUE TITLE
GRO file with incomplete velocities causes read error.

### ISSUE THREAD

**Issue by BartBruininks** [MDAnalysis/mdanalysis#820]
### Expected behaviour
If a GRO is loaded with the unknown velocities set to zero -- to mimic the GROMACS behaviour.
If a GRO is loaded with no velocities at all, they should not be included.

### Actual behaviour
If no velocities are present in the GRO it is loaded without the velocities attribute.
If velocities are present in the GRO it is loaded with the velocities, but only if they all have velocities set.

### Code to reproduce the behaviour
incomplete_velocities.gro
```
Incomplete velocities
4
 1248DOPC   NC3    1   7.956  12.408   4.949   7.956  12.408   4.949  
 1248DOPC   PO4    2   7.736  12.290   4.671   7.956  12.408   4.949
 1248DOPC   GL1    3   7.760  12.150   4.329
 1248DOPC   GL2    4   7.896  11.896   4.235   7.956  12.408   4.949
  22.28307  22.28307  23.34569
```

``` python
import MDAnalysis as mda

u = mda.Universe('incomplete_velocities.gro')
#crash#

```

### Currently version of MDAnalysis:
0.14.0

**Comment by richardjgowers** [comment]
Is it possible/common for GRO files to only have some velocities defined?

**Comment by BartBruininks** [comment]
Yes, this could happen if somebody wants to preserve the velocities of lets say a protein after exchanging the solvent.
