### ISSUE TITLE
Debian packaging support

### ISSUE THREAD

**Issue by GoogleCodeExporter** [MDAnalysis/mdanalysis#83]
As a Debian/Ubuntu user, I think MDAnalysis lacks Debian packaging support. In order to correct that (and because I am working on a tool that depends on MDAnalysis), I created some packages to make the installation "cleaner" on Debian-like systems.

These packages are available here (they were built for Ubuntu 11.10 but should work fine on Debian unstable): https://launchpad.net/~seb-buch/+archive/sandbox

This is the PPA I use as a personal sandbox so the packages there are not meant to be official.
These packages were created using the 0.7.4 release (MDAnalysis-0.7.4.tar.gz and MDAnalysisTestData-0.7.4.tar.gz files).

I am not sure if you want if you want to add Debian packaging support but here are attached two diff files to add this feature to MDAnalysis. I used the trunk and the MDAnalysisTestData branches (rev 914 for both) for creating them.

If you are not familiar with Debian packages but want to add support for them, I may join the project to maintain them.

Original issue reported on code.google.com by `sebastie...@gmail.com` on 14 Nov 2011 at 10:22

Attachments:
* [python-mdanalysis_trunk_r914.diff.gz](https://storage.googleapis.com/google-code-attachments/mdanalysis/issue-83/comment-0/python-mdanalysis_trunk_r914.diff.gz)
* [python-mdanalysis.tests-data_branches_MDAnalysisTestData_r914.diff.gz](https://storage.googleapis.com/google-code-attachments/mdanalysis/issue-83/comment-0/python-mdanalysis.tests-data_branches_MDAnalysisTestData_r914.diff.gz)

**Comment by orbeckst** [comment]
We haven't been supplying distribution packages for a while so I am closing this issue.
Perhaps around 1.0 we revisit and see if we can get MDAnalysis into some of the common distribution's contributed repositories on a regular basis.
