### ISSUE TITLE
conda: version `GLIBC_2.14' not found

### ISSUE THREAD

**Issue by hainm** [MDAnalysis/mdanalysis#830]
Seems that someone need to build MDA with old OS (centos 5, ...)

### Expected behaviour
no import error

### Actual behaviour
version `GLIBC_2.14' not found

### Code to reproduce the behaviour

``` python
import MDAnalysis as mda
....

```

### Currently version of MDAnalysis:
MDAnalysis channel.

**Comment by kain88-de** [comment]
This happens on older linux systems because the conda binary has been build on Fedora 23.

I'm currently working on setting up a vagrant box that is compatible with the manylinux project.

**Comment by kain88-de** [comment]
@hainm I've uploaded the current dev version to my [anaconda-channel](https://anaconda.org/kain88-de/mdanalysis/files) can you give it a try.

**Comment by hainm** [comment]
same error

```bash
$ conda install mdanalysis -c MDAnalysis --force
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: ............
Solving package specifications: .........

Package plan for installation in environment /home/haichit/anaconda3/envs/py2:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    mdanalysis-0.14.0          |           py27_0        37.9 MB

The following packages will be UPDATED:

    mdanalysis: 0.14.0-py27_0 --> 0.14.0-py27_0

Proceed ([y]/n)? y
```

```python
$ python -c 'import MDAnalysis as m; print(m)'
```

....
ImportError: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /home/haichit/anaconda3/envs/py2/lib/python2.7/site-packages/MDAnalysis/lib/c_distances.so)

**Comment by kain88-de** [comment]
@hainm this isn't the version I build. I have published it on my own account `kain88-de` and the version number is also upgraded.

try `conda install mdanalysis -c kain88-de` and see what happens

**Comment by hainm** [comment]
Oh I see. I did not read carefully. I will try later, not at computer now.

**Comment by kain88-de** [comment]
It works for me now on SLES 11. I guess it will also for you then.

**Comment by hainm** [comment]
>  I guess it will also for you then.

confirmed

Can you please buid python 3.4, 3.5 too? I just need them to test [NGLView]: https://github.com/arose/nglview/blob/master/devtools/travis-ci/setup_env.sh#L23-L28 (install  from source is quite slow).

**Comment by kain88-de** [comment]
Cool I prepare the builds for the next release then we can close this.

**Comment by kain88-de** [comment]
I'll look at the Python 3 builds

**Comment by kain88-de** [comment]
glib builds are fixed now

**Comment by kain88-de** [comment]
@hainm you can find python 3 builds on [my anaconda channel](https://anaconda.org/kain88-de/mdanalysis/files)

**Comment by hainm** [comment]
Fantastic. Thx.

**Comment by hainm** [comment]
confirmed that yours work well on travis.

**Comment by kain88-de** [comment]
cool thanks
