### ISSUE TITLE
ENT efile extension should be recognized as PDB

### ISSUE THREAD

**Issue by jbarnoud** [MDAnalysis/mdanalysis#834]
".ent" is an extension that use to be common for PDB files. It is still in use in the PDB ftp server. If you download a copy of the whole PDB, you get file names pdbXXXX.ent.gz.

### Expected behaviour

Files with '.ent' as file extension are treated as PDB files.

### Actual behaviour

The extension is not recognized:

```
ValueError: Cannot autodetect topology type for file '/coarse/jon/pdb/qs/pdb1qsh.ent.gz' (file extension could not be parsed).
           You can use 'Universe(topology, ..., topology_format=FORMAT)' to explicitly specify the format and
           override automatic detection. Known FORMATs are:
           dict_keys(['DMS', 'XPDB', 'PDBQT', 'DATA', 'TPR', 'GRO', 'CONFIG', 'PSF', 'TOP', 'XYZ', 'HISTORY', 'CRD', 'PDB', 'GMS', 'MOL2', 'PQR', 'XML', 'PRMTOP', 'PARM7', 'Permissive_PDB'])
           See http://docs.mdanalysis.org/documentation_pages/topology/init.html#supported-topology-formats
           For missing formats, raise an issue at http://issues.mdanalysis.org
```

### Code to reproduce the behaviour

``` python
import MDAnalysis as mda

u = mda.Universe('pdb1bta.ent.gz')

```

### Currently version of MDAnalysis:
(run `python -c "import MDAnalysis as mda; print(mda.__version__)"`)

0.14.1-dev0 but I did not see recent changes on that respect.

**Comment by jdetle** [comment]
The current guess_format function in util.py checks tries to guess the format from the filename extension. There is no current format defined by 'ENT' but a quick hack in coordinates/core.py in the get_reader_for() function could fix this problem. Do you want me to go ahead and add the if/else or were you hoping we could do something less hacky?

**Comment by richardjgowers** [comment]
We don't need any hacks here.  A Reader can define a list of formats it supports

**Comment by jdetle** [comment]
Oh okay, for some reason I thought a reader could only have one format associated with it. In this case I'll go ahead and add the ENT format to the PDBReader
