### ISSUE TITLE
IOError: Source file 'MDAnalysis/coordinates/dcdtimeseries.c' not found

### ISSUE THREAD

**Issue by hainm** [MDAnalysis/mdanalysis#836]
Why testing MDA for our new [NGLView PR](https://github.com/arose/nglview/pull/67),
I got error installing MDA. Error above. I got it when I did not have cython.

``` python
Attempting to autodetect OpenMP support... Compiler supports OpenMP
Will attempt to use Cython.
Couldn't find a Cython installation. Not recompiling cython extensions.
Traceback (most recent call last):
  File "setup.py", line 449, in <module>
    exts, cythonfiles = extensions(config)
  File "setup.py", line 353, in extensions
    "failed/disabled Cython build.".format(source))
IOError: Source file 'MDAnalysis/coordinates/dcdtimeseries.c' not found. This might be caused by a missing Cython install, or a failed/disabled Cython build.
```

**Comment by orbeckst** [comment]
@mnmelo or @kain88-de  did you recently look at the cython stuff?

**Comment by richardjgowers** [comment]
I think this might be that develop requires cython while releases (main
branch) does not

**Comment by orbeckst** [comment]
Am Apr 29, 2016 um 12:15 schrieb Richard Gowers <notifications@github.com>:

> I think this might be that develop requires cython while releases (main
> branch) does not

Did we update the wiki docs somewhere to point out what is required for working with the development branch?

In any case, a useful error message should be provided along the lines of "Your are using a development version of MDAnalysis. You must have cython installed. For more details see WIKI URL. "

**Comment by kain88-de** [comment]
@orbeckst see #799 there are some outstanding comments left. I hope @mnmelo finds time for that soon.

This will also fix this issue.

**Comment by mnmelo** [comment]
On it (all of the issues the last couple of weeks I've been unable to tend to).

**Comment by kain88-de** [comment]
@hainm this problem should go away if you build from the master branch. You need to switch manually because we have set 'develop' to be the default.

**Comment by hainm** [comment]
I just want to report this issue since I always have Cython. I got that problem when trying new conda env and forgot to add cython.
