### ISSUE TITLE
Inserted residues in PDB files cannot be individually selected

### ISSUE THREAD

**Issue by tomnewport** [MDAnalysis/mdanalysis#839]
### Expected behaviour

The PDB format includes an iCode (insertion code) field which extends residue IDs to give inserted residues unique identifiers. Three residues inserted between resid 163 and 164 would become 163A, 163B and 163C. This allows insertion of residues while maintaining consistency with the original numbering.

Using PyMol the following selections work as intended:

```
PyMOL>fetch 1osm
PyMOL>select sele, resid 163; select sele resid 163A
 Selector: selection "sele" defined with 18 atoms.
 Selector: selection "sele" defined with 39 atoms.
```

I would expect those selection strings to produce the same results in MDAnalysis.
### Actual behaviour

`resid 163` actually selects residue 163 and 10 inserted residues (A through J) in the PDB deposition.

`resid 163A` results in an error : 'Failed to parse number: 163A'.
### Code to reproduce the behaviour

Bash (for anyone in a hurry):

``` bash
$ python -i -c 'import MDAnalysis as mda; import urllib; downloader = urllib.URLopener(); downloader.retrieve("http://files.rcsb.org/download/1osm.pdb", "1osm.pdb"); u = mda.Universe("1osm.pdb")'
>>> u.select_atoms("resid 163")
<AtomGroup with 204 atoms>
>>> u.select_atoms("resid 163A")
MDAnalysis.exceptions.SelectionError: Selection failed: 'Failed to parse number: 163A'
```

Or Python:

``` python
import MDAnalysis as mda
import urllib; downloader = urllib.URLopener()
downloader.retrieve("http://files.rcsb.org/download/1osm.pdb", "1osm.pdb")
u = mda.Universe("1osm.pdb")
print u.select_atoms("resid 163")
print u.select_atoms("resid 163A")
```
### Currently version of MDAnalysis:

0.14.0

**Comment by orbeckst** [comment]
Is this something that could be easily implemented with the new topology system #363 – @richardjgowers / @dotsdl ?

**Comment by dotsdl** [comment]
With the new topology system we wouldn't make insertion codes part of the resid (to keep them integers), but we could make them a separate property for residues. Basically, there would be multiple residues with `resid` '163', but `icode` could be used to distinguish them like:

```python
u.select_atoms('resid 163 and icode B')
```

Internally `icode` would be an array of strings with total length the number of residues in the system. Most of these would be empty strings (`''`) or perhaps single spaces. This should be easy to implement since resids don't have to be unique under the new scheme; they're just a residue attribute like any other.

**Comment by kain88-de** [comment]
@dotsdl is this already fixed in the issue 363 branch? If not please remove the label again until it is fixed in the branch.

**Comment by richardjgowers** [comment]
@kain88-de I pushed a few fixes to icodes just now which allow the following:
```python
In [5]: u.select_atoms('resid 163 and icode A')
Out[5]: <AtomGroup with 21 atoms>
```

That said, the PDBParser is grouping all resid 163 atoms into a single residue, so this needs to be fixed to properly create many resid 163 residues as @dotsdl said above.

**Comment by dotsdl** [comment]
@kain88-de the tag indicates that it **should** be solved by 363 (as in, rather easily), so we don't lose track of it. You're right that at the moment the branch doesn't address this.

**Comment by richardjgowers** [comment]
Ok this is now implemented in the 363 branch.  PDBParser will correctly split resid 163 and resid 163 with icode A into two residues upon universe creation.  Currently the resid is left as an integer, with the icode as another field/attribute, so to select you would need to do `u.select_atoms('resid 163 and icode A')`.

I could append the icode onto the resid, ie create `resid 163A`, but this would then make the array have mixed type, or type `object` which isn't ideal really.

**Comment by orbeckst** [comment]
No, keep iCode as an attribute. 

--
Oliver Beckstein
email: orbeckst@gmail.com


> Am Oct 1, 2016 um 11:13 schrieb Richard Gowers <notifications@github.com>:
> 
> I could append the icode onto the resid, ie create resid 163A, but this would then make the array have mixed type, or type object which isn't ideal really.
