### ISSUE TITLE
Proposal: Refactor Align.py, port some functions to BaseAnalysis style 

### ISSUE THREAD

**Issue by jdetle** [MDAnalysis/mdanalysis#845]
Addresses issue #727 
First, there are some errors / redundancies in the align.py class to be addressed.

In **align_to:**
1. No need to divide weights relative to mean as this is already done in rmsd, simply pass ref_atoms.masses as argument to rmsd
3. Assign centers of mass outside of this if/else

In **rotation_matrix**: 
This code is entirely unnecessary in align.py, all one needs to do is get the matrix from the rmsd function with superpostion=True. This should be deleted. 

In **rms_fit_trj:**
1. Weight should be renamed to weights for consistency.
2. No need to divide weight relative to mean as this is already done in rmsd, simply pass ref_atoms.masses as argument to rmsd

 As far as I understand it, the BaseAnalysis format is only relevant for Multiframe analysis, and the only function that works with on multiple frames in align.py is **rms_fit_trj**. If I'm misunderstanding something let me know, but as of right now that seems like the only function that I would refactor into a class that follows the BaseAnalysis format. Please let me know if I'm missing something in either style or substance and I'll add it here.

**Comment by kain88-de** [comment]
**rotation_matrix**
It is good in *align.py* because all alignment functions live there. I don't like overloading the rmsd function with more options.

**alignto**:
  not dividing the weights is a good idea. But the "center_of_mass" assignment should be done in the if/else clause. It is actually calling two different functions `center_of_mass` and `center_of_geometry`.

**rms_fit_trj**:
yes this is the only class that needs to be converted. And I would rename it to `AlignTrj` to fit better into the other names and module naming. Internally it would be good if this class could use *alignto* to fit a single frame.

**Comment by jdetle** [comment]
I'm half asleep but I'm not sure about rotation matrix. It can at least be
heavily simplified by calling code from rmsd
On Sun, May 8, 2016 at 1:41 AM kain88-de <notifications@github.com> wrote:

> *rotation_matrix*
> It is good in *align.py* because all alignment functions live there. I
> don't like overloading the rmsd function with more options.
>
> *alignto*:
> not dividing the weights is a good idea. But the "center_of_mass"
> assignment should be done in the if/else clause. It is actually calling two
> different functions center_of_mass and center_of_geometry.
>
> *rms_fit_trj*:
> yes this is the only class that needs to be converted. And I would rename
> it to AlignTrj to fit better into the other names and module naming.
> Internally it would be good if this class could use *alignto* to fit a
> single frame.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/MDAnalysis/mdanalysis/issues/845#issuecomment-217703856>
>
-- 
Have a wonderful day,
John J. Detlefs

**Comment by kain88-de** [comment]
> I'm half asleep but I'm not sure about rotation matrix. It can at least be heavily simplified by calling code from rmsd

`rotation_matrix` is already pretty simple and straight forward. It is fine imho.
