### ISSUE TITLE
We should support AMBER crd and crdbox formats

### ISSUE THREAD

**Issue by kain88-de** [MDAnalysis/mdanalysis#846]
### Expected behaviour
have a amber crd (.mdcrd in MDAnalysis) produced with VMD should load just fine.

### Actual behaviour
I get an error the file couldn't be parsed. This is because we call the crd parser for CHARM files. 

### Currently version of MDAnalysis:
0.14.1dev

I see that this is a problem for pure `crd` file endings. For `crdbox` we can simply add it to the TRJ reader as a format. I'm not sure if it is worth it to special handle the `crd` ending when we read trajectory files and try to guess the format.

**Comment by richardjgowers** [comment]
If you put up an example of things I can knock this up.  Or is it that it can be read but the correct Parser/Reader isn't being used?

**Comment by kain88-de** [comment]
The second. We can read the files with `mda.coordinates.TRJ.TRJReader` but it isn't selected because that reader only registers **trj** and **mdcrd** as file formats. Adding **crdbox** as a format for the TRJ reader is trivial (PR will come today). But adding **crd** isn't that easy because CHARM is using the same extension.

**Comment by richardjgowers** [comment]
You can use `format='TRJ'` to override the guessing.  A cool solution might be something where one format can map to many Readers, so something like:
```python
potential_readers = _READERS[fmt]  # returns an iterable of possible readers
for reader in potential_readers:
    try:
        traj = reader(filename)
    except (IOError, ValueError):
        pass
    else:
        break
else:
    raise IOError("Tried all Readers and failed")
```

But this would rely on every Reader being able to check their files properly

**Comment by kain88-de** [comment]
> You can use format='TRJ' to override the guessing

Almost what I'm doing 

```python
try:
   u = mda.Universe(topo, trj)
except ValueError:
   u = mda.Universe(topo, trj, format='trj')
```

The try/expect clause it necessary because this code is in a library where I can't know what format the trj will be in.

**Comment by kain88-de** [comment]
This doesn't fix the issues with the `crd` ending that VMD suggests for the AMBER format. We could also just say VMD mixed up the formats and we are doing OK.

**Comment by orbeckst** [comment]
I always disliked VMD for doing that... technically, CHARMM is older so I think for right now it's fine to leave CRD for CHARMM CARD COORD files.
If we want to do smarter file format detection then that should be a separate issue. There's lots of room for improvement that one could do in `guess_format()`, including scanning the first few lines for magics or fingerprints.

**Comment by hainm** [comment]
> including scanning the first few lines for magics or fingerprints.

yeah, this should be done.
