### ISSUE TITLE
PDB performance gets worse if more frames are read.

### ISSUE THREAD

**Issue by kain88-de** [MDAnalysis/mdanalysis#848]
### Expected behaviour

Reading PDB frames should take constant time.

### Actual behaviour

There is a linear increase in the time it takes to read a frame

![index](https://cloud.githubusercontent.com/assets/4302678/15211433/744c3678-183b-11e6-9c59-78f2148d31ce.png)

Very annoying because reading longer PDB trajectories takes forever.

### Code to reproduce the behaviour

``` python
import MDAnalysis as mda
import time
import numpy as np
import matplotlib.pyplot as plt

u = mda.Universe(top, trj)
timings = []

for ts in u.trajectory[:2000]:
    timings.append(time.time())

plt.plot(np.diff(timings))
```

### Currently version of MDAnalysis:
(run `python -c "import MDAnalysis as mda; print(mda.__version__)"`)

0.14.1-dev0

**Comment by richardjgowers** [comment]
hmm I'm on it
