### ISSUE TITLE
PDBReader reopens files reading every frame

### ISSUE THREAD

**Issue by kain88-de** [MDAnalysis/mdanalysis#850]
The PDBReader opens and closes the trajectory file for reading every frame, [see](https://github.com/MDAnalysis/mdanalysis/blob/d989f27fa9269252f6000eb20e5c70a2d5a6dc10/package/MDAnalysis/coordinates/PDB.py#L374). Reopening the files all the time means we are doing direct I/O. This is an issue when MDAnalysis is run on an HPC cluster with 10 to 100 of different processes at the same time. 

HPC cluster usually have some kind of heavily buffered distributed filesystem, like the [GPFS](https://en.wikipedia.org/wiki/IBM_General_Parallel_File_System).  These type of filesystems **hate** direct I/O, they prefer buffered I/O. This would mean keeping a file open for longer period of time and reading from it. They can buffer that. Closing the file breaks their buffering mechanism. The end result is super slow file access for everybody on a cluster.

The solution is to keep the file pointer open. I did the same for the XTC/TRR readers.

**Comment by richardjgowers** [comment]
#239 was trying to move towards always accessing this way, but it sounds like this is a bad idea now

**Comment by kain88-de** [comment]
Yes if we want to allow MDAnalysis to run on HPC clusters for massively parallel analysis we have to keep the file descriptors open.
