### ISSUE TITLE
docs for XTC and TRR missing

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/mdanalysis#855]
[Flaviyan Jerome](https://plus.google.com/u/0/116090371828556431773?prsrc=4) noted on the mailing list in post [Gromacs XTC trajectory I/O](https://groups.google.com/d/msg/mdnalysis-discussion/KYhIhi1SWVY/-hpU98YSKQAJ) that the docs for TRR and XTC are missing.

The links from the [Table of Supported Coordinate Formats](http://pythonhosted.org/MDAnalysis/documentation_pages/coordinates/init.html#supported-coordinate-formats) such as the one for XTC
http://pythonhosted.org/MDAnalysis/documentation_pages/coordinates/XTC.html#module-MDAnalysis.coordinates.XTC give a blank page and neither TRR nor XTC are listed under http://pythonhosted.org/MDAnalysis/documentation_pages/coordinates_modules.html

The xdrfile page http://pythonhosted.org/MDAnalysis/documentation_pages/coordinates/xdrfile.html has entries but they are (1) buried deep and (2) pretty opaque.

All in all, we should have at least working pages for all our formats, *especially* from the overview table, which is one of the main entry points for new users.

(All in latest released 0.15.0).

**Comment by kain88-de** [comment]
How is this all setup? We don't even have an `xdrfile.py` anywhere? Is this stuff statically defined in the docs?

**Comment by orbeckst** [comment]
Pretty much everything uses sphinx autodoc so you need to be able to get at doc strings with `help(module)` or `help(function)`. The SWIG wrappers used to take care of the docs as well. I didn't check if this still worked with the new Cython wrappers.

The working xdrlib XTC/TRR docs come from [package/doc/sphinx/source/documentation_pages/coordinates/xdrfile/](https://github.com/MDAnalysis/mdanalysis/tree/develop/package/doc/sphinx/source/documentation_pages/coordinates/xdrfile).

The failing docs are linked from [MDAnalysis/coordinates/__init__.py](https://github.com/MDAnalysis/mdanalysis/blob/develop/package/MDAnalysis/coordinates/__init__.py#L157) by looking for, e.g., the XTC module:
```rst
   +---------------+-----------+-------+------------------------------------------------------+
   | Gromacs       | xtc       |  r/w  | Compressed (lossy) xtc trajectory format. Module     |
   |               |           |       | :mod:`MDAnalysis.coordinates.XTC`                    |
   +---------------+-----------+-------+------------------------------------------------------+
```
