### ISSUE TITLE
Link to guide for developers on website/wiki

### ISSUE THREAD

**Issue by jdetle** [MDAnalysis/mdanalysis#861]
### Expected behaviour
Figuring out how to setup a developer environment should be easy to find.
### Actual behaviour
Linking is a little complicated.
Say I am a developer looking how to do a developer install starting off at the MDAnalysis page.

Starting at quick start installation >>> 
http://www.mdanalysis.org/pages/installation_quick_start/
Installing MDAnalysis >>>
https://github.com/MDAnalysis/mdanalysis/wiki/Install 
Development Workflow
https://github.com/MDAnalysis/mdanalysis/wiki/DevelopmentWorkflow

None of these links have a reference to setup instructions on the wiki, which is very useful. 
Although we could expect people to click on the guide for developers wikilink, it is off to the right and not easily seen. 

I think in the [install](
https://github.com/MDAnalysis/mdanalysis/wiki/Install ) page should either just link to the 
1.[guide for developers](https://github.com/MDAnalysis/mdanalysis/wiki/Guide-for-Developers)
or 
2.[setup instructions](https://github.com/MDAnalysis/mdanalysis/wiki/Setup-Development-Environment)

I'm in favor of option 1.

**Comment by kain88-de** [comment]
This should also include a short guide how to rebase against another 'develop' and how merge conflicts should be fixed. Or even better link against a common existing guide.

**Comment by orbeckst** [comment]
I think the wiki [Install](https://github.com/MDAnalysis/mdanalysis/wiki/Install) page should show the basic installation with `pip` and then give alternatives. Keeping this page short is also good.

I agree that the last sentence regarding the development workflow was cryptic. I just changed it to simply say:
-------------
# Developers

Read the [Guide for Developers](https://github.com/MDAnalysis/mdanalysis/wiki/Guide-for-Developers), which includes special installation instructions.
-------------

I want to make it easy for new developers but I expect from a developer to invest the time to follow a linke and if in doubt, the introductory docs (like a page called "Install") should first help users and then developers.

**Comment by orbeckst** [comment]
Btw, a blog post for new developers would be nice. Along the lines of "The 5 things I wish I had known when starting developing on MDAnalysis" ;-).

**Comment by jdetle** [comment]
I think that's all that's really necessary too. I have trouble seeing the link on the right and I think that's all that a new developer really needs.

**Comment by jdetle** [comment]
Regarding the blog, I think so too! I'll start working on something, @fiona-naughton has me really thinking I need to step my blog quality up a notch.

**Comment by richardjgowers** [comment]
@jdetle practice drawing dogs?
