### ISSUE TITLE
select_atoms function and PBC condition 

### ISSUE THREAD

**Issue by hanhnguyen14** [MDAnalysis/mdanalysis#867]
We are looking to analyze water structure around a solute. Particularly, we are interested in whether waters (in a mixed solvent system) tend to cluster near the solute, or whether they tend to be pushed out towards bulk solvent. The number of waters near the solute could be higher or lower than bulk, however, it ought obviously to converge to bulk density in bulk. 

To analyze this, we utilized one of the MD Analysis functions, with periodic boundary conditions turned on. However, we find what appears to be a significant problem. Specifically, regardless of what point in our simulation box we pick (near the solute or far from the solute) we find that the number of water atoms within a given distance of that point always comes out higher than we would expect based on the number of water molecules in the system and the volume of the box. This happens whenever we analyze with Periodic Boundary Condition (PBC) turned on. When PBC is turned off for the analysis, we find that the number of solvent atoms within the specified sphere is equal to the number of solvent atoms we would expect to see. We don’t understand why this is, and are wondering whether there is a bug or whether we are missing a key concept. For example, we would expect that once the minimum image conversion is applied, it is impossible to for the analysis to yield a higher number of solvent atoms than the expected number everywhere in the box. Perhaps there is an issue with handling of the minimum image convention, or we are just missing something simple?
 
In our code [attached below], we utilized the function select_atoms( ‘ (‘point x y z 8’) and resname wat’) to select all water atoms within 8A radius of coordinate (x,y,z). As noted, this always yields a larger number of waters than we would expect given the ratio of the volume of the sphere to the volume of the box. 

The script and data file is stored in this Google drive:

https://drive.google.com/drive/folders/0B0_gJ4f4DTRVSURzeGEwQUNOYkE

**Comment by richardjgowers** [comment]
Hiya @hanhnguyen14 thanks for the detailed report.  

I think I've found the problem, on about line 180 you do `vol_sample = (4/3) etc`.  In Python 2 this will do integer division, so `4/3 = 1`, while `4/3.0 = 1.33`.  Two fixes for this, either always divide by floats or put `from __future__ import division` at the top of scripts, this imports the "new" style of division that's used in Python 3 (and works how you've expected it to).

I've only checked one point from your graph, but I get different results after this.  If you could try fixing this and let me know if you're having better luck and we can work from there.

Thanks
Richard

**Comment by hanhnguyen14** [comment]
Ok. Problem fixed! Thank you so much!

**Comment by richardjgowers** [comment]
Awesome, have fun!

**Comment by hanhnguyen14** [comment]
Hi Richard,
  I left a message on the same github issue tracker. So the water part is
working well. However, the curve for DMSO still doesn't behave the way I
expect it (details in the message on issue tracker).

On Fri, Jun 3, 2016 at 1:54 PM, Richard Gowers <notifications@github.com>
wrote:

> Awesome, have fun!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/MDAnalysis/mdanalysis/issues/867#issuecomment-223692102>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AMtCbzFegQDJpRHL9cBCCze55KNoUte4ks5qIJSVgaJpZM4It09x>
> .
>



-- 

*Hanh Nguyen*
*Graduate Student*
Chemistry Department
University of California, *Irvine*

**Comment by hanhnguyen14** [comment]
Hi Richard, 

   Thanks for helping me out. I have another issue regarding this project. Previous error found was from the division format 4.00/3.00. With this error fixed, our analysis yielded a lower number of water atoms than the expected number everywhere in the box. 

However, like I mentioned, we are also interested in the DMSO molecules and whether DMSO molecules  (in a mixed solvents water/DMSO system) tend to cluster near the solute, or whether they tend to be pushed out towards bulk solvent. Using the same approach, we find that the number of DMSO atoms within a given distance of that point always comes out higher than we would expect based on the number of DMSO molecules in the system and the volume of the box. 

I am not sure what is going on here since our analysis works for the water but not for the DMSO part. 

Thanks.
