### ISSUE TITLE
next/__iter__ in ProtoReader defined independetly

### ISSUE THREAD

**Issue by fiona-naughton** [MDAnalysis/mdanalysis#869]
Having looked through the `Reader` code, while there's a `next()`/`__next__()` defined, `__iter__()` is independently defined to loop over the timesteps itself - so changing `next` has no effect when iterating. This means (for example) in getting auxiliary data to update with the trajectory for #785 I need modify and check both methods separately.

It seems changing `__iter__()` to return self, and moving `raise StopIteration` to `next()`, would work the same but avoid this redundancy.

**Comment by richardjgowers** [comment]
Yeah I saw this too.  I think we're even making a mistake by not having our `__next__` raise StopIteration at the end...

Make a new branch off develop and do these changes and make a new PR.  It should just work(tm) but maybe it breaks something I've not thought of.
