### ISSUE TITLE
Installing tests doesn't run as expected

### ISSUE THREAD

**Issue by jdetle** [MDAnalysis/mdanalysis#873]
### Expected behaviour
sudo pip install -e . in ~/MDAnalysis/testsuite/
 
should properly install MDAnalysisTests.

### Actual behaviour
Obtaining file:///home/jdetlefs/github/MDAnalysis/testsuite
  Running setup.py (path:/home/jdetlefs/github/MDAnalysis/testsuite/setup.py) egg_info for package from file:///home/jdetlefs/github/MDAnalysis/testsuite
    
warning: no files found matching 'TODO'
warning: no files found matching 'SUMMARY.txt'
warning: no previously-included files matching '*~' found anywhere in distribution
warning: no previously-included files matching '*.pkl' found anywhere in distribution
**Downloading/unpacking MDAnalysis==0.15.1-dev0 (from MDAnalysisTests==0.15.1-dev0)
  Could not find a version that satisfies the requirement MDAnalysis==0.15.1-dev0** (from MDAnalysisTests==0.15.1-dev0) (from versions: 0.14.0, 0.11.0, 0.8.0, 0.9.0, 0.9.2, 0.12.1, 0.13.0, 0.8.1rc1, 0.10.0, 0.7.6, 0.8.1, 0.8.0rc2, 0.15.0, 0.9.0-dev, 0.8.0rc4, 0.9.1)
Cleaning up...
No distributions matching the version for MDAnalysis==0.15.1-dev0 (from MDAnalysisTests==0.15.1-dev0)
Storing debug log for failure in /home/jdetlefs/.pip/pip.log

### Code to reproduce the behaviour
```
git clone https://github.com/MDAnalysis/mdanalysis 
# after installing MDAnalysis in /mdanalysis/package
sudo pip install -e . 
```
### Currently version of MDAnalysis:
0.15.1-dev0

I'm probably missing something obvious but I thought it was worth posting.

**Comment by jbarnoud** [comment]
The warnings are not important. Did you have MDAnalysis (in the expected version) installed in the same environment before you tried installing MDAnalysisTests?

**Comment by jdetle** [comment]
That was unintentional spacing from the output, I recognize they're not important and edited it.

**Comment by jdetle** [comment]
...and I'm an idiot.

**Comment by kain88-de** [comment]
@jdetle please never 'sudo' install a developer version (in general never sudo install with pip). It will only lead to problems down the road

**Comment by jdetle** [comment]
Okay! I'm working in virtualenvs now so it won't happen again :+1:
