### ISSUE TITLE
pickling a segment raises depcreation warning

### ISSUE THREAD

**Issue by kain88-de** [MDAnalysis/mdanalysis#876]
### Expected behaviour

no warning at all
### Actual behaviour

just tells me to use segment.atoms.indices instrad
### Code to reproduce the behaviour

``` python
import MDAnalysis as mda
import pickle

u = mda.Universe(top, trj)
with open('testpicke', 'w') as f:
    pickle.dump(u.atoms.segments[0], f)

```
### Currently version of MDAnalysis:

(run `python -c "import MDAnalysis as mda; print(mda.__version__)"`)

0.15.0

**Comment by kain88-de** [comment]
likely solved after 363 anyway

**Comment by orbeckst** [comment]
Pickling is not working anymore with 0.16.0dev0:
```python
import pickle
import MDAnalysis as mda; from MDAnalysis.tests.datafiles import TPR, XTC
u = mda.Universe(TPR, XTC)
with open('testpicke', 'w') as f:
    pickle.dump(u.atoms.segments[0], f)
```

gives the error message
```
PicklingError: Can't pickle <class 'MDAnalysis.core.groups.Segment'>: it's not the same object as MDAnalysis.core.groups.Segment
```

@kain88-de I am closing this issue; all of this is related to our general problems with pickling. I will raise a separate issue.
