### ISSUE TITLE
AnalysisBase follows inconsistent style

### ISSUE THREAD

**Issue by jdetle** [MDAnalysis/mdanalysis#890]
### Expected behaviour
Variables should be named consistently.

### Actual behaviour
AnalysisBase.nframes doesn't have an underscore, but u.trajectory.n_frames, atoms.n_atoms does, atomgroup.n_residues does. This is kind of confusing and I think we should make convention consistent unless there are any objections.

**Comment by kain88-de** [comment]
Good point wanna take care of it?

**Comment by jdetle** [comment]
Yep!
On Wed, Jul 6, 2016 at 1:29 PM Max Linke <notifications@github.com> wrote:

> Good point wanna take care of it?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/MDAnalysis/mdanalysis/issues/890#issuecomment-230896435>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AKcARuVlqHePoU3sWxqAGm6_alMsPqBJks5qTBAlgaJpZM4JGauw>
> .
>
-- 
Have a wonderful day,
John J. Detlefs
