### ISSUE TITLE
analysis.rms.RMSD broken

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/mdanalysis#897]
### Expected behaviour
I should be able to set a RMSD analysis with `MDAnalysis.analysis.rms.RMSD`

### Actual behaviour
Raises `NameError`. 

#### Analysis
It seems that recently `_process_selection()` was renamed to `process_selection()` in 46f915b1 --- @jdetle seems to have forgotten to also rename references.

Even worse: **There are no unit tests for the RMSD class!** There's a test `TestRMSD` but it does *not* test the RMSD class but the `rmsd()` function. We should

- [x] fix `rms.RMSD`
- [x] rename `TestRMSD` to `Testrmsdfunc` (or just `Testrms` --- it all looks ugly?)
- [x] add a test `TestRMSD` for `rms.RMSD`

#### Stack Trace
```
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-6-be62615c3dd7> in <module>()
----> 1 R = RMSD(u, select="protein and name CA")

/nfs/homes2/oliver/Library/python/mdanalysis/package/MDAnalysis/analysis/rms.pyc in __init__(self, traj, reference, select, groupselections, filename, mass_weighted, tol_mass, ref_frame)
    339         else:
    340             self.reference = reference
--> 341         self.select = _process_selection(select)
    342         if groupselections is not None:
    343             self.groupselections = [_process_selection(s) for s in groupselections]

NameError: global name '_process_selection' is not defined
```

### Code to reproduce the behaviour

``` python
import MDAnalysis as mda
from MDAnalysis.tests.datafiles import PSF, DCD
from MDAnalysis.analysis.rms import RMSD
u = mda.Universe(PSF, DCD)
R = RMSD(u, select="protein and name CA")
```

### Currently version of MDAnalysis:
(run `python -c "import MDAnalysis as mda; print(mda.__version__)"`)
0.15.1-dev0

**Comment by orbeckst** [comment]
(By the way, not having tests for `rms.RMSD` is probably my own fault...)

**Comment by jdetle** [comment]
I broke it, someone else didn't cover the code, let's just call it a draw...

**Comment by orbeckst** [comment]
Sounds fair ;-)

**Comment by jdetle** [comment]
How about TestRMSDSingleFrame and TestRMSD?
