### ISSUE TITLE
install external code on travis for complete analysis testing?

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/mdanalysis#898]
Testing on travis currently skips a number of tests that call external tools. Apart from the fact that it reduces our coverage it also simply not good to have code that only gets tested occasionally if one of the @MDAnalysis/coredevs feels like doing it locally.

Should we try to install external packages on travis in order to run these tests?

From the top of my head
- [x] `analysis.hole`: [HOLE](http://www.smartsci.uk/hole/) (see installation instructions in the comments for 707b02bd67d7f2966bde567c71a0bcef08e0af85)
- [x] `analysis.align`: [clustal](http://www.clustal.org/) (there might even an Ubuntu package for installation)
- [ ] `analysis.x3dna`: [x3dna](http://x3dna.org/) – not easily accessible, not free, so that won't get done any time soon (see https://github.com/MDAnalysis/mdanalysis/issues/898#issuecomment-234040024)

HOLE and clustalx (or clustalw) should be pretty easy, x3dna I am not sure.

UPDATE: #906 proposes to make `analysis.x3dna` a legacy module.

**Comment by richardjgowers** [comment]
Yeah I'm in favour, more coverage helps reduce headaches down the road

**Comment by hainm** [comment]
you can build conda packages for external ones, so the travis builds are trivial.

**Comment by orbeckst** [comment]
True, although HOLE is not free, only available as binary, and I doubt that the license allows repackaging. Otherwise it would be very helpful to have it on Conda. 

--
Oliver Beckstein
email: orbeckst@gmail.com


> Am Jul 17, 2016 um 17:34 schrieb Hai Nguyen <notifications@github.com>:
> 
> you can build conda packages for external ones, so the travis builds are trivial.

**Comment by orbeckst** [comment]
Just FYI: the **[HOLE END USER LICENCE AGREEMENT NOT-FOR-PROFIT VERSION](https://github.com/MDAnalysis/mdanalysis/files/372246/Licence-not-for-profit.txt)** (attached) explicitly forbids making copies, e.g. for conda packages:

You may not:

* permit other individuals to use the Software except under the terms listed below;
* modify, translate, reverse engineer, decompile, disassemble (except to the extent applicable laws specifically prohibit such restriction), or create derivative works based on the Software;
* copy the Software (except for back-up purposes);
* rent, lease, transfer, or otherwise transfer rights to, the Software;
* remove any proprietary notices or labels on the Software.

Thus I cannot add it to a conda channel, even if I'd love to do it.

**Comment by hainm** [comment]
> copy the Software (except for back-up purposes);

according to this, you can't not even copy/build it on travis.

**Comment by orbeckst** [comment]
On travis we download the software every single time from the original download location. Because this is not-for-profit and academic use as described in the license agreement I believe this falls under permitted use.

But yes, it's an awful license. 

However, in the ion channel field, HOLE is the de-facto standard for measuring cavities so everybody wants to use it. (There are some alternative packages but I can't find any obvious links at the moment.)

**Comment by orbeckst** [comment]
PR #901 is pretty much complete for HOLE and clustalw. I am lacking the expertise (and currently the time) to do anything with x3dna. Furthermore, [downloading x3dna](http://forum.x3dna.org/site-announcements/download-instructions/) requires user registration and "command-line tools such as wget and curl are blocked on purpose" and it is [not open source](http://forum.x3dna.org/rna-structures/source-distributionlinux-packaging/msg1875/#msg1875) as far as I can tell. I cannot even find a license on the site.

I don't have a big need for x3dna myself at the moment so I am just going to skip this and when the time comes, we can mark the x3dna module as legacy, as discussed in #743.

**Comment by orbeckst** [comment]
Closed by #901.
