### ISSUE TITLE
change `quiet` keyword to `verbose`

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/mdanalysis#903]
In many places (namely, the analysis classes and the progress meter) we allow the user to mute output with `quiet=True`. However, it really seems more customary to use `verbose=False` (@kain88-de mentioned this in PR #892).

To make things a bit more uniform and conform to user expectations, we should 
- [ ] deprecate `quiet`
- [ ] make `verbose` available.

For 1.0, `verbose` should be the only available flag. Until then, `quiet` needs to override `verbose` so that users are guaranteed their old behavior.

Maybe it is possible to write a ten2eleven fixer — @tylerjereddy ??

**Comment by tylerjereddy** [comment]
I'll try to look into the fixer. I suppose I can justify some procrastination until the code is actually implemented though.
