### ISSUE TITLE
move analysis.x3dna to new analysis.legacy module

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/mdanalysis#906]
As discussed in #898, we cannot easily write full tests for the `MDAnalysis.analysis.x3dna` module because we cannot easily install [x3dna](http://x3dna.org/) on travis (and I don't even know the terms of the license — impossible to find on the home page!). In accordance with the [Guidelines on Testing in MDAnalysis.analysis](https://github.com/MDAnalysis/mdanalysis/wiki/Style-Guide#tests-for-mdanalysisanalysis) I propose to 
- [x] set up the new `MDAnalysis.analysis.legacy` module 
- [ ] **exclude `legacy` from testing/coverage**
- [x] add docs explaining the policy on legacy code (see #743 and [Guidelines on Testing in MDAnalysis.analysis](https://github.com/MDAnalysis/mdanalysis/wiki/Style-Guide#tests-for-mdanalysisanalysis))
- [x] move `MDAnalysis.analysis.x3dna` to `MDAnalysis.analysis.legacy.x3dna`
- [x] add a stub and deprecation (stub will go away in 1.0).

**Comment by richardjgowers** [comment]
So how will the namespace work if I want to use analysis.x3dna in the future?  Will I have to import from `analysis.legacy` instead?

I'm not a huge fan of fragmenting namespace like this - could we instead add a warning on import saying words to the effect of, "This is legacy with no tests, double check your results if you use this code"

**Comment by orbeckst** [comment]
> On 20 Jul, 2016, at 15:15, Richard Gowers <notifications@github.com> wrote:
> 
> So how will the namespace work if I want to use analysis.x3dna in the future? Will I have to import from analysis.legacy instead?

Yes, that was the idea, as discussed.

	from MDAnalysis.analysis.legacy import x3dna

The reason for why at least I favored this solution is because it makes it REALLY clear (semantically) that this package is “use at your own risk” – even before you import it. I like the idea of the user having to go the extra mile to import from legacy – should make them think, and should make clear that these packages are not first class citizens.

> 
> I’m not a huge fan of fragmenting namespace like this -

Fair enough (“flat is better than nested”) although in this instance I’d consider it justified.

> could we instead add a warning on import saying words to the effect of, “This is legacy with no tests, double check your results if you use this code"

I would ALSO add this warning. But warnings are easily ignored/muted. 

Anyway, my $0.02.

--
Oliver Beckstein * orbeckst@gmx.net
skype: orbeckst  * orbeckst@gmail.com
