### ISSUE TITLE
support mmtf format

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/mdanalysis#907]
@arose [suggested on twitter](https://twitter.com/asrmoin/status/753430985765588992) to use [MMTF](http://mmtf.rcsb.org/)  for storing big structures. "The Macromolecular Transmission Format (MMTF) is a new compact binary format to transmit and store biomolecular structural data quickly and accurately."

There is a python implementation available: https://github.com/rcsb/mmtf-python

**Comment by kain88-de** [comment]
they have another format -.-? What is with the [mmCIF](http://mmcif.wwpdb.org/) that is still in development for large macromolecular complexes?

**Comment by orbeckst** [comment]
> On 20 Jul, 2016, at 14:20, Max Linke <notifications@github.com> wrote:
> 
> they have another format -.-? What is with the mmCIF that is still in development for large macromolecular complexes?

If you look at the comparison graph for loading  mmCIF vs mmtf I would say it’s on the way out – but I don’t know how feature-complete mmtf is. I really did not dig into it in any more detail.

--
Oliver Beckstein * orbeckst@gmx.net
skype: orbeckst  * orbeckst@gmail.com

**Comment by arose** [comment]
Hey @kain88-de, mmCIF is still the archival format and there are no plans to retire it in any way! We created [MMTF](mmtf.rcsb.org) for the specific purpose of fast transmission over the internet (and whole archive analyses). It loads and parse real quick, allowing you to look at the 2.4M HIV Capsid in a [Browser](http://arose.github.io/ngl/?example=hiv). MMTF does not contain all the metadata from mmCIF files but rather most of the data generally used.

**Comment by orbeckst** [comment]
@arose, many thanks for the background information on MMTF! Very useful.

> On 20 Jul, 2016, at 14:58, Alexander Rose <notifications@github.com> wrote:
> 
> Hey @kain88-de, mmCIF is still the archival format and there are no plans to retire it in any way! We created MMTF for the specific purpose of fast transmission over the internet (and whole archive analyses). It loads and parse real quick, allowing you to look at the 2.4M HIV Capsid in a Browser. MMTF does not contain all the metadata from mmCIF files but rather most of the data generally used.

--
Oliver Beckstein * orbeckst@gmx.net
skype: orbeckst  * orbeckst@gmail.com

**Comment by orbeckst** [comment]
@richardjgowers I assigned you to this issue because you've been working on #907 and you already have some expertise – feel free to assign other folks and tag with 'help needed' or similar.

**Comment by richardjgowers** [comment]
@orbeckst OK, I'm trying to stop procrastinating on 363 so anyone else can finish this off if they want.
