### ISSUE TITLE
Is there an updated list of supported topology and trajectory formats in python

### ISSUE THREAD

**Issue by kain88-de** [MDAnalysis/mdanalysis#920]
In my own application code I would like to write code like the following

```python
ext = os.path.splitext(filename)[-1]
if not ext in mda.topology.formats:
    raise ValueError("Format not supported by MDAnalysis has to be one of:"
                     " {}".format(mda.topology.formats)
```

If I can write the same code for trajectory file formats that would be nice.

**Comment by richardjgowers** [comment]
So there's 2 dictionaries linking formats to Readers/Parsers, `MDAnalysis.topology._PARSERS` and `MDAnalysis.coordinates._READERS`

**Comment by kain88-de** [comment]
Thanks.
