### ISSUE TITLE
Progress bar does not show in jupyter notebooks

### ISSUE THREAD

**Issue by jbarnoud** [MDAnalysis/mdanalysis#927]
### Expected behaviour

Running an analysis with `quiet=False` in a jupyter notebook displays a progress bar.

### Actual behaviour

The progress bar is not actually displayed. This seems to be related to <https://github.com/ipython/ipython/issues/1527/>, the main issue being that the `\r` is printed at the end of the progress bar string rather than at the beginning.

I have a quick and dirty fix that works. I need to clean it a bit, though.

**Comment by kain88-de** [comment]
It worked for me. Which version are you using?

**Comment by jbarnoud** [comment]
Works for me in a terminal, but not in a jupyter notebook. I use a less 
than a week develop version of MDAnalysis, but a fairly old version of 
the jupyter notebook.

**Comment by kain88-de** [comment]
I'm using a recent version of ipython and the notebook. Can you try upgrading to version 4.1.x and try again.

**Comment by jbarnoud** [comment]
I just check. I am actually using the latest jupyter already. It is 
ipywidgets that I have old, because of nglview.

The progress bar needs some cleanup anyway, it uses old string formating 
and old docstring. Also fixing the bug for me was just a matter of 
replacing `progress\r` by `\rprogress` which means less gymnastic to 
restore the `\n` at the end (see 
<https://github.com/MDAnalysis/mdanalysis/blob/develop/package/MDAnalysis/lib/log.py#L255>).

**Comment by hainm** [comment]
You can try nglview dev. We just migrated from ipywidgets 4 to 5.

**Comment by jdetle** [comment]
For what its worth this is broken for me too, updated my ipywigets and notebook and its still broken.
