### ISSUE TITLE
attrbute settings aren't propagated up through levels

### ISSUE THREAD

**Issue by kain88-de** [MDAnalysis/mdanalysis#940]
### Expected behaviour

Settings a resname from the AtomGroup level also changes resnames and residue types in the residue and segment level.

In general I would expect that changes set at the Atom level also travel up to residue and segment groups as vice versa (that works now already)
### Actual behaviour

only residue names are changes but the residueGroup associated with an AtomGroup is still the same
### Code to reproduce the behaviour

``` python
import MDAnalysis as mda

u = mda.Universe(top, trj)
u.atoms.resnames = 'ALA'
print(np.unique(u.atoms.residues.resnames))
# shows more then just one residue type
print(np.unique(u.atoms.resnames))
# only prints 'ALA' so information about the universe has diverged.

# however
u.atoms.residues.set_resname('ALA')
print(np.unique(u.atoms.residues.resnames))
# only prints 'ALA'
```
### Currently version of MDAnalysis:

0.15.1-dev

**Comment by richardjgowers** [comment]
Yeah this is one of the things that should be fixed by 363 hopefully.  I guess to close this make sure tests that run through the above code successfully are added.

**Comment by kain88-de** [comment]
How would I do this with the original bug? Now `u.atoms.resnames = 'ALA'` raises a `NotImplementedError` in the topologyattr.

**Comment by richardjgowers** [comment]
Resnames can only be set by a residue, so `u.atoms.residues.resnames = 'ALA'` (or `u.residues.resnames`)

**Comment by kain88-de** [comment]
Yes it works if I only set it using the residues. But the error message isn't very helpful right now. Instead of the NotImplemented error if would be nicer to have a message saying that I'm trying to change a read-only variable and that I should rather change it at the residue/segment level.

**Comment by richardjgowers** [comment]
Ah yeah, or we could allow it to work again as long as the same resname is given for each atom in a given residue.  (So if atoms 1 & 2 are in Residue1, you can't set them to different resnames)

**Comment by kain88-de** [comment]
I'm just for better error messages. That will train people to use the correct method. Since your suggestions will break down once you try to use more complex topology changes to build up a system. 

I use MDAnalysis to build topologies for my own simulation software. Sometimes this requires doing weird stuff to an existing topology because I can't create a new one from scratch. I'm sure other people will also run into this.

**Comment by richardjgowers** [comment]
Yeah ok, bit of a rough edge I agree.  This needs to get fixed in the `set_atoms` of `core.topologyattrs.ResidueAttr`

**Comment by richardjgowers** [comment]
@kain88-de in PR #1164 

```python
In [9]: u.atoms[:10].resids = 20

NotImplementedError: Cannot set resids from AtomGroup. Use 'AtomGroup.residues.resids = '

In [10]: u.residues[0].mass = 42.0

NotImplementedError: Cannot set masses from Residue. Use 'Residue.atoms.masses = '

In [11]: u.atoms[0].segid = 'abcd'

NotImplementedError: Cannot set segid from Atom. Use 'Atom.segment.segid = '
```

**Comment by kain88-de** [comment]
Looks good. This are better error messages
