### ISSUE TITLE
Have a decorator to create a quick analysis class

### ISSUE THREAD

**Issue by kain88-de** [MDAnalysis/mdanalysis#946]
I notice in my own analysis scripts now a pattern. For a lot of analysis types I'm starting to write a Analysis class that only calls one function in `_single_frame`. That means a lot of boilerplate code for me. It would be nice to a decorator or something similar to quickly turn a function that only takes current atomgroup and a reference into a full analysis class.

For example to write a basic rotation analysis method the following code should be enough.

```python
@analysis
def RotationMatrix(mobile, ref):
    return align.rotation_matrix(mobile.coordinates, ref.coordinates)[0]

rot = RotationMatrix(u, ref, start=0, stop=10).run()
```

Right now I have to write all of this.

```python
class RotationMatrix(AnalysisBase):
    def __init__(self, mobile, ref, **kwargs):
        super(RotationMatrix, self).__init__(mobile.universe.trajectory, **kwargs)
        self._mobile = mobile
        self._ref = ref

    def _prepare(self):
        self.R = []

    def _single_frame(self):
        self.R.append(align.rotation_matrix(self._mobile.positions, self._ref.positions)[0])

    def _conclude(self):
        self.R = np.asarray(self.R)
```

**Comment by jbarnoud** [comment]
I like the idea of the decorator, yet it seems quite tricky to implement. An other option would be to have a class that inherit from `AnalysisBase` and take care of part of the boilerplate.

```python
class SimpleAnalysisBase(AnalysisBase):
    n_atom_group_input = 1

    def __init__(self, atom_groups, **kwargs):
        if self.n_atom_group_input == 1:
            trajectory = atom_groups.trajectory
        elif self.n_atom_group_input > 1:
            if len(atom_groups) != self.n_atom_group_input:
                raise ValueError('Unexpected number of atom groups provided')
            trajectory = atom_groups[0].trajectory
        else:
            raise ValueError('SimpleAnalysisBase need at least one AtomGroup')
        super(SimpleAnalysisBase, self).__init__(trajectory, **kwargs)
        self._atom_groups = atom_groups

    def _prepare(self):
        self.result = []

    def _conclude(self):
        self.result = np.asarray(self.result)
```

Then the boilerplate for your analysis is greatly reduced:

```python
class RotationMatrix(SimpleAnalysisBase):
    n_atom_group_input = 2

    def _single_frame(self):
        R = align.rotation_matrix(self._atom_groups[0].coordinates,
                                                self._atom_groups[1].coordinates)[0]
        self._result.append(R)
```

Still not ideal, but better already.

With the intermediate class, the decorator looks more doable.

```python
def analysis(n_atom_group_input):
    # First we create a new class that will host the analysis
    class DecoratorAnalysis(SimpleAnalysisBase):
        n_atom_group_input = n_atom_group_input

    # Since we create a decorator with an argument, the `analysis` function
    # needs to return the decorator callback. We create it here.
    def decorator(function):
        # The point is to build the _single_frame method so it calls the user's
        # function. We create the method, and we attach it to the class we
        # created earlier. The decorator returns that class rather than a function.
        def _single_frame(self):
            if self.n_atom_group_input == 1:
                self.result.append(function(self._atom_groups))
            else:
                self.result.append(function(*self._atom_groups))
        DecoratorAnalysis._single_frame = _single_frame
        return DecoratorAnalysis

    return decorator
```

Then, the decorator is used as:

```python
@analysis(n_atom_group_input=2)
def RotationMatrix(mobile, ref):
    return align.rotation_matrix(mobile.coordinates, ref.coordinates)[0]

mobile = u.select_atoms(...)
ref = u.select_atoms(...)
rot = RotationMatrix([mobile, ref], start=0, stop=10).run()
```

None of this is tested, not even remotely executed. It is just code from the top of my head. But the approach could work.

On a more general basis, I would prefer the `_single_frame` method to return its result rather than adding it to lists. It is what @mnmelo's MDReader expect and it helps a lot with parallelization, but also with tidiness.

**Comment by kain88-de** [comment]
> On a more general basis, I would prefer the _single_frame method to return its result rather than adding it to lists. It is what @mnmelo's MDReader expect and it helps a lot with parallelization, but also with tidiness.

That would only work on simple analysis classes like this one. For more advanced classes like [this](https://github.com/MDAnalysis/mdanalysis/blob/396e04084bc1dc3e1bfe5542c5f7ba2127cabf12/package/MDAnalysis/analysis/diffusionmap.py#L251) a return would be harder to achieve. So `_single_frame` doesn't do a return right now to allow for flexibility.

Otherwise your code looks good. If it works it would be great to create short one-of analysis.

**Comment by kain88-de** [comment]
I don't think the `n_atom_group_input` is necessary. We can introspect the number of arguments when the decorator is run. I have to look up the code to do the argument inspection, but that is possible in python.

**Comment by jbarnoud** [comment]
It is possible using the inspect module. I used the class argument to 
have something to show without looking at the doc...

**Comment by jbarnoud** [comment]
It works! <https://gist.github.com/jbarnoud/acb19928c2e6fb65d121d30e862aea64>

Before I go crazy about it, I would like to hear from others. There may be ways to introspect more things from the arguments. Some API details may not be optimal. There surely are corner cases I did not consider. Maybe it can be made more general...

I :heart: python!!

**Comment by jbarnoud** [comment]
After some thinking, I am a bit annoyed with some aspects of the decorator approach: I do not like that you have a nice standalone function, and you cannot use it as is because it gets heavily transformed afterward.

Instead of decorating the function, I would use the same `analysis` function to create the class.

```python
# Instead of this
@analysis
def RotationMatrix(mobile, ref):
    return align.rotation_matrix(mobile.positions, ref.positions)[0]

#I would do
def rotation_matrix(mobile, ref):
    return align.rotation_matrix(mobile.positions, ref.positions)[0]

RotationMatrix = analysis(rotation_matrix)
```

This allows to still be able to use the `rotation_matrix` function, and avoids the surprise of having a class where we expect a function. This is just a matter of usage though, as the `analysis` function does not change between the two examples.

**Comment by kain88-de** [comment]
Actually what we also could do is to have the decorator return the results when it's called.

```python
@analysis
def rotation_matrix(mobile, ref):
    return align.rotation_matrix(...)[0]

rotations = rotation_matrix(mobile, ref, step=2)
```

The decorator should work like this (not tested)

```python
def analysis(function):
    class DecoratorAnalysis(SimpleAnalysisBase):
        n_atom_group_input = len(inspect.getargspec(function).args)
    # The point is to build the _single_frame method so it calls the user's
    # function. We create the method, and we attach it to the class we
    # created earlier. The decorator returns that class rather than a function.
    def _single_frame(self):
        if self.n_atom_group_input == 1:
            self.result.append(function(self._atom_groups))
        else:
            self.result.append(function(*self._atom_groups))
    DecoratorAnalysis._single_frame = _single_frame

    def wrapper(*args, **kwargs):
        return DecoratorAnalysis(*args, *kwargs).run().result

    return wrapper
```

This gets close to [timeseries](https://pythonhosted.org/MDAnalysis/documentation_pages/core/Timeseries.html) but with the advantage that nothing needs to be written in C/Cython.

**Comment by kain88-de** [comment]
The center of mass would be easy

```python
@analysis
def center_of_mass(mobile):
    return mobile.center_of_mass()
```

I don't really know how the distance function from the timeseries would work with this. Right now I can only think of this.

```python
def distance(mobile, i, j)
    @analysis
    def _distance(mobile):
        return np.linalg.norm(mobile.positions[i] - mobile.positions[j])
   return _distance(mobile)

dist  = distance(u.atoms, 0, 2)
```

**Comment by kain88-de** [comment]
On a second thought the distance is not that hard either. This should work.

```python
@analysis
def distance(atom1, atom2):
    return np.linalg.norm(atom1.positions - atom2.positions)
```

**Comment by jbarnoud** [comment]
@kain88-de Doesn't this cancel the benefit from the `AnalysisBase` class? You loose the ability to slice your trajectory, or to control the progress bar for instance.

**Comment by kain88-de** [comment]
Yeah I noticed that. The decorator would need to do some smarter things with the arguments. I'll see if I can do some code based on your notebook on the weekend.

**Comment by jbarnoud** [comment]
Just be careful not to create a whole new API for analyses. What I like with your initial idea is that it reduces the clutter, but then you get something very familiar.

**Comment by kain88-de** [comment]
I'm playing around a little bit and see how far I get. I also want to see that I can get a collection of such small functions into a single analysis like this:

```python
def center_of_mass(...):
    pass

def dihedral(...):
    pass

Ana = analysis.collection(center_of_mass, dihedral)
a = Ana(u).run()
#simple access to all results
a.center_of_mass
a.dihedral
```

That would make it easy to combine simple analysis functions while still being efficient since we only iterate once.

**Comment by jbarnoud** [comment]
Ideally, the `collection` function could take classes as argument too. I wonder what is the actual gain in performance in combining the analysis though.

**Comment by kain88-de** [comment]
About the performance it depends. But for a slow reader like PDB it should be noticeable.

**Comment by kain88-de** [comment]
Otherwise when you need half a minutes to iterate over a long XTC trajectory it should also be noticeable to have a collection assuming the individual analysis function is fast.

**Comment by kain88-de** [comment]
I would use the [workshop](https://becksteinlab.github.io/MDAnalysis-workshop/datadownload.html#chapter-datadownload) trajectories to check the performance with the collection. But first I have to get it running.

**Comment by kain88-de** [comment]
I have a [demo](https://gist.github.com/kain88-de/644201535c1d1ef8c91c67ea1005a9b2) for the collections.  It works quite nice and with the inspect module I made create a more advanced parsing of named kwargs that allows the analysis functions also to have kwargs and safely mix them with the kwargs specific to `AnalysisBase`.  Right now the argspecs of all functions have to be exactly equal up to the correct default arguments. I don't check that the functions accept sinkhole arguments like `*args` and `**kwargs` which might be potentially problematic. I don't know right now how it would be possible to add a existing AnalysisClass to a collection. Another thing that is important for this to work is that non of the functions in a collection should change the coordinates in the Atomgroups they get parsed, otherwise it might leas to surprising results. The idea of creating a new [analysis_func](https://gist.github.com/kain88-de/c8450630957954f2d0f7fbaa59594e8c) decorator also worked out nicely.

So I would suggest we create 3 function to wrap simple analysis functions.

**1.** A `analysis_class` decorator that is used as a wrapper function

```python
def rotation_matrix(m, r):
    return align.rotation_matrix(m, r)[0]

RotationMatrix = analysis_class(rotation_matrix)
# or
@analysis_class
def RotationMatrix(m, r):
    return rotation_matrix(m, r)
```

**2.** A `analysis_func` decorator do instantly create a function that iterates over a whole trajectory and returns the result of an analysis. It should also allow to take kwargs for AnalysisBase to adjust the iteration.

```python
@analysis_func
def rotation_matrix(m, r):
    return align.rotation_matrix(m, r)[0]

R = rotation_matrix(m, r, step=2)
```

**3.** A `collection` function to combine several analysis functions into one. This is also semantically nice to read to combine different analysis tasks. I would like to use something like this to define a quick post processing class that calculates a bunch of observables. This has the potential to replace TimeSeries with a pure python implementation. 

```python
def rotation_matrix(m, r):
    return align.rotation_matrix(m, r)[0]

def com(m, r):
    return m.center_of_mass()

postprocessor = collection(rotation_matrix, com)

analysis = postprocessor(m, r).run()
analysis.result[com]
```

**Comment by jbarnoud** [comment]
I really like the `collection`, and I keep liking the `analysis_class`. I do not like the the analysis_func` creates a   new API.

It would actually be fine if all the analyses could be called like this. But then we loose some flexibility that I really like in the class, being that you can provide several ways of presenting the results as properties of the analysis class.

Fun work with the inspection. Couldn't part of what the `collection` function does be done in the init of the `CollectionAnalysisBase` instead? Could `CollectionAnalysisBase` also handle classes?

**Comment by kain88-de** [comment]
The collections need some more thought since they have some subtle issues. I think I raise a issue for them separately and go into the details of them there.
