### ISSUE TITLE
Stabilize coverage fluctuations due to random numbers in tests.

### ISSUE THREAD

**Issue by mnmelo** [MDAnalysis/mdanalysis#958]
As @richardjgowers pointed out in #955, coverage is currently reported with fluctuations of around 0.1% because the use of random numbers causes slightly different code paths to be followed.

One might argue that randomness should be avoided in tests, but it's a handy way to quickly generate on-the-fly test objects from scratch (like sets of coordinates).

I came up with a simple test plugin that'll reseed the `random` and `np.random` RNGs prior to each test, so that we get consistent creation of test values, and a stable code path. In turn, this will allow us to be more stringent when thresholding coverage drops (#955). I guess it'll be one more thing to convert when moving away from nose tests, but it's also not that critical anyway.

Perhaps the cleanest alternative is to hardcode those "random" test values, either as test datafiles or in the test scripts themselves. The fact that we follow different code paths dependent on input suggests we will want to control that at some point to be able to get full coverage. This, of course, will take much more work to solve.

**Comment by kain88-de** [comment]
Instead of a plugin we could also just use `RandomState` in the random tests and initialize it in the setup, that is anyway my preferred way to use random numbers with multi processing.

**Comment by mnmelo** [comment]
That might be the way to go. I'm bumping against race conditions because tests are not run each in their own process when parallelizing, and as such a plugin might not be able to do the trick.

I'll look into `RandomState`.

**Comment by richardjgowers** [comment]
What I've been meaning to do is find some "random" numbers that go down each code path and hard code these in.  

This is the only place we use random numbers, it seems a bit over the top to add more new things to the tests.

**Comment by kain88-de** [comment]
The RandomState is pretty easy to use. Actually `np.random` is mostly a interface to a global RandomState. To use them ourself we just need to do this.

```python
rng = np.random.RandomState(1337)
number = rng.uniform(-1, 1, size=1000)
```

Then it's basically down to finding a good seed to trigger all code-paths.

**Comment by mnmelo** [comment]
@richardjgowers, yeah, that's what I meant by the 'more work' alternative. It's, of course, the best way, but also the most troublesome.

@kain-de, I think we'll not only need a good seed, but also multiple tests. I imagine some of the code paths are alternative, and we can't hit them all at once, right @richardjgowers?

Finally, there's a couple more uses of random numbers in the tests, but to a lesser scale: `test_atomgroup.py`, `coordinates/test_xdr.py`, `analysis/test_persistencelength.py`, `analysis/test_density.py`, and `test_util.py`.
