### ISSUE TITLE
give correct error when file doesn't exist

### ISSUE THREAD

**Issue by kain88-de** [MDAnalysis/mdanalysis#981]
### Expected behaviour

`mda.Universe('this.is.a.non.existing.pdb')` should report that the file doesn't exist
### Actual behaviour

it says file can't be opened.
### Currently version of MDAnalysis:

(run `python -c "import MDAnalysis as mda; print(mda.__version__)"`)
0.15.0

**Comment by kain88-de** [comment]
ah damn the file didn't exist afterall on my PC. wrong alarm.

**Comment by richardjgowers** [comment]
Afaik there's not any `os.path.exists` calls ever in the file detection code, so maybe there should be a special error message for that.

**Comment by kain88-de** [comment]
Well the current one says it can't read the file. So a check if it exists after the format guessing would be nice.

**Comment by kain88-de** [comment]
I changed the PR title and description

**Comment by utkbansal** [comment]
Hi, can I work on this?

**Comment by kain88-de** [comment]
Yes you can. Please make a PR when you have a working solution. If you encounter proble,s you can ask here or on the mailing list.

**Comment by utkbansal** [comment]
@kain88-de Thanks! Just to be sure, I just have to check the existence of files before they are opened and if not present raise an exception? I might need some help as this is my first issue.

**Comment by jbarnoud** [comment]
I would be careful with the phrasing of the error message. Indeed, `os.path.exist` does not test if the file exists, but if the file is accessible by the user. A file that is not accessible by the user often means that the file does not exist, but it can also mean that the user does not have permissions to access it.

As an error message I would write something in the spirit of "The file does not exist or cannot be accessed." rather than just "The file does not exist."

**Comment by utkbansal** [comment]
Quick question, I have to check the _all_ the `open` calls in the project. Not just the one in the `Universe` class. Right?

**Comment by jbarnoud** [comment]
For the scope of this issue I would limit myself to the `Universe` class. Also, it may be worth having a look at what we can get from the `OSError` that is raised by `open`, indeed that could allow to be quite specific in the error message.

**Comment by utkbansal** [comment]
@jbarnoud `open` raises and `IOError` instead of an `OSError`. The `IOError` object has two usefull attributes :
* `filename` 
* `strerror` - which comes out out to be 'No such file or directory'
