### ISSUE TITLE
can't detect filetype for files with two formats in the name dot separated 

### ISSUE THREAD

**Issue by kain88-de** [MDAnalysis/mdanalysis#982]
### Expected behaviour

`mda.Universe('some.weird.not.pdb.but.converted.xtc` should load as with the xtc format reader
### Actual behaviour

ValueError that it can't detect the topology type
### Currently version of MDAnalysis:

(run `python -c "import MDAnalysis as mda; print(mda.__version__)"`)
0.15.0

**Comment by richardjgowers** [comment]
I'm fairly sure we're handling this correctly in terms of guessing, it's just the error message is misleading. It needs to say something like "XTC isn't a valid topology format" rather than it can't parse the file extension.

```python
In [3]: from MDAnalysis.lib.util import guess_format

In [4]: guess_format('some.weird.not.pdb.but.converted.xtc')
Out[4]: 'XTC'
```

**Comment by orbeckst** [comment]
https://github.com/MDAnalysis/mdanalysis/issues/982#issuecomment-246623212 would be a good test (if we don't have it already).

**Comment by utkbansal** [comment]
Hi, can I work on this?

**Comment by jdetle** [comment]
@utkbansal, I'm not a core dev, but to save you some time, but in open source software you can work on whatever you like. Generally you shouldn't *claim* an issue as yours, but communication is always better than no communication. Feel free to chime in on an issue and say "I am working on this, you should expect a pull request soon."

It is entirely possible that someone else will submit a change addressing the issue first, but either way you will inevitably have learned from the process and become more familiar with the codebase. So go for it, work on what you want to work on. Any work that you do is appreciated immensely by the maintainers of MDAnalysis.
