### ISSUE TITLE
Sync ResidueGroup and AtomGroup

### ISSUE THREAD

**Issue by yliu120** [MDAnalysis/mdanalysis#983]
ResidueGroup and AtomGroup should always sync their properties.

I am trying to reorder the residue ids after I merge several piece of PDBs together. I did a manual reordering using:
(See Python Code section)
### Expected behaviour

I will have a file with all residues in order.
### Actual behaviour

The residues id doesn't change.
### Code to reproduce the behaviour

Illustrate above already.

``` python
import MDAnalysis as mda

u = mda.Universe(top, trj)

index = 1
# self.system is the atom group that I would like to reorder
for res in self.system.residues:
     res.resid = index
     index += 1
self.system.atoms.write(....)

....

```
### Currently version of MDAnalysis:

(run `python -c "import MDAnalysis as mda; print(mda.__version__)"`)

The problem is when writing to a file, the write() function always looks at the atom.resid but not the ResidueGroup that I modified. I think this is a severe problem and needs to be redesigned and resolved. AtomGroup and ResidueGroup should share the residue's property. You CANT change something in one but the other guy doesn't realize that.

**Comment by kain88-de** [comment]
@richardjgowers is this fixed with issue-363?

**Comment by dotsdl** [comment]
@kain88-de yes, staleness between `ResidueGroup`s and `AtomGroup`s is one of the core things fixed by 363.

**Comment by mnmelo** [comment]
Do we have tests for this in the 363 testsuite?

**Comment by yliu120** [comment]
Issue 363 is not involved in MDAnalysis 0.15.0. Is that correct?

**Comment by mnmelo** [comment]
Not as of 0.15, no. It is an ongoing development branch the we hope will be fully merged into the main MDAnalysis trunk by release 0.16.

**Comment by yliu120** [comment]
OK. Since this is resolved in another development branch, I would not do a pull request to contribute to this. I currently just use a self-written hack to sync between the ResidueGroup and AtomGroup. I will update my code after 0.16 release. I close the issue.

BTW, do you guys use Gerrit(GerritHub) for code reviewing and submitting code? Then if you use this, people can easy contribute the code base and go through a review and add features to the next release.

**Comment by mnmelo** [comment]
There might be a couple of versions 0.15.1, 0.15.2, etc. before the one with the issue 363 fix, so if you have a solution at hand and would like to share, I'd say go ahead and open a pull request! It's always great to have people outside the core dev group contributing. We have a somewhat strict code quality standard, but don't worry, we'll point you in the right direction in the PR review.

We use GitHub itself for code review. This is not just an issue tracker. Check the tabs above where you have "Code" and "Pull Requests". You can even find the issue 363 branch we were talking about (though you'd be better off reading the discussion in #363 first). Or am I missing your point regarding the comparison to GerritHub?

**Comment by mnmelo** [comment]
(I admit I don't even know what GerritHub is...)

**Comment by yliu120** [comment]
Yeah, I know you guys conform to python pep8 style guide. That is not a problem at all. I worked at Google for a while and am pretty familiar with programming languages and style guides.

My current hack is just for my specific purpose. Under the current design, I would suggest to patch a method __sync_residues_with_atoms() and call it internally and lazily (whenever read and write access to the AtomGroup). I will read issue 363 to see whether you guys implement a new design.

Gerrit is an open source code review software developed at Google. It is very similar to Google's internal code review software but it is with Git. I think it is way better than the pull requests provided here at Github. People can setup a private Gerrit server or use GerritHub (an free service running Gerrit) and replicate repository there. You can directly push code to GerritHub and do code review easily there. GerritHub will sync back to GitHub automatically. However, GerritHub is running Gerrit with a outdated version.

**Comment by mnmelo** [comment]
Beware that issue 363 covers much more than just this, and is essentially a rewrite of the topology handling subsystem. 
Any short term fix like yours doesn't need to conform to what's being done for #363, so I'd say that if it works for you just open the PR and we can discuss the implementation in the PR review.

As to Gerrit(Hub) the discussion is perhaps better suited to the dev mailing list. Still, I don't quite get what it does that GitHub doesn't.

**Comment by richardjgowers** [comment]
@yliu120 this is exactly what the 363 branch is fixing.  In the mean time, you could do the following:

```python
res.resid += 1
for atom in res:
    atom.resid = res.resid

```
