### ISSUE TITLE
update citation in docs

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/mdanalysis#993]
Discussion MDAnalysis/MDAnalysis.github.io#27 lead to the new citation blurb: ask for both papers to be cited in academic work: http://www.mdanalysis.org/pages/citations/

We need to update the MDAnalysis docs in a similar way:
- [x] sphinx docs
- [x] README, meta data, etc

**Comment by richardjgowers** [comment]
Not 100% sure that all sphinx documentation has been checked for this change

**Comment by kain88-de** [comment]
Nope Sphinx docs need to be checked separately

**Comment by tylerjereddy** [comment]
I thought I had dealt with the few cases in the sphinx source -- I vaguely remember there only being 2 locations to update, but maybe I'm confused.

**Comment by orbeckst** [comment]
Double check the docs but I think a while back we did most of the rejiggling, including consolidating *all* references in *one place* in [references](http://www.mdanalysis.org/mdanalysis/documentation_pages/references.html).

Pages with MDA citations that immediately come to mind
- [x] http://www.mdanalysis.org/mdanalysis/
- [x] http://www.mdanalysis.org/mdanalysis/documentation_pages/references.html#citations-for-the-whole-mdanalysis-library
- [ ] package/[SUMMARY.rst](https://github.com/MDAnalysis/mdanalysis/blob/develop/package/SUMMARY.txt) (needs to be updated anyway... `easy_install` – really? ;-) )
- [ ] package/[README](https://github.com/MDAnalysis/mdanalysis/blob/develop/package/README) (also needs to be updated and actually slimmed down so that we are not repeating the same information everywhere)

I think these are all (I `git grep 'Michaud-Agrawal').

**Comment by kain88-de** [comment]
Those were updated in develop already before by someone else.

**Comment by orbeckst** [comment]
I think the sphinx docs are fine, the SUMMARY and README still need to be done.

**Comment by tylerjereddy** [comment]
For reference on the sphinx updates and README, but I guess those were superseded by @kain88-de : https://github.com/MDAnalysis/mdanalysis/pull/1001#issue-178953129

**Comment by orbeckst** [comment]
@tylerjereddy it seems that your edits for README / SUMMARY fell by the wayside, sorry. Would you mind re-doing them manually? If you make a PR with a branch in MDAnalysis I can also do some quick editing when I have a few minutes.
