### ISSUE TITLE
enable new *approved* PR feature on github for develop and master

### ISSUE THREAD

**Issue by kain88-de** [MDAnalysis/mdanalysis#994]
https://help.github.com/articles/about-pull-request-reviews/

should we activate that PR's to develop and master have to be marked as *approved* by at least one of us before the can be merged?

**Comment by richardjgowers** [comment]
Yes!

**Comment by kain88-de** [comment]
Done. For master I haven't enabled the review process but you now can't delete the branch anymore or force-push to it.
