### ISSUE TITLE
publish mdanalysis on conda-forge

### ISSUE THREAD

**Issue by kain88-de** [MDAnalysis/mdanalysis#995]
I was thinking if we should switch to publish our conda packages via conda-forge. I have recently published all the datreant packages on that channel (expect mdsynthesis). They are very welcome for new package contributions and it's also a lot easier to produce packages compatible for older linux versions since they are build on docker images based on a older centos.  On that channel we still have the rights to update our packages as usual. It also has the advantage that we build against multiple versions of numpy, currently users have to install the numpy version I used to build the package.

If everyone agrees I would slowly start to move the packages we maintain on our channel over to conda-forge.

As a little bonus this means I can also look into publishing 'nightly' builds of the development branch on our own channel. So people can beta test mdanalysis if they like.

**Comment by richardjgowers** [comment]
Looks like a good idea

**Comment by mnmelo** [comment]
Nightlies sound great! Also a easier way to direct bug posters to check whether the dev version fixes their woes.

**Comment by kain88-de** [comment]
Lets start with GridDataFormats

https://github.com/conda-forge/staged-recipes/pull/1862

Then we can quickler publish the next MDAnalysis release as well there.

**Comment by richardjgowers** [comment]
What needs doing for this to get nightlies to work?  Would be handy to let people try mmtf for example

**Comment by kain88-de** [comment]
Basically copying the conda-smithy tool. Then maybe figuring out a way to number the builds. I haven't looked into that at all yet. I'm also not sure how I can mark packages as unstable/beta on conda so that they aren't installed by default from our channel

**Comment by kain88-de** [comment]
Btw I planned to look seriously into nightlies after we publish 0.16

**Comment by HubLot** [comment]
Hi,

Is it still planned ? I would be really useful for python package which have MDAnalysis as a requirement. 
We have a python package with MDA as a dependency and we'll like to put it on conda-forge.

Thanks

**Comment by kain88-de** [comment]
I plan to publish the next release on conda-forge. Currently tempdir is missing as a dependency for 0.15.0. But this isn't a dependency for 0.16.0 anymore.

**Comment by hainm** [comment]
Fyi: thanks to manylinux python, my favorite distribution is now pip. :d

**Comment by orbeckst** [comment]
> Fyi: thanks to manylinux python, my favorite distribution is now pip. :d

That's a change of direction since #567 ;-)

**Comment by hainm** [comment]
@orbeckst technology changes quite fast :D

**Comment by kain88-de** [comment]
https://github.com/conda-forge/staged-recipes/pull/2715

MDAnalysis should pop up in about a day.

@HubLot What do you want to package on conda-forge?
